### PR TITLE
Fix `_partitions` `dtype` in `meta` for `DataFrame.set_index` and `DataFrame.sort_values`

### PR DESCRIPTION
**Pull request by hendrikmakait**
- [x] Fixes issue with `DataFrame.set_index()` that occurred in dask/distributed#8157
- [x] Closes dask/distributed#8165
- [x] Tests added / passed
- [x] Passes `pre-commit run --all-files`

### CODE REVIEW

**Comment by fjetter** [comment]
I can confirm this fixes the reproducer in https://github.com/dask/distributed/issues/8165

@hendrikmakait can we put a test in using the reproducer of #8165? I think that would be more meaningful than the low level asserts on the metadata. This will likely need to live in `test_distributed.py` and use P2P

**Comment by hendrikmakait** [comment]
> [](https://github.com/dask/distributed/issues/8165)
> 
> @hendrikmakait can we put a test in using the reproducer of #8165? I think that would be more meaningful than the low level asserts on the metadata. This will likely need to live in `test_distributed.py` and use P2P

Agreed, we can put an additional regression test in distributed. Note that dask/distributed#8157 includes an early check for the dtype that raises instead of silently failing.

**Review by phofl — APPROVED** [review]
Change looks good to me.

There is also a ``test_distributed.py`` file in dask/dask that you could use for the test

**Comment by phofl** [comment]
This might make a new release necessary. I think set_index and sort_values is broken generally on the current released version

**Comment by hendrikmakait** [comment]
> This might make a new release necessary. I think set_index and sort_values is broken generally on the current released version

+1, from what I see from the regression tests, these don't work with P2P.

**Comment by hendrikmakait** [comment]
> There is also a `test_distributed.py` file in dask/dask that you could use for the test

I'd rather have the regression tests live together with the actual P2P implementation.

**Comment by phofl** [comment]
cc @jrbourbeau for the new release

**Pull request merged**
