### PR TITLE
Concatenate meta along axis

### PR DESCRIPTION
**Pull request by jakirkham**
cc @pentschev

- [x] Tests added / passed
- [x] Passes `flake8 dask`

### CODE REVIEW

**Comment by jakirkham** [comment]
Planning on merging tomorrow if no comments.

**Comment by mrocklin** [comment]
+1 from me

I'm curious though, was this caused by some issue?  Is there something that we should test that was failing before?

**Comment by pentschev** [comment]
I double @mrocklin's comment entirely.

**Comment by jakirkham** [comment]
It came up when I was adding meta to `da.stack`. Not sure that there is a good way to test this in the case of `da.concatenate` (since the final shape will be filled with `0`s regardless).

**Comment by jakirkham** [comment]
Any other thoughts on this one?

**Comment by pentschev** [comment]
Not from me, you can merge at will.

**Pull request merged**
