### PR TITLE
Replace 'collections' key in unpack_collections with unique key

### LINKED ISSUE #3631: Incorrect result from computing when cache is enabled in 0.18.
Here is a reproducer:
```
(base) [yfeng1@waterfall tmp]$ cat test_nbkit.py 
import numpy
import dask
import dask.array as da
from dask.cache import Cache
print(dask.__version__)

with Cache(800000):
    a2 = da.from_array(numpy.ones((10, 3)) * 2, chunks=10000)
    a3 = da.from_array(numpy.ones((10, 3)) * 3, chunks=10000)

    print(a2.compute())
    print(a3.compute())

(base) [yfeng1@waterfall tmp]$ python test_nbkit.py 
0.18.0
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
```

0.18 has already hit anaconda.

### PR DESCRIPTION
**Pull request by rainwoodman**
Fixes #3631 

- [ ] Tests added / passed
- [ ] Passes `flake8 dask`

### CODE REVIEW

**Comment by rainwoodman** [comment]
It appears an item with the key 'collections' is put to the cache. If I clear that item in cache.py / _posttask, then the test case can pass.

I suspect this has to do with a change in the hash key calculation of a dask graph.

**Comment by rainwoodman** [comment]
It is the last item on the dsk graph that is keyed 'collections'.

**Comment by rainwoodman** [comment]
The 'collections' keyword is introduced in

https://github.com/dask/dask/commit/735061227b744750a8080646a3dcc16f13b90323

Looks like we need a better hashed name than 'collectioins'. Perhaps @jcrist or @mrocklin can comment?

**Comment by mrocklin** [comment]
Hrm, interesting.  Thanks for finding this @rainwoodman and for the minimal example.

I'm inclined to wait until @jcrist has a chance to comment on this, since I suspect he is the most familiar with the original decision.  However, I also think that he's out for the next couple days.  Is this blocking you from being productive, or would it be ok to wait a few days on this?  If it's blocking you then I'll find time to take a closer look.

**Comment by rainwoodman** [comment]
We can always pin to 0.17.x as a short term solution.

One of our user ran into this on Sunday. There could be some urgency as the current released version is silently producing wrong results.

**Comment by jcrist** [comment]
Ah, good catch. `collections` should be replaced in both locations with the same token generated by `uuid.uuid4().hex`.

**Comment by rainwoodman** [comment]
I see what you mean. I added the token.

In addition, I feel the test case shall be rewritten without using numpy / dask.array, though I am not sufficiently equipped to do this.

**Comment by mrocklin** [comment]
OK, merging this.  Thanks for finding, reporting, and fixing this @rainwoodman !

**Pull request merged**
