### PR TITLE
Test pandas 0.19.0 rc1

### PR DESCRIPTION
**Pull request by mrocklin**

### CODE REVIEW

**Comment by mrocklin** [comment]
Blocked on

https://github.com/pydata/pandas/issues/14354
https://github.com/dask/dask/issues/1616

**Comment by jcrist** [comment]
The only thing still failing is the timestamp indexing, which I believe is caused by pydata/pandas#14354. Do we want to fix it locally dependent on version, or wait for a pandas upstream fix?

**Comment by mrocklin** [comment]
I briefly tried doing the following:

```diff
diff --git a/dask/dataframe/indexing.py b/dask/dataframe/indexing.py
index cc1d8aa..0445091 100644
--- a/dask/dataframe/indexing.py
+++ b/dask/dataframe/indexing.py
@@ -96,10 +96,15 @@ def _maybe_partial_time_string(index, indexer, kind):
             stop = index._maybe_cast_slice_bound(indexer.stop, 'right', kind)
         else:
             stop = indexer.stop
+
+        if start > stop:
+            start, stop = stop, start
         return slice(start, stop)
 
     elif isinstance(indexer, pd.compat.string_types):
         start = index._maybe_cast_slice_bound(indexer, 'left', 'loc')
         stop = index._maybe_cast_slice_bound(indexer, 'right', 'loc')
+        if start > stop:
+            start, stop = stop, start
         return slice(start, stop)
     return indexer
```

Some problems persisted.  They might be resolvable though.

I'm somewhat in favor of patching this temporarily on the dask.dataframe side unless Pandas intends to release a bugfix patch quickly.

**Comment by jcrist** [comment]
I just pushed a simple fix for the indexing issue. I think this covers all the pandas 0.19.0 issues.

**Comment by mrocklin** [comment]
Grand!

**Comment by jcrist** [comment]
All tests passed. Merging.

**Comment by jreback** [comment]
ideally you should use the api functions

pd.types.api.is_categorical

**Pull request merged**
