### PR TITLE
Fix bug in ResourceProfiler resource cleanup

### LINKED ISSUE #1094: Profiler AssertionError: can only join a child process
I am finding when using the dask Profiler that I get errors like "AssertionError: can only join a child process" and this causes the IPython kernel to enter a state where it cannot be shut down from within Jupyter and needs to be killed manually. Example here: https://gist.github.com/alimanfoo/68f15f57c41db3df1652b54ff9c26a84

### PR DESCRIPTION
**Pull request by jcrist**
Previously a `__del__` method was on the `_Tracker` class, which would
join the tracker upon cleanup. This worked fine if the parent process gc
hit it first, but failed if the child process gc did (as child processes
can't join themselves). After this happens, if a new resource profiler
was created, then it would try to grab information from all of its
sibling processes, including the one that failed to cleanup properly.
Process information can't be gathered from a zombie process, so this
would error, leading to another zombie process, and so on...

The fix is to move the `__del__` cleanup to the `ResourceProfiler`
class, and also filter out zombie processes in the `_Tracker` class.

Fixes #1094.

### CODE REVIEW

**Comment by mrocklin** [comment]
cc @alimanfoo

**Comment by mrocklin** [comment]
Is there an easy easy to test this?

**Comment by jcrist** [comment]
Not that I could figure out with a few minutes thought. Could probably work something up though if desired.

**Comment by alimanfoo** [comment]
Thank you, I confirm this fixes the problem for me.

**Pull request merged**
