### PR TITLE
Update Dask copyright in the docs to 2024

### PR DESCRIPTION
**Pull request by krishanbhasin-px**
I noticed this in the footer of the docs. 

I'm entirely unsure whether the copyright is still Anaconda's though.

searching through the rest of the repo for copyright shows there are a few that are also out of date, and one that uses `datetime.now()` to keep it up to date. Happy to update all of them to that behaviour if preferred.

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

Admins can comment `ok to test` to allow this one PR to run or `add to allowlist` to allow all future PRs from the same author to run.

**Comment by phofl** [comment]
cc @mrocklin

**Comment by mrocklin** [comment]
I don't know that increasing the year in the the copyright has any value.  Does anyone have information on what this would help with?

**Comment by hendrikmakait** [comment]
We can probably drop the (end) years altogether: https://hynek.me/til/copyright-years/

**Comment by phofl** [comment]
the current thing looks very outdated to me, dropping seems like a good
solution

**Comment by krishanbhasin-px** [comment]
Not needed!

**Pull request closed without merging**
