### PR TITLE
fix tokenizing for when subindexing into numpy arrays

### PR DESCRIPTION
**Pull request by henrypinkard**
- [x] Tests added / passed
- [x] Passes `black dask` / `flake8 dask`

fix for #5350

### CODE REVIEW

**Comment by mrocklin** [comment]
Thanks for the PR @henrypinkard .  It looks like a related test is now failing in CI.  You might want to take a look.

**Comment by henrypinkard** [comment]
@mrocklin I spoke with Sebastian Berg (numpy developer) and made some changes which fixed the previous failing test.

I don't quite understand how the error with travis-ci is related to this PR though

**Comment by mrocklin** [comment]
> I don't quite understand how the error with travis-ci is related to this PR though

This is a linting failure.  See https://docs.dask.org/en/latest/develop.html#code-formatting

Or run the following:

```
pip install black flake8
black dask
flake8 dask
```

**Comment by henrypinkard** [comment]
got it, thanks!

**Comment by mrocklin** [comment]
Thanks @henrypinkard (and @seberg)!  This is in.

**Pull request merged**
