### PR TITLE
Fix style to comply with flake8

### PR DESCRIPTION
**Pull request by henriqueribeiro**
Minor style changes in order to reduce verbose when running flake8. 

I left some imports behind because I don't don't if they are needed/used.

### CODE REVIEW

**Comment by mrocklin** [comment]
Thanks for this @henriqueribeiro .  One open question here is if we should include these files in our CI test suite or not (currently we only test the `dask/` directory).  It looks like calling `flake8` on the entire repository adds an extra 30-40s (at least on my machine, probably more on travis).  My guess is that it is looking through non-py files as well?  I'm curious what's going on here.

**Comment by jcrist** [comment]
A different option would be to ignore certain paths in flake8 (set in `setup.cfg`). I'm a bit wary of the change to `versioneer.py`, since that was an auto-generated file that we didn't write. I assume you found this by running flake8 on the whole repo instead of just the `dask/` folder?

**Comment by jrbourbeau** [comment]
> I'm a bit wary of the change to versioneer.py, since that was an auto-generated file that we didn't write

I'm also in favor of avoiding changing auto-generated files like `versioneer.py`. @henriqueribeiro what do you think about modifying `setup.cfg` to exclude these files? Would require updating this line:

https://github.com/dask/dask/blob/0554dfbc541fc12c07b0d7611c67c71f5c6b47f4/setup.cfg#L7

**Comment by jrbourbeau** [comment]
Closing due to lack of response. Feel free to re-open if you'd like to pick this up again.

**Pull request closed without merging**
