### PR TITLE
Mark gpuCI CuPy test as flaky

### PR DESCRIPTION
**Pull request by pentschev**
There is a flaky CuPy test on gpuCI, initially noticed in https://github.com/dask/dask/pull/7982#issuecomment-891656571, but seen again in [a recent build](https://gpuci.gpuopenanalytics.com/job/dask/job/dask/job/prb/job/dask-prb/75/testReport/).

### CODE REVIEW

**Comment by pentschev** [comment]
@jrbourbeau the test in description has failed again. As we discussed yesterday, I'm marking it xfail since it's definitely flaky.

**Comment by pentschev** [comment]
From the gpuCI build, it looks like we can't xfail flaky tests "`[XPASS(strict)] Flaky test on gpuCI`", is that right @jrbourbeau ?

**Comment by jrbourbeau** [comment]
Ah, good point, we use strict `xfail`ing by default

https://github.com/dask/dask/blob/049b83b4d918af2cb3083e81df1c5b40e7e90d8f/setup.cfg#L53

Could you:

1. Open an issue for tracking the flaky test (for example like https://github.com/dask/dask/issues/7918)
2. Use the `pytest.mark.flaky` marker instead of `xfail` like

https://github.com/dask/dask/blob/d3bf07cec0b77c37b3ec1c8c30a3ae0cf00a993a/dask/tests/test_base.py#L1365
3. Include a comment  in the test which points to the issue

**Comment by pentschev** [comment]
@jrbourbeau thanks for the reply, I marked it flaky and opened https://github.com/dask/dask/issues/7996 to track it.

**Review by jrbourbeau — APPROVED** [review]
Thanks @pentschev!

**Pull request merged**
