### PR TITLE
Permit any integral type passed to repeat

### PR DESCRIPTION
**Pull request by jakirkham**
Permit any integral type to be passed to the `repeat` function.

### CODE REVIEW

**Comment by jcrist** [comment]
Looks like there's one in `tile` (a few lines down) too.

**Comment by jakirkham** [comment]
Ran into some seemingly unrelated test failures. Have opened issues with them and added links to the logs. Pushed a new commit here to restart the tests.

xref: https://github.com/dask/dask/issues/2372
xref: https://github.com/dask/dask/issues/2373

**Comment by jakirkham** [comment]
It appears `tile` is doing the [right]( https://github.com/dask/dask/pull/2371/files#diff-0dc21516366e88095fc3dbf2e9e62f9aR3847 ) thing or is there something else I'm missing.

That said, there are definitely a bunch of places in the code where values are tested against the `int` type when `Integral` would either be ok or a better choice. Though I don't want to go through and fix all of them at this time. Especially as many are in `dataframe`, which I don't really use so don't feel comfortable commenting on, or in internal code where there might be more going on.

**Comment by jcrist** [comment]
> It appears tile is doing the right thing or is there something else I'm missing?

Oop, you're right. Apparently I can't read today.

Thanks for the fix. Merging.

**Comment by jakirkham** [comment]
np. Thanks.

**Comment by jakirkham** [comment]
As a side note, Python 2 and Python 3 treat NumPy integral types differently. With Python 2, NumPy integral types are subclasses of `int` so they would have proceeded fine with the old code. However on Python 3 this is not the case. Instead only `numpy.int64` is a subclass of `int`. The rest of the NumPy integral types are not.

**Pull request merged**
