### PR TITLE
array: add constants

### PR DESCRIPTION
**Pull request by lucascolley**
Hi @jacobtomlinson, I've been testing `dask.array` in https://github.com/scipy/scipy/pull/20956 and another thing that would be useful is to add these constants. `newaxis` is just an alias for `None` for use in indexing.

Similarly to the dtypes, these are the same objects across NumPy, CuPy and Sparse. Should be good to add as well?

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

Admins can comment `ok to test` to allow this one PR to run or `add to allowlist` to allow all future PRs from the same author to run.

**Review by jacobtomlinson — COMMENTED** [review]
This seems fine to me.

If you look at [cupy as an example](https://github.com/cupy/cupy/blob/50f522128f8a6a5423df2ed96d3caed3f3f4ae21/cupy/__init__.py#L57-L62) it seems to expose more things from numpy than we are exposing here.

Does it make sense to make things consistent with `cupy` and expose the same things?

**Comment by lucascolley** [comment]
> Does it make sense to make things consistent with cupy and expose the same things?

Sure, I'll add in `euler_gamma` 👍

**Review by phofl — APPROVED** [review]

**Comment by phofl** [comment]
thx

**Pull request merged**
