### PR TITLE
Remove PY2 checks

### LINKED ISSUE #5388: Remove vestiges of Python 2
It has been a while since we dropped Python 2 and there doesn't seem to be catastropic blow-back.  To me, now seems like a safe time to clear out things like the compatibility file, six, and other Python 2 workarounds.  Note that we probably still want to keep things for PyPy and Windows compatibility.

### PR DESCRIPTION
**Pull request by jcrist**
- Cleans out our `compatibility` file of things we no longer need checks for
- Removes unnecessary python version checks for versions we no longer support
- Standardizes Python version checks to make them easier to grep for
- Removes unnecessary `__future__` imports
- Removes unnecessary `coding` headers from a few files
- A few linting cleanups

Fixes #5388.

### CODE REVIEW

**Comment by jcrist** [comment]
Since it's just deleting compatibility code, I think it'd be fine to merge in now. I've fixed the merge conflict that showed up.

**Comment by jcrist** [comment]
All green. Good to merge @jrbourbeau?

**Comment by mrocklin** [comment]
I have a slight preference to wait until after the release if that's OK.
It should only delay things by a day.

**Comment by jcrist** [comment]
Fine by me.

**Comment by jcrist** [comment]
Now that we've released, I'm going to merge this to avoid further merge conflicts. Thanks all

**Pull request merged**
