### PR TITLE
Dataframe now accepts dask arrays on columns assignemnt

### PR DESCRIPTION
**Pull request by henriqueribeiro**
- [x] Tests added / passed
- [x] Passes `black dask` / `flake8 dask`

Implementation of https://github.com/dask/dask/issues/5118

### CODE REVIEW

**Comment by martindurant** [comment]
Could you please provide an example of usage, here and in docstrings?

**Comment by martindurant** [comment]
Note that you appear to be failing on linting, make sure that flake and black are happy with the code, as per developer guidelines.

cc @TomAugspurger , if you want to comment

**Comment by TomAugspurger** [comment]
Can you add a small test for what happens when a Dask Array with a different number of partitions from `self` is assigned?

**Comment by henriqueribeiro** [comment]
Example

```python
import numpy as np
import pandas as pd
import dask.array as da
import dask.dataframe as dd

df = pd.DataFrame({"A": np.random.randint(0,10,50)})
ddf = dd.from_pandas(df, 2)

arr = np.array(np.random.randint(0,10,50))
darr = da.from_array(b, chunks=25)

ddf['B'] = darr
```

Do you agree with this example? Should I put it on the assign docstring?

**Comment by TomAugspurger** [comment]
@henriqueribeiro what's that an example of? That works fine since you have the same number of blocks / partitions (I think you have a typo. Should be `da.from_array(arr, chunks=...)`.

The issue is when you have a different number of chunks / partitions. That correctly raises

```python
    ...: darr = da.from_array(arr, chunks=10)
    ...: ddf['b'] = darr
    ...:
    ...:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-16-b65589e1de9e> in <module>
      9 arr = np.array(np.random.randint(0,10,50))
     10 darr = da.from_array(arr, chunks=10)
---> 11 ddf['b'] = darr
     12

~/sandbox/dask/dask/dataframe/core.py in __setitem__(self, key, value)
   3276             df = self.assign(**{k: value for k in key})
   3277         else:
-> 3278             df = self.assign(**{key: value})
   3279
   3280         self.dask = df.dask

~/sandbox/dask/dask/dataframe/core.py in assign(self, **kwargs)
   3527                         "Size mismatch ({0} != {1})".format(v.shape[0], len(self))
   3528                     )
-> 3529                 kwargs[k] = from_dask_array(v, index=self.index)
   3530
   3531         pairs = list(sum(kwargs.items(), ()))

~/sandbox/dask/dask/dataframe/io/io.py in from_dask_array(x, columns, index)
    437                 "({} != {})".format(index.npartitions, x.numblocks[0])
    438             )
--> 439             raise ValueError(msg)
    440         divisions = index.divisions
    441         to_merge.append(ensure_dict(index.dask))

ValueError: The index and array have different numbers of blocks. (2 != 5)

```

As far as documenting, the best place is probably `dataframe-indexing.rst`. You can add a new section on updating / setting data.

**Comment by henriqueribeiro** [comment]
It's an example that Martin Durant asked for. 

> The issue is when you have a different number of chunks / partitions. That correctly raises
I already added a test for that.

> As far as documenting, the best place is probably dataframe-indexing.rst. You can add a new section on updating / setting data.

Ok I will add it to the documentation.

**Comment by petioptrv** [comment]
@henriqueribeiro, are you still working on this issue. If not, mind if I complete the remaining couple of tasks?

**Comment by henriqueribeiro** [comment]
@petioptrv I had a few problems but I will take care of this soon.

**Comment by jrbourbeau** [comment]
Thanks for following up on this @henriqueribeiro! Will merge on green

**Pull request merged**
