### PR TITLE
Issue3762

### LINKED ISSUE #3762: ValueError exception when using da.stack() is too verbose.
I was attempting to stack 1-d arrays that were read in from a list of `hdf5` files and I blindly followed some boiler-plate [here (array-hdf5)](http://dask.pydata.org/en/latest/examples/array-hdf5.html#). I had ~10,000 arrays that I attempted to stack and the traceback was too verbose as it lists the size of each individual array that I was attempting to stack. 

It think the `Traceback` should  skip displaying the sizes of the individual arrays or handle them in a smarter way by return. Note that after _actually_ reading the [stack, concatenate, and block documentation](http://dask.pydata.org/en/latest/array-stack.html#) it was clear that I should be using `concatenate` and so it was really a user error on my part lol. 

Anyways, the problem still remains that the traceback is essentially unbounded. Plus, it's a simple fix as you only need to remove the  `"..Got %s", [x.shape for x in seq]"` portion of the `ValueError()` or maybe return only a list of the unique shapes tuples by doing `set([x.shape for x in seq])` or something along those lines.
 
MWE
``` python
import numpy as np
import dask.array as da

N=100
rand_size = np.random.randint(1e3,1e4,size=N) # N random array sizes
rand_arr = [np.random.rand(size) for size in rand_size] # N randomly sized arrays
da_rand_arr = [da.from_array(arr, chunks=1e2) for arr in rand_arr] # Convert them to dask arrays
x = da.stack(da_rand_arr, axis=0)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-1bc07fcfdcc1> in <module>()
      6 rand_arr = [np.random.rand(size) for size in rand_size] # N randomly sized arrays
      7 da_rand_arr = [da.from_array(arr, chunks=1e2) for arr in rand_arr] # Convert them to dask arrays
----> 8 x = da.stack(da_rand_arr, axis=0)

~/miniconda3/envs/astroconda3/lib/python3.6/site-packages/dask/array/core.py in stack(seq, axis)
   3637     if not all(x.shape == seq[0].shape for x in seq):
   3638         raise ValueError("Stacked arrays must have the same shape. Got %s",
-> 3639                          [x.shape for x in seq])
   3640 
   3641     ind = list(range(ndim))

ValueError: ('Stacked arrays must have the same shape. Got %s', [(3556,), (4444,), (3314,), (7310,), (9619,), (2346,), (3513,), (4840,), (7844,), (4226,), (5426,), (6735,), (9695,), (6998,), (9099,), (7529,), (3825,), (3720,), (8882,), (8107,), (2361,), (5933,), (7392,), (2839,), (8659,), (9984,), (5285,), (5445,), (8320,), (7674,), (8962,), (3500,), (7632,), (5624,), (3374,), (5849,), (1425,), (8344,), (1487,), (5457,), (6076,), (1608,), (1611,), (4152,), (3408,), (8743,), (5775,), (8244,), (1069,), (2922,), (9263,), (2802,), (6441,), (4198,), (3101,), (5776,), (2487,), (9003,), (2015,), (7582,), (5734,), (8715,), (8161,), (7697,), (7131,), (2417,), (4067,), (1188,), (1151,), (7045,), (5605,), (8532,), (5192,), (3520,), (2684,), (8015,), (2839,), (6987,), (5875,), (2619,), (5820,), (7123,), (9466,), (7467,), (6434,), (8581,), (6593,), (7352,), (5708,), (1217,), (8538,), (1286,), (8735,), (1031,), (8512,), (2643,), (3304,), (2847,), (2390,), (9384,)])

```

### PR DESCRIPTION
**Pull request by nmiles2718**
- [X] Tests added / passed
```console
(astroconda3) nmiles@nathan:dask$py.test dask/array/tests/test_array_core.py::test_stack_errs --verbose
============================================================== test session starts ===============================================================
platform darwin -- Python 3.6.5, pytest-3.6.2, py-1.5.3, pluggy-0.6.0 -- /Users/nmiles/miniconda3/envs/astroconda3/bin/python
cachedir: .pytest_cache
rootdir: /Users/nmiles/dask, inifile: setup.cfg
plugins: remotedata-0.3.0, openfiles-0.3.0, doctestplus-0.1.3, arraydiff-0.2
collected 1 item                                                                                                                                 

dask/array/tests/test_array_core.py::test_stack_errs PASSED                                                                                [100%]

============================================================ 1 passed in 0.19 seconds ============================================================
```
- [x] Passes `flake8 dask`

closes #3762

### CODE REVIEW

**Comment by mrocklin** [comment]
Thanks for submitting this @nmiles2718 !  

A couple points:

1.  We should add a test for this behavior.  Typically when testing exceptions I use the `pytest.raises` context manager

    ```python
    with pytest.raises(ValueError) as info:
        # do something bad
    assert 'informative message' in str(info.value)
    ```
2.  When we were talking at SciPy (I assume that this is the same person, please correct me if I'm wrong) we brought up the idea of suggesting that perhaps the user meant to use concatenate instead.  Good idea?  Bad idea?  Thoughts?

**Comment by nmiles2718** [comment]
@mrocklin yep, same person from SciPy! 

1. If you take look at #3762, I noted exactly this but was ensure if it was worth editing the pre-existing test. In short, `info.value` returns the entire error message whereas `str(info)` (which is currently used) only returns the error message up to the first `'\n'` character it finds. 

2. To be honest, I had intended to include that but just forgot because I went off on this tanget of "why is this assertion failing when it definitely shouldn't." I don't see any harm in omitting though. The only reason I ran into trouble with it was because I just quickly copy-and-pasting an example about reading datasets from `hdf5`. As soon as I saw the error it was pretty clear to me that I should be concatenating into a single array, as opposed to, stacking the arrays along a new dimension. The trouble was I had to scroll up pretty far to _actually_ see the error message because the shapes of all ~10,000 datasets I had attempted to stack were printed out.

**Comment by mrocklin** [comment]
> If you take look at #3762, I noted exactly this but was ensure if it was worth editing the pre-existing test. In short, info.value returns the entire error message whereas str(info) (which is currently used) only returns the error message up to the first '\n' character it finds.

The test suite previously didn't catch the project's poor behavior here.  We should add a test to ensure that this fix continues into the futue.  If someone were to revert your fix, they should get a failing test telling them what they've done that was wrong.  Would something like the following work?

```python
with pytest.raises(ValueError) as info:
    # bad thing
assert len(str(info.value)) < 200  # or something similar
```

**Comment by nmiles2718** [comment]
Ok, so what you're saying is that we should:

1. Maybe fix (all) the `assert` statement(s) to use `info.value` attribute rather than the overloaded `__str__()` method on the `ExceptionInfo` object?
2. Add an additional test so that moving forward no one gets away with using `str(info)` vs `info.value` for checking if something is in the actual error message?

**Comment by mrocklin** [comment]
Possibly.  For this PR all we need is a single test that tests that the error for da.stack is not absurdly long.  If there is a test within the test suite now that can be modified to accomplish this then yes, lets modify that (and only that).  Otherwise lets write a new test.  Hopefully this is something like a five-line addition to your current PR here.

**Comment by nmiles2718** [comment]
Ok sounds good. I'll just modify the existing test function [test_stack_errs()](https://github.com/dask/dask/blob/003962f61dc2c19e363ad723e9bb0ca406afd621/dask/array/tests/test_array_core.py#L3328) to check the length of the message. I'll have to increase the number of arrays used so that it will fail the tests if someone reverts the fix because my error message is longer than the one currently in master. Thankfully, the length of mine is roughly fixed and so I can just set that (plus some padding) to be the upper limit for the length of the error message. That way if they go back to printing the shapes of each individual array it will fail the length check.

**Comment by nmiles2718** [comment]
@mrocklin, not sure why it is failing now. Looking at the logs it seems to be an issue with the build timing out.

**Comment by mrocklin** [comment]
Looks good to me.  Merging.  Thanks @nmiles2718 !

**Pull request merged**
