### PR TITLE
Add lazy loader

### PR DESCRIPTION
**Pull request by jrmlhermitte**
Would it be appropriate to include an example of a lazy loader with dask?
I found such a feature useful and thought I'd share it in the examples.

thanks!

### CODE REVIEW

**Comment by mrocklin** [comment]
I wonder if we might instead point users towards dask.delayed and da.stack in cases like this.  Here is an example from a blogpost:

```python
import dask.array as da
from dask import delayed

imread = delayed(skimage.io.imread, pure=True)  # Lazy version of imread

urls = ['http://emdata.janelia.org/api/node/bf1/grayscale/raw/xy/2000_2000/1800_2300_%d' % i
        for i in range(10000)]  # A list of our URLs

lazy_values = [imread(url) for url in urls]     # Lazily evaluate imread on each url

arrays = [da.from_delayed(lazy_value,           # Construct a small Dask array
                          dtype=sample.dtype,   # for every lazy value
                          shape=sample.shape)
          for lazy_value in lazy_values]

stack = da.stack(arrays, axis=0)                # Stack all small Dask arrays into one
```

http://matthewrocklin.com/blog/work/2017/01/17/dask-images

Also, not particularly relevant for this example (which is more general), but you might want to look at `to_npy_stack` and `from_npy_stack`

**Comment by mrocklin** [comment]
I've pushed some proposed changes

**Comment by jrmlhermitte** [comment]
Thanks, I was not aware of `da.from_delayed`. This is a very useful example!
I like how you include both methods.
I just have one question and one comment:
- for the task graph, when supplying a list of args:
```py
        dsk = {(name, i, 0, 0): (func, (a,), (b,b2))}
```
implies
```py
func(a)(b, b2)
```
for example is that correct? (I tested example and it works)
- I just realized this example assumes the reader returns numpy arrays. It might be good that we add a mention of this. I have added this in the docstring.
- should we link your blog post as a reference for a more elaborate example?

If you have no comments I think this looks good to me. This would be very useful.

thanks for sharing all this information, very interesting!

**Comment by mrocklin** [comment]
See http://dask.pydata.org/en/latest/spec.html for information on the graph spec.  

(func, (a,), (b,b2)) converts to `func(a(), b(b2))` if a and b are both callables

**Comment by jrmlhermitte** [comment]
I should have checked the documentation again, silly question... I appreciate the answer.

**Comment by jrmlhermitte** [comment]
thanks!

**Pull request merged**
