### PR TITLE
add zstandard to compression.py

### PR DESCRIPTION
**Pull request by milkpowder101**
- [ ] Tests added / passed
- [ ] Passes `black dask` / `flake8 dask`

### CODE REVIEW

**Comment by mrocklin** [comment]
cc @martindurant

**Comment by martindurant** [comment]
What is the intended use of compressions like this? 

In https://github.com/dask/dask/pull/5064 we clarify the previous behaviour (which moved to [fsspec](https://github.com/intake/filesystem_spec/blob/master/fsspec/compression.py)) to use only compressed file-like objects (gzip, bz2, xz, zip), since the purpose is to interface with on-disc (or remote) files. Compression algorithms like snappy and zstd don't have canonical file representations.

Therefore, I would recommend, if anything, implementing a file-like interface using the zstd streaming reader/writer, and including that in fsspec. snappy also has a stream reader/writer that could be used to the same effect, with a little effort.

**Comment by milkpowder101** [comment]
Ah I see... I misunderstood

**Comment by martindurant** [comment]
@milkpowder101 , you were quite correct for the correct version of the code in master, but I suspect that the zstd compressor would have been unreachable anyway. Do you have any interest in implementing the zstd file-like in fsspec?

**Comment by mrocklin** [comment]
We also use compression for data on the wire and when writing temporary files to disk.  In these cases `zstd` might make a lot of sense.

**Comment by martindurant** [comment]
^ that would be in the serialization/framing of distributed?

**Comment by mrocklin** [comment]
Ah yes, we have separate code that handles this in distributed/protocol/compression.py, don't we.

**Pull request closed without merging**
