### PR TITLE
order: remove data task graph normalization

### PR DESCRIPTION
**Pull request by fjetter**
This normalization scheme was intended to remove "commonly shared dependencies/literals" from a graph and simplify the topology. These kinds of tasks often occur in xarray where the array task encodes an index.

I currently strongly believe that this section is never triggered in a realistic situation (at least not with a distributed scheduler)

The distributed scheduler is currently performing a transformation on every task that is "normalizing" the task, i.e. it ensures that it is certainly executable, i.e. after this conversion step `istask` will always return True for all values.

Since ordering is performed after this normalization step, this code section is de-facto currently dead. What is interesting (and important) is that the unit tests for dask order are not performing this kind of normalization and are covering graphs/topologies that exhibit this problematic structure and from what I can tell the code is now robust enough to no longer require this normalization 🎉 

I found this in https://github.com/dask/dask/pull/11248 since with https://github.com/dask/dask/pull/11248 this kind of normalization is no longer required and we can still distinguish literals from runnables.

It might make sense to revisit this normalization at some point but I'm currently rather glad to get rid of the deepcopy...

### CODE REVIEW

**Review by phofl — APPROVED** [review]
this looks good to me, but you certainly know much more about this part of the code than I do

**Comment by fjetter** [comment]
FWIW I ran a benchmark (left null) and there is no signal. There is one regression peak on the right side but I ran the jobs myself a couple of times and I couldn't reproduce.

image

**Comment by phofl** [comment]
So this is interesting. I was looking into https://github.com/dcherian/dask-demo/blob/main/nwm-climatology-cohorts.ipynb today. Dask-order is misbehaving for some reason here that it blocks the tree reduction until the very end which accumulates a lot of memory on the scheduler.

**Before this PR**

I only observed the problematic behaviour on a distributed cluster, Dask-order worked fine on a synchronous cluster.

**After this PR**

The problematic ordering behavior now also shows up on a synchronous cluster, so this PR impacted that case for some reason only on a sync cluster. 

reproducer:

```python
ds = xr.open_zarr(
    fsspec.get_mapper("s3://noaa-nwm-retrospective-2-1-zarr-pds/rtout.zarr", anon=True),
    consolidated=True,
)
subset = ds.zwattablrt.sel(time=slice("2001", "2002"))


result = subset.groupby("time.month").sum(method="map-reduce")
```

**Comment by dcherian** [comment]
FWIW my comment was about
```python
subset.chunk(time=TimeResampler("ME")).groupby("time.month").mean()
```

but if you can reduce the memory usage of the simple "map-reduce" that would be awesome

**Comment by phofl** [comment]
the map reduce should be able to run equivalently to the cohorts implementation (mostly), but Dask order misbehaves in a way that the final step of tree-reduction isn't triggered until everything else is through (the cohorts implementation does not have this problem). 

I didn't even get to the rechunking because that one already tripped me pretty badly :)

**Comment by phofl** [comment]
@fjetter and I talked offline and decided to revert this one

**Pull request merged**
