### PR TITLE
add cov and corr for rolling

### PR DESCRIPTION
**Pull request by sjyMystery**
We strongly suggest that the cov and corr is required.

- [ ] Tests added / passed
- [ ] Passes `black dask` / `flake8 dask`

### CODE REVIEW

**Comment by martindurant** [comment]
The methods appear both to be called `min`?
In any case, I would certainly add tests to ensure that these achieve the right results.

**Comment by jrbourbeau** [comment]
Also, note that there's an existing PR (#5154) which adds rolling `cov`

**Comment by martindurant** [comment]
@sjyMystery , we appreciate you making an effort to provide useful code. Please let us know your next steps following the couple of comments above.

**Comment by jrbourbeau** [comment]
Note that #5154 has been merged, so there is now support for rolling `cov`. Perhaps that will help pave the way for adding rolling `corr`

**Comment by TomAugspurger** [comment]
@sjyMystery are you interested in working on this?

**Comment by TomAugspurger** [comment]
Checking in @sjyMystery. Still interested in working on this?

**Comment by jrbourbeau** [comment]
Closing due to lack of response. @sjyMystery please feel free to re-open if you'd like to pick this up again.

**Pull request closed without merging**
