### PR TITLE
fix #4579

### LINKED ISSUE #4579: Accept `dtype` in RandomState.randint
NumPy 1.11 added an optional `dtype` argument to RandomState.randint

```
dtype : dtype, optional
    Desired dtype of the result. All dtypes are determined by their
    name, i.e., 'int64', 'int', etc, so byteorder is not available
    and a specific precision may have different C types depending
    on the platform. The default value is 'np.int'.

    .. versionadded:: 1.11.0
```

dask-ml would like to make use of that.

In https://github.com/dask/dask/blob/master/dask/array/random.py#L334, we may be able to add a `dtype='l'` argument, and pass that through to `self._wrap` A PR doing that and adding tests would be most welcome.

### PR DESCRIPTION
**Pull request by HSR05**
- [ ] Tests added / passed
- [ ] Passes `flake8 dask`

### CODE REVIEW

**Comment by HSR05** [comment]
> 
> 
> Thanks for the PR @HSR05! Looking forward to having this added
> 
> Could you please add a test to `dask/array/tests/test_random.py` to ensure that the new `dtype` keyword is behaving as expected. Also, it looks like there are some code linting issues causing the CI builds to fail. You can render these locally by running `flake8 dask`.

@jrbourbeau I'll work on adding the tests. Can you guide me for adding the tests? I will be more than thankful. 👍

**Comment by mrocklin** [comment]
@HSR05 you should read through http://docs.dask.org/en/latest/develop.html which explains in detail how we test.  If you have any particular questions then please ask them.  

Asking for general guidance is less likely to be successful.

**Comment by HSR05** [comment]
> 
> 
> @HSR05 you should read through http://docs.dask.org/en/latest/develop.html which explains in detail how we test. If you have any particular questions then please ask them.
> 
> Asking for general guidance is less likely to be successful.

Thankyou for an heads up. I'll go through that.  👍

**Comment by jrbourbeau** [comment]
Just wanted to check in here @HSR05. Are there any issues you've run into?

**Comment by quasiben** [comment]
@HSR05 wanted to gently ping again and see if you were interested finishing up this PR ?

**Comment by mrocklin** [comment]
Closing.  I've handled this elsewhere.

**Pull request closed without merging**
