### PR TITLE
IO dataframe : extra engine kwargs for sqlalchemy #2975

### PR DESCRIPTION
**Pull request by garaud**
- [X] Tests added / passed
- [X] Passes `flake8 dask`

The sqlalchemy engine parameter `echo` works well when you run the test `dataframe/io/sql/tests` with the `-s` option. You can see all SQL queries in the sqlalchemy logger. No clever idea to test this part.

### CODE REVIEW

**Comment by mrocklin** [comment]
cc @martindurant

**Comment by martindurant** [comment]
You probably want to [capture](https://docs.pytest.org/en/latest/capture.html#accessing-captured-output-from-a-test-function) the output in the test, to show that `echo` is doing the right thing.

**Comment by garaud** [comment]
Good idea. For now, the output is quite verbose and you have the timestamp from the logger, e.g.:

```
2018-11-08 15:38:14,347 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2018-11-08 15:38:14,347 INFO sqlalchemy.engine.base.Engine ()
2018-11-08 15:38:14,348 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2018-11-08 15:38:14,348 INFO sqlalchemy.engine.base.Engine ()
2018-11-08 15:38:14,348 INFO sqlalchemy.engine.base.Engine PRAGMA table_info("test")
```

I should parse the content of the stdout in order to skip the timestamp part.

**Comment by martindurant** [comment]
Am I right in thinking, that with `echo` you get those lines, but without it you do not? They it would be enough to try the two options and assert that you see "SELECT" in the output of the former but not in the latter.

**Comment by garaud** [comment]
@martindurant  You're thinking right. Without this `echo` option, you don't get this stdout from the sqlalchemy logger.

>They it would be enough to try the two options and assert that you see "SELECT" in the output of the former but not in the latter.

Your idea is smarter and easier than mine!

**Comment by garaud** [comment]
one more pushed commit

**Comment by martindurant** [comment]
Thanks for the changes. 
+1 when this goes green.

**Comment by garaud** [comment]
Hmmm, some trouble with the `out` attribute of the returned object from `capsys.readouterr()`. I develop on a Debian with py36 and I don't have this exception. I'll try to find a workaround.

**Comment by garaud** [comment]
And I have `pytest-3.10.0` instead of the 3.1.1 version used by Travis.

**Comment by mrocklin** [comment]
It looks like you have a failing test here

```
____________________ test_extra_connection_engine_keywords _____________________
[gw2] linux -- Python 3.6.6 /home/travis/miniconda/envs/test-environment/bin/python
capsys = <_pytest.capture.CaptureFixture object at 0x7fdbcc871160>
db = 'sqlite:////tmp/tmprydi1cfm.'
    def test_extra_connection_engine_keywords(capsys, db):
        data = read_sql_table('test', db, npartitions=2, index_col='number', engine_kwargs={'echo': False}
                              ).compute()
        # no captured message from the stdout with the echo=False parameter (this is the default)
>       assert "SELECT" not in capsys.readouterr().out
E       AttributeError: 'tuple' object has no attribute 'out'
```

**Comment by garaud** [comment]
I push a slightly modified version of the last commit. This was due to a different version of pytest. The tests should pass with `pytest==3.1.1`

**Comment by mrocklin** [comment]
(we would also welcome an update to our version of pytest on CI, though that would probably be best in a separate PR)

**Comment by martindurant** [comment]
Will this also pass with other versions of pytest, for the future?

**Comment by garaud** [comment]
> (we would also welcome an update to our version of pytest on CI, though that would probably be best in a separate PR)

Good idea. For now, I'm not very comfortable with the CI configuration but I'll take a look. 


> Will this also pass with other versions of pytest, for the future?

Yes :slightly_smiling_face: I ran `pytest==3.10` on the latest version and the test passes.

**Comment by mrocklin** [comment]
Merging this in.  Thanks @garaud for the contribution and @martindurant for the review.

I also notice that this is your first contribution to this repository @garaud .  Welcome!

**Comment by garaud** [comment]
Thank you for the review and your welcoming message! The first but not the last (I hope) :slightly_smiling_face:

**Pull request merged**
