### PR TITLE
Update task graphs in optimize docs

### LINKED ISSUE #5925: Visualize output in optimization docs doesn't display function names.
I just tried to follow the example in https://docs.dask.org/en/latest/optimize.html:

```python
import dask

def print_and_return(string):
    print(string)
    return string

def format_str(count, val, nwords):
    return (f'word list has {count} occurrences of '
            f'{val}, out of {nwords} words')

dsk = {'words': 'apple orange apple pear orange pear pear',
       'nwords': (len, (str.split, 'words')),
       'val1': 'orange',
       'val2': 'apple',
       'val3': 'pear',
       'count1': (str.count, 'words', 'val1'),
       'count2': (str.count, 'words', 'val2'),
       'count3': (str.count, 'words', 'val3'),
       'out1': (format_str, 'count1', 'val1', 'nwords'),
       'out2': (format_str, 'count2', 'val2', 'nwords'),
       'out3': (format_str, 'count3', 'val3', 'nwords'),
       'print1': (print_and_return, 'out1'),
       'print2': (print_and_return, 'out2'),
       'print3': (print_and_return, 'out3')}

dask.visualize(dsk)
```
And unlike in the docs, the output didn't have any function names: 

image

### PR DESCRIPTION
**Pull request by jsignell**
Closes #5925 

- [ ] Tests added / passed
- [ ] Passes `black dask` / `flake8 dask`

I'm not sure that this is actually an improvement. The original figures made it more clear what was going on. Maybe there should be a kwarg in `visualize` that allows users to toggle on the function names. 

Here are some examples of the changes:

image

image

### CODE REVIEW

**Comment by quasiben** [comment]
Yeah, the boxes just hanging out don't really help convey much

**Comment by jsignell** [comment]
I agree. But I think it is weird to have visualizations in the docs that you can't actually make, soI guess I am proposing that there should be a change in `visualize`

**Comment by quasiben** [comment]
Adding names optionally back in make sense to me.  @jrbourbeau do you recall why they were removed ?

**Comment by jsignell** [comment]
This is the most I've found so far: https://github.com/dask/dask/issues/4767#issuecomment-488664657

**Comment by quasiben** [comment]
> This is the most I've found so far: #4767 (comment)

@jsignell, right. 

I would say it looks like they can be useful and annoying so have an option for them seems like a good idea

**Comment by TomAugspurger** [comment]
https://github.com/dask/dask/issues/4146 and https://github.com/dask/dask/pull/4160 are relevant I think.

**Comment by jsignell** [comment]
Thanks Tom, from those links it seems like the decision was driven by a desire to remove redundant information. But seems like there wouldn't be opposition to adding a kwarg (off by default) to include the names. There is at least one comment where people express some confusion around this: https://github.com/dask/dask/pull/4160#issuecomment-443788638

**Comment by jsignell** [comment]
Just for my own self #4288 is another related issue.

**Comment by TomAugspurger** [comment]
This should be unblocked now that #5976 is in.

**Comment by jsignell** [comment]
Oh thanks for reminding me :)

**Comment by TomAugspurger** [comment]
Let us know when you think this is good to go.

**Comment by jsignell** [comment]
It's good to go!

**Comment by TomAugspurger** [comment]
Thanks!

**Pull request merged**
