### PR TITLE
DOC: Gen2 access with RBAC/ACL (security principal)

### LINKED ISSUE #8711: Add support for ADLS Gen2 with Service Principal (client_id/client_secret)
Hi daskers,

The documentation on [Microsoft Azure Storage](https://docs.dask.org/en/stable/how-to/connect-to-remote-data.html#microsoft-azure-storage) reads:
> Microsoft Azure Storage is comprised of Data Lake Storage (Gen1) and Blob Storage (Gen2). These are identified by the protocol identifiers adl and abfs, respectively, provided by the [adlfs](https://github.com/dask/adlfs) back-end.
> Authentication for adl requires tenant_id, client_id and client_secret in the storage_options dictionary.
> Authentication for abfs requires account_name and account_key in storage_options.

We use ADLS Gen2 (= Azure Blob Storage with HNS enabled). Azure has four different [access control models](https://docs.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-access-control-model), and we follow their [security recommendations](https://docs.microsoft.com/en-us/azure/storage/blobs/security-recommendations#identity-and-access-management) on: 
- "Use Azure Active Directory (Azure AD) to authorize access to blob data" - I.e. use service account `client_id`/`client_secret` via the ACL or RBAC models.
- "The principal of least privilege" - I.e. don't use `account_key`, which is basically root to the entire resource.
- "Disallow Shared Key authorization" - Again, don't `use account_key`.

So the Dask documentation goes directly against best security practices (and even leads less-experiences user in the direction of insecure setups).
Is this an actual limitation in Dask or adlfs? Or should the documentation be improved?

### PR DESCRIPTION
**Pull request by th0ger**
- [x] Closes #8711
- [x] Tests added / passed
- [x] Passes `pre-commit run --all-files`

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Review by jrbourbeau — COMMENTED** [review]
Thanks @th0ger

cc @martindurant @hayesgb for visibility

**Comment by jsignell** [comment]
ok to test

**Comment by martindurant** [comment]
Since this is supported in adlfs, I would expect no problems here.

**Comment by th0ger** [comment]
Seems ci agent had some issues.

**Comment by jsignell** [comment]
I forgot it was a docs change, so we can safely skip the tests. This looks fine to me! Thanks @th0ger

**Pull request merged**
