### PR TITLE
Avoid converting non-strings to arrow strings for read_parquet

### PR DESCRIPTION
**Pull request by phofl**
- [x] ref #10631
- [x] Tests added / passed
- [x] Passes `pre-commit run --all-files`

This disables the conversion for read_parquet (unfortunately also for fast parquet).

This is a minimal solution for a problem that we can solve with dask-expr and the pandas option infer_string in the future. This is aimed at solving the biggest pain for most users out there without too much effort on our side.
cc @fjetter

### CODE REVIEW

**Comment by mrocklin** [comment]
(non-blocking comment though)

**Comment by phofl** [comment]
I can do this as a follow up

**Comment by fjetter** [comment]
IIUC our type mapper is already doing the right thing for strings, isn't it?

**Review by fjetter — APPROVED** [review]

**Comment by phofl** [comment]
Yes I think matt is referring to dates getting cast to object instead of something more sensible like datetime64

**Comment by mrocklin** [comment]
And decimals and others I suspect.  There are a variety of types that we currently convert to strings that we shouldn't be.  It's probably easy to fix that problem by converting them to something more sensible, like decimal->float or decimal->pyarrow-decimal rather than decimal->string[pyarrow]

**Comment by phofl** [comment]
We are not casting them to strings anymore, we are now storing them as objects. Casting them with the types mapper is not supported out of the box, but we could cast them manually if we want to do this. We can also keep them as arrow backed objects, that would be the easiest solution

**Comment by mrocklin** [comment]
> We can also keep them as arrow backed objects, that would be the easiest solution

That seems better to me than object dtypes.  It also is maybe a good low-stakes test of arrow dtypes for us.

**Pull request merged**
