### PR TITLE
Test type promotions with da.where

### PR DESCRIPTION
**Pull request by jakirkham**
Make sure that Dask's Array `where` promotes types in a correct way when compared to NumPy's `where`.

### CODE REVIEW

**Comment by jakirkham** [comment]
This passes. Not sure if we still want it or not though.

**Comment by jcrist** [comment]
IMO the `test_where_scalar_dtype` test added in #2549 is sufficient.

**Comment by mrocklin** [comment]
What are we doing here.  Merging or closing?

**Comment by jakirkham** [comment]
I'm ok with either.

TBH it may be worth applying a similar testing strategy to [`result_type`]( https://github.com/dask/dask/blob/6d2889be4b9996036cdf437efc528bcb3b8ae82b/dask/array/core.py#L515 ). That may obviate the need for this level of thoroughness with `where`.

**Comment by jcrist** [comment]
Ok. I'm going to close this for now, we can add tests later if deemed necessary. Thanks @jakirkham.

**Comment by jakirkham** [comment]
SGTM. I'll try to look into exposing `result_type` in the API later. That should be a good function for this level of testing.

**Comment by jakirkham** [comment]
As a note, `result_type` was added in PR ( https://github.com/dask/dask/pull/2571 ) with similar tests.

**Comment by jakirkham** [comment]
As a note, `result_type` was added in PR ( https://github.com/dask/dask/pull/2549 ) and similar type tests were added in PR ( https://github.com/dask/dask/pull/2571 ).

**Pull request closed without merging**
