### PR TITLE
add correlation calculation and add test

### PR DESCRIPTION
**Pull request by quasiben**
- [x] Tests added / passed
- [x] Passes `black dask` / `flake8 dask`

PR resolves https://github.com/dask/dask/issues/4828

### CODE REVIEW

**Comment by jakirkham** [comment]
@TomAugspurger, would you have a chance to review?

**Comment by TomAugspurger** [comment]
Looks reasonable @quasiben. Can you add corr to the DataFrame API docs?

**Comment by quasiben** [comment]
Yup yup, should've included that before.

**Comment by jakirkham** [comment]
@TomAugspurger, could you please take another look?

**Comment by jangorecki** [comment]
could anyone explain (1 sentence is enough) how the tests are being defined in this PR (or dask)? looking at `test_groupby.py` I don't see any example that would correspond to my expected usage.

**Comment by quasiben** [comment]
Agg Funcs (sum/mean/min/co) are defined here: https://github.com/dask/dask/blob/2acc4c7f3ba16bdd250490243b433791cadab0bd/dask/dataframe/tests/test_groupby.py#L19-L41

This PR add `corr` to that list.  The list is used in many of the functions agg test functions like:

https://github.com/dask/dask/blob/2acc4c7f3ba16bdd250490243b433791cadab0bd/dask/dataframe/tests/test_groupby.py#L1176

**Comment by TomAugspurger** [comment]
Thanks @quasiben!

**Pull request merged**
