### PR TITLE
Remove duplicated `encoding` kwarg in docstring for `to_json`

### PR DESCRIPTION
**Pull request by SultanOrazbayev**
- [x] No related issue found
- [x] No tests added
- [ ] Passes `pre-commit run --all-files`

Currently this fails due to an issue with another docstring (dd.to_sql), which is being fixed in https://github.com/dask/dask/issues/9799

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

Admins can comment `ok to test` to allow this one PR to run or `add to allowlist` to allow all future PRs from the same author to run.

**Comment by ncclementi** [comment]
add to allow list

**Comment by SultanOrazbayev** [comment]
Thank you for checking, @ncclementi ! It is, but there is an error triggered elsewhere in the docs (not by these changes), so I was waiting for those to be fixed (https://github.com/dask/dask/pull/9809). Looks like https://github.com/dask/dask/pull/9809 is merged, so I will try again now.

**Comment by SultanOrazbayev** [comment]
There are a few tests still failing, but they are unrelated to this PR.

**Review by jrbourbeau — APPROVED** [review]
Thanks @SultanOrazbayev! This is in

**Pull request merged**
