### PR TITLE
add workaround for memory leaks in bag generators (fixes #5189)

### LINKED ISSUE #5189: Dask.bag with partition_size>1 has potential memory issues
## Abstract
Linear fused parts in dask.bag clean intermediate results too late, leading to potential memory issues.

### Code

```python
import weakref

import dask.bag as db
import dask.config

import objgraph

# to simplify debugging
dask.config.set(scheduler="synchronous")

# global weakref so we can feed objects into objgraph for analysis
memory = weakref.WeakValueDictionary()


class C:
    def __init__(self, i):
        print(f"init: {i}")
        self.i = i

    def __del__(self):
        print(f"del: {self.i}")


def f1(i):
    print(f"f1: {i}")
    obj = C(i)
    memory[i] = obj
    return obj


def f2(obj):
    print(f"f2: {obj.i}")
    return obj.i


def f3(i):
    print(f"f3: {i}")
    if i in memory:
        objgraph.show_backrefs(memory[i], filename=f'refs{i}.png', shortnames=False, max_depth=20)
    return i


bag = db.from_sequence(range(4), partition_size=2).map(f1).map(f2).map(f3).sum()
bag.visualize(optimize_graph=False, filename="graph.png")
bag.visualize(optimize_graph=True, filename="graph_opt.png")
bag.compute()
```

### Compute Graph
The compute graph *without fusing* looks like this:
graph

The optimized graph (with linear fusing) looks like this:
graph_opt

Notice that the chain `f1->f2->f3` is fused into a single task (along with the per-partition aggregation).

### Actual Output
```
f1: 0
init: 0
f2: 0
f3: 0
f1: 1
init: 1
f2: 1
f3: 1
del: 0
del: 1
f1: 2
init: 2
f2: 2
f3: 2
f1: 3
init: 3
f2: 3
f3: 3
del: 2
del: 3
```

Notice that the payload objects that are created in `f1` and destroyed in `f2` are kept until the whole partition is finished.

### Expected Output
```
f1: 0
init: 0
f2: 0
del: 0
f3: 0
f1: 1
init: 1
f2: 1
del: 1
f3: 1
f1: 2
init: 2
f2: 2
del: 2
f3: 2
f1: 3
init: 3
f2: 3
del: 3
f3: 3
```

## Reference Graphs
`i=0`:
refs0

`i=1`:
refs1

### PR DESCRIPTION
**Pull request by crepererum**
- [X] Tests added / passed
- [X] Passes `black dask` / `flake8 dask`

Fixes #5189 
This is an alternative to #5201

### CODE REVIEW

**Comment by martindurant** [comment]
The string of numba errors that appeared here are not likely to be related.

@jcrist , do you have time to review this, or perhaps suggest someone?

**Comment by jcrist** [comment]
Apologies for the delayed response here. The intent/approach here seems good to me, but I think we can make the implementation simpler. Mind if I push a commit to this PR?

**Comment by crepererum** [comment]
> Mind if I push a commit to this PR?

Go ahead.

**Comment by jcrist** [comment]
I've pushed a commit simplifying the implementation. This also builds a simpler task representation, which should (slightly) improve performance of any graph operations.

cc @crepererum for a quick review.

**Comment by crepererum** [comment]
OK, that looks cleaner. Thanks a lot!

> This also builds a simpler task representation, which should (slightly) improve performance of any graph operations.

For personal interest and if you have time, can you elaborate on that part a little bit?

**Comment by jcrist** [comment]
> For personal interest and if you have time, can you elaborate on that part a little bit?

Every nested potential sub-task (lists and tuples starting with a callable) in a task (a value in the graph) is traversed during graph optimization and execution a couple times. While these traversals usually are negligible compared to the cost of the actual computation, they do still take time and memory. Flattening the task structure a bit can help speed up optimization passes and execution time as the scheduler has less to do.

**Pull request merged**
