### PR TITLE
Remove `sqlachemy` 1.3 compatibility

### PR DESCRIPTION
**Pull request by McToel**
After I made dask compatible with Sqlachemy 1.4, it is now finally time to drop support for version 1.3. Pandas has dropped the support a long time ago, so dask does not work with Sqlalchemy 1.3 anyways.

- [ ] Closes #xxxx
- [x] Tests added / passed

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

Admins can comment `ok to test` to allow this one PR to run or `add to allowlist` to allow all future PRs from the same author to run.

**Comment by McToel** [comment]
Ok I found out that my local flake8 has some config problem, so it failed for some other weird reason. The problem is fixed now.

**Comment by McToel** [comment]
Might someone take a look at this? This is way overtime and should have been done many months ago.

**Review by jrbourbeau — COMMENTED** [review]
Thanks @McToel. Apologies for the delayed response. 

The code changes here look good. For my own understanding, when did `pandas` drop support for `sqlalchemy<1.4`? I ask because Dask currently supports older versions of `pandas` (back to 1.0) and I'm wondering if it makes sense to keep this functionality around until we increase the minimum supported `pandas` version to one that's more recent than when `sqlalchemy<1.4` was dropped. 

Also cc @martindurant who was involved with reviewing https://github.com/dask/dask/pull/8158

**Comment by McToel** [comment]
Pandas dropped support for `sqllachemy<1.4` in [version 1.4](https://pandas.pydata.org/docs/whatsnew/v1.4.0.html#backwards-incompatible-api-changes). This was on January 22, 2022.
With that in mind, it might actually make sense to keep `sqllachemy<1.4` compatibility for now. How and when does dask decide to drop support for old versions of pandas?

**Comment by mrocklin** [comment]
FWIW I'd be happy being more aggressive tha pandas when dropping libraries.  I also think that people who want to use old versions of pandas could also use old versions of Dask in this case.

**Review by jrbourbeau — COMMENTED** [review]
Thanks @McToel, that's good to know. 

> How and when does dask decide to drop support for old versions of pandas?

Historically we've continued to maintain support for "recent" versions of `pandas` (no strict policy here, but usually something like <12-18 months old) or until there's a maintenance burden associated with continuing to support an older version of `pandas`.

In this case, I don't fee strongly either way. The code here that supports `sqlachemy<1.4` seems to be working and I don't recall folks opening up issues that would require changes to this portion of the codebase (i.e. not currently a maintenance burden). At the same time, we've had deprecation warnings in place for almost a year in Dask -- so I think removing support is also okay. Given that you've already taken the time to push this PR up, I'm inclined to go ahead and just merge this in. Will do so in the next 24 hours if there aren't any objections.

**Review by jrbourbeau — APPROVED** [review]
Thanks @McToel -- this is in

**Pull request merged**
