### PR TITLE
bug fix for issue  #5439

### PR DESCRIPTION
**Pull request by tinaok**
Hi , this is my first time making PR to Dask, 
I did not add any tests, but I will explain how it improved the chunk size in the issue #5439

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Thanks @tinaok. Some of the CI failures will be resolved if you use our formatters: https://docs.dask.org/en/latest/develop.html#code-formatting

Can you confirm: Does the issue only arise when some of the `axes` are 'auto'? So it's only when you're mixing explicit sizes and 'auto'? A test demonstrating that would be nice to have.

**Comment by tinaok** [comment]
thank you @TomAugspurger 
I followed your suggestion and did formatting using black and flake8.

to respond your question;
I encounter this problem when I use 3 dimension shape, specifying all 3 dimension chunk size3 as 'auto'.

**Comment by TomAugspurger** [comment]
Thanks! It seems like there are some failures on our existing tests. Do you see them locally with `pytest dask/array/tests/test_array_core.py`?

Looking at the first one

```python
    def test_normalize_chunks_tuples_of_tuples():
        result = normalize_chunks(((2, 3, 5), "auto"), (10, 10), limit=10, dtype=np.uint8)
        expected = ((2, 3, 5), (2, 2, 2, 2, 2))
>       assert result == expected

E       assert ((2, 3, 5), (...1, 1, 1, ...)) == ((2, 3, 5), (2, 2, 2, 2, 2))

E         At index 1 diff: (1, 1, 1, 1, 1, 1, 1, 1, 1, 1) != (2, 2, 2, 2, 2)

E         Use -v to get the full diff
```

It seems like the behavior on master is what we want. The block with `5` rows in it is the largest, and there's 1 byte per item, so we can have at most 2 columns in the output, which is a chunksize of 2. On your PR it's choosing a chunksize of 1.

Haven't looked at the other tests yet.

**Comment by tinaok** [comment]
hi @TomAugspurger  I found a bug from some limes before my modification; it was introducing tuple in a chunk[I],  there was a ',' too much.  I took that out to make my modification works,
Lets see how checks works ok with that...

**Comment by jsignell** [comment]
I'm going to close this PR since it's pretty stale, but if you ever want to pick this work back up and need a hand @tinaok please feel free to ping me.

**Pull request closed without merging**
