### PR TITLE
Allow dd.map_partitions to not enforce meta

### PR DESCRIPTION
**Pull request by mrocklin**
- [ ] Tests added / passed
- [ ] Passes `black dask` / `flake8 dask`

### CODE REVIEW

**Comment by mrocklin** [comment]
@TomAugspurger what are your thoughts on this?  Currently we use `apply_and_enforce` everywhere, which is making it hard to reason about the graph (for RAPIDS we're trying to add an `inplace=True` option to drop when safe).

For operations that we define I would like to stop the enforcement, mostly to make the graph cleaner.  Any thoughts or concerns?

**Comment by TomAugspurger** [comment]
My immediate reaction is that we shouldn't add a private keyword to a public API like this. If this is the right way to achieve the goal, then I'd prefer to have `map_partitions` be something like

```python

def _map_partitions(func, *args, meta=no_default, transform_divisions=True, enforce=True, **kwargs):
    # the actual implementation

def map_partitions(func, *args, meta=no_default, transform_divisions=True, **kwargs):
    return _map_partitions(func, *args, meta=meta, transform_divisions=True, enforce=True, **kwargs)
```

In terms of the actual changes, I recall a dissatisfaction with `_apply_and_enforce`, though I don't recall the details at the moment.

**Comment by mrocklin** [comment]
How about a public but suitably long keyword, like `apply_and_enforce`?

**Comment by TomAugspurger** [comment]
Yep, that seems reasonable. I think avoiding `apply_and_enforce` wherever it's not necessary is worth goal.

**Comment by mrocklin** [comment]
@TomAugspurger thoughts on this?  I've changed the name to `enforce_metadata`, and applied it somewhat broadly throughout dask/dataframe/core.py

**Pull request merged**
