### PR TITLE
Change default branch from master to main

### PR DESCRIPTION
**Pull request by jsignell**
This should go in after the distributed PR https://github.com/dask/distributed/pull/4495

### CODE REVIEW

**Comment by jakirkham** [comment]
Are we just waiting on CI here? If so given that macOS builds are still queued and others have already passed, should we go ahead here?

cc @jrbourbeau (in case you also have thoughts on these questions)

**Review by jrbourbeau — APPROVED** [review]
Yep, this LGTM. Thanks for your work on this @jsignell!

**Comment by jakirkham** [comment]
Thanks Julia and James! 😄

**Comment by jsignell** [comment]
YAY!! Thanks to you as well @jrbourbeau :)

**Pull request merged**
