### PR TITLE
Remove kwarg validation for bokeh

### PR DESCRIPTION
**Pull request by jsignell**
- [ ] Closes #xxxx
- [x] Tests added / passed
- [x] Passes `black dask` / `flake8 dask` / `isort dask`

ref https://github.com/bokeh/bokeh/pull/11176

### CODE REVIEW

**Comment by bryevdv** [comment]
BTW if you do still want to do this checking, a future-proof alternative would  be to use `list(plot.properties())` instead. What we would like to clean up in the future is to have `properties` return a `Dict[str, property]` that maps names to property objects

**Comment by jsignell** [comment]
I don't know why we'd want to silently drop kwargs on the dask side. But maybe I'm missing some  context - @jrbourbeau what do you think?

**Review by jrbourbeau — COMMENTED** [review]
Thanks @jsignell, I agree silently ignoring invalid `kwargs` seems like something we would want to avoid. Could you add a small test which checks that things fail loudly when an invalid keyword is used?

**Comment by jsignell** [comment]
Note that the failing tests are just on Upstream and are unrelated.

**Pull request merged**
