### PR TITLE
Removed redundant check_dtypes

### PR DESCRIPTION
**Pull request by rajagurunath**
- [x] Closes https://github.com/dask/dask/issues/7947
- [x] Tests added / passed
- [x] Passes `black dask` / `flake8 dask` / `isort dask`

Hi @jakirkham & @jsignell 

Have done some initial changes based on the discussion, Please review and let me know if any other things need to be added/changed.

Thanks

### CODE REVIEW

**Review by jsignell — DISMISSED** [review]
This looks great! Thanks for working on it @rajagurunath

**Comment by jsignell** [comment]
From the test failures, it seems like we need to add `check_dtype` in some other places as well.

here:
https://github.com/dask/dask/blob/ff1cc1cc020ca7f02faa0d52bbd20a625545a5be/dask/dataframe/utils.py#L555

and here:
https://github.com/dask/dask/blob/ff1cc1cc020ca7f02faa0d52bbd20a625545a5be/dask/dataframe/utils.py#L563

**Comment by rajagurunath** [comment]
> From the test failures, it seems like we need to add `check_dtype` in some other places as well.
> 
> here:
> https://github.com/dask/dask/blob/ff1cc1cc020ca7f02faa0d52bbd20a625545a5be/dask/dataframe/utils.py#L555
> 
> and here:
> https://github.com/dask/dask/blob/ff1cc1cc020ca7f02faa0d52bbd20a625545a5be/dask/dataframe/utils.py#L563

Thanks for pointing this out!

I have added the check_dtype in the appropriate places and run the tests locally, test cases are passed, let see how it goes this time. 🤞

**Comment by jsignell** [comment]
I just triggered the tests to run, but it looks like you have some conflicts with main now, so you will need to merge in main or rebase before this can be merged.

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by quasiben** [comment]
ok to test

**Comment by rajagurunath** [comment]
> I just triggered the tests to run, but it looks like you have some conflicts with main now, so you will need to merge in main or rebase before this can be merged.

Hi think, I have resolved the conflict, please let me know if any further changes need to be done

**Comment by jsignell** [comment]
Looks great! Thanks @rajagurunath for the contribution!

**Pull request merged**
