### PR TITLE
Move Windows CI builds to GitHub Actions

### PR DESCRIPTION
**Pull request by jrbourbeau**
This PR moves our Windows CI builds from AppVeyor to GitHub Actions to enable multiple parallel jobs

xref https://github.com/dask/distributed/pull/3373

- [ ] Tests added / passed
- [ ] Passes `black dask` / `flake8 dask`

### CODE REVIEW

**Comment by mrocklin** [comment]
The Windows 3.6 test failure seems genuine?

**Comment by jrbourbeau** [comment]
> The Windows 3.6 test failure seems genuine?

Yeah it does. Unfortunately I'm not sure what's causing the failure at the moment. @TomAugspurger any idea if

`file:///C:/Users/RUNNER%7E1/AppData/Local/Temp/tmpm03pnz67/.test.accounts*`

has anything particularly pathological in it from `fsspec`'s point of view?

**Comment by TomAugspurger** [comment]
Nothing comes to mind, sorry.

**Comment by jrbourbeau** [comment]
I've gone ahead and `xfail`ed `test_with_urls` when running on Python 3.6 + Windows on GitHub Actions builds. I'm not particularly satisfied with this, but I'd prefer to not hold up the other changes in this PR on debugging that single test under those conditions. If this PR is merged, I'll open an issue to track the failing test.

Are we okay removing the AppVeyor build at this point (that's what we did over in `distributed`)? Or should we keep it around for a little while?

**Comment by TomAugspurger** [comment]
I'm OK to remove it.

**Comment by jrbourbeau** [comment]
Great, thanks for the feedback Tom!

If no further comments, I plan to merge this at the end of the day

**Pull request merged**
