### PR TITLE
Update Zarr store creation functions

### PR DESCRIPTION
**Pull request by rabernat**
- [ ] ~Closes #xxxx~
- [x] Tests added / passed
- [x] Passes `pre-commit run --all-files`

As discussed in https://github.com/zarr-developers/zarr-python/pull/1309#pullrequestreview-1231599350, Zarr can now handle a the creation of more types of store object from URLs thanks to the FSStore class. This means that usually Dask can just pass through the store URL with no modifications (e.g. calling `get_mapper`). The only exception is when the user specifies `storage_options` explicitly.

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

Admins can comment `ok to test` to allow this one PR to run or `add to allowlist` to allow all future PRs from the same author to run.

**Comment by mrocklin** [comment]
Cool.  Happy to see things moved upstream.  Is this new functionality widely deployed?  Should we be concerned at all about backwards compatibility?  (how old is it / what fraction of users are likely using that version or older?)

**Comment by ncclementi** [comment]
add to allowlist

**Comment by mrocklin** [comment]
CI failure seems unrelated.  Testing main here: https://github.com/dask/dask/pull/9792

**Comment by rabernat** [comment]
> Is this new functionality widely deployed? Should we be concerned at all about backwards compatibility? (how old is it / what fraction of users are likely using that version or older?)

This should work with all versions of Zarr > 2.6.0, which was released in July, 2021. That feels like a long time ago to me, but I have no data on what fraction of users are using older versions. (Do you have some way to get those numbers?)

**Comment by mrocklin** [comment]
Makes sense.  I was just curious.  CI seems unhappy.  I suspect due to unrelated issues.  I'm going to pause on this for a moment while I check those out.  My apologies for the delay.

**Comment by mrocklin** [comment]
Thanks @rabernat .  This is in.

**Pull request merged**
