### PR TITLE
make easier to link issues in PRs

### PR DESCRIPTION
**Pull request by raybellwaves**
Open to other suggestions here.

xarray have a few more items in their version: https://github.com/pydata/xarray/blob/master/.github/PULL_REQUEST_TEMPLATE.md

### CODE REVIEW

**Comment by crusaderky** [comment]
I would definitely add a note about documentation

**Review by crusaderky — COMMENTED** [review]
.

**Review by jrbourbeau — COMMENTED** [review]
Thanks for the PR @raybellwaves! Would you mind opening up a similar PR over in distributed? 

FWIW we used to include a check for documentation / changelog entry and found this added friction for new contributors who are the primary target of this checklist (xref https://github.com/dask/dask/pull/3459). We found that most PRs which are large enough to need a documentation change are included by the person submitting the PR and/or asked for by the reviewer(s)

**Review by jrbourbeau — APPROVED** [review]
Thanks @raybellwaves! This is in

**Pull request merged**
