### PR TITLE
Maintain annotations in `DataFrame.categorize`

### LINKED ISSUE #10118: `DataFrame.categorize` drops all annotations when computing categories even if low level fusion is deactivated
# Problem

`DataFrame.categorize` drops all annotations from the input graph when computing the categories even if low level fusion is deactivated.

# Example
Simplified version of https://github.com/dask/distributed/issues/7615#issuecomment-1484828091:

```python3
from __future__ import annotations

import dask
import dask.dataframe as dd
from dask.distributed import Client, LocalCluster


def foo():
    cluster = LocalCluster()
    client = Client(cluster)
    df = dask.datasets.timeseries(
        start="2000-01-01",
        end="2000-03-01",
        dtypes={"x": float, "y": str},
        freq="10 s",
    )
    df = dd.shuffle.shuffle(df, "x", shuffle="p2p")
    df = df.categorize(columns=["y"])
    df.compute()


if __name__ == "__main__":
    foo()
```

# Where do we drop annotations?

Within `categorize`, we compute the categories. In this step, we convert from a high-level graph to a low-level one without preserving the annotations:
https://github.com/dask/dask/blob/0cbc46ac89b6f6a2cf949f2fd73c4c1175419db5/dask/dataframe/categorical.py#L149-L154

# Related tickets
* dask/distributed#7615

### PR DESCRIPTION
**Pull request by hendrikmakait**
Sibling to https://github.com/dask/distributed/pull/7708

- [x] Closes #10118 
- [ ] Tests added / passed
- [x] Passes `pre-commit run --all-files`

### CODE REVIEW

**Review by jrbourbeau — COMMENTED** [review]
Thanks @hendrikmakait. This looks sensible. Could you add a test for this?

**Comment by hendrikmakait** [comment]
@jrbourbeau: Testing this in isolation isn't straightforward to me. I've added a test in https://github.com/dask/distributed/pull/7708 that addresses the original issue.

**Comment by jrbourbeau** [comment]
Thanks for adding a test over in `distributed`. I'm curious why something like 

```python
def test_categorize_annotations():
    # Regression test for https://github.com/dask/dask/issues/10118
    # Make sure `.categorize()` doesn't loose annotations
    df = pd.DataFrame({"x": [1, 2, 3, 4], "y": ["bob", "sally", "billy", "jean"]})
    with dask.annotate(foo="bar"):
        ddf = dd.from_pandas(df, npartitions=2)
    
    assert ddf.dask.layers[ddf._name].annotations["foo"] == "bar"
    ddf2 = ddf.categorize("y")
    assert ddf2.dask.layers[ddf._name].annotations["foo"] == "bar"
    ddf3, _ = dask.optimize(ddf2, ddf2.__dask_keys__())
    assert ddf3.dask.layers[ddf._name].annotations["foo"] == "bar"
```

Doesn't capture the same thing. This test passes on `main`, so clearly it's not fully what we're after, but it seems close. Though I could very well be missing something

**Review by jrbourbeau — APPROVED** [review]
Looks like the new test over in https://github.com/dask/distributed/pull/7708 is passing -- thanks @hendrikmakait

**Pull request merged**
