### PR TITLE
Fixes warning from setting categorical codes to floats

### LINKED ISSUE #4559: deprecation warnings in read_csv
The use of `pd.Categorical.from_codes` cases the following warnings:
```
intake/source/tests/test_csv.py::test_read_pattern
  /Users/mdurant/code/dask/dask/dataframe/io/csv.py:252: FutureWarning: float codes will be disallowed in the future and raise a ValueError
    colname: pd.Categorical.from_codes(np.zeros(len(head)), paths)

intake/source/tests/test_csv.py::test_read_pattern_with_path_as_pattern_str
  /Users/mdurant/code/dask/dask/dataframe/io/csv.py:252: FutureWarning: float codes will be disallowed in the future and raise a ValueError
    colname: pd.Categorical.from_codes(np.zeros(len(head)), paths)
```
Presumably fixed by specifying an int type to the numpy call.
( cc @jsignell )

### PR DESCRIPTION
**Pull request by jsignell**
- [x] Fixes #4559 
- [ ] Tests added / passed - let me know if you think this needs one. 
- [x] Passes `flake8 dask`

### CODE REVIEW

**Comment by martindurant** [comment]
+1 , looks totally fine. 
I don't know if there's a way to assert that a function call doesn't give a warning. If no one comments on here giving a way, I'll just merge in a few hours.

**Comment by jrbourbeau** [comment]
`pytest` has a nice [`pytest.warns` context manager](https://docs.pytest.org/en/4.3.1/warnings.html#recwarn) that records raised warnings. Something like

```python
with pytest.warns(None) as record:
    # code that doesn't raise a warning

assert len(record) == 0
```
could work here

**Comment by jsignell** [comment]
Yep that would work nicely, just not sure if it is overkill.

**Comment by martindurant** [comment]
I am happy either way, up to you.

**Comment by jsignell** [comment]
I tried it out and it seems that it would fail on any FutureWarning which seems like something that dask would want to be intentional about enabling. So I think this should go in as-is. 

RE https://github.com/dask/dask/issues/4559#issuecomment-475666927: I did a glance over unmerged PRs and didn't see this change in any of them.

**Comment by jrbourbeau** [comment]
> I think this should go in as-is

Agreed, failing on any warning here is probably overkill. I checked locally that the related `FutureWarning` is no longer raised. +1 from me

**Comment by jrbourbeau** [comment]
Thanks @jsignell

**Pull request merged**
