### PR TITLE
Backports for 0.17.5

### PR DESCRIPTION
**Pull request by TomAugspurger**
Just testing this out. The 0.23 compat changes aren't in yet.

Will also have to update the changelog on master to move the backported items to the right release.

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Reminder: we probably want to "Rebase and merge" to backport branches, rather than "Squash and merge".

**Comment by TomAugspurger** [comment]
cc @mrocklin @jakirkham 

do we want to put an upper bound on distributed? I think the next release will have a hard dependency between the two latest, so we could catch that now.

**Comment by TomAugspurger** [comment]
OK, here we go.

**Comment by crusaderky** [comment]
http://dask.pydata.org/en/latest/changelog.html doesn't look right; was it updated?

**Comment by jakirkham** [comment]
Hmm...it looks like the text is the changelog here. Went ahead and restarted RTD post-release to see if that might fix the issue. Let's see what happens.

**Comment by jakirkham** [comment]
Think the issue is RTD is cloning from `master`, which doesn't have the updated changelog. The changes here are in `0.17.x`. Proposed PR ( https://github.com/dask/dask/pull/3510 ) to merge them, but had to resolve a few merge conflicts. Would appreciate extra eyes to double check it got merged correctly.

**Pull request merged**
