### PR TITLE
Fix import failing when using "python -OO"

### LINKED ISSUE #6296: importing fails when calling python -OO
This was discovered by `xarray`'s `upstream-dev` CI ([environment](https://dev.azure.com/xarray/xarray/_build/results?buildId=2996&view=logs&j=2280efed-fda1-53bd-9213-1fa8ec9b4fa8&t=031ddd67-e55f-5fbd-2283-1ff4dfed6587)) a few days ago, but we were a bit slow in reporting so this also happens with the newly released `2.18.0`.

The problem is this:
```
$ python -OO -c 'import dask.array'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File ".../lib/python3.8/site-packages/dask/array/__init__.py", line 26, in <module>
    from .routines import (
  File ".../lib/python3.8/site-packages/dask/array/routines.py", line 18, in <module>
    from .creation import arange, diag, empty, indices
  File ".../lib/python3.8/site-packages/dask/array/creation.py", line 26, in <module>
    from .wrap import empty, ones, zeros, full
  File ".../lib/python3.8/site-packages/dask/array/wrap.py", line 173, in <module>
    full.__name__ = _full.__name__
AttributeError: 'functools.partial' object has no attribute '__name__'
```
without the optimization, the import obviously works.

See also pydata/xarray#4124

### PR DESCRIPTION
**Pull request by jsignell**
- [x] Tests added / passed
- [x] Passes `black dask` / `flake8 dask`
- [x] Fixes #6296

cc @dask/maintenance 
 
To test: try `python -OO -c 'import dask.array'`  on this branch vs master.

### CODE REVIEW

**Comment by martindurant** [comment]
?? optimised functions don't have names ?? :)

So you think it's worth doing a test run for OO, or at least an import check?

**Comment by jcrist** [comment]
We used to do this, but stopped since not many people wanted it and it took up a test matrix slot. The code logic is still in our travis setup, it's just not enabled.

**Comment by jsignell** [comment]
I think it's more like optimized partial functions don't have names. I think this PR is an improvement as I don't think the name is as intended on master anyways:

```python
>>> import dask.array
>>> print(dask.array.full.__name__)
blocked_full
```


don't really care one way or the other about CI.

**Comment by martindurant** [comment]
OK :)

**Pull request merged**
