### PR TITLE
Further removal of stale BlockwiseIO code

### PR DESCRIPTION
**Pull request by rjzamora**
#7048 Reverted a recent attempt to implement read_parquet, read_csv, read_orc, and array creation as `Blockwise` layers.  This PR goes a bit further and removes the stale `BlockwiseIO` code that is no longer being used.  It will be easier to review the replacement with the "old"/"bad" code completely removed :)

My mistake for not removing this in the original reversion (git-related mix-up on my part).

### CODE REVIEW

**Comment by rjzamora** [comment]
@jsignell -  This PR includes changes that I *thought* were already included in #7048 . The BlockwiseIO code that is still in the master branch is not actually used anywhere, so it is not critical to get this in before the release.  However, it would be nice to remove the stale code as soon as we can (to confusion).  Appologies for not getting these changes in before!

**Comment by jsignell** [comment]
I am retriggering the tests and then plan to merge

**Review by jrbourbeau — APPROVED** [review]

**Comment by bmerry** [comment]
FYI there is still one reference to BlockwiseIO in a docstring in blockwise.py.

**Comment by rjzamora** [comment]
>FYI there is still one reference to BlockwiseIO in a docstring in blockwise.py.

Oops - Thanks for reporting that!

**Pull request merged**
