### PR TITLE
Allow atop to change chunk shape

### PR DESCRIPTION
**Pull request by mrocklin**
## Example

``` python
def double(a, axis=0):
    return np.concatenate([a, a], axis=axis)

y = atop(double, 'ij', x, 'ij', chunks={'i': lambda n: 2*n}, axis=0)

y = atop(double, 'ij', x, 'ij', chunks={'j': lambda n: 2*n}, axis=1)
```

cc @shoyer @jcrist

### CODE REVIEW

**Comment by jcrist** [comment]
Seems fine to me. Only issue I see is that `chunks` is a common keyword in other functions, but means something else. May not be worthy of changing the keyword name though, I can't think of a better one.

**Comment by shoyer** [comment]
I also like this functionality but think the `chunks` name is a little too generic. Based on other uses of `chunks` in dask, I would expect `chunks` to explicitly set chunks on the result.

Other options: `chunks_map`, `chunking`, `rechunk`, `new_chunks`...

I think `rechunk` is my favorite?

**Comment by mrocklin** [comment]
Changed chunks to rechunk

**Comment by shoyer** [comment]
Actually, `rechunk` sort of implies adjusting chunk boundaries... maybe `adjust_chunks`?

**Comment by mrocklin** [comment]
Someone privately suggested that we also support the following inputs:

*  `rechunk={'i': 10}`: all chunks are of size 10
*  `rechunk={'i': [10, 10, 20]}`: explicitly list the chunk sizes (and check that there are three blocks in this dimension

**Comment by shoyer** [comment]
Yes, those are similar to inputs I supported in my version.

**Comment by mrocklin** [comment]
Implemented int and tuple forms of rechunk.

Waiting a bit on renaming to `adjust_chunks` in case any other names come up

**Comment by mrocklin** [comment]
Renamed to adjust_chunks

**Pull request merged**
