### PR TITLE
Fuse slices works with alias in graph

### LINKED ISSUE #2355: poor optimization of slicing operations on netCDF-backed xarray datasets
We have encountered a performance issue in xarray (pydata/xarray#1396) which appears to be a dask optimization issue at its core. In [correspondence on the xarray mailing list](https://groups.google.com/forum/#!topic/xarray/UbiQu7aZvkg), @mrocklin recommended I open an issue here.

The scenario is the following: I have a collection of large netCDF files on a disk. Each file can be though of as representing geospatial data: the first dimension is time, and the higher dimensions are spatial dimensions (e.g. x and y). I want to open the data as an xarray dataset, concatenating along the time dimension, select a single point in space, and lazily load the data for this point into memory, creating a timeseries. (This is an extremely common workflow in climate science and related fields.) xarray handles this by opening the files, wrapping the data in dask arrays, and then concatenating those arrays together, under the hood calling `dask.array.concatenate`. 

The problem is that the entire array from each file is being read eagerly before the slicing operation. This incurs a huge performance and memory penalty for what should naively be a very cheap operation. For very large datasets, it leads to memory overruns and total breakdown of the workflow.

Below is a reproducible example which requires xarray. A more detailed version of this example can be found in this [notebook](https://gist.github.com/rabernat/7175328ee04a3167fa4dede1821964c6)
```python
import numpy as np
import xarray as xr

### Create some test data
# This test data is typical of many climate datasets. Each file has 12 entires in the time
# dimension, representing e.g. each month of the year. There are 10 separate files,
# representing e.g. consecutive years. The code below writes about 9GB of data to disk.
# Change data_dir to a place where you can put 9GB of data

data_dir = '/data/scratch/rpa/xarray_test_data/'
nfiles = 10
nt = 12

for n in range(nfiles):
    data = np.random.rand(nt,1000,10000)
    time = (n*nt) + np.arange(nt)
    da = xr.DataArray(data, dims=['time', 'y', 'x'],
                      coords={'time': time})
    da.to_dataset(name='data').to_netcdf(data_dir + 'test_data.%03d.nc' % n)

### open the data via xarray
all_files = glob(data_dir + '*.nc')
ds = xr.open_mfdataset(all_files)

### Time loading the whole dataset into memory
# As a point of reference, let's see how long it takes to read all the data from disk and load it
# into memory. (We make a deep copy of the dataset first in order to preserve the original
# chunked dataset for later use.)

ds_copy = ds.copy(deep=True)
with ProgressBar():
    # on a high-performance workstation, this takes 15-20s
    %time _ = ds_copy.load()

### Time loading a single point
# This is the crux issue. We now want to just extract a timeseries of single point in space.
# If the loading is lazy, it should go much faster and use much less memory compared to
# the example above.

y, x = 200, 300
with ProgressBar():
    %time ts = ds.data[:, y, x].load()
```

The extraction of a single point takes about half the time of loading the whole dataset! Furthermore, by monitoring memory usage via top, I observe that resident memory increases strongly as the command executes. If I just loop through `all_files` manually and extract the point, it goes 500-1000 times faster and uses a tiny fraction of the memory. I explore this, and many other permutations (including bypassing xarray and doing `dask.array.concatenate` directly on the underling dask arrays of each dataset) in my [notebook](https://gist.github.com/rabernat/7175328ee04a3167fa4dede1821964c6). I believe this is a dask issue, not an xarray issue.

Here is the partial dot graph for `ds.data[:, y, x].dask`
result_dot_graph

Here is the partial dot graph for `result._optimize(result.dask, result._keys())` where `result = ds.data[:, y, x].dask`
result_dot_graph_optimized

The root cause of the issue, in the words of @mrocklin, is that "it looks like there is a getarray followed by a getitem.  We'll have to dive into why these two weren't fused into a single gatarray/getitem call."

```python
>>> print(xarray.__version__)
0.9.5-9-gd5c7e06
>>> print(dask.__version__)
0.14.3+19.gbcd0426
```

### PR DESCRIPTION
**Pull request by jcrist**
In #2080 a bug was introduced that prevented fusing slices across
aliases in the graph. These would show up when several dask arrays were
concatenated together. This fixes that bug, and adds a test that fusing
works across aliases.

Fixes #2355.

### CODE REVIEW

**Comment by rabernat** [comment]
This looks like a great fix! Thank you so much!

I just checked out your branch and gave it a try. It definitely works in some cases. However, unfortunately the default dask arrays created by `xarray.open_mfdataset` still are not benefitting from the new optimization. This is probably a downstream issue with xarray. However, while I have your attention, it would be great to have a little help debugging.

Let me provide a quick self-contained example. This creates a test dataset

```python
import numpy as np
import xarray as xr
nfiles = 10
nt = 12
all_files = []
for n in range(nfiles):
    data = np.random.rand(nt,1000,10000)
    time = (n*nt) + np.arange(nt)
    da = xr.DataArray(data, dims=['time', 'y', 'x'],
                      coords={'time': time})
    fname = 'test_data.%03d.nc' % n
    da.to_dataset(name='data').to_netcdf(fname)
    all_files.append(fname)
```

Here is what does work: manually concatenating the datasets
```python
all_dsets = [xr.open_dataset(fname).chunk() for fname in all_files]
ds_concat = xr.concat(all_dsets, dim='time')
%%timeit ts = ds_concat.data[:, 0, 0].load()
```
On my system, this gives `10 loops, best of 3: 13.5 ms per loop`, i.e. very fast, shows that the optimization has worked.

Here is what does *not* work: using xarray's `open_mfdataset` function, which is by far the most common way users load data
```python
ds = xr.open_mfdataset(all_files, decode_cf=False)
%%timeit ts = ds.data[:, 0, 0].load()
```
This gives `1 loop, best of 3: 7.35 s per loop`. This is the same sort of _SLOW_ speed I was getting before your PR.

I cannot find any differences in the dask graphs of these two different xarray datasets. Nevertheless, there is nearly a factor of 1000 difference in performance, indicating that your fix is being applied to `ds_concat` but not to `ds`.

Is there any further info I can provide that can help debug what might be going on?

cc to @shoyer, who might have some insight into the xarray side of things.

**Comment by jcrist** [comment]
Ah, that's because the `mfdataset` adds a lock to the reads, and our optimizations don't handle that case (but should). Will fix.

**Comment by shoyer** [comment]
Once we get this fixed, we should think about how we could add an integration test for this behavior in xarray (since it has major performance implications).

**Comment by jcrist** [comment]
@rabernat, this should be fixed with the recent commit.

**Comment by jcrist** [comment]
A different fix would have changed all the `get*` functions to also take a lock. I went down this path (and still have the commit saved), but it changed many many lines and this fix was simpler. However, there are some issues with the current approach in that a user can provide a custom `getitem` function to `from_array` that doesn't accept a lock, and also provide a lock, which will result in faulty behavior.

The `getitem` keyword was added in #2272 to support custom getitems. However, IIUC the intent of this keyword was to avoid calling `np.asarray` on chunks - an equivalent but simpler fix would have been to add an `asarray` keyword which defaults as True. Then we could standardize on all `get*` functions taking a lock without the possibility of user-error. Another downside of the current code is that the slice fusing doesn't work if there's a custom `get*` function, as the optimization doesn't know about it (which would be fixed if we had our own `getitem_with_lock` function).

I think that removing the `getitem` keyword and standardizing on all `get*` functions taking a lock would be the better and more robust fix in the long run, but the current fix is simpler. Ping @mrocklin for thoughts.

**Comment by rabernat** [comment]
I can confirm that my original issue (pydata/xarray#1396) looks to be fixed by this PR. 😄  Unfortunately I can't add much insight to the dask design questions.

@shoyer: 👍  to the xarray integration test.

**Comment by bradyrx** [comment]
It seems like I'm hitting a similar bottleneck with extracting values from my dask DataArray (xarray) after loading my data through `open_mfdataset`.

I have a 40x12 DataArray `calMean` that was filtered out of a 34x384x320x1032 xarray Dataset with great performance time (order tens of milliseconds). 

However, any attempt to extract the values for plotting or attempting to save the 40x12 array into a netCDF takes 3 minutes. (Example shows` np.asarray()` but had similar timing on `.load()`, `.values()`, and `.to_netcdf()`)

```
%time data = np.asarray(calMean)
CPU times: user 2min 24s, sys: 43.3 s, total: 3min 7s
Wall time: 2min 49s
```

I'm eager to see this fix merged as soon as possible to speed up my interactive analysis. Thanks all.

**Comment by mrocklin** [comment]
> I think that removing the getitem keyword and standardizing on all get* functions taking a lock would be the better and more robust fix in the long run, but the current fix is simpler. Ping @mrocklin for thoughts.

The choice to accept custom getitem functions was intended to be a release valve for advanced users.  I think that there is some value to this.  These users are typically able to handle writing their own optimization functions if necessary.

**Comment by jcrist** [comment]
> The choice to accept custom getitem functions was intended to be a release valve for advanced users.

From the timeline, I assume this was added to support your work with `sparse`, where the custom `getitem` was used to avoid calling `asarray`? What other things do you see being done with a custom `getitem` besides avoiding calling `asarray`? I can't think of any. If that's it, I think dropping this functionality and replacing with a boolean kwarg (`asarray=True`? Or maybe `subok` to follow numpy?) would be simpler and more robust.

**Comment by mrocklin** [comment]
This was originally motivated by private users with custom use cases that were more advanced than sparse.

**Comment by jcrist** [comment]
Ok. I'll merge this as is then.

**Pull request merged**
