### PR TITLE
Fix code formatting issue in "Defining a new collection backend" docs

### PR DESCRIPTION
**Pull request by cmarmo**
Dear maintainers,
this pull request addresses #5610.
It removes a "Error in "code-block" directive".

Thank you for considering it.

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

Admins can comment `ok to test` to allow this one PR to run or `add to allowlist` to allow all future PRs from the same author to run.

**Review by jrbourbeau — APPROVED** [review]
Thanks @cmarmo! This is in 

Just out of curiosity, did you happen to randomly stumble across this, or are you interested in writing your own collection backend? 

Also, I noticed this is your first code contribution to this repository. Welcome!

**Comment by cmarmo** [comment]
Thanks @jrbourbeau! To answer your question : I stumbled across this, not really randomly, as I'm trying to learn a bit more around Dask and I started from following literally all the documented steps for building... :)

**Comment by jrbourbeau** [comment]
Ah, I see. Well thank you for taking the time to fix this 👍

**Pull request merged**
