### PR TITLE
Update dataframe sql docs references to other libraries

### PR DESCRIPTION
**Pull request by charlesbluca**
Updates the dataframe SQL docs page:

- removed the reference to blazingSQL as it is no longer being maintained
- mentioned in dask-sql reference that experimental GPU support is available (also removed the warning that it is a developmental library)
- added some details to FugueSQL's reference mentioning that it can be integrated with Dask-SQL

- [ ] Closes #xxxx
- [ ] Tests added / passed
- [ ] Passes `pre-commit run --all-files`

### CODE REVIEW

**Comment by jakirkham** [comment]
Generally this seems reasonable to me. Thanks for updating this Charles 😄

@martindurant do you have thoughts on these changes? 🙂

**Comment by martindurant** [comment]
Fine from me

cc @charlesbluca @nils-braun

**Comment by martindurant** [comment]
(d'oh, I think we accept dask-sql people's say-so on this anyway! :) )

**Comment by jakirkham** [comment]
Thanks Martin! 🙏 

FWIW the docs can be [previewed here]( https://dask--9077.org.readthedocs.build/en/9077/dataframe-sql.html )

**Pull request merged**
