### PR TITLE
Add `pipe` method to dask.dataframe

### LINKED ISSUE #1555: Does ddf.pipe() make sense?
Often times, i end up writing a function that takes in a `dask.dataframe`. pandas implements [`pd.pipe(func)`](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.pipe.html) that i find pretty convenient.

This is a pretty easy to implement but i think pipe may be pretty confusing in `dask.dataframe` world especially if someone tries to do columnar reductions. Thoughts on if it makes sense to implement?

### PR DESCRIPTION
**Pull request by jcrist**
Fixes #1555

### CODE REVIEW

**Comment by mrocklin** [comment]
cc @hussainsultan

**Comment by hussainsultan** [comment]
Awesome thanks. Should this also work with delayed methods?

**Comment by jcrist** [comment]
This just follows the pandas implementation, and is just a chainable way of writing a function call. These are equivalent:

```python
f(df, *args, **kwargs)
df.pipe(f, *args, **kwargs)
```

The function is free to do whatever it wants, we make no distinction between delayed or not.

**Comment by hussainsultan** [comment]
Awesome. I checked it out and works for my use case. Thank you @jcrist

**Pull request merged**
