### PR TITLE
Labels in dot language must be positive integers

### PR DESCRIPTION
**Pull request by thedimlebowski**
- [ x] Tests added / passed
- [ x] Passes `black dask` / `flake8 dask`

--- 

This PR is intended to make a dask graph parsable by pydot. The character `-` seem to be reserved in dot language, so I am proposing replacing the `hash` function in dot.py with `poshash` which is a positive hash key as suggested in https://stackoverflow.com/questions/18766535/positive-integer-from-python-hash-function.

--- 

```
import pydot
from dask import visualize
graph = {
    'a': 1,
    'b': 2,
    'c': [1, 2],
    'd': ['a', 'b', 'c']
}
digraph = to_graphviz(graph)
dot = pydot.graph_from_dot_data(digraph.source)
```

This code used to yield the following error: ```ParseException: Expected "}" (at char 73), (line:4, col:2)```.
It is now running correctly.

Comments are welcome.

### CODE REVIEW

**Comment by jakirkham** [comment]
How does this look like when generating an image of a graph using graphviz?

**Comment by TomAugspurger** [comment]
@thedimlebowski are you interested in working on this still?

**Comment by TomAugspurger** [comment]
@thedimlebowski played with your branch a bit, and it seems like this broke some visualization things. Here's the `dask.visualize` for your example.


mydask


Can you double check your changes?

**Comment by mrocklin** [comment]
This appears to be stalled.  Closing.  @thedimlebowski if you want us to open please just let us know.

**Pull request closed without merging**
