### PR TITLE
Fix map_overlap in order to accept pandas arguments

### LINKED ISSUE #9567: Non-working implicit dask dataframe promotion in map_overlap
_map_overlap()_ is unable to handle raw pandas DataFrame, unlike _map_partition()_.

```
import dask.dataframe
import pandas as pd

df = pd.util.testing.makeMixedDataFrame()

# Works  fine
dask.dataframe.map_partitions(lambda df: df, df)

# Raises "IndexError: list index out of range"
dask.dataframe.rolling.map_overlap(lambda df: df, df, before=0, after=0)
```
image

It looks like it should be working as we can see the following code in _map_overlap()_:
```
if align_dataframes:
    args = _maybe_from_pandas(args)
```

I can work on a PR if needed.

### PR DESCRIPTION
**Pull request by faulaire**
- [X] Closes #9567
- [X] Tests added / passed
- [X] Passes `pre-commit run --all-files`

### CODE REVIEW

**Comment by martindurant** [comment]
lgtm

**Comment by faulaire** [comment]
Someone to integrate this PR ?

**Comment by martindurant** [comment]
Can you please resolve the conflicts?

**Comment by faulaire** [comment]
Done !

**Comment by martindurant** [comment]
Sorry for the long wait

**Pull request merged**
