### PR TITLE
from_bcolz added usecols= keyword

### PR DESCRIPTION
**Pull request by ankravch**
Added usecols= keyword to read selected columns only, that reduces a run time significantly especially for wide tables. Started in #1432 .

### CODE REVIEW

**Comment by mrocklin** [comment]
This looks good.  It could use a test.  It would be good to verify that the following hold:

1.  The resulting dataframe has column names that match usecols
2.  The bcolz.ctable within the `.dask` attribute also only has these columns.  I would iterate through `df.dask.values()` to find the ctable and then run the check on that
3.  This provides nice error messages if someone provides a usecols keyword argument that contains columns that aren't found in the ctable

**Comment by nirizr** [comment]
Won't `columns` fit better than `usecols`? I think it's used in other places for a similar purpose.

**Comment by ankravch** [comment]
I was inspired by pandas.read_csv(usecols=...) keyword,  though I can switch to 'columns' to be consistent with dask naming style.

**Comment by jcrist** [comment]
Sorry for the lapse in responses here. Either `columns` or `usecols` sounds fine to me. This should be good to go once Matt's comments above are addressed, and the merge conflicts fixed. Do you still have time/interest in finishing this up?

**Comment by mrocklin** [comment]
Closing this as stale.  Please feel free to speak up if anyone would like to take this on again.

**Pull request closed without merging**
