### PR TITLE
Reading parquet with `filters`. Last division limits are now correct. #3831

### PR DESCRIPTION
**Pull request by andrethrill**
- [x] Tests added / passed
- [x] Passes `flake8 dask`

When reading parquet with `filters`, last division limits are now correct. Related with #3831.

See: 
https://github.com/dask/dask/issues/3831#issuecomment-414732749

### CODE REVIEW

**Comment by martindurant** [comment]
Thanks for fixing this.
It would be nice to have a test that demonstrates this working.

**Comment by andrethrill** [comment]
you're right @martindurant. Unit test added.

**Comment by martindurant** [comment]
This is specifically testing fastparquet, so the new test should be fastparquet-specific. The failure seems to be for arrow.

**Comment by andrethrill** [comment]
Should be finally done now

**Comment by martindurant** [comment]
Looks good, thanks.

**Pull request merged**
