### PR TITLE
CI: Update Appveyor

### PR DESCRIPTION
**Pull request by TomAugspurger**
Closes https://github.com/dask/dask/issues/4380

* Unpins NumPy and pandas (changing policy to test against the latest, rather than oldest supported)
* uses `--no-deps` in the pip install sections

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Latest fixes this (silent) failure

```
(testenv) C:\projects\dask>cmd /C conda install -q -y bcolz bokeh h5py ipython lz4 psutil pytables s3fs scipy pyarrow fastparquet 
248Fetching package metadata .........
249Solving package specifications: .
250PackageNotFoundError: Package not found: '' Package missing in current win-64 channels: 
251  - pyarrow
252
```

**Comment by mrocklin** [comment]
Should we be concerned that Appveyor isn't running on this PR?

**Comment by TomAugspurger** [comment]
@mrocklin I've updated the `sparse` installs to pull from `pydata/sparse` rather than `pydata/sparse`. That's causing some issues in the mixed sparse tests. As best I can tell, the issue is that `sparse` previously accepted (and presumably converted) NumPy ndarrays in `sparse.concatenate`


```python
In [1]: import dask.array as da; import sparse; import numpy as np

In [2]: x = np.array([1, 2])

In [3]: sparse.concatenate([x, sparse.COO.from_numpy(x)])
Out[3]: <COO: shape=(4,), dtype=int64, nnz=4, sorted=True, duplicates=False>

In [4]: sparse.__version__
Out[4]: '0.1.1'
```

In sparse 0.6, that's no longer the case,


```python
In [3]: x = np.array([1, 2])

In [4]: sparse.concatenate([x, sparse.COO.from_numpy(x)])
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-956e9910ff70> in <module>
----> 1 sparse.concatenate([x, sparse.COO.from_numpy(x)])

~/Envs/dask-dev/lib/python3.7/site-packages/sparse/coo/common.py in concatenate(arrays, axis)
    382     """
    383     from .core import COO
--> 384     check_consistent_fill_value(arrays)
    385
    386     arrays = [x if isinstance(x, COO) else COO(x) for x in arrays]

~/Envs/dask-dev/lib/python3.7/site-packages/sparse/utils.py in check_consistent_fill_value(arrays)
    323
    324     if not all(isinstance(s, SparseArray) for s in arrays):
--> 325         raise ValueError('All arrays must be instances of SparseArray.')
    326     if len(arrays) == 0:
    327         raise ValueError('At least one array required.')

ValueError: All arrays must be instances of SparseArray.
```

@hameerabbasi do you know what the expected behavior is here, when concatenating a mix of NumPy and sparse ndarrays? If that should work, I'll open an issue.

For now, I've xfailed those tests.

**Comment by hameerabbasi** [comment]
We generally have a policy of only allowing mixed Sparse-dense algorithms if the mixed algorithm is superior to the dense one. In this case, it isn’t better.

So yes, this is desirable behaviour.

AFAICT, this was put in place because Sparse algorithms would sometimes return a dense array before, and I’ve made sure that most algorithms now return Sparse arrays, so it’s no longer needed.

I can look into changing it if there’s a use case, as always.

**Comment by TomAugspurger** [comment]
Thanks.

> if the mixed algorithm is superior to the dense one. In this case, it isn’t better.

Can we know that just from the types? I'm not sure how "better" is defined here, but if we go with something like "not blowing up memory", then `sparse.concatenate([small_dense_array, large_sparse_array])` is probably preferable to `np.concatenate`, which would (IIUC) convert everything to dense. Though I agree, it's not clear that `sparse.concatenate` would always be better than `np.concatenate`.

**Comment by hameerabbasi** [comment]
> Though I agree, it's not clear that `sparse.concatenate` would always be better than `np.concatenate`.

This is kind of how I define it, usually. :) If it's very easy to mess it up, I prefer to let the programmer be explicit.

**Comment by TomAugspurger** [comment]
👍 thanks for the explanation.

**Comment by TomAugspurger** [comment]
@martindurant do you have any guesses about this fastparquet failure at https://ci.appveyor.com/project/daskdev/dask/builds/21637433#L1294.

Previously, we were (accidentally) skipping all parquet tests on windows. Now we have fastparquet 0.2.1. The path we're passing there looks pretty bogus

```
path = 'C:/Users/appveyor/AppData/Local/Temp/1/pytest-of-appveyor/pytest-0/test_read_glob_fastparquet_fas0/C:/Users/appveyor/AppData/Local/Temp/1/pytest-of-appveyor/pytest-0/test_read_glob_fastparquet_fas0/part.0.parquet'
1356
```

**Comment by TomAugspurger** [comment]
OK, all green (finally). Summary of the changes

1. Let the appveyor NumPy and pandas versions float (latest available on defaults)
2. Include `--no-deps` in (most of) the calls to `pip install ...`. Previously we ended up with multiple NumPys installed. For some packages (e.g. distributed) we let pip pull in dependencies if necessary
3. switch install of `mrocklin/sparse` -> `pydata/sparse` (maybe this should just be from pip?)
   a. skip on dask.array tests that mix dense and sparse (see 
https://github.com/dask/dask/pull/4381#issuecomment-454382177)
4. Added a few skips for Numba<0.40. In particular, the numba from conda-forge on windows is a bit old, and was causing failures.
5. Added a few fastparquet skips on windows (e.g. https://github.com/dask/dask/pull/4381/files#diff-64a10d0aac80381d6dedc585834c43efR179). Haven't tracked down if this is a bug in fastparquet or dask yet.
6. Added a few import or skips for `snappy`.
7. Added an import or skip for `matplotlib.pyplot`. I didn't debug it, but the visualization tests were failing on some platforms with a qt issue.  `import matplotlib` doesn't trigger the import. The 3.5 job is still running these tests.


Of these changes, I think only the 3a demands further investigation, but I'd like to leave that as a followup PR.

**Comment by mrocklin** [comment]
Is it worth reporting the numba + windows + conda forge issue upstream?

**Comment by TomAugspurger** [comment]
As usual, @jakirkham is ahead of the game :) https://github.com/conda-forge/numba-feedstock/pull/21.

Seems like https://github.com/conda-forge/llvmlite-feedstock/pull/13 needs to be fixed and merged, then https://github.com/conda-forge/numba-feedstock/pull/21 restarted. I haven't looked, but there are llvmlite failures on OSX and Windows (27 only).

Hopefully the present compiler migration will make the llvmlite build a bit easier to do...

**Comment by mrocklin** [comment]
Thanks @TomAugspurger

**Pull request merged**
