### PR TITLE
Don't use mutable default argument

### PR DESCRIPTION
**Pull request by jseabold**

### CODE REVIEW

**Comment by jcrist** [comment]
What spurred this?

**Comment by jseabold** [comment]
Was just reading the code. Mutable default arguments are a common gotcha. The next time that function is called without a value for s3_params, it will have whatever the last value given to s3_params was. Perhaps that was intended? Maybe a bit too clever IMO, if so.

https://pythonconquerstheuniverse.wordpress.com/category/python-gotchas/

**Comment by jcrist** [comment]
In general that's a good rule of thumb, but it doesn't apply here. The dictionary default argument is never mutated itself, it's just immediately splatted into the kwargs of a further function. In the example in that post, the function mutates the list. I'm not saying this isn't a good fix as it might catch future bugs if the code changes. Ping @mrocklin for a final opinion, as this is his code.

**Comment by jseabold** [comment]
Yeah, that's true. Still struck me as potentially problematic down the road and maybe best to avoid before people start writing code against it.

**Comment by jcrist** [comment]
Perhaps instead of changing the signature of the function, just do:

```python
def read_block_from_s3(filename, offset, length, s3_params=None, delimiter=None,
                       compression=None):
     s3 = S3FileSystem(**(s3_params or {}))
```

Simple, still separates kwargs for `S3FileSystem` from others, and no mutable default.

**Comment by bryevdv** [comment]
That's a fairly standard idiom for this case.

**Comment by jseabold** [comment]
Yeah, that would have been my first choice, but then I looked at the rest of the signatures.

**Comment by jcrist** [comment]
Those are user facing, rather than just tasks in the graph. Using kwargs in functions in the graph results in `(apply, func, (arg1, arg2, ...), {'key1': val1, ...})`, rather than just `(func, arg1, arg2, ...)`. Both work fine, but the second option is slightly simpler which is why many task functions don't take keyword arguments like that (`s3_open` in that same file, for example). Again, not a big deal, but there is a mild reason for things being the way they are.

**Comment by jseabold** [comment]
Fair. Feel free to close the issue.

**Comment by jcrist** [comment]
No, it's a valid point, sorry for being so contrarian here. I was just arguing for the simple solution posted above instead of a change in the signatures. If you don't want to update the PR here, I can take care of it separately.

**Comment by jseabold** [comment]
Made your suggested change. Makes sense.

Still some context for me to understand, and a bit that's non-obvious (to me). Is there something to differentiate between the user-facing API and tasks in the graph here?

**Comment by jcrist** [comment]
Thanks.

> Still some context for me to understand, and a bit that's non-obvious (to me). Is there something to differentiate between the user-facing API and tasks in the graph here?

That's a fair point. In this case, the public functions are those here: https://github.com/jseabold/dask/blob/4292a35986ed57ac526cf78d6aa7d1a3c83416f3/dask/bytes/core.py. This file defines the implementations of those needed for the s3 protocol backend (so none of the functions in the s3 file are directly user facing). It appears this isn't documented anywhere though, will fix.

**Pull request merged**
