### PR TITLE
Add more ordering diagnostics to `dask.visualize`

### PR DESCRIPTION
**Pull request by eriknw**
I added these to help investigate https://github.com/dask/dask/pull/7929

The names could probably be better.  This also needs documented and tested, but I thought I'd share, because, you know, pretty plots!  I think all options here are potentially useful.  Anything else we might want to show?

Speaking of pretty plots, I'll share some tomorrow.  Good night!

- [x] Tests added / passed
- [x] Passes `black dask` / `flake8 dask` / `isort dask`

### CODE REVIEW

**Comment by eriknw** [comment]
As promised, here are a few graphs.  These show memory pressure--the number of dependencies that are held in memory when a task is run (shown in the function circle) and when the data of a task is released (shown in the data rectangle).

Here's a simple example to get you started:

graph1

Note that all these are created with `color="order-pressure"`, and `cmap="plasma"`.  The label on the functions is the order number and the memory pressure.  If we only wanted to show the memory pressure, then do `color="pressure"`.

Another one that is slightly more complicated:

graph2

And another:

graph3

And a more complicated one:

graph4

And the example from https://github.com/dask/dask/pull/7929 (main branch)

graph5

And the same one using PR 7929:

graph5-pr

To compare the two graphs above more directly, it would be nice to have them on the same scale.  So, we can now pass `maxval=` to `visualize`, which changes the previous graph to:

graph5-pr2

I think this is pretty nice.  I don't know why I didn't whip this up long ago!

**Comment by ncclementi** [comment]
@eriknw Checking in here, is this PR still WIP, or is it in a state ready for review?

**Comment by eriknw** [comment]
Thanks for checking!  Still WIP, and not forgotten.

TODO:
- [ ] docstring
- [ ] tests

**Comment by jsignell** [comment]
This a big diagnostic improvement and I love the narrative that you go through in https://github.com/dask/dask/pull/7992#issuecomment-952436239 - can we make that into a blog post or a how-to?

**Comment by quasiben** [comment]
+1 to writing up as a blogpost

**Comment by eriknw** [comment]
Aw, thanks for the kind words!

Yeah, I can write a blog post from this, but you must know how much it pains me to show off `dask.order` not doing well 😛 .

I'm about to go on vacation (hooray!), so it'll be *at least* a few weeks before I can get around to it.

**Comment by jsignell** [comment]
no worries, anytime is a good time :) it can be framed as how to understand or debug.

**Pull request merged**
