### PR TITLE
python setup.py test runs py.test

### PR DESCRIPTION
**Pull request by Horta**

### CODE REVIEW

**Comment by jakirkham** [comment]
Think you also need `pytest-runner` in `setup_requires`.

ref: https://docs.pytest.org/en/latest/goodpractices.html#integrating-with-setuptools-python-setup-py-test-pytest-runner

**Comment by jakirkham** [comment]
LGTM. Thoughts @mrocklin and @jcrist?

**Comment by mrocklin** [comment]
Just tried it out locally and it seems pretty nice.  +1 from me

**Comment by jcrist** [comment]
LGTM. Thanks @Horta. Merging.

**Pull request merged**
