### PR TITLE
Fix timezone metadata inference on parquet load

### LINKED ISSUE #4640: read_parquet does not handle timezones
Dask DataFrame method `read_parquet` does not read parquet timezone metadata (despite fastparquet handling this metadata), except if the file was written with fastparquet _and_ is being read with pyarrow.

This works:
```
import dask.dataframe as dd
import pandas as pd

df = pd.DataFrame([[0]], columns=['a'], dtype='datetime64[ns, UTC]')
df.to_parquet('tmp1.parquet', engine='fastparquet')
df = dd.read_parquet('tmp1.parquet', engine='pyarrow')
df.dtypes
# a    datetime64[ns, UTC]
# dtype: object

# But any other permutation of engines results in:
# a    datetime64[ns]
# dtype: object
```

`to_parquet` does correctly write timezones, for any permutation of read/write engines:
```
df.astype('datetime64[ns, UTC]').to_parquet('tmp2.parquet', engine='fastparquet')
pd.read_parquet('tmp2.parquet/part.0.parquet', engine='fastparquet').dtypes
# a    datetime64[ns, UTC]
# dtype: object
```

### PR DESCRIPTION
**Pull request by martindurant**
- [x] Tests added / passed
- [x] Passes `flake8 dask`

Will not pass until https://github.com/dask/fastparquet/pull/411 is merged and released

Fixes #4640 (but not very elegantly!)

### CODE REVIEW

**Comment by martindurant** [comment]
Does anyone know in which version of pyarrow timezones were added to the metadata?

**Comment by pentschev** [comment]
I believe this PR is fine from the codecov perspective. I'm still trying to understand what's going on with codecov, and I think it doesn't like PRs that don't have it's configuration file in it for some reason.

@martindurant would you mind merging current master in your branch so we can see if that solves codecov's complaints?

**Comment by pentschev** [comment]
It looks like Travis never returned its status here, it's been waiting for completion for about 12h now, but all tests have passed. Don't hold this due to that or codecov, go ahead and merge once reviewers are good ok with the changes.

**Comment by martindurant** [comment]
Would someone like to review this? I'll probably merge this evening if no one speaks.

**Pull request merged**
