### PR TITLE
Deprecate `zero_broadcast_dimensions` and `homogeneous_deepmap`

### PR DESCRIPTION
**Pull request by SnkSynthesis**
- [x] Tests added / passed
- [x] Passes `black dask` / `flake8 dask` / `isort dask`

Deprecate `zero_broadcast_dimensions` and `homogenous_deepmap` as mentioned in #8126

### CODE REVIEW

**Comment by jsignell** [comment]
ok to test

**Review by jsignell — APPROVED** [review]
Perfect!

**Review by jrbourbeau — COMMENTED** [review]
Thanks @SnkSynthesis!

It looks like the linting CI build is running into a formatting issue. See https://docs.dask.org/en/latest/develop.html#code-formatting for the code formatting checks that are automatically run (in this particular case, `black` would like to make a code formatting change)

**Comment by SnkSynthesis** [comment]
> Thanks @SnkSynthesis!
> 
> It looks like the linting CI build is running into a formatting issue. See https://docs.dask.org/en/latest/develop.html#code-formatting for the code formatting checks that are automatically run (in this particular case, `black` would like to make a code formatting change)

Okay, code formatted!

**Review by jrbourbeau — APPROVED** [review]
Thanks @SnkSynthesis -- will merge once CI finishes up

**Comment by jrbourbeau** [comment]
Note that the test failures here are unrelated to the changes in this PR and being resolved over in https://github.com/dask/dask/pull/8139. 

Also, I noticed this is your first code contribution to this repository. Welcome!

**Comment by SnkSynthesis** [comment]
Thank you, @jrbourbeau!

**Pull request merged**
