### PR TITLE
Remove blosc references

### LINKED ISSUE #9624: Drop blosc from envs and its mentions
I see that in https://github.com/dask/distributed/pull/6027 we drop blosc, but we forgot to cleanup over here in dask/dask see
https://github.com/dask/dask/search?q=blosc

I'll open a PR to clean this. :broom:

### PR DESCRIPTION
**Pull request by ncclementi**
- [x] Closes #9624
- [ ] Tests added / passed
- [x] Passes `pre-commit run --all-files`

### CODE REVIEW

**Comment by ncclementi** [comment]
@charlesbluca I see gpuCI is failing, would you mind taking a look?

**Comment by charlesbluca** [comment]
Yeah the gpuCI images shouldn't immediately be impacted by changes to the environment files, so this is definitely unrelated; let's rerun tests to see if this is an intermittent failure or if something is actually broken upstream.

**Comment by ncclementi** [comment]
> Yeah the gpuCI images shouldn't immediately be impacted by changes to the environment files, so this is definitely unrelated; let's rerun tests to see if this is an intermittent failure or if something is actually broken upstream.

Looks like re-run went ok :tada:

**Comment by ncclementi** [comment]
> Yeah the gpuCI images shouldn't immediately be impacted by changes to the environment files, so this is definitely unrelated; let's rerun tests to see if this is an intermittent failure or if something is actually broken upstream.

look like we are green 🎉 , thanks @charlesbluca !!

**Comment by charlesbluca** [comment]
> whoops, it looks like it's pending now. but when clicking on it says it passed, might be a tiny glitch

Yeah I think your quote of my original message containing the gpuCI triggering phrase started a new run 😅 looks like this is the previous run, which seems to be passing:

https://gpuci.gpuopenanalytics.com/job/dask/job/dask/job/prb/job/dask-prb/CUDA_VER=11.5,LINUX_VER=ubuntu18.04,PYTHON_VER=3.9,RAPIDS_VER=22.12/2882/console

**Review by ian-r-rose — APPROVED** [review]
Thanks @ncclementi!

**Pull request merged**
