### PR TITLE
Temporarily pin `fastparquet` in CI

### PR DESCRIPTION
**Pull request by jrbourbeau**

### CODE REVIEW

**Comment by jrbourbeau** [comment]
There are some CI failures which appear to be related to the latest `fastparquet` release using features from pandas which our minimum pandas version (0.25) doesn't support:

```python
 ___________ ERROR collecting dask/dataframe/io/tests/test_parquet.py ___________
dask/dataframe/io/tests/test_parquet.py:25: in <module>
    import fastparquet
/usr/share/miniconda3/envs/test-environment/lib/python3.7/site-packages/fastparquet/__init__.py:5: in <module>
    from .core import read_thrift
/usr/share/miniconda3/envs/test-environment/lib/python3.7/site-packages/fastparquet/core.py:13: in <module>
    from .converted_types import convert, simple, converts_inplace
/usr/share/miniconda3/envs/test-environment/lib/python3.7/site-packages/fastparquet/converted_types.py:69: in <module>
    np.dtype('bool'): pd.BooleanDtype()
/usr/share/miniconda3/envs/test-environment/lib/python3.7/site-packages/pandas/__init__.py:214: in __getattr__
    raise AttributeError("module 'pandas' has no attribute '{}'".format(name))
E   AttributeError: module 'pandas' has no attribute 'BooleanDtype'
```

cc @martindurant

**Comment by martindurant** [comment]
Booleans came in in v1.0.0, the one after the 0.25 line - which is 2 years old (today!). We can either skip this up update our min version, if people want. Yes, I realise that the requirement in fastparquet ought to have been updated :|

**Comment by jsignell** [comment]
If we are following the loose 18 month policy that was discussed in https://github.com/dask/dask/issues/7378, then we can update to pandas to `>=1.0.0` on July 30th. I'd say to fix this test, fastparquet should fix its requirements.txt.

**Comment by martindurant** [comment]
> I'd say to fix this test, fastparquet should fix its requirements.txt.

That won't affect the released version, of course.

**Comment by jsignell** [comment]
> That won't affect the released version, of course.

You could do a new build on conda-forge.

**Comment by martindurant** [comment]
Good idea.

**Comment by martindurant** [comment]
Can try kicking it again whenever we reckon conda-forge posts the new build

**Comment by jrbourbeau** [comment]
Thanks for the conda-forge update @martindurant. Bumping CI now...

**Comment by martindurant** [comment]
I don't know if the new build hasn't appeared yet in the channel metadata, or if the resolver will now insist on build 0, since it allows for the desired pandas version.

**Comment by jrbourbeau** [comment]
I might have bumped too early. I just did `conda create -n test fastparquet pandas` locally which pulled in the new `fast parquet` build (`conda-forge/osx-64::fastparquet-0.7.0-py39hc89836e_1`). Bumping CI again now

**Comment by jrbourbeau** [comment]
The linux Python 3.8 build is picking up build 1 of `fastparquet`, but the Python 3.7 build is installing build 0 still. Perhaps we  should open a PR over in https://github.com/conda-forge/admin-requests (like, for example, this PR https://github.com/conda-forge/admin-requests/pull/274) which marks build 0 as broken? cc'ing @jakirkham in case there's some other route we should go

**Comment by martindurant** [comment]
Ww should be able to remove build 0; but it might just get the earlier version. That would be OK too , I suppose.

**Comment by jrbourbeau** [comment]
Temporarily pinning `fastparquet` for Python 3.7 to try and unblock CI

**Comment by jrbourbeau** [comment]
Planning to merge this after CI finishes. I also opened up a PR in `conda-forge-repodata-patches-feedstock` which _should_ handle patching the `pandas` dependency for `fastparquet=0.7.0` (xref https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/152)

**Pull request merged**
