### PR TITLE
Update Travis to xenial

### PR DESCRIPTION
**Pull request by gliptak**

### CODE REVIEW

**Comment by mrocklin** [comment]
@jakirkham any thoughts/objections to this?

**Comment by mrocklin** [comment]
@gliptak I'm curious why you wanted to make this change.  Are there things in the shift to xenial that are important to help test?

**Comment by gliptak** [comment]
@mrocklin keeping up with Ubuntu versions and getting closer to current LTS ```18.04```

**Comment by jakirkham** [comment]
> any thoughts/objections to this?

No strong thoughts or objections from me.

**Comment by gliptak** [comment]
would you like to see updates?

**Comment by mrocklin** [comment]
I think that in general I'm not opposed to keeping things with older versions of Ubuntu.  It's sometimes nice for CI systems to lag a bit, because that way they reflect what is more commonly deployed.  Backwards compatibility also seems to be more common than forwards compatibility.

If there isn't a driving need for this then I recommend that we wait for a while on it.

**Pull request closed without merging**
