### PR TITLE
Pass username as 'user' when using pyarrow

### LINKED ISSUE #4437: "got an unexpected keyword argument 'username'" when reading from hdfs with authorization
```
  File "x.py", line 4, in <module>
    dd.read_csv('hdfs://user@example.org/file.csv')
  File "/Users/r/proj/env/lib/python3.7/site-packages/dask/dataframe/io/csv.py", line 488, in read
    **kwargs)
  File "/Users/r/proj/env/lib/python3.7/site-packages/dask/dataframe/io/csv.py", line 343, in read_pandas
    **(storage_options or {}))
  File "/Users/r/proj/env/lib/python3.7/site-packages/dask/bytes/core.py", line 80, in read_bytes
    storage_options=kwargs)
  File "/Users/r/proj/env/lib/python3.7/site-packages/dask/bytes/core.py", line 354, in get_fs_token_paths
    fs, fs_token = get_fs(protocol, options)
  File "/Users/r/proj/env/lib/python3.7/site-packages/dask/bytes/core.py", line 513, in get_fs
    fs = cls(**storage_options)
  File "/Users/r/proj/env/lib/python3.7/site-packages/dask/bytes/pyarrow.py", line 28, in __init__
    self.fs = pa.hdfs.HadoopFileSystem(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'username'
```

where x.py is:

```
import dask.dataframe as dd
dd.read_csv('hdfs://user@example.org/file.csv')
```

Dask version: '1.1.0'.

Pyarrow version: '0.12.0'.

Seems like bytes/utils.py extract username as "username" (https://github.com/dask/dask/blob/master/dask/bytes/utils.py#L81), while pyarrow expects "user" (https://github.com/apache/arrow/blob/master/python/pyarrow/hdfs.py#L205). It also seems like in both places those keys were used for a while now.

### PR DESCRIPTION
**Pull request by little-arhat**
fixes #4437

- [ ] Tests added / passed
- [v] Passes `flake8 dask`

### CODE REVIEW

**Comment by martindurant** [comment]
That looks fine, but it would be nice to see a test, if possible. Since HDFS is tricky to test, this needs to be marked for skipping, depending on the environment, as the other tests in test_hdfs.py are.

**Comment by martindurant** [comment]
btw: the failure appears to be from style:
```
dask/bytes/pyarrow.py:23:1: E302 expected 2 blank lines, found 1
dask/bytes/pyarrow.py:29:1: E302 expected 2 blank lines, found 1
dask/bytes/pyarrow.py:31:5: E301 expected 1 blank line, found 0
```

**Comment by little-arhat** [comment]
Seems like travis is failing due to flake8 failure:

`The command "if [[ $LINT == 'true' ]]; then flake8 dask; fi" exited with 1.` 

That's a bit strange as it passes locally. 

```
flake8 --version
3.6.0 (mccabe: 0.6.1, pycodestyle: 2.4.0, pyflakes: 2.0.0) CPython 3.7.2 on Darwin
```

Do I need special configuration for flake8 or something?

**Comment by martindurant** [comment]
Note sure about where the flake8 settings will come from, but it should be simple enough to correct the three errors shown in my comment above

**Comment by mrocklin** [comment]
Handling the flake8 errors elsewhere.  Those will be fixed shortly

**Comment by little-arhat** [comment]
@martindurant yeah, I've fixed them, and pushed new changes, and flake8 locally doesn't give those errors anymore (it used to, before I've fixed them). 

As you can see, there are 2 lines around `update_hdfs_options`, etc.

**Comment by martindurant** [comment]
In that case, I guess you can wait for @mrocklin 's fix to go in and merge from master at that point and hope to see the problem go away.

**Comment by mrocklin** [comment]
The flake8 fixes went in.  Tests here are looking good (though there was one conda failure which I've restarted)

**Comment by mrocklin** [comment]
Tests pass.  @martindurant I'll leave it to you to merge if you're happy with things here.

**Pull request merged**
