### PR TITLE
Spring cleaning

### PR DESCRIPTION
**Pull request by jcrist**
I noticed we'd accumulated some cruft over time. To solve this, I found unused functions using coverage, and unused top-level variables using a simple `ast` script. This PR removes all these.

- Delete unused functions and top-level variables
- Move some bytes-specific utility functions to `dask.bytes.utils` (last commit only, happy to revert)

Changes are split into separate many commits, so deleted/moved things that are used in external packages or that shouldn't be moved can be reverted.

### CODE REVIEW

**Comment by jcrist** [comment]
> - Move some bytes-specific utility functions to dask.bytes.utils (last commit only, happy to revert)

Looks like `dask.utils.infer_storage_options` is used in `distributed.hdfs`. Could add a patch there to move the import, or just revert this change. No strong opinions.

**Comment by jcrist** [comment]
Failures are due to ` ichart.yahoo.com` being down, resulting in an unrelated test failure.

**Comment by jcrist** [comment]
I hope to merge this later today. Ping @martindurant for thoughts on the move of some utils functions to `dask.bytes.utils` (last commit only). Afaict the only change that's needed is a patch to distributed to move the import of `infer_storage_options`. I like the move, as these are bytes related functions, but it's also not super important to move them.

**Comment by martindurant** [comment]
You wouldn't want users to absolutely require to keep their distributed and dask versions in sync, even though that should be common practice; should a reference to infer_storage_options be kept (not the code itself) to make sure we don't break anything? I am totally happy with the move itself.

**Comment by jcrist** [comment]
That's a fair point. Will add.

**Comment by jcrist** [comment]
Hmmm, that didn't work due to circular imports (tried a few simple things to fix them with no luck). I've moved the definition back, and imported it in `dask.bytes.utils`. All internal references are for `dask.bytes.utils`. Once distributed bumps the required dask version > this commit we can move the definition over.

**Comment by martindurant** [comment]
Sorry :|  A note should be made, then, to change this sometime later - perhaps next spring!

**Comment by jcrist** [comment]
There are comments in the code both at the import in `dask.bytes.utils` and at the definition. I think that's good enough.

**Pull request merged**
