### PR TITLE
Fix tests for new ``read_only`` kwarg in ``zarr=3``

### LINKED ISSUE #11515: ⚠️ Upstream CI failed ⚠️
[Workflow Run URL](https://github.com/dask/dask/actions/runs/11808903001)
<details><summary>Python 3.12 Test Summary</summary>

```
dask/array/tests/test_array_core.py::test_zarr_pass_store: TypeError: LocalStore.__init__() got an unexpected keyword argument 'mode'
dask/tests/test_order.py::test_array_store_final_order: TypeError: LocalStore.__init__() got an unexpected keyword argument 'mode'
dask/tests/test_distributed.py::test_zarr_distributed_with_explicit_directory_store: TypeError: LocalStore.__init__() got an unexpected keyword argument 'mode'
dask/tests/test_distributed.py::test_zarr_distributed_with_explicit_memory_store: TypeError: MemoryStore.__init__() got an unexpected keyword argument 'mode'
```

</details>

### PR DESCRIPTION
**Pull request by phofl**
- [ ] Closes #11515
- [ ] Tests added / passed
- [ ] Passes `pre-commit run --all-files`

### CODE REVIEW

**Review by jrbourbeau — APPROVED** [review]
Thanks @phofl, this LGTM if you've confirmed this fixes things (looks like it should). There's something weird going on with installing packages in the `upstream` CI build here

Also cc @jhamman for visibility

**Comment by jrbourbeau** [comment]
Nice, thanks. xref https://github.com/scikit-image/scikit-image/issues/7607 for anyone else who's interested

**Comment by phofl** [comment]
> if you've confirmed this fixes things (looks like it should)

I did not 😅 I was relying on CI for this, so lets rather wait until the upstream build is green

**Comment by jhamman** [comment]
Thanks @phofl for tackling this!

**Pull request merged**
