### PR TITLE
Test pivot_table against assert_eq

### PR DESCRIPTION
**Pull request by mrocklin**
So far these tests fail.

### CODE REVIEW

**Comment by mrocklin** [comment]
cc @TomAugspurger and @sinhrks who may have thoughts on how to improve this.

See #2052

**Comment by sinhrks** [comment]
I think the error is caused by the metadata (`Index.names`) difference as dask doesn't hold `Index.names` attr now. I think we can add skip option to `_check_dask`?

**Comment by TomAugspurger** [comment]
@mrocklin I think I have this working correctly. If you let me push to this branch (should be a checkmark on the right) I'll push them, or this patch should work (might have to rebase first). Or I can just open a new PR if that's easiest.

```patch
From 5b23c52efc2a9480b5ab2fe5006b4f32aa53b7a7 Mon Sep 17 00:00:00 2001
From: Tom Augspurger <tom.w.augspurger@gmail.com>
Date: Thu, 27 Apr 2017 11:58:01 -0500
Subject: [PATCH] Include name on the index

---
 dask/dataframe/reshape.py            |  4 ++--
 dask/dataframe/tests/test_reshape.py | 14 +++++++-------
 2 files changed, 9 insertions(+), 9 deletions(-)

diff --git a/dask/dataframe/reshape.py b/dask/dataframe/reshape.py
index b79c4731..e5db772f 100644
--- a/dask/dataframe/reshape.py
+++ b/dask/dataframe/reshape.py
@@ -134,8 +134,8 @@ def pivot_table(df, index=None, columns=None,
     # _emulate can't work for empty data
     # the result must have CategoricalIndex columns
     new_columns = pd.CategoricalIndex(df[columns].cat.categories, name=columns)
-    new_columns.categories.name = columns
-    meta = pd.DataFrame(columns=new_columns, dtype=np.float64)
+    meta = pd.DataFrame(columns=new_columns, dtype=np.float64,
+                        index=pd.Index([], name=index))
 
     kwargs = {'index': index, 'columns': columns, 'values': values}
 
diff --git a/dask/dataframe/tests/test_reshape.py b/dask/dataframe/tests/test_reshape.py
index 8c147acd..6e603119 100644
--- a/dask/dataframe/tests/test_reshape.py
+++ b/dask/dataframe/tests/test_reshape.py
@@ -188,8 +188,8 @@ def test_pivot_table_errors():
     ddf = dd.from_pandas(df, 2)
     ddf['C'] = ddf.C.astype('category')
     msg = "C must have known categories"
-    with tm.assertRaisesRegexp(ValueError, msg):
-        dd.pivot_table(ddf, index='A', columns='C', values=['B'])
+    with pytest.raises(ValueError) as err:
+        dd.pivot_table(ddf, index='A', columns='C', values=['B'], aggfunc='sum')
     assert msg in str(err.value)
 
     df = pd.DataFrame({'A': np.random.choice(list('abc'), size=10),
@@ -203,15 +203,15 @@ def test_pivot_table_errors():
 
 @pytest.mark.parametrize('aggfunc', ['mean', 'sum', 'count'])
 def test_index_columns_types(aggfunc):
-    df=pd.DataFrame({'index': [1, 2, 3, 1, 2, 3],
-                     'field': ["A", "A", "A", "B", "B", "B"],
-                     'value': [10, 20, 30, 100, 120, 130]})
+    df = pd.DataFrame({'index': [1, 2, 3, 1, 2, 3],
+                       'field': ["A", "A", "A", "B", "B", "B"],
+                       'value': [10, 20, 30, 100, 120, 130]})
     ddf = dd.from_pandas(df, 2)
     ddf = ddf.categorize('field')
 
     dpt = ddf.pivot_table(values="value", index="index", columns="field",
-            aggfunc=aggfunc)
+                          aggfunc=aggfunc)
     pt = df.pivot_table(values="value", index="index", columns="field",
-            aggfunc=aggfunc)
+                        aggfunc=aggfunc)
 
     assert_eq(pt, dpt)
-- 
2.12.2
```

**Comment by mrocklin** [comment]
Interestingly the checkbox was already checked

**Comment by mrocklin** [comment]
@TomAugspurger can you confirm that pushing to my branch fails ?

**Comment by TomAugspurger** [comment]
Sorry, I think it was because of how I check it out originally, the names weren't matching up.

And I had to do a force-push since I rebased.

**Pull request closed without merging**
