### PR TITLE
Move dask.async to dask.local

### LINKED ISSUE #1834: `dask.async` will become illegal in Python 3.7
According to https://docs.python.org/3.6/whatsnew/3.6.html#new-keywords:
> `async` and `await` are not recommended to be used as variable, class, function or module names. Introduced by PEP 492 in Python 3.5, they will become proper keywords in Python 3.7. Starting in Python 3.6, the use of `async` or `await` as names will generate a DeprecationWarning.

### PR DESCRIPTION
**Pull request by jcrist**
In Python 3.7 `async` will become a keyword and `dask.async` will no longer be a valid module name. We move `dask.async` to `dask.scheduler` and deprecate the old module. The documentation has been updated accordingly.

Fixes #1834.

### CODE REVIEW

**Comment by jcrist** [comment]
An alternative name I considered was `dask.local`. Happy to change to something else if desired.

**Comment by mrocklin** [comment]
Hrm, `dask.scheduler` does somewhat conflict with the distributed scheduler.  I think it's worth thinking about something like `dask.local`.

Is there any way to warn users?  Perhaps keep around async.py and fill it with functions that warn, then call the correct method?

**Comment by mrocklin** [comment]
Also thank you for doing this.

**Comment by jcrist** [comment]
> Is there any way to warn users? Perhaps keep around async.py and fill it with functions that warn, then call the correct method?

I did that for the two most likely to be used functions. The rest have changed periodically and I would be surprised if they're in use.

**Comment by mrocklin** [comment]
Grand.  Thanks

**Comment by jcrist** [comment]
Renamed to `dask.local`. Should be good to go.

**Comment by jcrist** [comment]
Planning to merge tomorrow if no comment.

**Pull request merged**
