### PR TITLE
Update the pytest version for TravisCI

### PR DESCRIPTION
**Pull request by garaud**
- [X] Tests added / passed
- [X] Passes `flake8 dask`

Just update the pytest version to `3.10`. All tests passed with py36 on my laptop.

### CODE REVIEW

**Comment by garaud** [comment]
According to the python version on TravisCI, the selected pytest version can be `3.8` or `3.10`. All tests passed!

I wonder why the job for the Python 3.6 version is often slower than the others, i.e. 2.7, 3.5 and 3.7.

**Comment by mrocklin** [comment]
This seems good to me.  Merging tomorrow if there are no further comments.

**Comment by garaud** [comment]
Ok, thanks.

**Comment by mrocklin** [comment]
Thanks @garaud !

**Pull request merged**
