### PR TITLE
corrected links to documentation from Examples

### PR DESCRIPTION
**Pull request by gdmcbain**
All pointed to the documentation for <array>.

### CODE REVIEW

**Comment by mrocklin** [comment]
Thanks!  This is great.  The Travis.ci error is unrelated.  Tracking it down now.

**Comment by mrocklin** [comment]
@jcrist any thoughts on what is happening here?

**Comment by jcrist** [comment]
The error occurs in that test run only because we collect doctests in that run. The failure is caused by the distributed recipe in the main channel not having s3fs as a dependency, while it is a dependency in the conda-forge channel (https://github.com/conda-forge/distributed-feedstock/blob/master/recipe/meta.yaml#L37). The main channel must have recently updated. Not sure why the difference in recipes, I would have expected them to be the same.

**Comment by jcrist** [comment]
Error fixed in #1559. Merging this now, thanks!

**Pull request merged**
