### PR TITLE
[WIP] Upstream fixes

### PR DESCRIPTION
**Pull request by jrbourbeau**
xref https://github.com/dask/dask/issues/10347

### CODE REVIEW

**Comment by graingert** [comment]
it looks like pyarrow doesn't support numpy 2

https://github.com/apache/arrow/blob/334c93726f3c9d9e69eb51136c7f354974c739fd/python/pyarrow/pandas_compat.py#L101

**Comment by graingert** [comment]
With the new pyarrow nightly I'm still getting warnings from pandas eg https://github.com/pandas-dev/pandas/pull/54155/files

**Comment by graingert** [comment]
requires https://github.com/dask/fastparquet/pull/886/files

**Comment by jakirkham** [comment]
Were these already added with PR ( https://github.com/dask/dask/pull/10549 )?

**Comment by jrbourbeau** [comment]
Thanks for following up here @jakirkham. Closing this PR as it's no longer needed

**Pull request closed without merging**
