### PR TITLE
Remove `kwargs` from `make_blockwise_graph`

### PR DESCRIPTION
**Pull request by fjetter**
Was reading a bit of code in this vicinity and stumbled over the kwargs. I believe they are nowhere used, at least not in dask/dask. Couldn't find any reference in other projects either (xarray, cudf, ??).

If they can be dropped this simplifies some code

### CODE REVIEW

**Comment by fjetter** [comment]
Why is there no CI running for this?

**Comment by mrocklin** [comment]
cc @rjzamora

**Review by jrbourbeau — COMMENTED** [review]
@rjzamora can you take a look?

**Review by rjzamora — APPROVED** [review]
This change seems like a net positive to me. Thanks @fjetter !

Although I suppose it is possible that downstream users/libraries are using `kwargs` with `make_blockwise_graph`, it seems pretty unlikely to me. I'm assuming that this function is only really used within `dask.blockwise` itself, where the convention is to embed key-word arguments into the callable function (usually a `SubgraphCallable`).

I suppose we *could* add a clear error message to inform the user that `make_blockwise_graph` no longer accepts arbitrary key-word arguments. However, I really doubt that such an error is necessary, so I'd be comfortable either way.

**Review by jrbourbeau — COMMENTED** [review]
Thanks for the PR @fjetter and reviewing @rjzamora

**Pull request merged**
