### PR TITLE
Add norm

### PR DESCRIPTION
**Pull request by jakirkham**
Adds a Dask Array implementation of [`numpy.linalg.norm`]( https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.norm.html ).

### CODE REVIEW

**Comment by jakirkham** [comment]
Any thoughts on this?

**Comment by mrocklin** [comment]
This looks great to me.  Merging soon if no one else has any objections.

**Comment by jcrist** [comment]
We also have `da.vnorm`/`da.Array.vnorm`, which is just a limited `norm` (added very early on). We should probably deprecate that function/method, and point to `da.linalg.norm` instead.

**Comment by jakirkham** [comment]
Also looked at rewriting `vnorm` to use `norm`, but found two issue. First `vnorm` has an `out` parameter and `norm` does not. Maybe there is an easy workaround for this though (`copyto`?). Second `vnorm` doesn't use `abs` when `ord` is divisible by 2, which could result in a complex result for complex data. Though this is arguably a bug. If we can make some decisions on these points, could include that change here as well.

**Comment by mrocklin** [comment]
Vector norms and matrix norms are different.  It may make sense to keep both.  cc @shoyer

**Comment by jakirkham** [comment]
Sure. Though the `norm` function from NumPy does both through the same API as this does. So this could reasonably replace `vnorm` and/or clean out some code.

**Comment by jakirkham** [comment]
Seems a couple of Travis CI builds failed spuriously with unrelated errors. Any chance we could get a restart?

**Comment by mrocklin** [comment]
Unfortunately the errors here aren't spurious.  We're now including checks for memory leaks dask.distributed testing system.  They're complaining here because there appears to be 4GB of leaked data around.  We can turn these checks off, but they are reporting a genuine issue with the dask test suite (though probably not with the changes here).

**Comment by jakirkham** [comment]
I see. It seems like there are similar [failures in `master`]( https://travis-ci.org/dask/dask/builds/263818356 ).

**Comment by mrocklin** [comment]
I'll have time to deal with this tomorrow.

**Comment by mrocklin** [comment]
Tests pass. It sounds like the norm/vnorm question is still alive.

**Comment by jakirkham** [comment]
Thanks @mrocklin.

As for `vnorm`, IMHO that can easily be settled in a subsequent issue/PR. It's unclear to me what we want to do with `vnorm` at this time. That said, this `norm` function nicely provides the functionality that NumPy also provides for Dask Array's.

**Comment by mrocklin** [comment]
Fair enough.  This looks good to me.  Merging.

**Comment by jakirkham** [comment]
Thanks @mrocklin.

**Comment by mrocklin** [comment]
Thank you @jakirkham !

**Comment by jakirkham** [comment]
Forgot to add it to the docs. Fix in PR ( https://github.com/dask/dask/pull/2605 ).

**Comment by jakirkham** [comment]
Opened issue ( https://github.com/dask/dask/issues/2606 ) to determine what to do with `vnorm`.

**Pull request merged**
