### PR TITLE
`DataFrame._data` deprecation in `pandas`

### PR DESCRIPTION
**Pull request by j-bennet**
Fixes test failure in upstream:

```
FAILED dask/dataframe/tseries/tests/test_resample.py::test_series_resample[frame-ohlc-5-h-left-right] - FutureWarning: DataFrame._data is deprecated and will be removed in a future version. Use public APIs instead.
```

Xref https://github.com/pandas-dev/pandas/pull/52003.

- [x] Tests added / passed
- [x] Passes `pre-commit run --all-files`

### CODE REVIEW

**Review by jrbourbeau — COMMENTED** [review]
Thanks @j-bennet! I pushed a small commit to just use `._mgr` unconditionally since that appears to exist for all supported `pandas` versions (including dev `pandas`). 

@phofl the deprecation warning says to use a public API instead of `._data`. `._mgr` works, but is still private. Is there a public API you'd recommend? Alternatively, is there a different approach we could take in this function? This function is meant to produce a unique, deterministic hash for a given `pd.DataFrame`

**Comment by phofl** [comment]
``_mgr`` should be fine for now.

You could iterate over all columns of the DataFrame to collect the arrays, but this is obviously slower then accessing them directly. So not really a good idea if performance is relevant here. I guess ``hash_pandas_object`` is not what you are looking for?

**Comment by jrbourbeau** [comment]
> _mgr should be fine for now.

Sounds good 👍 

> I guess `hash_pandas_object` is not what you are looking for?

Ah, good point. If there was a utility in `pandas` that we could offload this to, and there weren't any serious performance regressions, we probably would. I'll open a separate issue for this

**Comment by jrbourbeau** [comment]
xref https://github.com/dask/dask/issues/10083

**Pull request merged**
