### PR TITLE
Use cummulative sum in bincount.

### PR DESCRIPTION
**Pull request by rainwoodman**
The old algorithm uses a simple reduction. I worry it implies
every bincount must have finished (and results stored in memory)
before the reduction starts. When minlength is large this may
use excessive memory. (e.g. using bincount to build full sky healpix
maps of high resolution. )

The new algorithm adds many sum operations that gradually reduces
the sums. The assumption is that the dask scheduler will realize
the partial reduction can occur as the partial bincounts are computed,
and dispose any intermediate results that is no longer of use.

Nevertheless I did not observe much of an improvement in my test appliation.
But perhaps there are other factors that I weren't able to isolate.

- [x] Tests added / passed
- [ ] Passes `flake8 dask`

### CODE REVIEW

**Comment by mrocklin** [comment]
Thanks for the fix @rainwoodman .  In general I agree that this can help to reduce maximum memory use if the number of bins is very large.  However it also imposes an ordering on the computation.  I wonder if a tree-reduction might be more appropriate here, where we sum together every 16 intermediate chunks or so, and then sum the sums.  This is what we do with most of the other reductions.  Actually I wonder if it would be possible to reuse the tree reduction code with bincount.

My guess is that using tree reductions rather than linear summing will reduce the amount of task coordination overhead considerably, which, at least for other operations, has shown itself to be an occasional pain point.

**Comment by mrocklin** [comment]
To be clear, what I'm trying to avoid here is the O(n) number of sequential tasks in order to compute the bincount.  I think that with a tree reduction we should be able to get this down to O(log(n)) with a decently low base (this is the `split_every=` keyword I think)

**Comment by rainwoodman** [comment]
I agree a tree algorithm has more potential -- I'll take a stab. To be clear, are you suggesting to add asplit_every keyword to the function?

**Comment by mrocklin** [comment]
Ideally the existing tree_reduce algorithm would work for you:

https://github.com/dask/dask/blob/95c675037a6c15d8fe288fb7c9fee6bd04368805/dask/array/reductions.py#L156-L157

Or even the standard `reduction` algorithm

https://github.com/dask/dask/blob/95c675037a6c15d8fe288fb7c9fee6bd04368805/dask/array/reductions.py#L43-L45

However, I suspect that this might be more complex because of the fact that the intermediate of the reduction are arrays rather than scalars.  I wouldn't be surprised if those functions needed to be generalized somewhat.  I'm not sure though, it has been a little while since I looked at this code.

**Comment by rainwoodman** [comment]
Looks like at least concatenate=False needs to be set.

So far the function partial_reduce looks cryptic. I am a bit concerned
about book keeping of shapes of dimensions, which do not apply here at all;
so skipping should be the direction to generalize, if currently it can't be
skipped.

**Comment by mrocklin** [comment]
If it is easy to make these changes in a way that does not disrupt other operations then that might be a good path.  Ways to make `partial_reduce` less cryptic would also be welcome :)

**Comment by mrocklin** [comment]
Checking in here @rainwoodman .  Should we keep this open, or have you moved on for now?

**Comment by rainwoodman** [comment]
I probably won't be using dask in-depth for a while, and unlikely get around to finish this. Feel free to close this or reassign!

**Comment by jrbourbeau** [comment]
Closing based on https://github.com/dask/dask/pull/4491#issuecomment-488175753. Feel free to reopen this PR if you'd like to pick this up again

**Pull request closed without merging**
