### PR TITLE
Merge 0.17.x with master

### PR DESCRIPTION
**Pull request by jakirkham**
Should refresh the changelog in `master`, which should fix the issue noted by @crusaderky in ( https://github.com/dask/dask/pull/3505#issuecomment-389715649 ). Please double check this as the merge conflict was messy. Note we may want to use a standard merge commit here to ensure the 0.17.5 tag is reachable from `master` for things like `versioneer`.

cc @TomAugspurger @mrocklin

### CODE REVIEW

**Comment by mrocklin** [comment]
I'm not sure I understand the virtue of merging the commits back into the main branch, different versions of them are already in history elsewhere, no?  My understanding was that 0.17.5 would not be in the mainline history.

**Comment by TomAugspurger** [comment]
Agreed. I think the only relevant commit is 6126fc3. Everything else should still be in master, aside from e74f4ee and b2bed5e, which I don't think we want.

**Comment by jakirkham** [comment]
> Note we may want to use a standard merge commit here to ensure the 0.17.5 tag is reachable from `master` for things like `versioneer`.

Here's the current behavior on `master` for context.

```
$ python setup.py --version
0.17.4+20.g83107230
```

Ideally this would be a dev version based off of 0.17.5 instead of 0.17.4. Hence the merge commit suggestion.

**Comment by TomAugspurger** [comment]
Mmm. With pandas we typically make a .dev0 tag with the next version to keep it ahead of any backport branches.

________________________________

**Comment by mrocklin** [comment]
Is it feasible to ignore this problem until the next release, at which
point it possibly becomes less important?

**Comment by jakirkham** [comment]
As noted in the OP (and requested to be fixed by others), the changelog remains in accurate in `master`, which this fixes.

Honestly this seems like an easy fix for both issues. Not really understanding why it hasn't been merged yet.

**Comment by jakirkham** [comment]
> aside from e74f4ee and b2bed5e, which I don't think we want.

If this is the concern, could explicitly revert these changes before merging. However as the diff against `master` shows, they won't be included. That said, would be happy to do this if it would speed up resolution of this issue. Please let me know if this or something else would help. :)

**Comment by jakirkham** [comment]
Ah, thought I fixed the merge conflict earlier today with latest `master`, no? Looks ok from here. That said, definitely have seen mobile apps misreport this sort of thing before. :)

**Comment by TomAugspurger** [comment]
Oh, sorry I still had it set to "rebase and merge". The diff looks good, and since the 0.17.5 release commit is in there, it gets master ahead of 0.17.x again.

Thanks for fixing this up!

**Pull request merged**
