### PR TITLE
Deprecate 'inplace' argument for dask series renaming

### PR DESCRIPTION
**Pull request by marcelned**
See issue #8082

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by jsignell** [comment]
ok to test

**Comment by jsignell** [comment]
Thanks @marcelned for making this change - you might need to update some tests as well,  but CI will tell us if that's the case.

**Comment by jsignell** [comment]
Ok! Looks like this needs some linting and some changes in the tests. Here are the docs about how to contribute to dask: https://docs.dask.org/en/latest/develop.html#contributing-to-code let me know if you run into an issues.

**Comment by jsignell** [comment]
rerun tests

**Review by jcrist — APPROVED** [review]
Thanks @marcelned, this looks good to me. Merging.

**Pull request merged**
