### PR TITLE
Fix reduction with empty tuple axis

### LINKED ISSUE #4996: Computing `.var(axis=())` fails
Seeing the following failure with using `.var(axis=())` on `master`. This does not occur when using 1.2.2.

```python
In [1]: import dask.array as da                                                 

In [2]: a = da.random.random((10, 11, 12), chunks=5)                            

In [3]: a.var(axis=())                                                          
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-3-60e5d6560565> in <module>
----> 1 a.var(axis=())

~/Developer/dask/dask/array/core.py in var(self, axis, dtype, keepdims, ddof, split_every, out)
   1720         from .reductions import var
   1721         return var(self, axis=axis, dtype=dtype, keepdims=keepdims, ddof=ddof,
-> 1722                    split_every=split_every, out=out)
   1723 
   1724     def moment(self, order, axis=None, dtype=None, keepdims=False, ddof=0,

~/Developer/dask/dask/array/reductions.py in var(a, axis, dtype, keepdims, ddof, split_every, out)
    585                      keepdims=keepdims, dtype=dt, split_every=split_every,
    586                      combine=moment_combine, name='var', out=out,
--> 587                      concatenate=False)
    588 
    589 

~/Developer/dask/dask/array/reductions.py in reduction(x, chunk, aggregate, axis, keepdims, dtype, split_every, combine, name, out, concatenate, output_size, meta)
    161     result = _tree_reduce(tmp, aggregate, axis, keepdims, dtype, split_every,
    162                           combine, name=name, concatenate=concatenate,
--> 163                           reduced_meta=reduced_meta)
    164     if keepdims and output_size != 1:
    165         result._chunks = tuple((output_size, ) if i in axis else c

~/Developer/dask/dask/array/reductions.py in _tree_reduce(x, aggregate, axis, keepdims, dtype, split_every, combine, name, concatenate, reduced_meta)
    203     return partial_reduce(func, x, split_every, keepdims=keepdims, dtype=dtype,
    204                           name=(name or funcname(aggregate)) + '-aggregate',
--> 205                           reduced_meta=reduced_meta)
    206 
    207 

~/Developer/dask/dask/array/reductions.py in partial_reduce(func, x, split_every, keepdims, dtype, name, reduced_meta)
    247     if reduced_meta is not None:
    248         try:
--> 249             meta = func(reduced_meta, meta=True)
    250         # no meta keyword argument exists for func, and it isn't required
    251         except TypeError:

~/Developer/dask/dask/array/reductions.py in moment_agg(pairs, order, ddof, dtype, sum, axis, meta, **kwargs)
    524 
    525     ns = deepmap(lambda pair: pair['n'], pairs) if not meta else pairs
--> 526     ns = _concatenate2(ns, axes=axis)
    527     n = ns.sum(axis=axis, **keepdim_kw)
    528 

~/Developer/dask/dask/array/core.py in _concatenate2(arrays, axes)
    226         arrays = [_concatenate2(a, axes=axes[1:]) for a in arrays]
    227     concatenate = concatenate_lookup.dispatch(type(max(arrays, key=lambda x: getattr(x, '__array_priority__', 0))))
--> 228     return concatenate(arrays, axis=axes[0])
    229 
    230 

IndexError: tuple index out of range
```

Note: This also happens with `.std(axis=())`.

### PR DESCRIPTION
**Pull request by pentschev**
Fixes #4996 and #4997.

cc @jakirkham

### CODE REVIEW

**Comment by pentschev** [comment]
I tried to cover all test cases that already exist in Dask utilizing `axis`. Some were purposely left out because they're not supported by NumPy, such as `argmin`.

**Comment by jakirkham** [comment]
Thanks for working on this Peter! Would also grab the tests from PR ( https://github.com/dask/dask/pull/4993 ) if you haven't already.

**Comment by pentschev** [comment]
Oh sorry, I missed #4993. The second test is in this PR, but not the first one. Would you rather have me add them here or simply merge both PRs?

**Comment by jakirkham** [comment]
Please feel free to steal the code from the PR.

**Comment by pentschev** [comment]
Added it now, thanks @jakirkham for pointing to that PR.

**Comment by mrocklin** [comment]
Merging this in.  Thanks @pentschev !

**Pull request merged**
