### PR TITLE
Skip test_s3 for PYTHONOPTIMIZE=2 test

### PR DESCRIPTION
**Pull request by jcrist**
New release of moto breaks with `PYTHONOPTIMIZE=2`.

See https://travis-ci.org/dask/dask/jobs/413384495

### CODE REVIEW

**Comment by jcrist** [comment]
Failure is a periodic failure, but this fixed the issue with the PYTHONOPTIMIZE build. Merging, as our build is currently broken due to this.

**Comment by mrocklin** [comment]
Has anyone reported this upstream?  If not then should we?

**Comment by jcrist** [comment]
I'm not sure if PYTHONOPTIMIZE compatibility is a bug, but maybe.

**Comment by jcrist** [comment]
The issue has to do with a new dependency, and actually is an issue in pycparser.

**Comment by jcrist** [comment]
Already discussed and shotdown: https://github.com/eliben/pycparser/issues/205

**Pull request merged**
