### PR TITLE
Support tokenizing `datetime.time`

### LINKED ISSUE #9527: Dask does not support tokenizing `datetime.time`, only `datetime.date` and `datetime.datetime`
Did not see a prior reported issue and very straightforward issue:

```
tokenize(time(1,2,3)) != tokenize(time(1,2,3))
```

PR in https://github.com/dask/dask/pull/9528

### PR DESCRIPTION
**Pull request by timkpaine**
- [x] Closes #9527 
- [x] Tests added / passed
- [x] Passes `pre-commit run --all-files`

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

Admins can comment `ok to test` to allow this one PR to run or `add to allowlist` to allow all future PRs from the same author to run.

**Review by jrbourbeau — COMMENTED** [review]
Thanks @timkpaine! Overall this looks good. `datetime.time` objects can also have `microseconds` and `tzinfo` specified -- could you add test coverage for those as well?

**Comment by timkpaine** [comment]
@jrbourbeau added

**Review by jrbourbeau — APPROVED** [review]
This looks great -- thanks @timkpaine! 

Also, I noticed this is your first code contribution to this repository. Welcome!

**Pull request merged**
