### PR TITLE
Support negative drop_axis in map_blocks and map_overlap

### PR DESCRIPTION
**Pull request by grlee77**
This PR allows the `drop_axis` argument of `map_blocks` and `map_overlap` to use negative axis values in the same manner as functions in the NumPy API. 

This improves on #8064 which added a more informative error message on negative `drop_axis` (closing #7924). This PR changes the error to only occur when the specified axis exceeds the dimensions of the output array, otherwise the axis is converted to the equivalent positive-valued axis.

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by jrbourbeau** [comment]
add to allowlist

**Review by jrbourbeau — COMMENTED** [review]
Thanks @grlee77! It looks like there are some code formatting issues -- see https://docs.dask.org/en/latest/develop.html#code-formatting for what formatting checks to run or how to (optionally) have these automatically run with `pre-commit`

**Comment by grlee77** [comment]
> Thanks @grlee77! It looks like there are some code formatting issues -- see https://docs.dask.org/en/latest/develop.html#code-formatting for what formatting checks to run or how to (optionally) have these automatically run with pre-commit

Yeah, I had not installed pre-commit for this repo. It should be fixed now

**Comment by jsignell** [comment]
I'm going to re-run the windows tests; if they pass this is ready to go.

**Comment by jsignell** [comment]
Thanks @grlee77 !

**Pull request merged**
