### PR TITLE
Add documentation example that persists to a file.

### PR DESCRIPTION
**Pull request by SultanOrazbayev**
Based on this question: https://stackoverflow.com/a/75086108/10693596

- [x] Tests mostly passed (the one that erred seems to be unrelated to this PR)
- [x] Passes `pre-commit run --all-files`

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

Admins can comment `ok to test` to allow this one PR to run or `add to allowlist` to allow all future PRs from the same author to run.

**Review by jrbourbeau — COMMENTED** [review]
Thanks for the PR @SultanOrazbayev. How does this differ from the example directly above? They appear to be the same to me

https://github.com/dask/dask/blob/66f0cde91a5cde9dee31ec227a5164d5fe489098/dask/dataframe/io/sql.py#L530-L538

**Comment by SultanOrazbayev** [comment]
The example is the same (reuses the same data) except for persisting to a regular file vs `tmpfile`. Not sure how valuable this is, but the question came up, so seemed like a quick thing to suggest (but I can also understand if you want to keep the docs a bit more streamlined).

**Comment by jrbourbeau** [comment]
I see -- thanks for clarifying. In that case, I'd prefer to keep the current example. The `tmpfile` context manager is just being used so that we can clean up after ourselves when doctests are run and this example is actually executed.

**Comment by SultanOrazbayev** [comment]
Sure, this makes sense. I doubt it's `a` common issue.

**Pull request closed without merging**
