### PR TITLE
Add hdfs3 to builds

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

- [x] Tests added / passed
- [ ] Passes `flake8 dask`

### CODE REVIEW

**Comment by mrocklin** [comment]
My understanding of this topic may be out of date.  I'll leave this to
other maintainers to handle.

**Comment by martindurant** [comment]
There was at some testing of this previously, I thought; but agree that no effort should be made for hdfs3 any more, since we recommend arrow-hdfs instead.

**Comment by gliptak** [comment]
@mrocklin @martindurant how do you see this being updated?

**Comment by mrocklin** [comment]
@martindurant any thoughts here?

**Comment by martindurant** [comment]
I say don't add it. A *separate* issue to add pyarrow-hdfs and a cluster to test on could be considered, but I think would complicate things too much, as the tests would need to run on the edge-node of the cluster.

**Pull request closed without merging**
