### PR TITLE
Fixes for `svd` with `__array_function__`

### PR DESCRIPTION
**Pull request by pentschev**
Fixes a couple of small issues that were introduced with `__array_function__`-only cases in the works of #6616 and #6623 .

### CODE REVIEW

**Comment by pentschev** [comment]
Failure seems completely unrelated to this PR, any ideas about the origin for the error?

**Comment by TomAugspurger** [comment]
Agreed that the failure looks unrelated. I haven't seen that failure before and I wasn't able to reproduce it locally.

**Comment by TomAugspurger** [comment]
Oh, I take that back. When repeating the test 500 times I did eventually get a failure. I didn't have `--pdb` turned on though so it's gone.

Anyway, I'll take a look at it separately.

**Review by TomAugspurger — APPROVED** [review]

**Comment by pentschev** [comment]
Thanks @TomAugspurger for checking and merging!

**Pull request merged**
