### PR TITLE
Added color to show the materialization of HLG layers

### PR DESCRIPTION
**Pull request by freyam**
- [ ] Tests added 
- [x] Tests passed
- [x] Passes `black dask` / `flake8 dask` / `isort dask`

/cc @martindurant @GenevieveBuckley 

Hi. I have opened this PR to add a little color to the Graphviz visualization of the HighLevelGraphs.

## The Issue

Currently, Dask doesn't do anything differently to distinguish the materialized layers from the unmaterialized layers in the final output of the `HLG.dask.visualize()`.

image

As seen here, `head` is actually a materialized layer, but it is visualized the same as the `same-shuffle` and the `make-timeseries` layers.

## The Fix

I have added a simple light gray fill color to all the materialized layer nodes.

```py
if hg.layers[k].is_materialized() is True:
    attrs.setdefault("style", "filled")
    attrs.setdefault("fillcolor", "gray94")
```

This adds **gray84** fill color to the node.

## The Colour

Graphviz supports a wide range of colors. (https://graphviz.org/doc/info/colors.html)
image

The color I have chosen (**gray94**) has been inspired by the already existing HLG HTML Representation.
image

## The Demo

image

[Open to Discussion]

### CODE REVIEW

**Comment by freyam** [comment]
The failing tests are part of the `test_stats`. Surprisingly, I didn't get any FAILED locally.
> dask/array/tests/test_stats.py

**Comment by mrocklin** [comment]
Thank you for submitting this Freyam.

FWIW, I'd love to see us focus on things other than if a layer is
materialized.  I think that this attribute is mostly interesting to just a
few internal devs and not of great interest to users.  Because of this I
wouldn't want us to put a lot of visual weight behind this difference.
Users might wonder why one layer is shaded so differently from another, and
this difference doesn't really affect them.  For this PR in particular I
guess it's ok, but we would probably want to reduce the visual difference
by using a grey color that was less distinct.

In the future I think that users would be very interested in attributes
like layer size and type, as well as collection attributes like chunking
structure in the case of dask arrays.  Personally I would encourage you to
focus your efforts there.  You might also want to raise issues with
proposed changes in the future.  That will help you to get feedback on idea
from a broad set of people in the community, rather than just the one or
two that are engaging in the gsoc slack channel.

**Comment by freyam** [comment]
Yes! I agree with that.

**Comment by freyam** [comment]
For this PR, I have used a very light gray (gray94) to not make the materialized layers not very distinct.

image

**Comment by freyam** [comment]
Closing this PR for now.
Further Discussion: https://github.com/dask/dask/issues/7847

**Pull request closed without merging**
