### PR TITLE
Use chunks="auto" in array creation routines

### PR DESCRIPTION
**Pull request by mrocklin**
*We may or may not want to do this.  Feedback welcome.*

This uses the chunks="auto" option in array creation routines like
ones, zeros, random, arange, and so on.

```python
>>> import dask.array as da
    
>>> x = da.ones((10000, 10000))
>>> x.chunks
((2500, 2500, 2500, 2500), (2500, 2500, 2500, 2500))
```

- [x] Tests added / passed
- [x] Passes `flake8 dask`

cc @shoyer @jakirkham

### CODE REVIEW

**Comment by mrocklin** [comment]
Historically the counter-argument to this has been that we want users to think about how they want to chunk up their data before they start using dask.array.

The counter-counter-argument is that a novice user's first guess at this is fairly likely to be poor.

**Comment by shoyer** [comment]
In my experience these array creation functions are mostly for demo purposes -- real workloads use data loaded from disk or another system.

Given that, I think this is pretty harmless and possibly a slight win, given that it lowers the barrier to entry for new users to try dask.array.

**Comment by hmaarrfk** [comment]
I'm kinda against this.

Dask is not going to be a "first" numerical computation library. I would expect users to play around with `fortran` order arrays before looking at chunks in dask.

Having seen those, and noticing the important effects of memory alignment and allocation, it seems fine to force the users to think about chunk sizes.

**Comment by mrocklin** [comment]
The challenge is that we often see people who do something like `da.ones((1000, 1000), chunks=(32, 32))` or `da.ones((1000, 1000), chunks=(1, 1))` or something similar that gives poor performance.

**Comment by hmaarrfk** [comment]
Is the output of `auto_chunks` understandable by a new user? 
Maybe point them to start in that direction in the error message?

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-16-7f742e37cfac> in <module>
     10   """
     11 
---> 12 raise ValueError(sample_dask_error_message)

ValueError: You must specify a chunks= keyword argument.
This specifies the chunksize of your array blocks.  <--- Maybe this line can be omitted
Chunk sizes between 10MB-1GB are common.
For your array, we recommend specifying

  chunks=(1, 25, 7, 80, 90)

See the following documentation page for details:
  https://docs.dask.org/en/latest/array-chunks.html     <- I think this link is better
```

**Comment by mrocklin** [comment]
In general I agree that informative error messages are useful to point users in good directions.  However I still think that having this behavior by default might not be a bad thing.  I think that my thoughts mostly reflect @shoyer's above.

**Comment by hmaarrfk** [comment]
ok.

**Pull request merged**
