### PR TITLE
Add einsum autofunction in docs

### PR DESCRIPTION
**Pull request by sjperkins**
I added `einsum` in the summary but forgot to add the autofunction.

- [ ] Tests added / passed
- [x] Passes `flake8 dask`
- [x] Fully documented, including `docs/source/changelog.rst` for all changes
      and one of the `docs/source/*-api.rst` files for new API

### CODE REVIEW

**Comment by jakirkham** [comment]
Thanks for the follow up, @sjperkins.

Also needs to go in the `Top level user functions:` section.

CI is unnecessary for this so feel free to add `[ci skip]` to the next commit message pushed.

**Comment by mrocklin** [comment]
Yeah, looks like bcolz tests are failing hard.  Probably something changed upstream.

**Comment by jakirkham** [comment]
Looks like a build issue to me. Like maybe it is built with and using AVX2 instructions and Travis CI doesn't support them.

**Comment by mrocklin** [comment]
> Also needs to go in the Top level user functions: section.

Whoops.  I merged early on this.  My apologies.

**Comment by sjperkins** [comment]
> Also needs to go in the Top level user functions: section.

I already did this in the main PR, so I think the early merge is fine. The docs seemed to build correctly locally on my machine.

**Comment by jakirkham** [comment]
Yep, the `bcolz` rebuild fixed it.

There are two other failures. One is issue ( https://github.com/dask/dask/issues/3345 ) and [the other is explained in this comment]( https://github.com/dask/dask/pull/3412#issuecomment-383122235 ).

ref: https://travis-ci.org/dask/dask/builds/369157404

**Pull request merged**
