### PR TITLE
Fix Pandas 1.0 version comparison

### LINKED ISSUE #5848: str.extract StringDtype works with pandas 1.0.0rc0 but fails with pandas 1.0.0 final (TypeError)
This is a continuation of #5833 .

Using dask 2.10.0 and pandas 1.0.0rc0, I am able to use `.str.extract(...)` on a column with a pandas string dtype.  However, with dask 2.10.0 and pandas 1.0.0, this fails with the same `TypeError` as reported in #5833.

This installation script will install a conda environment with dask 2.10.0 and pandas 1.0.0rc0, and the operation succeeds.  If the `pip install` line is commented out, the operation fails.  I don't know if this is due to a regression in pandas, or due to pandas changing something between 1.0.0rc0 and 1.0.0 that would require a change to dask.  At the time of writing, dask master is the same as dask 2.10.0.

Bash installation script:

```bash
. /media/nas/x21324/miniconda3/etc/profile.d/conda.sh
conda create -y -c conda-forge --strict-channel-priority -n test toolz fsspec numpy pytz six python-dateutil dask
conda activate test
pip install pandas==1.0.0rc0
python mwe18.py
conda list
```

Python test script:

```python
import pandas as pd
import dask.dataframe as ddf
import os
import io
import tempfile
s=""",DATE,VIS
0,2019-01-03 22:00:00,"025000,1,9,9"
1,2019-01-04 04:00:00,"025000,1,9,9"
2,2019-01-04 22:00:00,"020000,1,9,9"
3,2019-01-05 22:00:00,"000100,1,9,9"
4,2019-01-08 04:00:00,"025000,1,9,9"
"""
df1 = pd.read_csv(io.StringIO(s), dtype={"STATION": pd.StringDtype()}, parse_dates=["DATE"])
# dask's read_csv can't read from stream
with tempfile.NamedTemporaryFile(suffix=".csv", mode="w+t", encoding="ascii",
        delete=False) as ntf:
    ntf.write(s)
df2 = ddf.read_csv(ntf.name, dtype={"VIS": pd.StringDtype()}, parse_dates=["DATE"])
try:
    vis1 = df1.VIS.str.extract(r"(\d{6}),(\d),([NV9]),(\d)")
    vis2 = df2.VIS.str.extract(r"(\d{6}),(\d),([NV9]),(\d)").compute()
finally:
    os.unlink(ntf.name)
```

<details><summary>output with pandas 1.0.0 (TypeError)</summary>
<p>

```
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /media/nas/x21324/miniconda3/envs/test

  added / updated specs:
    - dask
    - fsspec
    - numpy
    - python-dateutil
    - pytz
    - six
    - toolz


The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-0_gnu
  bokeh              conda-forge/linux-64::bokeh-1.4.0-py38_0
  ca-certificates    conda-forge/linux-64::ca-certificates-2019.11.28-hecc5488_0
  certifi            conda-forge/linux-64::certifi-2019.11.28-py38_0
  click              conda-forge/noarch::click-7.0-py_0
  cloudpickle        conda-forge/noarch::cloudpickle-1.2.2-py_1
  cytoolz            conda-forge/linux-64::cytoolz-0.10.1-py38h516909a_0
  dask               conda-forge/noarch::dask-2.10.0-py_0
  dask-core          conda-forge/noarch::dask-core-2.10.0-py_0
  distributed        conda-forge/noarch::distributed-2.10.0-py_0
  freetype           conda-forge/linux-64::freetype-2.10.0-he983fc9_1
  fsspec             conda-forge/noarch::fsspec-0.6.2-py_0
  heapdict           conda-forge/noarch::heapdict-1.0.1-py_0
  jinja2             conda-forge/noarch::jinja2-2.11.0-py_0
  jpeg               conda-forge/linux-64::jpeg-9c-h14c3975_1001
  ld_impl_linux-64   conda-forge/linux-64::ld_impl_linux-64-2.33.1-h53a641e_8
  libblas            conda-forge/linux-64::libblas-3.8.0-14_openblas
  libcblas           conda-forge/linux-64::libcblas-3.8.0-14_openblas
  libffi             conda-forge/linux-64::libffi-3.2.1-he1b5a44_1006
  libgcc-ng          conda-forge/linux-64::libgcc-ng-9.2.0-h24d8f2e_2
  libgfortran-ng     conda-forge/linux-64::libgfortran-ng-7.3.0-hdf63c60_4
  libgomp            conda-forge/linux-64::libgomp-9.2.0-h24d8f2e_2
  liblapack          conda-forge/linux-64::liblapack-3.8.0-14_openblas
  libopenblas        conda-forge/linux-64::libopenblas-0.3.7-h5ec1e0e_6
  libpng             conda-forge/linux-64::libpng-1.6.37-hed695b0_0
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-9.2.0-hdf63c60_2
  libtiff            conda-forge/linux-64::libtiff-4.1.0-hc3755c2_3
  locket             conda-forge/noarch::locket-0.2.0-py_2
  lz4-c              conda-forge/linux-64::lz4-c-1.8.3-he1b5a44_1001
  markupsafe         conda-forge/linux-64::markupsafe-1.1.1-py38h516909a_0
  msgpack-python     conda-forge/linux-64::msgpack-python-0.6.2-py38hc9558a2_0
  ncurses            conda-forge/linux-64::ncurses-6.1-hf484d3e_1002
  numpy              conda-forge/linux-64::numpy-1.17.5-py38h95a1406_0
  olefile            conda-forge/noarch::olefile-0.46-py_0
  openssl            conda-forge/linux-64::openssl-1.1.1d-h516909a_0
  packaging          conda-forge/noarch::packaging-20.1-py_0
  pandas             conda-forge/linux-64::pandas-1.0.0-py38hb3f55d8_0
  partd              conda-forge/noarch::partd-1.1.0-py_0
  pillow             conda-forge/linux-64::pillow-7.0.0-py38hefe7db6_0
  pip                conda-forge/linux-64::pip-20.0.2-py38_0
  psutil             conda-forge/linux-64::psutil-5.6.7-py38h516909a_0
  pyparsing          conda-forge/noarch::pyparsing-2.4.6-py_0
  python             conda-forge/linux-64::python-3.8.1-h357f687_2
  python-dateutil    conda-forge/noarch::python-dateutil-2.8.1-py_0
  pytz               conda-forge/noarch::pytz-2019.3-py_0
  pyyaml             conda-forge/linux-64::pyyaml-5.3-py38h516909a_0
  readline           conda-forge/linux-64::readline-8.0-hf8c457e_0
  setuptools         conda-forge/linux-64::setuptools-45.1.0-py38_0
  six                conda-forge/linux-64::six-1.14.0-py38_0
  sortedcontainers   conda-forge/noarch::sortedcontainers-2.1.0-py_0
  sqlite             conda-forge/linux-64::sqlite-3.30.1-hcee41ef_0
  tblib              conda-forge/noarch::tblib-1.6.0-py_0
  tk                 conda-forge/linux-64::tk-8.6.10-hed695b0_0
  toolz              conda-forge/noarch::toolz-0.10.0-py_0
  tornado            conda-forge/linux-64::tornado-6.0.3-py38h516909a_0
  wheel              conda-forge/linux-64::wheel-0.34.1-py38_0
  xz                 conda-forge/linux-64::xz-5.2.4-h14c3975_1001
  yaml               conda-forge/linux-64::yaml-0.2.2-h516909a_1
  zict               conda-forge/noarch::zict-1.0.0-py_0
  zlib               conda-forge/linux-64::zlib-1.2.11-h516909a_1006
  zstd               conda-forge/linux-64::zstd-1.4.4-h3b9ef0a_1


Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
#
# To activate this environment, use
#
#     $ conda activate test
#
# To deactivate an active environment, use
#
#     $ conda deactivate

/media/nas/x21324/miniconda3/envs/test/lib/python3.8/site-packages/dask/dataframe/_compat.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm  # noqa: F401
Traceback (most recent call last):
  File "mwe18.py", line 21, in <module>
    vis2 = df2.VIS.str.extract(r"(\d{6}),(\d),([NV9]),(\d)").compute()
  File "/media/nas/x21324/miniconda3/envs/test/lib/python3.8/site-packages/dask/dataframe/accessor.py", line 64, in _function_map
    self._series._meta_nonempty, self._accessor_name, attr, args, kwargs
  File "/media/nas/x21324/miniconda3/envs/test/lib/python3.8/site-packages/dask/dataframe/core.py", line 344, in _meta_nonempty
    return meta_nonempty(self._meta)
  File "/media/nas/x21324/miniconda3/envs/test/lib/python3.8/site-packages/dask/utils.py", line 505, in __call__
    return meth(arg, *args, **kwargs)
  File "/media/nas/x21324/miniconda3/envs/test/lib/python3.8/site-packages/dask/dataframe/utils.py", line 578, in _nonempty_series
    data = np.array([entry, entry], dtype=dtype)
TypeError: data type not understood
# packages in environment at /media/nas/x21324/miniconda3/envs/test:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       0_gnu    conda-forge
bokeh                     1.4.0                    py38_0    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
certifi                   2019.11.28               py38_0    conda-forge
click                     7.0                        py_0    conda-forge
cloudpickle               1.2.2                      py_1    conda-forge
cytoolz                   0.10.1           py38h516909a_0    conda-forge
dask                      2.10.0                     py_0    conda-forge
dask-core                 2.10.0                     py_0    conda-forge
distributed               2.10.0                     py_0    conda-forge
freetype                  2.10.0               he983fc9_1    conda-forge
fsspec                    0.6.2                      py_0    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
jinja2                    2.11.0                     py_0    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
ld_impl_linux-64          2.33.1               h53a641e_8    conda-forge
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgfortran-ng            7.3.0                hdf63c60_4    conda-forge
libgomp                   9.2.0                h24d8f2e_2    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
libopenblas               0.3.7                h5ec1e0e_6    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
libtiff                   4.1.0                hc3755c2_3    conda-forge
locket                    0.2.0                      py_2    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
markupsafe                1.1.1            py38h516909a_0    conda-forge
msgpack-python            0.6.2            py38hc9558a2_0    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
numpy                     1.17.5           py38h95a1406_0    conda-forge
olefile                   0.46                       py_0    conda-forge
openssl                   1.1.1d               h516909a_0    conda-forge
packaging                 20.1                       py_0    conda-forge
pandas                    1.0.0            py38hb3f55d8_0    conda-forge
partd                     1.1.0                      py_0    conda-forge
pillow                    7.0.0            py38hefe7db6_0    conda-forge
pip                       20.0.2                   py38_0    conda-forge
psutil                    5.6.7            py38h516909a_0    conda-forge
pyparsing                 2.4.6                      py_0    conda-forge
python                    3.8.1                h357f687_2    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
pytz                      2019.3                     py_0    conda-forge
pyyaml                    5.3              py38h516909a_0    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
setuptools                45.1.0                   py38_0    conda-forge
six                       1.14.0                   py38_0    conda-forge
sortedcontainers          2.1.0                      py_0    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
tblib                     1.6.0                      py_0    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
toolz                     0.10.0                     py_0    conda-forge
tornado                   6.0.3            py38h516909a_0    conda-forge
wheel                     0.34.1                   py38_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
yaml                      0.2.2                h516909a_1    conda-forge
zict                      1.0.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
zstd                      1.4.4                h3b9ef0a_1    conda-forge
```
</details>

<details><summary>output with pandas 1.0.0rc0 (success)</summary>
<p>

```
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /media/nas/x21324/miniconda3/envs/test

  added / updated specs:
    - dask
    - fsspec
    - numpy
    - python-dateutil
    - pytz
    - six
    - toolz


The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-0_gnu
  bokeh              conda-forge/linux-64::bokeh-1.4.0-py38_0
  ca-certificates    conda-forge/linux-64::ca-certificates-2019.11.28-hecc5488_0
  certifi            conda-forge/linux-64::certifi-2019.11.28-py38_0
  click              conda-forge/noarch::click-7.0-py_0
  cloudpickle        conda-forge/noarch::cloudpickle-1.2.2-py_1
  cytoolz            conda-forge/linux-64::cytoolz-0.10.1-py38h516909a_0
  dask               conda-forge/noarch::dask-2.10.0-py_0
  dask-core          conda-forge/noarch::dask-core-2.10.0-py_0
  distributed        conda-forge/noarch::distributed-2.10.0-py_0
  freetype           conda-forge/linux-64::freetype-2.10.0-he983fc9_1
  fsspec             conda-forge/noarch::fsspec-0.6.2-py_0
  heapdict           conda-forge/noarch::heapdict-1.0.1-py_0
  jinja2             conda-forge/noarch::jinja2-2.11.0-py_0
  jpeg               conda-forge/linux-64::jpeg-9c-h14c3975_1001
  ld_impl_linux-64   conda-forge/linux-64::ld_impl_linux-64-2.33.1-h53a641e_8
  libblas            conda-forge/linux-64::libblas-3.8.0-14_openblas
  libcblas           conda-forge/linux-64::libcblas-3.8.0-14_openblas
  libffi             conda-forge/linux-64::libffi-3.2.1-he1b5a44_1006
  libgcc-ng          conda-forge/linux-64::libgcc-ng-9.2.0-h24d8f2e_2
  libgfortran-ng     conda-forge/linux-64::libgfortran-ng-7.3.0-hdf63c60_4
  libgomp            conda-forge/linux-64::libgomp-9.2.0-h24d8f2e_2
  liblapack          conda-forge/linux-64::liblapack-3.8.0-14_openblas
  libopenblas        conda-forge/linux-64::libopenblas-0.3.7-h5ec1e0e_6
  libpng             conda-forge/linux-64::libpng-1.6.37-hed695b0_0
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-9.2.0-hdf63c60_2
  libtiff            conda-forge/linux-64::libtiff-4.1.0-hc3755c2_3
  locket             conda-forge/noarch::locket-0.2.0-py_2
  lz4-c              conda-forge/linux-64::lz4-c-1.8.3-he1b5a44_1001
  markupsafe         conda-forge/linux-64::markupsafe-1.1.1-py38h516909a_0
  msgpack-python     conda-forge/linux-64::msgpack-python-0.6.2-py38hc9558a2_0
  ncurses            conda-forge/linux-64::ncurses-6.1-hf484d3e_1002
  numpy              conda-forge/linux-64::numpy-1.17.5-py38h95a1406_0
  olefile            conda-forge/noarch::olefile-0.46-py_0
  openssl            conda-forge/linux-64::openssl-1.1.1d-h516909a_0
  packaging          conda-forge/noarch::packaging-20.1-py_0
  pandas             conda-forge/linux-64::pandas-1.0.0-py38hb3f55d8_0
  partd              conda-forge/noarch::partd-1.1.0-py_0
  pillow             conda-forge/linux-64::pillow-7.0.0-py38hefe7db6_0
  pip                conda-forge/linux-64::pip-20.0.2-py38_0
  psutil             conda-forge/linux-64::psutil-5.6.7-py38h516909a_0
  pyparsing          conda-forge/noarch::pyparsing-2.4.6-py_0
  python             conda-forge/linux-64::python-3.8.1-h357f687_2
  python-dateutil    conda-forge/noarch::python-dateutil-2.8.1-py_0
  pytz               conda-forge/noarch::pytz-2019.3-py_0
  pyyaml             conda-forge/linux-64::pyyaml-5.3-py38h516909a_0
  readline           conda-forge/linux-64::readline-8.0-hf8c457e_0
  setuptools         conda-forge/linux-64::setuptools-45.1.0-py38_0
  six                conda-forge/linux-64::six-1.14.0-py38_0
  sortedcontainers   conda-forge/noarch::sortedcontainers-2.1.0-py_0
  sqlite             conda-forge/linux-64::sqlite-3.30.1-hcee41ef_0
  tblib              conda-forge/noarch::tblib-1.6.0-py_0
  tk                 conda-forge/linux-64::tk-8.6.10-hed695b0_0
  toolz              conda-forge/noarch::toolz-0.10.0-py_0
  tornado            conda-forge/linux-64::tornado-6.0.3-py38h516909a_0
  wheel              conda-forge/linux-64::wheel-0.34.1-py38_0
  xz                 conda-forge/linux-64::xz-5.2.4-h14c3975_1001
  yaml               conda-forge/linux-64::yaml-0.2.2-h516909a_1
  zict               conda-forge/noarch::zict-1.0.0-py_0
  zlib               conda-forge/linux-64::zlib-1.2.11-h516909a_1006
  zstd               conda-forge/linux-64::zstd-1.4.4-h3b9ef0a_1


Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
#
# To activate this environment, use
#
#     $ conda activate test
#
# To deactivate an active environment, use
#
#     $ conda deactivate

WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Collecting pandas==1.0.0rc0
  Using cached pandas-1.0.0rc0-cp38-cp38-manylinux1_x86_64.whl (9.9 MB)
Requirement already satisfied: numpy>=1.13.3 in /media/nas/x21324/miniconda3/envs/test/lib/python3.8/site-packages (from pandas==1.0.0rc0) (1.17.5)
Requirement already satisfied: pytz>=2017.2 in /media/nas/x21324/miniconda3/envs/test/lib/python3.8/site-packages (from pandas==1.0.0rc0) (2019.3)
Requirement already satisfied: python-dateutil>=2.6.1 in /media/nas/x21324/miniconda3/envs/test/lib/python3.8/site-packages (from pandas==1.0.0rc0) (2.8.1)
Requirement already satisfied: six>=1.5 in /media/nas/x21324/miniconda3/envs/test/lib/python3.8/site-packages (from python-dateutil>=2.6.1->pandas==1.0.0rc0) (1.14.0)
Installing collected packages: pandas
  Attempting uninstall: pandas
    Found existing installation: pandas 1.0.0
    Uninstalling pandas-1.0.0:
      Successfully uninstalled pandas-1.0.0
Successfully installed pandas-1.0.0rc0
# packages in environment at /media/nas/x21324/miniconda3/envs/test:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       0_gnu    conda-forge
bokeh                     1.4.0                    py38_0    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
certifi                   2019.11.28               py38_0    conda-forge
click                     7.0                        py_0    conda-forge
cloudpickle               1.2.2                      py_1    conda-forge
cytoolz                   0.10.1           py38h516909a_0    conda-forge
dask                      2.10.0                     py_0    conda-forge
dask-core                 2.10.0                     py_0    conda-forge
distributed               2.10.0                     py_0    conda-forge
freetype                  2.10.0               he983fc9_1    conda-forge
fsspec                    0.6.2                      py_0    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
jinja2                    2.11.0                     py_0    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
ld_impl_linux-64          2.33.1               h53a641e_8    conda-forge
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgfortran-ng            7.3.0                hdf63c60_4    conda-forge
libgomp                   9.2.0                h24d8f2e_2    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
libopenblas               0.3.7                h5ec1e0e_6    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
libtiff                   4.1.0                hc3755c2_3    conda-forge
locket                    0.2.0                      py_2    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
markupsafe                1.1.1            py38h516909a_0    conda-forge
msgpack-python            0.6.2            py38hc9558a2_0    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
numpy                     1.17.5           py38h95a1406_0    conda-forge
olefile                   0.46                       py_0    conda-forge
openssl                   1.1.1d               h516909a_0    conda-forge
packaging                 20.1                       py_0    conda-forge
pandas                    1.0.0rc0                 pypi_0    pypi
partd                     1.1.0                      py_0    conda-forge
pillow                    7.0.0            py38hefe7db6_0    conda-forge
pip                       20.0.2                   py38_0    conda-forge
psutil                    5.6.7            py38h516909a_0    conda-forge
pyparsing                 2.4.6                      py_0    conda-forge
python                    3.8.1                h357f687_2    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
pytz                      2019.3                     py_0    conda-forge
pyyaml                    5.3              py38h516909a_0    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
setuptools                45.1.0                   py38_0    conda-forge
six                       1.14.0                   py38_0    conda-forge
sortedcontainers          2.1.0                      py_0    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
tblib                     1.6.0                      py_0    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
toolz                     0.10.0                     py_0    conda-forge
tornado                   6.0.3            py38h516909a_0    conda-forge
wheel                     0.34.1                   py38_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
yaml                      0.2.2                h516909a_1    conda-forge
zict                      1.0.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
zstd                      1.4.4                h3b9ef0a_1    conda-forge
```
</p>
</details>

### PR DESCRIPTION
**Pull request by TomAugspurger**
Closes #5848

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Probably warrants a release unfortunately.

@jrbourbeau Do you know what all will need to be updated on Conda-forge? `dask-core` for sure, but also `dask`? What about `distributed`?

**Comment by TomAugspurger** [comment]
Hmm not sure why those HDF5 tests would have failed just on windows. Are we not running them on Travis? Will investigate later.

**Comment by TomAugspurger** [comment]
Ah didn't have a pandas 1.0.* build in Travis. I bumped the 3.8 build to use it. The 3.7 build is still on 0.25.x, so that's covered.

**Comment by jrbourbeau** [comment]
> We can do a bugfix release for both dask and distributed

Actually, on second thought I'll hold off on a `distributed` release to let some recent commits simmer in `master`. Once `dask` and `dask-core` 2.10.1 are on `conda-forge`, `distributed` will be able to pull in the bugfix release

https://github.com/conda-forge/distributed-feedstock/blob/18aac51e8130b820b260a7935f827510ea882fc0/recipe/meta.yaml#L30

**Comment by mrocklin** [comment]
Ah, sorry about merging things recently :)

**Pull request merged**
