### PR TITLE
Don't overlap on non-overlapped dimensions

### PR DESCRIPTION
**Pull request by mrocklin**
This created far more tasks than were necessary

Fixes https://github.com/dask/dask/issues/3645

- [x] Tests added / passed
- [x] Passes `flake8 dask`

### CODE REVIEW

**Comment by mrocklin** [comment]
Merging this soon if there are no comments

**Comment by jakirkham** [comment]
Thanks Matt. This seems like a good improvement.

Just to make it concrete, how does the example in the xref'd issue change?

**Comment by mrocklin** [comment]
The example in the issue that you created works great now.  

I *think* that things are also better in the more complex 2d case, but it's harder to visualize because the graphs are necessarily so much larger.

**Comment by mrocklin** [comment]
Oh, I'm sorry, I was confusing this with another issue.  Yes, this resolve the original issue.

**Comment by jakirkham** [comment]
Yeah there’s a lot of work on `map_overlap`, which is great :)

**Comment by mrocklin** [comment]
If you happen to have concrete use cases of this that you're able to share
they would be welcome :)  I've been using the satellite image as my current
use case, but would welcome another that was equally simple to run.

**Pull request merged**
