### PR TITLE
Relax timing test

### PR DESCRIPTION
**Pull request by mrocklin**
This was an intermittent failure on travis.ci before.

### CODE REVIEW

**Comment by mrocklin** [comment]
cc @martindurant there might be a parquet/dask mismatch going on here

**Comment by martindurant** [comment]
Yes - merging #2113 should fix.

**Comment by mrocklin** [comment]
Would it be possible to smoothly deprecate the old attribute so that we can be resilient to slight changes in version?  For example if you were to release fastparquet today it would break any current dask user's experience.

**Comment by martindurant** [comment]
I can only think of duplicating it, or using a getter which raises a warning.

**Comment by mrocklin** [comment]
Typically one might create a property that raises a warning as you suggest:

```python
@property
def foo(self):
    warnings.warn("Foo has been deprecated, use bar instead")
    return bar
```

Although I'm not sure what technology is preferred for deprecation warnings these days (cc @jcrist )

**Comment by jcrist** [comment]
Raising a warning like that is probably the best way. Python ignores deprecation warnings by default, so raising a warning without a class has been the convention in dask.

**Comment by martindurant** [comment]
Added it straight in https://github.com/dask/fastparquet/commit/e0a3db5832d73057f77d5485827b5443d0b25e55

**Comment by mrocklin** [comment]
Rerunning tests here to verify that things run smoothly.  Then lets make the change.

**Pull request merged**
