### PR TITLE
Cache chunk boundaries for arrays

### PR DESCRIPTION
**Pull request by bmerry**
Currently the cached boundaries are used only for slicing, and not in
all cases. This makes slicing of a small piece of a very large array (as
measured in chunks) significantly faster: for an array with 10^6 chunks,
a slice returning a single chunk is about 10x faster to construct after
the cache is initialized.

- [x] Tests added / passed
- [x] Passes `flake8 dask`

### CODE REVIEW

**Comment by bmerry** [comment]
I can probably simplify `_slice_1d` a bit to take advantage of having the initial 0 in the chunk boundaries, rather than throwing it away and then having lots of special cases for chunk 0. But I'd like to get some feedback on the general approach first.

I've got a few questions:
- Do 'block' and 'chunk' mean different things (in dask), or are they interchangeable? I wasn't sure where to use what.
- What is the thread-safety model in dask? The getter isn't thread-safe if two threads read from the same array at the same time, but that's also true of `__dask_keys__` which has a similar cache.
- Should I add something to the changelog? The [development guidelines](http://docs.dask.org/en/latest/develop.html) say one should, but looking at the history of changelog.rst it seems the changelog gets written at release time.

**Comment by bmerry** [comment]
Forgot to mention: this is to implement #4867.

**Comment by mrocklin** [comment]
Thanks for PR @bmerry .  A few answers to your questions, and then some larger comments below:

> Do 'block' and 'chunk' mean different things (in dask), or are they interchangeable? I wasn't sure where to use what.

Interchangable I guess.  `chunks` very specifically also refers to the tuple-of-tuples, but we refer to a single numpy array interchangably as both a block and a chunk

> What is the thread-safety model in dask? The getter isn't thread-safe if two threads read from the same array at the same time, but that's also true of __dask_keys__ which has a similar cache.

This hasn't really come up before.  I don't think that there are many multithreaded applications that modify dask array state.

> Should I add something to the changelog? The development guidelines say one should, but looking at the history of changelog.rst it seems the changelog gets written at release time.

Nope, thanks for pointing this out.  I've changed the docs in  https://github.com/dask/dask/pull/4915

**Comment by mrocklin** [comment]
So, in terms of the actual content here, I'm quite glad to see the speedup, but the amount of code change is a little disheartening, particularly the modification of the core dask array state and having to thread through the cached value through all of the slicing code.  The combination of these two makes me wonder if the added complexity is worth the speed boost.  I wonder if there is another way.

At first I thought, "oh, let's just cache the result of cumsum based on the chunks value, maybe something like this"

```python
import toolz, weakref
cache = weakref.WeakKeyDictionary

cumsum = toolz.memoize(cache=cache)(np.cumsum)
```

"that would be great, we get the same caching, but we don't have to hold onto things manually and route things through ourselves".  Unfortunately, it looks like we can't make weak references of tuples.

As an alternative, I wonder if we might do the following:

```python
cumsum = functools.lru_cache()(np.cumsum)
```

```python
In [1]: import time, functools

In [2]: def slow_sum(c):
   ...:     time.sleep(1)
   ...:     return sum(c)
   ...:

In [3]: memo_sum = functools.lru_cache()(slow_sum)

In [4]: chunks = (1, 2, 3, 4, 5)

In [5]: %time memo_sum((0,) + chunks)
CPU times: user 847 µs, sys: 1.05 ms, total: 1.9 ms
Wall time: 1 s
Out[5]: 15

In [6]: %time memo_sum((0,) + chunks)
CPU times: user 4 µs, sys: 0 ns, total: 4 µs
Wall time: 7.87 µs
Out[6]: 15
```

Thoughts?  This probably isn't as optimalm, but it might be a lighter-weight code change, and add less maintenance costs going forward.

**Comment by bmerry** [comment]
> > What is the thread-safety model in dask? The getter isn't thread-safe if two threads read from the same array at the same time, but that's also true of dask_keys which has a similar cache.
> 
> This hasn't really come up before. I don't think that there are many multithreaded applications that modify dask array state.

The issue is that whenever you have a cache (as you do for `__dask_keys__`), you have an operation that has read-only semantics but a read-write implementation. So doing "read" operations on an array from two different threads can have a race condition.

**Comment by mrocklin** [comment]
> The issue is that whenever you have a cache (as you do for __dask_keys__), you have an operation that has read-only semantics but a read-write implementation. So doing "read" operations on an array from two different threads can have a race condition.

Yup.  No disagreement there.

Any thoughts on using something like `lru_cache`?  This would sidestep this issue (among others).

**Comment by mrocklin** [comment]
Ah, sorry.  I see that you have submitted this in #4923

**Comment by bmerry** [comment]
Closing in favour of #4923.

**Pull request closed without merging**
