### PR TITLE
Always compute 0 and 1 quantiles during quantile calculations.

### LINKED ISSUE #6551: `quantile` calculation using dask default method gives incorrect results
This is similar to #731 but reveals a broader issue and thus I would like to create a new issue for it. I'm using `dask==2.24.0` and `pandas==1.0.5`
```
import pandas as pd
import dask.dataframe as dd
x = pd.DataFrame({'a': [1,2,3]})
xd = dd.from_pandas(x, npartitions=3)
print(x['a'].quantile(0.5))
print(xd['a'].quantile(0.5).compute())
```

This difference persists as I try all natural number column `'a'` with length greater than 2 (i.e. `'a'` being natural numbers 1,...,N where N>2).

```
for i in range(1, 100):
    x = pd.DataFrame({'a': list(range(i))})
    xd = dd.from_pandas(x, npartitions=i+1)
    pd_quantile = x['a'].quantile(0.5)
    dd_quantile = xd['a'].quantile(0.5).compute()
    if pd_quantile == dd_quantile:
        print('same')
    else:
        print('different')
```

Using `method='tdigest'` does solve the issue, but the default algorithm shouldn't be giving a wrong answer either..

### PR DESCRIPTION
**Pull request by eriknw**
This is a super-quick fix to hopefully makes quantiles/percentiles slightly less bad by computing the 0 and 100 percentiles during the calculation.

We could perhaps take this "quick fix" further by adding even more quantiles to compute during computation.  For example, we could double the number of quantiles that get computed on each partition:
```python
        # Add 0 and 100 during calculation for more robust behavior (hopefully)
        temp_qs = np.pad(qs, 1)
        temp_qs[-1] = 100
        # Now add the midpoints between percentiles
        # In total, we use `2 * len(qs) + 3` percentile values during calculation
        calc_qs = np.empty(temp_qs.size * 2 - 1)
        calc_qs[0::2] = temp_qs
        calc_qs[1::2] = 0.5 * (temp_qs[1:] + temp_qs[:-1])
```
Fixes #6551

Observe that the tests that needed updated got more accurate.

- [X] Tests added / passed
- [x] Passes `black dask` / `flake8 dask`

### CODE REVIEW

**Comment by mrocklin** [comment]
cc @jcrist if you have time

**Comment by jcrist** [comment]
From the issue https://github.com/dask/dask/issues/6551#issuecomment-681964573 it looks like this doesn't fully resolve the issue. I'm skeptical of work on this front - the dask method is custom and lacks the statistical rigor users might expect. I'm skeptical of one-off fixes that improve things for certain use cases, as without statistical rigor the results are likely made worse for other users. Perhaps we should switch to using `tdigest` as the default, since that's much more robust?

**Comment by eriknw** [comment]
I agree on most counts.  We should use `tdigest` if possible.  I am skeptical of quick fixes.  The current method was never meant for generic percentile calculations and lacks the statistical rigor to do so.  Additional work (beyond what is in this PR IMHO) to improve or investigate the current approach for quantiles is probably not worth the effort.

As the person who wrote the code for *partition quantiles* (i.e., determining how to partition dask dataframes, which it does an excellent job at), it always bothered me how it was adapted for generic percentiles, and, in particular, how it doesn't include the 100% percentile.  This nags me, because I have knowledge of the implementation.  It should include 100%, and including 0% should also help at some boundary cases.

So, as somebody who understands the current implementation, I trust that this PR generally makes things better.  I'm sorry for not making it years ago.

This PR also *substantially improves* #6551 to the point where I think it's resolved within expectation.  I think the additional edge cases that were found should be expected, because these are *approximate* quantiles, and the default implementation doesn't have enough information to correctly gather and merge the partition summaries.

@jcrist shall I update the PR to make `tdigest` default if available, or do you still disagree in principle of making any changes to the current implementation?  The current implementation will still be used for non-numeric data, so I think improvements to the current implementation should be accepted if they are available.

**Comment by jcrist** [comment]
I'm fine with improving the current implementation, but think we should start a discussion about no longer defaulting to it. I'll open a new issue for that. The fix you have provided here and reasoning about it seems good to me, so I'm happy to merge (looks like the new black release has broke things here too though, black changed how it handles trailing commas).

**Comment by jcrist** [comment]
See #6566

**Pull request merged**
