### PR TITLE
debug output

### PR DESCRIPTION
**Pull request by TomAugspurger**

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Apparently, AppVeyor has support for logging into the build worker. https://www.appveyor.com/docs/how-to/rdp-to-build-worker/ Testing it out.

**Comment by TomAugspurger** [comment]
Well I reproduced it, but wasn't able to to figure out what's going wrong :/ Will try again later.

**Comment by TomAugspurger** [comment]
I wonder if it's a race condition between the test and the `atexit` in `partd.file`. I may try monkey patching that to not remove files (I think pytest will clean up for us in the test context).

**Comment by TomAugspurger** [comment]
Actually... I have no confidence that a monkeypatch will be serialized correctly between the processes...

**Comment by TomAugspurger** [comment]
OK, trying with a user-specified `pool=multiprocessing.pool.Pool()` under the hypothesis that the failures were when the process pool closed before the assert about the files was made.

**Comment by TomAugspurger** [comment]
I ran it successfully ~20 times with the Pool approach, so that may have been it.

I've reverted all the debug stuff and left just the change to the test. Merging if it passes, and will keep and eye out for sporadic failures.

**Comment by mrocklin** [comment]
Woo!  Go Tom!

There is no hero quite like a Windows-bug-squashing hero

**Comment by TomAugspurger** [comment]
Seems like our appveyor builds are currently stuck in "queued". https://ci.appveyor.com/project/daskdev/dask/history. I'll let it sit for a bit to see if they start, but I may have broken something with my Remote Desktop debugging.

**Comment by TomAugspurger** [comment]
Yay, they're running again (and this passed). Merging.

**Pull request merged**
