### PR TITLE
Pin `fsspec` to `2021.5.0` in CI

### PR DESCRIPTION
**Pull request by jrbourbeau**

### CODE REVIEW

**Comment by jrbourbeau** [comment]
@GenevieveBuckley FYI there were wide spread test failures here similar to what we were seeing in https://github.com/dask/dask/pull/7740. To try and narrow things down, I compared the packages which were installed between the last CI build in that PR (which was failing) and the most recent commit on `main` (which was passing at the time it ran). For the macOS / Python 3.9 build these were the package builds which differed:

```diff
66c66
<   - fasteners=0.16.1=pyhd3eb1b0_0
---
>   - fasteners=0.16=pyhd8ed1ab_0
79c79
<   - fsspec=2021.6.0=pyhd8ed1ab_0
---
>   - fsspec=2021.5.0=pyhd8ed1ab_0
164a165
>   - monotonic=1.5=py_0
215c216
<   - python-jose=3.3.0=pyhd8ed1ab_0
---
>   - python-jose=3.2.0=pyhd8ed1ab_0
226c227
<   - s3fs=0.6.0=pyhd8ed1ab_0
---
>   - s3fs=2021.5.0=pyhd8ed1ab_0
```

Initially none of these packages seemed particularly related to the error message we were seeing in https://github.com/dask/dask/pull/7740.

Though after trying to reproduce the test failures locally, which I was able to do, I was surprised to see that the contents of my entire local `dask` fork had been deleted. Because of this, I now suspect the latest `fsspec=2021.6.0` release _may_ be the source of the problem. I've pinned `fsspec` to `2021.5.0` in CI to test this hypothesis.

**Comment by jrbourbeau** [comment]
Alright, test builds are starting to pass. It looks like the `fsspec=2021.6.0` release was the underlying issue (cc @martindurant). Briefly looking through the changelog for that release, https://github.com/intake/filesystem_spec/pull/647 sticks out as potentially related because Windows CI builds still pass with `fsspec=2021.6.0` (though this is just a hunch)

**Comment by GenevieveBuckley** [comment]
Good sleuthing!
I wasn't able to reproduce the failures locally, but I also didn't re-create a new dask environment (I just used my existing environment). So that makes sense to me.

**Comment by jrbourbeau** [comment]
Merging to unblock CI for the time being. We can remove this pinning after things have been resolved upstream in `fsspec`

**Pull request merged**
