### PR TITLE
Move tests up out of dask dir

### PR DESCRIPTION
**Pull request by jsignell**
After this PR: 

```
$ tree -d
├── continuous_integration
├── dask
│   ├── array
│   │   └── lib
│   ├── bag
│   ├── bytes
│   ├── dataframe
│   │   ├── io
│   │   │   ├── orc
│   │   │   └── parquet
│   │   └── tseries
│   ├── diagnostics
│   └── widgets
│       └── templates
├── docs
└── tests
    ├── array
    ├── bag
    ├── bytes
    ├── dataframe
    │   ├── io
    │   └── tseries
    ├── diagnostics
    └── widgets
        └── templates
```

### CODE REVIEW

**Comment by jakirkham** [comment]
Thanks for getting this started Julia! 😄

Should the underlying directories be prefixed with `test_`?

**Comment by jsignell** [comment]
> Thanks for getting this started Julia! smile
> 
> Should the underlying directories be prefixed with `test_`?

I prefer no prefix unless others feel strongly.

**Review by jrbourbeau — COMMENTED** [review]
Thanks for taking this on @jsignell

> Should the underlying directories be prefixed with test_?
> I prefer no prefix unless others feel strongly.

I have a similar preference. Prefixing subdirectories with `test_` seems redundant given they are all in a root `tests/` directory

**Comment by jsignell** [comment]
There are two tests that I am definitely seeing locally as well as on CI. I am thinking maybe I'm missing setting some seed or something?

```python-traceback
____________________ test_name_consistent_across_instances _____________________

    def test_name_consistent_across_instances():
        func = delayed(identity, pure=True)
    
        data = {"x": 1, "y": 25, "z": [1, 2, 3]}
>       assert func(data)._key == "identity-02129ed1acaffa7039deee80c5da547c"
E       AssertionError: assert 'identity-645...88ae8f4ee45e2' == 'identity-021...eee80c5da547c'
E         - identity-02129ed1acaffa7039deee80c5da547c
E         + identity-645b5c5147ebc841ed488ae8f4ee45e2

tests/test_delayed.py:546: AssertionError
```

**Comment by jrbourbeau** [comment]
Hrm, I'm also able to reproduce. My first guess is that this test ends up relying on a filename path during tokenization. For example, like here

https://github.com/dask/dask/blob/007cbd4e6779c3311af91ba4ecdfe731f23ddf58/dask/base.py#L976-L987

where we incorporate a pickle dump into the tokenization process

**Comment by jsignell** [comment]
Thanks! Ok I am down to one failure locally:

```python
___________________________________ test_scheduler_highlevel_graph_unpack_import[False-_array_map_overlap-numpy.] ____________________________________
[gw0] linux -- Python 3.9.10 /home/julia/conda/envs/dask-dev/bin/python

op = <function _array_map_overlap at 0x7f722d6d7790>, lib = 'numpy.', optimize_graph = False
loop = <tornado.platform.asyncio.AsyncIOLoop object at 0x7f722d691d00>
tmpdir = local('/tmp/pytest-of-julia/pytest-182/popen-gw0/test_scheduler_highlevel_graph0')

    @pytest.mark.parametrize(
        "op,lib",
        [
            (_dataframe_shuffle, "pandas."),
            (_dataframe_tree_reduction, "pandas."),
            (_dataframe_broadcast_join, "pandas."),
            (_pq_pyarrow, "pandas."),
            (_pq_fastparquet, "pandas."),
            (_read_csv, "pandas."),
            (_array_creation, "numpy."),
            (_array_map_overlap, "numpy."),
        ],
    )
    @pytest.mark.parametrize("optimize_graph", [True, False])
    def test_scheduler_highlevel_graph_unpack_import(op, lib, optimize_graph, loop, tmpdir):
        # Test that array/dataframe-specific modules are not imported
        # on the scheduler when an HLG layers are unpacked/materialized.
    
        with cluster(scheduler_kwargs={"plugins": [SchedulerImportCheck(lib)]}) as (
            scheduler,
            workers,
        ):
            with Client(scheduler["address"], loop=loop) as c:
                # Perform a computation using a HighLevelGraph Layer
                c.compute(op(tmpdir), optimize_graph=optimize_graph)
    
                # Get the new modules which were imported on the scheduler during the computation
                end_modules = c.run_on_scheduler(lambda: set(sys.modules))
                start_modules = c.run_on_scheduler(
                    lambda dask_scheduler: dask_scheduler.plugins[
                        SchedulerImportCheck.name
                    ].start_modules
                )
                new_modules = end_modules - start_modules
    
                # Check that the scheduler didn't start with `lib`
                # (otherwise we arent testing anything)
                assert not any(module.startswith(lib) for module in start_modules)
    
                # Check whether we imported `lib` on the scheduler
>               assert not any(module.startswith(lib) for module in new_modules)
E               assert not True
E                +  where True = any(<generator object test_scheduler_highlevel_graph_unpack_import.<locals>.<genexpr> at 0x7f722d637120>)

tests/test_layers.py:227: AssertionError
```

**Comment by jsignell** [comment]
I'm also seeing an error like: 

```python-traceback
distributed.core - ERROR - __dask_distributed_unpack__() takes 2 positional arguments but 4 were given
Traceback (most recent call last):
  File "/home/julia/distributed/distributed/core.py", line 591, in handle_stream
    handler(**merge(extra, msg))
  File "/home/julia/distributed/distributed/scheduler.py", line 4542, in update_graph_hlg
    unpacked_graph = HighLevelGraph.__dask_distributed_unpack__(hlg)
  File "/home/julia/dask/dask/highlevelgraph.py", line 1117, in __dask_distributed_unpack__
    unpacked_layer = unpack_state(layer["state"], dsk, deps)
TypeError: __dask_distributed_unpack__() takes 2 positional arguments but 4 were given
distributed.scheduler - INFO - Remove client Client-4d5043dd-85f9-11ec-82b0-e8f408bd3d78
distributed.scheduler - INFO - Close client connection: Client-4d5043dd-85f9-11ec-82b0-e8f408bd3d78
distributed.core - ERROR - Exception while handling op register-client
Traceback (most recent call last):
  File "/home/julia/distributed/distributed/core.py", line 525, in handle_comm
    result = await result
  File "/home/julia/distributed/distributed/scheduler.py", line 5389, in add_client
    await self.handle_stream(comm=comm, extra={"client": client})
  File "/home/julia/distributed/distributed/core.py", line 591, in handle_stream
    handler(**merge(extra, msg))
  File "/home/julia/distributed/distributed/scheduler.py", line 4542, in update_graph_hlg
    unpacked_graph = HighLevelGraph.__dask_distributed_unpack__(hlg)
  File "/home/julia/dask/dask/highlevelgraph.py", line 1117, in __dask_distributed_unpack__
    unpacked_layer = unpack_state(layer["state"], dsk, deps)
TypeError: __dask_distributed_unpack__() takes 2 positional arguments but 4 were given
tornado.application - ERROR - Exception in callback functools.partial(<function TCPServer._handle_connection.<locals>.<lambda> at 0x7f54159824c0>, <Task finished name='Task-15' coro=<BaseTCPListener._handle_stream() done, defined at /home/julia/distributed/distributed/comm/tcp.py:513> exception=TypeError('__dask_distributed_unpack__() takes 2 positional arguments but 4 were given')>)
Traceback (most recent call last):
  File "/home/julia/conda/envs/dask-dev/lib/python3.9/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/home/julia/conda/envs/dask-dev/lib/python3.9/site-packages/tornado/tcpserver.py", line 331, in <lambda>
    gen.convert_yielded(future), lambda f: f.result()
  File "/home/julia/distributed/distributed/comm/tcp.py", line 530, in _handle_stream
    await self.comm_handler(comm)
  File "/home/julia/distributed/distributed/core.py", line 525, in handle_comm
    result = await result
  File "/home/julia/distributed/distributed/scheduler.py", line 5389, in add_client
    await self.handle_stream(comm=comm, extra={"client": client})
  File "/home/julia/distributed/distributed/core.py", line 591, in handle_stream
    handler(**merge(extra, msg))
  File "/home/julia/distributed/distributed/scheduler.py", line 4542, in update_graph_hlg
    unpacked_graph = HighLevelGraph.__dask_distributed_unpack__(hlg)
  File "/home/julia/dask/dask/highlevelgraph.py", line 1117, in __dask_distributed_unpack__
    unpacked_layer = unpack_state(layer["state"], dsk, deps)
TypeError: __dask_distributed_unpack__() takes 2 positional arguments but 4 were given
distributed.worker - INFO - Run out-of-band function 'lambda'
distributed.batched - INFO - Batched Comm Closed <TCP (closed) Client->Scheduler local=tcp://127.0.0.1:41972 remote=tcp://127.0.0.1:33259>
Traceback (most recent call last):
  File "/home/julia/distributed/distributed/batched.py", line 94, in _background_send
    nbytes = yield self.comm.write(
  File "/home/julia/conda/envs/dask-dev/lib/python3.9/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/home/julia/distributed/distributed/comm/tcp.py", line 247, in write
    raise CommClosedError()
distributed.comm.core.CommClosedError

**Comment by pavithraes** [comment]
@jsignell The [first error](https://github.com/dask/dask/pull/8662#issuecomment-1030326242) looks like [a known flaky test](https://github.com/dask/dask/issues/8480).

**Comment by jsignell** [comment]
Pausing on this while people work through flakiness on distributed.

**Pull request closed without merging**
