### PR TITLE
Compatibility for new info repr

### PR DESCRIPTION
**Pull request by TomAugspurger**
test-upstream

### CODE REVIEW

**Comment by TomAugspurger** [comment]
For now I've been lazy and am just enabling the new repr, even if the version of pandas is older. If it's desired I can make this compatible with both versions of pandas, but I think it's relatively low value.

**Comment by mrocklin** [comment]
Hooray for forced modernism!

**Comment by jrbourbeau** [comment]
Any idea what's causing the `test_groupby_cov` test failure? It seems unrelated, but is passing on `master`

**Comment by TomAugspurger** [comment]
Nope, I'm stumped right now.

And it fails reliably on that build.

**Comment by TomAugspurger** [comment]
Well, apparently I've just been unlucky on this branch. I think this test is hitting a bug in pandas (which is fixed): https://github.com/pandas-dev/pandas/issues/31289.

I'll push a fix for the test.

**Pull request merged**
