### PR TITLE
RFC: Support scipy.sparse matrices

### PR DESCRIPTION
**Pull request by mrocklin**
Here is a tiny PR that allows blocks of dask.arrays to be scipy.sparse matrices for common operations.

See ongoing discussion in #2160

### CODE REVIEW

**Comment by mrocklin** [comment]
This needs more thorough testing, but generally I was pleasantly surprised by how little I had to change here.  Most numpy functions seem to work sensible on scipy.sparse matrices.

**Comment by mrocklin** [comment]
Reductions don't work well.  Scipy.sparse doesn't like the keepdims keyword.

**Comment by mrocklin** [comment]
numpy.dot(scipy) doesn't work well.  We would need to implement a proper double-dispatch variant

**Comment by martindurant** [comment]
It seems to me that handling any explicitly 2D structure is more problematic than the fact that it's sparse. Any manipulation of indices will have to special-case around this. Maybe if the intent is only for linear algebra, e.g., for use in machine learning, then it can be made to work.

Would it be useful to start with a simpler situation, where some of the chunks are completely empty, containing only zeros or other fill value?

Note that there are other sparse ndarrays/tensors out there, e.g., in [tensorflow](https://www.tensorflow.org/api_guides/python/sparse_ops) and [thano](http://deeplearning.net/software/theano/tutorial/sparse.html). I haven't dug to see how compatible these are with the numpy API, but there are more hand-built pure-python implementations around too. 

Numpy compatibility would allow minimal work, of course, but also mixing sparse and dense blocks within the same dask.array.

**Comment by mrocklin** [comment]
I don't believe that Theano or Tensorflow provide immediate sparse matrix data structures that are relevant for our use.  At least when I was working on it Theano sparse arrays were compiled down to scipy.sparse.  Just because they have a concept of a sparse matrix in the language does not mean that they include a data structure relevant for us.  

Tensorflow probably does have a separate sparse matrix implementation somewhere.  It would be behind a lot of compilation machinery though.  I think that these libraries are not a good fit for what we need.  (at least not today).  Also the scipy sparse implementations are fine.  My experience has been that almost all CSR/CSC implementations look more or less the same.

**Comment by mrocklin** [comment]
@jcrist you raised concerns earlier about expanding the scope of dask.array to support multiple in-memory containers.  Can you look at this PR and see if those concerns remain?  

So far I've been surprised to find that compatibility is surprisingly easy.  I'm now tempted to push towards making dask.array in-memory-container agnostic for common case operations.

**Comment by jcrist** [comment]
I had two main concerns (and one minor one), and I'd say that they still remain:

- A disconnect in operations depending on backend. Numpy arrays are n-dimensional. Scipy sparse matrices are always 2d. They also don't support all the same methods or keyword arguments (as you've found). Since we don't track the type of the chunks (e.g. sparse/dense) there'd be no way to know if an operation would fail until compute time.

- Hard to reason about performance. Accidental conversion of sparse to dense could lead to unexpected memory usage. As is in this PR, calling `compute` will return a numpy array, even if all the chunks are sparse arrays. Of course, we could fix concatenate, but I'd still be wary of this.

- Potential desire for different metadata. This is more of an imagined issue, but I could see a need to know if a dask array is sparse or dense, and potentially the type of its storage format (e.g. `csr`, etc...). Given one format, some operation may be more efficient done one way or another. We may also want to include methods to convert by chunk from one format to another.

Given the differences in supported operations, performance reasoning, and different metadata, I really think sparse arrays would be best wrapped by a separate class. That said, they could share a base class with dask array and/or reuse many of the same functions that make dask array work (e.g. atop). I just think that at a user facing level there is benefit to having a different and restricted interface that better matches the in memory container being wrapped.

**Comment by mrocklin** [comment]
OK, those make sense.  Perhaps a common base class is what I'm after.  In general I think that most lines of code in dask.array have relatively little to do with dense arrays and much more to do with parallel algorithms over multi-dimensional blocked arrays.  That code should apply equally well to a variety of cases.  

Another thought here is that we could start tracking chunk-type in the same way that we track dtype and chunksize.  We could include this chunk-type in metadata checks.  This would presumably help us to understand when we change container type and would catch illegal operations early.

I agree that accidental conversion of sparse to dense is an issue, however it's also an unresolved issue for the in-memory libraries today.

**Comment by jcrist** [comment]
> ... That code should apply equally well to a variety of cases.

Agreed.

> ... we could start tracking chunk-type in the same way that we track dtype and chunksize.

I feel like a different class fits better here, as we want a different (more restricted) interface. Either would work though.

**Comment by mrocklin** [comment]
> I feel like a different class fits better here, as we want a different (more restricted) interface. Either would work though.

My discomfort here is that we're then on the hook to maintain another large API.  There is a fair amount of boiler plate here that will take some investment to build and maintain.  We'll also need to include various transformation functions etc. that go between all of the different collections.  This takes development time to get right both now and in the future.  

I think that the positive example for merging everything is recent change to support unknown chunk shapes.  These have many of the same problems with not supporting all operations, not having performance guarantees, etc..  However in this case (which admittedly is probably simpler) things seem to be going well.  Users get informative feedback on wrong behavior immediately and there are no explicit API switches that the user has to be aware of.  This had strong positive impact on development immediately after implementation.

**Comment by jcrist** [comment]
> My discomfort here is that we're then on the hook to maintain another large API. There is a fair amount of boiler plate here that will take some investment to build and maintain.

That's fair. My motivation for a separate class was also minimizing effort here. In my mind implementing with a separate class is some boilerplate work to separate a base class, then simple methods for the supported sparse operations that look something like (imaginary example, not saying we'd really do this):

```python
def sum(self, axis=None, dtype=None):
    return super(SparseArray, self).sum(axis=axis, dtype=dtype)
```

The same class solution might look like:

```python
def sum(self, axis=None, dtype=None, keepdims=None):
    if self.format != 'dense' and keepdims is not None:
        raise ValueError("Sparse arrays don't support keepdims")
    <rest of the method>
```

For operations that sparse arrays don't support at all, we would just not define the method on the subclass, rather than having a check on every method to see if it's supported and error if it isn't:

```python
def not_supported_method(...):
    if self.format != 'dense':
        raise NotImplementedError("Sparse arrays don't support this method. Use "
                                  "`.todense()` to convert to a dense array beforehand.")
    <rest of the method>
```

I may be misjudging which way is simpler though. Either is fine, my intent was also to minimize maintenance here.

**Comment by mrocklin** [comment]
Closing in support of #2234

**Pull request closed without merging**
