### PR TITLE
[DO NOT MERGE] Test upstream CI build

### PR DESCRIPTION
**Pull request by jrbourbeau**
Checking to see if our upstream build is passing (xref https://github.com/dask/dask/issues/8776#issuecomment-1084932584)

### CODE REVIEW

**Comment by jrbourbeau** [comment]
Looks like we're still installing the same nightly version as yesterday. Actually, if I look back a few days, installing from https://pypi.anaconda.org/scipy-wheels-nightly/simple is giving the same pandas nightly package version. @jorisvandenbossche do you know if there are any known issues around pandas nightly versions not being updated?

**Comment by jorisvandenbossche** [comment]
https://pypi.anaconda.org/scipy-wheels-nightly/simple/pandas/ indicates that there are more recent pandas versions, but so not directly an idea why pip is only finding an older one (pandas-1.5.0.dev0+506.g17dda440f9). 

Locally, I get the same (in a clean env):

```
$     python -m pip install --no-deps --pre \
>         -i https://pypi.anaconda.org/scipy-wheels-nightly/simple \
>         numpy \
>         pandas
Looking in indexes: https://pypi.anaconda.org/scipy-wheels-nightly/simple
Collecting numpy
  Downloading https://pypi.anaconda.org/scipy-wheels-nightly/simple/numpy/1.23.0.dev0%2B967.g41cf10dcb/numpy-1.23.0.dev0%2B967.g41cf10dcb-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.0/17.0 MB 90.3 kB/s eta 0:00:00
Collecting pandas
  Downloading https://pypi.anaconda.org/scipy-wheels-nightly/simple/pandas/1.5.0.dev0%2B506.g17dda440f9/pandas-1.5.0.dev0%2B506.g17dda440f9-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.9/11.9 MB 53.3 kB/s eta 0:00:00
Installing collected packages: pandas, numpy
Successfully installed numpy-1.23.0.dev0+967.g41cf10dcb pandas-1.5.0.dev0+506.g17dda440f9
```

**Comment by simonjayhawkins** [comment]
it looks like it maybe quite simple to fix... the test is not being skipped by `is_ci_environment` added in https://github.com/pandas-dev/pandas/pull/45812. looks like we need to set an environment variable for MacPython.

**Comment by simonjayhawkins** [comment]
> Looks like we're still installing the same nightly version as yesterday. Actually, if I look back a few days, installing from https://pypi.anaconda.org/scipy-wheels-nightly/simple is giving the same pandas nightly package version. @jorisvandenbossche do you know if there are any known issues around pandas nightly versions not being updated?

should be ok now.

**Comment by jrbourbeau** [comment]
> should be ok now.

Awesome, thanks for the update @simonjayhawkins! Indeed I'm no longer seeing the segfault 🎉 

> It looks like I forgot to actually merge https://github.com/dask/dask/pull/8558 - so it's that and some new groupby failures

Rerunning now that https://github.com/dask/dask/pull/8558 has been merged

**Comment by ian-r-rose** [comment]
Looks like a lot of the failures are due to https://github.com/pandas-dev/pandas/pull/34998, merged a few days ago

**Comment by jsignell** [comment]
> Looks like a lot of the failures are due to [pandas-dev/pandas#34998](https://github.com/pandas-dev/pandas/pull/34998), merged a few days ago

Oh that is a very nice change! It seems like it will make groupby much more predictable going forward. I can open a PR to address the changes that we need in dask. Unless someone is already on it?

**Comment by jrbourbeau** [comment]
I'm not aware of anyone working it : )

**Comment by jcrist** [comment]
Is there more you wanted to poke at here, or can this be closed?

**Pull request closed without merging**
