### PR TITLE
tensordot: ensure `axes` are positive / add tests for negative axes

### LINKED ISSUE #10811: `dask.array.tensordot` bug: negative values in argument `axes`  give wrong results.
**Describe the issue**:
While `numpy.tensordot` accepts negative axes, negative axes in `dask.array.tensordot`  give wrong results.

**Minimal Complete Verifiable Example**:

```python
import numpy as np
import dask.array as da

rng = np.random.default_rng()
a = rng.normal(size=(30, 10))
b = rng.normal(size=(10, 20))

kwargs = dict(axes=[[-1], [0]])
np_z = np.tensordot(a, b, **kwargs)
da_z = da.tensordot(da.array(a), da.array(b), **kwargs)
print(np_z.shape) 
# (30, 20) 
print(da_z.shape)
# (30, 1)
```

### PR DESCRIPTION
**Pull request by joanrue**
While `numpy.tensordot` accepts negative axes, negative axes in `dask.array.tensordot` were giving wrong results. This bug is easily fixed by ensuring that the left axes are positive before the sum-reduction step. 

- [x] Closes #10811
- [x] Tests added / passed
- [x] Passes `pre-commit run --all-files`

Co-authored-by: Sepand Kashani <sepand@kashani.ch>

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

Admins can comment `ok to test` to allow this one PR to run or `add to allowlist` to allow all future PRs from the same author to run.

**Comment by joanrue** [comment]
Hi! I'm reaching out to see if there's anything more I can do to facilitate the review process.

**Comment by joanrue** [comment]
Hi @hendrikmakait ! The only failing test is not related to these changes. Can we go ahead with the PR?

**Review by phofl — APPROVED** [review]

**Comment by phofl** [comment]
thx

**Pull request merged**
