### PR TITLE
Work around "#" getting special treatment in paths

### LINKED ISSUE #5036: dask.dataframe read_csv, to_csv crashes when '#' in path
$ pip freeze | grep -E 'dask|pandas'
dask==2.0.0
pandas==0.24.2

```
import dask.dataframe as ddf
import pandas as pd
from os import mkdir
from os.path import join
folder='Fdcm #31H~Vell 1_Out'
mkdir(folder)
df = pd.DataFrame({'A': [1, 1], 'B': [3, 3]})
df.to_csv(join(folder,'fil.csv'))
df2=ddf.from_pandas(df,npartitions=1)
df2.to_csv(join(folder,'fil2*.csv'))
```

```pytb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "%USERPROFILE%\Miniconda3\lib\site-packages\dask\dataframe\core.py", line 1167, in to_csv
    return to_csv(self, filename, **kwargs)
  File "%USERPROFILE%\Miniconda3\lib\site-packages\dask\dataframe\io\csv.py", line 661, in to_csv
    delayed(values).compute(scheduler=scheduler)
  File "%USERPROFILE%\Miniconda3\lib\site-packages\dask\base.py", line 156, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "%USERPROFILE%\Miniconda3\lib\site-packages\dask\base.py", line 398, in compute
    results = schedule(dsk, keys, **kwargs)
  File "%USERPROFILE%\Miniconda3\lib\site-packages\dask\threaded.py", line 76, in get
    pack_exception=pack_exception, **kwargs)
  File "%USERPROFILE%\Miniconda3\lib\site-packages\dask\local.py", line 462, in get_async
    raise_exception(exc, tb)
  File "%USERPROFILE%\Miniconda3\lib\site-packages\dask\compatibility.py", line 112, in reraise
    raise exc
  File "%USERPROFILE%\Miniconda3\lib\site-packages\dask\local.py", line 230, in execute_task
    result = _execute_task(task, data)
  File "%USERPROFILE%\Miniconda3\lib\site-packages\dask\core.py", line 119, in _execute_task
    return func(*args2)
  File "%USERPROFILE%\Miniconda3\lib\site-packages\dask\dataframe\io\csv.py", line 508, in _write_csv
    with fil as f:
  File "%USERPROFILE%\Miniconda3\lib\site-packages\dask\bytes\core.py", line 183, in __enter__
    f = SeekableFile(self.fs.open(self.path, mode=mode))
  File "%USERPROFILE%\Miniconda3\lib\site-packages\dask\bytes\local.py", line 61, in open
    return open(self._normalize_path(path), mode=mode)
FileNotFoundError: [Errno 2] No such file or directory: '%USERPROFILE%\\Projects\\Fdcm \\0.part'
```

### PR DESCRIPTION
**Pull request by martindurant**
- [ ] Tests added / passed
- [ ] Passes `black dask` / `flake8 dask`

Fixes #5036

### CODE REVIEW

**Comment by martindurant** [comment]
@TomAugspurger , the appveyor failure looks like one of the ones you were following

**Comment by TomAugspurger** [comment]
Appveyor isn't loading for me right now :/ But there is a random failure related to partd that I'm tracking.

I just noticed the `allow_fragements` option to `urlsplit`: https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urlsplit Does that avoid the need for re-joining the parsed value?

**Comment by martindurant** [comment]
Hm, interesting, I don't think that existed in previous versions (or I just didn't know). Not sure what to make of the statement about not stripping parameters, though, maybe best to leave it?

**Comment by TomAugspurger** [comment]
IIUC, the difference arises when you have query parameters and fragments:

```
In [9]: urllib.parse.urlparse('file://foo/bar?baz#qux', allow_fragments=False).path
Out[9]: '/bar'

In [10]: urllib.parse.urlparse('file://foo/bar#qux', allow_fragments=False).path
Out[10]: '/bar#qux'
```

With your implementation, `Out[9]` would be `/bar#qux`. IMO, following the stdlib here is probably best, but this is admittedly ambiguous.

**Comment by martindurant** [comment]
I don't suppose any of those characters are legal on windows!

**Comment by mrocklin** [comment]
The `partd` error is, I think, no longer active.   Restarting windows tests.

**Comment by quasiben** [comment]
@martindurant or @mrocklin can you restart the AppVeyor test ?  I don't have access

**Comment by martindurant** [comment]
Done. Although, in practice, this should and is fixed in fsspec.

**Pull request closed without merging**
