### PR TITLE
Make ddf * df have correct _meta

### LINKED ISSUE #6441: Inconsistent metadata after multiplication
**What happened**:
If a dask.DataFrame is multiplied with a pandas.Series, the metadata becomes inconsistent with the actual data.

**What you expected to happen**:
Metadata should be updated accordingly.

**Minimal Complete Verifiable Example**:

```python
import dask.dataframe as dd
import pandas as pd
import numpy as np

df = pd.DataFrame(np.ones((10, 3)), columns=list('BCA'))
factors = pd.Series([1, 2, 3], index=list('ABC'))

ddf = dd.from_pandas(df, 1)
ddf_mul = ddf * factors
res = ddf_mul.map_partitions(lambda x: x)
res.compute()
```
This will raise the following error:
```
ValueError: The columns in the computed data do not match the columns in the provided metadata
Order of columns does not match
```

**Environment**:

- Dask version: 2.21.0
- Python version: 3.7
- Operating System: macOS
- Install method (conda, pip, source): pip

### PR DESCRIPTION
**Pull request by jsignell**
- [x] Tests added / passed
- [x] Passes `black dask` / `flake8 dask`
- [x] Closes #6441 

If this is a good idea then I can add more dunder methods.

### CODE REVIEW

**Comment by quasiben** [comment]
I am +1 on this.  @TomAugspurger  ?

**Comment by TomAugspurger** [comment]
Looking through it now. A couple things:

1.Need to check if / how this is overwriting `__mul__` method that's created through `OperatorMethodMixin` and `_bind_binary_operator`. Are we defining it twice?
2.  `meta` is currently defined in `elemwise` at

```python
4772        if meta is no_default:
4773            if len(dfs) >= 2 and not all(hasattr(d, "npartitions") for d in dasks):
4774                # should not occur in current funcs
4775                msg = "elemwise with 2 or more DataFrames and Scalar is not supported"
4776                raise NotImplementedError(msg)
4777            # For broadcastable series, use no rows.
4778            parts = [
4779                d._meta
4780                if _is_broadcastable(d)
4781                else np.empty((), dtype=d.dtype)
4782                if isinstance(d, Array)
4783                else d._meta_nonempty
4784                for d in dasks
4785            ]
4786            with raise_on_meta_error(funcname(op)):
4787 ->             meta = partial_by_order(*parts, function=op, other=other)
```

We've converted the user-provided pandas Series to a Dask Array

```python
(Pdb) pp dasks[1].compute()
A    1
B    2
C    3
dtype: int64
```

and truncated it

```python
(Pdb) pp parts[1]
Series([], dtype: int64)
``` 

We would get the right `meta` if we just used the pandas object

```python
(Pdb) pp partial_by_order(parts[0], dasks[1].compute(), function=op, other=other)
     A    B    C
0  1.0  2.0  3.0
1  1.0  2.0  3.0
```

Would it be better to fix `elemwise` by using the pandas object? (probably). What would "fixing" it break? (no idea)

**Comment by jsignell** [comment]
Thanks @TomAugspurger for pointing out how it currently works. I totally missed that. It seems clear that what I've done in this PR isn't the right approach, but it does seem odd to follow such different paths for `mul` and `__mul__`. Wouldn't you expect them to do the same thing?

**Comment by TomAugspurger** [comment]
> it does seem odd to follow such different paths for mul and __mul__. Wouldn't you expect them to do the same thing?

Yep, agreed for the most part. They'll need to start on different paths since `DataFrame.mul` has different parameters than `DataFrame.__mul__`, but they should quickly converge on the same path to get consistent behavior.

**Comment by jsignell** [comment]
So I guess the question is - which is the better approach: using `elemwise` or `map_partitions`?

**Comment by jsignell** [comment]
Predictably, this is much gnarlier than anticipated. I think `elemwise` is the right approach but that method is used so broadly that it is hard to make changes in there. I am going to close this for now as I don't think it's particularly important.

**Pull request closed without merging**
