### PR TITLE
Add `py` to CI for `pytest=7.2.0` compatibility 

### PR DESCRIPTION
**Pull request by jrbourbeau**

### CODE REVIEW

**Comment by jakirkham** [comment]
Maybe this is related to the recent `pytest` upgrade ( https://github.com/conda-forge/pytest-feedstock/pull/153 )? Perhaps we can raise a reproducer on that feedstock

**Review by jakirkham — APPROVED** [review]
Thanks James! 🙏

**Comment by jrbourbeau** [comment]
Thanks for reviewing @jakirkham! Just noting that https://github.com/conda-forge/pytest-xdist-feedstock/pull/48 appears to resolve issues on the `pytest-xdist` side. If CI passes here, I'd still like to merge this in to unblock other CI builds ASAP. But we may be able to revert this change relatively quickly

**Comment by jakirkham** [comment]
Oh looks like that PR is already merged too, which means there should already be packages available. Should we just retest CI then?

**Comment by jrbourbeau** [comment]
Based on https://github.com/dask/dask/pull/9595#issuecomment-1291081104, let's see if CI in that PR passes (or at least doesn't run into the `pytest` issue we're seeing on `main`). If it does, then we can safely close this PR. If it doesn't (e.g. some other `pytest-*` package also needs to be updated) then let's go ahead with this PR.

**Comment by jrbourbeau** [comment]
Okay, it looks like the new `pytest-xdist=3.0.2` release did the trick. Closing this PR as it's no longer needed.

**Pull request closed without merging**
