### PR TITLE
ENH Adds empty mode to array.pad

### LINKED ISSUE #5161: Add "empty" mode for `da.pad`
NumPy 1.17.0 adds a new mode to `np.pad` called "empty", which pads the provided array with uninitialized arrays (like `np.empty`). Would be good to add this to `da.pad` as well.

### PR DESCRIPTION
**Pull request by thomasjpfan**
Closes #5161

- [x] Tests added / passed
- [x] Passes `black dask` / `flake8 dask`

### CODE REVIEW

**Comment by quasiben** [comment]
I see this is  your first time contributing, welcome!

@thomasjpfan this looks really great! There is currently a test failure due to incompatibility with older versions of NumPy.  You can skip the skip the test like we do here:

https://github.com/dask/dask/blob/54deb7fa4cdbbf3e124be6834224272be27ace65/dask/array/tests/test_routines.py#L812-L814

**Comment by thomasjpfan** [comment]
Thank you for looking at this so quickly!

Updated PR with a `pytest.mark.skipif` in the `parametrize` to skip if the numpy version is not >1.17

**Comment by quasiben** [comment]
Thanks for updating so quickly!  As I'm not very familiar with the array side of dask I'm going to wait until tomorrow to merge giving other reviewers some time to comment

**Comment by TomAugspurger** [comment]
Thanks!

**Comment by jakirkham** [comment]
Thanks Thomas! 😄

Great seeing you over here at Dask. Hopefully we see more of you in the future 😉

**Comment by thomasjpfan** [comment]
@jakirkham It is always fun diving into another codebase. ;)

**Pull request merged**
