### PR TITLE
 Moment: handle all elements being masked

### LINKED ISSUE #5338: std() fails on masked array of all masked elements
```python
In [1]: import numpy as np                                                                                                                                                                                 

In [2]: import dask.array as da                                                                                                                                                                            

In [3]: all_masked = np.ma.masked_array([1, 2], mask=[True, True])                                                                                                                                         

In [4]: all_masked.std()                                                                                                                                                                                   
Out[4]: masked

In [5]: dask_all_masked = da.ma.masked_array([1, 2], mask=[True, True])                                                                                                                                    

In [6]: dask_all_masked.std().compute()                                                                                                                                                                    
---------------------------------------------------------------------------
MaskError                                 Traceback (most recent call last)
<ipython-input-6-dd8d98362ed2> in <module>
----> 1 dask_all_masked.std().compute()

~/dl/forks/dask/dask/base.py in compute(self, **kwargs)
    173         dask.base.compute
    174         """
--> 175         (result,) = compute(self, traverse=False, **kwargs)
    176         return result
    177 

~/dl/forks/dask/dask/base.py in compute(*args, **kwargs)
    444     keys = [x.__dask_keys__() for x in collections]
    445     postcomputes = [x.__dask_postcompute__() for x in collections]
--> 446     results = schedule(dsk, keys, **kwargs)
    447     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    448 

~/dl/forks/dask/dask/threaded.py in get(dsk, result, cache, num_workers, pool, **kwargs)
     80         get_id=_thread_get_id,
     81         pack_exception=pack_exception,
---> 82         **kwargs
     83     )
     84 

~/dl/forks/dask/dask/local.py in get_async(apply_async, num_workers, dsk, result, cache, get_id, rerun_exceptions_locally, pack_exception, raise_exception, callbacks, dumps, loads, **kwargs)
    489                         _execute_task(task, data)  # Re-execute locally
    490                     else:
--> 491                         raise_exception(exc, tb)
    492                 res, worker_id = loads(res_info)
    493                 state["cache"][key] = res

~/dl/forks/dask/dask/compatibility.py in reraise(exc, tb)
    128         if exc.__traceback__ is not tb:
    129             raise exc.with_traceback(tb)
--> 130         raise exc
    131 
    132     import pickle as cPickle

~/dl/forks/dask/dask/local.py in execute_task(key, task_info, dumps, loads, get_id, pack_exception)
    231     try:
    232         task, data = loads(task_info)
--> 233         result = _execute_task(task, data)
    234         id = get_id()
    235         result = dumps((result, id))

~/dl/forks/dask/dask/core.py in _execute_task(arg, cache, dsk)
    116     elif istask(arg):
    117         func, args = arg[0], arg[1:]
--> 118         args2 = [_execute_task(a, cache) for a in args]
    119         return func(*args2)
    120     elif not ishashable(arg):

~/dl/forks/dask/dask/core.py in <listcomp>(.0)
    116     elif istask(arg):
    117         func, args = arg[0], arg[1:]
--> 118         args2 = [_execute_task(a, cache) for a in args]
    119         return func(*args2)
    120     elif not ishashable(arg):

~/dl/forks/dask/dask/core.py in _execute_task(arg, cache, dsk)
    117         func, args = arg[0], arg[1:]
    118         args2 = [_execute_task(a, cache) for a in args]
--> 119         return func(*args2)
    120     elif not ishashable(arg):
    121         return arg

~/dl/forks/dask/dask/array/reductions.py in moment_agg(pairs, order, ddof, dtype, sum, axis, computing_meta, **kwargs)
    731             denominator = np.nan
    732     else:
--> 733         denominator[denominator < 0] = np.nan
    734 
    735     return divide(M, denominator, dtype=dtype)

~/.local/share/virtualenvs/dask-dyglJSq3/lib/python3.7/site-packages/numpy/ma/core.py in __setitem__(self, indx, value)
   3288         """
   3289         if self is masked:
-> 3290             raise MaskError('Cannot alter the masked element.')
   3291         _data = self._data
   3292         _mask = self._mask

MaskError: Cannot alter the masked element.
```

### PR DESCRIPTION
**Pull request by gjoseph92**
This _almost_ works, but still fails for `std`, which returns 1-element array where the element is masked, instead of the MaskedConstant it should.

The issue is that `np.sqrt` doesn't return a masked constant, whereas `np.ma.sqrt` does:

```python
In [1]: import numpy as np                                                                                                                                                                                                                                                                                                                                                                                                                                       

In [2]: np.sqrt(np.ma.masked)                                                                                                                                                                                                                                                                                                                                                                                                                                    
Out[2]: 
masked_array(data=--,
             mask=True,
       fill_value=1e+20,
            dtype=float64)

In [3]: np.ma.sqrt(np.ma.masked)                                                                                                                                                                                                                                                                                                                                                                                                                                 
Out[3]: masked
```

`da.std` [calls `sqrt`](https://github.com/dask/dask/blob/master/dask/array/reductions.py#L818), which is a [dask ufunc wrapping `np.sqrt`](https://github.com/dask/dask/blob/2d8dd51fcdec25e8781ad69e40acfc5947bfb393/dask/array/ufunc.py#L222).

Replacing the `sqrt` ufunc with the masked version seems like a potentially significant change around the edge cases. For example, they handle NaN differently:

```python
In [1]: import numpy as np                                                                                                                                                                                                                                                                                                                                                                                                                                       

In [2]: np.ma.sqrt(np.nan)                                                                                                                                                                                                                                                                                                                                                                                                                                       
Out[2]: masked

In [3]: np.sqrt(np.nan)                                                                                                                                                                                                                                                                                                                                                                                                                                          
Out[3]: nan
```

I tried this in 45cef9a, but it doesn't seem like a good idea. (And breaks other tests due to the above discrepancy).

So the question is: how to write `std` in such a way that if the variance is a MaskedConstant, we just return the MaskedConstant without passing it to `sqrt`? (Or use a different version of `sqrt` that handles the MaskedConstant correctly, but doesn't interpret NaN as masked?)

- [x] Tests added / passed
- [x] Passes `black dask` / `flake8 dask`

Closes #5338.

### CODE REVIEW

**Comment by gjoseph92** [comment]
@mrocklin 2d8dd51 is my initial thought on how to resolve #5338, but I really don't know what to do about `sqrt`'s handling of masked constants. Looking for some ideas here.

**Comment by mrocklin** [comment]
@jcrist do you have a moment to look through this?  I've never really touched masked arrays before.

**Comment by mrocklin** [comment]
Also, I wonder if @bjlittle could recommend someone to help review this

**Comment by mrocklin** [comment]
cc'ing also @DPeterK in case he knows someone comfortable with reviewing masked array code.

**Comment by TomAugspurger** [comment]
Hows this going @gjoseph92? Is there anything in particular that others like @bjlittle or @DPeterK can help out with?

**Comment by mrocklin** [comment]
@TomAugspurger , this is currently blocked on people able to review masked array code.  

It seems like we no longer have anyone qualified who is able to review these things.  I wonder if we should stop supporting masked arrays.  @jacobtomlinson do you know if this is still used within UK Met?  If so, do you know anyone there who we could lean on to help?

**Comment by jacobtomlinson** [comment]
AFAIK it is and I think @DPeterK is the right person to ping, he's just on vacation right now.

**Comment by gjoseph92** [comment]
@TomAugspurger I've been out on vacation myself, so just catching up on this.

The core issue is that dask's data model for masked arrays doesn't quite line up with NumPy's (and frankly, kind of abuses dask's)—NumPy uses a separate subclass, while dask holds them in a plain dask array, and just knows that the functions in the graph will produce masked arrays. I don't believe there's a definitive way to tell if a dask array is masked or not without actually computing it. I think `_meta` isn't reliable; I remember some cases where `_meta` would be explicitly instantiated as a `np.array` regardless of input type, though of course I can't remember where now. More generally, I'd guess dask just doesn't play well with any ndarray subclasses, MaskedArray included.

Besides making a separate dask MaskedArray subclass (lot of effort), we could at least expose dask versions of all the `np.ma` ufuncs, so you'd have access to those versions when you needed them. But then you'd also want masked versions of the reductions (`da.masked_std` would need to use `da.masked_sqrt`, for example). Still a lot of effort and code duplication.

We could also make the dask ufuncs automatically switch between masked and non-masked versions on the type of the input array (like I mentioned [here](https://github.com/dask/dask/pull/5339#discussion_r319151225)). But that seems bad, because users can't control it, and it changes current behavior out from under them.

Or, to get this merged, I can just remove the test for `std` or `@pytest.mark.xfail` it. The fact that masked arrays likely need their own versions of many functions to behave correctly is its own, much larger issue.

**Comment by mrocklin** [comment]
This appears to be stalled.  @jcrist you're probably the best equiped person to handle this, but I can understand that it might not be high in your priority list.  I thought I'd make you aware of it in case you have some extra time.

@gjoseph92 I apologize that no one has been found who is able to review this work so far.

**Comment by jcrist** [comment]
Thanks @gjoseph92. I've updated this PR to make the required fixes a bit more localized. Thanks for being patient here, this one slipped through the cracks (apologies).

**Comment by jcrist** [comment]
Hmmm, tests are failing for numpy 1.15. Debugging.

**Comment by jcrist** [comment]
Was a bug in the test, fixed now.

**Comment by gjoseph92** [comment]
Wow thanks @jcrist! Wasn't expecting this to get solved, but we've still been running into it, so I really appreciate the help. `safe_sqrt` is a good solution here; looks good to me.

**Comment by jcrist** [comment]
Failure is unrelated. cc @jrbourbeau or @TomAugspurger for a quick review, but I think this is good-to-go.

**Pull request merged**
