### PR TITLE
Faster slice_1d in dask.array

### PR DESCRIPTION
**Pull request by rainwoodman**
- [X] Tests added / passed: dask/array/tests/
- [X] Passes `flake8 dask`

### CODE REVIEW

**Comment by mrocklin** [comment]
cc @TomAugspurger what is the current status on asv benchmarks?

**Comment by TomAugspurger** [comment]
The benchmarks in https://github.com/dask/dask-benchmarks are run and
posted to http://pandas.pydata.org/speed/dask/

**Comment by mrocklin** [comment]
At first glance this looks great to me.  I have a hard time coming up with a situation where this is likely to hurt performance, and the times when it is likely to help are numerous.

cc @shoyer

**Comment by shoyer** [comment]
This looks like a nice win to me, too.

**Comment by mrocklin** [comment]
This can probably go in once the benchmark tests are (re)moved.  Ideally these would land in dask-benchmarks, this would be good to make it less likely that we will regress here, but is not strictly necessary.  We aren't currently diligent about collecting benchmarks.

**Comment by rainwoodman** [comment]
The benchmark framework is cool. I will move the benchmarks there as a PR.

**Comment by shoyer** [comment]
I was going to ask about speeding up indexing with a list, but it looks like that already uses essentially this algorithm via the `partition_by_size()` helper function.

**Comment by rainwoodman** [comment]
`partition_by_size` needs some documentation. I can only vaguely understand what it does -- up to the first partition.

**Comment by mrocklin** [comment]
I'm going to go ahead and merge this.  I definitely encourage more discussion in this area though.  Thank you for identifying and accelerating a performance bug @rainwoodman !

**Pull request merged**
