### PR TITLE
Handle plot_width / plot_height deprecations

### PR DESCRIPTION
**Pull request by bryevdv**
cc @jrbourbeau 

Bokeh 3.0 will also finally execute the deprecations of `plot_width` and `plot_height` and expose only `width` and `height` (consistent with every other layout-able). 

Ran relevant unit tests locally with several versions 2.1.1 to 3.0dev. @jrbourbeau can you remind me where these plots actually show up? Are they included in the dashboard? something else? If the dashboard, could this code be moved to the other repo?

### CODE REVIEW

**Comment by bryevdv** [comment]
cc @jrbourbeau FYI looks like the test runner for the one failed test never started

**Comment by jsignell** [comment]
@bryevdv should we also deprecate this backwards compatibility code?

https://github.com/dask/dask/blob/54139c11c0527e1d6daaa5b3ad306155add52a5d/dask/diagnostics/profile_visualize.py#L252-L258

**Comment by bryevdv** [comment]
@jsignell  I was not sure who or what might be passing in those param values. I didn't see anything jump out in the codebase itself. I figured just leave that there until the min version is upped to 3.x, and then remove it would be sufficient. I suppose a deprecation could be emitted but I'd only do it for Bokeh >= 3.0.

**Review by jrbourbeau — COMMENTED** [review]
Thanks @bryevdv! 

It looks like when visualizing a profiler

https://github.com/dask/dask/blob/54139c11c0527e1d6daaa5b3ad306155add52a5d/dask/diagnostics/profile.py#L88-L97

we end up calling the profiler's `._plot` method

https://github.com/dask/dask/blob/54139c11c0527e1d6daaa5b3ad306155add52a5d/dask/diagnostics/profile_visualize.py#L193

which in turn calls functions with `plot_width` / `plot_height` compatibility code 

https://github.com/dask/dask/blob/54139c11c0527e1d6daaa5b3ad306155add52a5d/dask/diagnostics/profile_visualize.py#L252-L256

I agree that, if using `bokeh >= 3`, a small deprecation warning would be nice to have

**Comment by bryevdv** [comment]
@jsignell @jrbourbeau for sure, how do you normally issue deprecations warnings? Just `warnings.warn` or do you have some custom project API for it?

**Comment by jrbourbeau** [comment]
We have a [`_deprecated` decorator](https://github.com/dask/dask/blob/336aac39ee8a616ac2645e532392123ae1bfddd1/dask/utils.py#L42) that we use for conveniently deprecating entire methods, but otherwise just use `warnings.warn` (which I'd recommend for this particular case)

**Comment by bryevdv** [comment]
@jsignell @jrbourbeau the one windows test failures look unrelated? 
```
FAILED dask/tests/test_base.py::test_persist_array_bag - concurrent.futures.p...
FAILED dask/tests/test_multiprocessing.py::test_random_seeds[random] - OSErro...
FAILED dask/tests/test_threaded.py::test_reuse_pool[ThreadPool] - RuntimeErro...
ERROR dask/tests/test_distributed.py::test_blockwise_fusion_after_compute - P...
```
Can the tests be re-run, or is there anything else needed for this PR?

**Comment by jsignell** [comment]
Yeah the windows tests failures are unrelated. I haven't gotten a change to try this out yet, but I don't think that should block merge.

**Comment by jsignell** [comment]
Ok I just tried it! Looks good!

**Comment by jrbourbeau** [comment]
Thanks @bryevdv @jsignell!

**Pull request merged**
