### PR TITLE
Fix Precision Handling in `array.linalg.norm`

### LINKED ISSUE #7718: Frobenius norm promotes float32 matrix to float64 norm
When applying a Frobenius norm on a float32 matrix, a float64 outcome is generated. A float32 should be expected (similar to numpy). I will try to have a look at this problem next week. Not sure whether the same is true for int-type and complex-type matrices. It might also improve the calculation speed a bit.

Cheers.

**Minimal Complete Verifiable Example**:

```python
import numpy as np
a_64 = np.random.rand(500,500)
a_32 = a_64.astype(np.float32)
print(a_64.dtype, a_32.dtype) # float64 float32
print(np.linalg.norm(a_64, 'fro').dtype, np.linalg.norm(a_32, 'fro').dtype) # float64 float32

import dask.array as da
da_a_64 = da.asarray(a_64)
da_a_32 = da.asarray(a_32)
print(da_a_64.dtype, da_a_32.dtype) # float64 float32
print(da.linalg.norm(da_a_64, 'fro').dtype, da.linalg.norm(da_a_32, 'fro').dtype) # float64 float64
```

**Environment**:

- Dask version: '2021.04.0'
- Numpy version: '1.19.2'
- Python version: 3.8.3
- Operating System: Windows 10

### PR DESCRIPTION
**Pull request by joanrue**
- Closes #7718, where the concern of unintended coercion to double precision in array.linalg.norm was raised. 
- Added tests to validate that the precision aligns with NumPy's standards for single and double precision, both for floating-point and complex numbers. 
- Passes `pre-commit run --all-files`

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

Admins can comment `ok to test` to allow this one PR to run or `add to allowlist` to allow all future PRs from the same author to run.

**Comment by joanrue** [comment]
I've removed the tests that compare the output data types of Dask and NumPy. In Python 3.9 with NumPy 1.22, these tests fail because numpy.linalg.norm() always returns a double precision output.

**Review by phofl — COMMENTED** [review]
Could you add a test?

**Comment by joanrue** [comment]
Hi @phofl , 

Many thanks for checking out this PR! 
Following your suggestion, I've added a test to check that the the output of `dask.array.linalg.norm`  is of equivalent `dtype` as the input array. All tests pass except in Windows py3.11,   where **only one test** (`[gw0] [ 12%] FAILED dask/array/tests/test_array_core.py::test_setitem_hardmask `) fails. 

It seems the test that failes is not related to `dask.array.linalg.norm`, and I am not sure why it failed. Do you have any clue what might happen?

**Comment by joanrue** [comment]
I've added a test to check that `dask.array.linalg.norm` output's precision matches `numpy.linalg.norm`, however, for py3.9, Numpy's version doesn't compute at the input precision for `float32`.

**Comment by phofl** [comment]
I think you can ignore the setitem failure

I would xfail the test for python 3.9

**Comment by joanrue** [comment]
Many thanks for your feedback  @phofl , 

I've `xfail`ed the tests with `Numpy < 1.23` as before that version there was no i/o precision consistency for all the combinations of arguments of `linalg.norm` (see https://github.com/numpy/numpy/pull/17709). 
A new error appears for Ubuntu py3.12 in  `dask/dataframe/tests/test_arithmetics_reduction.py`, which is unrelated to the `linalg.norm`, I guess it can be ignored (?) .

**Review by phofl — APPROVED** [review]

**Comment by phofl** [comment]
thx @joanrue 

yes ci is a little flaky at the moment unfortunately

**Pull request merged**
