### PR TITLE
Clearing the key cache when deleting dataframe items

### PR DESCRIPTION
**Pull request by madsbk**

### CODE REVIEW

**Comment by madsbk** [comment]
OK, apparently the `self._cached_keys` is more then just a cache :)

**Comment by mrocklin** [comment]
OK, so there are a couple of issues here:

1.  While it's true that dask array caches keys, dask dataframe doesn't. It recomputes them each time.  

https://github.com/dask/dask/blob/67fb5363009c583c175cb577776a4f2f4e811410/dask/dataframe/core.py#L290-L291

2.  Also, while dask array uses the term `name` to point to the prefix of the key that it uses, dask dataframe doesn't.  This is because `.name` is also a common attribute for Series and DataFrame objects (imagine `df[df.name == "Alice"]`).  So instead dask dataframe uses the attribute `._name`.  

So, now I'm curious about what the underlying issue here was that this PR was intended to solve.

**Comment by madsbk** [comment]
> So, now I'm curious about what the underlying issue here was that this PR was intended to solve.

With this PR, I see a performance speedup. But I guess it is because some calculations were skipped?

**Comment by mrocklin** [comment]
Perhaps, yes.  This PR makes changes that would negatively affect correctness.

**Pull request closed without merging**
