### PR TITLE
Remove factorization logic from array auto chunking

### PR DESCRIPTION
**Pull request by jrbourbeau**
Closes https://github.com/dask/dask/issues/9488

cc @gjoseph92 @ian-r-rose

### CODE REVIEW

**Comment by jrbourbeau** [comment]
Ah, good check. Since we're not using `factors` here, and `dask` + `distributed` are tightly pinned to each other, I'll go ahead and push up a PR that adds `factors` to `distributed accordingly

**Comment by jrbourbeau** [comment]
xref https://github.com/dask/distributed/pull/7048

**Comment by jrbourbeau** [comment]
Alright CI is passing, I think this is ready for a review. Once folks are happy with this I'll roll back the temporary changes pointing CI to the companion `distributed` PR https://github.com/dask/distributed/pull/7048

**Review by ian-r-rose — APPROVED** [review]
Looks good to me, pending switching back to `distributed@main`.

I don't love how specific the tests are, but I don't think that's something we need to address here.

**Review by ian-r-rose — APPROVED** [review]

**Pull request merged**
