### PR TITLE
Enable/Fix test_select_partitioned_column for pyarrow 0.9.0

### PR DESCRIPTION
**Pull request by xhochy**
- [x] Tests added / passed
- [x] Passes `flake8 dask`
- [x] Fully documented, including `docs/source/changelog.rst` for all changes
      and one of the `docs/source/*-api.rst` files for new API

### CODE REVIEW

**Comment by xhochy** [comment]
Depends on https://github.com/apache/arrow/pull/1656

**Comment by martindurant** [comment]
+1 for the code, but the test appears to be skipped (as does the fastparquet variant?).

**Comment by xhochy** [comment]
@martindurant The skip for `pyarrow` is expected, 0.9.0 is not released. Once https://github.com/apache/arrow/pull/1656 is merged, I could see if we could change the `pyarrow` version check so that the nightlies are already included.

Fastparquet is skipped because it cannot be installed in the CI job (this should already be a failure?):

```
    gcc -pthread -B /home/travis/miniconda/envs/test-environment/compiler_compat -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/travis/miniconda/envs/test-environment/include/python3.5m -I/home/travis/miniconda/envs/test-environment/lib/python3.5/site-packages/numpy/core/include -c fastparquet/speedups.c -o build/temp.linux-x86_64-3.5/fastparquet/speedups.o
    gcc: error: fastparquet/speedups.c: No such file or directory
    gcc: fatal error: no input files
    compilation terminated.
    error: command 'gcc' failed with exit status 4
```

**Comment by mrocklin** [comment]
Thanks for continuing to track this @xhochy .  Merging.

**Pull request merged**
