### PR TITLE
base dask on fsspec

### PR DESCRIPTION
**Pull request by martindurant**
- [x] Tests added / passed
- [x] Passes `black dask` / `flake8 dask`

lots of red in the +/-!

### CODE REVIEW

**Comment by mrocklin** [comment]
Side thought: You should write about this.  The message might be something like "We (I) have invested a lot of time building out the bytes handling in Dask in a nicely modular way that can be helpful to others.  We found that, surprisingly, it was helpful to others.  This includes Intake, X, Y, and Z (zarr, rapids, ...?).  We've now moved the last bits from Dask so that you too can use these systems without depending on Dask explicitly (though of course it's a very lightweight dependency).

**Comment by martindurant** [comment]
@mrocklin : yep, eventually. I posted the code here more for backup and to show the dev group that this thing really would work.

**Comment by martindurant** [comment]
Merger here requires mergers on other repos and possibly releases; but all tests pass locally now.

**Comment by martindurant** [comment]
OK, so errors are due to two main things:
- s3fs not having been released with fsspec
- gzipfile et al being seekable with py37, but not giving "operation not supported" earlier

**Comment by mrocklin** [comment]
> Merger here requires mergers on other repos and possibly releases; but all tests pass locally now.

Woot!

**Comment by martindurant** [comment]
So it would be a good idea to make a decision now on read_* functions with compression. Should blocksize!=None be a straight exception? None of the compression engines support real random access normally (even if some can). Currently, random access is allowed and works on py37, but it is scanning through the file to find the right offset. That *could* be useful in some scenarios, but terrible in most.
If an early exception, I would probably put it in logical_size, since that's where the first scan would occur, to find the end of the uncompressed data.

**Comment by martindurant** [comment]
Just a single failure on https://travis-ci.org/dask/dask/jobs/557843869#L1002 around compression with chunksize; but quite a few windows path errors I'll need to do some work on.

**Comment by mrocklin** [comment]
> So it would be a good idea to make a decision now on read_* functions with compression. Should blocksize!=None be a straight exception? None of the compression engines support real random access normally (even if some can). Currently, random access is allowed and works on py37, but it is scanning through the file to find the right offset. That could be useful in some scenarios, but terrible in most.

When you say it like that, erring seems reasonable to me.  I haven't thought about this very deeply though.  cc'ing @jcrist who might have thoughts?

**Comment by jcrist** [comment]
For `read_csv` we already warn and then switch to using `blocksize=None`:

https://github.com/dask/dask/blob/3eb2dc89c9a70dcb828e86d043e23b751ab0d0fd/dask/dataframe/io/csv.py#L380-L387

Seems reasonable to me to convert this to an error everywhere.

**Comment by martindurant** [comment]
OK, actually passes Travis for py37 (linting not yet done).
Now back to windows paths...

**Comment by martindurant** [comment]
green on windows, only flake errors on py37 :)

**Comment by martindurant** [comment]
py37: passing (with s3fs from master)
py36: failing s3 only (s3fs from release)
py35: failing s3 (s3fs from release) and something in kwargs to compression

**Comment by martindurant** [comment]
Summary:
- I recommend merging this.

Outstanding:
- the test failure on appveyor is due to something with partd, which I'm pretty sure is unrelated
- the appveyor and py37 tests use master versions, which currently are the same as released versions. This can be reverted, but wanted to be sure that's the consensus.

**Comment by TomAugspurger** [comment]
> the test failure on appveyor is due to something with partd, which I'm pretty sure is unrelated

Most likely https://github.com/dask/dask/issues/5104

> the appveyor and py37 tests use master versions, which currently are the same as released versions. This can be reverted, but wanted to be sure that's the consensus.

Could they master versions be moved to the nightly upstream build? I've almost got that passing, just one remaining pandas failure that I'll try to fix today.

**Comment by martindurant** [comment]
> Could they master versions be moved to the nightly upstream build?

Sure, I'm ok with that - then for this PR, should go back to released versions only in all builds.

**Comment by rjzamora** [comment]
[PR#4995](https://github.com/dask/dask/pull/4995) now has these changes merged in, and all tests are passing.

**Comment by martindurant** [comment]
Will merge this evening, unless there are objections.

**Comment by jrbourbeau** [comment]
Woo! Thanks for all your work on this @martindurant :)

**Pull request merged**
