### PR TITLE
Allow non-memory ``zarr`` stores in ``to_zarr`` with ``distributed``

### LINKED ISSUE #10420: dask.array.core.to_zarr with distributed scheduler, MutableMapping should be ok if backed by disk
Hello dask array team!

Thanks for the amazing packages, they have enabled me to do some great science.

`dask.array.core.to_zarr` does not want to write to a memory-backed zarr array with the distributed scheduler. This of course makes sense and the [check for it is here.](https://github.com/dask/dask/blob/257d3784bd7e36695241451f06db223b0b5c0407/dask/array/core.py#L3664) However, some zarr arrays that are in fact backed by disk storage have stores that inherit from MutableMapping, [like the DirectoryStore](https://zarr.readthedocs.io/en/stable/api/storage.html#zarr.storage.DirectoryStore). So if you build your own zarr array backed by a DirectoryStore and you want to write a dask array to it with `to_zarr` on the distributed scheduler, you get told off even when what you're doing is ok. Seems like MutableMapping is not the right thing to check for here, it's not specific enough. What is a better type to check for to make sure we don't do parallel writes to memory, but allow parallel writes to on disk storage that inherits from MutableMapping?

MVCE
```python
from zarr.creation import open_array
from zarr.storage import DirectoryStore
import dask.array as da
import inspect
from dask.distributed import Client    # problem only with distributed scheduler

for parent in inspect.getmro(DirectoryStore): print(parent)    # note MutableMapping in the hierarchy

client = Client()

dstore = DirectoryStore('./derp.zarr')
zarr_on_disk = open_array(
    shape=(128, 128),
    chunks=(64, 64),
    dtype=int,
    store=dstore,
    mode='a',
)

darray = da.ones((128, 128), chunks=(64, 64), dtype=int)

da.to_zarr(
    darray,
    zarr_on_disk,
)

# Should get this runtime error:
# https://github.com/dask/dask/blob/257d3784bd7e36695241451f06db223b0b5c0407/dask/array/core.py#L3674
```

**Environment**:

(probably only the dask version matters here, but this bug is still in the latest on the main branch I think)
- Dask version: 2023.6.1
- distributed version: 2023.6.1
- zarr version: 2.13.3
- Python version: 3.10
- Operating System: Scientific Linux
- Install method (conda, pip, source): pip

### PR DESCRIPTION
**Pull request by GFleishman**
In `dask.array.core.to_zarr` I swapped the check for distributed scheduler + MutableMapping to distributed scheduler + zarr.storage.MemoryStore, which seems to be the only zarr.storage type that is backed by memory. Though I'm unsure about the [LMDB store](https://zarr.readthedocs.io/en/stable/api/storage.html#zarr.storage.LMDBStore).

I also removed the import of MutableMapping since this was the only place in all of `dask.array.core` to reference it.

- [x] Closes #10420 
- [x] Tests added / passed (but see comment below)
- [x] Passes `pre-commit run --all-files`

### CODE REVIEW

**Review by jrbourbeau — COMMENTED** [review]
Thanks @GFleishman! 

It looks like the code linter is unhappy -- could you run `pre-commit` to handle those? See https://docs.dask.org/en/stable/develop.html#code-formatting for more details

Also could you add a test to make sure we're covering this case (if we're not already)?

**Comment by GFleishman** [comment]
@jrbourbeau I think everything is actually working now. The code linter did its thing and I added tests for two new conditions:
(1) calling `to_zarr` with a zarr array initialized with a directory store (should work)
(2) calling `to_zarr` with a zarr array initialized with a memory store (should produce a RuntimeError)
The original case of calling `to_zarr` with a zarr array initialized with no store at all, which will default to a memory backed array, which is actually a `zarr.storage.KVStore` is covered by a test that was already there (right below the ones I added).

CI is still failing something, but if you look at the error log its not related to anything I added - something to do with dataframes. When I run my tests locally, they work fine. I.e.

```python
(bigstream) fleishmang@h07u01:confocal> ipython
Python 3.10.11 | packaged by conda-forge | (main, May 10 2023, 18:58:44) [GCC 11.3.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.8.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import dask.tests.test_distributed as tests
   ...: from distributed import Client
   ...: c = Client()
   ...: tests.test_zarr_distributed_with_explicit_directory_store(c)
   ...: tests.test_zarr_distributed_with_explicit_memory_store(c)

In [2]:
```

If I understand correctly, if either test were to fail then I would get an AssertionError or a RuntimeError.

**Comment by GFleishman** [comment]
Just checking on this PR. I'm currently under the impression that the changes are sufficient and tested but that CI has some kind of problem.

**Comment by aamster** [comment]
Following up on this. This bug prevents using to_zarr and passing in a zarr object as the destination with a local cluster? Can this please be merged in?

**Comment by mrocklin** [comment]
@quasiben maybe this is something your team can help resolve?

**Comment by GFleishman** [comment]
@mrocklin Just checking if there is anything else needed from me to help this out?

**Comment by mrocklin** [comment]
> @mrocklin Just checking if there is anything else needed from me to help this out?

Sorry for the long delay here.  I've updated your test slightly (adding a `importorskip("numpy")` and am merging.

Also @phofl it looks like there's a pandas nightly error (just some future warning that went away).

**Pull request merged**
