### PR TITLE
Test `exp` with CuPy arrays

### PR DESCRIPTION
**Pull request by jakirkham**
- [ ] Closes #xxxx
- [ ] Tests added / passed
- [ ] Passes `black dask` / `flake8 dask`

xref: https://github.com/dask/dask-image/issues/133#issuecomment-790842265

cc @GenevieveBuckley @pentschev

### CODE REVIEW

**Review by pentschev — APPROVED** [review]
Thanks @jakirkham ! 😄

**Review by jrbourbeau — COMMENTED** [review]
Just to confirm, does this test pass? (I don't have a GPU locally)

**Comment by jakirkham** [comment]
Yes here's the results from running this test on a DGX-1

<details>

```python
$ git log -n1
commit c6bbaf11273b843ef59e56fd7999344439a1b814 (HEAD)
Author: John Kirkham <jakirkham@gmail.com>
Date:   Thu Mar 4 11:00:20 2021 -0800

    Test `exp` with CuPy arrays
$ python -m pytest -k test_basic dask/array/tests/test_cupy.py 
============================= test session starts ==============================
platform linux -- Python 3.8.6, pytest-6.2.2, py-1.10.0, pluggy-0.13.1 -- /datasets/jkirkham/miniconda/envs/rapids17dev/bin/python
cachedir: .pytest_cache
rootdir: /datasets/jkirkham/devel/dask, configfile: setup.cfg
collected 182 items / 123 deselected / 59 selected                             

dask/array/tests/test_cupy.py::test_basic[<lambda>0] PASSED              [  1%]
dask/array/tests/test_cupy.py::test_basic[<lambda>1] PASSED              [  3%]
dask/array/tests/test_cupy.py::test_basic[<lambda>2] PASSED              [  5%]
dask/array/tests/test_cupy.py::test_basic[<lambda>3] PASSED              [  6%]
dask/array/tests/test_cupy.py::test_basic[<lambda>4] PASSED              [  8%]
dask/array/tests/test_cupy.py::test_basic[<lambda>5] PASSED              [ 10%]
dask/array/tests/test_cupy.py::test_basic[<lambda>6] PASSED              [ 11%]
dask/array/tests/test_cupy.py::test_basic[<lambda>7] PASSED              [ 13%]
dask/array/tests/test_cupy.py::test_basic[<lambda>8] PASSED              [ 15%]
dask/array/tests/test_cupy.py::test_basic[<lambda>9] PASSED              [ 16%]
dask/array/tests/test_cupy.py::test_basic[<lambda>10] PASSED             [ 18%]
dask/array/tests/test_cupy.py::test_basic[<lambda>11] PASSED             [ 20%]
dask/array/tests/test_cupy.py::test_basic[<lambda>12] PASSED             [ 22%]
dask/array/tests/test_cupy.py::test_basic[<lambda>13] PASSED             [ 23%]
dask/array/tests/test_cupy.py::test_basic[<lambda>14] PASSED             [ 25%]
dask/array/tests/test_cupy.py::test_basic[<lambda>15] PASSED             [ 27%]
dask/array/tests/test_cupy.py::test_basic[<lambda>16] PASSED             [ 28%]
dask/array/tests/test_cupy.py::test_basic[<lambda>17] PASSED             [ 30%]
dask/array/tests/test_cupy.py::test_basic[<lambda>18] PASSED             [ 32%]
dask/array/tests/test_cupy.py::test_basic[<lambda>19] PASSED             [ 33%]
dask/array/tests/test_cupy.py::test_basic[<lambda>20] PASSED             [ 35%]
dask/array/tests/test_cupy.py::test_basic[<lambda>21] PASSED             [ 37%]
dask/array/tests/test_cupy.py::test_basic[<lambda>22] XFAIL (cupy.do...) [ 38%]
dask/array/tests/test_cupy.py::test_basic[<lambda>23] XFAIL (cupy.do...) [ 40%]
dask/array/tests/test_cupy.py::test_basic[<lambda>24] XFAIL (cupy.do...) [ 42%]
dask/array/tests/test_cupy.py::test_basic[<lambda>25] PASSED             [ 44%]
dask/array/tests/test_cupy.py::test_basic[<lambda>26] PASSED             [ 45%]
dask/array/tests/test_cupy.py::test_basic[<lambda>27] PASSED             [ 47%]
dask/array/tests/test_cupy.py::test_basic[<lambda>28] PASSED             [ 49%]
dask/array/tests/test_cupy.py::test_basic[<lambda>29] PASSED             [ 50%]
dask/array/tests/test_cupy.py::test_basic[<lambda>30] PASSED             [ 52%]
dask/array/tests/test_cupy.py::test_basic[<lambda>31] PASSED             [ 54%]
dask/array/tests/test_cupy.py::test_basic[<lambda>32] PASSED             [ 55%]
dask/array/tests/test_cupy.py::test_basic[<lambda>33] PASSED             [ 57%]
dask/array/tests/test_cupy.py::test_basic[<lambda>34] PASSED             [ 59%]
dask/array/tests/test_cupy.py::test_basic[<lambda>35] PASSED             [ 61%]
dask/array/tests/test_cupy.py::test_basic[<lambda>36] PASSED             [ 62%]
dask/array/tests/test_cupy.py::test_basic[<lambda>37] PASSED             [ 64%]
dask/array/tests/test_cupy.py::test_basic[<lambda>38] PASSED             [ 66%]
dask/array/tests/test_cupy.py::test_basic[<lambda>39] PASSED             [ 67%]
dask/array/tests/test_cupy.py::test_basic[<lambda>40] PASSED             [ 69%]
dask/array/tests/test_cupy.py::test_basic[<lambda>41] PASSED             [ 71%]
dask/array/tests/test_cupy.py::test_basic[<lambda>42] PASSED             [ 72%]
dask/array/tests/test_cupy.py::test_basic[<lambda>43] PASSED             [ 74%]
dask/array/tests/test_cupy.py::test_basic[<lambda>44] PASSED             [ 76%]
dask/array/tests/test_cupy.py::test_basic[<lambda>45] PASSED             [ 77%]
dask/array/tests/test_cupy.py::test_basic[<lambda>46] PASSED             [ 79%]
dask/array/tests/test_cupy.py::test_basic[<lambda>47] PASSED             [ 81%]
dask/array/tests/test_cupy.py::test_basic[<lambda>48] PASSED             [ 83%]
dask/array/tests/test_cupy.py::test_basic[<lambda>49] PASSED             [ 84%]
dask/array/tests/test_cupy.py::test_basic[<lambda>50] PASSED             [ 86%]
dask/array/tests/test_cupy.py::test_basic[<lambda>51] PASSED             [ 88%]
dask/array/tests/test_cupy.py::test_basic[<lambda>52] PASSED             [ 89%]
dask/array/tests/test_cupy.py::test_basic[<lambda>53] PASSED             [ 91%]
dask/array/tests/test_cupy.py::test_basic[<lambda>54] PASSED             [ 93%]
dask/array/tests/test_cupy.py::test_basic[<lambda>55] PASSED             [ 94%]
dask/array/tests/test_cupy.py::test_basic[<lambda>56] PASSED             [ 96%]
dask/array/tests/test_cupy.py::test_basic[<lambda>57] PASSED             [ 98%]
dask/array/tests/test_cupy.py::test_basic[<lambda>58] PASSED             [100%]

============================= slowest 10 durations =============================
0.25s call     dask/array/tests/test_cupy.py::test_basic[<lambda>38]
0.06s call     dask/array/tests/test_cupy.py::test_basic[<lambda>19]
0.04s call     dask/array/tests/test_cupy.py::test_basic[<lambda>0]
0.03s call     dask/array/tests/test_cupy.py::test_basic[<lambda>57]
0.03s call     dask/array/tests/test_cupy.py::test_basic[<lambda>53]
0.03s call     dask/array/tests/test_cupy.py::test_basic[<lambda>20]
0.02s call     dask/array/tests/test_cupy.py::test_basic[<lambda>13]
0.02s call     dask/array/tests/test_cupy.py::test_basic[<lambda>54]
0.02s call     dask/array/tests/test_cupy.py::test_basic[<lambda>12]
0.02s call     dask/array/tests/test_cupy.py::test_basic[<lambda>21]
=========================== short test summary info ============================
XFAIL dask/array/tests/test_cupy.py::test_basic[<lambda>22]
  cupy.dot(numpy) fails
XFAIL dask/array/tests/test_cupy.py::test_basic[<lambda>23]
  cupy.dot(numpy) fails
XFAIL dask/array/tests/test_cupy.py::test_basic[<lambda>24]
  cupy.dot(numpy) fails
================ 56 passed, 123 deselected, 3 xfailed in 2.87s =================
```

</details>

**Review by jrbourbeau — APPROVED** [review]
Great, thanks @jakirkham!

**Comment by jakirkham** [comment]
Thanks James! 😄

**Pull request merged**
