### PR TITLE
Bug fix: Use a dtype that can support negation.

### PR DESCRIPTION
**Pull request by mikegraham**
Should address #1822

### CODE REVIEW

**Comment by mrocklin** [comment]
Can you think of a simple case that would have triggered this earlier that we can add as a test?

**Comment by mikegraham** [comment]
I was rushing to get out the door and wanted to post this commit to show you basically what was up. I wanted to get some tests in, too -- I want to check the coverage to make sure we go through each branch of the adjustment logic

**Comment by mrocklin** [comment]
OK, cool

**Comment by mrocklin** [comment]
I've added a test based on the `dd.demo` example in the issue.  Merging on passed tests.

**Pull request merged**
