### PR TITLE
`da.eye` fix for `chunks=-1`

### LINKED ISSUE #7852: Dask array `eye` key error
The following `da.eye` snippet 

```python
import dask.array as da
da.eye(10, chunks=-1).compute()
```

raises `KeyError: ('eye-c26fa66cf1d752e6525f23ca3762f597', 0, 0)`. I've not looked into this too deeply yet, but suspect we're not handling the `chunks=-1` case gracefully. 

<details>
<summary>Full traceback:</summary>

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-2-55dafe761500> in <module>
----> 1 da.eye(10, chunks=-1).compute()

~/projects/dask/dask/dask/base.py in compute(self, **kwargs)
    284         dask.base.compute
    285         """
--> 286         (result,) = compute(self, traverse=False, **kwargs)
    287         return result
    288

~/projects/dask/dask/dask/base.py in compute(*args, **kwargs)
    566         postcomputes.append(x.__dask_postcompute__())
    567
--> 568     results = schedule(dsk, keys, **kwargs)
    569     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    570

~/projects/dask/dask/dask/threaded.py in get(dsk, result, cache, num_workers, pool, **kwargs)
     77             pool = MultiprocessingPoolExecutor(pool)
     78
---> 79     results = get_async(
     80         pool.submit,
     81         pool._max_workers,

~/projects/dask/dask/dask/local.py in get_async(submit, num_workers, dsk, result, cache, get_id, rerun_exceptions_locally, pack_exception, raise_exception, callbacks, dumps, loads, chunksize, **kwargs)
    526                     finish(dsk, state, not succeeded)
    527
--> 528     return nested_get(result, state["cache"])
    529
    530

~/projects/dask/dask/dask/local.py in nested_get(ind, coll)
    306     """
    307     if isinstance(ind, list):
--> 308         return tuple([nested_get(i, coll) for i in ind])
    309     else:
    310         return coll[ind]

~/projects/dask/dask/dask/local.py in <listcomp>(.0)
    306     """
    307     if isinstance(ind, list):
--> 308         return tuple([nested_get(i, coll) for i in ind])
    309     else:
    310         return coll[ind]

~/projects/dask/dask/dask/local.py in nested_get(ind, coll)
    306     """
    307     if isinstance(ind, list):
--> 308         return tuple([nested_get(i, coll) for i in ind])
    309     else:
    310         return coll[ind]

~/projects/dask/dask/dask/local.py in <listcomp>(.0)
    306     """
    307     if isinstance(ind, list):
--> 308         return tuple([nested_get(i, coll) for i in ind])
    309     else:
    310         return coll[ind]

~/projects/dask/dask/dask/local.py in nested_get(ind, coll)
    306     """
    307     if isinstance(ind, list):
--> 308         return tuple([nested_get(i, coll) for i in ind])
    309     else:
    310         return coll[ind]

~/projects/dask/dask/dask/local.py in <listcomp>(.0)
    306     """
    307     if isinstance(ind, list):
--> 308         return tuple([nested_get(i, coll) for i in ind])
    309     else:
    310         return coll[ind]

~/projects/dask/dask/dask/local.py in nested_get(ind, coll)
    308         return tuple([nested_get(i, coll) for i in ind])
    309     else:
--> 310         return coll[ind]
    311
    312

KeyError: ('eye-c26fa66cf1d752e6525f23ca3762f597', 0, 0)
```

</details>

### PR DESCRIPTION
**Pull request by ncclementi**
- [x] Closes #7852
- [x] Tests added / passed
- [x] Passes `black dask` / `flake8 dask` / `isort dask`

Fixes bug in `da.eye` case of chunks=-1.

### CODE REVIEW

**Comment by mrocklin** [comment]
Nice minimal fix 👍

**Review by jrbourbeau — COMMENTED** [review]
Thanks @ncclementi! Overall this looks great. Passing user-provided `chunks` through `normalize_chunks` is definitely the way to go.

Fortunately `normalize_chunks` has some of the same chunksize calculation logic that we've implemented here in `da.eye`. So since we're now always calling `normalize_chunks`, we can remove some code from `da.eye` which is now unnecessary:

```diff
diff --git a/dask/array/creation.py b/dask/array/creation.py
index 2e8b0eab..87cc715b 100644
--- a/dask/array/creation.py
+++ b/dask/array/creation.py
@@ -544,18 +544,12 @@ def eye(N, chunks="auto", M=None, k=0, dtype=float):
     if not isinstance(chunks, (int, str)):
         raise ValueError("chunks must be an int or string")

-    chunks = normalize_chunks(chunks, shape=(N, M), dtype=dtype)
-    chunks = chunks[0][0]
+    vchunks, hchunks = normalize_chunks(chunks, shape=(N, M), dtype=dtype)
+    chunks = vchunks[0]
+
     token = tokenize(N, chunks, M, k, dtype)
     name_eye = "eye-" + token

-    vchunks = [chunks] * (N // chunks)
-    if N % chunks != 0:
-        vchunks.append(N % chunks)
-    hchunks = [chunks] * (M // chunks)
-    if M % chunks != 0:
-        hchunks.append(M % chunks)
-
     for i, vchunk in enumerate(vchunks):
         for j, hchunk in enumerate(hchunks):
             if (j - i - 1) * chunks <= k <= (j - i + 1) * chunks:
```

**Review by jrbourbeau — APPROVED** [review]
Thanks @ncclementi! Will merge after CI finishes up

**Comment by jrbourbeau** [comment]
Hmm there's an unrelated daily stock test failure (which I'm able to reproduce locally). Given that the error message says 

```
...
<h1 style="margin-top:20px;">Will be right back...</h1>\n      <p id="message-1">Thank you for your patience.</p>\n      <p id="message-2">Our engineers are working quickly to resolve the issue.</p>\n      </td>\n  </tr>\n  </tbody></table>\n  </body></html>'
```

I'll wait a bit and see if the test passes then

**Comment by jrbourbeau** [comment]
Just merged `main` which should resolve the unrelated CI failure

**Pull request merged**
