### PR TITLE
Fix formatting in random number generation docs

### PR DESCRIPTION
**Pull request by erayaslan**
trivial fix for formatting - highlight both BitGenerators and Generators in docs

- [x] Passes `pre-commit run --all-files`

### CODE REVIEW

**Comment by erayaslan** [comment]
cc @rjzamora  quick fix for formatting

**Review by phofl — APPROVED** [review]

**Comment by erayaslan** [comment]
> Mind putting them in a note section instead?

Done. Thanks for the comment

**Comment by erayaslan** [comment]
@jrbourbeau reminder for this quick fix in formatting. thanks

**Review by j-bennet — APPROVED** [review]
👍

**Pull request merged**
