### PR TITLE
Read whole files fix regardless of header for HTTP

### PR DESCRIPTION
**Pull request by martindurant**
cf https://github.com/pangeo-data/pangeo/pull/231

### CODE REVIEW

**Comment by mrocklin** [comment]
Are there tests or comments that would help ensure that these lines are not removed by well-meaning devs in the future?

**Comment by martindurant** [comment]
Comments, certainly - I can add those. Tests, not easy, since the python simple http server doesn't provide the header key at all.

**Comment by martindurant** [comment]
So it may be that the Content-Length in this case reflects the *compressed* size of the data (HTTP often compresses on-the-fly), but we can never deal directly with the compressed data, and the bytes= range when retrieving data does not refer to this size either. I actually don't know what to do about this, whether there's any absolute way to know the size of a URL's contents before fetching all the data.

**Comment by martindurant** [comment]
It seems this can be fixed by passing `headers={'Accept-Encoding': 'identity'}` in the call to HEAD.

**Pull request merged**
