### PR TITLE
ENH: dataframe.from_pandas ... accept npartitions or chunksize

### PR DESCRIPTION
**Pull request by thequackdaddy**
Hello,

In the project I'm building, I've found it much more convenient if I can make a constant dataframe of the same size and with the same shape as my `from_bcolz` data frame. (So the dataframe is just a column of zero's or one's or whatnot.) 

I wanted the divisions to be the same as well to make the processing easier.... and this was the easiest route to that.

Let me know your thoughts. 

Thanks.

### CODE REVIEW

**Comment by mrocklin** [comment]
+1 on the content.  This looks great!

Can I ask you to rebase in the whoopsie commit?  Or perhaps all into one for something of this size?

**Comment by thequackdaddy** [comment]
So this is where I confess I'm not too good with git. 

I think what you are suggesting is that I do the following

git checkout master
git fetch origin master
git checkout pd_dataframe_chunksize 
git rebase master

Is that right? I've screwed up git a lot.

**Comment by thequackdaddy** [comment]
Wait wait...

git checkout master
git fetch **upstream** master
git checkout pd_dataframe_chunksize 
git rebase master

**Comment by mrocklin** [comment]
Close.  I'm suggesting that you do the following:

```
git checkout master
git fetch upstream master
git checkout pd_dataframe_chunksize 
git rebase -i master
```

Then, change `pick` on the left to `squash` on the commits that should arguably have been written in the above commit.  In your case it will probably look like the following:

```
pick a0b0a3c ENH: Allow dataframe.from_pandas to accept chunksize or npartitions
squash 0d9913b DOC: Wrote a little more documentation
squash 5c6dcb7 DOC: Whoopsie...
```

Then you save/exit and rewrite the docstring.

Finally you force push back up to your fork on github.  As a warning, this is where you can lose information.

    git push -f origin pd_dataframe_chunksize

Alternatively, I can do all of this for you.  It's a decent thing to learn how to do though.

**Comment by thequackdaddy** [comment]
Yep I screwed it up.

Let me make a new pull request. I think I should have squashed the ones above this commit as well.

**Pull request closed without merging**
