### PR TITLE
Add test for map overlap ordering

### PR DESCRIPTION
**Pull request by mrocklin**
See https://github.com/dask/dask/issues/3554 

cc @jakirkham 

This doesn't resolve the issue in 2d though, and may be just a hack.  

- [x] Tests added / passed
- [x] Passes `flake8 dask`

### CODE REVIEW

**Comment by mrocklin** [comment]
cc also @TomAugspurger

**Comment by mrocklin** [comment]
Actually, as discussed in the original issue, this does seem to have a significant effect in 2d

**Comment by jakirkham** [comment]
Interesting, thanks for sharing Matt. Will give this a closer look.

Hmm...does it have negligible impact Tom or does it make things worse?

As you can imagine, we care about optimizing both of these cases as we do use both. :)

**Comment by TomAugspurger** [comment]
AFAICT, it has no effect on the other case.

**Comment by mrocklin** [comment]
From a first principles point of view, this will only improve things, however it may add to the cost of calling order.

**Comment by mrocklin** [comment]
OK, I tested the increased number of steps through order due to this change by looking at `test_gh_3055` and it's something around 5%, which I'm ok with.  Merging this.

**Pull request merged**
