### PR TITLE
Add more ufuncs

### PR DESCRIPTION
**Pull request by jakirkham**
Fixes https://github.com/dask/dask/issues/2311

Adds a bunch more ufuncs based on what was found scrounging around the NumPy documentation.

cc @mrocklin

### CODE REVIEW

**Comment by jakirkham** [comment]
AppVeyor had some sort of segfault, but I don't think it is related to anything here.

**Comment by jcrist** [comment]
Yeah, that segfault has come up before, it's a bug in the sparse package (filed here: https://github.com/mrocklin/sparse/issues/19)

Looks good to me, merging. Thanks @jakirkham!

**Comment by mrocklin** [comment]
Thank you @jakirkham !

**Comment by jakirkham** [comment]
Awesome, thanks guys.

**Pull request merged**
