### PR TITLE
Update tz for pandas 1.4.0

### LINKED ISSUE #8580: Failures with upcoming pandas 1.4 release
There are already some issues / PRs related to this (eg some upstream failures are also listed in ), but I thought it might be useful to have a dedicated issue about this.

Pandas released a 1.4.0rc0 last week, and probably will release a final 1.4.0 next week.

The upstream test build (eg https://github.com/dask/dask/runs/4823351165?check_suite_focus=true) shows several failures, falling into a few categories:

- Pandas will require a minimum version of sqlalchemy 1.4, which gives import errors in the sql test setup (*ImportError: Pandas requires version '1.4.0' or newer of 'sqlalchemy' (version '1.3.23' currently installed).*) https://github.com/dask/dask/pull/8158
- `DataFrame.append` is deprecated, and so the warnings are turned into errors. https://github.com/dask/dask/pull/8617
- Some timezone related failure with fastparquet (eg `test_roundtrip[fastparquet-df12-write_kwargs12-read_kwargs12]` is failing)
- `test_parquet.py::test_getitem_optimization` failures (*TypeError: Column name must be a string. Got column None of type NoneType*) -> this might also be related to the to_frame failure below https://github.com/dask/dask/pull/8554
- `dask/dataframe/tests/test_indexing.py::test_to_frame` (the result has a "NaN" column name instead of expected default of "0") https://github.com/dask/dask/pull/8554
- A set of groupby failures with cumulative methods (`test_cumulative`) https://github.com/dask/dask/pull/8554
- Some errors related to *FutureWarning: In a future version, DataFrame.mean(axis=None) will return a scalar mean over the entire DataFrame. To retain the old behavior, use 'frame.mean(axis=0)' or just 'frame.mean()'* (`test_groupby_column_and_index_apply`) https://github.com/dask/dask/pull/8555
- ufunc related failures (*ValueError: Metadata inference failed in `__array_wrap__`.*) caused by pandas removing `__array_wrap__`  -> this might already be covered by https://github.com/dask/dask/pull/8558 ?

### PR DESCRIPTION
**Pull request by martindurant**
- [ ] Closes #8580
- [ ] Tests added / passed
- [ ] Passes `pre-commit run --all-files`

Also requires https://github.com/dask/fastparquet/pull/738

### CODE REVIEW

**Comment by jrbourbeau** [comment]
Just pushed an empty commit to test against the `main` branch of `fastparquet` (given https://github.com/dask/fastparquet/pull/738 has been merged). Hope that's okay

**Comment by martindurant** [comment]
Yep. I thought that restarting the tests would have the same effect, but maybe not.

**Comment by martindurant** [comment]
This does *not* seem to be picking up fastparquet main in every run. Do I need to make a release? The (parquet) tests do all pass for me locally.

**Comment by jsignell** [comment]
Only the upstream test will pick up fastparquet from main. So yeah I think a release would be necessary to get the regular tests passing.

**Comment by martindurant** [comment]
OK; well upstream seems to be failing on *loads* of dataframe tests (from warnings?). They include some parquet, but I cannot tell if these are actually parquet failures or due to whatever broke elsewhere.

**Comment by jrbourbeau** [comment]
Comparing the failing test summary between the linux Python 3.9 build (which is using `pandas=1.4.0`) and the `upstream` build, the changes in this PR + the `fastparquet` fixes result in `dask/dataframe/io/tests/test_parquet.py::test_roundtrip[fastparquet*]` and `dask/dataframe/io/tests/test_parquet.py::test_timestamp96` passing. https://github.com/dask/dask/pull/8623 should address the other failures on `pandas=1.4.0`

**Comment by martindurant** [comment]
OK, so we merge and I'll release fastparquet? There are a couple of PRs waiting there that would be nice to get in first.

**Comment by jrbourbeau** [comment]
A `fastparquet` release would be great. Do you have a rough estimate on how long that might take? It would be good to have the Python 3.9 builds pass here, so if it will still be a bit before those other PRs can get in, then we might consider using the dev version of `fastparquet` in our 3.9 builds

**Comment by martindurant** [comment]
Coming... https://github.com/dask/fastparquet/pull/739

**Comment by jrbourbeau** [comment]
Woo 🎉

**Comment by jsignell** [comment]
Ok I am going to merge this and then we should be all green???? :)

**Comment by jsignell** [comment]
Thank you @martindurant for the quick turn around on this!

**Comment by martindurant** [comment]
Hope! Note that conda-forge did it's job, which is what matters here, but some pypi wheels didn't build. I'll track those down later.

**Comment by jrbourbeau** [comment]
Thanks @martindurant @jsignell!

**Pull request merged**
