### PR TITLE
Add failing test for dataframe.isin with distributed (#4974)

### PR DESCRIPTION
**Pull request by gsakkis**
Initial PR for #4974 - currently just a (failing) test case.

### CODE REVIEW

**Comment by TomAugspurger** [comment]
I think the next step may be to handle these view objects in https://github.com/dask/dask/blob/e0f9456eeeabcf8a80e526afee28f2705950a2ec/dask/delayed.py#L46.

**Comment by TomAugspurger** [comment]
@gsakkis do you intended to work on this more? Does the suggestion in https://github.com/dask/dask/pull/5009#issuecomment-506706723 make sense?

**Comment by gsakkis** [comment]
@TomAugspurger I opened the PR after @martindurant's [suggestion](https://github.com/dask/dask/issues/4974#issuecomment-505230376) to move the discussion to a separate issue so it doesn't get lost, I didn't plan (nor have the time atm) to work on a fix.

**Comment by TomAugspurger** [comment]
OK, I might close this then so that other contributors aren't put off by an open PR.

**Pull request closed without merging**
