### PR TITLE
read_sql_table - datetime index fix and  index type checking

### LINKED ISSUE #4289: Read_sql_table ufunc error
Whilst trying read_sql_table I get a somewhat obscure numpy error:

    
    import dask.dataframe as dd
    from dask.distributed import Client
    client = Client()
    connection_string = "mysql+pymysql://{user}:{password}@{host}:{port}/{database}".format(user=user, password=password, host=host, database=database, port=port)
    dd.read_sql_table(given_table_name, connection_string, index_col = 'idTx')

The error I am getting is the following:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-a060bf974152> in <module>()
----> 1 dd.read_sql_table('Logger_init', connection_string, index_col = 'idTx')

~/miniconda3/lib/python3.6/site-packages/dask/dataframe/io/sql.py in read_sql_table(table, uri, index_col, divisions, npartitions, limits, columns, bytes_per_chunk, head_rows, schema, meta, engine_kwargs, **kwargs)
    153             divisions[-1] = maxi
    154         else:
--> 155             divisions = np.linspace(mini, maxi, npartitions + 1).tolist()
    156 
    157     parts = []

~/miniconda3/lib/python3.6/site-packages/numpy/core/function_base.py in linspace(start, stop, num, endpoint, retstep, dtype)
    106     # Convert float/complex array scalars to float, gh-3504
    107     # and make sure one can use variables that have an __array_interface__, gh-6634
--> 108     start = asanyarray(start) * 1.0
    109     stop  = asanyarray(stop)  * 1.0
    110 

TypeError: ufunc 'multiply' did not contain a loop with signature matching types dtype('<U32') dtype('<U32') dtype('<U32')
```
I tried several index cols and got the same error. If I select a date column as index I get this different error:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-1a4e483e85a4> in <module>()
----> 1 dd.read_sql_table('Logger_init', connection_string, index_col = 'date')

```
~/miniconda3/lib/python3.6/site-packages/dask/dataframe/io/sql.py in read_sql_table(table, uri, index_col, divisions, npartitions, limits, columns, bytes_per_chunk, head_rows, schema, meta, engine_kwargs, **kwargs)
    149             divisions = pd.date_range(
    150                 start=mini, end=maxi, freq='%iS' % (
--> 151                     (maxi - mini) / npartitions).total_seconds()).tolist()
    152             divisions[0] = mini
    153             divisions[-1] = maxi

AttributeError: 'numpy.timedelta64' object has no attribute 'total_seconds'
```

### PR DESCRIPTION
**Pull request by jcorb**
Fixes #4289 

Also added a type check on the index column if `divisions is None`.  It will raise a `TypeError` if the index column's `dtype.kind` is not in `['i', 'u', 'f']` or equal to `M`

- [ ] Tests added / passed
- [ ] Passes `flake8 dask`

### CODE REVIEW

**Comment by martindurant** [comment]
Could you please add a test, in which a text column is chosen, and so it raises the exception?

**Comment by jcorb** [comment]
Yes, sure thing.  I presume it would sit in here `dask/dask/dataframe/io/tests/test_sql.py`?

**Comment by martindurant** [comment]
Yes exactly

**Comment by jcorb** [comment]
apologies for the delay -  I have added a test which sets the index column to be a character column and checks for the TypeError exception.  

(first time I have written that sort of test, so I just mimicked what was in there already -  hopefully it is along the right lines)

**Comment by martindurant** [comment]
Looks good, except lint:
```
dask/dataframe/io/tests/test_sql.py:266:84: W292 no newline at end of file
```

**Comment by jcorb** [comment]
Ah, missed that step - should be good now.

**Comment by martindurant** [comment]
Thank you.

**Pull request merged**
