### PR TITLE
Fix test_describe_empty to work without global -Werror

### PR DESCRIPTION
**Pull request by mgorny**
Fix test_describe_empty to work when the test suite is run without
global -Werror.  This is e.g. desirable for packagers who don't want
the test suite for a fixed version to suddenly start failing due to
DeprecationWarnings in dependencies that otherwise don't break
the package.

Since the test expects either a ValueError or a RuntimeWarning, it seems
that the easiest way to assert for that is to inject the "error" filter
for the scope of the call.

- [ ] Closes #xxxx
- [x] Tests added / passed
- [x] Passes `pre-commit run --all-files`

### CODE REVIEW

**Review by jrbourbeau — COMMENTED** [review]
Thanks @mgorny, apologies for the delayed reply. There are some unrelated CI failures which have been resolved in `main` already. If you merge `main` into this branch, those failures should go away. What deprecation warning is this for? I'm slightly confused about what the goal of this change is

**Comment by mgorny** [comment]
Let's put it like this: we're running tests for all Gentoo packages with `-Wdefault` since `-Werror` has caused a lot of pain in the past. This ensures that the test suite works with either setting.

**Comment by mgorny** [comment]
Ping.

**Comment by jsignell** [comment]
Sorry this slipped through the cracks here @mgorny I prefer to just split the check into a test of the error and a test of the warning. I will just push a commit to make that change and then this will be good to go.

**Pull request merged**
