### PR TITLE
Consolidate array Dispatch objects

### PR DESCRIPTION
**Pull request by jrbourbeau**
This PR consolidates `Dispatch` objects used throughout `dask.array`, and their corresponding registrations, into `dask/array/backends.py`. This goes along with https://github.com/dask/dask/pull/7503, which does the same thing for `dask.dataframe`. 

xref https://github.com/dask/dask/issues/7502

cc @jsignell @jakirkham @kkraus14

### CODE REVIEW

**Comment by jakirkham** [comment]
Should we extend codeowners here as well?

cc @pentschev @quasiben (for awareness)

**Comment by jsignell** [comment]
> Should we extend codeowners here as well?

I think I have a lableling solution that will actually work better given the restriction described here: https://github.com/dask/dask/pull/7503#discussion_r605839417

**Review by jsignell — COMMENTED** [review]
I think I prefer to have the dispatch objects all in one file separate form any of the registrations and with no imports. That way the registrations can import them all from dispatch and then the registrations don't get imported anywhere, so it makes for clean dependencies. And we can safely import from dispatch in all the places where we explicitly use the dispatch objects.

**Comment by jsignell** [comment]
https://github.com/dask/dask/pull/7506

**Comment by jsignell** [comment]
We should hold off merging either of these until we get a chance to talk things through thoroughly with the dask-cudf folks.

**Comment by jrbourbeau** [comment]
Yep, agreed let's hold off for right now. FWIW I think the changes here are backwards compatible.

**Comment by pentschev** [comment]
Looks fine to me, also ran CuPy tests locally and they pass as well!

**Comment by jakirkham** [comment]
Just noting this is still of interest, know everyone is busy with the Summit this week, but it would be good to figure out next steps here (maybe next week?). In particular Julia mentioned this PR might need some updating ( https://github.com/dask/dask/pull/7503#issuecomment-839022250 ).

**Comment by jsignell** [comment]
Yeah good ping @jakirkham. The remaining work is just to make the file structure in this PR match the other one, so separate out backends and dispatch into their own files.

**Comment by jrbourbeau** [comment]
Yeah, thanks for the ping @jakirkham. I just pushed a commit which updates the file structure here to match what @jsignell did over in https://github.com/dask/dask/pull/7503

**Review by jsignell — APPROVED** [review]
Looks good!

**Comment by jrbourbeau** [comment]
Thanks for testing @pentschev and reviewing @jakirkham @jsignell

**Pull request merged**
