### PR TITLE
CI: use nightly wheel to install pyarrow in upstream test build

### LINKED ISSUE #9449: `upstream` CI build failing to install nightly `pyarrow`
@ncclementi observed that our `upstream` CI build isn't able to install the nightly version of `pyarrow` due to a solve conflict. From the [latest `upstream` build logs](https://github.com/dask/dask/runs/8101427556?check_suite_focus=true):

```
Run source continuous_integration/scripts/install.sh
++ [[ -n 1 ]]
++ arr=($(mamba search --override-channels -c arrow-nightlies pyarrow | tail -n 1))
+++ mamba search --override-channels -c arrow-nightlies pyarrow
+++ tail -n 1
++ export PYARROW_VERSION=10.0.0.dev137
++ PYARROW_VERSION=10.0.0.dev137
++ mamba install -y -c arrow-nightlies pyarrow=10.0.0.dev137
conda-forge/linux-64                                        Using cache
conda-forge/noarch                                          Using cache

Looking for: ['pyarrow=10.0.0.dev137']


Pinned packages:
  - python 3.9.*


Encountered problems while solving:
  - package pyarrow-10.0.0.dev137-py39h1ed2e5d_0_cuda requires arrow-cpp 10.0.0.dev137 py39h3962255_0_cuda, but none of the providers can be installed
```

It's interesting that the `cuda` version (and not the `cpu` version) of `pyarrow` is trying to be installed. Not sure how relevant that is to the solve issue...

cc @jorisvandenbossche in case you have any thoughts

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
Attempt to close #9449

### CODE REVIEW

**Review by jrbourbeau — COMMENTED** [review]
Nice! I hadn't realized there were nightly wheels, thanks for pointing that out @jorisvandenbossche. It looks like the nightly version of `pyarrow` is getting installed correctly (currently `pyarrow=11.0.0.dev517` is installed).

Could you move these lines

https://github.com/dask/dask/blob/2a2b9d3cb503c052fd65e5693575498df1f9cd23/continuous_integration/scripts/install.sh#L19-L28

where we were installing from the nightly conda channel? 

Also, we have a test for packages installed in the `upstream` build. We should be able to uncomment `pyarrow` here now 

https://github.com/dask/dask/blob/2a2b9d3cb503c052fd65e5693575498df1f9cd23/dask/tests/test_ci.py#L29

**Comment by jorisvandenbossche** [comment]
> Could you move these lines .. where we were installing from the nightly conda channel?

Do you prefer those comments? Or could also remove it?

**Review by jrbourbeau — APPROVED** [review]
Thanks @jorisvandenbossche!

**Comment by jorisvandenbossche** [comment]
Thanks for finishing it up! (totally forgot about it)

**Pull request merged**
