### PR TITLE
Do not compare x.dim with None in array.

### PR DESCRIPTION
**Pull request by rainwoodman**
I suspect this is the cause of failure in Python 3 at

https://travis-ci.org/bccp/nbodykit/jobs/183846633#L570

### CODE REVIEW

**Comment by mrocklin** [comment]
The test failure is unrelated.  

Can you add a small test that would have failed prior to this fix?

**Comment by nickhand** [comment]
I think this is a mis-use of the intended API but we are getting the error when doing on python 3: 

```python
import dask.array as da
x = da.ones((100,3), chunks=10)
y = da.array(x)
```
I think we should be using `from_array` here

**Comment by mrocklin** [comment]
Indeed, from_array is the general way to convert from numpy arrays to dask arrays

**Comment by rainwoodman** [comment]
Well, I am looking for a function that ensures the result is a dask array. If the input is already dask array it shall not do anything. from_array seems to require rechunking -- is it expensive?

**Comment by mrocklin** [comment]
Perhaps an isinstance check would help to resolve this problem?

**Comment by rainwoodman** [comment]
Yes. It would work.

What do you think of Nick's solution with a duck check?

https://github.com/bccp/nbodykit/pull/275/commits/1da39112f6dc7a063490e87b30fc3de8ec78af43

**Comment by shoyer** [comment]
> Well, I am looking for a function that ensures the result is a dask array. If the input is already dask array it shall not do anything. from_array seems to require rechunking -- is it expensive?

`dask.array.core.asarray` does this. Perhaps we should expose it as public API.

Arguably, `da.array` should do coercion like `asarray`, as well.

**Comment by mrocklin** [comment]
Checking in here (sorry for my long absence).  What is the decision here, would exposing `asarray` to the public API suffice?

**Comment by rainwoodman** [comment]
As least da.array shall not fail on Python 3 when ndim is the default value None. This patch fixes that.

I think a write up that demonstrates the differences of three similar functions ```asarray``` ```array``` and ```fromarray``` in the docstring could be very useful.

**Comment by mrocklin** [comment]
@rainwoodman are you able to add a small regression test here?  I think that that is all that is necessary for this PR.

**Comment by rainwoodman** [comment]
Sure. I added a regression case in test_base.py

**Comment by QuLogic** [comment]
You appear to have flake8 errors.

**Comment by rainwoodman** [comment]
It's green now.

**Comment by mrocklin** [comment]
Sorry for the exceedingly long delay here @rainwoodman .  Thank you for following through with this.

**Pull request merged**
