### PR TITLE
Fix dimension chunking in indices

### PR DESCRIPTION
**Pull request by sjperkins**
chunk nesting for each dimension was incorrectly specified.

- [x] Tests added / passed
- [x] Passes `flake8 dask`
- [x] Fully documented, including `docs/source/changelog.rst` for all changes
      and one of the `docs/source/*-api.rst` files for new API

### CODE REVIEW

**Comment by sjperkins** [comment]
Fixes #3166

**Comment by mrocklin** [comment]
Looks good to me.  Merging.  Thanks for the excellent fix and test @sjperkins !

**Comment by jakirkham** [comment]
Thanks @sjperkins. :)

**Comment by sjperkins** [comment]
@jakirkham my pleasure. :grinning:

**Pull request merged**
