### PR TITLE
Remove compatibility entries for old distributed.

### PR DESCRIPTION
**Pull request by QuLogic**
setup.py lists distributed as 2021.06.0, which is far above the
2.something in these comments.

- [ ] Closes #xxxx
- [ ] Tests added / passed
- [x] Passes `black dask` / `flake8 dask` / `isort dask`

### CODE REVIEW

**Comment by QuLogic** [comment]
Hmm, looks like that version in the comment is not correct.

**Comment by jsignell** [comment]
Thank you for opening this! There is also one place in the dask/array/routines.py where apply is imported from compatibility.py. So that import should also be changed in this PR and then this can wait until dask depends on the version of distributed that has https://github.com/dask/distributed/pull/4913 in it.

**Review by jrbourbeau — COMMENTED** [review]
Thanks @QuLogic. I just pushed a commit which should resolve the test import errors

**Review by jrbourbeau — APPROVED** [review]
Thanks for cleaning this up @QuLogic! This is in

**Pull request merged**
