### PR TITLE
Added some extra test coverage

### PR DESCRIPTION
**Pull request by lrjball**
- [x] Tests added / passed
- [x] Passes `pre-commit run --all-files`

This is my first contribution to dask so thought I'd add some test coverage while I familiarize myself with the repo. I've added a test for an option to `sort_values` that wasn't previously tested, as well as a few other tests for lines in `numeric.py` and `shuffle.py` that weren't tested.

### CODE REVIEW

**Comment by scharlottej13** [comment]
@lrjball thanks for your patience on this PR! Would you mind resolving the merge conflicts and merging `main`?

**Comment by jsignell** [comment]
Or if you prefer one of us can do the rebase. Sorry this totally slipped through the cracks :(

**Comment by lrjball** [comment]
No worries, I have resolved the merge conflict now

**Comment by jsignell** [comment]
ok to test

**Comment by jsignell** [comment]
Thanks @lrjball for opening this PR and congrats on your first contribution to dask!

**Pull request merged**
