### PR TITLE
[WIP] Add read_avro to dask.dataframe

### PR DESCRIPTION
**Pull request by rjzamora**
There has been [interest](https://github.com/rapidsai/cudf/issues/6496) by users of dask-cudf to have Avro support in Dask.  This PR includes a simple `read_avro` implementation, using the [fastavro](https://fastavro.readthedocs.io/en/latest/) library.

@dask/io - This design allows the output partitioning to be comprised of groups of avro "blocks" or entire files.  Please do feel free to advise, or to ping people who may have real-world avro knowledge.  I am personally new to the format, and it is not clear to be if there are beter library and/or decompositions methods I should focus on.

@albert17 - I have confirmed that this design works with the cudf avro reader as well (you just need to define your own engine that overrides the `FastAvroEngine.read_partition` logic to use cudf).

- [ ] Tests added / passed
- [ ] Passes `black dask` / `flake8 dask`

### CODE REVIEW

**Comment by martindurant** [comment]
Quick reference to what might be similar code (I haven't looked yet): https://github.com/intake/intake-avro/blob/master/intake_avro/source.py

Note that `uavro` is much much faster than `fastavro`, for the case that the schema is strictly tabular - no nesting. I imagine that CUDF people would be more interested in something like that. I would also not be surprised if avro->arrow exists somewhere ( https://github.com/apache/arrow/pull/1026 attempted it)

**Comment by rjzamora** [comment]
Thanks @martindurant !  It looks like I should definitely add a `uavro` engine, and the intake code is a good reference.

**Comment by rjzamora** [comment]
> Thanks @martindurant ! It looks like I should definitely add a uavro engine, and the intake code is a good reference.

I can confirm that `uavro` is indeed **much** faster than `fastavro`

**Comment by mrocklin** [comment]
I'm glad to see this.  I'm curious @rjzamora , is there more work to be done here?

Also, it would be good to add references to read_avro in the create dataframes doc page and the dataframes api

**Comment by rjzamora** [comment]
> I'm glad to see this. I'm curious @rjzamora , is there more work to be done here?

If people think the overall approach here is reasonable, then I would expect the remaining work to be minor cleanup and addressing code review.  It would be nice to have avro support in pyarrow, and/or to not require fastavro to write files for testing, but the current inclusion of both fastavro and uavro engines seems okay for now. 

> Also, it would be good to add references to read_avro in the create dataframes doc page and the dataframes api

Sounds good.

**Comment by martindurant** [comment]
It would be extremely doable, these days, to create a set of pyarrow buffers from the known avro schema (very similar to however this must be done for parquet) and fill them, all in numba. Foe someone with the time, and interest in nested data... You could do worse than ask the people at awkward1 to see if they have an interest in supporting avro.

For now, yes I would say that some support is much better than none, and even fastavro alone might be enough for those that need it.

**Comment by beckernick** [comment]
I see from the linked cuDF issue that https://github.com/NVIDIA/NVTabular/pull/369 implemented a separate reader.

@rjzamora is this still a relevant PR? In general, I think supporting Avro would be a nice addition.

**Comment by rjzamora** [comment]
>@rjzamora is this still a relevant PR? In general, I think supporting Avro would be a nice addition.

I'd say it is still relevant.  This particular PR only lost steam because the need for both uavro and fastavro felt a bit messy, and the only vocal "stakeholder" at the time was NVTabular.  The "temporary" solution within nvtabular is pretty much a copy of this PR.

**Pull request closed without merging**
