### PR TITLE
Add meshgrid

### PR DESCRIPTION
**Pull request by jakirkham**
Fixes https://github.com/dask/dask/issues/2057

Implements `meshgrid` for Dask Arrays. Supports all keyword arguments (except `copy`). Tests the implementation against NumPy's. Adds `meshgrid` to Dask Array's public API and documents it. Includes a changelog entry for the addition. Also rewrites `indices` to use `meshgrid` internally (simplifying the code).

### CODE REVIEW

**Comment by mrocklin** [comment]
This looks great to me

**Comment by jakirkham** [comment]
Thanks @mrocklin.

Pretty happy that this basically fell out of the `indices` code. The only trick part was the `ij` vs `xy` bit. I think we can get `mgrid` and `ogrid` pretty easily too with some minor additions, but we can save that for later. ( https://github.com/dask/dask/issues/2939 )

**Comment by mrocklin** [comment]
Lets merge this tomorrow morning if no one else comes up with any comments

**Comment by mrocklin** [comment]
Thanks @jakirkham !

**Pull request merged**
