### PR TITLE
test-upstream

### PR DESCRIPTION
**Pull request by TomAugspurger**

### CODE REVIEW

**Comment by TomAugspurger** [comment]
@martindurant the following test has changed between fsspec 0.4.1 and master

```
$  pytest dask/bytes/tests/test_http.py::test_errors
```

```pytb
================================================================================================================ FAILURES =================================================================================================================
_______________________________________________________________________________________________________________ test_errors _______________________________________________________________________________________________________________

dir_server = '/var/folders/hz/f43khqfn7b1b1g8z_z6y3bsw0000gp/T/tmp5_o8megr'

    def test_errors(dir_server):
        f = open_files("http://localhost:8999/doesnotexist")[0]
        with pytest.raises(requests.exceptions.RequestException):
            with f as f:
                f.read()
        f = open_files("http://nohost/")[0]
        with pytest.raises(requests.exceptions.RequestException):
>           with f as f:

dask/bytes/tests/test_http.py:123:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../miniconda3/envs/dask-upstream-dev/lib/python3.7/site-packages/fsspec/core.py:65: in __enter__
    f = self.fs.open(self.path, mode=mode)
../../miniconda3/envs/dask-upstream-dev/lib/python3.7/site-packages/fsspec/spec.py:684: in open
    autocommit=ac, **kwargs)
../../miniconda3/envs/dask-upstream-dev/lib/python3.7/site-packages/fsspec/implementations/http.py:133: in _open
    return HTTPFile(self, url, self.session, block_size, **kw)
../../miniconda3/envs/dask-upstream-dev/lib/python3.7/site-packages/fsspec/implementations/http.py:204: in __init__
    cache_type=cache_type, **kwargs)
../../miniconda3/envs/dask-upstream-dev/lib/python3.7/site-packages/fsspec/spec.py:879: in __init__
    self.details = fs.info(path)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <fsspec.implementations.http.HTTPFileSystem object at 0x1141600b8>, url = 'http://nohost/', kwargs = {}, size = False, policy = 'get'

    def info(self, url, **kwargs):
        """Get info of URL

        Tries to access location via HEAD, and then GET methods, but does
        not fetch the data.

        It is possible that the server does not supply any size information, in
        which case size will be given as None (and certain operations on the
        corresponding file will not work).
        """
        size = False
        for policy in ['head', 'get']:
            try:
                size = file_size(url, self.session, policy, **self.kwargs)
                if size is not None:
                    break
            except Exception:
                pass
        else:
            # get failed, so conclude URL does not exist
            if size is False:
>               raise FileNotFoundError(url)
E               FileNotFoundError: http://nohost/

../../miniconda3/envs/dask-upstream-dev/lib/python3.7/site-packages/fsspec/implementations/http.py:166: FileNotFoundError
```

Is that a deliberate change (possibly from https://github.com/intake/filesystem_spec/pull/93)? Will we need to use fsspec's http server for this test?

**Comment by TomAugspurger** [comment]
Err sorry, I should look more closely at the test. We should just expect a FileNotFoundError, right?

**Comment by martindurant** [comment]
FileNotFound is, I think, the right thing to expect here

**Comment by TomAugspurger** [comment]
OK, I think the next failure looks more real.

```
$ pytest dask/bytes/tests/test_s3.py::test_compression[bz2-None] 
```

It seems like `read_bytes('s3://foo/*', compression='bz2', blocksize=None)` ends up trying to pass a local file path named `'s3://foo/...'` to `bs2.Bz2File`, which fails.

**Comment by TomAugspurger** [comment]
https://github.com/intake/filesystem_spec/issues/104 for the orc failure.

**Comment by TomAugspurger** [comment]
Ah, it turns out the `test_s3.py::test_compression` is failing due to https://github.com/intake/filesystem_spec/issues/104 as well.

**Comment by TomAugspurger** [comment]
@mrocklin https://github.com/dask/dask/pull/5267/commits/8a732aefe4c29b7e9ce1e132de2e5f381534f185 fixes some upstream failures from distributed's stricter(?) checking of lingering threads / processes like

```pytb
dask/tests/test_distributed.py:61: 
1685_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
1686../../../miniconda/envs/test-environment/lib/python3.7/contextlib.py:119: in __exit__
1687    next(self.gen)
1688../../../miniconda/envs/test-environment/lib/python3.7/site-packages/distributed/utils_test.py:721: in cluster
1689    client.close()
1690../../../miniconda/envs/test-environment/lib/python3.7/contextlib.py:119: in __exit__
1691    next(self.gen)
1692../../../miniconda/envs/test-environment/lib/python3.7/site-packages/distributed/utils_test.py:1544: in clean
1693    del thread_state.on_event_loop_thread
1694../../../miniconda/envs/test-environment/lib/python3.7/contextlib.py:119: in __exit__
1695    next(self.gen)
1696_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
1697
1698check = True
1699
1700    @contextmanager
1701    def check_process_leak(check=True):
1702        for proc in mp_context.active_children():
1703            proc.terminate()
1704    
1705        yield
1706    
1707        if check:
1708            for i in range(100):
1709                if not set(mp_context.active_children()):
1710                    break
1711                else:
1712                    sleep(0.2)
1713            else:
1714>               assert not mp_context.active_children()
1715E               assert not [<SpawnProcess(SpawnPoolWorker-68, started daemon)>, <SpawnProcess(SpawnPoolWorker-70, started daemon)>, <SpawnProcess... daemon)>, <SpawnProcess(SpawnPoolWorker-69, started daemon)>, <SpawnProcess(SpawnPoolWorker-71, started daemon)>, ...]
1716E                +  where [<SpawnProcess(SpawnPoolWorker-68, started daemon)>, <SpawnProcess(SpawnPoolWorker-70, started daemon)>, <SpawnProcess... daemon)>, <SpawnProcess(SpawnPoolWorker-69, started daemon)>, <SpawnProcess(SpawnPoolWorker-71, started daemon)>, ...] = <function active_children at 0x7fd9935bdbf8>()
1717E                +    where <function active_children at 0x7fd9935bdbf8> = <multiprocessing.context.ForkServerContext object at 0x7fd993546da0>.active_children
1718
1719../../../miniconda/envs/test-environment/lib/python3.7/site-packages/distributed/utils_test.py:1463: AssertionError
1720
```

The failing tests weren't the ones that needed updating though. It was the pool from a different test that needed closing, which made debugging difficult. Do you think it's possible for `check_process_leak` to only check for *new* processes / threads? Or is that hopeless?

**Comment by jakirkham** [comment]
@mrocklin, any thoughts on Tom's question above?

**Comment by mrocklin** [comment]
> Do you think it's possible for check_process_leak to only check for new processes 

Currently we close all processes when entering the context manager.  We assume that people are using the `mp_context` from within utils.py

We don't do this for threads, but I'm not sure that we can.

**Comment by TomAugspurger** [comment]
FYI: there's still one upstream dev failure I need to debug: https://travis-ci.org/dask/dask/jobs/571906205#L1208

**Comment by TomAugspurger** [comment]
All passing now.

**Comment by jrbourbeau** [comment]
Thanks for handling this @TomAugspurger. Merging

**Pull request merged**
