### PR TITLE
Inline fast functions before optimize slices in dask.array

### PR DESCRIPTION
**Pull request by mrocklin**
@shoyer switching around these two optimizations seems like a good idea to me.  However, if this raises any corner cases for you in XArray please let me know.

### CODE REVIEW

**Comment by mrocklin** [comment]
Merging this later today if there are no further comments

**Comment by shoyer** [comment]
@mrocklin can you give a concrete example of what this means and why this change seems like a good idea to you?

**Comment by mrocklin** [comment]
Generally `optimize_slices` helps when you have multiple getitem calls stacked in one compound task.  It is what turns `x[:10][5::2]` into `x[5:10:2]`.  

Inline_functions fuses operations that we consider "fast" enough to recompute.  Operations like transpose or getitem.  Generally it helps to make compound tasks like what `optimize_slices` consumes.  

Generally I think it's a good idea to do the inline optimization (make compound tasks) before doing optimize_slices (consumes compound getitem tasks).

I think that this would come up if we had an array-like object that had only a single very large chunk and then added it to another array that was more finely chunked.

```python
x = da.from_array(d, chunks=d.shape)
y = da.ones(d.shape, chunks=1000)
z = x + y
```

This would help to create compound getitem tasks that looked like `x[...][:1000, :1000]` and would rewrite these into `x[:1000, :1000]`

**Comment by mrocklin** [comment]
OK, this PR has become mostly a fixup after recent optimization things.  The test here ensures that dask-thing + non-dask-thing chunks things properly.  By properly I mean the following:

1.  Non-dask-thing is a raw value in the graph.  It is not included in other tasks of the graph.  This aids serialization.
2.  The non-dask-thing is sliced exactly once per dask-thing chunk.  It does not get sliced poorly and then resliced well.  Slice fusion works 
3.  These slices are not then fused into other tasks, they remain bare so that they can move around the network before engaging in other possibly-costly computations.

To accomplish this I had to add a new getarray function, `getarray_inline`, which is used by `asarray`, which we should probably start using as the default way to consume array-likes.  We should not use `from_array`, which no longer fuses nicely with others.  @shoyer, this may affect xarray.  

So to be clear, if you have an array-like that you want to interact with a dask.array 

    atop(..., my_dask_array, ..., my_non_dask_array, ...)

Then you should leave `my_non_dask_array` as is, and not call `da.from_array` on it (TODO, update docs).

**Comment by mrocklin** [comment]
Merging this soon if there are no further comments.

**Comment by shoyer** [comment]
OK, this seems reasonable to me. I will have to double check, but I don't think we currently do any automatic conversion to dask arrays.

**Comment by shoyer** [comment]
(To be clear, I haven't had time to look at the code here yet, just @mrocklin's high level description.)

**Comment by mrocklin** [comment]
Yeah, I *think* that things will probably be ok, but the complexity here is starting to grow, so I wouldn't be surprised if some performance issues crop up after releases and users have a chance to hammer at it.  

The changes here are substantial from a distributed computing point of view though.  Avoiding communication adds another set of constraints onto the slicing problem that will make life interesting for a bit.  

I'm going to merge this.

**Pull request merged**
