### PR TITLE
Merge global annotations when packing

### PR DESCRIPTION
**Pull request by madsbk**
This PR depend on https://github.com/dask/distributed/pull/4691 and closes  https://github.com/dask/dask/pull/7542

- [ ] Tests added / passed
- [ ] Passes `black dask` / `flake8 dask` / `isort dask`

### CODE REVIEW

**Comment by madsbk** [comment]
@jrbourbeau Can I get you to make the CI test use https://github.com/dask/distributed/pull/4691?

**Comment by jrbourbeau** [comment]
Just pointed CI to https://github.com/dask/distributed/pull/4691 (and vice versa)

**Review by jrbourbeau — APPROVED** [review]
Thanks @madsbk! Apologies for the delay in getting this merged

Note that merging in https://github.com/dask/distributed/pull/4691 along with this PR will cause tests to pass

**Comment by madsbk** [comment]
Thanks @jrbourbeau !

**Pull request merged**
