### PR TITLE
add dask.array.append

### PR DESCRIPTION
**Pull request by D-Stacks**
- [x] Tests added / passed
- [x] Passes `black dask` / `flake8 dask`

### CODE REVIEW

**Review by crusaderky — CHANGES_REQUESTED** [review]
Could you implement and test NEP18 support? One should be able to just call ``numpy.append`` and, as long as the leftmost argument is a dask array, the call should be automatically routed to ``da.append``.

**Review by jrbourbeau — COMMENTED** [review]
@D-Stacks we test [NEP-18](https://numpy.org/neps/nep-0018-array-function-protocol.html) functionality over in `dask/array/tests/test_array_function.py`. Specifically, you can ensure `np.append` dispatches to `da.append` by adding a new `pytest.mark.parametrize` entry here

https://github.com/dask/dask/blob/d0ecbeafc03ce1a49fb613441bca6acd2941f9a3/dask/array/tests/test_array_function.py#L15-L45

**Review by jrbourbeau — COMMENTED** [review]
Thanks for the updates @D-Stacks!

Apologies I should have mentioned this earlier, but since this adds a new top-level `dask.array` method, could you add a new entry to the Dask Array API docs at `docs/source/array-api.rst`? Other than that this PR looks good to me

**Comment by D-Stacks** [comment]
No problem, it's quick to add.

**Review by jrbourbeau — APPROVED** [review]
Thanks @D-Stacks! This is in

**Pull request merged**
