### PR TITLE
Enhance Reshape

### LINKED ISSUE #2081: dask.array.reshape should allow rechunking when existing chunks have size 1
This came up in pydata/xarray#1026

Currently, this raises an error as scenario where we can't do the rechunking efficiently, but we could actually handle these reshape operations efficiently -- this is a case we missed in #1469:
```
In [11]: x = da.ones((2, 3), chunks=1)

In [12]: x.reshape(-1)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-12-346513d08f0b> in <module>()
----> 1 x.reshape(-1)

/Users/shoyer/dev/dask/dask/array/core.py in reshape(self, *shape)
   1290         if len(shape) == 1 and not isinstance(shape[0], Number):
   1291             shape = shape[0]
-> 1292         return reshape(self, shape)
   1293
   1294     @wraps(topk)

/Users/shoyer/dev/dask/dask/array/core.py in reshape(array, shape)
   2847
   2848     if any(len(c) != 1 for c in array.chunks[ndim_same + 1:]):
-> 2849         raise ValueError('dask.array.reshape requires that reshaped '
   2850                          'dimensions after the first contain at most one chunk')
   2851

ValueError: dask.array.reshape requires that reshaped dimensions after the first contain at most one chunk
```

### PR DESCRIPTION
**Pull request by mrocklin**
Fixes #2081 

Fixes https://github.com/dask/dask/issues/2082

### CODE REVIEW

**Comment by mrocklin** [comment]
OK, this seems to work.  @rabernat @shoyer this could use test cases.  What reshape problems would you like to see covered?

**Comment by mrocklin** [comment]
This is ready for review.  cc @jcrist if he has time tomorrow.

**Comment by byersiiasa** [comment]
thanks @mrocklin I will test this in next few days

**Comment by mrocklin** [comment]
Merging later today if there are no further comments.

**Comment by shoyer** [comment]
Thanks @mrocklin! I didn't get the chance to look over this carefully but I think it's a step in the right direction.

**Pull request merged**
