### PR TITLE
Add filenames return for ddf.to_csv and bag.to_textfiles as they both…

### PR DESCRIPTION
**Pull request by asettouf**
Partial commit for #1622, to enable returning filenames I modified bytes.core.write_bytes, which broke bag.to_textfiles which was "fortunate" as it also allowed to have this method returning the filenames after creation.

If my PR is fine, I will work to integrate hdf filenames return.

Thanks in advance for the review

### CODE REVIEW

**Comment by martindurant** [comment]
Seems like a reasonable thing to do, although extracting the filenames isn't at all hard.
Is it weird that you get filenames if compute=True, but only delayed values if not? Probably changing that behaviour would impact many places.
Is write_bytes not referenced in other places?

**Comment by mrocklin** [comment]
@martindurant it doesn't seem easy to include names in the outputs of `write_block_to_file`.  Are you suggesting that we don't accept this PR in order to maintain consistency?  Do you have a fix in mind?  Or is this just a comment?

It looks like this fails the flake8 style check (see travis-ci tests).  There is also a dangling print statement in there.

**Comment by martindurant** [comment]
I was meant only as a comment, I think this can be useful, but we have to accept the slight inconsistency.

**Comment by asettouf** [comment]
@martindurant 

To address the issues you mention:

- In my understanding, `delayed` are used as node in the acyclic graph and will be computed at a later time, which leads me to think that it would seem more appealing to return the filenames when actually computed

- To my surprise, `write_bytes` is not referenced anywhere else I could find. Given the slight inconsistency I can modify the name of the function to something more adequate, I just thought it would be nicer to have those 2 parts of the logic go together, as it is somewhat the case (names are computed here, of course computing them directly in the `to_csv` body wouldn't be hard)

@mrocklin 

Actually I did not have any idea about flake8, now everything should be in order.

**Comment by mrocklin** [comment]
The closest docs we have for `write_bytes` are here: http://dask.pydata.org/en/latest/bytes.html although I see that we don't include data writing there.  This should probably be extended in the future.  cc'ing @martindurant , although he may be busy.

Similarly we should extend the developer docs here http://dask.pydata.org/en/latest/develop.html to include the warning about flake8.  I'll add a note for this soon.

**Comment by mrocklin** [comment]
> By the way, after the tests what does xfail means exactly?

A test marked with xfail is allowed to fail.  This is often because we don't fully support this functionality yet.

**Comment by mrocklin** [comment]
This PR looks good to me.  Any further comments @martindurant ?

**Comment by martindurant** [comment]
LGTM. Note to self to check into write_bytes.
Are there any other to_* functions that should be considered?

**Comment by mrocklin** [comment]
This is in .  Thanks @asettouf !

**Comment by asettouf** [comment]
@mrocklin My pleasure. By the way, in that case, should I close the #1622 issue or let someone else handle it?

**Pull request merged**
