### PR TITLE
Use `concurrent.futures.Executors` in a few tests

### PR DESCRIPTION
**Pull request by jakirkham**
- [ ] Closes #xxxx
- [x] Tests added / passed
- [x] Passes `black dask` / `flake8 dask`

### CODE REVIEW

**Comment by jakirkham** [comment]
@dask/maintenance, would someone have time to look at this? 🙂

**Comment by jakirkham** [comment]
Planning on merging EOD tomorrow if no comments

**Comment by jsignell** [comment]
Sorry I didn't get a chance to look at this before it merged @jakirkham, would you be able to take a look at the test failure that I just linked? You can run those tests on a PR by including `test-hdfs` in the commit message

**Comment by jakirkham** [comment]
Thanks Julia! Fixing with PR ( https://github.com/dask/dask/pull/7472 )

**Pull request merged**
