### PR TITLE
Support int slicing for non-NumPy arrays

### PR DESCRIPTION
**Pull request by pentschev**
- [ ] Unblocks https://github.com/rapidsai/dask-cuda/pull/548
- [ ] Tests added / passed
- [ ] Passes `black dask` / `flake8 dask`

### CODE REVIEW

**Comment by quasiben** [comment]
Thanks all!  Merging

**Comment by quasiben** [comment]
This PR [failed upstream](https://github.com/dask/dask/runs/2082142688?check_suite_focus=true#step:5:4424) tests when merged in.  @jrbourbeau any idea what's going on here ?

**Comment by jrbourbeau** [comment]
Our upstream tests aren't currently passing. Here's the build for the commit before this PR was merged in https://github.com/dask/dask/runs/2078992830, which looks to have similar test failures as after this PR was merged

**Comment by jakirkham** [comment]
Ah ok. Thanks for pointing that out. Are we tracking this in an issue somewhere?

**Comment by jrbourbeau** [comment]
Just opened up https://github.com/dask/dask/issues/7366 for tracking

**Comment by jakirkham** [comment]
Thanks James! 😄

**Comment by pentschev** [comment]
I did a bit of investigation and none of the failing tests are related to this PR. I summarized my findings in https://github.com/dask/dask/issues/7366#issuecomment-796655791 .

**Comment by jrbourbeau** [comment]
Thanks for investigating Peter!

**Pull request merged**
