### PR TITLE
Remove daily stock demo utility

### PR DESCRIPTION
**Pull request by jrbourbeau**
This PR removes our daily stock demo utility which has been deprecated since August (~4 months). This seems like an appropriate length for a deprecation cycle. Additionally some related CI failures have started popping up (see [this CI build](daily_stock)) so I'm taking this as an opportunity to drop this utility. 

cc @jsignell

### CODE REVIEW

**Comment by jrbourbeau** [comment]
Also cc @rjzamora for visibility

**Review by rjzamora — APPROVED** [review]
I have not encountered anyone using this demo - So, I think four months is reasonable considering the pain it is causing :)

**Comment by jrbourbeau** [comment]
Thanks for reviewing @rjzamora! I'll plan to merge after CI finishes here to unblock CI on other PRs. Happy to handle any additional comments in a follow-up PR

**Comment by rjzamora** [comment]
Hmm - CI failures certainly seem unrelated

**Comment by jrbourbeau** [comment]
I've seen the `test_scheduler_highlevel_graph_unpack_import` before (only sporadically) but I didn't see an open issue for it so I just created https://github.com/dask/dask/issues/8480. The other CI failure looks like the Windows machine ran out of memory. I don't recall seeing this happen elsewhere, so I'll still plan to merge and open an issue if I see this pop up in another PR

**Pull request merged**
