### PR TITLE
Issue/kwargs

### PR DESCRIPTION
**Pull request by caseyclements**
I added dict as arg type to core._execute_task. This allows compatibility.apply to accept kwargs where values are results of dependencies

- [ ] Tests added / passed
- [ ] Passes `flake8 dask`

### CODE REVIEW

**Comment by mrocklin** [comment]
I think that historically we didn't do this because users would often provide large lists of dicts as data (typical JSON data) and executing each of them was expensive.

Instead we typically unpack dicts-that-might-contain-tasks into tasks like 

    (dict, [(k, v), (k, v), (k, v)])

Or something similar

**Comment by caseyclements** [comment]
OK - I confirmed that unpacking the dict into a task correctly inserts the results of other tasks, which is awesome. It starts looking obscure with apply,  but that's all under the hood. Shall I close this?

**Comment by mrocklin** [comment]
We could reconsider diving within dicts, but my guess is that people would
be against it.  Regardless it would be a longer discussion on an issue
before an implementation like this was relevant.  Closing for now sounds
good.

**Comment by caseyclements** [comment]
I thought we might open this back up for discussion. I've encountered an issue with the workaround above - creating the kwargs dictionary from a task: apple(fcn, [], (dict, [(k, v), (k, v), (k, v)])). The issue arises if any of the kwargs of the function, fcn, happen to share a name with one of the graph's keys. If they do, dask.core._execute_task will replace the key..

Here's a simple example
```
import dask
from dask.compatibility import apply
def f(x=2, y=3):
    return x*y
dsk = {
    'x': 4,
    'y': [5, 6],
    #'z': (apply, f, [], (dict, [['y', 7]])),  # TypeError: unhashable type: 'list' (in dask.core._execute_task)
    'z': (apply, f, [], (dict, [['x', 7]])),  # TypeError: f() keywords must be strings  (in apply)
}
print(dask.get(dsk, 'z'))
```

I cannot see how one would create a dictionary that shares a key with one in the dask graph without that key being replaced by the value of the node that shares its name.

**Pull request closed without merging**
