### PR TITLE
Package license file in wheels

### PR DESCRIPTION
**Pull request by jakirkham**
cc @mrocklin

- [ ] Tests added / passed
- [ ] Passes `flake8 dask`

### CODE REVIEW

**Comment by mrocklin** [comment]
I see that you requested my review here @jakirkham .  I don't think I know enough to review this authoritatively.  I recommend that you either find someone else to review or go ahead solo.

**Comment by jakirkham** [comment]
Have tested locally already and verified this is doing the correct thing. Happy to just merge if that's ok.

**Comment by jrbourbeau** [comment]
This looks to be the same as what's in the [PyPA sample project](https://github.com/pypa/sampleproject/blob/cbabca3f3f54a6e053e231d4cc89a46550049107/setup.cfg#L1-L4). Between that and local testing, this is probably good to go

**Comment by jakirkham** [comment]
Thanks @jrbourbeau for checking. Have gone ahead and merged.

**Pull request merged**
