### PR TITLE
DOC fix doctest failures in slicing.py

### PR DESCRIPTION
**Pull request by marenwestermann**
When setting up the Dask development environment and testing the code with `py.test dask --verbose --doctest-modules` two docstring tests in `dask/array/slicing.py` failed. I fixed these docstring failures and now all tests are successful (at least on my machine which is a macOS).

- [x] Tests added / passed
- [x] Passes `pre-commit run --all-files`

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by jsignell** [comment]
ok to test

**Comment by jsignell** [comment]
Hmm we do run doctests on CI and they are passing on main, but failing on this PR. It could be due to a version difference with your local environment?

You can try making a fresh environment following these steps to double check: https://docs.dask.org/en/stable/develop.html#install

**Comment by marenwestermann** [comment]
I made new environments with pip and conda and these are the installed packages, respectively:

pip: 
<details>

```
attrs==21.2.0
backports.entry-points-selectable==1.1.1
bokeh==2.4.2
cfgv==3.3.1
click==8.0.3
cloudpickle==2.0.0
-e git+ssh://git@github.com/marenwestermann/dask.git@e41ddf9af59048917ff919ae4d160428aa693e3a#egg=dask
distlib==0.3.4
distributed==2021.12.0
execnet==1.9.0
filelock==3.4.0
fsspec==2021.11.1
HeapDict==1.0.1
identify==2.4.0
iniconfig==1.1.1
Jinja2==3.0.3
locket==0.2.1
MarkupSafe==2.0.1
msgpack==1.0.3
nodeenv==1.6.0
numpy==1.21.5
packaging==21.3
pandas==1.3.5
partd==1.2.0
Pillow==8.4.0
platformdirs==2.4.0
pluggy==1.0.0
pre-commit==2.16.0
psutil==5.8.0
py==1.11.0
pyparsing==3.0.6
pytest==6.2.5
pytest-forked==1.4.0
pytest-rerunfailures==10.2
pytest-xdist==2.5.0
python-dateutil==2.8.2
pytz==2021.3
PyYAML==6.0
six==1.16.0
sortedcontainers==2.4.0
tblib==1.7.0
toml==0.10.2
toolz==0.11.2
tornado==6.1
typing_extensions==4.0.1
virtualenv==20.10.0
zict==2.0.0
```

</details>

conda: 
<details>

```
# packages in environment at /usr/local/Caskroom/miniforge/base/envs/dask-dev2:
#
# Name                    Version                   Build  Channel
abseil-cpp                20210324.2           he49afe7_0    conda-forge
aiobotocore               2.0.1              pyhd8ed1ab_0    conda-forge
aiohttp                   3.8.1            py39h89e85a6_0    conda-forge
aioitertools              0.8.0              pyhd8ed1ab_0    conda-forge
aiosignal                 1.2.0              pyhd8ed1ab_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
appnope                   0.1.2            py39h6e9494a_2    conda-forge
arrow-cpp                 6.0.1           py39h9d2824b_6_cpu    conda-forge
asciitree                 0.3.3                      py_2    conda-forge
asn1crypto                1.4.0              pyh9f0ad1d_0    conda-forge
async-timeout             4.0.2              pyhd8ed1ab_0    conda-forge
atk-1.0                   2.36.0               he69c4ee_4    conda-forge
attrs                     21.2.0             pyhd8ed1ab_0    conda-forge
aws-c-cal                 0.5.11               hd2e2f4b_0    conda-forge
aws-c-common              0.6.2                h0d85af4_0    conda-forge
aws-c-event-stream        0.2.7               hb9330a7_13    conda-forge
aws-c-io                  0.10.5               h35aa462_0    conda-forge
aws-checksums             0.1.11               h0010a65_7    conda-forge
aws-sam-translator        1.42.0             pyhd8ed1ab_0    conda-forge
aws-sdk-cpp               1.8.186              h766a74d_3    conda-forge
aws-xray-sdk              2.9.0              pyhd8ed1ab_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
blosc                     1.21.0               he49afe7_0    conda-forge
bokeh                     2.4.2            py39h6e9494a_0    conda-forge
boto3                     1.19.8             pyhd8ed1ab_0    conda-forge
botocore                  1.22.8             pyhd8ed1ab_0    conda-forge
brotli                    1.0.9                h0d85af4_6    conda-forge
brotli-bin                1.0.9                h0d85af4_6    conda-forge
brotlipy                  0.7.0           py39h89e85a6_1003    conda-forge
brunsli                   0.1                  h046ec9c_0    conda-forge
bzip2                     1.0.8                h0d85af4_4    conda-forge
c-ares                    1.18.1               h0d85af4_0    conda-forge
c-blosc2                  2.0.4                ha1a4663_1    conda-forge
ca-certificates           2021.10.8            h033912b_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cachey                    0.2.1              pyh9f0ad1d_0    conda-forge
cairo                     1.16.0            he01c77b_1009    conda-forge
certifi                   2021.10.8        py39h6e9494a_1    conda-forge
cffi                      1.15.0           py39he338e87_0    conda-forge
cfgv                      3.3.1              pyhd8ed1ab_0    conda-forge
cfitsio                   4.0.0                hb20e66c_0    conda-forge
cfn-lint                  0.54.2           py39h6e9494a_0    conda-forge
charls                    2.2.0                h046ec9c_0    conda-forge
charset-normalizer        2.0.9              pyhd8ed1ab_0    conda-forge
click                     8.0.3            py39h6e9494a_1    conda-forge
cloudpickle               2.0.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
conda                     4.11.0           py39h6e9494a_0    conda-forge
conda-package-handling    1.7.3            py39h89e85a6_1    conda-forge
coverage                  6.2              py39h89e85a6_0    conda-forge
cramjam                   2.5.0            py39h78c2a6c_0    conda-forge
crick                     0.0.3           py39hc89836e_1002    conda-forge
cryptography              36.0.1           py39h209aa08_0    conda-forge
curl                      7.80.0               hf45b732_1    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cytoolz                   0.11.2           py39h89e85a6_1    conda-forge
dask                      2021.12.0+16.ge41ddf9a.dirty           dev_0    <develop>
dataclasses               0.8                pyhc8e2a94_3    conda-forge
decorator                 5.1.0              pyhd8ed1ab_0    conda-forge
distlib                   0.3.4              pyhd8ed1ab_0    conda-forge
distributed               2021.12.0+22.g96ee7f7b          pypi_0    pypi
docker-py                 5.0.3            py39h6e9494a_2    conda-forge
docker-pycreds            0.4.0                      py_0    conda-forge
ecdsa                     0.17.0             pyhd8ed1ab_0    conda-forge
editdistance-s            1.0.0            py39hf018cea_2    conda-forge
execnet                   1.9.0              pyhd8ed1ab_0    conda-forge
expat                     2.4.2                he49afe7_0    conda-forge
fasteners                 0.16               pyhd8ed1ab_0    conda-forge
fastparquet               0.7.2            py39hc89836e_1    conda-forge
filelock                  3.4.0              pyhd8ed1ab_0    conda-forge
flask                     2.0.2              pyhd8ed1ab_0    conda-forge
flask_cors                3.0.10             pyhd3deb0d_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.13.1            h10f422b_1005    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.28.5           py39h89e85a6_0    conda-forge
freetype                  2.10.4               h4cff582_1    conda-forge
fribidi                   1.0.10               hbcb3906_0    conda-forge
frozenlist                1.2.0            py39h89e85a6_1    conda-forge
fsspec                    2021.11.1          pyhd8ed1ab_0    conda-forge
future                    0.18.2           py39h6e9494a_4    conda-forge
gdk-pixbuf                2.42.6               h2e6141f_0    conda-forge
gettext                   0.19.8.1          hd1a6beb_1008    conda-forge
gflags                    2.2.2             hb1e8313_1004    conda-forge
giflib                    5.2.1                hbcb3906_2    conda-forge
glog                      0.5.0                h25b26a9_0    conda-forge
graphite2                 1.3.13            h2e338ed_1001    conda-forge
graphviz                  2.50.0               h77de9ca_1    conda-forge
grpc-cpp                  1.42.0               h6da9ac5_1    conda-forge
gtk2                      2.24.33              h675d97a_1    conda-forge
gts                       0.7.6                hccb3bdf_2    conda-forge
h5py                      3.6.0           nompi_py39hbc6cb89_100    conda-forge
harfbuzz                  3.2.0                h447b35c_0    conda-forge
hdf5                      1.12.1          nompi_h2f0ef1a_103    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
httpretty                 1.1.4              pyhd8ed1ab_0    conda-forge
icu                       69.1                 he49afe7_0    conda-forge
identify                  2.3.7              pyhd8ed1ab_0    conda-forge
idna                      3.1                pyhd3deb0d_0    conda-forge
imagecodecs               2021.11.20       py39h90d8905_1    conda-forge
imageio                   2.13.4             pyh239f2a4_0    conda-forge
importlib-metadata        4.10.0           py39h6e9494a_0    conda-forge
importlib_metadata        4.10.0               hd8ed1ab_0    conda-forge
iniconfig                 1.1.1              pyh9f0ad1d_0    conda-forge
ipython                   7.30.1           py39h6e9494a_0    conda-forge
itsdangerous              2.0.1              pyhd8ed1ab_0    conda-forge
jbig                      2.1               h0d85af4_2003    conda-forge
jedi                      0.18.1           py39h6e9494a_0    conda-forge
jinja2                    3.0.3              pyhd8ed1ab_0    conda-forge
jmespath                  0.10.0             pyh9f0ad1d_0    conda-forge
joblib                    1.1.0              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   hbcb3906_0    conda-forge
jsondiff                  1.3.0              pyhd8ed1ab_0    conda-forge
jsonpatch                 1.32               pyhd8ed1ab_0    conda-forge
jsonpointer               2.0                        py_0    conda-forge
jsonschema                3.2.0              pyhd8ed1ab_3    conda-forge
junit-xml                 1.9                pyh9f0ad1d_0    conda-forge
jxrlib                    1.1                  h35c211d_2    conda-forge
kiwisolver                1.3.2            py39hf018cea_1    conda-forge
krb5                      1.19.2               hcfbf3a7_3    conda-forge
lcms2                     2.12                 h577c468_0    conda-forge
lerc                      3.0                  he49afe7_0    conda-forge
libaec                    1.0.6                he49afe7_0    conda-forge
libarchive                3.5.2                h2b60450_1    conda-forge
libblas                   3.9.0           12_osx64_openblas    conda-forge
libbrotlicommon           1.0.9                h0d85af4_6    conda-forge
libbrotlidec              1.0.9                h0d85af4_6    conda-forge
libbrotlienc              1.0.9                h0d85af4_6    conda-forge
libcblas                  3.9.0           12_osx64_openblas    conda-forge
libcurl                   7.80.0               hf45b732_1    conda-forge
libcxx                    12.0.1               habf9029_0    conda-forge
libdeflate                1.8                  h0d85af4_0    conda-forge
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libev                     4.33                 haf1e3a3_1    conda-forge
libevent                  2.1.10               h815e4d9_4    conda-forge
libffi                    3.4.2                h0d85af4_5    conda-forge
libgd                     2.3.3                hb8742e1_1    conda-forge
libgfortran               5.0.0           9_3_0_h6c81a4c_23    conda-forge
libgfortran5              9.3.0               h6c81a4c_23    conda-forge
libglib                   2.70.2               hf1fb8c0_0    conda-forge
libiconv                  1.16                 haf1e3a3_0    conda-forge
liblapack                 3.9.0           12_osx64_openblas    conda-forge
libllvm10                 10.0.1               h009f743_3    conda-forge
libmamba                  0.19.1               h9ce2d19_0    conda-forge
libmambapy                0.19.1           py39h2c464dc_0    conda-forge
libnghttp2                1.43.0               h6f36284_1    conda-forge
libopenblas               0.3.18          openmp_h3351f45_0    conda-forge
libpng                    1.6.37               h7cec526_2    conda-forge
libprotobuf               3.19.1               hcf210ce_0    conda-forge
librsvg                   2.52.4               h02b643e_0    conda-forge
libsolv                   0.7.19               hcf210ce_5    conda-forge
libssh2                   1.10.0               h52ee1ee_2    conda-forge
libthrift                 0.15.0               hab56fdc_1    conda-forge
libtiff                   4.3.0                hd146c10_2    conda-forge
libtool                   2.4.6             he49afe7_1008    conda-forge
libutf8proc               2.7.0                h0d85af4_0    conda-forge
libwebp                   1.2.1                h28dabe5_0    conda-forge
libwebp-base              1.2.1                h0d85af4_0    conda-forge
libxml2                   2.9.12               h7e28ab6_1    conda-forge
libzlib                   1.2.11            h9173be1_1013    conda-forge
libzopfli                 1.0.3                h046ec9c_0    conda-forge
llvm-openmp               12.0.1               hda6cdc1_1    conda-forge
llvmlite                  0.36.0           py39h798a4f4_0    conda-forge
locket                    0.2.0                      py_2    conda-forge
lz4                       3.1.10           py39heb8eec3_0    conda-forge
lz4-c                     1.9.3                he49afe7_1    conda-forge
lzo                       2.10              haf1e3a3_1000    conda-forge
mamba                     0.19.1           py39ha435c47_0    conda-forge
markupsafe                2.0.1            py39h89e85a6_1    conda-forge
matplotlib-base           3.5.1            py39hb07454d_0    conda-forge
matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
mmh3                      3.0.0            py39h9fcab8e_1    conda-forge
mock                      4.0.3            py39h6e9494a_2    conda-forge
monotonic                 1.5                        py_0    conda-forge
more-itertools            8.12.0             pyhd8ed1ab_0    conda-forge
moto                      2.2.19             pyhd8ed1ab_0    conda-forge
msgpack-python            1.0.3            py39hf018cea_0    conda-forge
multidict                 5.2.0            py39h89e85a6_1    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
ncurses                   6.2                  h2e338ed_4    conda-forge
networkx                  2.6.3              pyhd8ed1ab_1    conda-forge
nodeenv                   1.6.0              pyhd8ed1ab_0    conda-forge
numba                     0.53.1           py39h32e38f5_1    conda-forge
numcodecs                 0.9.1            py39h9fcab8e_2    conda-forge
numexpr                   2.8.0            py39h4d6be9b_0    conda-forge
numpy                     1.21.5           py39h516c64c_0    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjpeg                  2.4.0                h6e7aa92_1    conda-forge
openssl                   1.1.1l               h0d85af4_0    conda-forge
orc                       1.7.1                h84518c8_1    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.3.5            py39h4d6be9b_0    conda-forge
pango                     1.48.10              h056538c_2    conda-forge
parquet-cpp               1.5.1                         2    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
partd                     1.2.0              pyhd8ed1ab_0    conda-forge
pcre                      8.45                 he49afe7_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.4.0            py39he9bb72f_0    conda-forge
pip                       21.3.1             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               hbcb3906_0    conda-forge
pluggy                    1.0.0            py39h6e9494a_2    conda-forge
pre-commit                2.16.0           py39h6e9494a_0    conda-forge
prompt-toolkit            3.0.24             pyha770c72_0    conda-forge
psutil                    5.8.0            py39h89e85a6_2    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
py                        1.11.0             pyh6c4a22f_0    conda-forge
pyarrow                   6.0.1           py39h4d6536f_6_cpu    conda-forge
pyasn1                    0.4.8                      py_0    conda-forge
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycosat                   0.6.3           py39h89e85a6_1009    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygments                  2.10.0             pyhd8ed1ab_0    conda-forge
pyopenssl                 21.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.6              pyhd8ed1ab_0    conda-forge
pyrsistent                0.18.0           py39h89e85a6_0    conda-forge
pysocks                   1.7.1            py39h6e9494a_4    conda-forge
pytables                  3.6.1            py39hfd850c7_5    conda-forge
pytest                    6.2.5            py39h6e9494a_1    conda-forge
pytest-cov                3.0.0              pyhd8ed1ab_0    conda-forge
pytest-forked             1.4.0              pyhd8ed1ab_0    conda-forge
pytest-rerunfailures      10.2               pyhd8ed1ab_0    conda-forge
pytest-xdist              2.5.0              pyhd8ed1ab_0    conda-forge
python                    3.9.9           h1248fe1_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-graphviz           0.19.1             pyhaef67bd_0    conda-forge
python-jose               3.3.0              pyh6c4a22f_1    conda-forge
python-snappy             0.6.0            py39hfa214c3_1    conda-forge
python-xxhash             2.0.2            py39h89e85a6_1    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pytz                      2021.3             pyhd8ed1ab_0    conda-forge
pywavelets                1.2.0            py39hc89836e_1    conda-forge
pyyaml                    6.0              py39h89e85a6_3    conda-forge
re2                       2021.11.01           he49afe7_0    conda-forge
readline                  8.1                  h05e3726_0    conda-forge
reproc                    14.2.3               h0d85af4_0    conda-forge
reproc-cpp                14.2.3               he49afe7_0    conda-forge
requests                  2.26.0             pyhd8ed1ab_1    conda-forge
responses                 0.16.0             pyhd8ed1ab_0    conda-forge
rsa                       4.8                pyhd8ed1ab_0    conda-forge
ruamel_yaml               0.15.80         py39h89e85a6_1006    conda-forge
s3fs                      2021.11.1          pyhd8ed1ab_0    conda-forge
s3transfer                0.5.0              pyhd8ed1ab_0    conda-forge
scikit-image              0.19.1           py39h4d6be9b_0    conda-forge
scikit-learn              1.0.1            py39hd4eea88_3    conda-forge
scipy                     1.7.3            py39h056f1c0_0    conda-forge
setuptools                60.1.0           py39h6e9494a_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.8                hb1e8313_3    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
sparse                    0.13.0             pyhd8ed1ab_0    conda-forge
sqlalchemy                1.3.23           py39h4b0b724_0    conda-forge
sqlite                    3.37.0               h23a322b_0    conda-forge
sshpubkeys                3.1.0                      py_0    conda-forge
tblib                     1.7.0              pyhd8ed1ab_0    conda-forge
threadpoolctl             3.0.0              pyh8a188c0_0    conda-forge
thrift                    0.15.0           py39h9fcab8e_1    conda-forge
tifffile                  2021.11.2          pyhd8ed1ab_0    conda-forge
tiledb                    2.5.3                hca4410a_0    conda-forge
tiledb-py                 0.11.3           py39h668ab2b_1    conda-forge
tk                        8.6.11               h5dbffcc_1    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.0              pyhd8ed1ab_1    conda-forge
toolz                     0.11.2             pyhd8ed1ab_0    conda-forge
tornado                   6.1              py39h89e85a6_2    conda-forge
tqdm                      4.62.3             pyhd8ed1ab_0    conda-forge
traitlets                 5.1.1              pyhd8ed1ab_0    conda-forge
typing-extensions         4.0.1                hd8ed1ab_0    conda-forge
typing_extensions         4.0.1              pyha770c72_0    conda-forge
tzdata                    2021e                he74cb21_0    conda-forge
urllib3                   1.26.7             pyhd8ed1ab_0    conda-forge
virtualenv                20.4.7           py39h6e9494a_1    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
websocket-client          1.2.3              pyhd8ed1ab_0    conda-forge
werkzeug                  2.0.1              pyhd8ed1ab_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
wrapt                     1.13.3           py39h89e85a6_1    conda-forge
xarray                    0.20.2             pyhd8ed1ab_0    conda-forge
xmltodict                 0.12.0                     py_0    conda-forge
xxhash                    0.8.0                h35c211d_3    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
yaml                      0.2.5                haf1e3a3_0    conda-forge
yaml-cpp                  0.6.3                hb1e8313_4    conda-forge
yarl                      1.7.2            py39h89e85a6_1    conda-forge
zarr                      2.10.3             pyhd8ed1ab_0    conda-forge
zfp                       0.5.5                h4a89273_8    conda-forge
zict                      2.0.0                      py_0    conda-forge
zipp                      3.6.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11            h9173be1_1013    conda-forge
zstd                      1.5.0                h582d3a0_0    conda-forge
```
</details>

Since the difference between my environment and the CI's environment are whitespaces, I added `+NORMALIZE_WHITESPACE` to make the tests pass. I noticed that this marker is used in multiple (30) other places in the repo. It might therefore be a good idea to set this globally in`setup.cfg`. This is done for example in scikit-learn alongside `ELLIPSIS`: https://github.com/scikit-learn/scikit-learn/blob/78a941aa73756595baff805fd390a0590262ac97/setup.cfg#L7

**Comment by jsignell** [comment]
Thanks for this @marenwestermann - I agree that normalizing whitespace is uncontroversial :) 

Congrats on your first contribution to Dask!

**Pull request merged**
