### PR TITLE
COMPAT: compat with pandas 0.20.0 for movement of pandas.util.hashing

### LINKED ISSUE #2293: COMPAT: pandas 0.20.0
https://github.com/pandas-dev/pandas/pull/16223

we moved the imports for ``pandas.util.hashing`` to ``pandas.util``. So I will put up a PR to reflect this change for dask. (these are deprecated in the original location).

### PR DESCRIPTION
**Pull request by jreback**
Fixes #2293.

### CODE REVIEW

**Comment by jreback** [comment]
note that I haven't merged https://github.com/pandas-dev/pandas/pull/16223 yet.

and the rc1 will now fail (as its a different path), but we are releasing 0.20.0 shortly (next day or so)

**Comment by jcrist** [comment]
Thanks. I also moved the import of `pandas.util.decorators.cache_readonly` (and grepped for others). Will merge once tests pass.

**Comment by TomAugspurger** [comment]
FYI I cherry-picked these two commits over in #2296 and the 0.20.0rc2 build succeeded: https://travis-ci.org/dask/dask/jobs/228796376

**Comment by jcrist** [comment]
Thanks @TomAugspurger!

**Pull request merged**
