### PR TITLE
allow custom shape and/or label in to_graphviz()

### PR DESCRIPTION
**Pull request by sheppard**
- [x] Tests added / passed
- [x] Passes `flake8 dask`
- [ ] Fully documented, including `docs/source/changelog.rst` for all changes
      and one of the `docs/source/*-api.rst` files for new API

This extends the `data_attributes` and `function_attributes` arguments to support `shape` and `label`.   Without this change, to_graphviz fails with `TypeError: node() got multiple values for keyword argument 'shape'`.  I don't think these arguments are currently documented so I'm not sure whether new documentation is needed.

### CODE REVIEW

**Comment by mrocklin** [comment]
I like your implementation here.  It looks like it's general to any attribute that we might want to pass through by key.  It would be useful to check this generality in tests just to verify that it sticks around in the future.

The failures in tests are unrelated and have since been resolved.  They should go away if you end up pushing again.

**Comment by mrocklin** [comment]
I found this useful today!  Thanks for your work here!

We're waiting on #2973 to merge for tests to pass.

**Comment by jcrist** [comment]
This looks good to me. Anything else left to do here?

**Comment by mrocklin** [comment]
Thanks for the reminder @jcrist , thanks for the work @sheppard !

**Comment by sheppard** [comment]
Thanks!

**Pull request merged**
