### PR TITLE
Remove skips from doctests (5 of 6)

### PR DESCRIPTION
**Pull request by zzhengnan**
This is one of 6 PRs that collectively addresses #7823. Please see https://github.com/dask/dask/issues/7823#issuecomment-873414398 for more context.

Links to all 6 PRs
- #7874
- #7873
- #7872
- #7865
- #7864
- #7863

### CODE REVIEW

**Comment by zzhengnan** [comment]
@jsignell Ready for review.

**Review by jsignell — COMMENTED** [review]
Hmm. I am not quite sure if these changes make the docs clearer. Particularly the times as floats is kind of hard to interpret. What do you think?

**Comment by zzhengnan** [comment]
@jsignell Could you clarify what you mean by the following? 
> Particularly the times as floats is kind of hard to interpret.

I too feel something like `('y', (add, 'x', 10), 1435352238.48039, 1435352238.480655, 140285575100160)` is hard to interpret, which is precisely the reason why I'm removing them in the PR.

Separately, please see https://github.com/dask/dask/pull/7865#discussion_r676938977.

**Comment by jsignell** [comment]
Oh :facepalm: I guess I was looking at the changes backwards or something? I have no idea. This looks great!

**Pull request merged**
