### PR TITLE
CI: pin libprotobuf to allow nightly pyarrow in the upstream CI build

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
See https://github.com/dask/dask/issues/9449, https://github.com/dask/dask/pull/9452

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
So this seems to be working to set up the build, just a _lot_ of actual test failures now :)

**Review by jrbourbeau — COMMENTED** [review]
Thanks for working on this @jorisvandenbossche! 

Is there an upstream issue in `pyarrow` somewhere that we can track? It'd be good to know when we can remove this pin

**Comment by jorisvandenbossche** [comment]
I think the failures are mostly related to three changes in pandas:

- deprecation of the `inplace` keyword in `set_index` (although we are still considering to revert that -> https://github.com/pandas-dev/pandas/pull/48417)
- deprecation of the default `numeric_only` in groupby -> this probably needs to be handled here
- a change in `astype` behaviour with a numpy datetime64 dtype without unit seems to cause some failures with pyspark -> relevant pandas issue: https://github.com/pandas-dev/pandas/issues/47844

**Comment by jorisvandenbossche** [comment]
> Is there an upstream issue in `pyarrow` somewhere that we can track? It'd be good to know when we can remove this pin

I am not fully sure if we have a JIRA about this, will check. There is https://github.com/conda-forge/arrow-cpp-feedstock/pull/815 that might be related upstream in conda-forge, but so those nightly packages are built in Arrow itself, so we might need to update our local recipe / conda build.

**Comment by ncclementi** [comment]
@jorisvandenbossche Yes, you are right, the failures are related to mainly upstream pandas compatibility. We will be working on that. But those are out of the scope of this PR. 

I'd be happy to merge this as is, unless @jrbourbeau you have any comments.

**Comment by jorisvandenbossche** [comment]
Yes, certainly, I wasn't planning on tackling them here. I just wanted to give some context for the failures (as I am involved in some of those changes in pandas)

**Review by jrbourbeau — COMMENTED** [review]
@jorisvandenbossche would you mind moving the `libprotobuf` pin to [where we install the `pyarrow` nightly build in the `upstream` build](https://github.com/dask/dask/blob/ef34664a9f7ec477c2e311d968603edcdb0d1dd0/continuous_integration/scripts/install.sh#L10-L13)? That way the `libprotobuf` pin is colocated with the relevant section of code and the pin only happens in the `upstream` build where it's (temporarily) needed. Other than that this looks good to go. 

> I think the failures are mostly related to three changes in pandas:

Thank you for the nice summary and pointing to corresponding upstream threads @jorisvandenbossche -- that's useful

**Comment by jorisvandenbossche** [comment]
@jrbourbeau that would indeed be cleaner. I already pushed it, however from testing locally, this will probably fail. The problem is that if the environment is first created with a newer abseil-cpp (which now depends on libabseil with an exact pin), doing a `mamba install abseil-cpp= ..` with an older version fails, because libabseil is pinned with it, and we can't remove libabseil first, as that would remove a while lot of packages ...

**Comment by jrbourbeau** [comment]
Ah, I see -- thanks for the additional context. Well in that case, if the current state of this PR works (not expected) then we can merge this in. If not, then let's go back to what was here before and then merge that. 

On a possibly related note, we've started seeing `pyarrow` related failures on `main` on our macOS Python 3.9 build. See, for example, [this build](https://github.com/dask/dask/runs/8213499408?check_suite_focus=true). We're getting strange linking errors like 

```
 E   ImportError: dlopen(/Users/runner/miniconda3/envs/test-environment/lib/python3.9/site-packages/pyarrow/lib.cpython-39-darwin.so, 2): Library not loaded: @rpath/libprotobuf.31.dylib
E     Referenced from: /Users/runner/miniconda3/envs/test-environment/lib/liborc.dylib
E     Reason: Incompatible library version: liborc.dylib requires version 32.0.0 or later, but libprotobuf.31.dylib provides version 31.0.0
```

I say this might be related as the traceback mentions `libprotobuf` and `libprotobuf` just had a new build issued a few hours ago

**Review by jrbourbeau — APPROVED** [review]
Thanks @jorisvandenbossche! I'll merge this after CI finishes

FWIW it looks like this has the unintended consequence of fixing the `libprotobuf` linking issue (though it's already been reported upstream in the conda-forge feedstock https://github.com/conda-forge/libprotobuf-feedstock/pull/128#issuecomment-1238531229)

**Comment by jorisvandenbossche** [comment]
I suppose https://issues.apache.org/jira/browse/ARROW-17635 is relevant issue on the Arrow side to update our conda recipe (and thus nightly packages)

**Pull request merged**
