### PR TITLE
Test CI

### PR DESCRIPTION
**Pull request by jrbourbeau**

### CODE REVIEW

**Comment by jrbourbeau** [comment]
Interestingly we've started getting several CuPy-related test failures with

```
17:04:41 E   TypeError: Implicit conversion to a NumPy array is not allowed. Please use `.get()` to construct a NumPy array explicitly.
```

cc @pentschev

**Comment by pentschev** [comment]
Thanks @jrbourbeau for finding this, it seems that our docker image was picking NumPy 1.19.5, which doesn't contain NEP-35. I'm adding NumPy 1.21 now in https://github.com/rapidsai/dask-build-environment/pull/3. I'll also work on skipping those tests on NumPy < 1.20.

**Comment by pentschev** [comment]
I opened https://github.com/dask/dask/pull/7982 to address tests that missed the `skip` mark.

**Comment by pentschev** [comment]
rerun tests

**Comment by pentschev** [comment]
https://github.com/rapidsai/dask-build-environment/pull/3 is merged and new docker images have been built already. Previously failing tests that depend on NEP-35 now pass, but there's still `test_set_index_interpolate[cudf]` that fails which is being addressed by https://github.com/dask/dask/pull/7982, when that's merged all gpuCI tests here should pass.

**Comment by jrbourbeau** [comment]
Closing as failures are being resolved elsewhere -- thanks @pentschev!

**Pull request closed without merging**
