### PR TITLE
Docs: Add Coiled to list of paid support organizations

### PR DESCRIPTION
**Pull request by koverholt**
Coiled offers paid support and training for Dask. This PR:

- Add Coiled to list of paid support organizations in docs
- Add note that the list of paid support organizations is listed in alphabetical order

### CODE REVIEW

**Review by jrbourbeau — COMMENTED** [review]
This seems okay to me, but since I work for Coiled I'll leave it to another maintainer employed by someone else (like @jsignell or @martindurant) to handle this PR. 

Also, +1 for making this list alphabetically ordered as to not indirectly communicate a relative priority between the listed organizations

**Comment by jrbourbeau** [comment]
Also, @jsignell you previously commented that Saturn shouldn't go in this "Paid Support" section (xref https://github.com/dask/dask/issues/6795#issuecomment-724963463). Just wanted to check in to see if that's still the case, or if we should also add Saturn here.

**Comment by jsignell** [comment]
Yeah this seems reasonable to me. Thanks for the ping and :wave: @koverholt

**Comment by jsignell** [comment]
I'll wait until the end of the day to merge to see if @martindurant has any comments.

**Comment by martindurant** [comment]
Certainly fine with me. Alphabetical listing general works to Anaconda's advantage, but doesn't matter while the list is short anyway. Should that change, we may want to make it randomised.

**Comment by koverholt** [comment]
Thanks @jsignell 🤘 and @martindurant for your input/help here!

**Pull request merged**
