### PR TITLE
Remove toolz dependency in async.py

### LINKED ISSUE #1849: ImportError: No module named 'toolz' on default install
The documentation states 

> pip install dask: Install only dask, which depends only on the standard library. This is appropriate if you only want the task schedulers.

With `dask==0.12.0` installed an import fails, because `toolz` is not required as a dependency.

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input> in <module>()
      1 import pandas as pd
----> 2 import dask

lib/python3.5/site-packages/dask/__init__.py in <module>()
      3 from .core import istask
      4 from .context import set_options
----> 5 from .async import get_sync as get
      6 try:
      7     from .delayed import do, delayed, value

lib/python3.5/site-packages/dask/async.py in <module>()
    118 import traceback
    119 
--> 120 from toolz import identity
    121 
    122 from .compatibility import Queue

ImportError: No module named 'toolz'
```

### PR DESCRIPTION
**Pull request by ernstki**
- provide an 'identity' function right inside dask/async.py so that toolz
  isn't a hard requirement for a "default" pip installation

- closes #1849

### CODE REVIEW

**Comment by mrocklin** [comment]
Looks like a doctest failures and a few minor pep8 issues.  Otherwise looks good to me.

**Comment by mrocklin** [comment]
You can see the failures by clicking on `Details` next to the red X on the line below, and then selecting one of the builds (I recommend the Python 2.7 build to also get the doctest failure).

**Comment by ernstki** [comment]
I'm new at this. I double-checked everything by running pytest and flake8 locally, to avoid future embarrassment. I think the CI builds should pass now.

**Comment by mrocklin** [comment]
No embarrassment needed.  I often fail doctest and flake8 checks myself and often rely on travis.ci to catch my mistakes.  

Thanks for the work!

**Comment by ernstki** [comment]
Just for my edification here: in your opinion, should the originator of a PR add "closes \<issue #>" to _their_ commit message, or do you have the opportunity to do that when you're rebasing / merging / however-that-works?

Sure, I do that all the time for my own repos where I have direct commit access, but it seems almost presumptuous to do that for someone else's.

**Comment by mrocklin** [comment]
From my perspective anyone who can close an issue should close it.  This involves all committers and the person who opened the issue.    Issues are more often left open too long than closed too early.

But I have no idea what's correct.  Not sure that there is a correct.  Your opinions here are probably just as valid as anyone's.

**Comment by darrenleeweber** [comment]
This MR doesn't entirely fix the dependency on `toolz` for a vanilla pip install of `dask`, i.e.
```
.venv/lib/python3.7/site-packages/dask/delayed.py:11: in <module>
    from toolz import curry, concat, unique, merge
E   ModuleNotFoundError: No module named 'toolz'
```

**Pull request merged**
