### PR TITLE
Fix io_deps bug in rewrite_blockwise

### PR DESCRIPTION
**Pull request by rjzamora**
Addresses [xarray#4703](https://github.com/pydata/xarray/issues/4703) (which is alse described in #6931 )

The current `rewrite_blockwise` code is updating a list of IO-dependencies (`io_deps`) within a loop that can be escaped before all dependencies are collected.  This is causing CI errors in xarray.  This PR moves the `io_deps` update to a simple/dedicated loop over all input layers.

**TODO**:
- [ ] come up with a test

### CODE REVIEW

**Comment by rjzamora** [comment]
cc @dcherian -  I'm hoping this is the only fix needed for the xarray CI failures.  Please do let me know if you already have a simple dask.array test handy :)

**Comment by dcherian** [comment]
I confirmed that xarray's CI passes on this branch locally. 

I could not create a pure `dask.array` test, or even a pure `xarray` test!

**Comment by ian-r-rose** [comment]
> I could not create a pure `dask.array` test, or even a pure `xarray` test!

I also tried to create a test, and found it really challenging! The xarray test has some very subtle things going on with null checks in a string array that I wasn't able to untangle.

**Comment by dcherian** [comment]
Yes it's breaking on

```
bool(
    (
        (arr1 == arr2) | (dask.array.isnull(arr1) & dask.array.isnull(arr2))
    ).any()
)
```

`arr1` and `arr2` are dask arrays created using `from_array` with either `str` or `int64` dtypes, and sometimes there is a `slice` involved. In one case `arr1` had unknown shape and chunksize.

**Comment by rjzamora** [comment]
Closing in favor of #7042

**Pull request closed without merging**
