### PR TITLE
[WIP] Enable codecov

### PR DESCRIPTION
**Pull request by pentschev**
Solves #2218.

cc @mrocklin @jakirkham @TomAugspurger 

- [ ] Tests added / passed
- [ ] Passes `flake8 dask`

### CODE REVIEW

**Comment by pentschev** [comment]
Looks like we have something here already. We should probably tweak what options we want to enable, and maybe decide on enforcement policy. For now I suggest we don't enforce coverage maintenance (i.e., that it's never negative) but provide this as a tool for developers to check how PRs affect the project, at least until we are comfortable that options we set suit our needs.

**Comment by jakirkham** [comment]
Generally seems ok to me.

Would slightly prefer if we could turn the comments off (to cutdown on noise). Also would be good to enable the status information so we can link to the details on their website as needed.

**Comment by pentschev** [comment]
> Generally seems ok to me.
> 
> Would slightly prefer if we could turn the comments off (to cutdown on noise). Also would be good to enable the status information so we can link to the details on their website as needed.

Agreed.

**Comment by pentschev** [comment]
I think to get codecov statuses we need to install its [Codecov Github app](https://github.com/apps/codecov). Could someone with permissions do that?

**Comment by mrocklin** [comment]
Done, I think

**Comment by pentschev** [comment]
We have status now, thanks @mrocklin for installing the app. I've attempted to add coverage for each submodule, but they all seem to redirect to the same place, I'm not sure if that's because there's no report (we have to merge to get it first) or something wrong with the configuration.

Either way, would you say we should have codecov status for each submodule as different projects or just a single one? I'm personally fine with either.

**Comment by jakirkham** [comment]
Thanks Matt!

No strong feelings. We might be ok with just one report near term. However if that's difficult to do, wouldn't worry about it.

**Comment by pentschev** [comment]
On the contrary, it's actually easier. I just thought it would be cool to
see them separately, but I'm not sure that worked. For now I'm gonna revert
it into a single project then.

**Comment by pentschev** [comment]
Ok, we now have the status for a single project setup. Unless someone already knows about other options that we may want, I would suggest we merge this PR and start looking at codecov comparisons after this to improve it further, since I don't think we can see the comparisons before it gets merged and creates a baseline report.

**Comment by mrocklin** [comment]
OK to merge?

**Comment by jrbourbeau** [comment]
+1 from me

**Pull request merged**
