### PR TITLE
Raise ``FutureWarning`` when passed ``meta`` results in a ``DataFrame`` in ``Series.apply``

### PR DESCRIPTION
**Pull request by phofl**
- [ ] Closes #xxxx
- [ ] Tests added / passed
- [ ] Passes `pre-commit run --all-files`

### CODE REVIEW

**Review by jrbourbeau — COMMENTED** [review]
Thanks @phofl! 

@j-bennet do you have bandwidth to review? Looks like this is an alternative to https://github.com/dask/dask/pull/10255

**Review by j-bennet — APPROVED** [review]
Upstream is green, LGTM. Thank you @phofl.

**Comment by frainz-de** [comment]
The common advice to use apply for unpacking a column of dicts or lists now returns the warning you added. What is the recommended way of unpacking a column now?

For an example, see https://stackoverflow.com/questions/50512188/unpack-dictionary-from-pandas-column

**Comment by phofl** [comment]
This is an upstream change, the relevant discussion is here: https://github.com/pandas-dev/pandas/issues/52116

Short: There is no convenient way to do this without apply behaving as right now. I added this there as well

**Pull request merged**
