### PR TITLE
[docs] Grammar and formatting updates to docstrings

### PR DESCRIPTION
**Pull request by jameslamb**
In this PR, I'd like to propose some minor changes to a few small improvements to docstrings.

This PR contains one grammatical correction and one suggested use of inline code formatting. All other changes are just eliminating excess whitespace...please let me know if you'd like me to revert the whitespace changes.

Thanks for your time and consideration.

## Required checks

- [x] Tests added / passed
- [x] Passes `black dask` / `flake8 dask`

### CODE REVIEW

**Comment by quasiben** [comment]
Thanks @jameslamb for the contribution.  In general, these look great.  However, a number of changed include moving from two spaces to one space after a period and I want to check in with other devs about this.  Are folks especially opinionated about the two vs one space after a period issue ?

**Comment by jameslamb** [comment]
> Thanks @jameslamb for the contribution. In general, these look great. However, a number of changed include moving from two spaces to one space after a period and I want to check in with other devs about this. Are folks especially opinionated about the two vs one space after a period issue ?

No problem! I just assumed those were mistakes, since most docstrings in the project have one space after periods. Let me know, I'm happy to revert those whitespace changes.

**Comment by jrbourbeau** [comment]
Thanks for the PR @jameslamb! I have no strong opinion on the one vs. two space after a period topic. Likewise I'm in favor of accepting inconsistencies and letting whoever is contributing documentation use whatever convention they prefer.

**Comment by jameslamb** [comment]
> Thanks for the PR @jameslamb! I have no strong opinion on the one vs. two space after a period topic. Likewise I'm in favor of accepting inconsistencies and letting whoever is contributing documentation use whatever convention they prefer.

sure! Ok I'll revert the changes then. If you don't consider them mistakes, let's not touch those lines.

**Comment by quasiben** [comment]
@jrbourbeau that's a good philosophy on doc edits.  I'll use that moving forward

**Comment by quasiben** [comment]
Thank you again for the updates @jameslamb and apologies for the back and forth on spaces

**Pull request merged**
