### PR TITLE
Support Python 3.5 in Parquet code

### LINKED ISSUE #5447: Python 3.5 support broken
The latest dask release, 2.5.0, contains syntax not supported in Python 3.5:

```python
$ python3.5 -c "from dask.dataframe.io.parquet import arrow"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "lib/python3.5/site-packages/dask/dataframe/io/parquet/arrow.py", line 108
    **kwargs,
            ^
SyntaxError: invalid syntax
```
It looks like there is a Python 3.5 CI pipeline, so I'm not sure how this was not caught.

### PR DESCRIPTION
**Pull request by mrocklin**
Fixes #5447

cc @TomAugspurger @quasiben 

I still don't know why black wanted to change this file.  Things seem to be valid in Python 3.5

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Black failed CI on 3.6 and 3.7.

So thoughts on temporarily disabling black (perhaps on a branch other than master) so that we can release a 2.5.3 that's compatible with 3.5? Or we can figure what's causing black to think we're 3.6+, which sounds harder.

**Comment by quasiben** [comment]
I want to spend a few minutes seeing if I can resolve the issue on the black side -- 10-20 if that's ok

**Comment by TomAugspurger** [comment]
Sounds good.

**Comment by quasiben** [comment]
I believe the issue has been resolved in latest master of black as @cpcloud noted here:
https://github.com/psf/black/issues/419#issuecomment-478220853

But there hasn't been a release of black since Mar. 14th.  

I tried with latest master and the trailing comma issue is fixed but a fair amount of reformatting of other previously black-ed files also occurs

**Comment by quasiben** [comment]
PR https://github.com/dask/dask/pull/5491 may resolve the issue but it requires black from source.   This would then require all devs to upgrade to black source -- i don't think we should do this.  It looks like black is trying to release: https://github.com/psf/black/issues/988 , however, there are issue which need to be resolved before that occurs. 

My vote would be to do as @TomAugspurger suggested.  Disable black temporarily and release then re-enable black once dask removes 3.5 as a supported python version

**Comment by mrocklin** [comment]
> This would then require all devs to upgrade to black source

We can control this by changing the version in `.pre-commit-config.yaml`

This is also what we do in `distributed` today.  

https://github.com/dask/distributed/blob/master/.pre-commit-config.yaml

**Comment by mrocklin** [comment]
I would prefer not to wait on the `black` devs to issue a release in a timely manner.  They haven't seemed very keen to do this in the past.  https://github.com/psf/black/issues/517

**Pull request closed without merging**
