### PR TITLE
Debug docs build

### PR DESCRIPTION
**Pull request by jrbourbeau**
xref https://github.com/dask/dask/issues/11519

### CODE REVIEW

**Review by jrbourbeau — COMMENTED** [review]
Okay, so this is weird one. As part of the docs build, we use requests to download dask and distributed config files. That works for me locally, but things are failing at that stage in the readthedocs build. We're getting this response saying "Access to this site has been restricted"

```html
<!DOCTYPE html>
<html>
  <head>
    <meta content="origin" name="referrer">
    <title>Forbidden &middot; GitHub</title>
    <style type="text/css" media="screen">
      body {
        background-color: #f1f1f1;
        margin: 0;
      }
      body,
      input,
      button {
        font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
      }
      .container { margin: 30px auto 40px auto; width: 800px; text-align: center; }
      a { color: #4183c4; text-decoration: none; font-weight: bold; }
      a:hover { text-decoration: underline; }
      h1, h2, h3 { color: #666; }
      ul { list-style: none; padding: 25px 0; }
      li {
        display: inline;
        margin: 10px 50px 10px 0px;
      }
      .logo { display: inline-block; margin-top: 35px; }
      .logo-img-2x { display: none; }
      @media
      only screen and (-webkit-min-device-pixel-ratio: 2),
      only screen and (   min--moz-device-pixel-ratio: 2),
      only screen and (     -o-min-device-pixel-ratio: 2/1),
      only screen and (        min-device-pixel-ratio: 2),
      only screen and (                min-resolution: 192dpi),
      only screen and (                min-resolution: 2dppx) {
        .logo-img-1x { display: none; }
        .logo-img-2x { display: inline-block; }
      }
    </style>
  </head>
  <body>

    <div class="container">
      <h1>Access to this site has been restricted.</h1>

      <p>
        <br>
        If you believe this is an error,
        please contact <a href="https://support.github.com">Support</a>.
      </p>

      <div id="s">
        <a href="https://githubstatus.com">GitHub Status</a> &mdash;
        <a href="https://twitter.com/githubstatus">@githubstatus</a>
      </div>
    </div>
  </body>
</html>
```

After Googling around it looks like setting a custom `User-Agent` header for the request might help this page not get blocked. I'll try that and see if that helps

**Comment by jrbourbeau** [comment]
Okay, adding the `User-Agent` did the trick. I'll open up a PR for that over in our sphinx theme

**Comment by phofl** [comment]
I had weird errors on xarray ci too, something changed for some reason

James Bourbeau ***@***.***> schrieb am Do. 14. Nov. 2024 um
18:19:

**Comment by jrbourbeau** [comment]
> I had weird errors on xarray ci too

Can you point me to the PR, etc?

**Comment by phofl** [comment]
https://github.com/pydata/xarray/pull/9770


James Bourbeau ***@***.***> schrieb am Do. 14. Nov. 2024 um
18:36:

**Comment by jrbourbeau** [comment]
Alright, there's a new `dask-sphinx-theme` release out with the fix. Let's confirm things are working here now with the current `main`

**Pull request closed without merging**
