### PR TITLE
Flake8

### PR DESCRIPTION
**Pull request by mrocklin**
I added a flake8 plugin to my editor and cleaned up a few things. 

I want to stress though that I don't think it is a good idea to apply all style checks automatically.  I think that this amount of process might add friction to progress.  It does seem like a good thing to do periodically though.

### CODE REVIEW

**Comment by jcrist** [comment]
I have flake8 setup with my editor to only run a few checks with a hotkey. I usually run it before committing just to find extra imports, dead variables, long lines, and extraneous whitespace. Totally agree that it shouldn't be part of our test suite though.

**Comment by mrocklin** [comment]
I did notice that the modules in which you tend to work were far more tidy
than the modules in which I tend to work :)

**Comment by sinhrks** [comment]
How about only enabling PyFlakes code checks on suite?

- https://flake8.readthedocs.io/en/latest/warnings.html

Though I don't have strong opinion, as we can check it before release.

**Comment by mrocklin** [comment]
I definitely see more value in pyflakes than in pep8.  

However when going through the code I found some pyflakes errors that I disagreed with.  Automated systems for style checking are difficult to do well.

Automated systems *are* nicer though in that we don't have to bug new developers.  I have found the 100% coverage test in PyToolz very helpful.  New contributors just fix things without me having to bother them.

I'm -0.5 on enforcing an automatic check everywhere in the repository.  I think that it's worth exploring though.  I think the right way to do this is to start with one module.

**Comment by eriknw** [comment]
FYI, there was a recent, notable change to pep8 that is opposite to what the automated tools check.  For multi-line expressions, binary operators may be at the beginning of the line:

https://hg.python.org/peps/rev/9afe77ad549b
https://www.python.org/dev/peps/pep-0008/#should-a-line-break-before-or-after-a-binary-operator

I for one welcome this change.

**Pull request merged**
