### PR TITLE
Avoid list index error in repartition_freq

### PR DESCRIPTION
**Pull request by Ced4**
avoid list index error if old divisions result in only one new division

- [x] Tests added / passed
- [x] Passes `flake8 dask`
- [ ] Fully documented, including `docs/source/changelog.rst` for all changes
      and one of the `docs/source/*-api.rst` files for new API

### CODE REVIEW

**Comment by mrocklin** [comment]
Thanks for starting this @Ced4 .  Would you be willing to make a simple test that would have failed before this change?

http://dask.pydata.org/en/latest/develop.html#test

**Comment by Ced4** [comment]
@mrocklin 
I have added a test that fails without the modification.

**Comment by mrocklin** [comment]
Looks like flake8 tests are failing: 

   dask/dataframe/core.py:3718:56: E703 statement ends with a semicolon

**Comment by mrocklin** [comment]
http://dask.pydata.org/en/latest/develop.html#style

**Comment by mrocklin** [comment]
This seems good to me otherwise

**Comment by mrocklin** [comment]
Merging.  Thanks @Ced4 !

**Pull request merged**
