### PR TITLE
Add support for Python 3.8

### LINKED ISSUE #5493: 3.8 Support
Tracking issue for adding 3.8 support.

- [ ] Add to CI (blocked by conda packages for 3.8)
- [ ] Add a 3.8 classifier to setup.py

### PR DESCRIPTION
**Pull request by jrbourbeau**
I suspect this won't pass CI at the moment because not all dependencies are built with Python 3.8 on conda-forge. Closes #5493

- [ ] Tests added / passed
- [ ] Passes `black dask` / `flake8 dask`

### CODE REVIEW

**Comment by jrbourbeau** [comment]
The default multiprocessing context on macOS was changed from `"fork"` to `"spawn"` in Python 3.8 (xref https://docs.python.org/3/whatsnew/3.8.html#multiprocessing). This impacts our multiprocessing scheduler and will break existing code.

For example, this snippet (executed as a Python script) runs fine when using multiple threads:

```python
# Run as a Python script

from dask import delayed

x = delayed(lambda x: x + 1)(1)
print(f"x = {x}")
result = x.compute(scheduler="threads")
print(f"result = {result}")
```

but raises a `RuntimeError` when using `scheduler="processes"`

```
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

(this is a common pain point for new users with the distributed scheduler)

To avoid breaking existing user code, I've updated our `dask.multiprocessing.get_context` function to continue to use `"fork"` for the default context. Although I'm happy to consider alternative approaches. It'd be great to hear what others think about this too. 


That said, the [Python 3.8 `multiprocessing` documentation](https://docs.python.org/3.8/library/multiprocessing.html#contexts-and-start-methods) says about macOS "The fork start method should be considered unsafe as it can lead to crashes of the subprocess". So we may also want to eventually not use `"fork"` by default on macOS. If that's the case, I think we'll want to raise a warning at least one release prior to making that change.

**Comment by TomAugspurger** [comment]
Thanks for the update. FWIW, I'm ok with either approach for `get_context`.

Does the doctest failure make sense to you?

```
=================================== FAILURES ===================================

__________________ [doctest] dask.bag.core.Bag.random_sample ___________________

659             element will be returned.

660         random_state : int or random.Random, optional

661             If an integer, will be used to seed a new ``random.Random`` object.

662             If provided, results in deterministic sampling.

663 

664         Examples

665         --------

666         >>> import dask.bag as db

667         >>> b = db.from_sequence(range(5))

668         >>> list(b.random_sample(0.5, 42))

Expected:

    [1, 3]

Got:

    [0, 1, 3, 4]
```

**Comment by jrbourbeau** [comment]
No, I'm able to reproduce that output locally, but am not yet sure what's causing it

**Comment by jrbourbeau** [comment]
So the `dask.bag.core.Bag.random_sample` discrepancy comes from us using tuples

https://github.com/dask/dask/blob/ffd23e87169debc0e79536200d0d1136842776ac/dask/bag/core.py#L2493-L2496

as a random seed, which is not guaranteed to be consistent across Python versions. For example, you can run:

```python
import random

random.seed(2)    # seed with integer
print("This number will be the same on different Python versions:")
print(random.random())

random.seed((1, 2))    # seed with tuple
print("This number may be different on different Python versions:")
print(random.random()
```

on Python 3.8 and 3.7 and will get identical results when an `int` is used as a seed, but different results when a `tuple` is used. This leads to confusing behavior and is actually depreciated in [Python 3.9](https://github.com/python/cpython/pull/15382). 

Seeding with an integer (e.g. using `random_state.randint(0, maxuint32)` as a seed instead of `tuple(random_state.randint(0, maxuint32) for i in range(624))`) will give us consistent results across Python versions. That said, I'm not sure why we're currently seeding with tuples, it may be for good reason. @jcrist does switching to an integer seed seem okay?

**Comment by TomAugspurger** [comment]
Using an integer as the seed seems reasonable to me. I'd recommend merging later today unless @jcrist objects.

**Comment by jcrist** [comment]
Hang on, there was a reason for this, let me track it down.

**Comment by jcrist** [comment]
Yeah, we still want to be passing around state data - otherwise we run the risk of creating identical sequences in each partition. Passing around state data decreases the probability of this happening to basically nil.

However, the existing implementation is wrong - it's not clear to me if it was always wrong (I think it was), or if Python changed it's implementation. Either way, we should be passing the tuple objects (with some tweaks) to `Random.setstate`, not passing it to the constructor.

I have a patch fixing this, mind if I push it here?

**Comment by jrbourbeau** [comment]
> I have a patch fixing this, mind if I push it here?

Go for it

**Comment by jcrist** [comment]
Pushed.

**Comment by TomAugspurger** [comment]
Thanks. There's a CI failure, but it's not obviously related to those changes. Most likely a dependency version issue?

**Comment by jrbourbeau** [comment]
A couple of the failures were from pulling in an old version of `sparse`. I've left `sparse` out of the Python 3.8 build, so those tests should be skipped now. I'm not sure how we were able to install `sparse` on 3.8 in the first place as it depends on `numba`, which isn't available on 3.8 yet. 

Looking into the `dask/dataframe/tests/test_shuffle.py::test_temporary_directory` failure now, which I'm so far not able to reproduce locally

**Comment by TomAugspurger** [comment]
Things look good here. I think we can ignore the upstream failures on this PR if you want.

**Comment by TomAugspurger** [comment]
Thanks @jrbourbeau!

**Pull request merged**
