### PR TITLE
Add dask.bag.zip

### PR DESCRIPTION
**Pull request by jcorbin**
Towards https://github.com/dask/dask/issues/1023

r @mrocklin

### CODE REVIEW

**Comment by jcorbin** [comment]
Things considered along the way and punted on to limit scope / keep it simple:
- I considered adding more general `zip(*bags, zipfunc=zip)` and `zip_longest(*bags, fillvalue=None)` however:
  - combining `*arg` and specific `key=value` args isn't supported in py2; we'd have to take a fully general **kwargs, and manually (or not) validate it
  - the use case for `zip_longest` in this case is tenuous, since if your partition lengths don't match, it's most likely due to something like a `filter` (or something even weirder); in this case you really need indexed data alignment like pandas provides, and probably don't want to zip your data together
- `db.range` really should act more like real range and take start/step; it would simply at least the example and test code for zip

I feel like there's room to add a convenience layer after this PR, something that lets you do:
```
records = dask.bag.from_something(...)
stuff = records.pluck('A')
stuff = stuff.zip(records.pluck('B'))
...
```

Essentially:
- `Bag.zip :: func(bag) Zip`
- `Zip.zip :: func(bag) Zip` // but this one appends on to the end of the growing zip, rather than creating a stair case of `(((a, b), c), d)` result tuples

**Comment by jcrist** [comment]
Overall this looks good, thanks for the PR! One caveat about this approach is that it will silently drop data if the number of partitions in each bag is equivalent, but the length of each partition is different.

```python
>>> x = db.from_sequence(range(20), npartitions=3)
>>> y = db.from_sequence(range(30), npartitions=3)
>>> z = db.zip(x, y)
>>> z.compute()
[(0, 0),
 (1, 1),
 (2, 2),
 (3, 3),
 (4, 4),
 (5, 5),
 (6, 6),
 (7, 10),
 (8, 11),
 (9, 12),
 (10, 13),
 (11, 14),
 (12, 15),
 (13, 16),
 (14, 20),
 (15, 21),
 (16, 22),
 (17, 23),
 (18, 24),
 (19, 25)]
```

There's not an easy way around this limitation though, but it might be good to but a disclaimer in the docstring.

**Comment by mrocklin** [comment]
Disclaimer in docstring sounds good.  We could also make a special `zip` function that raised an error at runtime.

**Comment by mrocklin** [comment]
In general I agree that this looks really nice.  Thank you especially for the docstring, simple code, and tests!

**Comment by jcorbin** [comment]
Updated with a disclaimer and an example of why `zip_longest` probably isn't what's wanted in this context

**Comment by jcrist** [comment]
This looks good to me. If you want, add yourself to [AUTHORS.md](https://github.com/dask/dask/blob/master/AUTHORS.md), and I'll merge. Thanks!

**Comment by jcorbin** [comment]
Added

**Comment by mrocklin** [comment]
+1

**Pull request merged**
