### PR TITLE
Make sure that delayed output operations still return lists of paths

### LINKED ISSUE #8495: Different output for to_json(compute=False) and  to_json(compute=True)
**What happened**:

I'm trying to save a dataframe with more than 1 partition to a json file. For this, I'm using an asynchronous client to compute the save later. The issue is that after waiting  the return is a list full of None objects.

**What you expected to happen**:

I expected to return the same as when using `to_json(df, path, compute=True)`

**Minimal Complete Verifiable Example**:

```python
async def save_to_json(data, path):
    client = Client.current(allow_global=False)
    files = to_json(data, path, compute=False)
    files = client.compute(files)
    return await asyncio.gather(*files)
```

**Anything else we need to know?**:

I think the issue comes from what's been returned in to_json() and that write_json_partition() doesn't return anything.

```python
parts = [
    delayed(write_json_partition)(d, outfile, kwargs)
    for outfile, d in zip(outfiles, df.to_delayed())
]
if compute:
    if compute_kwargs is None:
        compute_kwargs = dict()
    dask_compute(parts, **compute_kwargs)
    return [f.path for f in outfiles]
else:
    return parts #, [f.path for f in outfiles] This does the trick for now for me
```

I think this issue is also present in DataFrame.to_csv()

**Environment**:

- Dask version: 2021.11.2
- Python version: 3.8
- Operating System: macOS Monterey 12.1
- Install method (conda, pip, source): pip

<details>
<summary>Cluster Dump State:</summary>

</details>

### PR DESCRIPTION
**Pull request by jsignell**
- [x] Closes #8495
- [x] Tests added / passed
- [x] Passes `pre-commit run --all-files`

This is WIP because I need to add some tests still.

### CODE REVIEW

**Comment by jsignell** [comment]
@dask/maintenance for a second set of eyes.

**Comment by jsignell** [comment]
I'm planning to merge this if it passed CI.

**Comment by iortega-gradiant** [comment]
Hi Julia, 

Thanks for your effort solving this issue! I am really interested on updating my current docker image to one that includes this fix, but I see that the conda package is not getting updated since some windows/mac os tests are failing.

**Comment by martindurant** [comment]
> I see that the conda package is not getting updated since some windows/mac os tests are failing

We release regularly and are only occasionally and temporarily blocked by upstream or CI breakages :)

**Comment by jsignell** [comment]
Yeah this will be in the release 2022.01.1 that should go out tomorrow.

**Pull request merged**
