### PR TITLE
[WIP] Separate distributed and dask APIs

### PR DESCRIPTION
**Pull request by jsignell**
Related to https://github.com/dask/distributed/pull/5512 this is very WIP, but start separating them out and stop duplicating distributed API docs into dask proper.

### CODE REVIEW

**Comment by mrocklin** [comment]
I'm not sure that I agree with this direction.  If you look at Google analytics you'll find that docs.dask.org gets an order of magnitude more traffic than distributed.dask.org.  These bits of API are commonly used.  I don't think that we should split things like this.  I think instead that we should consolidate user docs for common features into one place.

**Comment by jsignell** [comment]
> I don't think that we should split things like this. I think instead that we should consolidate user docs for common features into one place.

Yeah consolating user docs is what we are trying to do. We were thinking that we should put all narrative docs in docs.dask.org and all API and internal docs for the distributed package should go in distributed. We could have a summary API page at docs.dask.org but I think the individual API pages (one for every function or Class) should live in distributed docs.

**Comment by mrocklin** [comment]
I think that it is important that the client.submit and similar APIs should
be considered part of core Dask, not some separate thing.  I think that
this should be top-level.  Are there advantages to putting the futures API
elsewhere?  We're keeping dask.array and dask.dataframe and dask.delayed
APIs on docs.dask.org, right?

**Comment by mrocklin** [comment]
Also, for historical context we used to separate things out, but no one ever found them.  That's why we started to deprecate the distributed.dask.org documentation.  People tend to go to a single website.  Putting core API (or setup API, as an other example) into a side-project's documentation ended up resulting in far fewer people understanding that functionality.

**Comment by jsignell** [comment]
ah ok that is good context. I hadn't realized that there was a concerted effort to move things off distributed.dask.org onto docs.dask.org. Maybe that is all we need to do then, just finish that work ad completely kill distributed.dask.org. I am happy with that solution. It's really the duplication that is getting to me.

**Comment by mrocklin** [comment]
Yeah, people just weren't finding it.  I'm all in favor of reducing
duplication and killing distributed.dask.org.

**Comment by jsignell** [comment]
Closing in favor of the opposite approach :)

**Pull request closed without merging**
