### PR TITLE
Use toolz.unique for possible speedup in ensure_dict

### PR DESCRIPTION
**Pull request by groutr**
When cytoolz is present, ensure_dict gets a small performance boost in one case.
Otherwise, there is no change in performance.

- [ ] Tests added / passed
- [x] Passes `black dask` / `flake8 dask`

### CODE REVIEW

**Comment by groutr** [comment]
@jrbourbeau I suspected that was the case.  However, in the utils module, I noted a function that import toolz, `dependency_depth` (though it could probably use lru_cache from functools instead of toolz.memoize).

```python
def ensure_dict(d):
    # original implementation
    if type(d) is dict:
        return d
    elif hasattr(d, "dicts"):
        result = {}
        seen = set()
        for dd in d.dicts.values():
            dd_id = id(dd)
            if dd_id not in seen:
                result.update(dd)
                seen.add(dd_id)
        return result
    return dict(d)

def ensure_dict2(d):
    # using toolz.unique
    if type(d) is dict:
        return d
    elif hasattr(d, "dicts"):
        result = {}
        for dd in unique(d.dicts.values(), key=id):
            result.update(dd)
        return result
    return dict(d)
    
def ensure_dict3(d):
    # using toolz.merge and toolz.unique
    if type(d) is dict:
        return d
    elif hasattr(d, "dicts"):
        return merge(unique(d.dicts.values(), key=id))
    return dict(d)
```

With a graph that has 42 values in `dicts.values()`.
```
ensure_dict
168 µs ± 5.94 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
ensure_dict2 (with toolz.unique)
167 µs ± 3.51 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
ensure_dict3 (with toolz.merge and toolz.unique)
165 µs ± 1.74 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)

ensure_dict2 (with cytoolz.unique)
160 µs ± 2.98 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
ensure_dict3 (with cytoolz.merge and cytoolz.unique)
151 µs ± 569 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```

Perhaps small performance gain isn't worth the trouble of gaining a dependency on toolz.  In that case, I suggest refactoring the function so that the user at least has the option of substituting cytoolz functions. For example
```python
from dask import utils
from cytoolz import unique, merge
utils.unique = cytoolz.unique
utils.merge = cytoolz.merge
```
If `ensure_dict3` form is used, then user can use accelerated unique and merge functions.

**Comment by jrbourbeau** [comment]
Thanks for providing benchmarks for different implementations of `ensure_dict`! I suspect most users won't manually set the `utils.unique` or `utils.merge` attributes. To make the speedup more broadly available to users, I'd prefer to do something like:

```python
try:
    from cytoolz import merge, unique
except ImportError:
    def merge():
        ...
    
    def unique():
        ...
```

That said, it's not clear to me that the added code complexity is worth the relatively small performance gain. Out of curiosity, does your use case significantly benefit from using the `cytoolz` implementations? 

> I noted a function that import toolz, dependency_depth (though it could probably use lru_cache from functools instead of toolz.memoize)

Good catch. I agree that could be updated to use `functools.lru_cache` instead

**Comment by groutr** [comment]
@jrbourbeau submitted #5978 to remove the toolz.memoize usage.

Regarding ensure_dict, I thought we were trying to avoid the usage of toolz/cytoolz. I'm not super attached to these changes and agree that if the payoff doesn't cross some threshold, then probably not worth merging.  In my mind, the payoff is:
1. Easier to understand code.  `merge(unique(d.dicts.values(), key=id))` is pretty clear as to what is happening.
2. By expressing it in this way, faster `merge` and `unique` functions could yield a speedup.  `ensure_dict` is called in a loop a couple of places in dask and is always the first step of any optimization. My intuition (which might be mistaken) is that this function probably gets called a lot. A small performance increase per call could yield a larger cumulative performance benefit.  My only use case only shows a small performance benefit.

I felt that these changes would be an overall improvement, but if benefits aren't clear enough, I will not develop this PR further. Perhaps better set changes would be to optionally import cytoolz where ever toolz is already being imported.  This seems to be done in some places, but not in others.

**Comment by eriknw** [comment]
Just a reminder that `toolz` installs `tlz` as well.  `tlz` looks just like `toolz`, but imports from `cytoolz` if available.  This negates the need for `try-except` around `cytoolz`.

**Comment by groutr** [comment]
@eriknw thanks for pointing that out. Does dask depend on a new enough version of toolz to make use of that?  `tlz` seems to be in toolz 0.8, but the min version that dask requires is 0.7.3. Perhaps the min version could be bumped to 0.8 (released almost 4 yrs ago)? That would also make the version checking in dask/bag/core unnecessary.

**Comment by TomAugspurger** [comment]
@groutr can you provide updated benchmarks with the new implementation.

Bumping to toolz>=0.8 and import tlz sounds fine to me, but that should likely be done separately.

**Comment by groutr** [comment]
@TomAugspurger I agree that using tlz should be done in another PR.

I will work on some more detailed benchmarks.

**Comment by jakirkham** [comment]
> Just a reminder that `toolz` installs `tlz` as well. `tlz` looks just like `toolz`, but imports from `cytoolz` if available. This negates the need for `try-except` around `cytoolz`.

I did not even know this! 🤯 Thanks Eric! 😄

**Comment by mrocklin** [comment]
Was this showing up in performance profiles somewhere?  I hesitate to start rewriting toolz code inside of Dask if it's not improving performance of full workloads.  

It's really easy to start microbenchmarking things and improving individual functions without actually improving user experience.  I think that profiling and tuning are really important, but I think that we need to start with more wholesale workloads.  If folks don't mind, I'd prefer to close this PR.

**Comment by jrbourbeau** [comment]
Closing this PR for now. @groutr if you have a workload where `ensure_dict` is becoming a performance bottleneck, please feel free to reopen

**Pull request closed without merging**
