### PR TITLE
Don't optimize in to_parquet .to_delayed

### LINKED ISSUE #6758: Unable to specify worker resources with .to_parquet
**What happened**: Distributed scheduler is ignoring required worker resources when `to_parquet` is part of the compute graph.

**What you expected to happen**: Worker resources should be respected, especially when specifying `optimize_graph=False`

**Minimal Complete Verifiable Example**:

```python
# setup a scheduler with 2 or more workers, one of them having resource "GPU=1"

from dask import dataframe as dd
from dask import core
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.rand(50,3), columns=['a', 'b', 'c'])
ddf = dd.from_pandas(df, npartitions=5)

def _op(df: pd.DataFrame):
    import time
    time.sleep(5)
    return df

r1 = ddf.map_partitions(_op, meta=dd.utils.make_meta([
    ('a', 'f'),
    ('b', 'f'),
    ('c', 'f')]))
r2 = r1.to_parquet(r"D:\Temp\dd.parquet", compute=False)

r2.compute(resources={tuple(core.flatten(r1.__dask_keys__())): {'GPU': 1}}, optimize_graph=False)
```

**Anything else we need to know?**: This doesn't work no matter what `optimize_graph` in `compute` and `write_index` in `to_parquet` are set to. I'm pretty sure this is because `to_parquet` introduces additional steps (`reset_index`, `rename`, etc.).

I'm not sure if this is desired behavior. What is the correct way to specify resource requirements in this setting?

**Environment**:

- Dask version: 2.21.0
- Python version: 3.8.4
- Operating System: Win10
- Install method (conda, pip, source): pip

### PR DESCRIPTION
**Pull request by jsignell**
- [ ] Tests added / passed
- [x] Passes `black dask` / `flake8 dask`
- [x] closes  #6758, 6784

### CODE REVIEW

**Review by rjzamora — APPROVED** [review]
Thanks for this change @jsignell - Do you know if we need to add anything [in the schema-inference code](https://github.com/dask/dask/blob/f937c06a2ee1b92515714365ea945ca7b4d0e945/dask/dataframe/io/parquet/arrow.py#L861)?  Also, do you think it is possible to test this change somehow (not sure if this makes sense)?

**Comment by jsignell** [comment]
> Do you know if we need to add anything in the schema-inference code?

I think it seems ok as is, but maybe @chrisroat can confirm?

> do you think it is possible to test this change?

Yes. I am thinking about how to do this. At the least we can run one of the MREs from the linked issues or check the dask graph keys.

**Comment by mrocklin** [comment]
Does this mean that if the user calls `to_parquet` then they won't get any of the dataframe optimizations?  For example, if I did the following:

```python
df = dd.read_parquet(path)
df = df[["a", "b", "c"]]  # get only a few columns
df.to_parquet(...)
```

Would I no longer benefit from the column selection optimization?

**Comment by jsignell** [comment]
> Does this mean that if the user calls to_parquet then they won't get any of the dataframe optimizations?

Dang it. It would appear so. Although it'd be nice if there were a failing test to prove it. My current thinking is that users should be able to toggle `optimize_graph` in the `compute_kwargs` of `to_parquet`, but that isn't terribly discoverable, so if someone has a better idea that'd be great :)

**Comment by mrocklin** [comment]
dask.config.set ?

But ideally we fix whatever the underlying problem is.  I wouldn't want
users to ever *want *to turn off optimizations.

**Comment by jsignell** [comment]
> I wouldn't want users to ever *want* to turn off optimizations.

I think that if we seem to allow it, it should be thorough.

**Comment by rjzamora** [comment]
> Would I no longer benefit from the column selection optimization?

Ah - This makes sense :(

> ...but that isn't terribly discoverable, so if someone has a better idea that'd be great

I agree that the `optimize_graph` kwarg feels a bit messy.  It *may* make the most sense to avoid `to_delayed` altogether.  However, this may require us to move away from the use of keyowrd args in `write_partition`.  I can experiment with this a bit, but I would rather not change the `Engine` API if possible.

**Comment by jsignell** [comment]
Closing in favor of #6801

**Pull request closed without merging**
