### PR TITLE
Fix mimesis API >=13.1.0 - use random.randint

### LINKED ISSUE #10858: Tests for dummy data generation failing
Looks like there are some tests failing for the dummy data generation

https://dask.github.io/dask/test_short_report.html

https://github.com/dask/dask/actions/runs/7650514559/job/20846717103

### PR DESCRIPTION
**Pull request by milesgranger**
- [x] Closes #10858 
- [x] Tests added / passed
- [x] Passes `pre-commit run --all-files`

https://mimesis.name/en/master/changelog.html#version-13-1-0

### CODE REVIEW

**Review by jrbourbeau — COMMENTED** [review]
Thanks @milesgranger. Would you mind updating the minimum version listed for `mimesis` in https://docs.dask.org/en/stable/install.html#optional-dependencies? Otherwise, this LGTM

**Comment by jrbourbeau** [comment]
Oh, here too https://github.com/dask/dask/blob/c472a8a649b038f1f53b9d01dc07051a9a3a026b/continuous_integration/environment-mindeps-optional.yaml#L35

**Comment by milesgranger** [comment]
Thanks @jrbourbeau! 
I'm slightly confused though, why do we need to adjust the minimum? We're not using any new API, only changed to use the `random.randint` provider which has been available since the minimum version.

**Review by jrbourbeau — APPROVED** [review]
Ah, nevermind then. I thought this was a new API. Thanks again @milesgranger

**Pull request merged**
