### PR TITLE
Cleanup remote tracebacks

### PR DESCRIPTION
**Pull request by j-bennet**
Adds a utility function `shorten_traceback`, and wraps `sys.excepthook` to apply it to unhandled exceptions.

The behavior of the function is controlled by several settings:

* `admin.traceback.shorten`
* `admin.traceback.allowlist`
* `admin.traceback.skiplist`

If `admin.traceback.shorten: true`,  and any of the stack frames match a pattern listed in `admin.traceback.allowlist`, stack trace is shortened. Frames that match a pattern listed in `admin.traceback.skiplist` are omitted. The method always preserves the first and last stack frame though.

For `IPython`, instead of `sys.excepthook`,  a custom exception handler is provided.

The second part - adding worker info to the remote exception - is implemented in https://github.com/dask/distributed/pull/7847.

Issue: https://github.com/dask/distributed/issues/4880.

- [x] Tests added / passed
- [x] Passes `pre-commit run --all-files`

As discussed with @crusaderky.

### CODE REVIEW

**Comment by j-bennet** [comment]
@crusaderky Finally got the test passing. Lesson learned: never expect ipython to behave the same on different envs. This is now ready for review.

One more thing I was thinking about adding to this PR: exposing a function to install the `excepthook`, instead of modifying it without the user participation. It might be an overkill. What do you think?

**Review by crusaderky — APPROVED** [review]
@j-bennet see my review commit

**Comment by crusaderky** [comment]
>  exposing a function to install the excepthook, instead of modifying it without the user participation. It might be an overkill. What do you think?

I don't think I follow. What function are you referring to?

**Comment by j-bennet** [comment]
> @j-bennet see my review commit Merging as soon as you confirm you're happy with my changes

`when` and `what` sounds fine.

> I don't think I follow. What function are you referring to?

In the PR at the current state, as soon as the user imports something from `dask`, `sys.excepthook` is wrapped, even if the wrapper does nothing when `admin.traceback.shorten` is `false`.

Alternatively, wrapping excepthook could be something that's triggered by the user, by calling a method, let's say, `dask.instal_hooks`.

**Comment by crusaderky** [comment]
> In the PR at the current state, as soon as the user imports something from `dask`, `sys.excepthook` is wrapped, even if the wrapper does nothing when `admin.traceback.shorten` is `false`.
> 
> Alternatively, wrapping excepthook could be something that's triggered by the user, by calling a method, let's say, `dask.instal_hooks`.

I see your reasoning, but I feel that if we added a completely different API it would make things worse for the UX rather than better.
This (and quite a few other situations) could potentially resolved by being able to install callbacks in `dask.config.set`. Definitely out of scope though.

**Comment by crusaderky** [comment]
Thank you!

**Pull request merged**
