### PR TITLE
Add swapaxes to dask array

### PR DESCRIPTION
**Pull request by mrocklin**

### CODE REVIEW

**Comment by mrocklin** [comment]
Merging later today if no comments

**Comment by shoyer** [comment]
Just a note that I usually prefer `moveaxis` to swapaxis or rollaxis. I'd suggest making a dask.array version, but `numpy.moveaxis` should already work because it's implemented with duck typing.

**Comment by shoyer** [comment]
`np.transpose` defers to the `transpose` method, if available.

I'm pretty sure I tested `moveaxis` on dask arrays when I wrote it.

**Comment by shoyer** [comment]
Anyways, I have no objections here

**Comment by mrocklin** [comment]
Oh cool.  Didn't realize that NumPy duck-typed on `.transpose`

**Pull request merged**
