### PR TITLE
Timedelta deterministic hashing

### LINKED ISSUE #9210: datetime.timedelta deterministic hashing
What happened:

It seams that python datetime.timedelta arguments in a pure delayed are generating inconsistant dask keys.

Minimal Complete Verifiable Example:

```python
import dask
import datetime

@dask.delayed(pure=True):
def test(obj):
    return obj

dt = datetime.timedelta(days=1)
assert test(dt).key == test(dt).key
```

Environment:

Dask version: 2022.6.0
Python version: 3.9
Operating System: Linux (Red Hat 7)
Install method (conda, pip, source): pip

Fix proposal:

Add date.timedelta in the list of types where identity is applied (https://github.com/dask/dask/pull/7836/files)

I can provide a PR

### PR DESCRIPTION
**Pull request by faulaire**
- [x] Closes #9210
- [ ] Tests added / passed
- [ ] Passes `pre-commit run --all-files`

### CODE REVIEW

**Review by jsignell — APPROVED** [review]
This seems reasonable to me! Thanks for the PR.

**Comment by jsignell** [comment]
I just merged main into your branch to fix the merge conflict.

**Comment by jsignell** [comment]
rerun tests

**Comment by faulaire** [comment]
Thanks !

**Pull request merged**
