### PR TITLE
DEV: Add asv benchmarks

### PR DESCRIPTION
**Pull request by TomAugspurger**
Closes https://github.com/dask/dask/issues/1733

This is the bare skeleton. A couple things

- Are we OK with having the benchmarks folder in the repo? Some projects (e.g. [astropy](https://github.com/astropy/astropy-benchmarks)) place theirs in a separate repo. Pandas has it in the `pandas` repo, which I think is nice for writing new benchmarks and testing them as part of a PR
- I've used conda as the default for the benchmark configuration, but we can also use `virtualenv`.

To test this out, you would clone this branch, install the new deps (`asv`), and run `asv run`, which should run the latest commit.

### CODE REVIEW

**Comment by TomAugspurger** [comment]
One more thing, it'd be good to establish consistent naming conventions for the timing methods, as the `asv run` methods take a `-b` flag for filtering benchmarks by name.

**Comment by mrocklin** [comment]
First attempt:

```
· Creating environments...........
·· Error running /home/mrocklin/Software/anaconda/bin/conda install -p /home/mrocklin/workspace/dask/.asv/env/7235d23482054cba6410ca9045e5d891 --yes cloudpickle numpy zarr distributed partd s3fs pandas toolz
             STDOUT -------->
             Fetching package metadata .......
             Solving package specifications: .
             STDERR -------->
             
             
             PackageNotFoundError: Package not found: '' Package missing in current linux-64 channels: 
               - zarr
             
             You can search for packages on anaconda.org with
             
                 anaconda search -t conda zarr
             
             

·· Failure creating environment for conda-py2.7-cloudpickle-distributed-numpy-pandas-partd-s3fs-toolz-zarrTraceback (most recent call last):
  File "/home/mrocklin/Software/anaconda/bin/asv", line 11, in <module>
    sys.exit(main())
  File "/home/mrocklin/Software/anaconda/lib/python3.4/site-packages/asv/main.py", line 38, in main
    result = args.func(args)
  File "/home/mrocklin/Software/anaconda/lib/python3.4/site-packages/asv/commands/__init__.py", line 48, in run_from_args
    return cls.run_from_conf_args(conf, args)
  File "/home/mrocklin/Software/anaconda/lib/python3.4/site-packages/asv/commands/continuous.py", line 51, in run_from_conf_args
    env_spec=args.env_spec, **kwargs
  File "/home/mrocklin/Software/anaconda/lib/python3.4/site-packages/asv/commands/continuous.py", line 75, in run
    _returns=run_objs, _machine_file=_machine_file)
  File "/home/mrocklin/Software/anaconda/lib/python3.4/site-packages/asv/commands/run.py", line 168, in run
    Setup.perform_setup(environments, parallel=parallel)
  File "/home/mrocklin/Software/anaconda/lib/python3.4/site-packages/asv/commands/setup.py", line 78, in perform_setup
    list(map(_create, environments))
  File "/home/mrocklin/Software/anaconda/lib/python3.4/site-packages/asv/commands/setup.py", line 20, in _create
    env.create()
  File "/home/mrocklin/Software/anaconda/lib/python3.4/site-packages/asv/environment.py", line 455, in create
    self._setup()
  File "/home/mrocklin/Software/anaconda/lib/python3.4/site-packages/asv/plugins/conda.py", line 96, in _setup
    self._install_requirements(conda)
  File "/home/mrocklin/Software/anaconda/lib/python3.4/site-packages/asv/plugins/conda.py", line 124, in _install_requirements
    util.check_output([conda] + conda_cmd + conda_args)
  File "/home/mrocklin/Software/anaconda/lib/python3.4/site-packages/asv/util.py", line 512, in check_output
    raise ProcessError(args, retcode, stdout, stderr)
asv.util.ProcessError: Command '/home/mrocklin/Software/anaconda/bin/conda install -p /home/mrocklin/workspace/dask/.asv/env/7235d23482054cba6410ca9045e5d891 --yes cloudpickle numpy zarr distributed partd s3fs pandas toolz' returned non-zero exit status 1
```


My guess is that this relies on the conda-forge channel being included by default.

**Comment by mrocklin** [comment]
@jcrist @eriknw this seems like the sort of thing you might enjoy pushing on at odd intervals between other low-concentration work activities :)

**Comment by mrocklin** [comment]
The error I experienced above may also be due to an odd configuration in my local conda environment.

**Comment by pitrou** [comment]
I would recommend a separate repository for benchmarks. It helps run a new version of the benchmarks against old versions of the codebase.

**Comment by mrocklin** [comment]
Related, I'm also curious about where to put dask/distributed benchmarks.  The separate repository would solve that problem.  I agree that it *is* convenient to keep things in one repository though.

**Comment by pitrou** [comment]
Some thoughts about this (not necessarily prescriptive):
* The source tree may have some nesting to facilitate categorization (e.g. `benchmarks/array/...`, `benchmarks/core/...`, etc.)
* Unfortunately, some kinds of optimizations may need large datasets in order to be stressed. I wonder if there's a way to tag some benchmarks as "slow", so as to only run them on a CI machine.

**Comment by pitrou** [comment]
Yes, I think a separate repository could hold all dask-related benchmarks (dask, distributed, zict...).

**Comment by TomAugspurger** [comment]
Sorry about the zarr import, that's removed now.

> It helps run a new version of the benchmarks against old versions of the codebase.

I'm not quite sure how, but I think `asv` stores all the benchmarks in memory or something and then checks out each revision of the codebase. However it's done, the *current* version of the benchmark is run on each revision.

Anyway, it seems like having a dedicated benchmark repo is preferable. This would also be nice because if we want something like http://www.astropy.org/astropy-benchmarks/, we'd need a dedicated physical machine. I don't think running `asv` on a CI machine is recommended because the varying load and physical hardware would affect the timings. I'll start a `dask/benchmarks` repo, if that sounds good to everyone.

**Comment by TomAugspurger** [comment]
Opened up https://github.com/dask/dask-benchmarks

One note or warning, if the path to your `dask-benchmarks` repo is too long, you could run into https://github.com/conda/conda-build/pull/877 when creating the environments for the repo.

I'll follow up over the next couple days adding benchmarks, just taking examples from the issue tracker.

**Pull request closed without merging**
