### PR TITLE
WIP: Make bzip2 compressed files seekable

### PR DESCRIPTION
**Pull request by xhochy**
- [x] Tests added / passed
- [x] Passes `flake8 dask`
- [x] Fully documented, including `docs/source/changelog.rst` for all changes
      and one of the `docs/source/*-api.rst` files for new API

### CODE REVIEW

**Comment by mrocklin** [comment]
Are BZ2File objects efficiently seekable?

**Comment by mrocklin** [comment]
It looks like this is failing some compression checks

**Comment by xhochy** [comment]
BZ2File should at least by theory be efficiently seekable (in contrast to gzip). In practice this code worked on a very large CSV for me. 

I will look into the test in more depth later today.

**Comment by xhochy** [comment]
@mrocklin Can you suggest some tooling so I can find out if the seeking is done as expected?

**Comment by mrocklin** [comment]
For seek performance I would probably just open a large bz2-compressed file and compare the time it takes to seek to byte position 1 and the time it takes to seek to some much larger byte position.  We would expect them to be about the same.  With a non-seekable compression format like gzip the time it takes to seek grows with the byte position (seek works, but just scans through the file linearly).

It looks like most tests are failing due to style issues (run `flake8 dask`).  The last test run on travis-ci is failing due to, I think, unrelated issues in pandas master.

**Comment by xhochy** [comment]
Sadly not the results I was looking for:

```
In [6]: %%time
   ...: f.seek(0)
   ...:
CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 293 µs
Out[6]: 0

In [7]: %%time
   ...: f.seek(1024**2)
   ...:
CPU times: user 36 ms, sys: 0 ns, total: 36 ms
Wall time: 38.8 ms
Out[7]: 1048576

In [8]: %%time
   ...: f.seek(4 * 1024**2)
   ...:
CPU times: user 84 ms, sys: 108 ms, total: 192 ms
Wall time: 207 ms
Out[8]: 4194304

In [9]: %%time
    ...: f.seek(512 * 1024**2)
    ...:
CPU times: user 15.8 s, sys: 10.4 s, total: 26.2 s
Wall time: 26.9 s
Out[9]: 536870912
```

**Comment by mrocklin** [comment]
I don't know much about the bz2 format, but in other formats that are seekable I've found that you need to compress the file in a certain way.  Perhaps the same is true here?

**Comment by xhochy** [comment]
No, bz2 compresses by default in blocks of a certain size (I think I read 11MiB somewhere). You only would need to decompress the blocks you actually access.

That is why all Hadoop tutorials urge you to bz2-compress the large text files.

**Comment by xhochy** [comment]
The main problem here is that the `bz2` module decompresses all intermediate blocks as far as I understood the code. Data is immediately thrown away but still decompressed.

**Comment by mrocklin** [comment]
In that case I would consider raising an issue with CPython.  It seems like this would need to be fixed there. Or perhaps there is a third-party implementation somewhere on PyPI?

**Comment by xhochy** [comment]
I could not find a third-party module that supports seeks but there is a package that backports the upstream improvements: https://pypi.python.org/pypi/bz2file

**Comment by xhochy** [comment]
Besides the seeking problem, I am a bit concerned with 

```
dask/bag/tests/test_text.py::test_read_text[bz2-None-ascii0] continuous_integration/travis/run_tests.sh: line 14:  3286 Segmentation fault      (core dumped) coverage run `which py.test` dask --runslow --doctest-modules --verbose $XTRATESTARGS
```

I will mark this PR as WIP as it will take some time to go more in-depth into these problems :(

**Comment by mrocklin** [comment]
cc @pitrou who might have thoughts here

**Comment by pitrou** [comment]
A quick look at the `bz2` module suggests that indeed seeking is implemented by decompressing all the data up to the seek point.

**Comment by OlivierNV** [comment]
IIRC, one of the fatal flaws in BZIP2 for seeking is that it compresses independent blocks of up to 900KB but that is *after* a RLE pass on the input, and the original uncompressed block size is not stored in the compressed file, so one has to fully decompress the block in order to find out its uncompressed size.

**Comment by jrbourbeau** [comment]
@xhochy just wanted to check in, is it safe to close this PR or move the work elsewhere? It looks like we no longer have a `dask/bytes/compression.py` module (perhaps that was moved to fsspec?)

**Comment by xhochy** [comment]
This can be closed.

**Pull request closed without merging**
