### PR TITLE
Return ``da.Array`` rather than ``dd.Series`` for non-ufunc elementwise functions on ``dd.Series``

### PR DESCRIPTION
**Pull request by jsignell**
This seems to work fine, but it does change the output type of ufuncs. I think this is better than it was originally and this code is very old, but I'd appreciate a second set of eyes. Maybe someone from @dask/array

### CODE REVIEW

**Comment by jsignell** [comment]
@jorisvandenbossche or @rjzamora would either of you be able to sanity check this?

**Comment by jakirkham** [comment]
Have we tested this on older versions of NumPy (like [1.18]( https://github.com/dask/dask/blob/e790aab16e3285e9d4a0ad9c0f0955217029f321/setup.py#L15 ))?

**Comment by jsignell** [comment]
> Have we tested this on older versions of NumPy (like [1.18](https://github.com/dask/dask/blob/e790aab16e3285e9d4a0ad9c0f0955217029f321/setup.py#L15))?

That's what runs on the python 3.7 tests https://github.com/dask/dask/runs/4781480587?check_suite_focus=true for instance

**Comment by jorisvandenbossche** [comment]
> but it does change the output type of ufuncs.

Do you mean that `da.ufunc(dd.Series)` now gives a da.Array instead of preserving the dd.Series? 
(it seems to me that dd.Series is the "better" result type)

**Comment by jsignell** [comment]
> > but it does change the output type of ufuncs.
> 
> Do you mean that `da.ufunc(dd.Series)` now gives a da.Array instead of preserving the dd.Series? (it seems to me that dd.Series is the "better" result type)

That is what I mean, it seems like with this PR we come a lot closer to matching the numpy + pandas object behavior:

```python
import numpy as np
import pandas as pd
import dask.array as da
import dask.dataframe as dd

s = pd.Series(np.random.randn(100))
ds = dd.from_pandas(s, 3)

da.sin(ds)  # dd.Series
np.sin(s)  # pd.Series
da.real(ds)  # da.Array
np.real(s)  # np.Array
```

**Comment by jorisvandenbossche** [comment]
The `__array_wrap__` method was added back, but deprecated (https://github.com/pandas-dev/pandas/pull/45451/). That should give you some more time to get this fixed (i.e. the pandas release tomorrow won't yet break dask directly).

>  it seems like with this PR we come a lot closer to matching the numpy + pandas object behavior:

Isn't it the other way around, i.e. further from numpy/pandas' behaviour?

With the numpy / pandas combo, calling a numpy ufunc on a pandas Series returns a pandas Series (`np.ufunc(pd.Series) -> pd.Series`).  
And with dask, before this PR, calling a dask.array ufunc on a dask Series also preserved the dask Series (`da.ufunc(dd.Series) -> dd.Series`).

While you mention that with this PR it will start returning a `da.Array` instead of `dd.Series`, so which AFAIU is less consistent with pandas.

**Comment by jsignell** [comment]
Sorry @jorisvandenbossche I think I'm missing something, can you provide an example that gives surprising behavior? The example that I gave above seems to match the numpy on pandas behavior.

**Comment by jorisvandenbossche** [comment]
Ah, sorry, I misinterpreted your code snippet in https://github.com/dask/dask/pull/8558#issuecomment-1016560288. I wasn't looking carefully enough to notice the difference between `np.sin` return types and `np.real` return types. 
And the cause of my confusion is that `np.sin` is a ufunc, and `np.real` is not a ufunc.

So just to be very explicit, the following wasn't actually a correct statement:

> > > but it does change the output type of ufuncs.
> > 
> > 
> > Do you mean that `da.ufunc(dd.Series)` now gives a da.Array instead of preserving the dd.Series? (it seems to me that dd.Series is the "better" result type)
> 
> That is what I mean

So for _ufuncs_ the output did *not* change (according to the code snippet in https://github.com/dask/dask/pull/8558#issuecomment-1016560288, the ufunc `da.sin` still returns a dd.Series). 
But it is for the non-ufunc numpy functions that the output changed. Previously, dask made them preserve the Series class as well, while numpy doesn't actually do that with pandas.Series.

So yes, that indeed seems to bring the behaviour closer to numpy/pandas.

**Comment by jsignell** [comment]
Ah sorry for the confusion @jorisvandenbossche I don't know why I thought those were all ufuncs :upside_down_face:

**Comment by bryanwweber** [comment]
@jsignell Does this PR need a review? Do you have a suggestion for someone to do that?

**Comment by jsignell** [comment]
This PR needs a decision more than it needs review. I'll add a deprecation cycle and then it'll be ready for review.

**Comment by jsignell** [comment]
grrr it's hard to deprecate this in a way that is at all usable. I'll think some more about it unless anyone else has ideas.

**Comment by jsignell** [comment]
@ncclementi in case you are looking into "test upstream" failures this resolves 12 or so, but it is kind of hard to implement in a backwards compatible way.

**Comment by ncclementi** [comment]
@jsignell Thanks for the heads up, it looks like there are not many left. I think if we find a solution to https://github.com/dask/dask/issues/8722#issuecomment-1040734933 that should solve all upstream problems.

**Comment by jsignell** [comment]
I talked with @jcrist and we agreed that since the previous behavior was really more of a bug than anything else, we think it's ok to merge this without a deprecation.

**Comment by jsignell** [comment]
I'll try kicking off ci later when github is healthier

**Comment by jakirkham** [comment]
cc @galipremsagar

**Comment by jsignell** [comment]
I'm planning on merging this when tests pass.

**Pull request merged**
