### PR TITLE
Cleanup and fortify where tests

### PR DESCRIPTION
**Pull request by jakirkham**
* Try using different typed arrays in `where` (for type promotion).
* Loop over possible conditions and second arrays.

### CODE REVIEW

**Comment by mrocklin** [comment]
Looks like there is a dtype issue with older versions of numpy.  I would just skip the test on older versions of numpy.  If you feel like asking "should we stop supporting these versions of numpy" then I think we should raise an issue for discussion.

**Comment by jakirkham** [comment]
> Looks like there is a dtype issue with older versions of numpy.

Yeah basically `randint` didn't support the `dtype` argument until NumPy 1.11. That said, it is a simple matter to call `astype` on the test data after the fact. So have changed this in the last commit. This works ok for me locally when testing against NumPy 1.10 and Python 3.4. Will see how the CIs do.

> If you feel like asking "should we stop supporting these versions of numpy" then I think we should raise an issue for discussion.

We definitely should be having this discussion. Especially with NumPy 1.13 around the corner. That said, I don't think this is a big enough problem to justify raising that issue.

**Comment by jakirkham** [comment]
It seems to be working however the Python 2.7 build appears to have timed out. Could someone please restart it?

**Comment by mrocklin** [comment]
Ah, I've been seeing some shuffle test failing in windows builds recently.  I was glad to see which one it was here.  Restarted, thanks for the ping.

**Comment by jakirkham** [comment]
Glad it helped. Thanks.

**Pull request merged**
