### PR TITLE
Support literals in top and atop

### PR DESCRIPTION
**Pull request by mrocklin**
We use a special index value of `None` to imply that a value should be treated as a literal.

```python
>>> top(add, 'z', 'i', 'x', 'i', 100, None,  numblocks={'x': (2,)})  # doctest: +SKIP
{('z', 0): (add, ('x', 0), 100),
 ('z', 1): (add, ('x', 1), 100)}
```

### CODE REVIEW

**Comment by mrocklin** [comment]
cc @jcrist @jakirkham

**Comment by jakirkham** [comment]
Just so I understand correctly, literals here means a scalar that is broadcasted or is there something more that is going on?

**Comment by mrocklin** [comment]
Yes, something that should be placed into the task graph without modification, though in this case you're right that "scalar" probably does make more sense (especially considering that these could be delayed objects, which are not literals).

**Comment by jakirkham** [comment]
Thanks for clarifying.

`None` seems perfectly reasonable in this case. Though I guess an empty string could be considered as well. Any thoughts on this? No preference from me.

**Comment by mrocklin** [comment]
Empty string would already be used for a zero-dimensional array

**Comment by jcrist** [comment]
Looks good to me. I think that `None` is a reasonable choice here.

**Comment by jakirkham** [comment]
Would it be worth including a test for [`slice(None)`]( https://github.com/dask/dask/issues/2651#issuecomment-327158852 ) as a literal?

**Comment by mrocklin** [comment]
Sure, added.

**Comment by jakirkham** [comment]
Thanks.

Nothing else from me. Though am not as familiar with this particular part of the code.

**Comment by mrocklin** [comment]
`top` and `atop` power a lot of dask.array.  They might be worth looking into at some point :)

**Comment by jakirkham** [comment]
Agreed. Have played with them some, but haven't needed to dive into the internals yet. 😄

**Pull request merged**
