### PR TITLE
Catch exceptions when attempting to load CLI entry points

### LINKED ISSUE #10379: CLI registration can fail with bad submodule
If a package registers an entry point for the CLI but the entrypoint is broken or not importable the CLI cannot work at all.

This is a little hard to create an MRE for but I seeing this with `dask-ctl` when updating `textual` to a more recent version. Ther error comes from the following line.

https://github.com/dask/dask/blob/85c99bc20abc382774cfb6e5bf5f2db76ac09378/dask/cli.py#L97

When this line is called third-party code is loaded, so we have no control over what happens. We could broadly catch exceptions here, print a warning and carry on.

### PR DESCRIPTION
**Pull request by jacobtomlinson**
- [x] Closes #10379
- [x] Tests added / passed
- [x] Passes `pre-commit run --all-files`

### CODE REVIEW

**Review by douglasdavis — APPROVED** [review]
Definitely makes sense to have this check!

**Comment by douglasdavis** [comment]
the readthedocs failure appears unreleated to this PR (I'll open another issue there- looks related a docstring update in scipy that uses a scipy-made `doi` sphinx directive) so if you have nothing else to add I think this is good to go!

**Comment by jacobtomlinson** [comment]
I intend to merge this on Monday if there are no further comments.

**Review by jrbourbeau — APPROVED** [review]
Thanks @jacobtomlinson

**Comment by jacobtomlinson** [comment]
Thanks for merging @jrbourbeau

**Pull request merged**
