### PR TITLE
add support for collect list aggregation via agg API

### PR DESCRIPTION
**Pull request by madhur-tandon**
- [x] Tests added / passed
- [x] Passes `black dask` / `flake8 dask`

Tests are yet to be added, will do so in a separate commit.
Closes https://github.com/dask/dask/issues/6602

### CODE REVIEW

**Comment by madhur-tandon** [comment]
@mrocklin @TomAugspurger This should be ready! Tests are added!

**Comment by madhur-tandon** [comment]
This also works if I use `ddf.groupby("A").agg(list)` 
(i.e. I don't choose a column and thus results of all columns are shown in that case)
instead of 
`ddf.groupby("A")["B"].agg(list)` 
(which only shows results for column B).

Let me know if I should add a test for the former case.

**Comment by madhur-tandon** [comment]
Update: Also fixed a typo from `arugment` to `argument`

**Comment by raybellwaves** [comment]
Looks there's on old typo at https://github.com/madhur-tandon/dask/blob/collect-list-aggregation/dask/dataframe/groupby.py#L671
keword -> keyword

**Comment by raybellwaves** [comment]
Probably worth dropping the doc example at https://docs.dask.org/en/latest/dataframe-groupby.html#aggregate with this moving to the code base.

**Comment by raybellwaves** [comment]
Tested the example in the docs as well

```>>> df = pd.DataFrame({'a': ['a', 'b', 'a', 'a', 'b'], 'b': [0, 1, 0, 2, 5], })
>>> ddf = dd.from_pandas(df, 2)
>>> df.groupby('a').agg(list)
           b
a           
a  [0, 0, 2]
b     [1, 5]

>>> ddf.groupby('a').agg(list).compute()
           b
a           
a  [0, 0, 2]
b     [1, 5]
```

LGTM. Thanks for working on this.

**Comment by madhur-tandon** [comment]
Thanks @raybellwaves for the suggestions.
The typo has now been fixed and docs have been edited as well.

CC: @TomAugspurger @mrocklin This is ready to merge!

**Comment by TomAugspurger** [comment]
Thanks @madhur-tandon!

**Pull request merged**
