### PR TITLE
#2017 fixed with a test.

### LINKED ISSUE #2017: Read_parquet with custom columns incorrect
If the parameter columns are not alphabetically sorted, the _meta.columns and actual DataFrame.columns differ. I noticed this when renaming columns, it mixed them up.
```
def test_read_parquet_custom_columns():
    with tmpdir() as tmp:
        tmp = str(tmp)
        data = pd.DataFrame({'i32': np.arange(1000, dtype=np.int32),
                             'f': np.arange(1000, dtype=np.float64)})
        df = dd.from_pandas(data, chunksize=50)
        df.to_parquet(tmp, write_index=False)

        columns = ['i32', 'f']
        df2 = read_parquet(tmp, index=False, columns=columns)

        assert (df2._meta.columns == np.asarray(columns)).all(), \
            'Order of columns incorrect.'
```
I will prepare a pull request with a test.

### PR DESCRIPTION
**Pull request by Talmaj**
Added reordering of the columns to meta, so that we keep the same order as we have given in the parameter ```columns```.

Fixes #2017.

### CODE REVIEW

**Comment by mrocklin** [comment]
This looks good to me.  Happy to merge.  A couple of things you could do if you wanted to bit slightly more thorough:

1.  Use `assert_eq(df2, df2)` which will also check that `df2._meta.colums` is the same as df2.compute().columns (Actually, I just checked this and we *don't* check this, but we should.  I'll add that in another PR soon, regardless it would be helpful to add the assert_eq check in this PR)
2.  Rearrange columns to be both `['f', 'i32']` and `['i32', 'f']` to ensure that we are not sensitive to alphabetical ordering

**Comment by mrocklin** [comment]
Ah, we do already check that `df._meta.columns` matches `df.compute().columns`

**Comment by mrocklin** [comment]
+1 from me.  Merging in a few hours if no further comments.  

cc @martindurant in case he wants to comment before then.

**Comment by martindurant** [comment]
Fixes #2017  (issue was not actually referenced here)

Thanks for the fix!

**Comment by jcrist** [comment]
> (issue was not actually referenced here)

Note that the "Fixes #issuenumber" needs to be in the top comment or in a commit for github to automatically close it. I've edited the original comment to add it.

**Comment by jcrist** [comment]
Merging, thanks for the fix!

**Pull request merged**
