### PR TITLE
Add some basic examples to doc strings on dask.bag all, any, count methods

### PR DESCRIPTION
**Pull request by ndanielsen**
Found the API documentation was lacking basic examples on these methods, so figured this would be helpful to others.

- [ ] Closes #xxxx
- [ ] Tests added / passed
- [ ] Passes `black dask` / `flake8 dask` / `isort dask`

### CODE REVIEW

**Comment by GenevieveBuckley** [comment]
I like these, I think it's helpful to have them here.

**Comment by quasiben** [comment]
Looks like there are still some linting issues.  If you run `black dask/bag/` that should take care of it.   We have docs on getting set up with black/pre-commit [here](https://docs.dask.org/en/latest/develop.html#code-formatting)

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by jrbourbeau** [comment]
add to allowlist

**Review by jrbourbeau — APPROVED** [review]
Thanks @ndanielsen! I merged `main` and ran our `pre-commit` hooks (hope that's okay). This looks great, will merge once CI finishes up 

Also, I noticed this is your first code contribution to this repository. Welcome!

**Comment by ndanielsen** [comment]
Thanks @jrbourbeau feels good to contribute here!

**Pull request merged**
