### PR TITLE
[WIP] Add k arg to diag

### LINKED ISSUE #2726: Dask Array's diag supporting diagonal selection
Would be nice if Dask Array's [`diag`]( http://dask.pydata.org/en/latest/array-api.html#dask.array.diag ) supported the `k` value to allow selection of the diagonal as NumPy's implementation [does]( https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.diag.html ). It seems like Dask Array's API docs suggest `diag` does support `k`, but the code does not allow for this option.

https://github.com/dask/dask/blob/f015b5f0808420bdd23f8408f5822d2f5aff8ff1/dask/array/creation.py#L413

### PR DESCRIPTION
**Pull request by TAdeJong**
This closes #2726 and reduces some code duplication by calling `da.diagonal` where applicable. This for now breaks by #5661, therefore the WIP, although I don't feel equipped or have the time to solve that issue here.

- [ ] Tests added / passed
- [x] Passes `black dask` / `flake8 dask`

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Sorry for the delay in review.

> This for now breaks by #5661 

Can you expand on that? You're saying #5661 is a blocker for fixing this? I'm looking into that a bit now.

**Comment by TAdeJong** [comment]
This reuses code from `da.diagonal` in `da.diag`. The test that fails here, fails because of the issue described in #5661, as `test_corrcoef()` calls `da.diag`, which since this pull request calls `da.diagonal`, exposing the bug described in #5661. In principle this code can be merged, except that the test now fails because of #5661. 

@TomAugspurger is that clear? Please let me know if something is still unclear

**Comment by TomAugspurger** [comment]
That makes sense, thanks. I looked into #5661, but didn't make much
progress.

**Comment by martindurant** [comment]
@TomAugspurger , were you working on ironing things out here?

**Comment by TomAugspurger** [comment]
Last I looked this is hitting an issue in another dask.array method. I'm
not currently working on it.

**Comment by TAdeJong** [comment]
For the overview: the other issue would be #5661 , which @jsignell seems to be working on.

**Comment by jcrist** [comment]
Superseded by #8689.

**Pull request closed without merging**
