### PR TITLE
Use `delayed(x).compute()` instead of `compute(*x)`

### LINKED ISSUE #1888: memory leak in to_csv
The following call to DataFrame.to_csv took more than 40 GB of memory.
```
df_generator = lambda: pd.DataFrame(np.random.randint(0,100,size=(1, 5)))
ddf = [dask.delayed(df_generator)() for i in range(5000)]
ddf = dask.dataframe.from_delayed(ddf, meta = df_generator())
ddf.to_csv(os.path.join(tempfile.mkdtemp(), 'bla*.csv'))
```

The memory is allocated before a single file is written.  By interrupting the process I assume, that the memory allocation is mostly due to the function `merge `in toolz.dicttoolz. What is going on here?

Edit: I gave it some more time to run and it peaked over 130 GB memory consumption.

### PR DESCRIPTION
**Pull request by jcrist**
Previously `compute(*args)` is used in several places to compute a list
of `Delayed` values - usually for I/O purposes. This uses the generic
`compute` function from `dask.base`. This is a generic method that
has no knowledge of `Delayed`, and instead works with the `dask`
attributes on objects. Because of this, it does unnecessary merging of
dictionaries that can be skipped by using `delayed(args).compute()`
instead. For large numbers of `Delayed` objects, this can be much
faster, and uses less memory.

Fixes #1888.

### CODE REVIEW

**Comment by jcrist** [comment]
Running this script in `foo.py` on both master and this branch:

```python
import os
import numpy as np
import pandas as pd
import dask
import dask.dataframe
from dask.diagnostics import ResourceProfiler

os.makedirs('foo2')

df_generator = lambda: pd.DataFrame(np.random.randint(0,100,size=(1, 5)))
ddf = [dask.delayed(df_generator)() for i in range(5000)]
ddf = dask.dataframe.from_delayed(ddf, meta=df_generator())
with ResourceProfiler() as rprof:
    ddf.to_csv('foo2/foo.*.csv')

peak = max(m.mem for m in rprof.results)
print("Max memory: %s MB" % peak)
```

Results:

```bash
(dask) jcrist dask $ time python foo.py
Max memory: 4056.526848 MB

real    0m17.082s
user    0m15.056s
sys     0m2.402s
(dask) jcrist dask $ git checkout fast-merge-delayed
Switched to branch 'fast-merge-delayed'
(dask) jcrist dask $ rm -r foo2/
(dask) jcrist dask $ time python foo.py
Max memory: 135.815168 MB

real    0m8.156s
user    0m6.622s
sys     0m1.497s
```

For lots of delayed values, this branch is ~twice as fast, and uses ~4% of the memory as master.

**Comment by mrocklin** [comment]
Cool.  I'm curious though, why were we using 4GB of RAM when merging 5000 dicts?  This is more expensive than I would expect?

**Comment by jcrist** [comment]
That's a good point, I'm not entirely sure. I may take a look this weekend, otherwise Monday.

**Comment by abast** [comment]
It is great to see, how fast the dask team respons to issues. Thanks!

**Comment by jcrist** [comment]
This case was merging `5000` dictionaries of length `1002`. The first 1000 tasks of each of these were shared, resulting in lots of unnecessary copies. Using `memory_profiler`, the bad line is merging of dictionaries as done in `dask.delayed.Delayed` (as suspected).

```
   167  106.941 MiB    0.000 MiB       if kwargs.get('optimize_graph', True):
   168  106.941 MiB    0.000 MiB           groups = groupby(attrgetter('_optimize'), variables)
   169 3876.188 MiB 3769.246 MiB           groups = {opt: [merge([v.dask for v in val]),
   170  118.461 MiB -3757.727 MiB                           [v._keys() for v in val]]
   171  118.461 MiB    0.000 MiB                     for opt, val in groups.items()}
```

Returning the values instead of computing, we can compute the memory usage using `sys.getsizeof`:

```python
In [11]: len(vals)
Out[11]: 5000

In [12]: dsk = vals[0].dask

In [13]: from sys import getsizeof

In [14]: getsizeof(dsk)
Out[14]: 786528

In [15]: getsizeof(dsk) * 5000 / 1e9   # in GB
Out[15]: 3.93264
```

So the memory usage adds up.

---

Because wrapping a list of delayed values in a delayed call may not be intuitive, I've also added a patch to the `compute` call to first check for a `_dasks` parameter, and use that if found. This reduces the memory usage significantly (profile of just commit 2):

```
   182  106.551 MiB    0.000 MiB       if kwargs.get('optimize_graph', True):
   183  106.551 MiB    0.000 MiB           groups = groupby(attrgetter('_optimize'), variables)
   184  106.551 MiB    0.000 MiB           groups = {opt: _extract_dask_and_keys(val)
   185  106.551 MiB    0.000 MiB                     for opt, val in groups.items()}
```

I've left the first patch in though, as there are mild performance perks of `delayed(args).compute()` instead of the generic `compute` call.

**Comment by mrocklin** [comment]
I've run into issues with large delayed computations as well.  I think I've been bound by the `unique(..., key=id)` call.  Any thoughts on occasionally performing dictionary merges?  Are there ways to do this well?

**Comment by jcrist** [comment]
> I think I've been bound by the `unique(..., key=id)` call

That surprises me, I'd expect that to be fast compared to doing the actual merges. Doing a small profile of merging 100000 lists of 3 dictionaries (one of them shared between all), this is still in the `ms` range:

```python
In [26]: dsk = {'a': 1}

In [27]: vals = [[dsk, {'b': 1}, {'c': 1}] for i in range(100000)]

In [28]: %time o = flat_unique(vals)
CPU times: user 106 ms, sys: 7.7 ms, total: 114 ms
Wall time: 114 ms

In [29]: len(o)
Out[29]: 200001
```

>  Any thoughts on occasionally performing dictionary merges? Are there ways to do this well?

Not that I can think of. In this case, all the Delayed tasks were small additions to an original large graph (the `_dasks` attribute contained 3 graphs of sizes 1000, 1, and 1, with the 1000 one shared between all). It'd be hard to do occasional merging in a smart way, as it could result in lots of unnecessary copies (as done in this case).

I'm also unsure what benefit occasional merges would give. It would reduce the number of graphs to eventually merge, and limit the constant memory overhead of each dictionary. But I'm skeptical that it would reduce the runtime significantly.

**Comment by mrocklin** [comment]
I should have raised a github issue at the time.  Perhaps I was doing something that involved quadratic calls?  Not a blocker for any of the work here, just thoughts.

**Comment by jcrist** [comment]
Perhaps. I don't doubt there are inefficiencies here.

Barring other comments, I think this should be good to go now.

**Comment by mrocklin** [comment]
+1 from me

**Pull request merged**
