### PR TITLE
[REVIEW] Prioritize getitem tasks in shuffle

### PR DESCRIPTION
**Pull request by madsbk**
This PR implements custom task prioritization of `getitem()` tasks in shuffle operations. See https://github.com/dask/dask/pull/6051 for a detailed discussion of the performance benefits.  

```python

    @staticmethod
    def __dask_distributed_annotations_unpack__(
        annotations: MutableMapping[str, Any],
        new_annotations: Optional[Mapping[str, Any]],
        keys: Iterable[Hashable],
    ) -> None:
        """Implement custom task prioritization of `getitem()` tasks.

        The scheduling policies of Dask is depth-first generally speaking, which works
        great in most cases. However, in case of shuffle, it increases the memory usage
        significantly. This is because depth-first delays the freeing of the result of
        `shuffle_group()` until the end of the shuffling.

        We address this by forcing a breadth-first scheduling of the `getitem()` tasks
        that follows the `shuffle_group()` task. This way all the `getitem()` tasks
        finish immediately and the output of shuffle_group()` can be freed before
        continuing to the next phase of the operation.

        See https://github.com/dask/dask/pull/6051 for a detailed discussion
        """
```

- [ ] Closes #6051
- [ ] Tests added / passed
- [x] Passes `black dask` / `flake8 dask` / `isort dask`

### CODE REVIEW

**Comment by mrocklin** [comment]
Is there something we can do here that would be a good test?  The implementation here with `"split-"` seems somewhat brittle to me (future devs could change that name and this functionality would stop without us knowing).  

Maybe we look at the Scheduler.transition_log and see that some set of tasks occurs before some other set of tasks?

**Comment by mrocklin** [comment]
Also, I think that doing this in unpack is fine, but I'm also curious if it would make sense to put these annotations on the Layer itself and then trust the general machinery to move those annotations up to the scheduler.  This feels somewhat less efficient, but also somewhat more general.

**Comment by madsbk** [comment]
> Is there something we can do here that would be a good test? The implementation here with `"split-"` seems somewhat brittle to me (future devs could change that name and this functionality would stop without us knowing).
> 
> Maybe we look at the Scheduler.transition_log and see that some set of tasks occurs before some other set of tasks?

I have been thinking of a more general solution but that will require some API redesign, I think. 
One idea is to make [`order()`](https://github.com/dask/dask/blob/main/dask/order.py#L85) understand annotations and prioritizes  fast-tasks such as `getitem()`. But I think it makes sense to start with this specialized approach and get some experience before redesigning the task ordering API.

**Comment by madsbk** [comment]
> Also, I think that doing this in unpack is fine, but I'm also curious if it would make sense to put these annotations on the Layer itself and then trust the general machinery to move those annotations up to the scheduler. This feels somewhat less efficient, but also somewhat more general.

Notice, before layer unpack we don't know the task keys. We could do this in `__dask_distributed_unpack__` instead of `__dask_distributed_annotations_unpack__` but I like to keep annotation specializations to the annotation method.

**Comment by mrocklin** [comment]
There is a middle ground.  We can put annotations on the layer instance.  This would be equivalent to what happens when we call 

```python
with dask.annotate(priority=...):
    ... create some layers ...
```

We can just populate the layer instance with an `annotations = {"priority": ...}` dict.  Again, this isn't as efficient (we have to pack and unpack annotations) but it does reduce the number of code paths that we use for this sort of thing.  While layers and packing are in flux it might be wise to stick to client-side / blessed API for a while.

**Comment by madsbk** [comment]
> We can just populate the layer instance with an `annotations = {"priority": ...}` dict. Again, this isn't as efficient (we have to pack and unpack annotations) but it does reduce the number of code paths that we use for this sort of thing. While layers and packing are in flux it might be wise to stick to client-side / blessed API for a while.

We only want to prioritize `getitem()` tasks, the rest of the shuffle tasks should keep there original priority. Basically, it is the Shuffle.Layer that tells the scheduler that some of it tasks needs priority.

**Comment by mrocklin** [comment]
> We only want to prioritize getitem() tasks, the rest of the shuffle tasks should keep there original priority. Basically, it is the Shuffle.Layer that tells the scheduler that some of it tasks needs priority.

Agreed.  I believe that you can put the information you placed in the unpack method directly on the Layer and that the Client will send that information up.

**Comment by madsbk** [comment]
> Agreed. I believe that you can put the information you placed in the unpack method directly on the Layer and that the Client will send that information up.

I am not sure I follow, do you suggest that we sets annotations when creating `SimpleShuffleLayer` and `ShuffleLayer` like here: https://github.com/dask/dask/blob/main/dask/dataframe/shuffle.py#L602 ?

In that case we need to use a `callable` annotation in order to avoid graph materialization, which could also work.

**Comment by mrocklin** [comment]
Yes there, or even within the layer's constructor 

> In that case we need to use a callable annotation in order to avoid graph materialization, which could also work.

My hope is that we could figure out the relevant keys without generating the entire graph.  

What is in this PR is fine too.  I just think that if we can keep this logic on the client side then it's less likely to need maintenance going forward.

**Comment by madsbk** [comment]
> My hope is that we could figure out the relevant keys without generating the entire graph.

 I will have to think about this :)

**Comment by mrocklin** [comment]
@rjzamora I'm not sure if @madsbk mentioned this to you or not, but if it was easy to generate a set of keys for shuffle layers without generating the full graph then that would make it easier for us to specify nicer priorities at the layer level to shuffles.  I would love to get this PR in, one way or another, by next release.

My hope is that you understand the shuffle system well enough to be able to quickly generate a `def keys(self)` method.  I think that if we add that then we can move the callable here directly onto the Layer instance, rather than push it into the unpack method.  

If we can't do that this week then let's punt and find a way to merge this in.

**Comment by rjzamora** [comment]
>My hope is that you understand the shuffle system well enough to be able to quickly generate a def keys(self) method.

Makes sense - I’ll look through this PR and give you my thoughts tomorrow.  There is no doubt that we can generate a set of keys without “materializing” the graph, but the algorithm will have the same complexity as _construct_graph.

**Comment by mrocklin** [comment]
Oh interesting.  I would have expected it to be fairly cheap to generate just the keys.

**Comment by rjzamora** [comment]
>Oh interesting. I would have expected it to be fairly cheap to generate just the keys.

I should say *may* have - I'll need to think about it :).

**Comment by mrocklin** [comment]
Also, we only need to generate the keys that need to have a set priority here.

**Pull request closed without merging**
