### PR TITLE
Make `preserve_index` explicit in `pyarrow_schema_dispatch`

### PR DESCRIPTION
**Pull request by hendrikmakait**
- [x] Closes https://github.com/dask/dask/pull/10500/files#r1319881063
- [x] Tests added / passed
- [x] Passes `pre-commit run --all-files`

### CODE REVIEW

**Review by rjzamora — APPROVED** [review]
Thanks @hendrikmakait ! Any chance we can address [my other comment](https://github.com/dask/dask/pull/10500#discussion_r1319887298) from #10500 here?

Otherwise, this is good.

**Comment by hendrikmakait** [comment]
> Thanks @hendrikmakait ! Any chance we can address [my other comment](https://github.com/dask/dask/pull/10500#discussion_r1319887298) from #10500 here?

Sure, we can do that here. Should we also clean up the `**kwargs` in other pyarrow-related dispatches in a follow-up?

**Comment by rjzamora** [comment]
>Should we also clean up the **kwargs in other pyarrow-related dispatches in a follow-up?

I will be supportive of any cases where we can formalize the specific/necessary arguments in the pandas dispatch functions. However, I will understand if there are still arguments you are planning to experiment with in p2p.

**Review by rjzamora — APPROVED** [review]
Thanks for the quick turnaround @hendrikmakait !

**Pull request merged**
