### PR TITLE
Raise exception when 'from_array' is given a dask array

### LINKED ISSUE #5262: `from_array` no longer detects dask arrays
## Problem

Not sure if this needs to be supported, but I had some old code that accidentally did a `da.from_array(existing_dask_arr)`. This is obviously unnecessary, but the code ran fine. Starting with dask 2.2 this no longer seems to work and will result in `map_blocks` passing a dask array to the underlying function instead of a numpy array.

## Example Code

```
import numpy as np; import dask.array as da

a = np.zeros((5, 5), dtype=np.float)
a = da.from_array(a, chunks=2)
b = da.from_array(a, chunks=2)

def test(arr): 
    print(type(arr)) 
    return arr 

print("Running a")
a.map_blocks(test, dtype=a.dtype).compute() 
print("Running b")
b.map_blocks(test, dtype=b.dtype).compute() 
```

## Output

```
Running a
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
Running b
<class 'numpy.ndarray'>
<class 'dask.array.core.Array'>
<class 'dask.array.core.Array'>
<class 'dask.array.core.Array'>
<class 'dask.array.core.Array'>
<class 'dask.array.core.Array'>
<class 'dask.array.core.Array'>
<class 'dask.array.core.Array'>
<class 'dask.array.core.Array'>
<class 'dask.array.core.Array'>
```

## Expected

```
Running a
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
Running b
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
```

### PR DESCRIPTION
**Pull request by djhoese**
Closes #5262.

- [ ] Tests added / passed
- [x] Passes `black dask` / `flake8 dask`

### CODE REVIEW

**Comment by djhoese** [comment]
@jakirkham Let me know if you want a test. I don't see any `from_array` specific tests so not sure where the best place is.

**Comment by jakirkham** [comment]
> Let me know if you want a test.

That would be great. Could you please add one in [`dask/array/tests/test_array_core.py`]( https://github.com/dask/dask/blob/281fd90c1ebdda7b3fb6d067e632368376969b6d/dask/array/tests/test_array_core.py )?

> I don't see any `from_array` specific tests so not sure where the best place is.

Hmm...that's concerning. Could you please raise an issue for this?

**Comment by djhoese** [comment]
Ah I didn't realize the tests were separated that way. I was only looking in `dask/tests`. I'm sure there are `from_array` tests in `dask/array/tests/`.

**Comment by jakirkham** [comment]
Yeah, if you search for `def test_from_array_*`, there are a few different cases tested. They are a bit scattered though.

**Comment by djhoese** [comment]
So test was added but there is one failure in `dask/array/tests/test_optimization.py:test_gh3937`. The issue is that `asarray` is given a list of dask arrays. `asarray` looks like:

```
    if isinstance(a, Array):
        return a
    elif hasattr(a, "to_dask_array"):
        return a.to_dask_array()
    elif isinstance(a, (list, tuple)) and any(isinstance(i, Array) for i in a):
        a = stack(a)
    elif not isinstance(getattr(a, "shape", None), Iterable):
        a = np.asarray(a)
    return from_array(a, chunks=a.shape, getitem=getter_inline, **kwargs)
```

This will hit the `stack` if statement which will convert everything to a dask array which it then passes to `from_array`.

**Comment by jakirkham** [comment]
Where is it calling `from_array` in `stack`?

**Comment by jakirkham** [comment]
Could we just move that `from_array` into the `else` case? I don't think any other case needs it.

**Comment by djhoese** [comment]
We could, but then `chunks`, `getitem`, and `**kwargs` are not being used.

**Comment by jakirkham** [comment]
They don't seem to be used by anything else anyways.

**Comment by jrbourbeau** [comment]
The following seems to pass tests for me locally

```diff
diff --git a/dask/array/core.py b/dask/array/core.py
index bb40549c..286dbcbc 100644
--- a/dask/array/core.py
+++ b/dask/array/core.py
@@ -3580,7 +3580,7 @@ def asarray(a, **kwargs):
     elif hasattr(a, "to_dask_array"):
         return a.to_dask_array()
     elif isinstance(a, (list, tuple)) and any(isinstance(i, Array) for i in a):
-        a = stack(a)
+        return stack(a)
     elif not isinstance(getattr(a, "shape", None), Iterable):
         a = np.asarray(a)
     return from_array(a, chunks=a.shape, getitem=getter_inline, **kwargs)
```

**Comment by jakirkham** [comment]
Yeah I think the application of `from_array` to anything other than the result of `np.asarray` here is unintentional. It's probably best for us to go ahead and clean that up now to avoid similar mistakes in the future.

**Comment by djhoese** [comment]
Sounds good. Done. Thanks @jrbourbeau.

**Comment by jakirkham** [comment]
Thanks @djhoese! 😄

**Pull request merged**
