### PR TITLE
Refactor config default search path retrieval

### PR DESCRIPTION
**Pull request by jrbourbeau**
This is _mostly_ a cleanup PR which moves the logic for how our config system determines the places to look for config YAML files into its own function which makes it easier to write tests for. 

Additionally, I noticed that we currently look in `~/.dask` for config files but state in the docs that this is deprecated and will be removed shortly. Since this notice was added ~3.5 years ago (xref https://github.com/dask/dask/pull/3432) I decided to go ahead and stop looking in `~/.dask`. This is the only functional change in this PR.

### CODE REVIEW

**Comment by jsignell** [comment]
3.5 years seems like a good definition of "shortly" :grin:

**Comment by jrbourbeau** [comment]
cc @abergou @djhoese for visibility. This is a small refactor following up on https://github.com/dask/dask/pull/8531 which should make testing a bit easier

**Comment by jrbourbeau** [comment]
Planning to merge tomorrow if there are no further comments

**Review by djhoese — APPROVED** [review]
Looks good to me. I'm starting to think we need to re-discuss the use of a package like donfig or at least switching dask's config to a class.

**Pull request merged**
