### PR TITLE
Clean up places where we inadvertently iterate over arrays

### PR DESCRIPTION
**Pull request by jsignell**
- [x] Tests added / passed
- [x] Passes `black dask` / `flake8 dask` / `isort dask`

### CODE REVIEW

**Comment by jsignell** [comment]
@dask/maintenance for a :+1: on this.

**Comment by martindurant** [comment]
👍  !! 
How did you happen across this?

**Comment by jsignell** [comment]
I tried to implement an `__iter__` that returned computed output and got some failures :)  

ref: https://github.com/dask/dask/issues/7889

**Comment by mrocklin** [comment]
This is great.  Thank you for doing this.

**Pull request merged**
