### PR TITLE
Add an example of index_col usage

### PR DESCRIPTION
**Pull request by asyd**
It's a very small PR but I guess that can help people..

### CODE REVIEW

**Comment by rth** [comment]
This is helpful. Could you please rebase?

**Comment by asyd** [comment]
Hi @rth thanks! I'm must confess I don't know if I should do something since my fork seem to be rebased by @quasiben :)

**Comment by asyd** [comment]
@quasiben np!

**Comment by quasiben** [comment]
Thanks for the doc update!

**Pull request merged**
