### PR TITLE
Fix windows ci failing

### LINKED ISSUE #4432: Windows CI tests are failing
As is demonstrated here: https://github.com/dask/dask/pull/4421

If anyone has any time to investigate this that would be very very helpful.

### PR DESCRIPTION
**Pull request by Dimplexion**
- [x] Tests added / passed
- [x] Passes `flake8 dask`

Closes #4432 

Worked around psutil not allowing pickling Process objects after version 5.5.0.

Reference: https://github.com/giampaolo/psutil/issues/1396

### CODE REVIEW

**Comment by Dimplexion** [comment]
I don't mind at all, I was actually considering fixing them when I noticed but you saved me the trouble there. It is indeed weird why they suddenly showed up now.

**Comment by mrocklin** [comment]
Merging this in.  Thank you very much for this contribution @Dimplexion .  You've made my day :)

**Comment by Dimplexion** [comment]
You are welcome, it was no trouble at all. It's really cool to contribute to such an awesome project. :)

**Comment by mrocklin** [comment]
In that case we know who to call for future windows testing issues :)

**Pull request merged**
