### PR TITLE
fix index_col duplication if index_col is type str

### LINKED ISSUE #7436: dd.from_sql_table() duplicates index with SQLAlchemy==1.4.1
When using `dd.from_sql_table(index='index_col')` (note that index is a string), the function internally duplicates the index, if it is already in columns. This is due to this code always being executed if index is of type str as columns contains sqlalchemy columns and not strings.
```python
if index_col not in columns:
        columns.append(
            table.columns[index_col] if isinstance(index_col, str) else index_col
        )
```
This was no problem so far because older versions of SQLAlchemy automatically removed this additional column. In version 1.4.1 however, the additional column gets an alias ("index_col__1") instead of being dropped. The extra column results in a meta error, if meta is specified.

To fix this, I think it should be enough to change the snippet from above to the following
```python
if index not in columns:
        columns.append(
            index
        )
```
As `index` is a sqlalchemy column.

I could test this and make a PR.

### PR DESCRIPTION
**Pull request by McToel**
As I described in #7436, using SQLAlchemy >= 1.4 makes a bug, that was unnoticed with SQLAlchemy < 1.4, dublicate the `index_col`, if `index_col` is of type `str` and already part of `columns`. This small change fixes that.

- [x] Closes #7436
- [x] Tests passed
- [x] Passes `black dask` / `flake8 dask` / `isort dask`

### CODE REVIEW

**Comment by McToel** [comment]
Is it my fault that the PR labeler fails? It raises a HttpError

**Review by jrbourbeau — COMMENTED** [review]
@McToel could you merge the current `main` branch into your branch to re-trigger CI

**Comment by QuLogic** [comment]
This fixes 13 of 14 test failures due to SQLAlchemy 1.4. The remaining failure is:
```
___________________________ test_select_from_select ____________________________
[gw0] linux -- Python 3.10.0 /usr/bin/python3
db = 'sqlite:////tmp/tmp3u834qcu.'
    def test_select_from_select(db):
        from sqlalchemy import sql
    
        s1 = sql.select([sql.column("number"), sql.column("name")]).select_from(
            sql.table("test")
        )
>       out = read_sql_table(s1, db, npartitions=2, index_col="number")
dask/dataframe/io/tests/test_sql.py:406: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
dask/dataframe/io/sql.py:115: in read_sql_table
    index = table.columns[index_col] if isinstance(index_col, str) else index_col
/usr/lib64/python3.10/site-packages/sqlalchemy/sql/selectable.py:2888: in columns
    return self.c
<string>:2: in c
    ???
/usr/lib64/python3.10/site-packages/sqlalchemy/util/deprecations.py:389: in warned
    _warn_with_version(message, version, wtype, stacklevel=3)
/usr/lib64/python3.10/site-packages/sqlalchemy/util/deprecations.py:36: in _warn_with_version
    _warnings_warn(warn, stacklevel=stacklevel + 1)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
message = SADeprecationWarning('The SelectBase.c and SelectBase.columns attributes are deprecated and will be removed in a futur... columns that this SELECT object SELECTs from, use the SelectBase.selected_columns attribute. (deprecated since: 1.4)')
category = None, stacklevel = 5
    def _warnings_warn(message, category=None, stacklevel=2):
    
        # adjust the given stacklevel to be outside of SQLAlchemy
        try:
            frame = sys._getframe(stacklevel)
        except ValueError:
            # being called from less than 3 (or given) stacklevels, weird,
            # but don't crash
            stacklevel = 0
        except:
            # _getframe() doesn't work, weird interpreter issue, weird,
            # ok, but don't crash
            stacklevel = 0
        else:
            # using __name__ here requires that we have __name__ in the
            # __globals__ of the decorated string functions we make also.
            # we generate this using {"__name__": fn.__module__}
            while frame is not None and re.match(
                r"^(?:sqlalchemy\.|alembic\.)", frame.f_globals.get("__name__", "")
            ):
                frame = frame.f_back
                stacklevel += 1
    
        if category is not None:
            warnings.warn(message, category, stacklevel=stacklevel + 1)
        else:
>           warnings.warn(message, stacklevel=stacklevel + 1)
E           sqlalchemy.exc.SADeprecationWarning: The SelectBase.c and SelectBase.columns attributes are deprecated and will be removed in a future release; these attributes implicitly create a subquery that should be explicit.  Please call SelectBase.subquery() first in order to create a subquery, which then contains this attribute.  To access the columns that this SELECT object SELECTs from, use the SelectBase.selected_columns attribute. (deprecated since: 1.4)
/usr/lib64/python3.10/site-packages/sqlalchemy/util/langhelpers.py:1660: SADeprecationWarning
```

**Comment by QuLogic** [comment]
You'll probably want to unpin `SQLAlchemy` (i.e., reverting #7405) to see that.

**Comment by McToel** [comment]
I think part of the problem is that we try to support a passing a tablename or a sql expression within the same function. SQLAlchemy 1.4 makes it different to select from a table compared to a subquery. It would probably make sense to split that up in `read_sql` and `read_sql_table`.

Still, it will be necessary to check the Version of SQLAlchemy and run different code for >=1.4 and <1.4. But this is how pandas handles it internally too.

**Comment by martindurant** [comment]
Yes, my feeling is that you will need to explicitly check the version of sqlalchemy and the type of index_col, and write separate code paths (perhaps split into helper functions).

**Comment by martindurant** [comment]
@McToel , I had a go myself at making the appropriate <1.4;>=1.4 versions of how the index and column handling should look, but I have failed so far. Were you intending to add a code branch for newer sqlalchemy here?

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by martindurant** [comment]
What is here appears to work fine, but only for sqlalchemy<1.4 (which is now pinned in the environments). You get various warnings (which become errors in the tests) from the use of `.columns` and elsewhere for latest sqlalchemy.

**Comment by jsignell** [comment]
I'd prefer to throw a clear error if sqlalchemy doesn't match requirements particularly since it's very much an extra requirement. Something straightforward like:

```python
raise ImportError("Dask requires sqlalchemy< 1.4.; you have {version}")
```

**Comment by McToel** [comment]
That would be a cleaner implementation, but it will break some code.

**Comment by jsignell** [comment]
Ok in that case, let's merge this and move forward from there. Thanks for working on this @McToel

**Pull request merged**
