### PR TITLE
Add `.__wrapped__` to constructed `Delayed` object

### LINKED ISSUE #10685: Add a `.__wrapped__` (or similar) attribute for `@dask.delayed`-decorated functions
It would be nice if the `@dask.delayed`-decorated function had an attribute that could be called to return the undecorated function. Drawing inspiration from the widely used [`functools.wraps()`](https://docs.python.org/3/library/functools.html) function, I would suggest calling it `.__wrapped__` for consistency. Having the ability to quickly strip off the decorator can be very useful for those building libraries around Dask-delayed functions. For instance, imagine a scenario where you have made a library of pre-decorated functions. If you want to use that function in another module but _not_ have it be delayed, there is currently no way to do so without copying/pasting. In practice, what you would like is something like so:

```python
from dask import delayed

@delayed
def add(a, b):
    return a+b

add.__wrapped__(1,2) # 3, not delayed
```

Note that because Delayed objects are immutable, it's not possible for someone like me to "manually" add the `.__wrapped__` attribute after the Delayed function is made.

### PR DESCRIPTION
**Pull request by Andrew-S-Rosen**
- [X] Closes #10685
- [x] Tests added / passed
- [x] Passes `pre-commit run --all-files`

Adds a `.__wrapped__` attribute to return the original object wrapped by `@dask.delayed`.

Demo:

```python
from dask import delayed

@delayed
def add(a, b):
    return a+b

add.__wrapped__(1, 2)
```

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

Admins can comment `ok to test` to allow this one PR to run or `add to allowlist` to allow all future PRs from the same author to run.

**Comment by Andrew-S-Rosen** [comment]
@hendrik, this should be ready for your review. The test I added passes, and I was able to try it out locally. The failing tests on Windows are unrelated to this PR (seen in `main`).

**Review by hendrikmakait — CHANGES_REQUESTED** [review]
@Andrew-S-Rosen: Simply forwarding the `__annotations__` unfortunately does not work here. With your change, the following happens:

```python3
import inspect
from dask import delayed

def add(a: int, b: int) -> int:
    return a

print(inspect.signature(add))
# <Signature (a: int, b: int) -> int>

print(isinstance(add(1, 2), int))
# True
# As expected, add is eagerly evaluated and returns an integer

deladd = delayed(add)
print(inspect.signature(add))
# <Signature (a: int, b: int) -> int>
# Signature of deladd matches add

print(isinstance(add(1, 2), int))
# False
# ERROR: The expected return type does not match the actual type! 

print(deladd(1, 2))
# Delayed('add-7892a429-a034-4821-9e5e-ad482e18f217')
# deladd returns a `Delayed` object
```

I'd recommend removing the `__annotations__` forwarding and sticking to `__wrapped__` for this PR.

**Comment by Andrew-S-Rosen** [comment]
@hendrikmakait: Thanks for the review. I simplified the PR to only address `.__wrapped__`. Let me know if you need anything else from me.

**Review by hendrikmakait — APPROVED** [review]
Thanks for your contribution, @Andrew-S-Rosen!

**Pull request merged**
