### PR TITLE
Use np.random.Generator to generate random numbers

### LINKED ISSUE #8790: Add ``dask.array.default_rng``
Functions used for the generation of random samples (for example [dask.array.random.normal](https://docs.dask.org/en/latest/generated/dask.array.random.normal.html#dask.array.random.normal)) indicate in their docstring:
`New code should use the normal method of a default_rng() instance instead.`. 

This feature is not currently available and would be very useful for compatibility with other array modules (numpy, cupy, ...).

### PR DESCRIPTION
**Pull request by erayaslan**
- [x] Closes #8790 
- [x] Tests added / passed
- [x] Passes `pre-commit run --all-files`

First pass at using np.random.Generator instead of deprecated np.random.RandomState class. Keep backward compatibility and make deprecation and switching over easy.  Please let me know if an alternative approach is preferable.

Had a quick look and it should be relatively easy to change internal RandomState usage to Generator

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by erayaslan** [comment]
1/
Regarding commits b5eed091 and bcd00d99:

`numpy.random.RandomState` had random_sample - which we aliased to random - which had the following signature:
  

> random.RandomState.random_sample(size=None)


random_sample is removed in `numpy.random.Generator` and is replaced with random which has the following signature: 

> random.Generator.random(size=None, dtype=np.float64, out=None)

so, `da.random.random(5,5)` used to work with RandomState but errors out with Generator.  Instead we need to use `da.random.random(5, chunks=5)`

In other words, this is a breaking change.  Are we allowed to do that?

2/
windows tests fail dask/array/tests/test_random.py::test_choice with:

> 
> [gw2] win32 -- Python 3.10.4 C:\Miniconda3\envs\test-environment\python.exe
> 
>     def test_choice():
>         np_dtype = np.random.choice(1, size=()).dtype
>         size = (10, 3)
>         chunks = 4
>         x = da.random.choice(3, size=size, chunks=chunks)
>         assert x.dtype == np_dtype
>         assert x.shape == size
>         res = x.compute()
>         assert res.dtype == np_dtype
> E       AssertionError: assert dtype('int64') == dtype('int32')

I do not have easy access to a windows environment and it looks like a known windows weirdness. How should we proceed?

**Comment by erayaslan** [comment]
so all tests pass but

1/ All platforms:
`da.random.random(5, 5)` used to work but raises TypeError now. Use `da.random.random(5, chunks=5)` instead

2/ Windows Only:
`da.random.choice()` dtype changed from int32 to int64

**Comment by quasiben** [comment]
add to allowlist

**Review by jsignell — COMMENTED** [review]
Thanks for taking this on! I think it's broadly fine to change behavior, but if possible we try to deprecate or at least raise an informative error.

**Comment by erayaslan** [comment]
continued on PR #9038. Closing

**Pull request closed without merging**
