### PR TITLE
TST: rename dataframe eq to assert_frame

### PR DESCRIPTION
**Pull request by sinhrks**
Renamed ``dataframe.utils.eq`` to ``assert_frame``, which should be consistent with ``array.utils.assert_eq``

### CODE REVIEW

**Comment by mrocklin** [comment]
No strong thoughts either way, but how about `assert_eq` rather than `assert_frame`.  The term "assert frame" to me sounds like we want to assert that a particular object is a frame or has frame-like properties.

**Comment by mrocklin** [comment]
cc @jcrist for thoughts

**Comment by sinhrks** [comment]
Will fix to use ``assert_eq``. 

What I intend to fix is mixed use of ``eq`` and ``assert eq``. It may be caused by ``eq`` looks not to perform assertion (actually it does).

**Comment by mrocklin** [comment]
> What I intend to fix is mixed use of eq and assert eq. It may be caused by eq looks not to perform assertion (actually it does).

Agreed that this should be fixed

**Comment by mrocklin** [comment]
Looks good to me.  Merging.

**Pull request merged**
