### PR TITLE
Adopt Black formatting

### LINKED ISSUE #4319: Use Black for automatic styling
Do we want to use an automatic style tool like [black](https://black.readthedocs.io/en/stable/)?  This tool would standardize all Python code with the repository.  This would remove conversations around style (which I think is good) but also remove flexibility that we might want at times (which might be bad).

I was pretty happy when we added `flake8` to CI.  I'm curious if adding `black` to pre-commit hooks would be a further step along this direction.

Any thoughts?

### PR DESCRIPTION
**Pull request by jrbourbeau**
This PR adopts the `black` code style to allow for auto-formatting. Specifically, this PR:

- [x] Updates the contributing docs
- [x] Updates Travis CI to run `black dask`
- [x] Applies `black` to the codebase 
- [x] Adds `pre-commit` configuration file (with `flake8` and `black`)
- [x] Updates our pull request template

Closes #4319.

### CODE REVIEW

**Comment by jrbourbeau** [comment]
Note I haven't applied `black` yet, I figured it would be easier to review other changes (e.g. doc updates) prior to that commit

**Comment by mrocklin** [comment]
Looks good to me so far.  And the CI failures around black are encouraging that this would catch things.

**Comment by jrbourbeau** [comment]
Black supports Python 3.6.0+ only, which would set a minimum Python version for contributing to Dask. I'm personally okay with this. Do others have reservations?

**Comment by mrocklin** [comment]
No objections from me.

**Comment by mrocklin** [comment]
Are we good to go here @jrbourbeau ?  Anything stopping the actual application of black?

**Comment by jrbourbeau** [comment]
Nope, just wanting to give some time for additional feedback. I'll go ahead and merge `master` and run `black dask`

**Comment by mrocklin** [comment]
That'd be welcome.  I think you're good to go.

**Comment by TomAugspurger** [comment]
Thoughts on isort? I'm not pushing it, but if we're going to do it nows the
time.

**Comment by mrocklin** [comment]
No thoughts either way from me.  @TomAugspurger it sounds like you might have thoughts though?

**Comment by TomAugspurger** [comment]
Not strong ones :) My only preference is to avoid creating a bunch of merge
conflicts twice.

**Comment by mrocklin** [comment]
If no one has any strong thoughts and there hasn't been any conversation about it then I say that we just move ahead without it.

**Comment by jrbourbeau** [comment]
I'm neutral on isort as well

**Comment by mrocklin** [comment]
Screen Shot 2019-06-24 at 10 58 26 PM

**Comment by jrbourbeau** [comment]
Fortunately, there were only two `flake8` issues after running `black dask`! They were both related to Python 2 compatibility and have been fixed in https://github.com/dask/dask/pull/4983/commits/2b1edd508bea7520381b1086ac5b54463b3dfffe and https://github.com/dask/dask/pull/4983/commits/92107a4be33dfb84e7aae5b37f90fb3d0a1ead9e.

At this point, I think we've covered all the previously mentioned TODOs and this PR should be good to merge. Additional comments and review are welcome

**Comment by mrocklin** [comment]
This is in.  Thanks @jrbourbeau !

I hope you don't mind but I took the liberty of rewriting your commits into two, and then rebase-and-merging

1.  First commit does all of the administrative work
2.  Second commit applies black

**Comment by jrbourbeau** [comment]
Not a problem

**Pull request merged**
