### PR TITLE
Add sizeof support for cupy.ndarray

### PR DESCRIPTION
**Pull request by pentschev**
@mrocklin we need this to properly calculate size of `cupy.ndarray`s to spill their memory to host/disk.

- [ ] Tests added / passed
- [ ] Passes `flake8 dask`

### CODE REVIEW

**Comment by mrocklin** [comment]
Looks fine to me.  We should probably have a tiny test in `test_sizeof.py` that uses

```python
cupy = pytest.importorskip('cupy')
```

**Comment by mrocklin** [comment]
It won't ever be caught by our CI, but at least when we run Dask tests on GPU machines we'll pick up something.

**Comment by pentschev** [comment]
Good idea, but doesn't it make more sense to do it in `test_cupy.py` perhaps?

**Comment by mrocklin** [comment]
Sure.  That makes sense.  I had forgotten that such a thing existed :

**Comment by mrocklin** [comment]
+1 

Merging on passed tests

**Pull request merged**
