### PR TITLE
DataFrame: index_bounds instead of divisions for better partition start/stop bounds

### PR DESCRIPTION
**Pull request by gorlins**
This is an implementation which should improve dask DataFrames (and Series) by granting them knowledge of the full index ranges within each partition, rather than how divisions act at the moment.

Divisions, as implemented, are problematic because they a) do not tell the maximum value w/in any given partition (just a less than bound) and b) are confusing and inconsistent since they do try to capture that value for the last partition only.  This implementation solves that by storing a start, stop boundary (as well as whether it is inclusive or exclusive) for each partition.  In all cases where a DF is created within the standard library (parquet, hdf, from_pandas, ... except maybe sql?) this information is already available without additional computation.

It is an implementation of #3384 (and inadvertently solves #3411 as it gives a cleaner way of slicing... and can be further improved)

Tests all seem to be passing (which weren't failing before, eg FFT) though many skip for me (hdfs, ...) so I would like to know if there are remaining issues.

I believe it is fully backwards compatible but will allow for a path to deprecate the use of `.divisions` as we see fit... the `IndexBounds` instance contains more information than divisions and therefore should always be able to recreate the previous behavior.

There are a number of functions that may be improved still w/ the greater amount of information which I did not touch much, such as the repartitioning utilities.  I have marked some with `# TODO`.

I have not yet done much documentation etc... can spend more time if this PR is desirable.  Since this is a rather large change (though most is refactoring) I would appreciate solid feedback before investing more time.

### CODE REVIEW

**Comment by mrocklin** [comment]
Thanks for putting this together @gorlins .  I'm actually quite surprised at how doable it is.  My first thoughts are as follows (first negative, then positive):

1.  I haven't seen many applications where this is critical (though obviously you have one), and so I'm somewhat hesitant to make a big move like this.  Even though this code looks great at first glance there are likely several days of maintanance and bug fixing over the next several months if we make a change this large.  It's not clear who would perform that maintenance.

    This is the kind of change that would have been much easier to make when the project was first starting.
2.  It would be good to generalize out dask dataframe's partitioning structure so that allow for other people, like yourself, could build and use different partitioning schemes.  The other obvious candidate for this today is geopandas.

    This would allow for greater experimentation without causing churn for all current users.

> Divisions, as implemented, are problematic because they a) do not tell the maximum value w/in any given partition b) are confusing and inconsistent since they do try to capture that value for the last partition only

Just in case it wasn't clear, divisions do give an upper bound per partition, it's just not strict.  The i'th partition is guaranteed to have values between the i'th and i+1'th divisions, left-inclusive and right exclusive.

**Comment by gorlins** [comment]
Thanks.  Can you clarify whether this is a 1) no go at all, 2) needs some consideration, 3) want to think of a different way of doing it ... ?  I definitely have some cycles that can be devoted given that I feel this is strongly in the interest of a more general architecture for dask.

If you're looking for a different way of performing something similar, I've been playing with higher-level objects that are collections of single-partition DataFrames (ie so their divisions are right inclusive) and that works well but I'd rather not introduce yet another DataFrame-like type without good cause.  But, it may fit the need of 'generalize out dask dataframe's partitioning structure' so I could share some code if there's interest there.

> Just in case it wasn't clear, divisions do give an upper bound per partition, it's just not strict. The i'th partition is guaranteed to have values between the i'th and i+1'th divisions, left-inclusive and right exclusive.

This is unfortunately just not true as the last division is documented and treated as right *inclusive*.  It makes working with individual partitions very annoying as evidenced by the last commit on this branch (#c6ffa1) which would fail on master.  The utility of having that correct, in case it's still unclear - other than better filtering - is in cross joins/convolutions and other workflows between two frames that don't quite follow the `map_partitions` logic where partitions of all frames are mapped together.

**Comment by mrocklin** [comment]
You're right that the meaning is slightly different on the last division.  My main intention was to state that we do include upper bounds for partitions, not just lower bounds.

> other than better filtering - is in cross joins/convolutions and other workflows between two frames that don't quite follow the map_partitions logic where partitions of all frames are mapped together

I agree that these operations can be improved in general with more information about partitions.  My experience has been that the information currently contained in divisions maps well to common situations and provides as much efficiency as we're likely to achieve.  I rarely see, for example, a great difference between the maximum value of one partition and the minimum value of the next.  To motivate this change it would be useful to gather concrete users for whom this would significantly improve performance.

> 1) no go at all, 2) needs some consideration, 3) want to think of a different way of doing it 

First I think that this needs more input.  I've stated my viewpoints above but other people who maintain dask dataframe often have other viewpoints, and their viewpoints often carry more weight (they do more maintenance work these days).  So we should wait a bit for them to weigh in.

Assuming that their viewpoints are in line with my own then I think that there are a few options for progress:

1.  Generalize partitioning to allow multiple schemes.  This has enough concrete use cases behind it (for example, all of geopandas, cc @jorisvandenbossche) that it is easy to justify a large change in the codebase.
2.  Further motivate this approach by collecting more use cases

    if anyone sees this PR and has situations where including more precise maximums values per partition would help beyond what the current divisions scheme provides I strongly encourage them to speak up.
3.  Further motivate this approach by showing that it can be made *very* lightweight so that it is unlikely to require additional maintenance in the future.  This is fuzzy though and it's hard to guarantee what, if anything, will satisfy requirements here.

My recommendation would be to wait a bit, maybe hear thoughts from @TomAugspurger and @jcrist if they have time, and in the mean time discuss ideas for generalizing partitioning, perhaps in another issue.  Divisions, this scheme, and geospatial partition provide three distinct use cases that might have enough variety to inform generalization.

> I definitely have some cycles that can be devoted given that I feel this is strongly in the interest of a more general architecture for dask

To be clear, I'm quite impressed with this PR and very much want to encourage your continued involvement with this project.  I'm hopeful that we can find a way to satisfy all concerns.

**Comment by TomAugspurger** [comment]
Thanks for the PR @gorlins. I'm still digesting it :)

---

> Generalize partitioning to allow multiple schemes.

I'm very interested in this, since I think it'd be neat and useful. IIUC, this PR is mostly orthogonal to that goal. It can be seen as a "better" (subjective) implementation of the current scheme?

---

Some questions as I try to understand the implications of these change:

1. Does having a fully sorted index simplify anything for you? (https://github.com/dask/dask/issues/3376)
2. What would the result of

```python
In [9]: ddf = dd.from_pandas(pd.DataFrame({"A": range(10), "B": [1] * 10}), 2).set_index("A")

In [10]: ddf
Out[10]:
Dask DataFrame Structure:
                   B
npartitions=2
0              int64
5                ...
9                ...
Dask Name: sort_index, 6 tasks

In [11]: ddf.loc[1:7]
Out[11]:
Dask DataFrame Structure:
                   B
npartitions=2
1              int64
5                ...
7                ...
Dask Name: loc, 8 tasks
```

be for the bounds? Would the second partition know that it's upper limit it 7 and that's inclusive?

Will post more later, but busy with pandas things for the remainder of the week.

**Comment by gorlins** [comment]
> Thanks for the PR @gorlins. I'm still digesting it :)

I realize I should have created it with the internal changes only and not done the internal refactoring, just to make it easier to parse!  Sorry.  Most of the changes are just to ensure we don't lose information internally by 'downsampling' to divisions where not necessary

>  It can be seen as a "better" (subjective) implementation of the current scheme?

Yes, I see this as a strictly better implementation of the current scheme.  Since it can be 100% backwards compatible, there should be no reason other than inertia not to do something like this.  I haven't seen any work on a better partitioning scheme but I had in mind this could actually support it - my `Interval` class can take any object, so that could potentially be a row from a multi-indexed df, or contain partition info, be a tuple/namedtuple (`start = (partition, index)` for example) and 'just work' by providing the appropriate abstraction to that class and not dataframe internals

> Does having a fully sorted index simplify anything for you? (#3376)

No, I think that is orthogonal.  Setting the index would have to calculate (or be told) interval bounds same as it would with divisions.  However, my approach could actually add functionality here - keeping an `Interval` per partition could enable one to have partitions out of order but still preserve the bounds (if desired).  There is no reason to enforce the bounds to be monotonic increasing if you don't rely on the bounds being `divs[i], divs[i+1]` and the slicing object relies on `query in interval` or `interval.overlaps(slice)` semantics.

> be for the bounds? Would the second partition know that it's upper limit it 7 and that's inclusive?

In my implementation of `from_array` and `from_pandas` I chose to make all bounds inclusive rather than exclusive when we know them (and the code does in those places).  For integer domain this doesn't matter but an inclusive range carries more information and is more generalizable so that's why I coded it that way.

For setting an index, the new bounds either have to be passed in, computed (see my tweaks to `compute_divisions` and the new `compute_bounds` in `dataframe.shuffle`), or potentially be given a hint function that takes the current bounds (eg see `IntervalBounds.map`).  If the original code is calling `compute_divisions` in this case, then I did code the result to be inclusive bounds on the min/max of the new df.

When slicing a result with bounds, the new bound is smart enough to take the actual bound using the intersection of the slice and the partition bound.  See `Interval.__and__` and `dataframe.indexing._LocIndexer._loc_slice`.  I'm pretty sure that is tested, plus I added a few.  The resulting bounds should be `IndexBounds((Interval.inclusive(1, 4), Interval.inclusive(5, 7)))`

**Comment by gorlins** [comment]
I'll add that I chose to write my own `Interval` class and implement robust logic inside because I couldn't find a good library to use, but ideally that is not something we reinvent so I'm open to consider other libraries.  I discounted a few (pyinter, pyinterval, interval, ...) because they were too closely aligned with typed bounds (ie most of the work is on floats, or they have subclasses per type) or didn't treat an Interval as a named tuple, which I thought could be important for speed.  I think it is important to have an implementation but that can be replaced with another class if desired.

**Comment by TomAugspurger** [comment]
Haven't forgotten about this. I've just been busy with pandas things and prepping a tutorial. Will revisit it after PyCon.

**Comment by jsignell** [comment]
I am closing this since it is pretty stale at this point. Sorry that it slipped through the cracks @gorlins. Please reopen if you are planning on continuing the work.

**Pull request closed without merging**
