### PR TITLE
Read csv supports setting a sorted column as index directly

### PR DESCRIPTION
**Pull request by abast**
Saving a `dask.DataFrame` to csv and reading it in again currently comes at the cost that all information about the index and known divisions is lost. Recalculating this information is expensive. In this pull request, I therefore want to suggest two changes of the API of `read_csv`:

- `dd.read_csv` provides the keyword `sorted_index_col`, which allows to specify the name of a sorted column. This column is then set as index directly.
- `dd.read_csv` provides the keyword `divisions`, which allows to set the divisions along the `sorted_index_col`. I think, providing divisions should only be supported, if the number of partitions is equal to the number of files, i.e. blocksize has to be None. 

Does this approach make sense?

This is my first pull request ever. Please feel free to correct everything that I should have done differently.

### CODE REVIEW

**Comment by mrocklin** [comment]
This looks like it effectively merges the `set_partition` function into read_csv.  Is this correct?  Would it be reasonable instead to call `read_csv(...).set_partitions(...)` rather than `read_csv(..., ...)`?  What are the advantages to merging everything into one function?

**Comment by abast** [comment]
I see two advantages:

(1) When it comes to access data by index, the proposed method is much faster:

```
# generate dataframes 
ddf = dd.read_csv('[path]/dask_to_csv.*.csv').set_partition('my_index', divisions = my_known_divisions)
ddf2 = dd.read_csv('[path]/dask_to_csv.*.csv', sorted_index_col = 'my_index', divisions = divisions, blocksize = None)
# time to access data by index
%time ddf.loc['some_index'].compute()
%time ddf2.loc['some_index'].compute()
```

> CPU times: user 30min 52s, sys: 2min 18s, total: 33min 11s
> Wall time: 21min 50s
> CPU times: user 364 ms, sys: 8 ms, total: 372 ms
> Wall time: 377 ms

 `DataFrame.set_partition` seems to extend the dask graph with computationally expensive calculations out of the shuffle / sorting machinery. This is not necessary if the metainformation is already incorporated at the level of the creation of the delayed objects. This also helps to keep the dask graph slim:
```
import cloudpickle
%timeit -o cloudpickle.dumps(ddf)
%timeit -o cloudpickle.dumps(ddf2)
```

> 1 loop, best of 3: 2.41 s per loop
> 1 loop, best of 3: 1.5 s per loop

(2) for new users, `read_csv` is much more prominent than `set_partition`. A reasonable user expectation could be that `read_csv` offers all the functionality that is necessary to fully restore a dataframe that was saved using`to_csv`. Restoring a dataframe whose metadata is known should not be computationally expensive.

**Comment by mrocklin** [comment]
Can you try `df.set_index(column, sorted=True, divisions=...)`

**Comment by abast** [comment]
Perfect. Like magic. So it would be VERY helpful to add `divisions =` to the docstring of `set_index`. Currently the docs imply that `set_partition` is doing the job.

My path was basically: read about set_index --> read about set_partitions --> play around --> documented API doesn't give performant results --> raise issue --> pull request --> oh, it is already implemented :D

**Comment by mrocklin** [comment]
Yeah, sorry about that.  Honestly I had to go and look at the code myself to figure out if this was possible.  I agree that this should be in the docstring.  I also think that we should have an example of this use case in the listed examples (which web analytics show is highly trafficked).  I apologize for your round-about path here and not providing more support.

**Comment by abast** [comment]
You've encouraged me to do my first steps on github, so I am certainly not complaining :D 
I still think this pull request might be a good idea:

(1) The presented approach is ~10% faster. I've executed it several times and it was consistent:
```
ddf = dd.read_csv('[path]/dask_to_csv.*.csv').set_index('sim_trail_index', sorted=True, divisions = divisions)
ddf2 = dd.read_csv('[path]/dask_to_csv.*.csv', sorted_index_col = 'sim_trail_index', divisions = divisions, blocksize = None)
%timeit -o ddf.loc['20160629-2316_16837/000000'].compute()
%timeit -o  ddf2.loc['20160629-2316_16837/000000'].compute()
```

> 1 loop, best of 3: 376 ms per loop
> 1 loop, best of 3: 336 ms per loop
```
%timeit -o cloudpickle.dumps(ddf)
%timeit -o cloudpickle.dumps(ddf2)
```
> 1 loop, best of 3: 1.65 s per loop
> 1 loop, best of 3: 1.51 s per loop

(2) If the idea to infer the divisions automatically with something similar to https://github.com/dask/dask/pull/1853 sounds appealing, the function that sets the index needs to know that it reads from csv, because it has to do some file type specific sampling. Merging the two functions into one would make sense then.

(3) if the user chooses a somehow risky parameter combination (like blocksize on default while trying to set divisions manually) he can be warned that the number of partitions might change when the files get bigger.

Another idea to make read_csv more user friendly might be that `to_csv` pickles the metadata and saves it together with the csv files. `read_csv` then could reconstructs the dataframe accordingly. 

What should be the prefered direction to go? Or just leave it as it is?

**Comment by mrocklin** [comment]
Personally I'm not motivated by the 10% speed increase.  Historically read_csv has been very expensive to maintain (I've personally put hundreds of hours into various CSV functions in this project and others) so I'm pretty conservative when it comes to code-complexity to performance tradeoffs.  It's not just "does this code work" but also "how much harder does this code make it to understand or change the surrounding code in the future".  This aversion is also partly why I like keeping general functionality outside of read_csv.

However, you're correct that if we want to automatically find divisions then we'll need to do some trick that is more integrated.  Asking the user to track divisions manually seems unfriendly and doing a full scan is expensive (although far less expensive than a shuffle).

The proposed solution affects core code, and will need to be more thoroughly reviewed by others (touching dask.bytes.core is a serious change that affects the entire project).  If there is a way that avoids that that's more likely to make it in faster.  

I'm somewhat against dask having a special pickle file.  Users are welcome to do this but I don't want to make dask-specific CSV files.  Instead, I would encourage users to use Parquet, of which there appear to be two decent implementations arising.  I expect to see a decent dask.dataframe + parquet solution sometime in the next release in January.

So preferred directions from my perspective in order of attractiveness

1.  Better documentation and example.  I think this is a clear win.
2.  Some clever use of other dask.bytes.core functions to get divisions without seriously changing dask.bytes.core
3.  A minimal and tasteful change to dask.bytes.core to make option two easier if option two is not feasible today

**Comment by abast** [comment]
Thanks for this clear answer. I currently rely on python 2. Fastparquet does not seem to support it, what about the other arising solution?

When it comes to improve the docs, I can say the following pieces of information would have shortened my trip:
- if you want to set a sorted index colum, you have the following options to do it without a need of recomputation: ...
- division information is valuable [link to an explanation why this is the case]. if speedy access by index is important, keep track of it. You can cheaply restore it in the following way: ...
- big disclaimer: do not use set_partition! ;) (When is this function of use?)
- read_csv is meant to be an allrounder and is not highly speed optimized. If your problem fits a special case (like not beeing on a cluster), feel free to implement a thin wrapper around e.g. pd.read_csv yourself. [Example of such a custom method, that is also able to set an index and divisions. Maybe second example where divisions are read in automatically]

For a user trying to implement a custom approach, things might get a bit more complex if e.g. hdfs gets involved. From my short glimpse at the code I had the impression, that bytes.core.open_files is taking care of opening the right files. Could this function be exposed to the public API?

Generally, I understand the push towards parquet. At the same time, it might be good to have a robust and well developed fall back solution. csv might be ideal to complement parquet in this way. Also, using parquet involves converting data into parquet, so a good support of common formats still seems to be desirable.

**Comment by abast** [comment]
Closing, since something equivalent is provided here: https://github.com/dask/dask/issues/1848

**Comment by mrocklin** [comment]
Thanks for tracking progress here.

**Pull request closed without merging**
