### PR TITLE
Un-numpy like behaviour in dask.array.pad

### LINKED ISSUE #5303: un-numpy-like behavior of `da.pad` with stats
`da.pad` with `mode` set to a statistic (e.g., `minimum`) a) doesn't match numpy and b) gives a confusing error message when it fails. The source of this problem is how `da.pad` tries to calculate the `stat_length` parameter when that kwarg is not specified.  

If I have the time, I can put together a PR to fix this. It should not be too hard. The problem is this line: https://github.com/dask/dask/blob/master/dask/array/creation.py#L1007, which blindly uses `args[0]` as `stat_length` without an earlier check for whether `stat_length` has been supplied as a `kwarg`. 

MRE: 
```
import dask.array as da
# this works:
arr_2d = da.zeros((1,1))
da.pad(arr_2d, pad_width=1, mode='minimum')

# error: `TypeError: `pad_value` must be composed of integral typed values.`
arr_3d  = da.zeros((1,1,1))
da.pad(arr_3d, pad_width=1, mode='minimum')

# In numpy, pad with mode=$statistic uses an extra kwarg called `stat_length, which defaults to None. 
# In `da.pad`, passing stat_length=None doesn't work. This produces the same confusing error about the non-integral type of the pad_value.
da.pad(arr_3d, pad_width=1, mode='minimum', stat_length=None)

# this gives equivalent behavior to np.pad with stat_length=None:
da.pad(arr_3d, pad_width=1, mode='minimum', stat_length=arr_3d.shape)
```

### PR DESCRIPTION
**Pull request by mark-boer**
Hi everyone, this is my first PR on this project.

This PR fixes two very minor bugs in `dask.array.pad` and has the tests available for two more bugs.

 1. `pad_widths` did not support an argument of the form `((a, b),)`, where numpy does.
 2. Fixes #5303: `mode` is stats did not work on 3D data.
 3. `mode="mean"` converts data to floats. Test is available, but not yet fixed
 4. If `mode` one of ("reflect", "symmetric", "wrap"), and the `pad_width` is larger than the size of the array, it is handled differently by numpy as dask. Test available, but not yet fixed.

Should I add separate issues in the issue tracker for items 3 and 4?

- [x] Tests added / passed
- [x] Passes `black dask` / `flake8 dask`

### CODE REVIEW

**Comment by mark-boer** [comment]
It seems that `mode = 'linear_ramp'` also has issues in Python 3.6.

**Comment by quasiben** [comment]
Thanks @mark-boer!  I see this is your first time contributing, welcome!  For 3/4, are the test failing ?

**Comment by mark-boer** [comment]
Yes if you uncomment out these lines: 

```
        # "mean", TODO bug: dask changes the dtype to float
        "minimum",
        # "reflect", TODO bug: reflect, symmetric and wrap do not work when the pad_width is larger than the dimension
        # "symmetric",
        # "wrap", 
```

**Comment by martindurant** [comment]
(fsspec issues should have gone away, sorry about that. Will do bugfix release.)

**Comment by TomAugspurger** [comment]
@mark-boer for now I'd recommend splitting out the things that do work from the things that don't (so remove the commented test cases) and keep this PR focused on one issue. That'll make it easier to review and merging won't be held up by unrelated issues.

**Comment by mark-boer** [comment]
> so remove the commented test cases
Shall i just mark them xfail, with a link to a github issue?

I will check why python 3.6 failed later this week, maybe numpy changed something between versions 1.15 and 1.17.

**Comment by mark-boer** [comment]
I think this is about ready to merge, if you agree with the way I skip the tests with a link to the github issue. I might create a pull request that fixes point 3 or 4 later.

**Comment by mark-boer** [comment]
Great, thanks @TomAugspurger! Since issue #5303 is now closed there is no longer a GitHub issue related to points 3 and 4, shall I open a 1 or 2 new github issues for those?

**Pull request merged**
