### PR TITLE
Fix first line of array.random.* docs

### LINKED ISSUE #6041: dask.array.random docs not showing up properly
dask.array.random docs not showing up properly

https://docs.dask.org/en/latest/array-api.html#random

I guess the table is printing the first line of the docstring e.g. https://docs.dask.org/en/latest/array-api.html#dask.array.random.beta

believe the docs are autogenerated in
https://github.com/dask/dask/blob/master/docs/source/array-api.rst#random

Not sure of a workaround.

### PR DESCRIPTION
**Pull request by martindurant**
Original docs erroneously include the signature in the docstring, e.g., https://github.com/numpy/numpy/blob/master/numpy/random/mtrand.pyx#L435
This creates an explicit exception for them.

Fixes #6041 

Note that explicitly checking for "(" and ")" (i.e., signature-like) threw up many other cases, but I thought to keep this simple. This would break if numpy were to clean up their docstrings.

### CODE REVIEW

**Comment by mrocklin** [comment]
I'm curious, what is it about the RandomState docstrings that makes them fail for our current logic?

At first glance they seem typical

```python
In [1]: import numpy as np                                                      

In [2]: np.random.RandomState.beta?                                             
```

```
beta(a, b, size=None)

Draw samples from a Beta distribution.

The Beta distribution is a special case of the Dirichlet distribution,
and is related to the Gamma distribution.  It has the probability
distribution function

.. math:: f(x; a,b) = \frac{1}{B(\alpha, \beta)} x^{\alpha - 1}
                                                 (1 - x)^{\beta - 1},
```

I would much rather make our logic a bit more generic than start special casing functions if possible.

**Comment by martindurant** [comment]
The problem is "beta(a, b, size=None)" - this should not be in the docstring, but generated fro the signature. The current dask code keeps this as the header line, but sphinx recognises it as signature-like and strips it. The root may be, that these are defined as methods and aliased to functions.

I did briefly attempt to recognise the situation automatically, but that seemed to catch many other docstrings too (which I didn't investigate).

**Comment by martindurant** [comment]
@mrocklin , ok to go with the simple exception to the rule for now?

**Comment by mrocklin** [comment]
I think I'm -0.5 on something that special cases something like this within a core function.  I think it's ok to special case, but that we should special-case as close to the specialness as possible.  I agree that this fix is simple, but I think that we can do better without a ton of work.

Maybe we can include a more general parameter like the number of lines to skip or something similar and then use that parameter in the dask.array.random module?  That seems like a more general and more maintainable solution to me that might help future situations.

**Comment by martindurant** [comment]
OK, the "special caseyness" has been moved to where the decorators are called - but there are quite a few of them.

**Comment by martindurant** [comment]
Intend to merge in 24hr.

**Comment by mrocklin** [comment]
Thanks for doing this @martindurant .  This looks good to me.  Merging.

**Pull request merged**
