### PR TITLE
Simplify BlockwiseIODeps importing

### PR DESCRIPTION
**Pull request by rjzamora**
Minor follow-up to #7381

Makes the change suggested [in this comment](https://github.com/dask/dask/pull/7381#discussion_r595567232) (use fully qualified name of BlockwiseIODeps subclass, rather than a `(<module>, <name>)` tuple).  I am separating this change from #7415 since that PR has a huge diff, and this component should be easy to review.

### CODE REVIEW

**Comment by rjzamora** [comment]
cc @jrbourbeau @ian-r-rose

**Comment by rjzamora** [comment]
Looks like a recent `sparse` release is breaking `dask/array/tests/test_sparse.py::test_basic[<lambda>13]`

**Comment by jrbourbeau** [comment]
Just merged the current `main` branch which should resolve the unrelated test failure

**Review by jrbourbeau — APPROVED** [review]
Thanks @rjzamora!

**Pull request merged**
