### PR TITLE
Few travis fixes, pandas version >= 0.18.0

### PR DESCRIPTION
**Pull request by jcrist**
Without --no-deps, pip would upgrade all packages that were out of date,
even if this was intentional by the pandas/numpy build matrix.

### CODE REVIEW

**Comment by jcrist** [comment]
Out of curiousity, why was the `python setup.py develop` line switched to `pip install -e .[complete]`? Is there a reason to prefer one over the other?

**Comment by jcrist** [comment]
Ok, so this turned up a few test failures due to version incompatibility issues, as well as bugs in pandas that are fixed on the latest release. I've fixed all but one of these (still tracking down what's wrong with shuffle). Now might be a good time to discuss again what versions of pandas to support, as this is adding a bit of a maintenance burden. I'm pushing for > 0.18.0 only (as stated more verbosely here: https://github.com/dask/dask/issues/1240).

**Comment by jcrist** [comment]
This should be good to go. Ping @mrocklin for review.

**Comment by mrocklin** [comment]
This looks good to me.  It's a really satisfying PR to look at.  Lets hold off on merging for a day just to think it over and make sure that we want to drop this support.

**Comment by mrocklin** [comment]
https://twitter.com/mrocklin/status/746089445279989761

**Comment by mrocklin** [comment]
Pulling the trigger on this.

**Pull request merged**
