### PR TITLE
Add configuration option to turn off task fusion

### PR DESCRIPTION
**Pull request by mrocklin**
cc @eriknw @jcrist @TomAugspurger 

- [ ] Tests added / passed
- [ ] Passes `black dask` / `flake8 dask`

### CODE REVIEW

**Comment by tlambert03** [comment]
fwiw, I just tested this locally and it works perfectly for our needs!   this PR with `dask.config.set({"optimization.fuse.active": False})` solves https://github.com/napari/napari/issues/718!

**Comment by TomAugspurger** [comment]
Seems OK.

We currently have the parameters for `fuse` in the top-level of the config (`fuse_ave_width`, ...). Are you OK with having that inconsistency, versus having something like `fuse_active`?

I prefer the nested version here, so we would ideally move `fuse_ave_width` in a followup PR if we deem it worth the effort.

**Comment by martindurant** [comment]
Now conflicted, but also failing on apparently the same segfault as has been cropping up elsewhere.

**Comment by mrocklin** [comment]
> We currently have the parameters for fuse in the top-level of the config (fuse_ave_width, ...). Are you OK with having that inconsistency, versus having something like fuse_active?

I think that we should move the other fuse config options under this namespace.  There was some conversation in the other optimization PR about deprecating the old values.  I'm -1 on adding more values like `fuse_active`

**Comment by mrocklin** [comment]
OK, I've gone ahead and added a mechanism to deprecate old configuration values.  cc @jcrist

**Comment by jcrist** [comment]
Thanks @mrocklin, this looks good to me. Merging.

**Pull request merged**
