### PR TITLE
Added product (alias of prod)

### LINKED ISSUE #1259: Add missing methods to Series
Pandas methods like `to_timestamp` are trivial to add to dask.dataframe.  We should go through the API and verify that we've implemented everything like this that is more-or-less trivial to do.

### PR DESCRIPTION
**Pull request by freyam**
- [x] Tests added / passed
- [x] Passes `black dask` / `flake8 dask` / `isort dask`

### CODE REVIEW

**Comment by freyam** [comment]
I ran the tests locally (`py.test dask/dataframe`) after adding `product()` and they all PASSED :heavy_check_mark:

**Comment by martindurant** [comment]
Thanks for contributing. Looks good to me.

This does not "Close #1259", which has potentially several methods to implement - please remove this from the PR description.

Note that `pd.DataFrame.product is pd.DataFrame.prod` - I think you mentioned this in the connected issue.

**Comment by freyam** [comment]
Removed "Closes #1259" from the PR.

and yes, pd.DataFrame.product is pd.DataFrame.prod indeed! So, aliasing also worked!
Now, I ill pick up some other methods like `axes` or `duplicated` from #1259 and work on them

**Comment by freyam** [comment]
Yayyy :rocket: 

This was my first contribution to Dask!! 
Thank you @martindurant for the quick review. This shall also help in my GSoC application. Now, I shall continue adding more methods #1259.

**Comment by martindurant** [comment]
> This was my first contribution to Dask!!

Congratulations and welcome!

**Pull request merged**
