### PR TITLE
Use key_split rather than funcname in dot names

### LINKED ISSUE #4146: Use key names rather than function names in dask.visualize
When creating task graph images we currently inspect the task graph to find functions and use those function names in the graph.  Now that atop produces `subgraph_callables` all the time, this is less informative than it used to be.  We could either dig deeper here, or we could use the keynames instead.  This is what is done in most of the other diagnostics.  It might be a good time to switch over?

cc @jcrist

### PR DESCRIPTION
**Pull request by mrocklin**
Also remove labels for data boxes

Fixes #4146

- [x] Tests added / passed
- [x] Passes `flake8 dask`

dask

### CODE REVIEW

**Comment by mrocklin** [comment]
cc @jcrist

**Comment by mrocklin** [comment]
I'm not entirely sure about this.  

If we remove the labels in the boxes (which I agree seem redundant) then do we need the boxes at all?

**Comment by jcrist** [comment]
Perhaps use the boxes to mark output keys? Since `visualize` can also take a raw graph, this may not be the easiest to do with the current api. Otherwise yeah, I'm not sure if the boxes are necessary.

**Comment by mrocklin** [comment]
I think short term I'm inclined to merge this as is and change things
incrementally

**Comment by jakirkham** [comment]
> If we remove the labels in the boxes (which I agree seem redundant) then do we need the boxes at all?

Would agree with this assertion as well. If the interest is to declutter things a bit, might as well drop the empty boxes too.

**Comment by jakirkham** [comment]
Also would add that personally I find it useful to see which chunk went where (e.g. `(0, 1)`) though the name is pretty obvious given the function it is attached to. Unless of the course the graph becomes very large with lots of crossing connections, then the name becomes necessary to decipher things.

**Comment by mrocklin** [comment]
OK, so I think that my desire to keep the boxes is mostly around style continuity / intertia.  

In an effort to make them useful, I'm now including the chunk/partition index if sensible.

```python
import dask.array as da
x = da.ones((15, 15), chunks=(5, 5))
y = x + x.T - x.mean(axis=0)
y.visualize('dask.png')
```

dask

**Comment by mrocklin** [comment]
Merging this tomorrow morning if there are no further comments

**Comment by Vvkmnn** [comment]
Is there a way to optionally toggle this? [I'm still new to Dask](https://youtu.be/mqdglv9GnM8?t=532), and I'm sad I missed this feature. `funcnames` probably would've worked in my application.

**Pull request merged**
