### PR TITLE
Blockwise.clone

### PR DESCRIPTION
**Pull request by crusaderky**
dask.graph_manipulation.bind and clone will no longer materialize Blockwise layers

### CODE REVIEW

**Comment by crusaderky** [comment]
No new tests as this is already 100% covered by test_graph_manipulation.py

**Review by jrbourbeau — COMMENTED** [review]
Thanks @crusaderky! Could you add a test to ensure `clone`ing doesn't materialize the `Blockwise` layer (e.g. using the `is_materialized` method)

**Comment by crusaderky** [comment]
@jrbourbeau done

**Review by jrbourbeau — APPROVED** [review]
Great, thanks @crusaderky!

**Pull request merged**
