### PR TITLE
add LLM chatbot to Dask docs

### PR DESCRIPTION
**Pull request by dchudz**
This adds a LLM chatbot (using RAG based on Dask docs, StackOverflow Q&A, and a few other Dask-related sources) to the Dask docs. It's something I talked with a few Dask contributors about (@mrocklin , @jrbourbeau , @fjetter, @jacobtomlinson  via Florian) before getting this pull request ready.

We (I and some other folks at Coiled) have played a bit with the questions and answers and think the quality is high enough to try out on real users, but we (@jrbourbeau for now) will plan to monitor the Q&A for quality. 

It's implemented using a product (https://runllm.com/) that Coiled plans to pay for (and continue paying for if this experiment goes well and we keep this in the docs). To avoid paying unlimited amounts for anonymous questions and limit abuse, we're requiring users to join the Dask Slack to send more than 2 queries.

Some considerations going into the choices here:

* Discourse would have been better since the Dask community is much more present there; supporting Discourse is more complicated than Slack, but it's on RunLLM's roadmap. We'd probably want to switch to pushing people there once it's an option. (I've created the Slack channel "DaskBot" for this and set up the integration.)
* I picked the middle/right side of the screen for the button, since dask.docs.org already shows ads in the bottom right.
* We can't currently change the text "Ask AI", but if people feel it's important to switch to something more like "Ask Daskbot", I can let the RunLLM people know we'd really like to make that switch in the future. 

Screenshot 2024-11-21 at 5 12 20 PM
Screenshot 2024-11-21 at 5 12 06 PM

### CODE REVIEW

**Review by jacobtomlinson — COMMENTED** [review]
This is exciting, thanks @dchudz!

Should we put this directly in the Dask theme instead of just in `dask/dask`? That way it will be present in distributed and all the other Dask subprojects.

I'm also not sure about the wording "Ask AI" on the button. I feel like we are at the point where lots of people have AI fatigue and people may be put off by that wording.

Also I noticed that the bot doesn't work in the RTD build preview. Perhaps it's a domain issue?

image

**Comment by dchudz** [comment]
Thanks Jacob! Yeah, the docs preview thing is a problem with the domain. I'll get them to allowlist it.  In the meantime if you feel like it (not that I expect this effort to be worthwhile for you), `localhost` is currently allow-listed so you're welcome play with it locally if you like.

I'll push them on "Join our community" as well as "Ask AI". Hopefully that's easy for them to make configurable for us.

> Should we put this directly in the Dask theme

Good idea! Although I think we wouldn't get docs previews, so maybe I should leave it here for now? Or my screenshots are sufficient preview, happy to make that switch now.

**Comment by mrocklin** [comment]
> I'll push them on "Join our community" as well as "Ask AI". 

I'd go for "Ask Dask" or "Ask DaskBot" or something.

**Comment by jacobtomlinson** [comment]
> Or my screenshots are sufficient preview, happy to make that switch now.

Totally happy with screenshots for preview. If you could switch it that would be awesome.

> I'd go for "Ask Dask" or "Ask DaskBot" or something.

Yeah I like something more along these lines.

**Comment by dchudz** [comment]
Just pushed chages for:

1. "Ask DaskBot"
2. Not mention "Slack Community" (I have "Chat with DaskBot in Slack").

Screenshot 2024-11-25 at 10 37 31 PM

@jacobtomlinson I had a little trouble figuring out stuff with the sphinx theme, and then I realized RunLLM needs to allow-list the all domains we'll use, so it wouldn't just automatically work on any new Dask project anyway.

Probably still good to get it in the theme and allow-list existing projects but how about we just start here and expand to other projects later?

**Comment by jacobtomlinson** [comment]
Can they allowlist a wildcard? E.g `*.dask.org` That would cover everything we need.

If we merge this here it'll need to be removed again when it's added to the theme. Are you happy to own that action?

**Review by jacobtomlinson — APPROVED** [review]
Thanks @jrbourbeau @dchudz. Let's do it then! Thanks for funding this effort Coiled folks!

**Review by jrbourbeau — COMMENTED** [review]
Thanks @dchudz for the work here and @jacobtomlinson for reviewing

**Pull request merged**
