### PR TITLE
dd.merge indicator keyword support

### PR DESCRIPTION
**Pull request by ankravch**
I've tried to implement 'indicator' keyword for dd.merge, but it has some issues in hash_join function.
```python
In [4]: hash_df1 = dd.read_hdf(r'/home/SECDEV.LOCAL/akravchenko/ddf1.h5', '/test', chunksize=1000, lock=False)

In [5]: hash_df2 = dd.read_hdf(r'/home/SECDEV.LOCAL/akravchenko/ddf2.h5', '/test', chunksize=10000, lock=False)

In [6]: out1 = dd.merge(hash_df1, hash_df2, on='v0', how='outer', indicator=True).count()
here we are!!!
Catch all hash join!
started hash_join, indicator =  True

In [7]: dask.compute(out1)
Out[7]:
(v0        100000
 _merge    100000
 dtype: int64,)

In [8]: dask.compute(out1)
Out[8]:
(v0        100000
 _merge    100000
 dtype: int64,)

In [9]: dask.compute(out1)
Out[9]:
(v0        100000
 _merge    100000
 dtype: int64,)

In [10]: dask.compute(out1)
Segmentation fault
```

### CODE REVIEW

**Comment by mrocklin** [comment]
Cool.  This could use some tests to verify that the behavior works in all join cases.

**Comment by ankravch** [comment]
dask.compute(out1, get=dask.async.get_sync) always works. I wonder if there is a way to get a full traceback from dask.compute(out1), instead of 'Segmentation fault'?

**Comment by ankravch** [comment]
running it from gdb python

```python
[akravchenko@hnode1 ~]$ cat test_gdb.py
import dask.dataframe as dd
import pandas as pd
import dask

hash_df1 = dd.read_hdf(r'/home/SECDEV.LOCAL/akravchenko/ddf1.h5', '/test', chunksize=100000, lock=False)
hash_df2 = dd.read_hdf(r'/home/SECDEV.LOCAL/akravchenko/ddf2.h5', '/test', chunksize=50000, lock=False)
out1 = dd.merge(hash_df1, hash_df2, on='v0', how='outer', indicator=True).count()#.head()
dask.compute(out1)#,get=dask.async.get_sync)

[akravchenko@hnode1 ~]$ gdb python
GNU gdb (GDB) Red Hat Enterprise Linux (7.2-90.el6)
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /home/SECDEV.LOCAL/akravchenko/anaconda3/bin/python...done.
(gdb) run test_gdb.py
Starting program: /home/SECDEV.LOCAL/akravchenko/anaconda3/bin/python test_gdb.py
[Thread debugging using libthread_db enabled]
Detaching after fork from child process 4981.
Missing separate debuginfo for /home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/numpy/core/../../../../libiomp5.so
Detaching after fork from child process 4982.
Detaching after fork from child process 4984.
[New Thread 0x7fffe4765700 (LWP 4985)]
[New Thread 0x7fffe3d64700 (LWP 4986)]
[New Thread 0x7fffe3363700 (LWP 4987)]
[New Thread 0x7fffe2962700 (LWP 4988)]
[New Thread 0x7fffe08f3700 (LWP 4989)]
[New Thread 0x7fffdfef2700 (LWP 4990)]
[New Thread 0x7fffdf4f1700 (LWP 4991)]
[New Thread 0x7fffdeaf0700 (LWP 4992)]
[New Thread 0x7fffde0ef700 (LWP 4993)]
[New Thread 0x7fffdd6ee700 (LWP 4994)]
[New Thread 0x7fffdcced700 (LWP 4995)]
here we are!!!
Catch all hash join!
started hash_join, indicator =  True
started _pdmerge, indicator =  True
started _pdmerge, indicator =  True
[Thread 0x7fffdcced700 (LWP 4995) exited]
[Thread 0x7fffdeaf0700 (LWP 4992) exited]
[Thread 0x7fffdfef2700 (LWP 4990) exited]
[Thread 0x7fffe08f3700 (LWP 4989) exited]
[Thread 0x7fffdf4f1700 (LWP 4991) exited]
[Thread 0x7fffde0ef700 (LWP 4993) exited]
[Thread 0x7fffdd6ee700 (LWP 4994) exited]

Program received signal SIGSEGV, Segmentation fault.
_IO_vfprintf_internal (s=0x7fffff3ff620, format=0x7fffbea17903 "can't locate ID", ap=0x7fffff3ff750) at vfprintf.c:1320
1320      f = lead_str_end = __find_specmb ((const UCHAR_T *) format);
```
and another try:
```python
...
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffdeb30700 (LWP 5301)]
0x00007fffbe894e37 in H5FL_reg_malloc ()
   from /home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/tables/../../../libhdf5.so.10
```

**Comment by mrocklin** [comment]
Have you tried not using `lock=False` around the HDF call?  HDF is not threadsafe

**Comment by ankravch** [comment]
right, I did try lock=True, and that produces segfault as well.

**Comment by mrocklin** [comment]
Is it still segfaulting in PyTables?  Perhaps try this without hdf.

**Comment by mrocklin** [comment]
You could also see if this is reproducible on master, and if you're on the most recent Pandas release.

**Comment by ankravch** [comment]
Good ideas. Switching from hdf5 to csv helped, all 20/20 attempts were successful.
```python
[akravchenko@hnode1 ~]$ cat test_gdb.py
import dask.dataframe as dd
import pandas as pd
import dask

#hash_df1 = dd.read_hdf(r'/home/SECDEV.LOCAL/akravchenko/ddf1.h5', '/test', chunksize=100000)
#hash_df2 = dd.read_hdf(r'/home/SECDEV.LOCAL/akravchenko/ddf2.h5', '/test', chunksize=100000)

hash_df1 = dd.read_csv(r'/home/SECDEV.LOCAL/akravchenko/ddf1.csv', blocksize=100000)
hash_df2 = dd.read_csv(r'/home/SECDEV.LOCAL/akravchenko/ddf2.csv', blocksize=100000)

out1 = dd.merge(hash_df1, hash_df2, on='v0', how='outer', indicator=True).count()#.head()
dask.compute(out1)#,get=dask.async.get_sync)
```
P.S. 
from gdb (running on hdf5 with lock=True) consistently produces
```python
Program received signal SIGSEGV, Segmentation fault.
_IO_vfprintf_internal (s=0x7fffff3ff620, format=0x7fffbea57903 "can't locate ID", ap=0x7fffff3ff750) at vfprintf.c:1320
1320      f = lead_str_end = __find_specmb ((const UCHAR_T *) format);
```

>You could also see if this is reproducible on master, and if you're on the most recent Pandas release.

that's right, i am on master (just added those 'indicator' keywords...)

**Comment by mrocklin** [comment]
A separate issue with a reproducible fail case for the HDF stuff would be useful here.

**Comment by jcrist** [comment]
Superseded by #1575. Closing.

**Pull request closed without merging**
