### PR TITLE
dataframe.to_bcolz

### PR DESCRIPTION
**Pull request by simonkamronn**
Save a dask dataframe in a bcolz ctable. The method uses `len()` to calculate the length of the table to allow bcolz to optimize the `chunksize`. Perhaps this could be included the the graph but it seems pretty fast as it is now. Not sure how bcolz behaves with parallel writes so `get_sync` is the default `get` as of now.

### CODE REVIEW

**Comment by simonkamronn** [comment]
Apparently #1374 tries to solve the same problem but in a different way. Not sure which is better

**Comment by mrocklin** [comment]
The performance of `len` can vary greatly.  It forces a full computation of the result.  So for example if you are reading from a stack of CSV files we'll end up having to go through that stack twice.  Once to determine the length and once to actually read the data.  My gut instinct says that this is probably not worth it, and that it might make more sense to choose a sensible default for bcolz chunksize on our own with a bit less intelligence

**Comment by mrocklin** [comment]
Perhaps just something like however many rows would result in 10MB chunks

**Comment by simonkamronn** [comment]
Good idea. How about counting the rows in the first partition and multiplying with number of partitions? Assuming partitions are reasonable in size

**Comment by mrocklin** [comment]
In many cases that will work great.  There are some computations (like some joins) that are highly connected enough that getting *any* of the partitions requires most of the work.

I'm not sure where the tradeoff is here.

**Comment by simonkamronn** [comment]
The bcolz algorithm for calculating optimal chunksize seems efficient so I'd rather not go around that. Now the expected length is extrapolated from the first chunk and there's still the option to provide an expected length in which case the computation is skipped.

**Comment by mrocklin** [comment]
Just to make everyone aware, there are two active PRs for to_bcolz.  I wonder if some communication between @simonkamronn and @ankravch might produce good review and possibly a nice conglomeration of the two approaches in https://github.com/dask/dask/pull/1386 and https://github.com/dask/dask/pull/1374

**Comment by simonkamronn** [comment]
accidentally on master branch

**Pull request closed without merging**
