### PR TITLE
Pass `store`'s `kwargs` to `compute` call

### PR DESCRIPTION
**Pull request by jakirkham**
Fixes https://github.com/dask/dask/issues/3299
Related https://github.com/dask/dask/pull/2980

Appears the `kwargs` intended for the `compute` call in Dask Array's `store` were getting dropped after a recent rewrite. This corrects it so that `kwargs` are passed to the `compute` call.

cc @mrocklin @rabernat

### CODE REVIEW

**Comment by jakirkham** [comment]
Not sure of a good test here given we already passed `kwargs` in tests and they were just getting dropped. Suggestions welcome.

**Comment by rabernat** [comment]
While perhaps overkill, some version of my example from #3299 with the `UnreliableStore` target would be an effective test of `store(..., retries=n)`.

**Comment by martindurant** [comment]
For the student: how many retries with `UnreliableStore` and `N` partitions would it take to have a >99.9% chance of passing the test? :)

**Comment by rabernat** [comment]
> For the student: how many retries with UnreliableStore and N partitions would it take to have a >99.9% chance of passing the test? :)

For this reason, the `UnreliableStore` should probably be modified to just fail once and then succeed after, via some internal state memory.

**Comment by mrocklin** [comment]
We probably can't use retries= to test the store function.  Retries is
specific to the distributed scheduler.

**Comment by jakirkham** [comment]
We probably could create a custom `get` function and then pass some keyword argument(s) in and check for them in the custom `get` function. There might be something easier than this though.

**Comment by jcrist** [comment]
> We probably could create a custom get function and then pass some keyword argument(s) in and check for them in the custom get function. There might be something easier than this though.

That's what I would do (we've done similar things elsewhere). Something like:

```python
def test_forwarded_kwargs()
    called = False
    def myget(*args, **kwargs):
        called = True
        assert 'foo' in kwargs
        return dask.get(*args, **kwargs)
    store([source], [target], get=myget, foo='fake keyword')
    assert called
```

**Comment by jakirkham** [comment]
Thanks. Went ahead and did exactly that.

Please let me know if there is anything else.

**Pull request merged**
