### PR TITLE
Fix HDFS tests

### LINKED ISSUE #7751: hdfs tests failing on main
```python-traceback
______________________ ERROR at setup of test_read_bytes _______________________

request = <SubRequest 'hdfs' for <Function test_read_bytes>>

    @pytest.fixture
    def hdfs(request):
>       hdfs = pyarrow.hdfs.connect(host="localhost", port=8020)

dask/bytes/tests/test_hdfs.py:34: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

host = 'localhost', port = 8020, user = None, kerb_ticket = None
extra_conf = None

    def connect(host="default", port=0, user=None, kerb_ticket=None,
                extra_conf=None):
        """
        Connect to an HDFS cluster. All parameters are optional and should
        only be set if the defaults need to be overridden.
    
        Authentication should be automatic if the HDFS cluster uses Kerberos.
        However, if a username is specified, then the ticket cache will likely
        be required.
    
        Parameters
        ----------
        host : NameNode. Set to "default" for fs.defaultFS from core-site.xml.
        port : NameNode's port. Set to 0 for default or logical (HA) nodes.
        user : Username when connecting to HDFS; None implies login user.
        kerb_ticket : Path to Kerberos ticket cache.
        extra_conf : dict, default None
          extra Key/Value pairs for config; Will override any
          hdfs-site.xml properties
    
        Notes
        -----
        The first time you call this method, it will take longer than usual due
        to JNI spin-up time.
    
        Returns
        -------
        filesystem : HadoopFileSystem
        """
        warnings.warn(
            _DEPR_MSG.format("hdfs.connect", "2.0.0", "fs.HadoopFileSystem"),
>           DeprecationWarning, stacklevel=2
        )
E       DeprecationWarning: pyarrow.hdfs.connect is deprecated as of 2.0.0, please use pyarrow.fs.HadoopFileSystem instead.

/opt/conda/lib/python3.7/site-packages/pyarrow/hdfs.py:215: DeprecationWarning
```
https://github.com/dask/dask/runs/2731208592

### PR DESCRIPTION
**Pull request by jsignell**
- [x] Closes #7751
- [x] Tests added / passed
- [x] Passes `black dask` / `flake8 dask` / `isort dask`

### CODE REVIEW

**Comment by martindurant** [comment]
+1, yep fsspec had to do this too.

**Comment by martindurant** [comment]
`from pyarrow.hdfs import HadoopFileSystem`

**Comment by jsignell** [comment]
I'm getting a seg fault. I assume that's something like what this SO issue is describing https://stackoverflow.com/questions/62520197/how-to-replace-old-legacy-hdfs-connector-with-new-fs-hadoopfilesystem

**Comment by martindurant** [comment]
bahh

**Comment by jsignell** [comment]
@martindurant if you have any ideas please push to this branch

**Comment by martindurant** [comment]
I'll try tomorrow on linux

**Comment by martindurant** [comment]
OK, so I think this will pass for now. 

This should be considered a bug in pyarrow: `pa.hdfs._connect` works fine, `pa.hdfs.connect` fails because we don't allow the deprecation warning, but `pa.fs.HadoopFileSystem` first fails to connect, and then crashes (core dump) for the same system configuration.

`pyarrow.__version__ == 3.0.0` with the given docker build.

@jorisvandenbossche maybe ?

**Comment by martindurant** [comment]
Remind me how to make the hdfs tests actually run? :|

**Comment by jrbourbeau** [comment]
Include `test-hdfs` in the commit message

**Comment by martindurant** [comment]
"Additional / hdfs" passes

**Comment by jrbourbeau** [comment]
We're now getting 

```python
ImportError: cannot import name '_connect' from 'pyarrow.hdfs' (/usr/share/miniconda3/envs/test-environment/lib/python3.8/site-packages/pyarrow/hdfs.py)
```

in the normal test CI builds https://github.com/dask/dask/pull/7752/checks?check_run_id=2739260432#step:7:18381. Potentially a pyarrow version compatibility issue?

**Comment by martindurant** [comment]
ugh. OK, so I'll need different actions depending on pyarrow version.

**Comment by jsignell** [comment]
Let me know if you want me to take back over @martindurant

**Comment by martindurant** [comment]
Not yet!

**Comment by martindurant** [comment]
This is good. Is the apparently unrelated failure known elsewhere?

**Comment by jsignell** [comment]
That failure looks transient to me.. merging. Thanks Martin!!

**Comment by jorisvandenbossche** [comment]
Note that this doesn't actually fix the underlying issue, it just circumvents the deprecation warning we are raising in pyarrow (by accessing a private API (`_connect`) that was created to raise the warning, so that's the reason it didn't work on older pyarrow versions)

> we would like to list Matplotlib
as a Core Project (i.e., with the draft notice removed).

> This should be considered a bug in pyarrow: `pa.hdfs._connect` works fine, `pa.hdfs.connect` fails because we don't allow the deprecation warning,

This part is not a pyarrow bug ;)

> but `pa.fs.HadoopFileSystem` first fails to connect, and then crashes (core dump) for the same system configuration.

If it crashes, that's a bug, and please report issues about this if you encounter that. 
(though, in general the problem with HDFS is that we don't have an arrow committer that actually uses hadoop or has experience with it ..., so it's certainly not the easiest part of the codebase to maintain)

**Comment by martindurant** [comment]
> If it crashes, that's a bug, and please report issues about this if you encounter that.

Yes it does - and that it works fine with the old entry point is interesting. I don't know how to report it, it takes quite some docker messing around to set up a system to investigate this.

**Comment by jorisvandenbossche** [comment]
> I don't know how to report it

Actually, it were the dask tests that segfaulted? That would be a good starting point.

**Comment by martindurant** [comment]
Yes! The segfault happens *after* a couple of tests fail, so I would guess that this is the incorrectly initialised filesystem instance at garbage collection time.

**Comment by jorisvandenbossche** [comment]
OK, I opened https://issues.apache.org/jira/browse/ARROW-13011 on the pyarrow side. Will see if I find some time the coming days to try to reproduce it.

And I opened https://github.com/intake/filesystem_spec/issues/663 on the fsspec side about the actual underlying issue of the deprecation warnings.

**Comment by pitrou** [comment]
The crash is mostly likely a libhdfs issue: https://issues.apache.org/jira/browse/HDFS-16084

Since we're talking about a pointer to free()d memory, it may still point to valid data until some new allocation overwrites it. Hence the fact that the crash may happen at random points.

**Pull request merged**
