### PR TITLE
Pivot table min max functions

### PR DESCRIPTION
**Pull request by sorenwacker**
- [x] Closes #9722
- [x] Tests added / passed
- [x] Passes `pre-commit run --all-files`

### CODE REVIEW

**Comment by phobson** [comment]
ok to test

**Comment by sorenwacker** [comment]
Should I close this?

**Comment by j-bennet** [comment]
Hi @sorenwacker , I'm sorry this fell through the cracks. Your PR seems to be in good shape, no conflicts, no need to close.

cc @jrbourbeau, please take a look, LGTM.

**Comment by sorenwacker** [comment]
Closing this now.

**Pull request closed without merging**
