### PR TITLE
Added melt as a method of Dask DataFrame

### PR DESCRIPTION
**Pull request by dustindall**
I am new to dask and was applying a chain of methods for data processing. I ran into an error when I tried melting the data. I then realized melt is not a method under a dask DataFrame. This PR adds it as a method.

A few other thoughts while I was digging around -
- The documentation is a duplicate of what is shown under pandas.melt. Would it be worthwhile to change the documentation to be @derived_from(pd....)?
- There are currently no tests for melt. Would it be worthwhile for me to add some?

Thanks,
Dustin

### CODE REVIEW

**Comment by TomAugspurger** [comment]
> Would it be worthwhile to change the documentation to be @derived_from(pd....)?

Yes, that would be good.

> There are currently no tests for melt. Would it be worthwhile for me to add some?

There's a basic test in `dask/dataframe/tests/test_multi.py`. Not sure why they're in multi. Possibly because they're using `list_eq`? You could see if `assert_eq` works and move it to `test_reshape.py` if you want. 

It'd be good to add a test for `DataFrame.melt` as well.

**Comment by dustindall** [comment]
I decided not to go ahead with @derived_from and use the docstring as is.

I moved the melt test to test_reshape.py. I tried using assert_eq but the sort on columns than index in _maybe_sort was preventing a pass. Thus, I kept the test using list_eq and I moved list_eq from test_multi.py to dataframe/utils.py and imported it both into test_multi.py and test_reshape.py.

Let me know if i need to do anything else.

Thanks,
Dustin

**Comment by TomAugspurger** [comment]
I’m not sure that we want list_eq in DataFrame/utils.py. Then it becomes part of the public API.

**Comment by mrocklin** [comment]
Merged.  Thanks @dustindall !

Also, I notice that this was your first code contribution to this repository.  Welcome!

**Pull request merged**
