### PR TITLE
Use meta in stack

### PR DESCRIPTION
**Pull request by jakirkham**
Fixes https://github.com/dask/dask/issues/4929

Rewrites `da.stack` to use `_meta`. Borrows from PR ( https://github.com/dask/dask/pull/4925 ) and PR ( https://github.com/dask/dask/pull/4937 ).

cc @pentschev

- [x] Tests added / passed
- [x] Passes `flake8 dask`

### CODE REVIEW

**Comment by jakirkham** [comment]
Planning on merging tomorrow if no comments.

**Comment by pentschev** [comment]
Would you mind adding a small test? I think you could add:

```python
assert isinstance(np.stack([y, y])._meta, sparse.COO)
```

in https://github.com/dask/dask/blob/master/dask/array/tests/test_sparse.py#L160

Otherwise, LGTM. Thanks for that @jakirkham !

**Comment by jakirkham** [comment]
Thanks @pentschev! Done. 🙂

**Comment by pentschev** [comment]
Awesome! From my side, you can merge as soon as build succeeds.

**Pull request merged**
