### PR TITLE
Add Python 3.6 to travis.yml, remove Python 3.3

### PR DESCRIPTION
**Pull request by mrocklin**

### CODE REVIEW

**Comment by mrocklin** [comment]
Should we also remove Python 3.4?  cc @jcrist

**Comment by mrocklin** [comment]
Or rather "I am in favor of removing testing for Python 3.4.  Any objections?"

**Comment by jcrist** [comment]
I'd be potentially fine with removing testing for 3.4. One concern is that both scikit-image and xarray still support 3.4. I doubt any incompatibilities will be introduced, but since they are downstream packages, we should still support 3.4. This might be as simple as testing with 3.4 once right before release though.

**Comment by mrocklin** [comment]
OK, happy to keep it around until downstream projects remove support.  

I plan to merge this soon if no one has any objections.

**Pull request merged**
