### PR TITLE
use generalized form of index checking (is_index_like)

### PR DESCRIPTION
**Pull request by quasiben**
- [ ] Tests added / passed
- [x] Passes `flake8 dask`

@mrocklin do you have an idea of what a good test might be for this change ?

### CODE REVIEW

**Comment by mrocklin** [comment]
Unfortunately we don't have a good lightweight pandas-like project lying around.  For Dask array we tend to use sparse.  

For recent cudf compatibility PRs like this I haven't been testing much in the dask/dask codebase.  I think we're ok to merge this for now.  We should probably start thinking about a longer term solution though.

**Comment by mrocklin** [comment]
Merging this shortly if there are no comments.

**Comment by mrocklin** [comment]
@quasiben you might consider adding a test to dask-cudf

**Comment by quasiben** [comment]
PR https://github.com/dask/dask/pull/4531

**Comment by mrocklin** [comment]
Tested in https://github.com/rapidsai/dask-cudf/pull/121

**Pull request merged**
