### PR TITLE
Add condition if using overwrite mode is not in LocalFileSystem

### PR DESCRIPTION
**Pull request by thinhnd2104**
- [ ] Tests added / passed
- [ x] Passes `black dask` / `flake8 dask` / `isort dask`

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Review by jrbourbeau — COMMENTED** [review]
Thanks for the PR @thinhnd2104. Is there an existing issue the changes here are addressing? It's not clear to me why these changes are needed

**Comment by thinhnd2104** [comment]
> Thanks for the PR @thinhnd2104. Is there an existing issue the changes here are addressing? It's not clear to me why these changes are needed

There is not an existing issue. For example: If I write to s3 filesystem and use _overwrite=False_ & partition_on not None, file name was not changed so It still overwrite on destination.

**Comment by jsignell** [comment]
https://github.com/dask/dask/pull/7682 seems like a more general solution to me. I think the `overwrite` kwarg is only intended to mean "if True -> delete all the files in this path before writing'" It _does not_ promise: "if False -> no files will be overwritten". I agree that this is a subtle distinction and it's definitely confusing and perhaps at odds with the name `overwrite`.

**Comment by thinhnd2104** [comment]
> #7682 seems like a more general solution to me. I think the `overwrite` kwarg is only intended to mean "if True -> delete all the files in this path before writing'" It _does not_ promise: "if False -> no files will be overwritten". I agree that this is a subtle distinction and it's definitely confusing and perhaps at odds with the name `overwrite`.

**Pull request closed without merging**
