### PR TITLE
Pandas compat

### PR DESCRIPTION
**Pull request by TomAugspurger**
xref https://github.com/dask/dask/issues/6148

### CODE REVIEW

**Comment by TomAugspurger** [comment]
The many partd-related failures are handled in https://github.com/pandas-dev/pandas/pull/33892. I'll push another commit on Monday which should fetch a wheel with the fixes in pandas.

**Comment by jorisvandenbossche** [comment]
BTW, I think we should maybe rather consider reverting that freq-related change in pandas: https://github.com/pandas-dev/pandas/pull/33815#issuecomment-620820134

**Comment by TomAugspurger** [comment]
FYI: pandas nightly builds have been failing for ~6 days now, so we're still getting the wheel that broke Partd. Fixing that in https://github.com/MacPython/pandas-wheels/pull/84 and in pandas. Once we get a fresh wheel this should be good.

**Comment by jrbourbeau** [comment]
Thanks for the update

**Comment by jakirkham** [comment]
Is this good to merge? 🙂

**Comment by TomAugspurger** [comment]
No, n the pandas nightly wheel still isn't building correctly.

**Comment by jakirkham** [comment]
Ah ok. Sorry I misread then. Thought the merged PR xref’d above meant this was already fixed.

**Comment by TomAugspurger** [comment]
No worries. https://github.com/pandas-dev/pandas/issues/34114 is the issue to watch on the pandas side.

**Comment by TomAugspurger** [comment]
(partially) fixed the build issue on the pandas side. Lots off new failures though :/

**Comment by mrocklin** [comment]
Thanks for always doing this Tom.  I've learned to not think at all about
Pandas/Dask compatibility over the last few years (which has been
glorious), and I realize that that's not an easy task.

**Comment by TomAugspurger** [comment]
https://github.com/dask/dask/pull/6429 instead.

**Pull request closed without merging**
