### PR TITLE
Remove ``numeric_only`` from ``GroupBy.idxmin`` and ``GroupBy.idxmax``

### PR DESCRIPTION
**Pull request by phofl**
- [ ] Closes #xxxx
- [x] Tests added / passed
- [x] Passes `pre-commit run --all-files`

These are not actually supported by pandas (even though the docs tell you that they are, that's a different problem though)

### CODE REVIEW

**Review by jrbourbeau — COMMENTED** [review]
Thanks @phofl. Is there an upstream `pandas` issue for this? Is `pandas` also removing `numeric_only=` from these methods, or something else?

**Comment by phofl** [comment]
It was never supported here

the docs are wrong

**Review by j-bennet — APPROVED** [review]
Very nice.

**Comment by jrbourbeau** [comment]
Hmm to me this looks like `numeric_only` is having an impact on `groupby.idxmax` (and `idxmin`) with `pandas=2.0.1`. What am I missing?

```python
In [1]: import pandas as pd
pd
In [2]: pd.__version__
Out[2]: '2.0.1'

In [3]: df = pd.DataFrame({"A": [1, 1, 2], "B": [3, 4, 3], "C": ["a", "b", "c"]})

In [4]: df.groupby("A").idxmax(numeric_only=True)
Out[4]:
   B
A
1  1
2  2

In [5]: df.groupby("A").idxmax(numeric_only=False)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[5], line 1
----> 1 df.groupby("A").idxmax(numeric_only=False)

File ~/mambaforge/envs/dask-py39/lib/python3.9/site-packages/pandas/core/groupby/generic.py:2018, in DataFrameGroupBy.idxmax(self, axis, skipna, numeric_only)
   2015     return df.idxmax(axis=axis, skipna=skipna, numeric_only=numeric_only)
   2017 func.__name__ = "idxmax"
-> 2018 result = self._python_apply_general(
   2019     func, self._obj_with_exclusions, not_indexed_same=True
   2020 )
   2021 return result

File ~/mambaforge/envs/dask-py39/lib/python3.9/site-packages/pandas/core/groupby/groupby.py:1402, in GroupBy._python_apply_general(self, f, data, not_indexed_same, is_transform, is_agg)
   1367 @final
   1368 def _python_apply_general(
   1369     self,
   (...)
   1374     is_agg: bool = False,
   1375 ) -> NDFrameT:
   1376     """
   1377     Apply function f in python space
   1378
   (...)
   1400         data after applying f
   1401     """
-> 1402     values, mutated = self.grouper.apply(f, data, self.axis)
   1403     if not_indexed_same is None:
   1404         not_indexed_same = mutated

File ~/mambaforge/envs/dask-py39/lib/python3.9/site-packages/pandas/core/groupby/ops.py:767, in BaseGrouper.apply(self, f, data, axis)
    765 # group might be modified
    766 group_axes = group.axes
--> 767 res = f(group)
    768 if not mutated and not _is_indexed_like(res, group_axes, axis):
    769     mutated = True

File ~/mambaforge/envs/dask-py39/lib/python3.9/site-packages/pandas/core/groupby/generic.py:2015, in DataFrameGroupBy.idxmax.<locals>.func(df)
   2014 def func(df):
-> 2015     return df.idxmax(axis=axis, skipna=skipna, numeric_only=numeric_only)

File ~/mambaforge/envs/dask-py39/lib/python3.9/site-packages/pandas/core/frame.py:10640, in DataFrame.idxmax(self, axis, skipna, numeric_only)
  10637 else:
  10638     data = self
> 10640 res = data._reduce(
  10641     nanops.nanargmax, "argmax", axis=axis, skipna=skipna, numeric_only=False
  10642 )
  10643 indices = res._values
  10645 # indices will always be np.ndarray since axis is not None and
  10646 # values is a 2d array for DataFrame
  10647 # error: Item "int" of "Union[int, Any]" has no attribute "__iter__"

File ~/mambaforge/envs/dask-py39/lib/python3.9/site-packages/pandas/core/frame.py:10524, in DataFrame._reduce(self, op, name, axis, skipna, numeric_only, filter_type, **kwds)
  10520     df = df.T
  10522 # After possibly _get_data and transposing, we are now in the
  10523 #  simple case where we can use BlockManager.reduce
> 10524 res = df._mgr.reduce(blk_func)
  10525 out = df._constructor(res).iloc[0]
  10526 if out_dtype is not None:

File ~/mambaforge/envs/dask-py39/lib/python3.9/site-packages/pandas/core/internals/managers.py:1534, in BlockManager.reduce(self, func)
   1532 res_blocks: list[Block] = []
   1533 for blk in self.blocks:
-> 1534     nbs = blk.reduce(func)
   1535     res_blocks.extend(nbs)
   1537 index = Index([None])  # placeholder

File ~/mambaforge/envs/dask-py39/lib/python3.9/site-packages/pandas/core/internals/blocks.py:339, in Block.reduce(self, func)
    333 @final
    334 def reduce(self, func) -> list[Block]:
    335     # We will apply the function and reshape the result into a single-row
    336     #  Block with the same mgr_locs; squeezing will be done at a higher level
    337     assert self.ndim == 2
--> 339     result = func(self.values)
    341     if self.values.ndim == 1:
    342         # TODO(EA2D): special case not needed with 2D EAs
    343         res_values = np.array([[result]])

File ~/mambaforge/envs/dask-py39/lib/python3.9/site-packages/pandas/core/frame.py:10487, in DataFrame._reduce.<locals>.blk_func(values, axis)
  10485     return values._reduce(name, skipna=skipna, **kwds)
  10486 else:
> 10487     return op(values, axis=axis, skipna=skipna, **kwds)

File ~/mambaforge/envs/dask-py39/lib/python3.9/site-packages/pandas/core/nanops.py:91, in disallow.__call__.<locals>._f(*args, **kwargs)
     89 if any(self.check(obj) for obj in obj_iter):
     90     f_name = f.__name__.replace("nan", "")
---> 91     raise TypeError(
     92         f"reduction operation '{f_name}' not allowed for this dtype"
     93     )
     94 try:
     95     with np.errstate(invalid="ignore"):

TypeError: reduction operation 'argmax' not allowed for this dtype
```

**Comment by phofl** [comment]
Yikes, sorry. I looked at the wrong function signature... Sorry. I messed up SeriesGroupBy and DataFrameGroupBy.

**Comment by phofl** [comment]
I rechecked the pandas implementation and I must have been on an older version somehow. This was added in 1.5, which at least explains the errors I was seeing locally

**Pull request closed without merging**
