### PR TITLE
Don't package tests

### PR DESCRIPTION
**Pull request by jrbourbeau**
This PR proposes we no longer package our tests in the source distribution we push to PyPI. This helps avoids issues like https://github.com/dask/dask/issues/8475 and is similar to what we started doing over in `distributed` (xref https://github.com/dask/distributed/pull/5054). The resulting diff for the `SOURCE.txt` file generated by `python setup.py sdist bdist_wheel` is shown below.

<details>
<summary>SOURCE.txt diff:</summary>

```diff
77,118d75
< dask/array/tests/__init__.py
< dask/array/tests/test_array_core.py
< dask/array/tests/test_array_function.py
< dask/array/tests/test_array_utils.py
< dask/array/tests/test_atop.py
< dask/array/tests/test_chunk.py
< dask/array/tests/test_creation.py
< dask/array/tests/test_cupy_core.py
< dask/array/tests/test_cupy_creation.py
< dask/array/tests/test_cupy_gufunc.py
< dask/array/tests/test_cupy_linalg.py
< dask/array/tests/test_cupy_overlap.py
< dask/array/tests/test_cupy_percentile.py
< dask/array/tests/test_cupy_random.py
< dask/array/tests/test_cupy_reductions.py
< dask/array/tests/test_cupy_routines.py
< dask/array/tests/test_cupy_slicing.py
< dask/array/tests/test_cupy_sparse.py
< dask/array/tests/test_dispatch.py
< dask/array/tests/test_fft.py
< dask/array/tests/test_gufunc.py
< dask/array/tests/test_image.py
< dask/array/tests/test_linalg.py
< dask/array/tests/test_linearoperator.py
< dask/array/tests/test_masked.py
< dask/array/tests/test_numpy_compat.py
< dask/array/tests/test_optimization.py
< dask/array/tests/test_overlap.py
< dask/array/tests/test_percentiles.py
< dask/array/tests/test_random.py
< dask/array/tests/test_rechunk.py
< dask/array/tests/test_reductions.py
< dask/array/tests/test_reshape.py
< dask/array/tests/test_routines.py
< dask/array/tests/test_slicing.py
< dask/array/tests/test_sparse.py
< dask/array/tests/test_stats.py
< dask/array/tests/test_svg.py
< dask/array/tests/test_testing.py
< dask/array/tests/test_ufunc.py
< dask/array/tests/test_wrap.py
< dask/array/tests/test_xarray.py
126,130d82
< dask/bag/tests/__init__.py
< dask/bag/tests/test_avro.py
< dask/bag/tests/test_bag.py
< dask/bag/tests/test_random.py
< dask/bag/tests/test_text.py
134,140d85
< dask/bytes/tests/__init__.py
< dask/bytes/tests/test_bytes_utils.py
< dask/bytes/tests/test_compression.py
< dask/bytes/tests/test_hdfs.py
< dask/bytes/tests/test_http.py
< dask/bytes/tests/test_local.py
< dask/bytes/tests/test_s3.py
180,209d124
< dask/dataframe/io/tests/__init__.py
< dask/dataframe/io/tests/test_csv.py
< dask/dataframe/io/tests/test_demo.py
< dask/dataframe/io/tests/test_hdf.py
< dask/dataframe/io/tests/test_io.py
< dask/dataframe/io/tests/test_json.py
< dask/dataframe/io/tests/test_orc.py
< dask/dataframe/io/tests/test_parquet.py
< dask/dataframe/io/tests/test_sql.py
< dask/dataframe/tests/__init__.py
< dask/dataframe/tests/test_accessors.py
< dask/dataframe/tests/test_arithmetics_reduction.py
< dask/dataframe/tests/test_boolean.py
< dask/dataframe/tests/test_categorical.py
< dask/dataframe/tests/test_dataframe.py
< dask/dataframe/tests/test_extensions.py
< dask/dataframe/tests/test_format.py
< dask/dataframe/tests/test_groupby.py
< dask/dataframe/tests/test_hashing.py
< dask/dataframe/tests/test_hyperloglog.py
< dask/dataframe/tests/test_indexing.py
< dask/dataframe/tests/test_merge_column_and_index.py
< dask/dataframe/tests/test_multi.py
< dask/dataframe/tests/test_numeric.py
< dask/dataframe/tests/test_optimize_dataframe.py
< dask/dataframe/tests/test_reshape.py
< dask/dataframe/tests/test_rolling.py
< dask/dataframe/tests/test_shuffle.py
< dask/dataframe/tests/test_ufunc.py
< dask/dataframe/tests/test_utils_dataframe.py
212,213d126
< dask/dataframe/tseries/tests/__init__.py
< dask/dataframe/tseries/tests/test_resample.py
218,248d130
< dask/diagnostics/tests/__init__.py
< dask/diagnostics/tests/test_profiler.py
< dask/diagnostics/tests/test_progress.py
< dask/tests/__init__.py
< dask/tests/test_base.py
< dask/tests/test_cache.py
< dask/tests/test_callbacks.py
< dask/tests/test_compatibility.py
< dask/tests/test_config.py
< dask/tests/test_context.py
< dask/tests/test_core.py
< dask/tests/test_datasets.py
< dask/tests/test_delayed.py
< dask/tests/test_distributed.py
< dask/tests/test_docs.py
< dask/tests/test_dot.py
< dask/tests/test_graph_manipulation.py
< dask/tests/test_hashing.py
< dask/tests/test_highgraph.py
< dask/tests/test_layers.py
< dask/tests/test_local.py
< dask/tests/test_ml.py
< dask/tests/test_multiprocessing.py
< dask/tests/test_optimization.py
< dask/tests/test_order.py
< dask/tests/test_rewrite.py
< dask/tests/test_sizeof.py
< dask/tests/test_system.py
< dask/tests/test_threaded.py
< dask/tests/test_utils.py
< dask/tests/test_utils_test.py
255d136
< dask/widgets/tests/test_widgets.py

```

</details>

Closes https://github.com/dask/dask/issues/8475

cc @jsignell @jakirkham

### CODE REVIEW

**Comment by jsignell** [comment]
I love this!!

**Comment by jrbourbeau** [comment]
Glad to hear it : )  Just merged `main` which should resolve the unrelated CI failures

**Comment by jakirkham** [comment]
Would suggest actually moving the tests out-of-tree instead (like into a separate `tests` directory). The value is we can still package them in `sdist`, which is useful for packager who like running them to confirm installs work correctly. The other benefit is tests don’t get installed in user environments, which is often where testing issues (like in that GH issue) crop up.

**Comment by jsignell** [comment]
Just to circle back, at the meeting yesterday we all agreed that it seems fine to separate out the tests into their own top-level directory. Jim pointed out that separating tests like that can make it easier to run them against different versions of the code-base.

**Comment by jsignell** [comment]
I'm opening a PR now to move the tests.

**Comment by jsignell** [comment]
https://github.com/dask/dask/pull/8662 does the lifting of moving tests up and out.

**Comment by jrbourbeau** [comment]
Thanks @jsignell -- closing this PR in favor of https://github.com/dask/dask/pull/8662

**Pull request closed without merging**
