### PR TITLE
Revert "Revert "Use HighLevelGraph layers everywhere in collections (…

### PR DESCRIPTION
**Pull request by TomAugspurger**
…#6510)" (#6697)"

This reverts commit e09d8d976725ec844d39ae033f797c41aaa37ba6.

cc @madsbk

### CODE REVIEW

**Comment by mrocklin** [comment]
Let's wait until we do a release.  There were some issues last time around
with string keys in subgraphcallables.  I think that we might want to do a
small mid-week release for this as well as anything else that feels
critical, and then start merging in the HLG fixes.

**Review by jrbourbeau — COMMENTED** [review]
Playing around with this PR locally it looks like we can still produce `HighLevelGraphs` that have raw dictionaries in their layers which causes `HighLevelGraph.get_dependencies` to fail. For example:

```python
import dask.array as da

x = da.ones(10, chunks=(2,))
dsk = x.__dask_graph__()
# Print out HighLevelGraph layers for x
from pprint import pprint
pprint(dsk.layers)

# Get dependencies for all the keys
deps = dsk.get_dependencies()
print(f"{deps = }")
```

raises and `AttributeError`:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-61e7febb21f5> in <module>
      8
      9 # Get dependencies for all the keys
---> 10 deps = dsk.get_dependencies()
     11 print(f"{deps = }")

~/projects/dask/dask/dask/highlevelgraph.py in get_dependencies(self)
    369             self.key_dependencies = {}
    370             for layer in self.layers.values():
--> 371                 self.key_dependencies.update(layer.get_dependencies(all_keys))
    372
    373         return self.key_dependencies

AttributeError: 'dict' object has no attribute 'get_dependencies'
```

I see there's a `HighLevelGraph._fix_hlg_layers_inplace` method which ensures all layers are of type `Layer`. Should we call that at the end of `HighLevelGraph.__init__` to make sure we always have a uniform layer type? @madsbk I'd be curious to hear what you think -- I also could be totally missing something

**Comment by madsbk** [comment]
> I see there's a `HighLevelGraph._fix_hlg_layers_inplace` method which ensures all layers are of type `Layer`. Should we call that at the end of `HighLevelGraph.__init__` to make sure we always have a uniform layer type? @madsbk I'd be curious to hear what you think -- I also could be totally missing something

Good point, I totally agree :) I think we should:
1. Merge this PR
2. Merge https://github.com/dask/dask/pull/6699
3. Create a PR that moves `HighLevelGraph._fix_hlg_layers_inplace()` into `HighLevelGraph.__init__()`

Afterwards, we can look at merging:

- ShuffleStage HLG Layer: https://github.com/dask/dask/pull/6650
- Map on HighLevelGraph Layers: https://github.com/dask/dask/pull/6689
- Serialization of layers: https://github.com/dask/dask/pull/6650

After which, we can begin the work of sending HLGs directly to the scheduler:

- HLGs through `_graph_to_futures()`: https://github.com/dask/distributed/pull/4139
- Sending HLGs to the scheduler: https://github.com/dask/distributed/pull/4140

**Review by jrbourbeau — APPROVED** [review]
Thanks for the nice outline @madsbk, that gives me a much better sense of how the ongoing HLG pieces fit together. 

+1 to merging this PR, then #6699, and then moving `_fix_hlg_layers_inplace` to `HighLeveLGraph.__init__`. I'll leave this open for a bit for feedback, but then plan to start merging

**Comment by rjzamora** [comment]
Thanks all for coordinating!

**Pull request merged**
