### PR TITLE
Add lock to lazy dispatch

### LINKED ISSUE #9181: Possible race condition in `dask.utils:Dispatch.dispatch`
**What happened**:
When using a large number of tasks with `np.ma.core.MaskedArray` blocks, sometimes the scheduler loses the ability to deserialize them. I think I have tracked this down to a possible race condition in [`dask.utils:Dispatch.dispatch`](https://github.com/dask/dask/blob/71aa6ffb3cfdc2a7dcfbc5f5ed91b20f7735c7fd/dask/utils.py#L578), where the lazy registration function is popped off before the registration. If another dispatch happens between those two events, the implementation is not yet in `self._lookup`, but also the lazy registration function is no longer present and thus dask concludes that it can not deserialize the item.

**What you expected to happen**:
That dask/distributed retains the ability to deserialize masked arrays.

**Minimal Complete Verifiable Example**:

I don't have a complete verifiable example due to the tricky nature of reproducing race conditions.

**Environment**:

- Dask version: `main`
- Python version: Python 3.8.13 | packaged by conda-forge
- Operating System: Linux
- Install method (conda, pip, source): Conda environment + dask and distributed source

<details>
<summary>Cluster Dump State:</summary>

</details>

### PR DESCRIPTION
**Pull request by zklaus**
- [ ] Closes #9181 
- [ ] Tests added / passed
- [ ] Passes `pre-commit run --all-files`

This is a draft. Essentially, it adds a readers-writer lock using a new dependency to guard the lazy loading of dispatchers against a race condition. If you want to try it out, you must manually install the [`readerwriterlock` package](https://github.com/elarivie/pyReaderWriterLock).

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

Admins can comment `ok to test` to allow this one PR to run or `add to allowlist` to allow all future PRs from the same author to run.

**Review by jrbourbeau — COMMENTED** [review]
Thanks for working on this @zklaus! 

I don't think we should add a new dependency for this. If a lock is needed, let's use a `theading` / `multiprocessing` / etc. lock instead. Alternatively, I think avoiding the `pop` call until after registration has happened might also avoid the race condition. I'd be curious to get your thoughts on https://github.com/dask/dask/pull/9545.

**Comment by zklaus** [comment]
I'll give the simpler approach a go and report in that issue. I agree that a new dependency should be avoided if possible and I was surprised to find that Python doesn't have a rwlock, c.f. python/cpython#53046.

**Comment by zklaus** [comment]
Superseded by #9545.

**Pull request closed without merging**
