### PR TITLE
Raise an error on the use of the get= keyword and set_options

### PR DESCRIPTION
**Pull request by mrocklin**
Previously we used to warn if the user used the `get=` keyword or used `dask.set_options`

Now we raise an informative TypeError pointing to the `scheduler=` keyword and `dask.config.set` functions respectively.

cc @jcrist @shoyer

### CODE REVIEW

**Comment by mrocklin** [comment]
May: 24fda1faf0da80a3d839d917372aeb7cd421e59c

I'm mostly pushing this now because I think we should probably remove this before 1.0.

**Comment by jcrist** [comment]
Looks good to me. Nice error message, appropriate error. I agree that this should only be part of a major release, but if we think the next release will be a major one then I'm fine merging now.

**Comment by mrocklin** [comment]
> It might be a little early for this.

@shoyer any thoughts on this?  I'm also happy to hold off if you think that that's best.

**Comment by mrocklin** [comment]
> Currently I still think we are losing functionality that is necessary with the new config

@jakirkham are you aware of https://github.com/dask/dask/pull/4062 ?

I think that with that PR all current functionality is handled.

Although I agree that #3708 would be good to do if someone is interested.

**Comment by jakirkham** [comment]
I was not. Thanks for pointing that out to me. Think that actually resolves the issue. There is just a question of doing a little tidying up now.

**Comment by shoyer** [comment]
I think we should wait a little bit longer for https://github.com/dask/dask/pull/4062 to get out into the wild for at least a release or two. I suspect there are a few users who haven't been able to migrate yet.

**Comment by mrocklin** [comment]
Note that most users don't need #4062 .  They've been using `scheduler='threads'`for a long while.  You only need #4062 if you have a custom get function, which today I think I've only seen in practice in test suites (dask's and xarray's).  We've had a warning for anyone that was using the `get=` keyword for quite a while now.

I think that what we did wrong was that we didn't allow people any way to safely use a `get(graph, keys)` callable without getting a warning for a number of releases.  However, because we did that I think it's probably safer to remove it now a bit more quickly than we would have done otherwise.

**Comment by mrocklin** [comment]
To make my statement above more clear (and to bump this thread).  This PR removes the `get=` functionality from dask.  This functionality has been deprecated and has been raising a warning for several months now.  

The fact that no one complained that there wasn't a viable alternative until #4062 is, I think, strong evidence that users were comfortable switching over to using the `scheduler='threads'` approach and that no one needs `get=` today (except for our test suites).

I would still like to push this in.

**Comment by shoyer** [comment]
This does feel a little fast to me, but it's a pretty easy upgrade/fix to make in downstream applications so I don't see much of a downside from pushing this in now.

**Comment by mrocklin** [comment]
> This does feel a little fast to me

See comments above.  This has been deprecated for around five months (which is a long time in dask-months).  

> but it's a pretty easy upgrade/fix to make in downstream applications

Agreed.  See https://github.com/pydata/xarray/pull/2500

> so I don't see much of a downside from pushing this in now.

Huzzah.  This is one of the few things between us and 1.0 (I think)

**Comment by mrocklin** [comment]
Merging tomorrow if there are no additional concerns.

**Pull request merged**
