### PR TITLE
Allow `dask.bag` reductions to work on very sparse data.

### PR DESCRIPTION
**Pull request by eriknw**
Now, the `aggregate` function that merges results can return `no_result` if all the inputs are also `no_results`.  However, the very last call to the `aggregate` function will not return `no_results`, so it will still error as appropriate.

### CODE REVIEW

**Comment by mrocklin** [comment]
This all looks pretty good to me.  I'm curious if there are more corner cases with other reductions, but I suspect not.

**Comment by eriknw** [comment]
I can look for more edge cases later tonight.

**Comment by eriknw** [comment]
I glanced through the code, and I think this is everything.  Ready to merge.

**Comment by jcrist** [comment]
Oop, sorry, just merged #1939 (which handled this for `frequencies`. You'll need to fix the merge conflicts. Otherwise, this looks good to me.

**Comment by eriknw** [comment]
No problem.  Conflicts resolved.

**Pull request merged**
