### PR TITLE
Include `fastparquet` in upstream CI build

### PR DESCRIPTION
**Pull request by jrbourbeau**
cc @martindurant @rjzamora

### CODE REVIEW

**Comment by martindurant** [comment]
> [XPASS(strict)] Parquet doesn't support nanosecond precision

This is what I removed, no? Perhaps there's a bad merge?

**Comment by jrbourbeau** [comment]
Yeah, my local `main` branch didn't include the changes from https://github.com/dask/dask/pull/7880 when I opened this PR. Just merged the upstream `main` branch here so the upstream build _should_ pass now

**Comment by martindurant** [comment]
I think so. Installing from git should force a cythonize on fastparquet, I hope that doesn't add too much time.

**Comment by jrbourbeau** [comment]
The upstream build passed 👍 Planning to merge after the rest of the CI builds finish up

**Pull request merged**
