### PR TITLE
Dask dataframe get dummies sparse

### PR DESCRIPTION
**Pull request by TomAugspurger**
- [x] Tests added / passed
- [x] Passes `flake8 dask`

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Fixed up the whitespace, this should be good to go assuming the tests pass.

**Comment by TomAugspurger** [comment]
Actually, one minute. Adding the new `dtype` kwarg from pandas.

**Comment by TomAugspurger** [comment]
@jakirkham thoughts on sneaking this in before the release (assuming the tests pass?)

**Comment by TomAugspurger** [comment]
Ahh whoops hold on, I messed up git.

**Comment by mrocklin** [comment]
I think he has already started the process.  It's not a bad thing for
features to linger in master for a while before a release anyway.

**Comment by TomAugspurger** [comment]
👍

**Comment by TomAugspurger** [comment]
Merging later today if no objections.

**Pull request merged**
