### PR TITLE
_repr_html_: color sides darker instead of drawing all the lines

### LINKED ISSUE #6670: Size of dask repr_html for large arrays
**What happened**:

I saved a notebook with numerous large dask arrays displayed using `_repr_html_`. The size of the notebook on disk was 50 MB. This is completely dominated by the size of the dask-generated SVG. Notebooks this big are inconvenient to work with and store.

**What you expected to happen**:

I would expect dask to be smarter about generating it's `_repr_html_` so as not to create such large SVG data. In this case, rendering a line for each chunk is pointless, since there are not nearly enough pixels on a screen to actually display this information.

I see three ways to resolve this
- **best**: have `_repr_html_` look at the number of lines it is planning to draw and decide whether it is reasonable. If not, just render a flat polygon.
- **better**: figure out how to rasterize the SVG
- **good**: fall back on the plain-text repr in these cases

**Minimal Complete Verifiable Example**:

```python
import dask.array as dsa
data = dsa.ones((16000, 2400, 3600), chunks=(1, 2400, 3600))
display(data)
len(data._repr_html_().encode('utf-8')) # -> 1379359
```

The repr is 1.4 MB. This is because there are 16000 svg lines drawn along the top and sides of the cube

image

**Environment**:

- Dask version: '2.26.0'
- Python version: 3.7
- Operating System: linux
- Install method (conda, pip, source): conda

### PR DESCRIPTION
**Pull request by jsignell**
- [x] Tests added / passed
- [x] Passes `black dask` / `flake8 dask`

Closes #6670

See what you all think. I set the max number of gridlines to the size of the svg. I don't have a strong opinion, but 20 seemed small to me as a max.

### Original
image

### This PR
image

### UPDATED
image

### CODE REVIEW

**Comment by mrocklin** [comment]
Thanks @jsignell !  This is definitely an improvement on what we had before.  +1 to merge from me.

Personally, I'm still a fan of having some lines (50?) on dimensions with very many chunks.  My guess is that when a novice sees an image like this they'll interpret the darker shade as a stylish shadow rather than "lots of chunks".

**Comment by jsignell** [comment]
> Personally, I'm still a fan of having some lines (50?) on dimensions with very many chunks. My guess is that when a novice sees an image like this they'll interpret the darker shade as a stylish shadow rather than "lots of chunks".

Oh interesting! I hadn't understood that was the intention. Yes I think that number should be related to size as well. Perhaps size/4 or something.

**Comment by jsignell** [comment]
Ok I added lines and made it trigger earlier. I messed around a bit with appearance and `size // 6` looked pretty good to me.

**Comment by jsignell** [comment]
I'll merge this since I think it's uncontrovertial unless anyone else has feedback @dask/maintenance?

**Review by TomAugspurger — APPROVED** [review]
I like the updated version. Maybe leave it for a few hours but I think this is good to go.

**Comment by mrocklin** [comment]
Thanks Julia!  I think that that looks great!

**Pull request merged**
