### PR TITLE
Adding a proper README

### PR DESCRIPTION
**Pull request by seemethere**
This adds a proper README so that users coming to the github project can get a glimpse of what the project is about without having to go to the documentation.

This has no functional impact on the module.

### CODE REVIEW

**Comment by mrocklin** [comment]
We used to have a README like this.  We removed it because it grew out of sync with the documentation.  I'm concerned that this will happen again.  Thoughts on how to resolve this issue?

**Comment by seemethere** [comment]
Use the index.rst as the readme for the repo?

**Comment by mrocklin** [comment]
Is there a way to do this and also have it in docs/source/ as is expected by sphinx?

**Comment by seemethere** [comment]
You could have that as part of the makefile for the docs I would assume.

**Comment by mrocklin** [comment]
We use readthedocs, so they handle all of our doc building.  Having index.rst be someplace different seems more of a burden than just including a link.  My thought here was that clicking on a link was simple enough.  Are there situations where this is significant?

**Comment by llllllllll** [comment]
You can symlink the readme to doc/source/index.rst

**Comment by seemethere** [comment]
How often would README realistically change in a project?

**Comment by mrocklin** [comment]
Our docs get updated fairly often.  Examples change; the project evolves.  We found that the README got out of sync fairly quickly while it contained detailed information like what is proposed here.

For example this project used to be all about out-of-core nd-arrays, then it was nd-arrays and dataframes, and now suddenly it does distributed computing, and actually we're really starting to stress not nd-arrays and dataframes so much, but ad-hoc parallelism.

If you wanted to include only fairly stable information, like a link to the documentation, a very brief description, badges for travis and friends, I'd be entirely for that.

**Comment by seemethere** [comment]
I can do that, I'll make a PR later today with an updated version of the `README.rst`

**Pull request closed without merging**
