### PR TITLE
Test against pandas 0.20.0rc2

### PR DESCRIPTION
**Pull request by TomAugspurger**

### CODE REVIEW

**Comment by TomAugspurger** [comment]
https://travis-ci.org/dask/dask/jobs/228796376 succeeded, closes.

**Comment by mrocklin** [comment]
Are these commits necessary to interact well with Pandas 0.20.0?  Should we issue another micro-release?

**Comment by jcrist** [comment]
Yeah, they just moved some imports. I say wait until 0.20.0 is actually out and then release.

**Comment by mrocklin** [comment]
@TomAugspurger @jreback do you know when this is likely to be?

**Comment by TomAugspurger** [comment]
Tonight most likely. Working on the last couple doc issues now, but those aren't blockers, so we're flexible.

**Comment by mrocklin** [comment]
No rush from me just scheduling things on my end.

**Pull request closed without merging**
