### PR TITLE
Add author field

### PR DESCRIPTION
**Pull request by szabgab**
See also: https://pydigger.com/docs/author

### CODE REVIEW

**Review by jrbourbeau — COMMENTED** [review]
Thanks @szabgab. We already have a `maintainer=` field in our `setup.py`, could you elaborate on how the `author=` field differs?

Side note: We also might consider changing this to something like "Dask developers". @mrocklin do you have any reservations against that?

**Comment by szabgab** [comment]
As far as I understand author is the original person who created the package while maintainer is the currently active person/group.

**Comment by mrocklin** [comment]
I think that we should move both Author and Maintainer to "Dask developers".

Dask has always been a multi-author project.  I'm ok going against
convention a bit here in order to promote team mentality.

**Comment by jrbourbeau** [comment]
Great! @szabgab would you be okay updating author and maintainer to "Dask developers" here?

**Comment by szabgab** [comment]
I've updated the author field.
It might be better for someone else to update the maintainer field, probably together with the maintainer_email field.

**Pull request closed without merging**
