### PR TITLE
Add schema keyword to read_sql

### LINKED ISSUE #2581: Support schema for sql_read_table
Hi,

I tried to use the dask read_sql_table function with a table within a schema, but it returns 'NoSuchTableError'. 

Here are more details:
My database is hosted by amazon rds with postegres

If I try to connect using psycopg2, it works:
```
import psycopg2
import dask.dataframe as dd
url_db = 'postgres://...'
connection = psycopg2.connect(url_db)

cur = connection.cursor()
cur.execute(
    """SELECT * FROM my_schema.my_table""")
print(cur.fetchall())
# this works
```

So the connection is right, but when I try to use dask:

`df = dd.read_sql(table='my_table', schema='my_schema', uri=url_db, index_col='id')`

then I got:

```
---------------------------------------------------------------------------
NoSuchTableError                          Traceback (most recent call last)
<ipython-input-44-e6602fc736cb> in <module>()
...
```

Furthermore, if I try to load a table not in a schema, it works:
`df = dd.read_sql(table='another_table', uri=url_db, index_col='id')`

then it also works...

So I wonder if sql schema is supported in dask ? I didn't found anything on the web about it.

### PR DESCRIPTION
**Pull request by martindurant**
Possibly fixes #2581

### CODE REVIEW

**Comment by martindurant** [comment]
@alexisrosuel , can you check if this solves the problem to you? The schema keyword should now be correctly passed on the sqlalchemy.

**Comment by martindurant** [comment]
@mrocklin , I would merge this simple change, even though I cannot make a test for schema with sqlite. 
Do you think it warrants explicit mention in the docstring?

**Comment by alexisrosuel** [comment]
(just to know, if this branch is merged, when is planned the next release ? Sorry if it is not the right place for asking this !)

**Comment by mrocklin** [comment]
@martindurant what is the limitation behind making a test with sqlite?  It this just that you're short on time or something to do with sqlite itself?

**Comment by martindurant** [comment]
I don't think sqlite supports tables organized within schemas - I certainly can't now find information on how you would create one.

**Comment by mrocklin** [comment]
SQLite tables still have schemas, even if they're somewhat simpler than other databases.  

Regardless, what would happen if a user called our function with a schema keyword argument when reading from a sqlite database?  What would behavior be?  Would this fail?

**Comment by martindurant** [comment]
I mean tables *within* a schema (as opposed to the schema which is the structure of the table itself). 
It seems that for sqlite, if you include this keyword, it tries to open a different database, which makes no sense, as in sqlite each database is a different file, and you give the whole file path as the URI.

**Pull request merged**
