### PR TITLE
Temporarily skip problematic sparse test

### PR DESCRIPTION
**Pull request by jrbourbeau**
As title

### CODE REVIEW

**Comment by jsignell** [comment]
Thank you for doing this!

**Comment by jrbourbeau** [comment]
It looks like we started hitting https://github.com/dask/dask/issues/7169 in the main test suite with the new sparse release. This PR is a temporary quick fix which skips the corresponding problematic test until https://github.com/dask/dask/issues/7169 is resolved.

**Review by jsignell — APPROVED** [review]

**Review by jakirkham — APPROVED** [review]
Thanks for the quick fix James! 😄

**Comment by jrbourbeau** [comment]
Thanks for the quick reviews! I'll merge this in as soon as CI passes (might not wait on the macOS builds if there's a sizable wait queue)

**Pull request merged**
