### PR TITLE
Fix `_partitions` `dtype` in `meta`

### PR DESCRIPTION
**Pull request by hendrikmakait**
- [ ] Closes #xxxx
- [ ] Tests added / passed
- [x] Passes `pre-commit run --all-files`

### CODE REVIEW

**Review by jrbourbeau — COMMENTED** [review]
Thanks @hendrikmakait! Could you add a test for what this is fixing?

**Comment by hendrikmakait** [comment]
@jrbourbeau: I'm not sure how to add a good test in `dask/dask` because `_partitions` is transient. However, it broke things I worked on in `distributed`, so there would be tests relying on this over there. If you have ideas on how to test this here, let's chat.

**Comment by jrbourbeau** [comment]
Presumably this is fixing some issue you encountered when running something. Can we reduce that down to something small and place it in a test? I'm happy to look somewhere if you can point me to where the issue is

**Comment by hendrikmakait** [comment]
This PR was motivated by https://github.com/dask/distributed/pull/8131#discussion_r1304503570.

**Comment by hendrikmakait** [comment]
Regarding the test: Presumably, I can pull out the shuffle layer and verify the meta dtypes from that. 🤔

**Comment by hendrikmakait** [comment]
It looks like CI is broken on `main`.

**Comment by phofl** [comment]
Yikes I saw this last week, but thought this was because of my PR

**Review by phofl — APPROVED** [review]
change looks good

**Comment by phofl** [comment]
Does ``_split_partition`` suffer from the same problem?

**Pull request merged**
