### PR TITLE
Improve reshape test when limiting max chunk size

### PR DESCRIPTION
**Pull request by GenevieveBuckley**
Follow up work from PR 8124, to address [James' suggestions made here](https://github.com/dask/dask/pull/8124/files#r768951852).

This PR:
- Adds a `limit` keyword argument to the reshape method (in addition to the reshape function)
- improves the test cases when testing whether a reshaped Dask array will respect a chunk size limit.

Checklist:
- [x] Follow up work from https://github.com/dask/dask/pull/8124
- [x] Tests added / passed
- [x] Passes `pre-commit run --all-files`

### CODE REVIEW

**Comment by GenevieveBuckley** [comment]
FYI @jrbourbeau, since these were originally your suggestions :smile:

**Review by jsignell — COMMENTED** [review]
Thanks for opening this PR! It looks like a nice improvement.

There is one more piece that @jrbourbeau and I talked about last week but I can't find where we wrote it up. It seems like in other places (namely slicing.py) `split-large-chunks` raises a warning if it is `None`. In your first PR, when `split-large-chunks` is `None` it allows chunk splitting. 

https://github.com/dask/dask/blob/1f30a14865683d76dfeb1f8632879b57d1d6e124/dask/array/reshape.py#L236-L237

Instead it should probably throw a warning, or be treated as Falsey like:

```python
    if limit is None and config.get("array.slicing.split-large-chunks"):
        limit = parse_bytes(config.get("array.chunk-size"))
```

**Comment by GenevieveBuckley** [comment]
I missed that conversation.

Lines 236-237 in `reshape.py` have been updated with your suggested change:
```python
    if limit is None and config.get("array.slicing.split-large-chunks"):
        limit = parse_bytes(config.get("array.chunk-size"))
```

**Comment by jsignell** [comment]
I just merged main to see if we can get tests running a bit better here.

**Review by jsignell — COMMENTED** [review]
I was trying to figure out what was going on with the tests and ended up coming up with a slightly different approach. See what you think of https://github.com/dask/dask/pull/8511

**Comment by jsignell** [comment]
I'm going to close this since we merged #8511 instead

**Pull request closed without merging**
