### PR TITLE
STY: Adjust insert_to_ooc argument order to match store's

### PR DESCRIPTION
**Pull request by jakirkham**
Pulls a stylistic change out of PR ( https://github.com/dask/dask/pull/2980 ). Reorders the input and output arguments for the internal function `insert_to_ooc` in Dask Array to match more closely with `store`'s argument order.

### CODE REVIEW

**Comment by jakirkham** [comment]
Merging tomorrow if no comments.

**Comment by mrocklin** [comment]
This is internal enough that I'm fine with it.  @jcrist might have thoughts.

**Comment by jcrist** [comment]
Fine by me.

**Comment by jakirkham** [comment]
Thanks all.

**Pull request merged**
