### PR TITLE
Unpin `sqlalchemy` and fix compatibility issues

### LINKED ISSUE #9896: `sqlalchemy` 2.0 compatibility
`sqlalchemy` 2.0 was recently released and is causing tests to fail. We should temporarily pin `sqlalchemy<2` in CI as a temporary workaround. 

EDIT: https://github.com/dask/dask/pull/9897 adds the `<2` pin to CI

### PR DESCRIPTION
**Pull request by phofl**
- [x] Closes #9896
- [x] Tests added / passed
- [x] Passes `pre-commit run --all-files`

Removed the restriction when pandas 2.0 is pulled, pandas <2.0 is not compatible with SQLAlchemy 2.0

### CODE REVIEW

**Comment by phofl** [comment]
Failure seems unrelated, saw it also here: https://github.com/dask/dask/actions/runs/4609933258/jobs/8147751744?pr=9756

**Review by jrbourbeau — COMMENTED** [review]
Thanks @phofl! @charlesbluca I think you were looking into something similar. Do you have bandwidth to review this PR? 

> Failure seems unrelated

+1 -- see https://github.com/dask/dask/pull/10145

**Review by charlesbluca — APPROVED** [review]
Thanks @phofl! This LGTM, some relevant sections from the 2.0 migration guide to contextualize these changes:

- https://docs.sqlalchemy.org/en/14/changelog/migration_20.html#implicit-and-connectionless-execution-bound-metadata-removed
- https://docs.sqlalchemy.org/en/14/changelog/migration_20.html#select-no-longer-accepts-varied-constructor-arguments-columns-are-passed-positionally

**Review by jrbourbeau — APPROVED** [review]
Thanks for the fix @phofl and reviewing @charlesbluca!

**Pull request merged**
