### PR TITLE
debug CI with conda 4.3

### PR DESCRIPTION
**Pull request by kalefranz**
Not to be merged. I just need to use your CI to help debug this.

### CODE REVIEW

**Comment by mrocklin** [comment]
No worries.  Very happy to be a conda guinea pig (even if I've been lazy about dogfooding myself).

**Comment by kalefranz** [comment]
Well, I reproduced this once locally, then (because there's something going on with package caching), I couldn't reproduce it again.  You have the reliable, reproducible way.  So thanks for letting me use you as a guinea pig!

**Comment by kalefranz** [comment]
BTW, I'm just listening to our talk python podcast now for conda.  Just realized you got two different shoutouts for favorite packages :)

**Comment by mrocklin** [comment]
:)  I really enjoyed the show even without that.  I was tickled pink though.  Although, I should say that credit for PyToolz these days really should go to @eriknw.  I think he has put more work into it than I have by now.

**Comment by kalefranz** [comment]
Ok, found the problem.  It's subtle and small.  Happens because and `.endswith()` comparison and confusion between `toolz-0.8.2-py35_0.tar.bz2` and `cytoolz-0.8.2-py35_0.tar.bz2`.

**Comment by kalefranz** [comment]
conda `4.3.5` is in the `conda-canary` channel now if you want to test it

**Pull request closed without merging**
