### PR TITLE
Fix naming bug of cumulative aggregations

### LINKED ISSUE #3037: repeated cumsum on dataframe returns the results of the first cumsum
reproduce with 
```python
import pandas as pd
import dask.dataframe as ddf

df = pd.DataFrame(dict(a=list('aabbcc')),
                  index=pd.date_range(start='20100101', periods=6))
df['ones']=1
df['twos']=2

dadf = ddf.from_pandas(df, npartitions=3)
dadf['onescs']=dadf.ones.cumsum()
dadf['twoscs']=dadf.twos.cumsum()
print dadf.compute()
```
which yields
```
            a  ones  twos  onescs  twoscs
2010-01-01  a     1     2       1       1
2010-01-02  a     1     2       2       2
2010-01-03  b     1     2       3       3
2010-01-04  b     1     2       4       4
2010-01-05  c     1     2       5       5
2010-01-06  c     1     2       6       6
```

Pandas itself works correctly:
```python
df['onescs']=df.ones.cumsum()
df['twoscs']=df.twos.cumsum()
print df
```
which yields
```
            a  ones  twos  onescs  twoscs
2010-01-01  a     1     2       1       2
2010-01-02  a     1     2       2       4
2010-01-03  b     1     2       3       6
2010-01-04  b     1     2       4       8
2010-01-05  c     1     2       5      10
2010-01-06  c     1     2       6      12
```

### PR DESCRIPTION
**Pull request by mfaafm**
Fixes #3037.

- [x] Tests added / passed
- [x] Passes `flake8 dask`
- [x] Fully documented, including `docs/source/changelog.rst` for all changes
      and one of the `docs/source/*-api.rst` files for new API

### CODE REVIEW

**Comment by mrocklin** [comment]
This is great.  Thank you for the bug report and the excellent fix.  

I suspect that this bug escaped notice for a while because of the ambiguous use of the name `token`, which we often use to mean "unique identifier" but which in the case of this method seems to mean "name of operation".  We might consider changing the name in this method as well from `token=` to `name=` or something similar.

That's just a small thought though.  I'm +1 on this change after tests pass.

**Comment by mrocklin** [comment]
The last failing test is due to https://github.com/dask/dask/issues/3043 and is unrelated to this PR.

**Comment by mfaafm** [comment]
For setting up the dask graph, local variables called `name` are used a lot in the code. So I would suggest not changing that, since this is also used in `_cum_agg`.  How about changing `token` to `op_name`?

**Comment by mrocklin** [comment]
That seems good to me

**Comment by TomAugspurger** [comment]
Thanks @mfaafm !

**Comment by mrocklin** [comment]
Thanks @mfaafm!

**Pull request merged**
