### PR TITLE
Use strict channel priority in CI

### PR DESCRIPTION
**Pull request by jrbourbeau**

### CODE REVIEW

**Comment by jrbourbeau** [comment]
Errors like the following have started showing up in CI

```
2021-07-06T22:21:13.4210680Z     import numpy as np
2021-07-06T22:21:13.4211310Z     
2021-07-06T22:21:13.4212100Z     import dask.array as da
2021-07-06T22:21:13.4212840Z     from dask import delayed
2021-07-06T22:21:13.4214460Z     from dask.array.ufunc import wrap_elemwise
2021-07-06T22:21:13.4215310Z     from dask.utils import derived_from
2021-07-06T22:21:13.4215980Z     
2021-07-06T22:21:13.4216540Z     try:
2021-07-06T22:21:13.4217190Z >       import scipy.stats
2021-07-06T22:21:13.4217720Z 
2021-07-06T22:21:13.4220080Z dask/array/stats.py:40: 
2021-07-06T22:21:13.4221090Z _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
2021-07-06T22:21:13.4221680Z 
2021-07-06T22:21:13.4222240Z     """
2021-07-06T22:21:13.4222860Z >   from .stats import *
2021-07-06T22:21:13.4223370Z 
2021-07-06T22:21:13.4224830Z ../../../miniconda3/envs/test-environment/lib/python3.7/site-packages/scipy/stats/__init__.py:391: 
2021-07-06T22:21:13.4225940Z _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
2021-07-06T22:21:13.4226450Z 
2021-07-06T22:21:13.4227020Z     """
2021-07-06T22:21:13.4227560Z     
2021-07-06T22:21:13.4228170Z     import warnings
2021-07-06T22:21:13.4228810Z     import math
2021-07-06T22:21:13.4229460Z     from math import gcd
2021-07-06T22:21:13.4230200Z     from collections import namedtuple
2021-07-06T22:21:13.4230910Z     
2021-07-06T22:21:13.4231520Z     import numpy as np
2021-07-06T22:21:13.4232230Z     from numpy import array, asarray, ma
2021-07-06T22:21:13.4232890Z     
2021-07-06T22:21:13.4233660Z >   from scipy.spatial.distance import cdist
2021-07-06T22:21:13.4234320Z 
2021-07-06T22:21:13.4235730Z ../../../miniconda3/envs/test-environment/lib/python3.7/site-packages/scipy/stats/stats.py:174: 
2021-07-06T22:21:13.4236730Z _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
2021-07-06T22:21:13.4237240Z 
2021-07-06T22:21:13.4237800Z     """
2021-07-06T22:21:13.4238340Z     
2021-07-06T22:21:13.4238960Z     from .kdtree import *
2021-07-06T22:21:13.4239660Z     from .ckdtree import *
2021-07-06T22:21:13.4240330Z >   from .qhull import *
2021-07-06T22:21:13.4242400Z E   ImportError: dlopen(/Users/runner/miniconda3/envs/test-environment/lib/python3.7/site-packages/scipy/spatial/qhull.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libopenblas.dylib
2021-07-06T22:21:13.4244940Z E     Referenced from: /Users/runner/miniconda3/envs/test-environment/lib/python3.7/site-packages/scipy/spatial/qhull.cpython-37m-darwin.so
2021-07-06T22:21:13.4246230Z E     Reason: image not found
2021-07-06T22:21:13.4246770Z 
2021-07-06T22:21:13.4248200Z ../../../miniconda3/envs/test-environment/lib/python3.7/site-packages/scipy/spatial/__init__.py:98: ImportError
```

Note that this appears to only impact our Python 3.7 builds. This might be a packaging issue. cc @jakirkham in cast you have any thoughts or have seen this elsewhere recently

**Comment by jakirkham** [comment]
Unfortunately that is not enough to go on. Would need to look at the log to see what was installed. Should add I may not have time to get to this this week

**Comment by jrbourbeau** [comment]
No worries @jakirkham. It looks like the issue was we weren't using strict conda channel priority in CI which was causing a bad mixture of packages from `conda-forge` and `defaults`

**Comment by jrbourbeau** [comment]
Using strict conda channel priority in our CI builds fixes the unrelated failures (and is probably a good thing to do anyways). Planning to merge after CI finishes

**Comment by jakirkham** [comment]
Yeah we have been recommending strict channel priority in conda-forge. So it makes sense to make that change

**Comment by jrbourbeau** [comment]
> Presumably we were getting MKL from defaults in some cases alongside packages from conda-forge built with OpenBLAS

Yeah, that's exactly what was happening. I think we originally added `channel-priority: true` with the intent of using strict channel priority, but didn't realize that `channel-priority: true` is an older alias for `channel-priority: flexible`, not `channel-priority: strict`

**Comment by jakirkham** [comment]
Yeah that makes sense. Reading [this doc]( https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-channels.html?highlight=channel_priority#strict-channel-priority ) it sounds like `True`/`False` are legacy options. So they were left alone and continue to behave as they had. Instead `"strict"`, `"flexible"`, and `"disabled"` are preferred going forward

**Pull request merged**
