### PR TITLE
DOC: update develop doc with conda option

### PR DESCRIPTION
**Pull request by raybellwaves**
- [NA] Tests added / passed
- [NA] Passes `black dask` / `flake8 dask`

Update the documentation in https://docs.dask.org/en/latest/develop.html#contributing-to-documentation with https://github.com/dask/dask/blob/master/docs/README.rst

### CODE REVIEW

**Comment by quasiben** [comment]
@raybellwaves you may be interested in this PR: https://github.com/dask/distributed/pull/3406

**Comment by raybellwaves** [comment]
Thanks @quasiben i'll update my PR to include some of the git commands in https://distributed.dask.org/en/latest/develop.html#install

**Comment by quasiben** [comment]
Thanks @raybellwaves for the doc updates.  Is this ready to be merged ?

**Comment by raybellwaves** [comment]
Yep

**Comment by quasiben** [comment]
Great!  Merging in

**Pull request merged**
