### PR TITLE
Add pytest color to CI

### PR DESCRIPTION
**Pull request by jrbourbeau**
Inspired by @consideRatio over in https://github.com/dask/dask-gateway/pull/430

EDIT: cc @jacobtomlinson

### CODE REVIEW

**Comment by jsignell** [comment]
beautiful!

**Comment by jsignell** [comment]
I just looked at the raw logs and now have mixed feelings.

```
2021-09-01T15:29:46.2602118Z [31m[1m_________________________________ test_errors __________________________________[0m
2021-09-01T15:29:46.2602985Z [gw2] linux -- Python 3.9.6 /usr/share/miniconda3/envs/test-environment/bin/python
2021-09-01T15:29:46.2603472Z 
2021-09-01T15:29:46.2604301Z self = <fsspec.implementations.http.HTTPFileSystem object at 0x7f28d0f36550>
2021-09-01T15:29:46.2605568Z url = 'http://localhost:8999/doesnotexist', kwargs = {}, info = {}
2021-09-01T15:29:46.2606428Z session = <aiohttp.client.ClientSession object at 0x7f28d0ab26d0>
2021-09-01T15:29:46.2607188Z policy = 'get'
2021-09-01T15:29:46.2607422Z 
2021-09-01T15:29:46.2608044Z     [94masync[39;49;00m [94mdef[39;49;00m [92m_info[39;49;00m([96mself[39;49;00m, url, **kwargs):
2021-09-01T15:29:46.2608673Z         [33m"""Get info of URL[39;49;00m
2021-09-01T15:29:46.2609131Z     [33m[39;49;00m
2021-09-01T15:29:46.2609817Z     [33m    Tries to access location via HEAD, and then GET methods, but does[39;49;00m
2021-09-01T15:29:46.2610521Z     [33m    not fetch the data.[39;49;00m
2021-09-01T15:29:46.2610985Z     [33m[39;49;00m
2021-09-01T15:29:46.2611717Z     [33m    It is possible that the server does not supply any size information, in[39;49;00m
2021-09-01T15:29:46.2612629Z     [33m    which case size will be given as None (and certain operations on the[39;49;00m
2021-09-01T15:29:46.2613420Z     [33m    corresponding file will not work).[39;49;00m
2021-09-01T15:29:46.2613959Z     [33m    """[39;49;00m
2021-09-01T15:29:46.2614281Z         info = {}
2021-09-01T15:29:46.2615133Z         session = [94mawait[39;49;00m [96mself[39;49;00m.set_session()
2021-09-01T15:29:46.2615571Z     
2021-09-01T15:29:46.2616310Z         [94mfor[39;49;00m policy [95min[39;49;00m [[33m"[39;49;00m[33mhead[39;49;00m[33m"[39;49;00m, [33m"[39;49;00m[33mget[39;49;00m[33m"[39;49;00m]:
2021-09-01T15:29:46.2616911Z             [94mtry[39;49;00m:
2021-09-01T15:29:46.2617286Z                 info.update(
2021-09-01T15:29:46.2617844Z >                   [94mawait[39;49;00m _file_info(
2021-09-01T15:29:46.2618219Z                         url,
2021-09-01T15:29:46.2618603Z                         size_policy=policy,
2021-09-01T15:29:46.2619031Z                         session=session,
2021-09-01T15:29:46.2619604Z                         **[96mself[39;49;00m.kwargs,
2021-09-01T15:29:46.2619982Z                         **kwargs,
2021-09-01T15:29:46.2620307Z                     )
2021-09-01T15:29:46.2620588Z                 )

**Comment by consideRatio** [comment]
Ooooh, are these coloring-letters a result of forcing color=yes everywhere via setup.cfg that would have not happened if instead used --color=yes in the call just within the github workflow file?

I have never seen the issue of having such symbols emitted in logs across several projects, but I've always made it an explicit workaround for github workflows.

**Comment by consideRatio** [comment]
Aaaah okay, yeah that is a drawback I think won't be avoidable if there is to be color in the web UI.

**Comment by jsignell** [comment]
Ok yeah maybe the github UI is better now I feel like I used to not be confident when ctrl-fing the rendered logs. I am fine to keep things as they are from this PR, we can see if other people bring it up.

**Comment by jcrist** [comment]
I've been having issues with the github UI not properly rendering test logs (maybe they're too long? idk), and having to go look at the raw logs which are pretty unreadable due to all the markup (e.g. see https://pipelines.actions.githubusercontent.com/0DoyRJDtENhiFu7PGYnBf3mmhonFflRovDx9lQVGIuKFuV9otW/_apis/pipelines/1/runs/40580/signedlogcontent/3?urlExpires=2022-03-07T20%3A33%3A24.9300229Z&urlSigningMethod=HMACV1&urlSignature=QYdTvHGa%2BsLp6vsGwpswj4ez4e1dBshKgTtXm53ouFw%3D). Not 100% saying we should revert this, but it's a bit annoying.

**Pull request merged**
