### PR TITLE
Don't constrict stage/k dtype in dataframe shuffle

### PR DESCRIPTION
**Pull request by mrocklin**
This was causing us to drop partitions in some cases

Fixes https://github.com/dask/distributed/issues/2226

- [ ] Tests added / passed
- [ ] Passes `flake8 dask`

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Is the test case from dask/distributed#2226 too expensive to include as a test?

**Comment by mrocklin** [comment]
Yes, I think so.  It takes a minute or two.  I might be able to construct something though.  I'll take a look

**Comment by TomAugspurger** [comment]
If producing a smaller example proves to be difficult, then just merging seems fine to me.

**Comment by mrocklin** [comment]
I looked into this a bit this morning.  I tried to trigger the previous error sooner by playing with the `max_branch=` keyword in the shuffle functions but wasn't able to do much.  I'm going to go ahead and merge this untested.

**Pull request merged**
