### PR TITLE
Add test deps for pip development

### PR DESCRIPTION
**Pull request by jsignell**
If you install with pip following https://docs.dask.org/en/latest/develop.html you'll be missing the testing dependencies. I'm wondering if this is best handled by adding more docs, or by having a `pip install -e ".[test]"`

ref https://github.com/dask/dask/issues/7358#issuecomment-795545859

This is the docs version, but I am wondering if people would be opposed to adding another pip extra option called `[test]` that would not be included in `[complete]` 

@dask/maintenance

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
>  am wondering if people would be opposed to adding another pip extra option called [test] that would not be included in [complete]

Sounds reasonable to me.

Many of the Dask subprojects have a `requirements-test.txt` file and instructions in the contributing docs to install that when developing. 

Is the idea to replace that with `pip install .[test]`?

**Review by jrbourbeau — COMMENTED** [review]
Thanks for improving things here @jsignell. I have a slight preference for either the `requirements-test.txt` or `[test]` extras option as those are less likely to go out of date than documentation.

Since we already handle all our optional deps through `setup.py` extras instead of a `requirements.txt` file, adding a new `[test]` extra seems like the smoothest option. I think multiple extras can also be specified so something like

```python
python -m pip install -e ".[complete,test]"
```

should work

**Comment by jacobtomlinson** [comment]
Both of @jrbourbeau's sugegstions would be possible. In many Dask projects we read the requirements from a `requirements.txt` file within `setup.py`.

We could add a `requirements-test.txt` file and then read that in the `setup.py` as a `test` extras requires.

**Comment by jsignell** [comment]
Ok I think I'll do the smallest change and just inline the test reqs in setup.py.

**Review by jacobtomlinson — APPROVED** [review]

**Pull request merged**
