### PR TITLE
Implement `sizeof` for some `bytes`-like objects

### PR DESCRIPTION
**Pull request by jakirkham**
As it appears we don't actually support `sizeof` for `bytes`-like types [on PyPy]( https://github.com/dask/dask/blob/326a12a940f815d27ecf3afac623927a17c1c83b/dask/sizeof.py#L7 ), but they are easy to implement and commonly encountered, go ahead and implement custom `sizeof` for these `bytes`-like types.

- [x] Tests added / passed
- [x] Passes `black dask` / `flake8 dask`

### CODE REVIEW

**Comment by mrocklin** [comment]
+1

**Comment by gforsyth** [comment]
@jakirkham -- can you rebase against / merge from master so we can pick up the parquet test fixes?

**Comment by jakirkham** [comment]
Thanks for the ping. Yep, merged with `master`. 🙂

**Comment by jakirkham** [comment]
Looks like CI is now happy 💚

**Pull request merged**
