### PR TITLE
Unpin graphviz now that new conda-forge recipe is built

### LINKED ISSUE #7231: Test failures on windows with graphviz missing .bat files.
Today I started seeing failures in the tests like:

```python-traceback
cmd = ['dot.bat', '-Kdot', '-Tpng']
input = b'digraph {\n\tgraph [rankdir=BT]\n\t4770961679805687079 [label="" shape=box]\n\t-2718215776272399448 [label="" shape=...79 -> 1289659767108614192\n\t-1109490218808452559 [label="" shape=box]\n\t-2595565211807651805 [label="" shape=box]\n}'
capture_output = True, check = True, encoding = None, quiet = False
kwargs = {'stderr': -1, 'stdin': -1, 'stdout': -1}

    def run(cmd, input=None, capture_output=False, check=False, encoding=None,
            quiet=False, **kwargs):
        """Run the command described by cmd and return its (stdout, stderr) tuple."""
        log.debug('run %r', cmd)
    
        if input is not None:
            kwargs['stdin'] = subprocess.PIPE
            if encoding is not None:
                input = input.encode(encoding)
    
        if capture_output:
            kwargs['stdout'] = kwargs['stderr'] = subprocess.PIPE
    
        try:
            proc = subprocess.Popen(cmd, startupinfo=get_startupinfo(), **kwargs)
        except OSError as e:
            if e.errno == errno.ENOENT:
>               raise ExecutableNotFound(cmd)
E               graphviz.backend.ExecutableNotFound: failed to execute ['dot.bat', '-Kdot', '-Tpng'], make sure the Graphviz executables are on your systems' PATH

C:\Miniconda3\envs\test-environment\lib\site-packages\graphviz\backend.py:169: ExecutableNotFound
```

for example: https://github.com/dask/dask/pull/7230/checks?check_run_id=1911913930

I suspsect that something is wrong with the conda-forge package: graphviz 2.46.1 h93c640b_0 which was released today. 

I am going to pin graphviz to an older version in the tests

### PR DESCRIPTION
**Pull request by jsignell**
Closes #7231, reverts #7232

### CODE REVIEW

**Review by jrbourbeau — COMMENTED** [review]
That was quick! Looking at the full environment files, I think we can actually drop `graphviz` as `python-graphviz` is a metapackage which includes both the system `graphviz` package as well as the the Python bindings (though I realize having both `graphviz` and `python-graphviz` predates the changes in https://github.com/dask/dask/pull/7232)

**Comment by jrbourbeau** [comment]
Just restarted CI (it takes ~20 minutes for new conda-forge builds to be available to download). Also cc @jakirkham

**Comment by jakirkham** [comment]
Looks like the macOS builds are still queued. Is that typical? The rest of the builds appear to have passed. FWIW only Windows was affected by this issue IIUC

**Comment by jrbourbeau** [comment]
I know there are fewer macOS machines available on GitHub actions so sometimes it takes a bit longer to get one. Though I don't recall this extra wait time being several hours (like we're seeing right now) : / 

> FWIW only Windows was affected by this issue IIUC

Yeah, that's the case. I'll merge this in as Windows CI has already passed

**Comment by jrbourbeau** [comment]
Thanks @jsignell!

**Comment by jakirkham** [comment]
Ah ok. Yeah I was trying to see if there was something mentioned on the status page about this, but didn’t find anything

Cool. Thanks James and Julia! 😀

**Pull request merged**
