### PR TITLE
Replace use of explicit type check with ._is_partition_type predicate

### PR DESCRIPTION
**Pull request by mrocklin**
- [ ] Tests added / passed
- [ ] Passes `flake8 dask`

### CODE REVIEW

**Comment by mrocklin** [comment]
Fixes https://github.com/rapidsai/dask-cudf/issues/115

**Comment by quasiben** [comment]
I am unable to reproduce locally with a py27 env.  I restarted the py36/py27 builds and I'll see what happens

**Comment by quasiben** [comment]
Nevermind!  Forgot to change branches

**Comment by quasiben** [comment]
In py27 pandas fails on `hasattr(typ, 'columns').  Note that if you call dir on the object `columns` is in the list

```python
Python 2.7.15 |Anaconda, Inc.| (default, Dec 14 2018, 13:10:39)
Type "copyright", "credits" or "license" for more information.

IPython 5.8.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import pandas as pd

In [2]: hasattr(type(pd.DataFrame()), 'columns')
Out[2]: False

In [3]: 'columns' in dir(type(pd.DataFrame()))
Out[3]: True

In [4]: 'columns' in dir(type(pd.Series()))
Out[4]: False
```

**Comment by mrocklin** [comment]
```python
In [3]: pd.__version__
Out[3]: u'0.24.1'
```

**Comment by quasiben** [comment]
The test is against pd `0.20.02`:

```python
In [10]: pd.__version__
Out[10]: u'0.20.2'
```

**Comment by quasiben** [comment]
In version 0.23 this issue was resolved

**Comment by quasiben** [comment]
@mrocklin how would you like to proceed here ?  I imagine dropping support for older pandas is not on the table at the moment, is it ?

**Comment by mrocklin** [comment]
Fixes https://github.com/dask/dask/issues/4596

**Comment by mrocklin** [comment]
Merging in 24 hours if there are no comments

**Pull request merged**
