### PR TITLE
Bytes paths

### PR DESCRIPTION
**Pull request by martindurant**
For consistency in how paths are passed around with the backends.

This would require a little knock-on code in distributed.hdfs and gcsfs.dask_link .

### CODE REVIEW

**Comment by mrocklin** [comment]
Is it possible to do this in such a way that slightly older versions of dask.distributed will continue to work, although without the improved feature set?

**Comment by martindurant** [comment]
(Should have gone in the main description)

Previous distributed.hdfs did not work as intended https://github.com/dask/dask/pull/2171 , which is where this came from

**Comment by mrocklin** [comment]
Understood.  I'm not asking for that bug to be retroactively fixed in dask.distributed, I'm asking that we ensure that these changes do not cause dask.distributed tests to break without changes of their own.  We should subsequently make those changes, I'm just trying to make sure that users are allowed some flexibility so that the libraries don't have to be updated in precise lock-step.

**Comment by martindurant** [comment]
Yes, I can confirm that the tests in distributed/tests/test_hdfs pass with these changes in place.

**Comment by DigitalPig** [comment]
I have tested this using:

```python
import dask.dataframe as dd
df = dd.read_parquet('s3://bucket/dask_data/*')
```

and I have the following errors:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-c743efed9868> in <module>()
----> 1 df = dd.read_parquet('s3://mr-meeseeks/testing/dask_data/*')

/home/ec2-user/coding/dask/dask/dataframe/io/parquet.py in read_parquet(path, columns, filters, categories, index, storage_options)
     75
     76     if len(paths) > 1:
---> 77         pf = fastparquet.ParquetFile(paths, open_with=myopen, sep=myopen.fs.sep)
     78     else:
     79         try:

/opt/anaconda/anaconda3.4.3.1/lib/python3.6/site-packages/fastparquet/api.py in __init__(self, fn, verify, open_with, sep)
     43                  sep=os.sep):
     44         try:
---> 45             fn2 = sep.join([fn, '_metadata'])
     46             self.fn = fn2
     47             with open_with(fn2, 'rb') as f:

TypeError: sequence item 0: expected str instance, list found
```

**Comment by martindurant** [comment]
@DigitalPig , are you using the latest fastparquet master?

**Comment by martindurant** [comment]
Gahh, fails on windows paths in LocalFileSystem

**Comment by martindurant** [comment]
@mrocklin , this is a timing sensitive test?
`dask/tests/test_threaded.py::test_interrupt FAILED`

**Comment by mrocklin** [comment]
Yes, it has been breaking recently.  I think that @jcrist is aware of it but he's out this week.

**Comment by mrocklin** [comment]
https://github.com/dask/dask/issues/2192

**Comment by martindurant** [comment]
Rerunning made it pass

**Comment by mrocklin** [comment]
+1 from me

**Pull request merged**
