### PR TITLE
Register a normalizer for literal

### LINKED ISSUE #5897: normalize_token pickles data of literal
While investigating a slow call to `tokenize` I discovered that when a `literal` is passed to a function that tokenizes args, it ends up pickling the quoted data instead of recursively normalising it. This is because there is no normalizer registered for `literal`, so it goes down the generic path for callables, which uses pickle.

Example:
```python
from dask.base import normalize_token
from dask.core import literal

d = {'a': [1, 2], 'b': [3]}
print(normalize_token(d))
print(normalize_token(literal(d)))
```

Output:
```
('list', [('tuple', ['a', ('list', [1, 2])]), ('tuple', ['b', ('list', [3])])])
b'cdask.core\nliteral\np0\n((dp1\nVa\np2\n(lp3\nL1L\naL2L\nasVb\np4\n(lp5\nL3L\nastp6\nRp7\n.'
```

This is on current master.

### PR DESCRIPTION
**Pull request by bmerry**
Closes #5897.

- [x] Tests added / passed
- [x] Passes `black dask` / `flake8 dask`

### CODE REVIEW

**Comment by bmerry** [comment]
I wasn't sure if the return value should include the class of the literal object, so that `tokenize(literal(x))` and `tokenize(x)` would be different. I'm assuming that if both are used then they're intended to mean the same thing, so I haven't.

**Comment by mrocklin** [comment]
Thank you for finding and resolving this issue @bmerry !

My guess is that it's slightly safer to treat them differently.  I can't actually think of a situation where this would matter, but it seems safer to include some slight difference, maybe even just `return "literal", normalize_token(lit())`

**Comment by bmerry** [comment]
Ok, done as you suggested. I had to change the test so it now just tests that the tokenization is consistent, so it's no longer a regression test for #5897. Let me know if you think it's worth adding a test on `normalize_token`.

**Comment by mrocklin** [comment]
Thanks @bmerry !

**Pull request merged**
