### PR TITLE
Autogenerate modules in API

### PR DESCRIPTION
**Pull request by scharlottej13**
Addresses #8656.

This still does not work! But pushing a draft PR to show what I'm trying. The templates are from [here](https://github.com/JamesALeedham/Sphinx-Autosummary-Recursion/tree/master/docs/_templates)

### CODE REVIEW

**Comment by scharlottej13** [comment]
@bryanwweber I think you have some sphinx expertise-- any thoughts on what I can try next here?

**Comment by jsignell** [comment]
Thanks for keeping working on this @scharlottej13! I think the behavior is not quite good enough to merge yet. Let me answer your questions:

> - Do we want to change the templates so all methods show up on one page? With the current templates, you have to click through to get to the method you're looking for (they are not all listed on one page as they are [here](https://docs.dask.org/en/stable/dataframe-api.html), e.g.)

Definitely yes. Ideally our new docs will look very similar to the old docs, but they would be autogenerated.

> - I changed a couple docstrings to get past autosummary errors (`array.core` and `array.slicing`)

:rocket:  that seems fine.

> - Another issue is autogeneration of tests, but I'm working on changing this w/ [`autodoc-skip-member`](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#event-autodoc-skip-member)

This will probably stop being an issue when we move the tests #8662

**Comment by scharlottej13** [comment]
Thanks @jsignell! That answers my questions-- I'll prioritize fixing the templates and then work on excluding the tests (if #8662 is still open).

**Comment by scharlottej13** [comment]
I think this is *much* closer to what we want! Feedback would be much appreciated @jsignell and thanks @bryanwweber for pairing with me on this!

A couple outstanding items:

1. When using the `recursive` option with `sphinx-autosummary-accessors` I get: `ValueError: not enough values to unpack (expected 2, got 1)` on [this line](https://github.com/keewis/sphinx-autosummary-accessors/blob/758d8131604e5c4c3b26b9a38a09684fd77f9f24/sphinx_autosummary_accessors/autosummary.py#L12). An example `match` that causes the error is `[('automodule', 'dask.bag')]` when something like `[('currentmodule', 'dask'), ('autoaccessorattribute', 'dataframe.Series.cat.ordered')]`, e.g. is expected. @keewis maybe you have some insight on this?


2. The main API pages look OK, but could be better! One simple improvement could be to have reference text with the full name that links to the module, or maybe I could add in a short docstrings to the modules themselves? The array-api page, e.g. looks like:
Screen Shot 2022-03-24 at 4 59 47 PM

**Comment by jsignell** [comment]
Thanks for investigating this @scharlottej13! If there is anyway to specialcase the Array class to put a summary at the top level I think that would be a big improvement.

**Comment by scharlottej13** [comment]
Sorry for the delay on this! Main edits:
- added a summary for the Array class in `array-api`
- restructured `dataframe-api` to more closely match the current structure
- [opened a PR](https://github.com/xarray-contrib/sphinx-autosummary-accessors/pull/67) to be able to use `recursive` while `sphinx-autosummary-accessors` is installed

**Comment by bryanwweber** [comment]
Hi @scharlottej13! Sorry for taking so long to get back to you on this PR. This is really excellent work to get the extension working properly and set up the templates!

I had some feedback on the new style as a result of auto-documenting more of the API. In particular, I really miss the _Top Level Functions_ section from the current API docs; one thing I like to do when I don't know the name of a function to use is scroll through that section and see what description matches what I'm trying to do. I also don't love that the submodules (`array.fft` and others) have to click through a link to see the names of the functions.

As we discussed when we were pairing on some of this work, it's a little bit of a limitation of using page templates for the docs. For example, to pull the `array.fft` functions up to the "top" page, the way they are now, would require making the `array-api.rst` page a template itself, which introduces further complications.

Similarly, adding docs for the ufuncs (`array.abs`, `array.absolute`, and more, including in the `dataframe` docs) is tough because they aren't necessarily implemented in `dask`, deferring instead to the implementation in the underlying library and mostly copying the docstring. This makes it hard for Sphinx/the autosummary extension to find the right place to look, and so they don't show up in the top-level page. At least, that's my interpretation of how this works.

That all being the case (especially the last thing there about the ufuncs), plus the fact that the Numpy/pandas APIs are _relatively_ stable (although you did just have to add a few pandas methods), means I'm not totally sure how much benefit the recursive autodocs provides if that's the only thing that we're changing, compared to the cost of losing a bunch of docs.

As such, I don't think it makes sense to merge this PR right now (although I'm just one voice 😄). I think when we have a larger, concerted, effort to improve/consolidate the documentation for Dask/Distributed/and other Dask projects where we can devote more cycles to working around these issues (either in code or in organization of the docs) and then this PR will be a great base to start from!

cc @jsignell @jrbourbeau for your thoughts as well.

I'm attaching a zip file of the built HTML docs from my local machine to this comment. Here are a few screenshots comparing the format as well.

[pr-8657-docs.zip](https://github.com/dask/dask/files/8534519/pr-8657-docs.zip)

Screen Shot 2022-04-21 at 3 28 09 PM
Screen Shot 2022-04-21 at 3 29 38 PM

**Comment by scharlottej13** [comment]
@bryanwweber thank you so much for taking the time to summarize the changes in such detail (and for all your help in getting things this far along!). I agree that right now may not be the right time to make these changes and would be happy to help if/when using `recursive` might make sense.

**Pull request closed without merging**
