### PR TITLE
Improve multi dataframe join performance

### LINKED ISSUE #8739: join should take maximal advantage of _recursive_pairwise_outer_join when present
Right now, when joining more than two DataFrames, Dask uses `_recursive_pairwise_outer_join` for the DataFrames being joined to and performs a final non-parallelized merge. Instead we should allow all of the merges to be computed in parallel.

### PR DESCRIPTION
**Pull request by holdenk**
by allowing recursive merge function to take also operate on the initial frame rather than a separate non-parallel merge.

- [ X ] Closes #8739
- [ X ] Tests added / passed (`py.test dask --verbose -k test_multi.py`)
- [ X ] Passes `pre-commit run --all-files`

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Review by KrishanBhasin — APPROVED** [review]
Oh nice! LGTM 🚀

**Comment by jsignell** [comment]
add to allowlist

**Comment by jsignell** [comment]
Thanks for this change @holdenk and thanks @KrishanBhasin for the review!

**Pull request merged**
