### PR TITLE
Add link to YARN docs

### LINKED ISSUE #3713: Add Yarn documentation
The setup documentation currently includes options like Kubernetes and HPC.  Given the introduction of [dask-yarn](http://dask-yarn.readthedocs.io/en/latest/) it seems reasonable to put a link up for that as well.  This might help to drive traffic to the new project.

One thing to consider is that most people who have a Yarn cluster probably think of it as a Hadoop or Spark cluster and may not recognize the name.  We might consider naming this section "Yarn / Hadoop" for their benefit.  

We should probably also include a small section explaining that many clusters that were originally designed to run Hadoop/Spark/Hive/... use the Yarn resource manager, and that Dask can also use this resource manager natively.

I'm happy to write something up, but also happy to defer to @jcrist , who likely has more experience here.  It might be useful also to provide wisdom in this documentation section that is commonly useful when using Yarn clusters.  I don't have anything in particular in mind, but suspect that something exists.

### PR DESCRIPTION
**Pull request by jcrist**
Adds a link to dask-yarn documentation. The link shows up in the sidebar as well, keeping a uniform feel to the page. Fixes #3713.

### CODE REVIEW

**Comment by jcrist** [comment]
Ping @mrocklin for quick review. I'd prefer to do this over creating a `setup/yarn.rst` page, as that means we have two sets of docs to keep up to date.

**Comment by mrocklin** [comment]
In general this looks good to me.  Thoughts on replacing "YARN" with "YARN / Hadoop" ?  I suspect that more people will correctly identify the term Hadoop than will correctly identify the term YARN.

**Comment by jcrist** [comment]
I'm not sure if that's true for users who use YARN (you can't deploy on YARN without seeing the word YARN everywhere, or using the `yarn` cli tool), but I've made the change.

**Comment by mrocklin** [comment]
I agree that experts who know that they want to use YARN will be fine
regardless.  Mostly I'm thinking about the user that has access to a
standard Hadoop-y installation at their workplace, is curious about Dask,
and wants to try it out.  My guess is that this kind of person will need
help from someone at their institution, but at least this will point them
in the right direction.

**Pull request merged**
