### PR TITLE
Fix CuPy tests or properly marks as xfail

### PR DESCRIPTION
**Pull request by pentschev**
- [ ] Tests added / passed
- [ ] Passes `flake8 dask`

### CODE REVIEW

**Comment by mrocklin** [comment]
Looks like a small linting error

```
$ if [[ $LINT == 'true' ]]; then flake8 dask; fi
dask/array/tests/test_cupy.py:43:49: E251 unexpected spaces around keyword / parameter equals
dask/array/tests/test_cupy.py:44:22: E128 continuation line under-indented for visual indent
The command "if [[ $LINT == 'true' ]]; then flake8 dask; fi" exited with 1.
```

**Comment by pentschev** [comment]
Thanks for pointing it out @mrocklin. Is there a way to get GitHub notifications after builds complete, in particular the ones that fail?

**Comment by mrocklin** [comment]
> Is there a way to get GitHub notifications after builds complete, in particular the ones that fail?

I think that this is all or nothing.  Travis is willing to e-mail us when builds fail, but it would be for all builds, which would be a lot of e-mail.

**Comment by pentschev** [comment]
No worries, I thought there was an option to opt-in only for PRs that you're the author or something, but that's fine. Thanks @mrocklin.

**Comment by mrocklin** [comment]
Thanks @pentschev !

**Pull request merged**
