### PR TITLE
Tokenize bag groupby keys

### LINKED ISSUE #6723: Switch to different, stable hash algorithm in Bag
In #6640, it was pointed out that groupby() doesn't work on non-numerics. The issue: `hash()` is used to group, `hash()` gives different responses for different Python processes. The solution was to set a hash seed.

Unfortunately, Distributed has the same issue (https://github.com/dask/distributed/issues/4141) and it's harder to solve. E.g. `distributed-worker` without a nanny doesn't have a good way to set a consistent seed.

Given that:

1. Until now groupby was broken for non-numerics and no one noticed. So probably not a huge use case.
2. It's hard to solve this with `hash()`.

A better approach might be a different hash algorithm. For example, https://deepdiff.readthedocs.io/en/latest/deephash.html.

deephash seems promising:

```python
from deepdiff import DeepHash
from pprint import pprint

class CustomObj:

    def __init__(self, x):
        self.x = x

    def __repr__(self):
        return f"CustomObj({self.x})"


objects = [
    125,
    "lalala",
    (12, 17),
    CustomObj(17),
    CustomObj(17),
    CustomObj(25),
]

for o in objects:
    print(repr(o), "has hash", DeepHash(o)[o])
```

Results in:

```
$ python example.py 
125 has hash 08823c686054787db6befb006d6846453fd5a3cbdaa8d1c4d2f0052a227ef204
'lalala' has hash 2307d4a08f50b743ec806101fe5fc4664e0b83c6c948647436f932ab38daadd3
(12, 17) has hash c7129efa5c7d19b0efabda722ae4cd8d022540b31e8160f9c181d163ce4f1bf6
CustomObj(17) has hash 477631cfc0315644152933579c23ed0c9f27743d632613e86eb7e271f6fc86e4
CustomObj(17) has hash 477631cfc0315644152933579c23ed0c9f27743d632613e86eb7e271f6fc86e4
CustomObj(25) has hash 8fa8427d493399d6aac3166331d78e9e2a2ba608c2b3c92a131ef0cf8882be14
```

Downsides:

1. This hashing approach, serializing the object to a string and then hashing the string, is probably much more expensive than `hash()`.
2. Custom `__hash__` won't work.

That being said, bag has used `hash()` this way for 4 years, maybe more, it's been broken with Distributed the whole time I assume, so probably that second downside is less relevant. Not sure about the performance aspect, though.

### PR DESCRIPTION
**Pull request by cisaacstern**
- [x] Closes #6723 
- [x] Tests added / passed
- [x] Passes `pre-commit run --all-files`

I wanted to see if this approach could solve effect of non-deterministic hashing of `None` (and containers which contain it) on `dask.bag.Bag.groupby` keys, as discussed in https://github.com/dask/dask/issues/6723#issuecomment-1865838013. It appears that it does!

Opening as a draft as discussion is ongoing in #6723 as to the best solution. I thought it would be helpful to have something concrete to discuss, so offering this in that spirit.

If we do take this route, it's possible we may be able to revert https://github.com/dask/distributed/pull/8400 & https://github.com/dask/dask/pull/6660.

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

Admins can comment `ok to test` to allow this one PR to run or `add to allowlist` to allow all future PRs from the same author to run.

**Comment by cisaacstern** [comment]
Aside from `pandas-nightly`, which IIUC is not related to this PR, the only failures are on:

- `(ubuntu-latest, 3.9)`
- `(ubuntu-latest, 3.10)`

And in both cases `test_bag_groupby_none` fails with timeouts (from the raw logs):

```
[31mFAILED[0m dask/bag/tests/test_bag.py::[1mtest_bag_groupby_none[processes-disk][0m - Failed: Timeout >300.0s
[31mFAILED[0m dask/bag/tests/test_bag.py::[1mtest_bag_groupby_none[processes-tasks][0m - Failed: Timeout >300.0s
```

**Comment by cisaacstern** [comment]
👋 Dask team! This is now ready for review IMHO.

To recap for those who may be getting (back) up to speed on this, https://github.com/dask/dask/issues/6723 is a long-running issue related to the (deliberate) inter-process/session non-determinism of Python's built-in `hash`, which here in `dask.bag` is currently used in a few places for groupby, causing inaccurate grouping when workers do not share a process/session.

https://github.com/dask/distributed/pull/8400 was a partial solution for this for the case of string keys in groupby, but I later realized did not go far enough, as it does not cover the case of `None` being non-deterministically hashed. While `None` as (part of) a key may initially seem uncommon, it's actually quite practical insofar as frozen dataclasses (an otherwise reasonable key type, IMO) will hash non-deterministically if any of their fields are set to `None` when hashed.

Over in https://github.com/dask/dask/issues/6723, there's been extensive discussion spanning years about what the best stable hashing approach might be, but the fix proposed here I think avoids most of the aesthetic/design concerns there by doing something embarrassingly simple: it just **_uses Dask's own `tokenize` to generate a stable hash_**!

My hope is that this should be relatively non-controversial but of course look forward to feedback from those more familiar with this code! In terms of my own motivations, this PR will dramatically unblock my ongoing efforts on the Apache Beam Dask Runner, as Beam internals use `None` extensively as part of group keys.

cc @jacobtomlinson, since you have been following this work 😃

**Comment by fjetter** [comment]
The dask tokenizer is exposed to a more or less similar problem. We recently tried to solve this for tokenize but couldn't come up with a stable version that is stable across machines. see https://github.com/dask/dask/issues/10905 for some references.
There are cases where we have to fall back to cloudpickle which can cause issues.

**Comment by cisaacstern** [comment]
Thanks for that additional context, @fjetter.

I wonder if this PR may still be worth merging, as an incremental improvement over the status quo?

If I understand those linked issue(s) correctly, where `tokenize` still falls short on determinism mostly has to do with complex, user-defined types, and perhaps especially in the distributed context?

Here, I am hoping we can find a way simply to get built-ins (i.e. `NoneType`) to hash deterministically, at the very least in the single-machine multiprocessing context. The current release of `dask.bag` cannot do this; `tokenize` as used here appears to solve that. I am not sure if this solution generalizes to the (multi machine) distributed case as well, but even the single machine multi-processing setting is a huge win IMHO.

In the particular case of the Apache Beam runner I mentioned above, Beam is notably lacking a performant and user-friendly single-machine multi-processing runner. At a minimum, I believe this PR (or something like it), would unblock the Dask backend work there, e.g. by unblocking https://github.com/apache/beam/issues/29365 for single-machine multiprocessing.

Very curious to hear your thoughts. Thanks so much.

**Review by TomAugspurger — COMMENTED** [review]
These changes seem reasonable to me. Would we need to make this change with a deprecation cycle? I'm leaning towards not needing a deprecation, but maybe I'm missing out on some use case where the outcome is sensitive to the hashing.

**Comment by cisaacstern** [comment]
Thanks for weighing in, @TomAugspurger.

Of course will defer to dask folks re: deprecation or not.

**Comment by cisaacstern** [comment]
Just a gentle ping to ask if merging this as an incremental improvement seems like a possibility, or if there would be further changes needed before that happens?

This would still be very impactful to our work on [Pangeo Forge](https://github.com/pangeo-forge/pangeo-forge-recipes) if/when it's able to go in. Thanks so much!

**Review by fjetter — APPROVED** [review]
Sorry, didn't want to stop merging this. I agree this is an improvement and the edge cases that are not handled well by tokenize are likely rarely if ever hit by this code.

I also don't think this needs a deprecation cycle. Thanks for you work and sorry for the delay @cisaacstern

**Comment by cisaacstern** [comment]
Thanks so much, @fjetter !

**Pull request merged**
