### PR TITLE
Building out the HDF5 documentation section

### PR DESCRIPTION
**Pull request by linwoodc3**
Added examples.  Similar to the section added earlier but contains code to build a synthetic HDF5 dataset so users can test.  The additions are:

*  Created new references to new `examples/dataframe-hdf5.rst` page in `source/dataframe-examples.rst` file
*  created new `examples/dataframe-hdf5.rst`
* Added more cross referencing between sections so users can learn more about other features.

### CODE REVIEW

**Comment by mrocklin** [comment]
It looks like there are some git conflicts going on.  Git practice can take some getting used to. 

Generally it's recommended to always perform new work in development branches, not in your master branch.  When we merged your last PR we squashed a lot of those commits together into a single commit.  Your previous commits should not probably be discarded.  This is easy to do if you always do development work in a new branch.  I usually create a new branch as follows

    git checkout -b new-hdf5-docs

In your case we'll need to reset your master branch, make a new branch and switch to it, and then pull in the last commit of your recent work:

```
git checkout master # probably already here, but good to be safe
git checkout -b backup  # create new branch with all of our commits just as a backup
git checkout master # switch back to master, we're about to reset it
git remote add dask https://github.com/dask/dask.git
git remote update dask
git reset --hard dask/master  # reset commits to exactly what is on the master fork/branch
git checkout -b new-hdf5-docs  # make new branch for development work
git cherry-pick 	9c99e00  # Pull in recent commit
git remote add linwoodc3 git@github.com:linwoodc3/dask.git  # add your fork as a remote (you probably already have this)
git push linwoodc3 new-hdf5-docs  # Push to your github fork
```

**Comment by linwoodc3** [comment]
Thanks.  I did everything you types and got a "check mark".  I know how to use git but never worked like this on a project.  Thanks.  I'll keep chipping in on documentation as time allows.  Helps me learn.

**Comment by mrocklin** [comment]
So you'll actually have to close this PR and open a new one from your new branch, new-hdf5-docs.  

It'll be a success when the original commits from your last PR (for example "Adding documenation to create dask DataFrame from HDF5") are no longer included in this PR.

**Comment by mrocklin** [comment]
You could also try asking for live help at the gitter chat.  There are usually people around that can be helpful: https://gitter.im/dask/dask

**Comment by linwoodc3** [comment]
Okie dokie

**Pull request closed without merging**
