### PR TITLE
Update fsspec version

### PR DESCRIPTION
**Pull request by mrocklin**
- [ ] Tests added / passed
- [ ] Passes `black dask` / `flake8 dask`

### CODE REVIEW

**Comment by jrbourbeau** [comment]
`test_json_compressed[xz]` fails due to a change in the `fsspec==0.4.5` release, but has been fixed upstream in https://github.com/intake/filesystem_spec/pull/139. Apologies, I should have raised an issue in the issue tracker here to bring attention to this. 

ping @martindurant @TomAugspurger would it be possible to get a new `fsspec` release?

**Comment by TomAugspurger** [comment]
I can do one in ~5 hours or tomorrow morning.

**Comment by TomAugspurger** [comment]
I'll start an fsspec 0.5 release now.

**Comment by jrbourbeau** [comment]
Thanks for pushing out a new `fsspec` release @TomAugspurger. It looks like tests are passing now (woo!). Do we also want to bump the minimum `fsspec` version to `0.5.1` in `setup.py`?

**Comment by TomAugspurger** [comment]
I didn't follow the fsspec issue too closely. From a skim, it seems sensible to bump the required version though.

**Pull request merged**
