### PR TITLE
Update read_hdf default mode to "r"

### PR DESCRIPTION
**Pull request by rs9w33**
Changed read_hdf function (line 422) to have default mode as 'r' instead of 'a', similar to pandas. See https://github.com/dask/dask/issues/7022#issuecomment-756178918 for elaboration

Closes https://github.com/dask/dask/issues/7022

- [ ] Tests added / passed
- [ ] Passes `black dask` / `flake8 dask`

### CODE REVIEW

**Comment by jsignell** [comment]
Thanks for opening this PR. It looks like the tests are failing because the files are already open in a writable mode. I am not sure how to proceed but maybe @gforsyth or @martindurant can comment on what the behavior should be.

**Comment by gforsyth** [comment]
Hey @rs9w33 -- thanks for putting this in!
I think the two test failures are more of a test structuring problem, in that we shouldn't re-use the same file handler when we are both writing and then reading those files.  I think you can make this change to fix them:

```
diff --git a/dask/dataframe/io/tests/test_hdf.py b/dask/dataframe/io/tests/test_hdf.py
index 418f2d948..93017aefa 100644
--- a/dask/dataframe/io/tests/test_hdf.py
+++ b/dask/dataframe/io/tests/test_hdf.py
@@ -120,8 +120,8 @@ def test_to_hdf_multiple_nodes():
     with tmpfile("h5") as fn:
         with pd.HDFStore(fn) as hdf:
             b.to_hdf(hdf, "/data*")
-            out = dd.read_hdf(fn, "/data*")
-            assert_eq(df16, out)
+        out = dd.read_hdf(fn, "/data*")
+        assert_eq(df16, out)
 
 
 def test_to_hdf_multiple_files():
@@ -203,8 +203,8 @@ def test_to_hdf_multiple_files():
     with tmpfile("h5") as fn:
         with pd.HDFStore(fn) as hdf:
             a.to_hdf(hdf, "/data*")
-            out = dd.read_hdf(fn, "/data*")
-            assert_eq(df, out)
+        out = dd.read_hdf(fn, "/data*")
+        assert_eq(df, out)
 
 
 def test_to_hdf_modes_multiple_nodes():
```

**Comment by rs9w33** [comment]
Hi gforsyth, jsignell, thank you so much for making clear the code changes needed in the pull request! Was easy to implement, even for a git newbie like me :-) https://github.com/dask/dask/pull/7044 Here the other pull request to change the file handling as suggested by gforsyth.

**Comment by gforsyth** [comment]
Hey @rs9w33 -- we're happy to help.  

I think the tests will only pass if both sets of changes are in the same pull request, so you would want to push up a commit including those changes here.  You should be able to use `git` to pull down the branch you made (`patch-1`), make additional changes to it, commit those changes and then push them up here.

**Comment by jsignell** [comment]
Thanks @rs9w33 for this improvement!

**Pull request merged**
