### PR TITLE
.str accessor needs to pass thru both args & kwargs

### PR DESCRIPTION
**Pull request by jreback**
- small fix for windows compat on testing
- xfail test added for possible bug in ``._meta`` determination on derived ``.dask``

### CODE REVIEW

**Comment by jreback** [comment]
cc @tilign

**Comment by jcrist** [comment]
Thanks for the fix.

The issue with the metadata thing is that pandas changes the dtype to object with the NaN there for regex. Inferring metadata in pandas is *hard* because the output dtype changes dependent on if there's missing data. Observe:

```python
In [1]: import pandas as pd

In [2]: import numpy as np

In [3]: x = pd.Series(['a', 'b', 'c', 'D', np.nan], name='x',
   ...:               index=['e', 'f', 'g', 'H', 'I'])

In [4]: x.str.contains('a').dtype
Out[4]: dtype('O')

In [5]: x[:3].str.contains('a').dtype
Out[5]: dtype('bool')

In [6]: x.str.contains('a', na=True).dtype
Out[6]: dtype('bool')

In [7]: x.str.contains('a', regex=True).dtype
Out[7]: dtype('O')
```

Dask infers metadata by running the operation on a small sample of data of the dtype. Since the input is an object series (which we assume are strings), the output is a boolean series, as contains nominally returns a boolean series. However, since the actual data has `NaN` in it, pandas coerces it to an object series. Dask can't know if there's missing data or not without inspecting the actual data, which we can't do. I'm not sure if there's a good way to handle this case - it works well most of the time, but breaks down in cases where missing/non-missing changes the dtype.

**Comment by jreback** [comment]
yeah I *think* this is only an issue with the actual tests, but hard to say. In theory if I am passing in a ``meta`` template I should be passing *object* if I know I have ``nan`` (and am using booleans).

as an aside, this is actually much more efficiently represented by a categorized object when you have booleans and nans, e.g.

```
In [1]: s = pd.Series([True, np.nan, False])

In [2]: s
Out[2]:
0     True
1      NaN
2    False
dtype: object

In [3]: s.astype('category')
Out[3]:
0     True
1      NaN
2    False
dtype: category
Categories (2, object): [False, True]
```

**Comment by jcrist** [comment]
> yeah I think this is only an issue with the actual tests, but hard to say. 

The only reason that test fails is because you have a `NaN` in the series. Otherwise it would pass fine.

> In theory if I am passing in a `meta` template I should be passing object if I know I have nan (and am using booleans).

I might be misunderstanding, but are you suggesting adding the `meta` keyword to all operations? I'm slightly against this, as it would complicate our implementation. It would allow users a way to override the inference if they know it's wrong, but that happens fairly infrequently.

As far as completing this PR, I'd be fine with merging if you remove the xfail and add a simple test to `test_str_accessor` to ensure keyword arguments are passed through. The meta inference issue will need some more thought.

**Comment by jreback** [comment]
> I might be misunderstanding, but are you suggesting adding the meta keyword to all operations? I'm slightly against this, as it would complicate our implementation. It would allow users a way to override the inference if they know it's wrong, but that happens fairly infrequently.

no I mean when passing a ``meta`` kw, the users should be aware that if they are passing a dtype that must NOT have nans AND they expect nans's then this is an error (e.g. boolean or int columns that have nans)

**Comment by jreback** [comment]
updated

**Comment by jcrist** [comment]
Thanks!

**Pull request merged**
