### PR TITLE
WIP/RFC: Support computed task functions and support them through imperative values, used under Bag.map and co

### PR DESCRIPTION
**Pull request by jcorbin**
This PR is an alternative path to #1041 which permits a solution to #1040 without changing the signature of the Bag.map family, and at the same time supports other novel uses such as computed reduction functions.

If this direction is acceptable, then I plan to:
- [ ] breakout just the computed function prep work into a separate PR, and complete tests / polish
- [ ] break out the imperative module work around partialfunc, and consider what may be missed there; for example would we rathe have a special `class PartialFunc` rather than (ab/re)-using the `Value` plumbing?
- [ ] finally this PR would become the final mile support in the bag module, with more tests, and maybe completion for Bag.fold and any other misses

### CODE REVIEW

**Comment by jcorbin** [comment]
Example usage as I haven't gotten this put into a test yet, for Bag.map:
```python
b = dask.bag.from_sequence(range(5))

pf = dask.imperative.partialfunc(
    lambda x, total: float(x) / total,
    args=(),
    kwargs=dict(total=b.sum()))

mf = b.map(pf)

assert sum(mf) == 1.0
```

Similarly for `Bag.map_partitions`:
```python
b = dask.bag.from_sequence(range(100), npartitions=10)

pf = dask.imperative.partialfunc(
    lambda total, part: [float(x) / total for x in part],
    args=[b.sum()],
    kwargs={})

mp = b.map_partitions(pf)

assert sum(mp) == 1.0
```

My only concerns at this point is that the UX of partialfunc isn't very nice, and I'd really rather have a convenience `dask.imperative.partial(func, *args, **kwargs)` wrapper.

**Comment by mrocklin** [comment]
My gut reaction is that this is more technology than we need to solve this problem.  This feels a bit like Pandora's box.

Evaluating the function in a dask graph is a powerful concept and something we might want to do someday.  I don't think we need it to accomplish your goal of including dask values within a `bag.map` call.

Are you comfortable being restricted to using dask values/items as keyword arguments (rather than normal arguments) within `bag.map`?

**Comment by jcorbin** [comment]
Indeed @mrocklin I have no need for the case 2 you mention in #1041 (passing normal arguments).  Further I think I can cope with being limited to keyword arguments.  Also doing that first in bag.map(_partitions) would easily leave room to make it a convenience path for creating a partialfunc if you decide to go that route :-)

**Comment by jcorbin** [comment]
Also note, of the three use cases demonstrated in this PR (.map, .map_partitions, and .reduction) only is it .reduction that seems truly "worth it" since it takes two functions, and adding two sets of arg-dictionaries for them to .reduction would feel like more of a hack. However that support in `.reduction` is a solution seeking a problem as it was something I did "while in the room" rather than "with a use case".

Aside: despite the fact that I empathize with the "too much technology" sensation here, I was really impressed with how little it took to carve out the core support for computed functions: https://github.com/dask/dask/compare/master...jcorbin:computed_funcs .

**Comment by jcorbin** [comment]
This PR has served its conversational purpose ;-)

**Pull request closed without merging**
