### PR TITLE
Pass delimiter to fsspec in bag.read_text

### LINKED ISSUE #7293: bag.read_text linedelimiter option has unexpected behavior
Based on the documentation my assumption is dask.bag.read_text is suppose to return a bag of lines which are defined by the passed linedelimiter.  However, specifying a non-default linedelimiter has unexpected behavior.

```python
import dask.bag as db

open('test.txt','w').write('abc\nababa\n')
print(db.read_text('test.txt').take(2))
print(db.read_text('test.txt',linedelimiter='a').take(2))
print(db.read_text('test.txt',linedelimiter='a',blocksize=1).take(2))
print(db.read_text('test.txt',linedelimiter='b',blocksize=1).take(2))
```

This prints out:

```
('abc\n', 'ababa\n')
('abc\n', 'ababa\n')
('abc\n', 'a')
('ab',)
```

Keeping the default results in the expected tuple of two lines.  Changing the delimiter to 'a' produces exactly the same result, ignoring the passed linedelimiter.  Setting the blocksize to 1 shows that the passed linedelimiter may be used when creating partitions, if not items (although the first 'a' instance is not separated).  I cannot rationalize the result with the 'b' delimiter where only one item is returned from take(2).

**Environment**:

- Dask version: 2021.02.0
- Python version: 3.8.5
- Operating System: Ubuntu 20.04
- Install method (conda, pip, source): pip

### PR DESCRIPTION
**Pull request by martindurant**
- [x] Closes #7293
- [x] Tests added / passed
- [x] Passes `black dask` / `flake8 dask`

### CODE REVIEW

**Comment by martindurant** [comment]
Before adding tests, @dkoes can you confirm that this has the behaviour you would expect? It will still "convert" newlines according to StringIO semantics, if you use one of the recognised newline possibilities.

I don't particularly see a problem with materialising the list instead of making generators, since the dask task will produce lists anyway.

**Comment by dkoes** [comment]
I don't have a lot of confidence in reviewing dask internals code, but that does look like it would implement a generic line delimiter.  But won't it potentially insert an extra one at the very end of the file even if one doesn't exist?  That is, `abc\nabc` will become `(abc\n, abc\n)`

**Comment by martindurant** [comment]
Interesting that this fails on windows ("\r\n"). We should check that the test was, in fact, correct!

**Comment by dkoes** [comment]
Looks like it should work, but when I wrote a test it did not pass with blocksize passed:

```python
        longstr = 'abc\ndef\n123\n$$$$\ndog\ncat\nfish\n\n\r\n$$$$hello'
        with filetexts({'.test.delim.txt': longstr}):
            assert read_text(".test.delim.txt",linedelimiter='$$$$').count().compute() == 3
            assert read_text(".test.delim.txt",linedelimiter='$$$$',blocksize=2).count().compute() == 3
            vals = read_text(".test.delim.txt",linedelimiter='$$$$').compute()
            assert vals[-1] == 'hello'
            assert vals[0].endswith('$$$$')
            vals = read_text(".test.delim.txt",linedelimiter='$$$$',blocksize=2).compute()
            assert vals[-1] == 'hello'
            assert vals[0].endswith('$$$$')
```

**Comment by martindurant** [comment]
What do you expect to happen if the separator is larger than the blocksize??

It actually seems to work, except that you get `[""]` from an empty block. With the tests changed as in the last commit, it passes. Is this reasonable? I don't know how to distinguish between two successive separators and an empty block.

**Comment by martindurant** [comment]
(still fails windows line ending)

**Comment by dkoes** [comment]
I think you still get empty blocks with a blocksize of 6 though, so it isn't just the relationship between the delimiter length and blocksize.  I thought empty blocks got cleaned up somewhere (they do with the newline case).

**Comment by martindurant** [comment]
I hope everyone appreciates that I had to boot into Windows to get this right!

**Comment by martindurant** [comment]
@jsignell , want a look?

**Review by jsignell — APPROVED** [review]
This looks good to me!

**Pull request merged**
