### PR TITLE
Implement filters for _read_pyarrow

### PR DESCRIPTION
**Pull request by gsakkis**
Fixes https://github.com/dask/dask/issues/4255

### CODE REVIEW

**Comment by mrocklin** [comment]
cc @xhochy 

@gsakkis this could probably use a test

Also, see https://github.com/dask/dask/pull/4336 for an alternate approach

**Comment by mrocklin** [comment]
> Also, see #4336 for an alternate approach

Though that PR may likely take a while, so this kind of fix would still be welcome short term.

**Comment by gsakkis** [comment]
Tests have been updated

**Comment by mrocklin** [comment]
I'm going to give this another day in case @xhochy has time.  Otherwise I'll merge it tomorrow.

**Comment by mrocklin** [comment]
Merging.  Thanks for the contribution @gsakkis !  It's good having you around.

**Pull request merged**
