### PR TITLE
update cheat sheet

### PR DESCRIPTION
**Pull request by electronwill**
update cheat sheet

### CODE REVIEW

**Comment by electronwill** [comment]
New version from @VictoriaODell .

**Comment by electronwill** [comment]
@mrocklin I believe this is ready to merge.

**Comment by kerrywatson1** [comment]
I proofed it and found one typo, changed fequencies() to frequencies() in the attached new version. 

The main change is the addition of the logo. @mrocklin also added some examples, modified "Create Dask DataFrame from CSV files" section, and proofed and okayed them in May. 

[Dask_CheatSheetv2_v8.pdf](https://github.com/dask/dask/files/364270/Dask_CheatSheetv2_v8.pdf)

@electronwill this can be merged with the attached pdf.

**Comment by mrocklin** [comment]
My apologies for the delay.  I'll have more time to review this after the
weekend.

**Comment by kerrywatson1** [comment]
Matt, I annotated my copy as I proofed it, so if you review the circled
items it may make your job easier. If the circled items look okay I'd like
to get it on the site ASAP. Kerry

[image: Inline image 1]

_______________________________

Kerry Watson
Documentation manager

[image: Continuum Analytics] <http://continuum.io>

**Comment by electronwill** [comment]
The new pdf looks great, and I've uploaded the new version with frequencies() to this pull request. However, the image with items circled isn't displaying for me.

**Comment by mrocklin** [comment]
Should I merge this?

**Comment by kerrywatson1** [comment]
Yes, thanks Matt.

_______________________________

Kerry Watson
Documentation manager

[image: Continuum Analytics] <http://continuum.io>

**Pull request merged**
