### PR TITLE
Update Anaconda link in "Paid support" section of docs

### PR DESCRIPTION
**Pull request by martindurant**
In "paid support" - old page was retired

- [ ] ~Closes #xxxx~
- [ ] ~Tests added / passed~
- [ ] ~Passes `pre-commit run --all-files`~

### CODE REVIEW

**Comment by jbednar** [comment]
Looks good! I believe makepath.com will also be happy to help with Dask, particularly for geoscience applications.

**Comment by martindurant** [comment]
> I believe makepath.com will also be happy to help with Dask

Can you please tag someone to propose this from their side? We should probably have that as a separate PR in case it requires discussion.

**Comment by brendancol** [comment]
@martindurant @jbednar hey hey thanks for thinking of us!

Definitely want to help with Geospatial Dask!

A good link would be: https://makepath.com/contact/

**Review by jrbourbeau — APPROVED** [review]
Thanks for the fix @martindurant. This is in

@brendancol would you be up for opening a PR which adds an entry for makepath? 

EDIT: I should note that the CI failures here are unrelated and have been resolved elsewhere

**Pull request merged**
