### PR TITLE
Make da.RandomState extensible to other modules

### PR DESCRIPTION
**Pull request by mrocklin**
This enables other libraries like cupy or randomgen to compose their
random modules with dask array.

Fixes https://github.com/dask/dask/issues/3993

- [ ] Tests added / passed
- [ ] Passes `flake8 dask`

### CODE REVIEW

**Comment by mrocklin** [comment]
I ended up wanting this for some cupy experiments.

@dhirschfeld can I ask you to give this a spin?

**Comment by mrocklin** [comment]
Alas: https://github.com/cupy/cupy/issues/1675

**Comment by dhirschfeld** [comment]
Only back in the office today so I *probably* won't get a chance to test until at least tomorrow...

**Comment by dhirschfeld** [comment]
Looks like it works great!

image

**Comment by mrocklin** [comment]
Thanks for verifying @dhirschfeld

**Comment by dhirschfeld** [comment]
Thanks for adding this functionality - it makes for a very quick/easy win for end users!

**Pull request merged**
