### PR TITLE
Open HDF files in read-only mode for reading.

### PR DESCRIPTION
**Pull request by stefanseefeld**
This patch allows a given HDF file to be opened multiple times for reading.

### CODE REVIEW

**Comment by jcrist** [comment]
Looks fine to me. Is There an easy way to test this?

**Comment by stefanseefeld** [comment]
I have slightly refined the patch to allow users to specify the file mode, rather than imposing 'r'. With this change all existing tests pass. I have also added a new test that demonstrates that with that change it's possible to call read_hdf(mode='r') while someone else already keeps an open HDFStore in read-only mode (as is the case in the code I'm working with).

**Comment by jcrist** [comment]
Since our interface here is just a reading function, is there ever a reason to open in other than `'r'`? I'd prefer not to add another keyword that we have to maintain unless there's a reason to.

**Comment by stefanseefeld** [comment]
I share your concern, and mandating 'r' was my initial thought. However, as it turns out, the existing tests contained a use-case where a HDFStore was already open in default mode ('a'), which triggered an error when opening the file again in read-only mode. (See https://github.com/dask/dask/blob/master/dask/dataframe/tests/test_io.py#L760-L765)
I'm not sure how frequent that use-case is, but it required the full exposure of the 'mode' keyword to work in these different cases.

**Comment by jcrist** [comment]
Ok, this sounds reasonable to me. Just trying to understand how hdf5 file modes work. The file in that test is open in `'a'` mode, and is then read in `'a'` mode (which will open it multiple times when computed). So the only restriction is if a file is open in `'r'` mode then all have to be open in `'r'` mode?

**Comment by stefanseefeld** [comment]
Yes, that's my understanding. (I'm not even sure having the file open in 'a' mode multiple times makes any sense in practice. At least the user needs to know exactly what (s)he is doing...)

**Comment by jcrist** [comment]
Alright, this seems good to me then. Thanks!

**Pull request merged**
