### PR TITLE
Add dask.array.multinomial

### LINKED ISSUE #1149: Multinomial random generator
`dask/array/random.py` is missing a multinomial random generator (there is aplaceholder `# multinomial`).

Will dask have a multinomial random generator at some point? Does it require a significantly different approach than the other generators?

### PR DESCRIPTION
**Pull request by mrocklin**
Fixes #1149

### CODE REVIEW

**Comment by yoavram** [comment]
OK, so at first I got an error `ValueError: shape can only contain integers.` which I fixed by setting `size=1` (maybe default value should be 1 instead of `None`?).

Then I got `ValueError: shape-mismatch for sum` which I'm not sure how to solve.
You can reproduce the error with this notebook: https://github.com/yoavram/ipython-notebooks/blob/master/dask-multinomial.ipynb

**Comment by mrocklin** [comment]
We should definitely improve those error messages.  Two things

1.  Currently we expect the first two parameters to not be dask-things.  This can implemented, but it's somewhat tricky and error prone so it's low on my TODO list.
2.  Currently chunks should match size.  So if `size=1` then `chunks=1`.  The extra dimension caused by the multinomial nature will be added on regardless of user input.  We're following the tradition of `np.random.multinomial` which doesn't expect users to add dimensions to `size`.

**Comment by mrocklin** [comment]
@yoavram what is your objective?

**Comment by yoavram** [comment]
1. So I should do `compute` before giving it to the `multinomial`? That would limit my graphs to single iterations of the loop rather than the whole loop, right?

Objective: I want to do calculations similar to the one in the notebook above, with big matrices - M shape 1000x1000 or even 10000x10000 - and for possibly millions of iterations.

**Comment by mrocklin** [comment]
In this case I suspect that limiting the graph to single iterations of the loop is a good thing.  There doesn't appear to be any parallelism that can cross creating that intermediate result so you might as well cut the graph at that point and start over with a new one.  

The scheduler will also appreciate this, as graphs with more than a million tasks will probably start to become annoying (each task is perhaps on the order of 100-1000 bytes)

**Comment by yoavram** [comment]
OK, thanks, I'll try it. 
"while I have you here" - is there any benefit using dask (rather than numpy) for this kind of computation if the "data" (here the arrays `M` and `v`) are small enough to keep in memory?

**Comment by mrocklin** [comment]
You might get some speedup from multiple cores.  I'd time the same computation in numpy and dask and see if there is a significant difference.  If not then I'd just stick with numpy.  

I suspect that your bottleneck is in the matrix-vector multiply.  If so then it's probably best to stick with numpy but pay attention to the BLAS library you're linked against.  That'll probably give you multi-core parallelism all on its own.  If so then naive use of dask.array might actually be *slower* as the two multi-core libraries fight for threads.

If you're linked against a single-threaded BLAS library then dask.array would be a cheap way to get multi-core, I suspect it'd be 20% slower than optimized OpenBLAS though.

**Comment by mrocklin** [comment]
I'm going to go ahead and merge this as is for now.  We're close to a release.

**Pull request merged**
