### PR TITLE
CI: force nightly pyarrow in the upstream build

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
Same as https://github.com/dask/dask/pull/8993, but now doing it earlier in the cycle

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
It's still not clear to me how to have it robustly install the latest development version, I opened https://github.com/mamba-org/mamba/issues/1682 about this

**Review by jrbourbeau — COMMENTED** [review]
Thanks for filing the upstream issue @jorisvandenbossche. As a temporary workaround, what if we use `mamba search` to get the latest `pyarrow` nightly release version (similar to what we do over in `distributed` [here](https://github.com/dask/distributed/blob/41ecbca2f94f029ebcbcaa1bbe5ae059e4858865/.github/workflows/conda.yml#L50-L54))? Something like (the code below is untested):

```bash
# Workaround for https://github.com/mamba-org/mamba/issues/1682
arr=($(mamba search --override-channels -c arrow-nightlies pyarrow | tail -n 1))
export PYARROW_VERSION=${arr[1]}
mamba install -y -c arrow-nightlies "pyarrow=$PYARROW_VERSION"

**Review by jrbourbeau — APPROVED** [review]
Thanks @jorisvandenbossche!

**Comment by jorisvandenbossche** [comment]
It indeed seems to have worked. Thank you for the suggestion!

**Pull request merged**
