### PR TITLE
Add support for ``numeric_only=False`` in ``DataFrame.var``

### PR DESCRIPTION
**Pull request by phofl**
- [ ] Closes #xxxx
- [ ] Tests added / passed
- [ ] Passes `pre-commit run --all-files`

### CODE REVIEW

**Comment by phofl** [comment]
Yes, that's a good point. Is on my todo list as well, but wanted to do this as follow up to avoid too many merge conflicts

**Comment by hendrikmakait** [comment]
> Yes, that's a good point. Is on my todo list as well, but wanted to do this as follow up to avoid too many merge conflicts

Makes sense, could you create a small issue for that so that we keep it on our radar?

**Review by hendrikmakait — APPROVED** [review]
LGTM as long as we clean up tests in a follow-up. Thanks, @phofl!

**Comment by phofl** [comment]
https://github.com/dask/dask/issues/10265

**Pull request merged**
