### PR TITLE
Implement ma.*_like functions

### LINKED ISSUE #9301: Mask preserving *_like functions
It would be useful to have versions of `ones_like`, `zeros_like` and `empty_like` that preserve masks when applied to masked dask arrays.  Currently (version 2022.7.1) we have

```python
import dask.array as da

array = da.ma.masked_array([2, 3, 4], mask=[0, 0, 1])
print(da.ones_like(array).compute())
```
```
[1 1 1]
```
whereas numpy's version preserves the mask
```python
import numpy as np

print(np.ones_like(array.compute()))
```
```
[1 1 --]
```

I notice there are several functions in `dask.array.ma` that just apply `map_blocks` to the `numpy.ma` version of the function.  So perhaps the simplest thing would be to implement `dask.array.ma.ones_like`, etc. that way.  If it really is that simple, I'd be happy to open a PR.

### PR DESCRIPTION
**Pull request by rcomer**
Implements `ones_like`, `zeros_like` and `empty_like` within `dask.array.ma`.  I also looked at `full_like`, but that does not currently exist in `numpy.ma`, so I left it out for simplicity.

Note that until recently (https://github.com/numpy/numpy/pull/19899), `ones_like` and `zeros_like` were missing from `numpy.ma.core.__all__` and therefore did not appear in the `numpy.ma` namespace.  So I am using `numpy.ma.core` directly.

- [x] Closes #9301
- [X] Tests added / passed
- [X] Passes `pre-commit run --all-files`

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

Admins can comment `ok to test` to allow this one PR to run or `add to allowlist` to allow all future PRs from the same author to run.

**Comment by ncclementi** [comment]
add to allowlist

**Comment by rcomer** [comment]
I forgot they would also need adding to the docs.  Is it just a case of including them in https://github.com/dask/dask/blob/main/docs/source/array-api.rst?

**Comment by rcomer** [comment]
Thanks @jsignell!

**Comment by pavithraes** [comment]
@rcomer Hi! Thanks for working on this! We'll be highlighting this PR in a "release highlights" Twitter post. Would you be comfortable sharing your Twitter handle with me so we can tag you in it?

**Comment by rcomer** [comment]
Thanks @pavithraes!  I am [flyingcomer](https://twitter.com/flyingcomer) on Twitter but not very active there.  (I see you have already found me!)

**Pull request merged**
