### PR TITLE
Add retry logic to test_shuffle_priority

### PR DESCRIPTION
**Pull request by rjzamora**
A new `test_shuffle_priority` test was recently added in  #7846. While this test does consistently fail when shuffle "split" tasks are not prioritized, it does *occasionally* fail when the priorities are set correctly (due to the non-deterministic nature of the scheduler).  This PR adds simple retry logic in the test to make it less likely to cause CI issues in the future.

### CODE REVIEW

**Review by jrbourbeau — COMMENTED** [review]
Just merged `main` to resolve the unrelated macOS Python 3.7 CI failure

**Comment by jrbourbeau** [comment]
Thanks for the update @rjzamora! Long-term I'd like to see this test be more deterministic, but don't have a concrete suggestion about how to do this at the moment. The changes here are definitely an improvement over the current situation.

Instead of putting a `for` loop inside this test, could we use the `@pytest.mark.flaky` marker from [`pytest-rerunfailures`](https://github.com/pytest-dev/pytest-rerunfailures) to automatically rerun the test when a failure happens? For example, this is similar to what we do here 

https://github.com/dask/dask/blob/364d799e177ad93020d60b4504fb5ab34ab1588f/dask/tests/test_base.py#L1366

Using the `flaky` marker will, I think, more visibly signal the flakyness of this test to other maintainers

**Comment by rjzamora** [comment]
>Using the flaky marker will, I think, more visibly signal the flakyness of this test to other maintainers

Thanks for the suggestion @jrbourbeau - Good call.  I didn't realize I needed "pytest-rerunfailures" to get `@pytest.mark.flaky` working :)

**Review by jrbourbeau — APPROVED** [review]
Thanks @rjzamora

**Pull request merged**
