### PR TITLE
Adding support for string timedelta in `map_overlap`

### LINKED ISSUE #9554: Adding support for string timedelta in map_overlap before/after parameters
It would be convenient to allow string timedelta in _map_overlap_ _before_ and _after_ parameters:

`dask.dataframe.rolling.map_overlap(func, dd, before='5min', after=0)`

Also setting a default value to zero could improve readability:

`dask.dataframe.rolling.map_overlap(func, dd, before='5min')`

I can work on a PR, if it makes sense.

### PR DESCRIPTION
**Pull request by epizut**
- [x ] Closes #9554
- [x ] Tests added / passed
- [x ] Passes `pre-commit run --all-files`

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

Admins can comment `ok to test` to allow this one PR to run or `add to allowlist` to allow all future PRs from the same author to run.

**Comment by jsignell** [comment]
ok to test

**Review by jsignell — APPROVED** [review]
This looks very reasonable and straightforward to me! Thanks @epizut for the PR!

**Review by jrbourbeau — APPROVED** [review]
Thanks @epizut! This is in

**Pull request merged**
