### PR TITLE
Add issue template

### PR DESCRIPTION
**Pull request by mrocklin**

### CODE REVIEW

**Comment by mrocklin** [comment]
cc @martindurant @jcrist for feedback

**Comment by martindurant** [comment]
A request to include the versions of all packages concerned, python and OS?

**Comment by jreback** [comment]
FYI when you merge things, the template is often included (as its in the top-of-PR). I generally clean them up on merging.

**Comment by mrocklin** [comment]
Does this go away if we prepend with git comment characters (#)?

**Comment by jreback** [comment]
@mrocklin sorry I deleted this because I was referring to the PR template (not sure if you have that). The issue template is good.

**Comment by mrocklin** [comment]
I've added versions.  Merging soon if no further comments.

**Pull request merged**
