### PR TITLE
Bump to numpy >= 1.13, pandas >= 0.21.0

### LINKED ISSUE #4580: Increase minimum supported NumPy/Pandas versions
Currently we claim to require the following versions:

```python
extras_require = {
  'array': ['numpy >= 1.11.0', 'toolz >= 0.7.3'],
  'bag': ['cloudpickle >= 0.2.1', 'toolz >= 0.7.3', 'partd >= 0.3.8'],
  'dataframe': ['numpy >= 1.11.0', 'pandas >= 0.19.0', 'toolz >= 0.7.3',
                'partd >= 0.3.8', 'cloudpickle >= 0.2.1'],
  'distributed': ['distributed >= 1.22'],
  'delayed': ['toolz >= 0.7.3'],
}
```

Do we want to increase some of these versions?  I think that this question is motivated by two parts:

1.  How much of a pain for maintainers is it to support older versions?
2.  How much of a pain for users is it to upgrade?

We don't currently receive any complaints of the form "Dask's version requirements are too modern for me to use", so we can probably push things a bit.  

cc @TomAugspurger @jcrist @jakirkham

### PR DESCRIPTION
**Pull request by jcrist**
Increases the minimum versions of these dependencies, and removes backwards compat fixes for the previous versions (quite a lot of code!!).

Fixes #4580.

### CODE REVIEW

**Comment by jakirkham** [comment]
Thanks for working on this @jcrist. Am happy to see so much code removed. Also nice to see only a couple of test failures. These appear to be Pandas specific and are really just failures from the docstring tests due to whitespace changes. Should be straightforward to fix.

**Comment by jcrist** [comment]
All green now.

**Comment by jcrist** [comment]
Merging later today if no comment.

**Comment by mrocklin** [comment]
Thanks @jcrist

**Pull request merged**
