### PR TITLE
Allow dask arrays to contain numpy arrays as elements

### PR DESCRIPTION
**Pull request by jlintusaari**
This feature came from a personal need when working with a project planned to use dask (which is a very nice library I must say). 

I need to apply user defined functions on numpy arrays. The requirement for these user defined functions is that they operate on a numpy array and return a numpy array. They will always maintain the main axis (axis 0) but may change the inner dimension. Therefore we can count that the main axis will always remain the same in the transformation. 

Therefore I need to be able to represent only the main axis as a dask array and the elements of this array would be numpy arrays of constant shape. We just don't know the exact shape of the sub arrays until the computation has actually occurred. With the proposed change we can achieve this and it won't alter existing supported behaviour.

It is a bit similar idea to having `np.zeros(6, dtype='(2, 3)float32')` which will actually in the end create a numpy array of shape `(6, 2, 3)`. Here we have a single main axis containing subarrays of shape (2, 3).

I will add the tests and other needed things if you are favourable for this addition.

### CODE REVIEW

**Comment by shoyer** [comment]
I'm not sure I understand the use case here. Can you give a concrete example?

> Therefore I need to be able to represent only the main axis as a dask array and the elements of this array would be numpy arrays of constant shape. We just don't know the exact shape of the sub arrays until the computation has actually occurred.

This is at odds with the dask.array data model, which expects that it knows the full shape of every array element. I suspect that well more than `concatenate3` would break, though it's hard to say without testing. I don't think it's a good idea to extend the dask array data model to include arrays with unknown inner dimension sizes.

The most straightforward way to do this (which would work currently) would be to make a dask array with `dtype=object` and stuff numpy arrays inside it for each element. Or you could require your users to specify the shape of arrays before doing the computation.

**Comment by jlintusaari** [comment]
Hi,

sure here is a toy example

```python
# Define two arbitrary transformations
# takes the sum along axis=1
map1 = lambda a: np.sum(a, axis=1, keepdims=True)
# expands a scalar value to a (2,2) numpy array
map2 = lambda a: np.reshape(np.repeat(a, 4), (len(a), 2, 2))

# Construct a dask array holding numpy arrays of unknown size to dask.
# In this toy example of course the size could be known, but `a`
# and `b` could come from a function outputting numpy arrays of constant shape
name = 'arr'
a = np.array([[1,2,3], [4,5,6]])
b = np.array([[7,8,9]])
dask = {
    (name, 0): a,
    (name, 1): b,
}
# note that this appears now a 1d array for dask where each element is at this 
# moment a (1,3) vector defined as dtype='object'
chunks = ((2,1),)
arr = da.Array(dask, name, chunks, dtype='object')
print(arr.shape)
print(arr.compute())
# (3,)
# [[1 2 3]
#  [4 5 6]
#  [7 8 9]]

# take the sum of arrays of unknown length to dask
arr2 = arr.map_blocks(map1)
print(arr2.shape)
print(arr2.compute())
# (3,)
# [[ 6]
#  [15]
#  [24]]

# expand each sum to a (2,2) numpy array
arr3 = arr2.map_blocks(map2)
print(arr3.shape)
print(arr3.compute())
# (3,)
# [[[ 6  6]
#   [ 6  6]]
#
#  [[15 15]
#   [15 15]]
#
#  [[24 24]
#   [24 24]]]
```

> This is at odds with the dask.array data model, which expects that it knows the full shape of every array element. 

Yes, it does make it a bit more relaxed, but we can think of the elements as objects. So the dask array shape is fully known, but just holds objects that happen to be numpy arrays.

> I suspect that well more than concatenate3 would break, though it's hard to say without testing.

So concatenate3 works as before, but it just allows now the numpy arrays to have a greater dimension than the chunking defines (hence achieving subarrays, before you'd get indexing errors). The only potential problem I can think of is that now the memory size of each element object is unknown until after execution.

The latter while loop was redundant in the earlier code, because `chunks_from_arrays` would fail if the condition was true.

> The most straightforward way to do this (which would work currently) would be to make a dask array with dtype=object and stuff numpy arrays inside it for each element. 

This is true and the above example basically does what you suggest but just in a vectorized form as you can just give numpy arrays to the dask array blocks. Each element will be of dtype object. I'm afraid that elementwise dealing would kill performance because the arrays are large and I need to perform vectorized operations on them.

> Or you could require your users to specify the shape of arrays before doing the computation.

This I would really like to avoid :)

**Comment by shoyer** [comment]
There are lots of dask array and numpy operations (e.g., transpose, broadcasting as used in all arithmetic operations, negative `axis` arguments for methods such as `sum`) where semantics depend on knowing the rank an array. Indexing (without using `...`) does not, but that is the exception, not the rule.

I would be open to allowing arrays with known rank but unknown shape (by allowing `None` as a valid element in `chunks`). This could be done largely within the same data model, because the block layout scheme would remain unchanged, and would be useful for other applications as well (e.g., boolean indexing). However, this would still be a major overhaul of dask array internally (my guess is at least a week's effort) because it would entail auditing and tests for every single dask.array function.

**Comment by jlintusaari** [comment]
Thank you for your response. I clarified the pull request even further by explaining the extended behaviour in more detail in the method documentation with an added example. I also removed the cleanup I made. It is now in its bare minimum. I'd really appreciate if you'd be able to review it once more.

I'm working on a computational framework software research project and we are currently seeking a library to parallelize the computations. Dask seems to be a great fit but we need the ability to place subarrays into arrays. Numpy is flexible in it, that if you create an array from constant shaped subarrays, it will result into one big array. Essentially this is the flexibility we need.

> The most straightforward way to do this (which would work currently) would be to make a dask array with dtype=object and stuff numpy arrays inside it for each element.

Even this doesn't work with the current dask version, because numpy creates this one big array from subarrays, so the dtype changes to the dtype of the subarray elements. With the proposed change, this would be possible.

> There are lots of dask array and numpy operations (e.g., transpose, broadcasting as used in all arithmetic operations, negative axis arguments for methods such as sum) where semantics depend on knowing the rank an array. Indexing (without using ...) does not, but that is the exception, not the rule.

The change won't influence to the typical workflow or existing implementations because we only naturally extend `concatenate3` to where it's behaviour was previously undefined (you'd get indexing errors). In fact, to create a dask array of subarrays in the first place, you need to go though the constructor as I did in the earlier post. So I'm seeking the flexibility of the basic numpy arrays when we work with extended dask arrays. We use mainly the dask array constructor, map_blocks and indexing. Even the methods you mentioned will work correctly if you provide the axes along which the operations are performed. In essence the framework shouldn't need to provide protection for the extended use. This is the responsibilty of the extender.

The proposed extension to the dask array definition that will allow element arrays in a nutshell:
- The resulting concrete array must match the shape of the dask array in every dimension of the dask array (same as currently)
- Any leftover dimensions must have a constant shape (this makes element arrays possible)

I have been persistent with this because we really love dask and would like to use it. I will not pursue this any further though, as we also need to move forward. We will respect any decision you make regarding this and thank you for your consideration.

**Comment by shoyer** [comment]
> > The most straightforward way to do this (which would work currently) would be to make a dask array with dtype=object and stuff numpy arrays inside it for each element.
> Even this doesn't work with the current dask version, because numpy creates this one big array from subarrays, so the dtype changes to the dtype of the subarray elements. With the proposed change, this would be possible.

OK, this is definitely a bug then and we would gladly accept patches to fix it. If all you need is `map_blocks` and indexing, it sounds like a `dtype=object` array would cover your use cases. Or you could build your own data structure on top of dask, using dictionary or the `dask.delayed` interface.

> In essence the framework shouldn't need to provide protection for the extended use. This is the responsibilty of the extender.

Unfortunately, in my experience this doesn't work very well. If we embrace such a change, we need to embrace it fully. (Which, in turn, entails the significant costs I mentioned above.)

If you make use of dask.array in ways that violate internal assumptions, you are going to be in for a bad time, because other aspects of dask internals could change to break you at any time (including in patch releases).

On the other hand, adding this functionality in a limited fashion makes for a bad user experience, because it's no longer clear to other users what should or should not work. They are likely to try a different set of dask.array functions than those you use, and they will complain when it doesn't work or breaks. This influences their opinion of the entire project.

**Comment by shoyer** [comment]
It's worth noting that https://github.com/dask/dask/pull/1840 will add support for dask arrays with unknown shape.

**Comment by mrocklin** [comment]
Closing this as stale.  Please feel free to speak up if anyone would like to take this on again.

**Pull request closed without merging**
