### PR TITLE
add resample methods

### PR DESCRIPTION
**Pull request by quasiben**
- [ ] Tests added / passed
- [ ] Passes `black dask` / `flake8 dask`

closes https://github.com/dask/dask/issues/5547

### CODE REVIEW

**Comment by TomAugspurger** [comment]
LGTM. Do you think you got all the relevant methods?

**Comment by quasiben** [comment]
@TomAugspurger , this PR adds nunique, size, and quantile.  That brings in all of the [computations/descriptive-stats](https://pandas.pydata.org/pandas-docs/stable/reference/resampling.html#computations-descriptive-stats) .  Do you think we should go after the upsampling methods as well ?  ffill, backfill, fillna, etc ?

**Comment by quasiben** [comment]
@TomAugspurger, all tests passing now.   I think descriptive-stats is enough.  @birdsarah do you have thoughts here ?

**Comment by TomAugspurger** [comment]
I think we're good here, thanks. Can do the others as followups if needed.

**Pull request merged**
