### PR TITLE
Remove additional pandas warnings in tests

### PR DESCRIPTION
**Pull request by mrocklin**
- [ ] Tests added / passed
- [ ] Passes `flake8 dask`

### CODE REVIEW

**Comment by mrocklin** [comment]
Merging shortly if there are no further comments

**Comment by jrbourbeau** [comment]
Do we want to deprecate `clip_lower` and `clip_upper` in Dask? I'm not sure what's been done in these situations in the past

**Comment by mrocklin** [comment]
My guess is that the pandas warning will pass through to users.  I haven't
actually checked the implemention yet though.  I'll check in a bit.

**Comment by mrocklin** [comment]
Yeah, we just call `map_partitions(M.clip_upper, ...)` so we'll end up calling this function on the `meta` object, which will trigger the warning from Pandas

**Comment by mrocklin** [comment]
OK to merge @jrbourbeau ?

**Comment by jrbourbeau** [comment]
Yeah, this LGTM

**Pull request merged**
