### PR TITLE
Defer order/casting einsum parameters to NumPy implementation

### LINKED ISSUE #4898: [BUG] dask.array.einsum doesn't support CuPy backend
Running into numpy array related issues when trying to use cupy arrays with einsum. Looks like it's perhaps due to still getting to the `asarray` branching logic which appears to be set to True somewhere internally, despite the cupy inputs. Perhaps it's being reset or not fully passed down from the original arrays to an intermediate array.

```python
import cupy as cp
import dask.array as da
​
A = cp.array([0., 1, 2])
​
B = cp.array([[ 0,  1.,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])
​
dA = da.from_array(A, asarray=False)
dB = da.from_array(B, asarray=False)
​
res = da.einsum('i,ij->i', dA, dB).compute()
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-147-06b849502129> in <module>
     11 dB = da.from_array(B, asarray=False)
     12 
---> 13 res = da.einsum('i,ij->i', dA, dB).compute()

/conda/envs/rapids/lib/python3.7/site-packages/dask/base.py in compute(self, **kwargs)
    154         dask.base.compute
    155         """
--> 156         (result,) = compute(self, traverse=False, **kwargs)
    157         return result
    158 

/conda/envs/rapids/lib/python3.7/site-packages/dask/base.py in compute(*args, **kwargs)
    396     keys = [x.__dask_keys__() for x in collections]
    397     postcomputes = [x.__dask_postcompute__() for x in collections]
--> 398     results = schedule(dsk, keys, **kwargs)
    399     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    400 

/conda/envs/rapids/lib/python3.7/site-packages/dask/threaded.py in get(dsk, result, cache, num_workers, pool, **kwargs)
     74     results = get_async(pool.apply_async, len(pool._pool), dsk, result,
     75                         cache=cache, get_id=_thread_get_id,
---> 76                         pack_exception=pack_exception, **kwargs)
     77 
     78     # Cleanup pools associated to dead threads

/conda/envs/rapids/lib/python3.7/site-packages/dask/local.py in get_async(apply_async, num_workers, dsk, result, cache, get_id, rerun_exceptions_locally, pack_exception, raise_exception, callbacks, dumps, loads, **kwargs)
    460                         _execute_task(task, data)  # Re-execute locally
    461                     else:
--> 462                         raise_exception(exc, tb)
    463                 res, worker_id = loads(res_info)
    464                 state['cache'][key] = res

/conda/envs/rapids/lib/python3.7/site-packages/dask/compatibility.py in reraise(exc, tb)
    110         if exc.__traceback__ is not tb:
    111             raise exc.with_traceback(tb)
--> 112         raise exc
    113 
    114     import pickle as cPickle

/conda/envs/rapids/lib/python3.7/site-packages/dask/local.py in execute_task(key, task_info, dumps, loads, get_id, pack_exception)
    228     try:
    229         task, data = loads(task_info)
--> 230         result = _execute_task(task, data)
    231         id = get_id()
    232         result = dumps((result, id))

/conda/envs/rapids/lib/python3.7/site-packages/dask/core.py in _execute_task(arg, cache, dsk)
    116     elif istask(arg):
    117         func, args = arg[0], arg[1:]
--> 118         args2 = [_execute_task(a, cache) for a in args]
    119         return func(*args2)
    120     elif not ishashable(arg):

/conda/envs/rapids/lib/python3.7/site-packages/dask/core.py in <listcomp>(.0)
    116     elif istask(arg):
    117         func, args = arg[0], arg[1:]
--> 118         args2 = [_execute_task(a, cache) for a in args]
    119         return func(*args2)
    120     elif not ishashable(arg):

/conda/envs/rapids/lib/python3.7/site-packages/dask/core.py in _execute_task(arg, cache, dsk)
    117         func, args = arg[0], arg[1:]
    118         args2 = [_execute_task(a, cache) for a in args]
--> 119         return func(*args2)
    120     elif not ishashable(arg):
    121         return arg

/conda/envs/rapids/lib/python3.7/site-packages/dask/optimization.py in __call__(self, *args)
    940                              % (len(self.inkeys), len(args)))
    941         return core.get(self.dsk, self.outkey,
--> 942                         dict(zip(self.inkeys, args)))
    943 
    944     def __reduce__(self):

/conda/envs/rapids/lib/python3.7/site-packages/dask/core.py in get(dsk, out, cache)
    147     for key in toposort(dsk):
    148         task = dsk[key]
--> 149         result = _execute_task(task, cache)
    150         cache[key] = result
    151     result = _execute_task(out, cache)

/conda/envs/rapids/lib/python3.7/site-packages/dask/core.py in _execute_task(arg, cache, dsk)
    117         func, args = arg[0], arg[1:]
    118         args2 = [_execute_task(a, cache) for a in args]
--> 119         return func(*args2)
    120     elif not ishashable(arg):
    121         return arg

/conda/envs/rapids/lib/python3.7/site-packages/dask/compatibility.py in apply(func, args, kwargs)
     91     def apply(func, args, kwargs=None):
     92         if kwargs:
---> 93             return func(*args, **kwargs)
     94         else:
     95             return func(*args)

/conda/envs/rapids/lib/python3.7/site-packages/dask/array/einsumfuncs.py in chunk_einsum(*operands, **kwargs)
     17     dtype = kwargs.pop('kernel_dtype')
     18     einsum = einsum_lookup.dispatch(type(operands[0]))
---> 19     chunk = einsum(subscripts, *operands, dtype=dtype, **kwargs)
     20 
     21     # Avoid concatenate=True in blockwise by adding 1's

/conda/envs/rapids/lib/python3.7/site-packages/numpy/core/einsumfunc.py in einsum(*operands, **kwargs)
   1344     # If no optimization, run pure einsum
   1345     if optimize_arg is False:
-> 1346         return c_einsum(*operands, **kwargs)
   1347 
   1348     valid_einsum_kwargs = ['out', 'dtype', 'order', 'casting']

ValueError: object __array__ method not producing an array
```

Some initial debugging
```python
> /conda/envs/rapids/lib/python3.7/site-packages/numpy/core/einsumfunc.py(1346)einsum()
   1344     # If no optimization, run pure einsum
   1345     if optimize_arg is False:
-> 1346         return c_einsum(*operands, **kwargs)
   1347 
   1348     valid_einsum_kwargs = ['out', 'dtype', 'order', 'casting']

ipdb>  type(operands[1])
<class 'cupy.core.core.ndarray'>
ipdb>  type(operands[2])
<class 'cupy.core.core.ndarray'>
```

### PR DESCRIPTION
**Pull request by pentschev**
This is one of requirements to fix #4898, together with https://github.com/cupy/cupy/pull/2249 and NumPy `_implementation` attribute from https://github.com/numpy/numpy/pull/13627.

Thanks @mrocklin for the guidelines on deferring non-Dask specific `kwargs` to the backend library (NumPy, CuPy, etc.).

A test for this already exists https://github.com/dask/dask/blob/4d3a48ee6d5e2b63fef1b0e6740b6478261cdaea/dask/array/tests/test_cupy.py#L60

cc @jakirkham

### CODE REVIEW

**Comment by mrocklin** [comment]
I'm +1 on this approach.  In general I think that we should leave kwarg checking to `blockwise` when it tries out the function on a small sample.

**Comment by pentschev** [comment]
> I'm +1 on this approach. In general I think that we should leave kwarg checking to `blockwise` when it tries out the function on a small sample.

Me too, this will make things much simpler for `__array_function__` going further.

**Comment by jakirkham** [comment]
Thanks for putting this together Peter. Looks great! 😄

**Comment by jakirkham** [comment]
It seems this causes `test_einsum_invalid_args` to fail.

**Comment by pentschev** [comment]
Thanks @jakirkham for pointing it out, indeed I had not seen it failed. I'll work on it.

**Comment by pentschev** [comment]
Just a quick update on this: the issue is a bit more complex than I first predicted, `blockwise_meta` is shadowing exceptions from function calls to other libraries (in this case, `np.einsum`), so I'm working on a fix for that.

**Comment by mrocklin** [comment]
Right, so we may or may not want to raise a TypeError on failed calls on meta.  This is a complex question.

Fortunately we've already been doing this in Dask Dataframe for a year or two now, so we have some information on how what happens.  In general we get lots of user bug reports on malformed meta.  We try functions on tiny sample functions and they fail, and users get pretty frustrated.  Most of them don't understand things well enough to understand how to fix their problem.  In Dask Dataframe we kind of have to maintain meta in order to operate effectively (we need column names and dtypes more than we do in Dask Array), so we're sort of stuck with having to explain to people, over and over, that they need to provide proper metadata.  This is, as you can imagine, super-frustrating for all involved.

In the Dask array case we might want to be a bit more lenient.  It seems like there is a spectrum of strictness that we could use:

1.  Not strict: default back to a dtype transform, or even just return the meta of the first input array
2.  Warn: Raise a warning that things didn't work out great, inform them how to remove the warning, and probably point to a longer doc page on the topic.  However continue on with the not strict approach and give them a possibly malformed dask array.
3.  Raise: Same as above, but we raise and don't allow them to continue.

**Comment by pentschev** [comment]
I actually realized one thing on the error here, the test currently is:

```python
     with pytest.raises(TypeError):
         da.einsum('a', *da_inputs, foo=1, bar=2)
```

and Dask raises the exception. However, we're now deferring the exception to the compute library (NumPy, CuPy), so what we really need to do is to add `.compute()` at the end, rather than making `blockwise_meta` raise the exception. I guess that makes sense, what do you think @jakirkham, @mrocklin ?

**Comment by pentschev** [comment]
In fact, here's one other existing test:

```python
def test_average_raises():
    d_a = da.arange(11, chunks=2)

    with pytest.raises(TypeError):
        da.average(d_a, weights=[1, 2, 3])

    with pytest.warns(RuntimeWarning):
        da.average(d_a, weights=da.zeros_like(d_a)).compute()
```

in this case, Dask raises a `TypeError`, but NumPy raises a `RuntimeWarning`, which is what I think we should expect for the `einsum` case failing in this PR too.

**Comment by mrocklin** [comment]
I actually realized one thing on the error here, the test currently is:

```python
     with pytest.raises(TypeError):
         da.einsum('a', *da_inputs, foo=1, bar=2)
```

and Dask raises the exception. However, we're now deferring the exception to the compute library (NumPy, CuPy), so what we really need to do is to add .compute() at the end, rather than making blockwise_meta raise the exception. I guess that makes sense, what do you think @jakirkham, @mrocklin ?

I think that it's still good to catch errors at graph construction time rather than compute time if we can.  Obviously, this isn't always possible, but I think that we can do it in the case of bad keywords.

I recommend that we make a function like this, and use it whenever we try to get meta from calling a user provided function:

```python
def compute_meta(func, *args, **kwargs):
    bad_keywords = set(inspect.signature(func).parameters) - set(kwargs)
    if bad_keywords:
        raise TypeError("Unexpected keywords to %s function: %s" % (funcname(func), bad_keywords)

    args = [getattr(arg, "_meta", arg) for arg in args]
    kwargs = {k: getattr(v, "_meta", v) for k, v in kwargs.items()}
    
    try:
        meta = func(*args, **kwargs)
    except Exception:
        meta = ...

    return meta
```

**Comment by pentschev** [comment]
@mrocklin we can definitely do that too for this particular case. But this will clearly not be the case for all exceptions, and I think the more we move towards `__array_function__`, it's likely that we're going to push more of such errors to the compute task itself. Are we ok with that?

**Comment by mrocklin** [comment]
> @mrocklin we can definitely do that too for this particular case. But this will clearly not be the case for all exceptions, and I think the more we move towards __array_function__, it's likely that we're going to push more of such errors to the compute task itself. Are we ok with that?

To a certain extent I think that it's necessary.  People will provide functions that strongly expect certain things that won't be true of meta.  I recommend that we also include the following test.

```python
def test_permissible_meta_calculations():
    def f(x):
        assert x.shape == (10, 10)
        return x + 1

    x = da.ones((30, 30), chunks=(10, 10))
    y = x.map_blocks(f)

    assert_eq(y, np.ones((30, 30)) + 1)
```

**Comment by pentschev** [comment]
Once again, this is a nice solution, except it has a lot of caveats. I've attempted to work on your suggestion @mrocklin, but it's not so simple. Again we fall on the shadowing of exceptions that I've mentioned before, but another issue comes from functions that take `**kwargs` instead of the actual named parameters, where we can't test for a bad signature.

I think we should then move conservatively (from the `_meta` perspective), just like we are doing in https://github.com/dask/dask/pull/4938, and for now let this fail during `compute`. Do you have any objection here?

I will raise a few issues (and perhaps some [WIP] PRs) with a few ideas I have attempted that fix some issues, but not all of them, and then we can build upon those ideas.

**Comment by mrocklin** [comment]
Yes, I agree that if the function has `**kwargs` then the keyword check should just pass.

I think it's suboptimal to fail on `compute` but probably necessary some of the time.  I'm curious what we did before.

```python
In [1]: import dask; dask.__version__
Out[1]: '1.2.2'

In [2]: import dask.array as da

In [3]: x = da.ones((30, 30), chunks=(10, 10))

In [4]: def f(x):
   ...:     assert x.shape == (10, 10)
   ...:     return x + 1
   ...:

In [5]: x.map_blocks(f)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-5f8635e7db98> in <module>
----> 1 x.map_blocks(f)

~/workspace/dask/dask/array/core.py in map_blocks(self, func, *args, **kwargs)
   1637     @wraps(map_blocks)
   1638     def map_blocks(self, func, *args, **kwargs):
-> 1639         return map_blocks(func, self, *args, **kwargs)
   1640
   1641     def map_overlap(self, func, depth, boundary=None, trim=True, **kwargs):

~/workspace/dask/dask/array/core.py in map_blocks(func, *args, **kwargs)
    493
    494     if dtype is None:
--> 495         dtype = apply_infer_dtype(func, args, original_kwargs, 'map_blocks')
    496
    497     if drop_axis:

~/workspace/dask/dask/array/core.py in apply_infer_dtype(func, args, kwargs, funcname, suggest_dtype, nout)
    282         msg = None
    283     if msg is not None:
--> 284         raise ValueError(msg)
    285     return o.dtype if nout is None else tuple(e.dtype for e in o)
    286

ValueError: `dtype` inference failed in `map_blocks`.

Please specify the dtype explicitly using the `dtype` kwarg.

Original error is below:
------------------------
AssertionError()

Traceback:
---------
  File "/Users/mrocklin/workspace/dask/dask/array/core.py", line 267, in apply_infer_dtype
    o = func(*args, **kwargs)
  File "<ipython-input-4-014b0f39d8bc>", line 2, in f
    assert x.shape == (10, 10)
```

Hrm, so it looks like what I'm proposing is a relaxation of our previous policy, where we were more strict.  It still feels correct to me to loosen things here, mostly because I don't trust users to understand and provide a `meta` array as much as I trust them to understand and provide a dtype.

Lets cc @jcrist and @shoyer to get their thoughts here.  What should we do in the following situation where our attempt to run a user defined function fails on a `_meta` chunk.  Should we err, warn, pass?  Discussion above.

```python
def test_permissible_meta_calculations():
    def f(x):
        assert x.shape == (10, 10)
        return x + 1

    x = da.ones((30, 30), chunks=(10, 10))
    y = x.map_blocks(f)

    assert_eq(y, np.ones((30, 30)) + 1)
```

**Comment by pentschev** [comment]
Right now, `blockwise_meta` ignores a lot of `TypeError`s (by catching `Exception`) and defaults to constructing `dask.array` with the `dtype`, so that's the major problem when we let `TypeError` pass. I do think we should increase coverage of possible cases here, but I also think that will take time and we'll break more user code in the short term, so that's why I'm proposing a short-term solution for this PR and continue the discussion on how we increase the `_meta` coverage for this situation.

**Comment by mrocklin** [comment]
If you'd like a strict mode so that it's easier for developers to detect issues we would always add a strict mode relatively easily and control it with [configuration](https://docs.dask.org/en/latest/configuration.html)

**Comment by pentschev** [comment]
Yes, I agree with that, mainly because I don't think we will fix appropriately all issues we get on the tests in a timely manner. I will raise various issues tomorrow for that and the things I mentioned before.

So for now my question is: are you ok if we just call `.compute()` for the failing test here as a short-term solution and we continue with a more detailed conversation on the new issues?

**Comment by mrocklin** [comment]
> So for now my question is: are you ok if we just call .compute() for the failing test here as a short-term solution and we continue with a more detailed conversation on the new issues?

For this test in particular I think that we should not call compute.  I think that we should implement the inspect solution.  That's something I think we can do in any case.  I'm happy to push a commit like this if you prefer.

**Comment by pentschev** [comment]
What do you mean with the "inspect solution"?

**Comment by pentschev** [comment]
Ah, nevermind, I understand now. But this is what I'm saying: we have to allow `TypeError`s to pass, and with that we have lots of other errors, not just the `kwargs` error.

**Comment by mrocklin** [comment]
I think that short term we should keep the `except TypeError` in the code.  I think that we should check for keyword arguments, which will make the current failing test pass (and improve user experience I think).  I think that this would be a good incremental change while we figure out what to do next.  If there are other failing tests that would result from this approach I'm not aware of them (there appears to be only one at the moment, and I think we can fix it quickly), but would not be surprised if there are other things going on with cupy or whatnot that I'm not aware of.

(also, I'm shutting down for the night, so may not repond until much later)

**Comment by pentschev** [comment]
That's what I'm saying: we fix that one test, yes, but dozens of others fail, not because of argument, but because we now let `TypeError` pass and they raise `TypeError`s for various different reasons, and this is what `except Exception:` is doing when it falls back to `dtype`.

Long story short: we fix this one issue and raise dozens of others. So I stand by my proposal: use `compute` for now until we can solve the dozens of other errors, which will require some time and perhaps a more consistent approach to operating on the 0-length meta arrays in `blockwise_meta`.

**Comment by mrocklin** [comment]
Do you mind if I push a small commit to your branch with my proposal?  I think that this will be faster than prose communication.

**Comment by pentschev** [comment]
Do it.

**Comment by mrocklin** [comment]
Ah, I see now.  We're using a custom `chunk_einsum` function that has `**kwargs`, so my suggestion of using the inspect module doesn't suffice to detect the failure early.

**Comment by pentschev** [comment]
Yup. Sorry, this was my mistake, we've talked offline on how we could fix this case for `einsum`, but I should have pointed it out here as well.

**Comment by mrocklin** [comment]
Yes, so I now agree with you that, given that we're using `**kwargs` in einsum, we should probably call `.compute` in the test.  This is a bit of a regression in usability, but it seems like the right choice to me at the moment.

**Comment by pentschev** [comment]
@mrocklin we can definitely undo that in the future, but we have to improve `_meta` exception handling before.

**Comment by mrocklin** [comment]
Thanks @pentschev !  Sorry for getting in the way here for a while :)

**Comment by pentschev** [comment]
I've created #4951 and #4952 summarizing the discussion we had here, that would hopefully help us improve `_meta`.

**Comment by shoyer** [comment]
Would it make sense to still raise TypeError if unrecognized keyword arguments that NumPy doesn't know how to handle are used? 

e.g.,
```python
if not kwargs.keys() <= {'casting', order'}:
    raise TypeError
```

We still don't have to pass them on to `np.einsum()` unless they were explicitly provided.

Xarray has a unit-test that verifies that the errors get raised for invalid keyword arguments (https://github.com/pydata/xarray/issues/3009). We could just remove the test, but it seems like a reasonable thing to keep around.

**Comment by pentschev** [comment]
@shoyer https://github.com/dask/dask/pull/4954/files#diff-3598e11c3b3a16881fecff61abdf1f4cR97 will solve that.

**Comment by jakirkham** [comment]
It's worth noting that `np.einsum` itself doesn't note which arguments it takes in its signature, but only takes a generic `**kwargs`. This makes it hard for us to inspect and check validity of arguments at this level.

```python
In [1]: import numpy as np                                                      

In [2]: import inspect                                                          

In [3]: inspect.getfullargspec(np.einsum)                                       
Out[3]: FullArgSpec(args=[], varargs='operands', varkw='kwargs', defaults=None, kwonlyargs=[], kwonlydefaults=None, annotations={})
```

It would be better if NumPy's `einsum` explicitly listed keyword arguments it would accept so we could inspect it and stay current. Explicit checking on our end will inevitably go stale if the allowed keyword arguments change in the future.

**Comment by mrocklin** [comment]
As @pentschev mentions above, this is being resolved in https://github.com/dask/dask/pull/4954

Please excuse our churn here.

@shoyer so far I think that we'll be able to make the next Dask release fully backwards compatible from an Xarray perspective.

**Comment by shoyer** [comment]
NumPy is saving Python 2 incompatible changes for 1.18 (the next release
after this one). But eventually they'll be able to use real keyword
arguments for einsum

**Pull request merged**
