### PR TITLE
`tmpfile` does not end files with period on empty extension

### PR DESCRIPTION
**Pull request by hendrikmakait**
As it turns out, when not specifying an extension, `tmpfile` ends the filename with a period, which is discouraged on Windows (https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file) and caused issues fixed in dask/distributed#6954 as other system utilities strip the period away.

- [ ] Tests added / passed
- [x] Passes `pre-commit run --all-files`

### CODE REVIEW

**Review by gjoseph92 — APPROVED** [review]
Thanks for fixing this here too!

**Comment by gjoseph92** [comment]
I'm not familiar enough with dask's CI to know if these failures are flaky, or if this actually broke something?
* `dask/bytes/tests/test_http.py::test_parquet[fastparquet]` (this is failing everywhere so it's probably actually broken)
* `dask/tests/test_distributed.py::test_blockwise_dataframe_io[True-True-hdf]`
* `dask/tests/test_distributed.py::test_blockwise_dataframe_io[True-None-hdf]`

**Comment by ian-r-rose** [comment]
> dask/tests/test_distributed.py::test_blockwise_dataframe_io[True-True-hdf]

This looks like #8816, a known flaky test related to HDF5 and distributed disagreeing about whether something is locked.

**Comment by hendrikmakait** [comment]
`dask/bytes/tests/test_http.py::test_parquet[fastparquet]` looks like #9424

**Comment by jrbourbeau** [comment]
Just merged `main` which should fix the `test_parquet` failure

**Review by jrbourbeau — APPROVED** [review]

**Comment by gjoseph92** [comment]
Thanks @hendrikmakait @jrbourbeau!

**Pull request merged**
