### PR TITLE
Enhance `dask.array.broadcast arrays`

### PR DESCRIPTION
**Pull request by magonser**
Thi PR suggest a way to enhance `broadcast_arrays` by an `signature` argument to exclude core dims from broadcast and a `sparse` argument, like in `numpy.meshgrid`. 

While the standard behavior stays the same as in `numpy.broadcast_arrays`, the added functionality is beyond numpys implementation and this function might need a different name.

I've kept the new proposal still in extra module `dask.array.broadcast arrays` instead of overwriting `broadcast_array` inside `dask.array.core`.

- [x] Tests added / passed
- [x] Passes `flake8 dask`

### CODE REVIEW

**Comment by shoyer** [comment]
I think the current implementation is a little too flexible/powerful to be easily understood. I would consider if you can make a simplified version that captures the core functionality you want. Right now I think there a few too many special cases (e.g., omitted inputs or outputs) to be easily understood.

For example, you might change the `signature` argument to specify only core dimensions on input arrrays, i.e., the left-hand side of the signature for a gufunc. For example, if a gufunc has a signature `(k,n),(n,m)->(k,m)` (e.g., matrix-multiplication), then to do broadcasting like the gufunc you could write `broadcast_arrays(*arrays, signature='(k,n),(n,m)')`.

**Comment by magonser** [comment]
Thank you for your thoughts - that means focusing only on excluding core dimensions from broadcast, but strictly keep loop dimensions behaviour as in the original broadcast_arrays.

May I ask further suggestions for this example when the input arrays were of shapes a=(3, k=4, n=5), b=(2, n=5, m=6)? In such case to my understanding, I had following choices:
* Use `[]` syntax to introduce the required loop dimensions for one of the two arrays: `broadcast_arrays(a[:, np.newaxis, ...], b, signature='(k,n),(n,m)')`
* Have the same extension to exclude core dimensions in an extended  `meshgrid` function, where all loop dimensions are considered different from each other
* Put the proposed flexible treatment of loop dimensions in a separate function

For me the pain point in working with arrays without dimension names is to keep track of the position of all dimensions throughout calculations. I appreciate therefore the generalized ufuncs string like syntax for it's simplicity and clarity (besides solutions like `xarray` to name dimensions). So the motivation really is, to stay free of `[..., np.newaxis, ...]` and `transposes` in calculations to make calculations more readable. 

If this PR concludes that it would better to simplify behaviour, could we also consider focusing on the loop dimensions instead of the core dimensions for the broadcast signature? From the implemented tests it feels more logical to me. I.e. gufunc is about core dimensions and hence it's signature focuses on that, however broadcasting is about loop dimensions so the signature should be about loop dimensions. The example given with the arrays shapes stated above would become `broadcast_arrays(a, b, signature='(i),(j)')`. 

Note, that since in this numpy/dask ecosystem also the output arrays are without dimension names, it will be more difficult for the user to anticipate, in which order the loop dimensions were broadcast if we short the syntax too much.

**Comment by magonser** [comment]
@shoyer  ... there is no hurry, but maybe could you suggest, if this is better to be discussed upstream in NumPy or are we going to continue anything here? If so, I would post more insight on potential cleaner API in an issue, rather than here in the PR. 

If the suggested extension is out of scope or not interesting here, it is not a problem either for me and we can reject/close it.

**Comment by shoyer** [comment]
Yes, I think this would make sense to discuss upstream.

**Comment by magonser** [comment]
Closing this PR for now

**Pull request closed without merging**
