### PR TITLE
Duplicate argument definitions in `to_csv` docstring

### PR DESCRIPTION
**Pull request by tebesfinwo**
There are two definitions of `compression` arguments in `data.dataframe.io.csv.to_csv` docstring and one of them does not match with the implementation. 

https://github.com/dask/dask/blob/7aaef9fa8d9d37c7c7e57a1125d7d06ef2a8fefb/dask/dataframe/io/csv.py#L743-L746

https://github.com/dask/dask/blob/7aaef9fa8d9d37c7c7e57a1125d7d06ef2a8fefb/dask/dataframe/io/csv.py#L782-L785

**What happened**:
I noticed that compression didn't apply automatically even though the `gz` was an extension of the filename when I was using `data.dataframe.io.csv.to_csv`. Then, I realized there were two `compression` arguments in the [API documentation](https://docs.dask.org/en/latest/dataframe-api.html#dask.dataframe.to_csv). 

**What you expected to happen**:
I expected the argument definitions in the `to_csv` docstring to match up with its implementation. 

**Environment**:
- Dask version: 2.19.0
- Python version: Python 3.7.3
- Operating System: macOS
- Install method (conda, pip, source): poetry

### CODE REVIEW

**Comment by gforsyth** [comment]
Hey @tebesfinwo -- I don't see the duplicated argument.  Which line number is it on?

**Comment by tebesfinwo** [comment]
> Hey @tebesfinwo -- I don't see the duplicated argument. Which line number is it on?

Hi @gforsyth, they are at L743 and L782 on `dask/dask/dataframe/io/csv.py`

https://github.com/dask/dask/blob/7aaef9fa8d9d37c7c7e57a1125d7d06ef2a8fefb/dask/dataframe/io/csv.py#L743-L746

https://github.com/dask/dask/blob/7aaef9fa8d9d37c7c7e57a1125d7d06ef2a8fefb/dask/dataframe/io/csv.py#L782-L785

**Comment by gforsyth** [comment]
> Hi @gforsyth, they are at L743 and L782 on `dask/dask/dataframe/io/csv.py` and I believe the `compression` at L743 does not match the implementation, which is the one I removed in the commit.

Thanks!  I had trouble spotting it!  I'm good with this change, but can you move the `compression` description up to where the one you removed is?  It's better for the order of the args in the docstring to match the function signature.  (I know there are some other ordering issues -- if you want to fix those here I think that's in scope for this PR).

**Comment by tebesfinwo** [comment]
> Thanks! I had trouble spotting it! I'm good with this change, but can you move the `compression` description up to where the one you removed is? It's better for the order of the args in the docstring to match the function signature. (I know there are some other ordering issues -- if you want to fix those here I think that's in scope for this PR).

Thanks, @gforsyth. Its docstring is quite lengthy. Sure, I'll fix the ordering and also add back the missing definition of the argument `df`  in another commit on this PR. 

There are some argument definitions in the docstring that are not defined in the function signature and I believe that they are passed to the `pandas.dataframe.to_csv`. What do you think of replacing those with following? 
```
    kwargs : dict
        Additional parameters to pass to `pd.dataframe.to_csv()`
```

With this, I think that we can shorten the docstring and don't have to update `dask.datafrane.to_csv` docstring each time  `pandas.dataframe.to_csv`  is changed.

**Comment by gforsyth** [comment]
> What do you think of replacing those with following?

Yep, I think that's a good plan!

**Comment by tebesfinwo** [comment]
@gforsyth Thanks for being patient. I made the change per our discussion. 

I followed the instruction under the [Contributing to documentation](https://docs.dask.org/en/latest/develop.html#contributing-to-documentation) to build the HTML files on my local machine but the colons are missing. See the attached image. Same for other APIs. Any idea? 

Screen Shot 2020-07-20 at 9 25 22 AM

**Comment by tebesfinwo** [comment]
> Also I see that this is your first contribution to `dask`. Welcome! We're happy to have you!

Thanks, @gforsyth. Happy to contribute!

**Pull request merged**
