### PR TITLE
Fix normalize_meta to support Xarray test suite

### PR DESCRIPTION
**Pull request by mrocklin**
Fixes https://github.com/pydata/xarray/issues/3009

cc @pentschev @shoyer

### CODE REVIEW

**Comment by pentschev** [comment]
I don't like this solution, IMO, falling back to the creation of a NumPy array should be the very last resort. The problem with doing something like this is that it shadows other issues, like a potential bug or missing feature of the target library, such as not properly handling 0-length dimensions. I can foresee the case where we believe some third-party library should work properly with `_meta` being very difficult to debug, as we won't know where we transparently fallback to NumPy.

A similar issue that I'm working on right now involves https://github.com/dask/dask/pull/4914, where I just treated `TypeError` in `blockwise_meta` as a function that doesn't support `concatenate` (which is added by `blockwise`), and this prevents us from passing back a `TypeError` issue from whatever library is computing something, which in that particular case is `einsum`, either with NumPy or CuPy.

I think the best is to understand why `normalize_meta` fails when working on `xarray` and maybe address that, is it a limitation on the way we increase or reduce the number of dimensions within `normalize_meta`? I'm not very familiar with xarray, so I really don't know the answer here yet.

**Comment by mrocklin** [comment]
Xarray had an internal type that didn't much like being sliced with tuple-of-slice.  I think that we should still be able to support this type in dask array though, even if we can't do slicing operations on it.

Ideally we would fix things, but it's also important to get the xarray test suite up and running quickly (they are a very important downstream project for Dask) and I don't personally plan to investigate or resolve things perfectly.  I also don't think that you should, given time constraints.

**Comment by pentschev** [comment]
> Xarray had an internal type that didn't much like being sliced with tuple-of-slice. I think that we should still be able to support this type in dask array though, even if we can't do slicing operations on it.

Then we should raise an issue to investigate this.



> Ideally we would fix things, but it's also important to get the xarray test suite up and running quickly (they are a very important downstream project for Dask) and I don't personally plan to investigate or resolve things perfectly. I also don't think that you should, given time constraints.

I understand your point. So here's my suggestion: to prevent xarray tests from working but also to prevent the shadowing of issues, let's add a small check for now to test for an xarray and allow a fallback to NumPy, but prevent that from happening for other libraries. I very much _want_ to know if there are issues with the approach here, and so far it has been successful, that's the only reason why @shoyer saw this issue and we were able to identify that there is one.

**Comment by mrocklin** [comment]
Good idea, I've raised an issue on Xarray here: https://github.com/pydata/xarray/issues/3022

I agree that it would be valuable for us to learn quickly when meta normalization fails, however I think that it's more important that things mostly-work for users in these odd cases.  This is different than the emulation issues you're running into in `blockwise_meta` because there you're catching issues with user code, which they should know about.  Not supporting slicing with slice objects isn't as likely to be a user issue and I don't think that we should block their progress in this case.

**Comment by pentschev** [comment]
> Not supporting slicing with slice objects isn't as likely to be a user issue and I don't think that we should block their progress in this case.

I'm not talking about user issues, I'm talking about we expecting the `_meta` work to function correctly for its purpose, and not having those failures will prevent us from catching issues that may arise with other libraries that we don't know of. Eventually we wish `_meta` to work on all (or most) cases, and we will never be able to figure out those problems if we can't find out about them.

**Comment by mrocklin** [comment]
I'm confident that we'll still find out about them.

I don't think that us finding out about them is a sufficient reason to break user code.

**Comment by pentschev** [comment]
> I'm confident that we'll still find out about them.

We will, we'll just waste a lot more time to do that.

**Comment by pentschev** [comment]
> I don't think that us finding out about them is a sufficient reason to break user code.

Also, in that sense I don't think it's possible then to fix what I'm referring to in https://github.com/dask/dask/pull/4914. I'll allow exceptions from other libraries to pass through, but there's an endless amount of possible errors that can arise from code I don't know about that we're trying to compute `_meta` from.

**Comment by mrocklin** [comment]
>> I'm confident that we'll still find out about them.

> We will, we'll just waste a lot more time to do that.

Yes, but that's better than things not working for users.

> Also, in that sense I don't think it's possible then to fix what I'm referring to in #4914. I'll allow exceptions from other libraries to pass through, but there's an endless amount of possible errors that can arise from code I don't know about that we're trying to compute _meta from.

Good point.  I've commented on that PR.

**Comment by pentschev** [comment]
LGTM.

**Pull request merged**
