### PR TITLE
Serialization of layers

### PR DESCRIPTION
**Pull request by madsbk**
This PR implements a default serialization of `Layer`. In order to be compatible with pickle, we use the `__reduce__` protocol but for security reasons Distributed uses `msgpack` for serialization when communicating with the scheduler thus this must also be compatible with `msgpack` (see https://github.com/dask/distributed/pull/4140).

```python 

    def __reduce__(self):
        """Default serialization implementation, which materialize the Layer

        This should follow the standard pickle protocol[1] but must always return
        a tuple and the arguments for the callable object must be compatibly with
        msgpack. This is because Distributed uses msgpack to send Layers to the
        scheduler.

        [1] <https://docs.python.org/3/library/pickle.html#object.__reduce__>
        """
```

- [x] Tests added / passed
- [x] Passes `black dask` / `flake8 dask`

### CODE REVIEW

**Comment by mrocklin** [comment]
Does msgpack respect these methods?

I'm curious to see how this would operate with Blockwise.  We can do this as future work of course.  I'm exctied :)

**Comment by madsbk** [comment]
> Does msgpack respect these methods?

Not natively but the changes in https://github.com/dask/distributed/pull/4140 makes msgpack call `__reduce__`. 
See https://github.com/dask/distributed/pull/4140/files#diff-7a335df475cb573124e2aedec25f055aR118

**Comment by jrbourbeau** [comment]
`Layer.__reduce__` appears to be interacting poorly with `dask/tests/test_highgraph.py::test_map_tasks`. @madsbk if you're able to diagnose that'd be great, otherwise I can look into it tomorrow

**Comment by madsbk** [comment]
> `Layer.__reduce__` appears to be interacting poorly with `dask/tests/test_highgraph.py::test_map_tasks`. 

The issue is that [`Blockwise.map_task()` calls `copy.copy()`](https://github.com/dask/dask/blob/14f6a76b38b2990fa40ef64fcd8933b6ee56b93f/dask/blockwise.py#L270), which in turn calls `__reduce__()` and since the default implementation of `__reduce__()` materializes the Layer, we get the error. 
I have fixed this by implementing a default `__copy__()`. Alternatively, we can avoid using `__reduce__()` all together and define our own API.

**Comment by madsbk** [comment]
@jrbourbeau if CI passes, I think this is ready to be merged.

**Review by jrbourbeau — APPROVED** [review]
Thanks @madsbk! 

There was John's comment (https://github.com/dask/distributed/pull/4140#issuecomment-708059073) about not using `__reduce__` and instead defining separate methods. I'm happy to revisit that later and go with this for now to not block progress on https://github.com/dask/distributed/pull/4140

**Pull request merged**
