### PR TITLE
Add dd.demo.daily_stock function

### PR DESCRIPTION
**Pull request by mrocklin**
This adds a function to generate fake stock data to the
dask.dataframe.demo submodule.  This is useful for benchmarking and
teaching.

Examples
--------

```python
    >>> import dask.dataframe as dd
    >>> df = dd.demo.daily_stock('GOOG', '2010', '2011', freq='1s')
    >>> df
    Dask DataFrame Structure:
                           close     high      low     open
    npartitions=252
    2010-01-04 09:00:00  float64  float64  float64  float64
    2010-01-05 09:00:00      ...      ...      ...      ...
    ...                      ...      ...      ...      ...
    2010-12-31 09:00:00      ...      ...      ...      ...
    2010-12-31 16:00:00      ...      ...      ...      ...
    Dask Name: from-delayed, 504 tasks

    >>> df.head()
                           close     high      low     open
    timestamp
    2010-01-04 09:00:00  626.944  626.964  626.944  626.951
    2010-01-04 09:00:01  626.906  626.931  626.906  626.931
    2010-01-04 09:00:02  626.901  626.911  626.901  626.905
    2010-01-04 09:00:03  626.920  626.920  626.905  626.905
    2010-01-04 09:00:04  626.894  626.917  626.894  626.906
```

This is intended to replace the library
https://github.com/mrocklin/fakestockdata

cc @martindurant @dhavide

### CODE REVIEW

**Comment by mrocklin** [comment]
So, for example, we can generate datasets for students using code like the following:

```python
for sym in ['goog', 'appl', ...]:
    df = dd.demo.daily_stock(sym, '2010', '2011', freq='1s')
    df.to_parquet(sym + '.parq')
    # or 
    df.to_csv(sym + '.parq')
```

**Comment by mrocklin** [comment]
This *does* require internet connectivity and the ability to access either the yahoo or google APIs, but does not require significant bandwidth (we only pull down kilobytes).

**Comment by martindurant** [comment]
Is this the same basic code as in fake-stock-data?

**Comment by mrocklin** [comment]
The code to interpolate is the same.  We get the data from a different
source.

**Pull request merged**
