### PR TITLE
Fixes some type issues in Dask Array shapes

### PR DESCRIPTION
**Pull request by jakirkham**
Fixes https://github.com/dask/dask/issues/2374

### CODE REVIEW

**Comment by jakirkham** [comment]
Have added a test that reproduces the original issue and verified it demonstrates this fix works. Should be good to go on my end as long as it passes.

**Comment by jakirkham** [comment]
Looks like this is now passing. Any comments on it or is this good to go?

**Comment by mrocklin** [comment]
Would this be resolved by moving the change to the last line of `dask/array/core.py::normalize_chunks`?

**Comment by mrocklin** [comment]
I've pushed a proposed change.  Feel free to remove it if preferred.

**Comment by jakirkham** [comment]
The test still passes. So fine by me. 👍

**Pull request merged**
