### PR TITLE
Allow loading of parquet files which have multi-index

### PR DESCRIPTION
**Pull request by martindurant**
Requires the user to specify which index then want (including False
for no index), and rest of index columns then appear as ordinary
columns.

- [x] Tests added / passed
- [x] Passes `flake8 dask`
- [ ] Fully documented, including `docs/source/changelog.rst` for all changes
      and one of the `docs/source/*-api.rst` files for new API

### CODE REVIEW

**Comment by martindurant** [comment]
Fixes #3104
Sorry, @TomAugspurger , I could not figure out how to make this work with pyarrow.

**Comment by martindurant** [comment]
Anyone have any thoughts on this?

**Comment by TomAugspurger** [comment]
What was the issue with pyarrow readers?

IIUC, the behavior we're fixing is that

1. A file was written with an index
2. User specifies `index=False` for "read the index in as a column."

In the case of `index=False`, we need to add the index storage names to the column names, so modify `_normalize_index` to return a tuple of `index_names, column_names`. Then at https://github.com/martindurant/dask/blob/47ca5b663dc7dc84b1fb0da3b5e55bebea7d3317/dask/dataframe/io/parquet.py#L185-L186

it'll be 

```
if user_index is False:
    index_names = []
    column_names = column_names + data_index
...
return index_names, column_names
```

**Comment by martindurant** [comment]
- a file was written with one or more index columns (i.e., columns which are mentioned int he pandas-specific metadata). These cannot be loaded by dask at all.
- the user can choose one of those indexes as the dask index, or none (with `False`) - other indexes should appear as ordinary columns.

The current behaviour in pyarrow is to create the multi-index for each partition, the index and column values are not used in the same way. Presumably the logic in `_read_pyarrow_parquet_piece` could be changed somehow.

**Comment by mrocklin** [comment]
@TomAugspurger @jcrist any feedback on this?  Is this critical to release?

**Comment by jcrist** [comment]
Sorry, I'm just about done with a PR to supersede this. I'd like to get this in before the release.

**Comment by jcrist** [comment]
https://github.com/dask/dask/pull/3149

**Comment by mrocklin** [comment]
I believe that this can now be closed

**Pull request closed without merging**
