### PR TITLE
Add datasets module

### PR DESCRIPTION
**Pull request by mrocklin**
Currently this only contains timeseries.
Hopefully this creates a model on which we can add in the future.

### Example

```python
In [1]: import dask

In [2]: dask.datasets.timeseries()
Out[2]: 
Dask DataFrame Structure:
                   id    name        x        y
npartitions=30                                 
2000-01-01      int64  object  float64  float64
2000-01-02        ...     ...      ...      ...
...               ...     ...      ...      ...
2000-01-30        ...     ...      ...      ...
2000-01-31        ...     ...      ...      ...
Dask Name: make-timeseries, 30 tasks
```

- [ ] Tests added / passed
- [ ] Passes `flake8 dask`

### CODE REVIEW

**Comment by mrocklin** [comment]
Adding this seems a little premature with only one dataset, but I'm inclined to start recording some videos and I'd like to future-proof them a bit

**Comment by jakirkham** [comment]
Are you planning to start storing test data in Dask? If so, would like to discuss that further.

**Comment by mrocklin** [comment]
Nope

**Comment by mrocklin** [comment]
I think that operationally we need to decide what sort of API we want for easy to use datasets going forwards.  Should this be centralized in the dask project?  Should it be in a `.datasets` module or something else (sklearn does this)?

If no one has any thoughts on this I'm going to go ahead and merge.

**Comment by jakirkham** [comment]
If it's only including generated data (not binary data), I have no thoughts on it. If we get into binary data packaging, I'd like to engage in that discussion.

**Comment by mrocklin** [comment]
When you say binary data packaging do you mean that we'll ship data along
with the dask package or do you mean that we'll download datasets?

**Comment by jakirkham** [comment]
Definitely packaging binary data. Possibly also downloaded data. How/when would downloaded datasets get added?

**Comment by mrocklin** [comment]
If we started doing that then we would probably follow the model in
libraries like scikit-learn.  I think that they download when necessary but
keep some sort of cache around.

I would be -1 to including non-trivial data within the dask package itself.

**Comment by jakirkham** [comment]
I see. Is it on import?

Ok, that makes sense.

**Comment by mrocklin** [comment]
Nothing happens on import.  If someone calls a function like get_nyc_taxi()
then some download might happen, but definitely nothing would happen on
packaging, installation, or import.

**Comment by mrocklin** [comment]
OK to merge?  

This is in-line with existing conventions in scikit-learn, (and I suspect other projects).  I think that having it in a release will make it easier to integrate with the dask-examples repository, which will encourage additional use in the future.

**Comment by jakirkham** [comment]
Sure this seems fine. Would you like to add a test?

**Comment by mrocklin** [comment]
The current timeseries function is currently tested in the dataframe
module.  I think that might be enough.  Open to other suggestions though.

**Pull request merged**
