### PR TITLE
[WIP] Add nunique API

### PR DESCRIPTION
**Pull request by whiletruelearn**
- [ ] Tests added / passed
- [x] Passes `flake8 dask`

### CODE REVIEW

**Comment by whiletruelearn** [comment]
Trying to fix #3817

**Comment by mrocklin** [comment]
Welcome @whiletruelearn 

I recommend adding a test that compares this against Pandas behavior.  The following links might be helpful

https://github.com/dask/dask/blob/904805bbea947cf977af735bd6d7c66e30eb955a/dask/dataframe/tests/test_dataframe.py#L2991-L2996

http://docs.dask.org/en/latest/develop.html#test

**Comment by mrocklin** [comment]
It looks like tests fail.  Copying over from the travis-ci run here: https://travis-ci.org/dask/dask/jobs/436079285

```
=================================== FAILURES ===================================
_________________________________ test_nunique _________________________________
[gw1] linux -- Python 3.6.6 /home/travis/miniconda/envs/test-environment/bin/python
    def test_nunique():
        df = pd.DataFrame({'A': [1, 2, 3], 'B': [1, 1, 1]})
        ddf = dd.from_pandas(df, npartitions=2)
>       assert_eq(df.nunique(), ddf.nunique())
dask/dataframe/tests/test_dataframe.py:3287: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
dask/dataframe/utils.py:597: in assert_eq
    b = _check_dask(b, check_names=check_names, check_dtypes=check_dtypes)
dask/dataframe/utils.py:529: in _check_dask
    result = dsk.compute(scheduler='sync')
dask/base.py:156: in compute
    (result,) = compute(self, traverse=False, **kwargs)
dask/base.py:395: in compute
    results = schedule(dsk, keys, **kwargs)
dask/local.py:542: in get_sync
    return get_async(apply_sync, 1, dsk, keys, **kwargs)
dask/local.py:488: in get_async
    fire_task()
dask/local.py:484: in fire_task
    callback=queue.put)
dask/local.py:531: in apply_sync
    res = func(*args, **kwds)
dask/local.py:277: in execute_task
    result = pack_exception(e, dumps)
dask/local.py:272: in execute_task
    result = _execute_task(task, data)
dask/local.py:253: in _execute_task
    return func(*args2)
dask/compatibility.py:93: in apply
    return func(*args, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <methodcaller: nunique>, obj = A    3
B    1
dtype: int64, args = ()
kwargs = {'axis': 0, 'dropna': True}
    def __call__(self, obj, *args, **kwargs):
>       return getattr(obj, self.method)(*args, **kwargs)
E       TypeError: nunique() got an unexpected keyword argument 'axis'
dask/utils.py:687: TypeError
```

**Comment by whiletruelearn** [comment]
@mrocklin thanks. I saw that, didn't find time yet to dive deep on this. I think I need to understand the codebase slightly more. I will try to fix this in next couple of days.

**Comment by Vvkmnn** [comment]
Running into the same issue trying to use `dropna`, and the [docs](http://docs.dask.org/en/latest/dataframe-api.html#dask.dataframe.DataFrame.dropna) disagree on whether it's valid parameter or not. Currently not a valid argument in the function though (using `dask-1.0.0` on Conda flavoured `python3`) 

**Input**
```python
data = data.dropna(axis="columns", how="all") # dask.dataframe
```

**Output**
```python
TypeError: dropna() got an unexpected keyword argument 'axis'
```

**Pull request closed without merging**
