### PR TITLE
Make observed kwarg optional

### LINKED ISSUE #6951: Optional kwarg for `observered`
In https://github.com/dask/dask/pull/6854, dask added the `observed` keyword to categorical groupby operations.  In RAPIDS we just released cuDF 0.17 which does not currently support the `observed` keyword for categorial series groupby operations:

```python
import dask.dataframe as dd
import pandas as pd
import cudf

df = pd.DataFrame({
    'c1': pd.Categorical(['v11', 'v12', 'v11'], ['v11', 'v12', 'v13']),
    'c2': pd.Categorical(['v21', 'v22', 'v23']),
    'c3': [1, 4, 7]})


cdf = cudf.from_pandas(df)
ddf = dd.from_pandas(cdf, npartitions=1)
ddf.c1.groupby(ddf.c1).size().compute()
```

The above fails with:

```
/datasets/bzaitlen/GitRepos/dask/dask/dataframe/groupby.py in __init__(self, df, by, slice, group_keys, dropna, sort, observed)
   1109         self.observed = observed
   1110
-> 1111         self._meta = self.obj._meta.groupby(
   1112             index_meta, group_keys=group_keys, observed=observed, **self.dropna
   1113         )

TypeError: groupby() got an unexpected keyword argument 'observed'
```

RAPIDS is addressing this https://github.com/rapidsai/cudf/pull/6964, however,  when Dask is next released, this will break the stable 0.17 RAPIDS version.  I am asking if we can temporarily pass `observed` as an optional kwarg until 0.18 and then we can switch back.

### PR DESCRIPTION
**Pull request by jsignell**
- [ ] Tests added / passed
- [x] Passes `black dask` / `flake8 dask`
- [x] Closes #6951 

@rjzamora would you mind testing this out with cudf?

### CODE REVIEW

**Comment by quasiben** [comment]
This works for me.  Thanks @jsignell !


```
In [1]: import dask

In [2]: dask.__version__
Out[2]: '2.30.0+104.g0e524343'

In [3]: import dask.dataframe as dd
   ...: import pandas as pd
   ...: import cudf
   ...:
   ...: df = pd.DataFrame({
   ...:     'c1': pd.Categorical(['v11', 'v12', 'v11'], ['v11', 'v12', 'v13']),
   ...:     'c2': pd.Categorical(['v21', 'v22', 'v23']),
   ...:     'c3': [1, 4, 7]})
   ...:
   ...: ddf = dd.from_pandas(df, npartitions=1)
   ...: ddf.c1.groupby(ddf.c1).size().compute()
   ...:
   ...: cdf = cudf.from_pandas(df)
   ...: ddf = dd.from_pandas(cdf, npartitions=1)
   ...: ddf.c1.groupby(ddf.c1).size().compute()
Out[3]:
c1
v11    2
v12    1
dtype: int64
```

**Comment by jsignell** [comment]
:+1: ok I'll merge if it passes tests.

**Comment by kkraus14** [comment]
Thanks for this @jsignell. It's greatly appreciated!

**Comment by rjzamora** [comment]
Thanks @jsignell !

**Comment by jsignell** [comment]
I'm going to go ahead and merge this since it seems like the last test is hanging and there is no reason why it'd fail.

**Pull request merged**
