### PR TITLE
fix issue with index dtype after applying dd.pivot_table (#5379)

### LINKED ISSUE #5379: dask.dataframe.pivot_table seems to destroy datetime type information on the new index
I ran into an issue when using pivot_table on a dask.dataframe recently: when selecting a column with type `datetime64[ns]` as the new index, the dtype of the index is `object` afterwards. I have generated some mock data below resembling the original data which is coming from machine sensors:

```
import numpy as np
import pandas as pd
import dask.dataframe as dd


df = pd.DataFrame({'dateTime': np.repeat(pd.date_range(start='2019-08-01',
                                         periods=2000,
                                         freq='s'), 5),
                   'plantCode': np.random.choice(['P1', 'P2', 'P3'], size=10000),
                   'value': np.random.uniform(0, 100, 10000),
                   'variableName': np.random.choice(['xyz', 'abc', 'xoxo', 'lol', 'wtf'], size=10000)})

ddf = dd.from_pandas(df, npartitions=10).categorize()
ddf.info()
```

Output (dtypes as expected):
```
<class 'dask.dataframe.core.DataFrame'>
Columns: 4 entries, dateTime to variableName
dtypes: category(1), category(1), datetime64[ns](1), float64(1)
```

Now pivot the table:
```
ddf_pivot = ddf.pivot_table(index='dateTime', columns='variableName', values='value')
ddf_pivot.index
```

Output (index type is `object`):
```
Dask Index Structure:
npartitions=1
    object
       ...
Name: dateTime, dtype: object
Dask Name: truediv, 48 tasks
```

Mapping the index manually after the pivot resulted in all entries being `NaT`:
```
ddf_pivot.index = ddf_pivot.index.map_partitions(pd.to_datetime,
                                                 meta='M8',
                                                 infer_datetime_format=True, 
                                                 errors='coerce')
ddf_pivot.index
```
Output:
```
Dask Index Structure:
npartitions=1
NaT    datetime64[ns]
NaT               ...
dtype: datetime64[ns]
Dask Name: assign_index, 51 tasks
```

### PR DESCRIPTION
**Pull request by therhaag**
- [ ] Tests added / passed
- [ ] Passes `black dask` / `flake8 dask`

I followed the recommended fix by @TomAugspurger and added a basic test for an index with type `datetime64`. Resolves #5379

### CODE REVIEW

**Comment by therhaag** [comment]
Sorry but I'm stuck here. I created a conda environment locally using the environment.yaml file provided in the appveyor directory to make sure my package versions match the test env. Cannot reproduce the problem, though. Any help is appreciated.

**Comment by TomAugspurger** [comment]
This is a new test, and I don't think I've seen it fail before.

```
================================== FAILURES ===================================
662______________________ test_compute_chunk_sizes_3d_array ______________________
663
664N = 8
665
666    def test_compute_chunk_sizes_3d_array(N=8):
667        X = np.linspace(-1, 2, num=8 * 8 * 8).reshape(8, 8, 8)
668        X = da.from_array(X, chunks=(4, 4, 4))
669        idx = X.sum(axis=0).sum(axis=0) > 0
670        Y = X[idx]
671>       idx = X.sum(axis=1).sum(axis=1) < 0
672
673dask\array\tests\test_array_core.py:4142: 
674_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
675dask\array\core.py:1959: in sum
676    out=out,
677dask\array\reductions.py:334: in sum
678    dt = getattr(np.empty((1,), dtype=a.dtype).sum(), "dtype", object)
679_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
680
681a = array([nan]), axis = None, dtype = None, out = None, keepdims = False
682initial = <no value>
683
684    def _sum(a, axis=None, dtype=None, out=None, keepdims=False,
685             initial=_NoValue):
686>       return umr_sum(a, axis, dtype, out, keepdims, initial)
687E       RuntimeWarning: invalid value encountered in reduce
688
689
```

I've restarted the appveryor CI to see if it goes away for now.

**Comment by TomAugspurger** [comment]
Failed again :/ Not sure what's up but will take a look later.

**Comment by TomAugspurger** [comment]
Merged master to see if the failures go away.

**Comment by TomAugspurger** [comment]
Well, that did it for some reason.

Thanks for the PR, and congrats on becoming a Dask contributor :)

**Comment by therhaag** [comment]
Thanks for investigating. Must be Murphy’s law when you do something for the first time :)

**Pull request merged**
