### PR TITLE
reduction(chunk, combine, aggregate)

### PR DESCRIPTION
**Pull request by crusaderky**
Breaking API change in ``dask.array.reductions.reduction``, from ``reduction(x, chunk, aggregate, ...,  combine=None)`` to ``reduction(x, chunk, combine, aggregate, ...)``.

I found that the old API was very confusing, and there is no particular reason why combine (which is a fundamental piece of the reduction) should be omitted while aggregate is mandatory. Also, I find much clearer to provide chunk, combine, aggregate as 3 mandatory positional parameters, as it makes it easy to wrap your head around the chronological order of the 3 steps of the reduction.

This change is marked as breaking as ``reduction`` is not public API, but somebody somewhere likely tapped into it to implement custom reductions.

On the side - added unit tests for nancumsum and nancumprod, which were 100% untested.

### CODE REVIEW

**Comment by mrocklin** [comment]
I wonder if either @jakirkham or @shoyer have the time to review this

**Comment by crusaderky** [comment]
@mrocklin should we go through any deprecation process, at all? This is an internal function, and it's not even linked to the top level documentation.

**Comment by crusaderky** [comment]
> Figuring out how to do the intermediate combination steps is sometimes harder for novice users to understand.
It's not something a novice user can ignore though. It's actually extremely dangerous; if he doesn't understand that an extra function will be invoked when there's 3+ levels in the reduction graph, there are good chances he won't write a unit test for the use case either!

**Comment by crusaderky** [comment]
> Figuring out how to do the intermediate combination steps is sometimes harder for novice users to understand.

It's not something a novice user can ignore though. It's actually extremely dangerous; if he doesn't understand that an extra function will be invoked when there's 3+ levels in the reduction graph, there are good chances he won't write a unit test for the use case either!

I would agree with you if split_every=None meant that you never get recursive aggregation; but as of today the default is 4, and to add insult to injury the parameter never appears in the readthedocs pages for any of the aggregation - so a novice user will flat out ignore it exists. With my change, a novice user writing a custom aggregation MUST understand what the "combine" function is about; there is much less risk that he'll unwittingly use the same function as aggregate even if it's incorrect.

**Comment by mrocklin** [comment]
As you mention above:

> This change is marked as breaking as reduction is not public API, but somebody somewhere likely tapped into it to implement custom reductions.

I'm inclined to agree with this.  I think I've seen people use reduction in the wild.  If we don't want to go through any deprecation process then we'll have to wait to merge this until we're confident that we're doing a release with breaking changes.

**Comment by mrocklin** [comment]
I would be good to get some other maintainer to review this work.  @jakirkham and @shoyer seem like the most likely candidates.

**Comment by crusaderky** [comment]
@mrocklin any hope to have this merged? It's been waiting 5 months...

**Comment by mrocklin** [comment]
It seems like it still needs someone to review it more thoroughly and provide thoughts on how to handle the deprecation.  Perhaps @jakirkham ?

**Comment by crusaderky** [comment]
I'll just close this...

**Pull request closed without merging**
