### PR TITLE
Add few hdf tests using the distributed scheduler

### PR DESCRIPTION
**Pull request by nirizr**
This is to test the distributed scheduler is functioning properly with different dask operations

Signed-off-by: Nir Izraeli <nirizr@gmail.com>

### CODE REVIEW

**Comment by nirizr** [comment]
This will fail at least until #1879 is merged, as it adds a test for the bug it fixes. #1881 is also waiting for this.

I tried making a decorator with
```
with cluster() as (s, [a, b]):
    with distributed.Client(('127.0.0.1', s['port']), loop=loop) as c:
````
but that wasn't as smooth.

**Comment by mrocklin** [comment]
This looks good to me.  We might want to add `distributed` to the conda-install line in travis.yml, at least in one of the versions.

**Comment by nirizr** [comment]
The python3.3 test appears to fail once I added `distributed` to the conda install list:
```
$ conda install -c conda-forge numpy=$NUMPY scipy pytables h5py bcolz pytest coverage toolz scikit-learn cytoolz chest blosc cython psutil ipython numba distributed
Fetching package metadata .........
Solving package specifications: ....
UnsatisfiableError: The following specifications were found to be in conflict:
  - numpy 1.9.2*
  - python 3.3*
```

Travis job for this PR without installing distributed (first commit): https://travis-ci.org/dask/dask/jobs/189618525
Travis job for this PR when installing distributed (second commit): https://travis-ci.org/dask/dask/jobs/189620811

**Comment by mrocklin** [comment]
Perhaps just add `distributed` to the Python 3.5 version for now?  (follow the `if` pattern in other lines below).  I suspect that we'll drop Python 3.3 support soon after adding Python 3.6 support, which should be fairly soon.

**Comment by nirizr** [comment]
Actually, just took a look now and saw this:
```
- if [[ $PYTHON != '3.3' ]]; then pip install git+https://github.com/dask/distributed --upgrade --no-deps; fi
```

This also explain why other tests fail (instead of skipping the new distributed tests).
Would you like me to:
1. keep it as is?
2. Change all python versions (except 3.3) to installing distributd through conda (testing against latest release, not master)? or
3. Only test against latest release for a specific version (python 3.5, as you suggested)?

**Comment by mrocklin** [comment]
Ah ha, indeed.  Keeping it as is seems fine to me.

**Comment by nirizr** [comment]
Done. will rebase once the fix is merged. Already made sure build pass with it.

**Comment by nirizr** [comment]
I'm not quite sure why the last test fails. Could it be an actual bug?

**Comment by mrocklin** [comment]
Could be.  I would check out the actual hdf files written during the test.  A bit of pdb debugging my clear things up.

**Comment by nirizr** [comment]
Alright, I'll try investigating further. might take a day or two.

**Comment by jakirkham** [comment]
Any news on this?

**Comment by mrocklin** [comment]
Replacing with https://github.com/dask/dask/pull/1891 .  I identified the error.  to_hdf isn't multiprocess safe.  I haven't fixed it but have marked it with an xfail.  Closing this.

**Pull request closed without merging**
