### PR TITLE
Avoid using operator.itemgetter in dask.dataframe

### PR DESCRIPTION
**Pull request by mrocklin**
This is not serializable in Python 2

### CODE REVIEW

**Comment by mrocklin** [comment]
Fixes https://github.com/dask/distributed/issues/1254

**Comment by jcrist** [comment]
I'd prefer not to use a lambda here (which requires cloudpickle to serialize), but instead implement our own `itemgetter` class in `dask.utils`. We already do this for `methodcaller`.

**Comment by mrocklin** [comment]
How about toolz.curried.get?

**Comment by jcrist** [comment]
```python
class itemgetter(object):
    __slots__ = ('index',)
    def __init__(self, index):
        self.index = index

    def __call__(self, x):
        return x[self.index]

    def __reduce__(self):
        return (itemgetter, (self.index,))


def test_itemgetter():
    data = [1, 2, 3]
    g = itemgetter(1)
    assert g(data) == 2
    g2 = pickle.loads(pickle.dumps(g))
    assert g2(data) == 2
    assert g2.index == 1
```

**Comment by jcrist** [comment]
> How about toolz.curried.get?

That'd work, but serializes slower and into more bytes.

```python
In [11]: from toolz.curried import get

In [12]: g = get(1)

In [13]: g2 = itemgetter(1)  # my itemgetter class

In [14]: len(pickle.dumps(g))
Out[14]: 993

In [15]: len(pickle.dumps(g2))
Out[15]: 34

In [16]: %timeit pickle.dumps(g)
21.1 µs ± 331 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

In [17]: %timeit pickle.dumps(g2)
2.58 µs ± 49.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
```

**Comment by mrocklin** [comment]
Pushed

**Pull request merged**
