### PR TITLE
ENH: dd.get_dummies for categorical Series

### LINKED ISSUE #1581: Enable get_dummies for dask
Allow the user to use the Pandas get_dummies function with minimal to no changes for Pandas user experience

### PR DESCRIPTION
**Pull request by sinhrks**
Closes #1581.

It only support categorical ``Series`` to have correct ``columns`` as @TomAugspurger indicated.

### CODE REVIEW

**Comment by mrocklin** [comment]
This seems sensible to me.  @TomAugspurger any feedback?

**Comment by TomAugspurger** [comment]
@sinhrks Does anything break if we allow DataFrames? At least a DataFrame with no object type columns (so only the categorical ones are dummy encoded).

**Comment by TomAugspurger** [comment]
For instance, I've used it [here](https://github.com/TomAugspurger/sktransformers/blob/e83cd2e9b8c425e8bac420f4a48376b460a64dd0/sktransformers/preprocessing.py#L73) on a dask DataFrame, I think without issue. At that point it's expected that there are no object dtype columns.

**Comment by sinhrks** [comment]
@TomAugspurger Thx, added ``DataFrame`` support. ``get_dummies`` is applied only to columns with ``category`` dtype by default. Raises if ``object`` columns are specified.

**Comment by TomAugspurger** [comment]
Thanks for adding that, I think this looks great.

**Pull request merged**
