### PR TITLE
Add documentation build

### PR DESCRIPTION
**Pull request by jrbourbeau**
This PR adds a CI build to ensure the docs are built successfully. I'm using GitHub actions here to avoid adding more builds to our current Travis / AppVeyor CI. This has the benefit of catching changes that break documentation builds at the PR-level instead of discovering them after the fact when we notice RTD builds have been failing.

(currently just testing this out, but curious to hear what others think)

### CODE REVIEW

**Comment by jrbourbeau** [comment]
Looks like GitHub actions won't activate unless there is an action in the repo. The pandas team ran into this over in https://github.com/pandas-dev/pandas/pull/29661 and added a simple action with an `echo` to activate things. I'm happy to do the same here if we're interested in trying out GH actions.

Any objections to trying it out?

**Comment by TomAugspurger** [comment]
No objections here.

**Comment by jrbourbeau** [comment]
This should be ready for review. For reference the added documentation build takes ~1.5 minutes while the other CI builds on Travis and AppVeyor take around 20 minutes

**Comment by TomAugspurger** [comment]
Seems reasonable to me, though I've never used GitHub actions :) I say we merge it and revert if it starts causing issues.

**Comment by jrbourbeau** [comment]
That sounds good to me. Thanks for taking a look Tom!

**Pull request merged**
