### PR TITLE
groupby-nunique works on empty chunk

### LINKED ISSUE #4503: Groupby nunique on empty dataframe fails
There seems to be an issue when calling Groupby.nunique on an empty dataframe

On plain pandas:
```python
ua_pd_df = pandas.DataFrame(columns=['username', 'user_agent', 'requests'])
ua_pd_df.groupby(['user_agent']).username.nunique()
Series([], Name: username, dtype: int64)
```

On dask dataframe:

```python
ua_dd = dd.from_pandas(ua_pd_df, npartitions=5) 
ua_dd.groupby('user_agent').username.nunique().compute() 

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-76-d6bfb5ac8c8c> in <module>
----> 1 ua_df[['username', 'user_agent', 'requests']].groupby('user_agent').username.nunique().compute()

~/virtualenvs/esa-engine-dask3/lib/python3.6/site-packages/dask/base.py in compute(self, **kwargs)
    154         dask.base.compute
    155         """
--> 156         (result,) = compute(self, traverse=False, **kwargs)
    157         return result
    158 

~/virtualenvs/esa-engine-dask3/lib/python3.6/site-packages/dask/base.py in compute(*args, **kwargs)
    396     keys = [x.__dask_keys__() for x in collections]
    397     postcomputes = [x.__dask_postcompute__() for x in collections]
--> 398     results = schedule(dsk, keys, **kwargs)
    399     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    400 

~/virtualenvs/esa-engine-dask3/lib/python3.6/site-packages/distributed/client.py in get(self, dsk, keys, restrictions, loose_restrictions, resources, sync, asynchronous, direct, retries, priority, fifo_timeout, actors, **kwargs)
   2329             try:
   2330                 results = self.gather(packed, asynchronous=asynchronous,
-> 2331                                       direct=direct)
   2332             finally:
   2333                 for f in futures.values():

~/virtualenvs/esa-engine-dask3/lib/python3.6/site-packages/distributed/client.py in gather(self, futures, errors, maxsize, direct, asynchronous)
   1653             return self.sync(self._gather, futures, errors=errors,
   1654                              direct=direct, local_worker=local_worker,
-> 1655                              asynchronous=asynchronous)
   1656 
   1657     @gen.coroutine

~/virtualenvs/esa-engine-dask3/lib/python3.6/site-packages/distributed/client.py in sync(self, func, *args, **kwargs)
    673             return future
    674         else:
--> 675             return sync(self.loop, func, *args, **kwargs)
    676 
    677     def __repr__(self):

~/virtualenvs/esa-engine-dask3/lib/python3.6/site-packages/distributed/utils.py in sync(loop, func, *args, **kwargs)
    275             e.wait(10)
    276     if error[0]:
--> 277         six.reraise(*error[0])
    278     else:
    279         return result[0]

~/virtualenvs/esa-engine-dask3/lib/python3.6/site-packages/six.py in reraise(tp, value, tb)
    691             if value.__traceback__ is not tb:
    692                 raise value.with_traceback(tb)
--> 693             raise value
    694         finally:
    695             value = None

~/virtualenvs/esa-engine-dask3/lib/python3.6/site-packages/distributed/utils.py in f()
    260             if timeout is not None:
    261                 future = gen.with_timeout(timedelta(seconds=timeout), future)
--> 262             result[0] = yield future
    263         except Exception as exc:
    264             error[0] = sys.exc_info()

~/virtualenvs/esa-engine-dask3/lib/python3.6/site-packages/tornado/gen.py in run(self)
   1131 
   1132                     try:
-> 1133                         value = future.result()
   1134                     except Exception:
   1135                         self.had_exception = True

~/virtualenvs/esa-engine-dask3/lib/python3.6/site-packages/tornado/gen.py in run(self)
   1139                     if exc_info is not None:
   1140                         try:
-> 1141                             yielded = self.gen.throw(*exc_info)
   1142                         finally:
   1143                             # Break up a reference to itself

~/virtualenvs/esa-engine-dask3/lib/python3.6/site-packages/distributed/client.py in _gather(self, futures, errors, direct, local_worker)
   1494                             six.reraise(type(exception),
   1495                                         exception,
-> 1496                                         traceback)
   1497                     if errors == 'skip':
   1498                         bad_keys.add(key)

~/virtualenvs/esa-engine-dask3/lib/python3.6/site-packages/six.py in reraise(tp, value, tb)
    690                 value = tp()
    691             if value.__traceback__ is not tb:
--> 692                 raise value.with_traceback(tb)
    693             raise value
    694         finally:

~/virtualenvs/esa-engine-dask3/lib/python3.6/site-packages/dask/compatibility.py in apply()
     91     def apply(func, args, kwargs=None):
     92         if kwargs:
---> 93             return func(*args, **kwargs)
     94         else:
     95             return func(*args)

~/virtualenvs/esa-engine-dask3/lib/python3.6/site-packages/dask/dataframe/groupby.py in _nunique_df_aggregate()
    315 
    316 def _nunique_df_aggregate(df, levels, name):
--> 317     return df.groupby(level=levels, sort=False)[name].nunique()
    318 
    319 

~/virtualenvs/esa-engine-dask3/lib/python3.6/site-packages/pandas/core/base.py in __getitem__()
    273         else:
    274             if key not in self.obj:
--> 275                 raise KeyError("Column not found: {key}".format(key=key))
    276             return self._gotitem(key, ndim=1)
    277 

KeyError: 'Column not found: username'
```
Any other method to use to get the number of unique values per group?

Dask: v1.1.1
Python: v3.6
Dask distributed: v1.25.3

### PR DESCRIPTION
**Pull request by jcrist**
Previously this would error out, as groupby-apply fails to preserve
metadata on empty chunks.

Also adds a test for the other groupby reductions on empty data.

Fixes #4503.

### CODE REVIEW

**Comment by jcrist** [comment]
Looks like empty groupby-reductions fail for old versions of pandas (at least up to 0.20.2). I'm fine punting on this issue and just skipping that test for older pandas versions (things work fine on recent releases). Thoughts @TomAugspurger?

**Comment by TomAugspurger** [comment]
Yep, skipping for old pandas seems fine.

**Comment by mrocklin** [comment]
Are you +1 on this @TomAugspurger ?

**Comment by tbazadaykin** [comment]
Does it released already? 2.30.0 still crushed on it.

**Pull request merged**
