### PR TITLE
Landing page

### PR DESCRIPTION
**Pull request by mrocklin**
This is a high-level landing page for Dask's main site.
It mostly links to the documentation, but with a more aesthetic first
impression.

This adds a single HTML and small CSS file.
All larger CSS and images are hosted separately.

Fixes https://github.com/dask/dask/issues/3174

### CODE REVIEW

**Comment by mrocklin** [comment]
Critical feedback or commits to this branch would be quite welcome.  I'm separately hosting the original version of this page here: http://matthewrocklin.com/dask-webpage/

**Comment by martindurant** [comment]
Will there be links from the main documentation back to the landing page? 
(I understand you wouldn't want to change them yet)

At some point we were talking about making a list of "related projects" more prominent, and it would be nice of course to have some set of "successes". I mention this here, because you often see such things on this style of project page.

**Comment by mrocklin** [comment]
Such links currently exist.

Yes, I would love to see a list of related projects but I'm currently shooting for a minimal viable solution.

**Comment by jakirkham** [comment]
Generally really like this. Visually appealing. Puts things in terms of what users are likely familiar with which is good. Very minimal, which it makes the meat of the content really stick out, which is great. Have a few suggestions.

First it seems like left to right we have NumPy, Pandas, Scikit-Learn. Though the examples go Pandas, NumPy, Scikit-Learn. Would be nice if they were organized to flow in the same way.

Another consideration along these lines would be to have the example code laid out horizontally to match.

Second the font on the graphics for the NumPy, Pandas, Scikit-Learn parts is a little small. Would try to address the Pandas one in particular as that's very small. Ideally the Dask Dataframe and Pandas Dataframe text would be a bit larger. The other info there is less important. So it could be a little bigger, but we wouldn't want it to dominate.

Third the Scikit-Learn graph looks cool, but offhand not totally sure what I'm looking at. Maybe a graph title would help give it context.

**Comment by mrocklin** [comment]
> Would be nice if they were organized to flow in the same way

Fixed in this PR, not in the demo website

> Another consideration along these lines would be to have the example code laid out horizontally to match.

Could do.  If so what image should we put where they are currently?

> Second the font on the graphics for the NumPy, Pandas, Scikit-Learn parts is a little small. Would try to address the Pandas one in particular as that's very small. Ideally the Dask Dataframe and Pandas Dataframe text would be a bit larger. The other info there is less important. So it could be a little bigger, but we wouldn't want it to dominate.

That seems reasonable.  We use the same image everywhere though so this might have unintended consequences.  I'll bump it up a bit and see how it looks.

**Comment by mrocklin** [comment]
> Third the Scikit-Learn graph looks cool, but offhand not totally sure what I'm looking at. Maybe a graph title would help give it context.

A title like "The Rosenbrock function" might be a bit distracting.  Can you think of a better image that we might use?

**Comment by mrocklin** [comment]
Any further comments on this?  Planning to merge this tomorrow afternoon if there are no further comments.

**Comment by jakirkham** [comment]
> > Another consideration along these lines would be to have the example code laid out horizontally to match.
>
> Could do.  If so what image should we put where they are currently?

So was mainly thinking of this in the context that users see NumPy, Pandas, and Scikit-Learn listed and as a they scroll down they see relevant snippets of code under these headings. Not sure that there would be room for another image based on this layout.

>> Third the Scikit-Learn graph looks cool, but offhand not totally sure what I'm looking at. Maybe a graph title would help give it context.
>
> A title like "The Rosenbrock function" might be a bit distracting.  Can you think of a better image that we might use?

Would recommend taking a look at some of the images scikit-learn has. Maybe a plot or plots of results from a common classifier or clustering algorithm would be good. Though I'm guessing @TomAugspurger can make better suggestions here.

**Comment by mrocklin** [comment]
> Would recommend taking a look at some of the images scikit-learn has. Maybe a plot or plots of results from a common classifier or clustering algorithm would be good. Though I'm guessing @TomAugspurger can make better suggestions here.

That's a nice idea.  The carousel they have on their frontpage has a few nice samples.  Maybe this one: http://scikit-learn.org/stable/auto_examples/classification/plot_classifier_comparison.html ?

**Comment by mrocklin** [comment]
> So was mainly thinking of this in the context that users see NumPy, Pandas, and Scikit-Learn listed and as a they scroll down they see relevant snippets of code under these headings. Not sure that there would be room for another image based on this layout.

OK, I'm not sure I understand your suggestion then.  Are you suggesting transposing the numpy/pandas/scikit-learn bits so that they are horizontal?  If you're able to describe things more explicitly that might help.  I guess it's hard to discuss 2d layouts in text :)

**Comment by jakirkham** [comment]
Yeah that classifier comparison did look pretty nice.

Not sure what classifiers we already include. So might want to be somewhat careful that the graphs included matching things that are available (lest they are followed with questions of why doesn't this exist ;). Then again, could result in useful feedback/positive encouragement to include other popular classifiers.

That's fair. It is hard to describe this in text. Yes, was meaning to transpose them.

**Comment by jcrist** [comment]
Only change I would suggest is to better demarcate the difference between the tiny dask logo in the upper left and the "Why dask" link. Currently the spacing makes this look like less of a link than the other links. Possibly just needs more space between the logo and the text, or a vertical bar to separate (like `|`, but not actually the pipe character)

Additionally, I might add a link to the doc landing page to the top bar, but there's already a lot of links up there.

**Comment by mrocklin** [comment]
Added a margin around the logo.  Should we add a link with the title "Documentation" or no?  Alternatively, we could collapse arrays, dataframes, ... into a dropdown if that's nicer.

**Comment by jcrist** [comment]
> Alternatively, we could collapse arrays, dataframes, ... into a dropdown if that's nicer.

I think that'd be good. Suggested links and drop down:

```
Why Dask | Documentation | Install | Deploy | Tutorial
------------------------------------------------------
           Overview
           Arrays
           DataFrames
           Machine Learning
           Custom Applications
           Real Time
```

**Comment by shoyer** [comment]
I like the webpage. It's a nice succinct pitch for Dask!

It would be nice if the dask docs looked slightly more consistent with the homepage -- maybe if the Dask logo appeared on the upper left of every page? [ReadTheDocs has some instructions that look relevant](http://docs.readthedocs.io/en/latest/custom_installs/customization.html) (and does this for their own docs), but I haven't figured out exactly how, yet.

**Comment by TomAugspurger** [comment]
> So might want to be somewhat careful that the graphs included match things that are available

I wouldn't worry about this, since we have things like `distributed.joblib`, and `ParallelPostFit`, which can be used with (almost) any scikit-learn esetimator.

**Comment by jcrist** [comment]
> It would be nice if the dask docs looked slightly more consistent with the homepage -- maybe if the Dask logo appeared on the upper left of every page?

I think the numba docs do a good job of this (see https://github.com/numba/numba/tree/master/docs and http://numba.pydata.org/numba-doc/0.37.0/index.html). Looks like they use the `sphinx_bootstrap_theme`, which comes with support for a logo. I think that should be a separate PR though.

**Comment by mrocklin** [comment]
image

**Comment by jcrist** [comment]
Looks great!

**Comment by mrocklin** [comment]
OK, I'm merging this in a few hours of there are no further comments.

**Comment by mrocklin** [comment]
Thanks also to @birdsarah who provided some design guidance during this process.

**Comment by mrocklin** [comment]
This is live: http://dask.pydata.org/en/latest/

Additional feedback requested.  I suspect that we'll get many small suggestions now that it has a wider audience.

**Comment by alimanfoo** [comment]
Really nice! Typo in "sattelite". Also you could add "genomics" to the list of application areas if you like, although no worries if covered by "biomedical sciences".

**Comment by mrocklin** [comment]
> Really nice! Typo in "sattelite". Also you could add "genomics" to the list of application areas if you like, although no worries if covered by "biomedical sciences".

Thanks!  Hot-fixed the typo.

**Pull request merged**
