### PR TITLE
Fix example of using blockwise for an outer product

### LINKED ISSUE #7118: Example outer product implementation doesn't work
The docstring for `dask.array.blockwise` contains this example:

```python
z = blockwise(operator.mul, 'ij', x, 'i', y, 'j', dtype='f8')  # doctest: +SKIP
```

However, it doesn't actually work (computing it fails), because `operator.mul` between two 1D chunks produces another 1D chunk, not a 2D outer product of the chunks. I think replacing it with `np.outer` will work, but I'll double-check and make a PR.

### PR DESCRIPTION
**Pull request by bmerry**
Closes #7118.

- [x] Tests added / passed
- [x] Passes `black dask` / `flake8 dask`

### CODE REVIEW

**Comment by jsignell** [comment]
Thanks! It'd be nice if the doctests ran on this code. Would you be able to add the setup so that that could work?

**Comment by bmerry** [comment]
> It'd be nice if the doctests ran on this code. Would you be able to add the setup so that that could work?

I'll try to take a look next week - I have a few things on fire at the moment.

**Comment by bmerry** [comment]
> Thanks! It'd be nice if the doctests ran on this code. Would you be able to add the setup so that that could work?

Done

**Comment by jsignell** [comment]
Thanks!

**Pull request merged**
