### PR TITLE
Update dashboard docs for queuing

### PR DESCRIPTION
**Pull request by gjoseph92**
Closes https://github.com/dask/distributed/issues/7306.

Also some driveby fixes of typos/small inaccuracies in the docs (not exhaustive).

- [x] Tests added / passed
- [x] Passes `pre-commit run --all-files`

### CODE REVIEW

**Comment by gjoseph92** [comment]
https://dask--9660.org.readthedocs.build/en/9660/dashboard.html#progress

**Review by ncclementi — COMMENTED** [review]
This LGTM, we are seeing multiple failures but they are unrelated to this PR. 
The only doubt I have and not sure what's going on is with the linting check

**Comment by gjoseph92** [comment]
```
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f26ec47bbe0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /packages/b2/6c/9ccb5213a3d9fd3f8c0fd69d207951901eaef86b7a1a69bcc478364d3072/pre_commit-2.20.0-py2.py3-none-any.whl
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f26ec47beb0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /packages/b2/6c/9ccb5213a3d9fd3f8c0fd69d207951901eaef86b7a1a69bcc478364d3072/pre_commit-2.20.0-py2.py3-none-any.whl
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f26ec47bf70>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /packages/b2/6c/9ccb5213a3d9fd3f8c0fd69d207951901eaef86b7a1a69bcc478364d3072/pre_commit-2.20.0-py2.py3-none-any.whl
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f26ec4a4040>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /packages/b2/6c/9ccb5213a3d9fd3f8c0fd69d207951901eaef86b7a1a69bcc478364d3072/pre_commit-2.20.0-py2.py3-none-any.whl
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f[26](https://github.com/dask/dask/actions/runs/3465838377/jobs/5789036313#step:4:28)ec4a42b0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /packages/b2/6c/9ccb5213a3d9fd3f8c0fd69d207951901eaef86b7a1a69bcc478364d3072/pre_commit-2.20.0-py2.py3-none-any.whl
ERROR: Could not install packages due to an OSError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/b2/6c/9ccb5213a3d9fd3f8c0fd69d207951901eaef86b7a1a69bcc478364d3072/pre_commit-2.20.0-py2.py3-none-any.whl (Caused by NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f26ec4a4460>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
```
for linting: some transient pip stuff setting up pre-commit

**Comment by jrbourbeau** [comment]
Yep, looks like a connection blip -- restarting that CI build

**Comment by ncclementi** [comment]
@gjoseph92 Thanks for this, will merge this in!

**Pull request merged**
