### PR TITLE
Fix CI failures

### PR DESCRIPTION
**Pull request by jrbourbeau**

### CODE REVIEW

**Comment by mrocklin** [comment]
(thanks for working to track this down @jrbourbeau )

**Comment by jrbourbeau** [comment]
The `test_frame_series_arithmetic_methods` failure here looks genuine (https://travis-ci.org/github/dask/dask/jobs/662027956#L1198-L1329) and started with the recent pandas 1.0.2 release. Looking at the [1.0.2 release notes](https://pandas.pydata.org/docs/whatsnew/v1.0.2.html), https://github.com/pandas-dev/pandas/pull/31679 is the only change related to arithmetic operations. @TomAugspurger any ideas on what needs to change on our end?

**Comment by TomAugspurger** [comment]
Thanks James. You may need to xfail that for pandas>=1.0.2 for now. https://github.com/pandas-dev/pandas/issues/32685.

**Comment by jrbourbeau** [comment]
Done, thanks @TomAugspurger!

**Comment by jrbourbeau** [comment]
Summarizing the conda environment changes:

- `pip` installing `cityhash` was causing Windows CI compilation errors, but unfortunately there's no `cityhash` package on conda-forge to switch to

- We've removed `cityhash` from the conda environment files, but are still installing it in our Travis builds https://github.com/dask/dask/blob/ee6a769d5776f8aef379ef23e34400882db11f1a/continuous_integration/travis/install.sh#L30

    - Interestingly, `conda list` on previous GH actions Windows builds wasn't showing `cityhash`, `xxhash`, or `mmh3` as installed packages. I checked older AppVeyor builds and saw a similar lack of installed packages. Not sure if these packages were ever actually installed or if `conda list` was inaccurate somehow. 

- We've switched to installing `xxhash` and `mmh3` from conda-forge instead of PyPI to hopefully reduce future installation issues.

**Comment by jrbourbeau** [comment]
The Windows 3.7 failure is a known flaky test (xref #5910). Planning to merge this once other CI builds pass

**Comment by mrocklin** [comment]
> pip installing cityhash was causing Windows CI compilation errors, but unfortunately there's no cityhash package on conda-forge to switch to

@jjhelmus ?

**Comment by jrbourbeau** [comment]
xref https://github.com/conda-forge/staged-recipes/pull/11057. Looks like the same Windows compiler flag issue is happening over there too. May need to make an upstream change or patch in the recipe

**Pull request merged**
