### PR TITLE
Map e.g. `.repartition(freq="M")` to `.repartition(freq="MS")`

### PR DESCRIPTION
**Pull request by rubenvdg**
Currently, if you naively repartition a dataframe on months, observations of the last day of each month will be part of the next month's partition. Example:

```
import dask.dataframe as dd
import pandas as pd

pdf = pd.DataFrame(
    index=[
        pd.Timestamp("2020-1-31 15:00:00"),  # January
        pd.Timestamp("2020-2-1 15:00:00")    # February
    ],
    data={"foo": "foo"}
)

ddf = dd.from_pandas(pdf, npartitions=1).repartition(freq="M")
>>> ddf.npartitions  # you expect two partitions (one for January, one for February)
1
```

You **should** do:
```
ddf = dd.from_pandas(pdf, npartitions=1).repartition(freq="MS")
```
to get the desired result (namely two partitions with each one observation). 

This PR proposes to map
- "M" to "MS"
- "Q" to "QS"
- "Y" to "YS"
- and all the other exotic variants that pandas offers (e.g., "3BQS-JUN")

- [ ] Closes nothing (PR follows discussion [here](https://github.com/dask/dask/pull/7470))
- [x] Tests added / passed
- [x] Passes `black dask` / `flake8 dask` / `isort dask`

### CODE REVIEW

**Comment by rubenvdg** [comment]
I realize this is maybe a bit abstract logic, but the alternative is to hard code the mappings.

**Comment by rubenvdg** [comment]
Hmmm tests are failing (but locally everything runs smooth). Will check that out later.

**Comment by jsignell** [comment]
The CI failures seem related to this PR. The python 3.7 and mindeps-array-dataframe tests pin to pandas 0.25.0 so I imagine something changed between that version and more recent pandas. You can skip the tests based on the pandas version, but it'd be good to try to write a test to make sure that the behavior is as expected for the old version of pandas as well.

```python-traceback
=================================== FAILURES ===================================
___________________ test_map_freq_to_period_start[Q-QS-JAN] ____________________
[gw1] linux -- Python 3.7.10 /usr/share/miniconda3/envs/test-environment/bin/python

freq = 'Q', expected_freq = 'QS-JAN'

    @pytest.mark.parametrize(
        "freq, expected_freq",
        [
            ("M", "MS"),
            ("MS", "MS"),
            ("2M", "2MS"),
            ("Q", "QS-JAN"),
            ("2Q", "2QS-JAN"),
            ("BQ", "BQS-JAN"),
            ("2BQ", "2BQS-JAN"),
            ("SM", "SMS-15"),
            ("A", "AS-JAN"),
            ("A-FEB", "AS-MAR"),
            ("BA", "BAS-JAN"),
            ("2BA", "2BAS-JAN"),
            ("BY", "BAS-JAN"),
            ("Y", "AS-JAN"),
            (pd.Timedelta(seconds=1), pd.Timedelta(seconds=1)),
        ],
    )
    def test_map_freq_to_period_start(freq, expected_freq):
        new_freq = _map_freq_to_period_start(freq)
>       assert new_freq == expected_freq
E       AssertionError: assert 'QS-MAR' == 'QS-JAN'
E         - QS-JAN
E         + QS-MAR

dask/dataframe/tests/test_dataframe.py:2100: AssertionError
__________________ test_map_freq_to_period_start[2Q-2QS-JAN] ___________________
[gw1] linux -- Python 3.7.10 /usr/share/miniconda3/envs/test-environment/bin/python

freq = '2Q', expected_freq = '2QS-JAN'

    @pytest.mark.parametrize(
        "freq, expected_freq",
        [
            ("M", "MS"),
            ("MS", "MS"),
            ("2M", "2MS"),
            ("Q", "QS-JAN"),
            ("2Q", "2QS-JAN"),
            ("BQ", "BQS-JAN"),
            ("2BQ", "2BQS-JAN"),
            ("SM", "SMS-15"),
            ("A", "AS-JAN"),
            ("A-FEB", "AS-MAR"),
            ("BA", "BAS-JAN"),
            ("2BA", "2BAS-JAN"),
            ("BY", "BAS-JAN"),
            ("Y", "AS-JAN"),
            (pd.Timedelta(seconds=1), pd.Timedelta(seconds=1)),
        ],
    )
    def test_map_freq_to_period_start(freq, expected_freq):
        new_freq = _map_freq_to_period_start(freq)
>       assert new_freq == expected_freq
E       AssertionError: assert '2QS-MAR' == '2QS-JAN'
E         - 2QS-JAN
E         + 2QS-MAR

dask/dataframe/tests/test_dataframe.py:2100: AssertionError
__________________ test_map_freq_to_period_start[BQ-BQS-JAN] ___________________
[gw1] linux -- Python 3.7.10 /usr/share/miniconda3/envs/test-environment/bin/python

freq = 'BQ', expected_freq = 'BQS-JAN'

    @pytest.mark.parametrize(
        "freq, expected_freq",
        [
            ("M", "MS"),
            ("MS", "MS"),
            ("2M", "2MS"),
            ("Q", "QS-JAN"),
            ("2Q", "2QS-JAN"),
            ("BQ", "BQS-JAN"),
            ("2BQ", "2BQS-JAN"),
            ("SM", "SMS-15"),
            ("A", "AS-JAN"),
            ("A-FEB", "AS-MAR"),
            ("BA", "BAS-JAN"),
            ("2BA", "2BAS-JAN"),
            ("BY", "BAS-JAN"),
            ("Y", "AS-JAN"),
            (pd.Timedelta(seconds=1), pd.Timedelta(seconds=1)),
        ],
    )
    def test_map_freq_to_period_start(freq, expected_freq):
        new_freq = _map_freq_to_period_start(freq)
>       assert new_freq == expected_freq
E       AssertionError: assert 'BQS-MAR' == 'BQS-JAN'
E         - BQS-JAN
E         + BQS-MAR

dask/dataframe/tests/test_dataframe.py:2100: AssertionError
_________________ test_map_freq_to_period_start[2BQ-2BQS-JAN] __________________
[gw1] linux -- Python 3.7.10 /usr/share/miniconda3/envs/test-environment/bin/python

freq = '2BQ', expected_freq = '2BQS-JAN'

    @pytest.mark.parametrize(
        "freq, expected_freq",
        [
            ("M", "MS"),
            ("MS", "MS"),
            ("2M", "2MS"),
            ("Q", "QS-JAN"),
            ("2Q", "2QS-JAN"),
            ("BQ", "BQS-JAN"),
            ("2BQ", "2BQS-JAN"),
            ("SM", "SMS-15"),
            ("A", "AS-JAN"),
            ("A-FEB", "AS-MAR"),
            ("BA", "BAS-JAN"),
            ("2BA", "2BAS-JAN"),
            ("BY", "BAS-JAN"),
            ("Y", "AS-JAN"),
            (pd.Timedelta(seconds=1), pd.Timedelta(seconds=1)),
        ],
    )
    def test_map_freq_to_period_start(freq, expected_freq):
        new_freq = _map_freq_to_period_start(freq)
>       assert new_freq == expected_freq
E       AssertionError: assert '2BQS-MAR' == '2BQS-JAN'
E         - 2BQS-JAN
E         ?      ^ ^
E         + 2BQS-MAR
E         ?      ^ ^

dask/dataframe/tests/test_dataframe.py:2100: AssertionError
_________________ test_map_freq_to_period_start[A-FEB-AS-MAR] __________________
[gw1] linux -- Python 3.7.10 /usr/share/miniconda3/envs/test-environment/bin/python

freq = 'A-FEB', expected_freq = 'AS-MAR'

    @pytest.mark.parametrize(
        "freq, expected_freq",
        [
            ("M", "MS"),
            ("MS", "MS"),
            ("2M", "2MS"),
            ("Q", "QS-JAN"),
            ("2Q", "2QS-JAN"),
            ("BQ", "BQS-JAN"),
            ("2BQ", "2BQS-JAN"),
            ("SM", "SMS-15"),
            ("A", "AS-JAN"),
            ("A-FEB", "AS-MAR"),
            ("BA", "BAS-JAN"),
            ("2BA", "2BAS-JAN"),
            ("BY", "BAS-JAN"),
            ("Y", "AS-JAN"),
            (pd.Timedelta(seconds=1), pd.Timedelta(seconds=1)),
        ],
    )
    def test_map_freq_to_period_start(freq, expected_freq):
        new_freq = _map_freq_to_period_start(freq)
>       assert new_freq == expected_freq
E       AssertionError: assert 'AS-JAN' == 'AS-MAR'
E         - AS-MAR
E         + AS-JAN

dask/dataframe/tests/test_dataframe.py:2100: AssertionError
```

**Comment by rubenvdg** [comment]
@jsignell You're totally right, sorry. I pushed a fix and now all seems OK. So ready for review IMO.

**Review by jsignell — APPROVED** [review]
This looks good to me and I think the behavior will be much less surprising. Thanks for opening this @rubenvdg! 

@TomAugspurger I am planning on merging this on Wednesday unless you have qualms :)

**Comment by TomAugspurger** [comment]
Hmm I thought I had left a comment here but I don't see it.

It feels wrong to be guessing at the user's intent here. How do you know that they wanted MS rather than Month-end? But perhaps I'm missing context.

**Comment by jsignell** [comment]
This work is based converastaions leading up to https://github.com/dask/dask/pull/7470#issuecomment-808410433. I think the strangeness has to do with the fact that repartition uses the frequency as a period rather than aggregating to one time. It seems to me that regardless of whether you put `M`, `ME` or `MS` you want all of January in one partition right? So coercing to `MS` is really just an implementation detail.

**Comment by rubenvdg** [comment]
@jsignell Just checking in if the idea is to carry on with this? Something else I can do for this?

**Comment by jsignell** [comment]
Yeah thanks for the reminder. @TomAugspurger I'll plan to merge this today unless my assumptions in https://github.com/dask/dask/pull/7504#issuecomment-813444208 are wrong? Or is there some one else I should check with? Maybe @jorisvandenbossche?

**Comment by jsignell** [comment]
Ok I merged, but let's keep an eye out for issues that might be related to this. Thanks for your work and your patience @rubenvdg!

**Pull request merged**
