### PR TITLE
dask.array: Don't use dummy expansion for trim_internal in overlapped

### LINKED ISSUE #3947: performance of `map_overlap` with boundary='none' is hindered by `add_dummy_padding`
`map_overlap` provides a few boundary conditions. The performance of the `'none'` boundary condition is seriously affected when the array is trimmed  since `dummy_padding` is added to the array which forces a whole copy of the array.

To illustrate the problem, I define a convenience function that implements the trim logic at the end of `map_overlap`.

Benchmark:

```python
from dask import array as da
from dask.array.overlap import (coerce_boundary, 
                                coerce_depth, 
                                trim_internal, 
                                add_dummy_padding)
shape=(150, 1024, 1024)
chunks=(-1, 512, 512)
dtype='float32'
z = da.zeros(shape=shape, chunks=chunks, dtype=dtype).persist()

# convenience function, inverse of da.overlap.overlap
# logic taken from map_overlap
def trim(x, depth, boundary=None):
    boundary2 = coerce_boundary(x.ndim, boundary)
    depth2 = coerce_depth(x.ndim, depth)
    
    x2 = add_dummy_padding(x, depth2, boundary2)
    return trim_internal(x2, depth2)

# Call once to force python to load all the necessary modules
_ = trim(z, 10, boundary='nearest').persist()
%time _ = trim(z, 10, boundary='none').persist()
%time _ = trim(z, 10, boundary='nearest').persist()
%time _ = trim(z, 10, boundary='none').persist()
%time _ = trim(z, 10, boundary='nearest').persist()
%time _ = trim(z, 10, boundary='none').persist()
%time _ = trim(z, 10, boundary='nearest').persist()
```

Results: 
* 'nearest' finishes in 30 ms
* 'none' finishes in 500 ms

# Computation graph
## Trimming with 'nearest'

```python
trim(z, 10, boundary='nearest').visualize()
```

image

## Trimming with 'none'

```python
trim(z, 10, boundary='none').visualize()
```
mydask

This is very likely the issue I was seeing in Issue #3938 

cc: @jni

### PR DESCRIPTION
**Pull request by hmaarrfk**
… computations

Fixes #3947

- [ ] Tests added / passed
- [ ] Passes `flake8 dask`

### CODE REVIEW

**Comment by hmaarrfk** [comment]
Note to self. I guess i need to specify the partial arguments as kwargs for python 2.7 to take them in.

**Comment by mrocklin** [comment]
Except for the Python 2 errors things here seems sensible to me.  @jakirkham might find this PR interesting.  

@hmaarrfk if I recall correctly you have a small benchmark where this showed significant speed improvement.  Would you might including a small example as a comment in this PR?  We might also include the speed difference in the commit message.

**Comment by hmaarrfk** [comment]
2.7 bug is fixed in #3966

**Comment by hmaarrfk** [comment]
# Benchmark

Adapted from https://github.com/dask/dask/issues/3947#issue-357016692

`map_overlap` provides a few boundary conditions. The performance of the `'none'` boundary condition is seriously affected when the array is trimmed  since `dummy_padding` is added to the array which forces a whole copy of the array.

To illustrate the problem, I define a convenience function that implements the trim logic at the end of `map_overlap`.


Benchmark:

```python
from dask import array as da
from dask.array.overlap import (coerce_boundary, 
                                coerce_depth, 
                                trim_internal, 
                                trim_overlap,
                                add_dummy_padding)
shape=(150, 1024, 1024)
chunks=(-1, 512, 512)
dtype='float32'
z = da.zeros(shape=shape, chunks=chunks, dtype=dtype).persist()

# convenience function, inverse of da.overlap.overlap
# logic taken from map_overlap (before this patch)
def trim(x, depth, boundary=None):
    boundary2 = coerce_boundary(x.ndim, boundary)
    depth2 = coerce_depth(x.ndim, depth)
    
    x2 = add_dummy_padding(x, depth2, boundary2)
    return trim_internal(x2, depth2)

# Call once to force python to load all the necessary modules
_ = trim(z, 10, boundary='nearest').persist()
%time _ = trim(z, 10, boundary='none').persist()
%time _ = trim(z, 10, boundary='nearest').persist()
%time _ = trim_overlap(z, 10, boundary='none').persist()
%time _ = trim_overlap(z, 10, boundary='nearest').persist()

%time _ = trim(z, 10, boundary='none').persist()
%time _ = trim(z, 10, boundary='nearest').persist()
%time _ = trim_overlap(z, 10, boundary='none').persist()
%time _ = trim_overlap(z, 10, boundary='nearest').persist()
```

Results: 
* 'nearest' finishes in 30 ms
* 'none' finishes in 500 ms
* new trim_overlap boundary='none' finishes in 2ms
* new trim_overlap boundary='nearest' finishes in 2ms

# Computation graph
## Trimming with 'nearest'

```python
trim(z, 10, boundary='nearest').visualize()
```

image

## Trimming with 'none'

```python
trim(z, 10, boundary='none').visualize()
```
mydask

cc: @jni 

Much to my surprise, this speeds up boundary='nearest' as well.

**Comment by hmaarrfk** [comment]
oh i didnt see that you had merged into my branch i guess i rebased and forced pushed...

**Comment by hmaarrfk** [comment]
@mrocklin do you have any insight as to why this sped up `normal` bdy conditions too? 30ms -> 2ms

**Comment by mrocklin** [comment]
To be honest I don't have great recall over this part of the codebase.  You
may be the world expert right now :)

**Comment by hmaarrfk** [comment]
What do you want to do with the function `add_dummy_padding`. Here is the docstring from that function

```python
    Pads an array which has 'none' as the boundary type.
    Used to simplify trimming arrays which use 'none'.

    >>> import dask.array as da
    >>> x = da.arange(6, chunks=3)
    >>> add_dummy_padding(x, {0: 1}, {0: 'none'}).compute()  # doctest: +NORMALIZE_WHITESPACE
    array([..., 0, 1, 2, 3, 4, 5, ...])
```

Had you done any changes to it before I erased yours?

Also, the results of that benchmark still baffle me. I thought that it was serialization thing where because I defined the function from the REPL dask was having a hard time making the bytecode for it. Unfortunately, even if I move the old and new code into the benchmark script, I get the same results :S.

I even modified it with:
```python
def trim(x, depth, boundary=None):
    boundary2 = coerce_boundary(x.ndim, boundary)
    depth2 = coerce_depth(x.ndim, depth)
    
    x2 = add_dummy_padding(x, depth2, boundary2)
    if boundary == 'nearest':
        print('got here')
        assert x is x2
    return trim_internal(x2, depth2)
```
and in fact, nearest just passes x2 as x, so I'm really confused.

**Comment by hmaarrfk** [comment]
I wouldn't trust the 30ms -> 2ms speedup. Trying a few different combination out, I think `z.persist` doesn't do what I thought it did. I thought it moved the memory to the workers, but guess it doesn't. 

There is definitely some memory issues (page faulting), that are causing the 30ms number to appear.

```
from dask import array as da
from dask.array.overlap import (coerce_boundary, 
                                coerce_depth, 
                                trim_internal, 
                                trim_overlap,
                                add_dummy_padding)
import numpy as np
shape=(150, 1024, 1024)
chunks=(-1, 512, 512)
dtype='float32'

z = da.from_array(np.random.random(size=shape).astype(dtype), chunks=chunks, name=False).persist()

# convenience function, inverse of da.overlap.overlap
# logic taken from map_overlap (before this patch)
def trim(x, depth, boundary=None):
    boundary2 = coerce_boundary(x.ndim, boundary)
    depth2 = coerce_depth(x.ndim, depth)
    
    x2 = add_dummy_padding(x, depth2, boundary2)
    return trim_internal(x2, depth2)

# Call once to force python to load all the necessary modules
# _ = trim(z, 10, boundary='nearest').persist()
%time _ = trim_overlap(z, 10, boundary='nearest').persist()
%time _ = trim(z, 10, boundary='nearest').persist()
%time _ = trim_overlap(z, 10, boundary='none').persist()
# Don't put this benchmark first, as it will trash the RAM
%time _ = trim(z, 10, boundary='none').persist()

%time _ = trim(z, 10, boundary='nearest').persist()
%time _ = trim_overlap(z, 10, boundary='nearest').persist()
%time _ = trim_overlap(z, 10, boundary='none').persist()
%time _ = trim(z, 10, boundary='none').persist()
```
A best case time of 2ms can be achieved on `nearest` for the old code and new code. A worst case time of `30 ms` can also be acheived for the `nearest` computation. (2400MHz memory, 16 GB of RAM, dual channel, i7 7700HQ, Ubuntu 16.04 64 bit)

The 500 ms number seems consistent.

**Comment by hmaarrfk** [comment]
Right thanks for pointing that out. 

Still I don't undertand the huge difference in performance from 30ms to 2ms for operations that should effective call the dask infrastructure and a graph with no-ops

**Comment by mrocklin** [comment]
You might find these mechanisms helpful to help figure out what's going on:
http://dask.pydata.org/en/latest/understanding-performance.html

**Comment by mrocklin** [comment]
@jakirkham and @hmaarrfk you two might want to trade reviewing each others' PRs at https://github.com/dask/dask/pull/3958 and https://github.com/dask/dask/pull/3964

**Comment by hmaarrfk** [comment]
@jakirkham I've added a new api function `trim_overlaped` do I need to add it to:  `docs/source/array-api.rst` manually?

**Comment by mrocklin** [comment]
> I've added a new api function trim_overlaped do I need to add it to: docs/source/array-api.rst manually?

Sorry for the delay in response.  Yes, we handle API docs manually.  I think that there is a section in the array api docs that is about overlapped.  Presumably this would go there.

**Comment by mrocklin** [comment]
If there are no further comments on this I plan to merge this at the end of the day.

**Comment by hmaarrfk** [comment]
Did you want me to add things to the docs first? or were you going to do it?

**Comment by mrocklin** [comment]
@jakirkham if you're around before then to look at things that would be welcome

**Comment by mrocklin** [comment]
> Did you want me to add things to the docs first? or were you going to do it?

I don't plan to do this, no.  I'm somewhat busy with other things.  I just wanted to make sure that this PR didn't linger for too long. If you have time to add docs that would be welcome.

**Comment by hmaarrfk** [comment]
Just a ping. I think I added the required info to the docs. Let me know if you need anything else.

**Comment by jakirkham** [comment]
Sorry to be absent here. I'll try to look, but unfortunately can't promise anything before Friday. If other people are happy with this, would encourage you to move ahead without me.

**Comment by mrocklin** [comment]
OK, I'm going to go ahead and merge.  Retroactive reviewing would still be welcome @jakirkham if you have time.

**Comment by mrocklin** [comment]
Thanks for the work here @hmaarrfk .  It's nice to see someone take on performance for in-memory use cases.

**Pull request merged**
