### PR TITLE
Improve hashing in dd.shuffle

### PR DESCRIPTION
**Pull request by jcrist**
Previously, python's `hash` function was used to hash indices for partitioning in shuffle. This could lead to non-ideal behavior, as python's hash function could have low entropy (on my machine `hash((a,
b)) % 5 == 1` for any integers `a` and `b`). This also was slow-ish for large chunks, as it doesn't take advantage of numpy/pandas vectorized operations.

This implements a custom elementwise hashing operation for use in shuffle partitioning. Each pandas dtype has a small function to map a series of that type deterministically to an integer array (the hashes),
which are then combined iteratively with a simple `new_hash = 3 * hash1 + hash2`. This is both faster (as it takes advantage of vectorization for non object columns), and seems to partition more evenly in many cases.

This also fixes a bug where empty partitions would lack the requisite metadata (column names or dtypes), which caused problems with subsequent operations.

### CODE REVIEW

**Comment by mrocklin** [comment]
Nice.  Do you happen to have benchmark numbers for an on-disk groupby?

**Comment by jcrist** [comment]
Here's one for just the shuffle. Admittedly the bottleneck isn't the hash, but you can still see the performance difference.

**Master:**

```python
In [1]: import dask.dataframe as dd

In [2]: df = dd.demo.make_timeseries('2000', '2010', {'value': float, 'id': int}, freq='10s', partition_freq='365D', seed=1)

In [3]: len(df)
Out[3]: 31536000

In [4]: s = dd.shuffle.shuffle(df, df.id)

In [5]: %time _ = s.compute()
CPU times: user 44.4 s, sys: 7.23 s, total: 51.6 s
Wall time: 43.2 s
```

**This PR:**

```python
In [1]: import dask.dataframe as dd

In [2]: df = dd.demo.make_timeseries('2000', '2010', {'value': float, 'id': int}, freq='10s', partition_freq='365D', seed=1)

In [3]: len(df)
Out[3]: 31536000

In [4]: s = dd.shuffle.shuffle(df, df.id)

In [5]: %time _ = s.compute()
CPU times: user 30.2 s, sys: 2.84 s, total: 33.1 s
Wall time: 27.1 s
```

**Comment by mrocklin** [comment]
Awesome

**Comment by mrocklin** [comment]
This all seems sensible to me.  +1

**Pull request merged**
