### PR TITLE
Switch default object encoding to utf8

### PR DESCRIPTION
**Pull request by mrocklin**
This may be a more common default than bytes

Thoughts on this choice @martindurant ?

### CODE REVIEW

**Comment by martindurant** [comment]
My thinking was to use the more basic type, which requires the least processing - if the user wants to use utf8, they should realise that it's an extra.

**Comment by mrocklin** [comment]
The argument for utf-8 would be that this sort of data probably more often represents text than binary data and that utf-8 is the defacto representation of text.  I suspect it is also the standard used by other parquet reader/writers.

**Comment by martindurant** [comment]
Naturally, there is no parquet standard: in systems like impala, drill, spark, you create a schema where text and bytes types are separate, so there is no confusion. When those systems import from something text-like (csv, json), I suspect you need to specify the text encoding, and the default may well be ascii (i.e., bytes). I cannot find information on how this is done in 3 minutes of googling.

**Comment by mrocklin** [comment]
If we're dealing with text then there are some good reasons to use utf-8 over ASCII

*  Support for non-american-english text
*  Python 3 standard

However, I'm unfamiliar with the performance implications here.  I hope that this isn't too much more costly.  I also note that fastparquet appears to use utf8 as a default for str objects, so this would align dask.dataframe's default handling with fastparquet.

**Comment by martindurant** [comment]
In fastparquet, object_encoding=None (or {}, or {col: enc} where the column of interest is not included) results in assuming bytes. 
If passing 'infer', the new current default, then yes, strings will result in utf8, bytes in bytes. The conversion is a list comprehension, so slow for a lot of values compared to (say) reading/writing a fixed-length bytes array. If it's category labels, it won't matter from a performance point of view.

**Comment by mrocklin** [comment]
Can you provide some rough numbers around relative costs between

- object_encoding='utf8'
- object_encoding='bytes'
- fixed_text= ... with utf8
- fixed_text= ... with bytes

**Comment by martindurant** [comment]
Using current master.
Column `a` is strings, column `b` in bytes, max 6 char long, all characters are actually ascii.
```
%time fastparquet.write('temp.parq', df[['a']], write_index=False, has_nulls=False, object_encoding='utf8')
Wall time: 869 ms
%time out = pf.to_pandas()
Wall time: 730 ms

%time fastparquet.write('temp.parq', df[['a']], write_index=False, has_nulls=False, object_encoding='utf8', fixed_text={'a': 6})
Wall time: 527 ms
%time out = pf.to_pandas()
Wall time: 333 ms

%time fastparquet.write('temp.parq', df[['b']], write_index=False, has_nulls=False, object_encoding='bytes')
Wall time: 471 ms
%time out = pf.to_pandas()
Wall time: 451 ms

%time fastparquet.write('temp.parq', df[['b']], write_index=False, has_nulls=False, object_encoding='bytes', fixed_text={'b': 6})
Wall time: 88.1 ms
%time out = pf.to_pandas()
Wall time: 61.6 ms
```

**Comment by mrocklin** [comment]
cc @seibert thoughts on prioritizing numba string handling?  Performance hits here are somewhat painful.

**Comment by mrocklin** [comment]
Or, perhaps more openly, are there performance gains to be made here and if so what are the development costs?  Dask data ingestion would find improved performance on python string objects very useful.

**Comment by pitrou** [comment]
I don't know how fastparquet is architected (does it use C or Cython code?), but Python 3 has a very fast utf8 decoder internally. If some pure Python path is being hit here, perhaps there's a way to avoid it...

**Comment by martindurant** [comment]
I don't have much of an idea of how to make string handling faster. Tight looping within numba would certainly be a help (create a python bytes or str object from bytes with possibly decoding). Apparently, cython can do this by calling directly into the cpython api.

**Comment by mrocklin** [comment]
@pitrou fastparquet is Python + Numba.  No Cython or C as far as I'm aware.

**Comment by martindurant** [comment]
Correct, no cython or C

**Comment by mrocklin** [comment]
@martindurant is it easy for you to produce a small test case that is representative of workloads here and could also be used for benchmarking by numba devs?

**Comment by pitrou** [comment]
@martindurant, how many entries (rows or cells) are there in your benchmark's dataframe? I'm trying to get an idea of the order of magnitude we are talking about here.

**Comment by martindurant** [comment]
I threw the timings into here https://github.com/dask/fastparquet/commit/3faf36d2ead21ef3c1145383784f8a5b196e5694
They come out slightly slower than above, but same trend. This is for 1M items.
```
bytes: read, fixed: 6 58.882
bytes: read, fixed: None 512.981
bytes: write, fixed: 6 133.439
bytes: write, fixed: None 559.238
str: read, fixed: 6 363.559
str: read, fixed: None 813.009
str: write, fixed: 6 624.31
str: write, fixed: None 1005.485
```

**Comment by mrocklin** [comment]
Can you isolate the performance hit to a particular numba-on-numpy-array operation?

**Comment by pitrou** [comment]
So I guess the main difference between `bytes` and `utf8` is calling `data.str.encode('utf8')`?

**Comment by martindurant** [comment]
Decoding:
`out[:] = [s.decode('utf8') for s in data]`
Reading non-fixed:
`np.array([file_obj.read(struct.unpack('<i', file_obj.read(4))[0])
                     for _ in range(count)], dtype="O")`
Reading fixed:
`np.frombuffer(memoryview(raw_bytes), dtype='S6', count=count)`

The point is that this does **not** involve numba, which can't handle object arrays. It also can't handle file objects, but I have a file object-like class embedding a uint8 (bytes) numpy array to perform the same job.

**Comment by pitrou** [comment]
I was asking about writing, not reading.

**Comment by martindurant** [comment]
Yes, encoding during write looks like this:
`data.str.encode('utf8').values`
and this code path is avoided for data that is already bytes.

**Comment by pitrou** [comment]
Easy speedup on Python 3:
```
>>> %timeit data.str.encode('utf8')
10 loops, best of 3: 41.9 ms per loop
>>> %timeit data.map(str.encode)
10 loops, best of 3: 23 ms per loop
```

Similar hack for Python 2:
```
>>> %timeit data.str.encode('utf8')
10 loops, best of 3: 70 ms per loop
>>> import codecs
>>> enc = lambda x, _enc=codecs.utf_8_encode: _enc(x)[0]
>>> %timeit data.map(enc)
10 loops, best of 3: 30.5 ms per loop
```

**Comment by martindurant** [comment]
Interesting.
`[x.encode('utf8') for x in data]` is as fast - that's the style I use in decoding on read.

**Comment by martindurant** [comment]
Gives new times
```
utf8: write, fixed: 6 270.079
utf8: write, fixed: None 666.602
```
Thanks, @pitrou , this helps.

**Comment by pitrou** [comment]
If you want to throw in some Cython to try extracting more speed, you may start by copying Pandas' `map_infer()` function which powers the `map()` and `.str.XXX` methods internally:
https://github.com/pandas-dev/pandas/blob/master/pandas/src/inference.pyx#L1214-L1250

Instead of taking a Python callable `f`, you'd directly call the C API function for encoding `PyUnicode_AsUTF8String` (doc at https://docs.python.org/3/c-api/unicode.html#c.PyUnicode_AsUTF8String). Hopefully that would shave a bit more runtime off by avoiding some indirections and argument parsing.

**Comment by pitrou** [comment]
I wonder if Pandas would be interested in such an optimization of mass encoding and decoding. @jreback ?

**Comment by mrocklin** [comment]
@martindurant I'm still tempted to merge this.  I think that, performance issues aside, saving objects as text is likely the least surprising option.

**Comment by pitrou** [comment]
See https://github.com/dask/fastparquet/pull/62 for performance improvements.

**Comment by mrocklin** [comment]
@martindurant ok to merge after tests pass?

**Comment by mrocklin** [comment]
Merging soon if no further comment

**Pull request merged**
