### PR TITLE
editing doc string in to_textfiles

### PR DESCRIPTION
**Pull request by jslmann**
it was noticed that rendered html docs were incorrectly formatted due to missing spaces around double back-quotes - so spaces were inserted. Also, incorrect mark-up was used around the word 'must' so that was simply removed.

### CODE REVIEW

**Comment by mrocklin** [comment]
Looks like this needs to be rebased on the master branch of the main fork

**Comment by mrocklin** [comment]
To be clear, I would resolve this as follows:

cd dask
git checkout -b backup  # create new git branch with this fix, makes a copy of current master branch
git checkout master  # switch back, we're about to blow this away
git remote add dask git@github.com:dask/dask.git  # you probably already have this as origin or something, but I'm being explicit here
git remote update dask
git reset --hard dask/master  # kill everything in your current master branch and hard set it to be what's in the master branch on the main dask fork
```

OK, now you're in a clean git state with a commit lying around that you'd like to put into a development branch and push up to github.  What happens from here on out is normal git development process:

```python
git checkout -b fix-typo-textfiles

git cherry-pick 	1d927d7  # grab your latest commit from the other branch
or 
Just redo your original edit

git commit -a 
git push your-fork-name fix-typo-textfiles
```


General advice is to never ever commit to your own master branch.  Keep this branch clean and only pull from dask/master.  Make all edits in other branches.
git

**Comment by jslmann** [comment]
just a heads up that I can't touch this today (I believe) but am appreciating the assistance very much..

**Comment by mrocklin** [comment]
I have squashed and merged this separately.  Closing this branch. 

Your current master branch now has invalid commits in it.  Before you do any further work I recommend that you blow these away and reset hard to the master fork

    git remote update dask
    git reset --hard dask/master

and that in the future you always perform work in a separate branch to avoid these issues

**Comment by jslmann** [comment]
arg. my apologies, Matthew. I've been reading up on git etc. In an attempt
to not screw up in the future but apparently took too long.
I could have executed the commands you gave, but there were subtle hics and
I wanted to understand what was really happening.

On another note I, very much enjoyed your talk from SciPy 2014. I am,
unfortunately, not a coveted specialist but I do see wide application for
your ideas.

thanks again for your help, hopefully I can make better contributions in
the future,

Joe

**Comment by mrocklin** [comment]
No worries.  Happy to help out.

**Pull request closed without merging**
