### PR TITLE
Always call abspath in LocalFilesystem

### LINKED ISSUE #2256: Use absolute paths in read_* functions
In a distributed context the workers may have different working directories than the client.  In this case relative paths may be confusing.  Should we consider converting all paths on the posix file systems to absolute paths?

### PR DESCRIPTION
**Pull request by martindurant**
Fixes #2256

### CODE REVIEW

**Comment by mrocklin** [comment]
I think that this lacks only a flake8 fix

**Comment by mrocklin** [comment]
I had some issues when I tried this out.

```python
In [1]: import pandas as pd

In [2]: df = pd.DataFrame({'x': [True, False]})

In [3]: df.to_csv('foo.csv')  # write to local directory

In [4]: import dask.dataframe as dd

In [5]: ddf = dd.read_csv('foo.csv')

In [6]: list(ddf.dask.values())[0][1].path  # should this be an absolute path?
Out[6]: 'foo.csv'

In [7]: from dask.distributed import Client

In [8]: client = Client('localhost:8786')  # workers are not in this directory, but are on this machine

In [9]: ddf.compute()
FileNotFoundError: [Errno 2] No such file or directory: 'foo.csv'
```

**Comment by martindurant** [comment]
Hm. My change (which is probably a good idea nonetheless) only seems to affect glob paths. Not sure where to put in an abspath otherwise (bytes.core.get_fs_paths_myopen passes through paths without asking the file-system anything). 
Would it be reasonable to store the working directory in the LocalFileSystem on instantiation, and use it for any paths that don't look absolute?

**Comment by mrocklin** [comment]
Ah, indeed that works well

```python
In [10]: ddf = dd.read_csv('foo*.csv')

In [11]: list(ddf.dask.values())[0][1].path
Out[11]: '/home/mrocklin/workspace/dask/foo.csv'

In [12]: ddf.compute()
Out[12]: 
   Unnamed: 0      x
0           0   True
1           1  False
```

**Comment by mrocklin** [comment]
> Would it be reasonable to store the working directory in the LocalFileSystem on instantiation, and use it for any paths that don't look absolute?

Maybe?  Honestly I think you probably have a better grasp on this problem and this system than I do.

**Comment by mrocklin** [comment]
Is this good to go?

**Comment by martindurant** [comment]
Good to go - was waiting for tests to finish.

**Pull request merged**
