### PR TITLE
WIP: Lazy compress

### PR DESCRIPTION
**Pull request by jakirkham**
(Tries to) fix https://github.com/dask/dask/issues/2540

Attempts to implement Dask Array's [`compress`]( http://dask.pydata.org/en/latest/array-api.html#dask.array.compress ) in a lazy manner. Does this by making used of [`delayed`]( http://dask.pydata.org/en/latest/delayed-api.html#dask.delayed.delayed ) to wrap up applications of slices to the Dask Array being `compress`ed. Also makes use of `np.nan` to describe the length of dimension that was `compress`ed. This seems to sort of work.

That said, there are definitely some rough edges. First as `delayed` returns one big chunk and we are not breaking up array chunks before slicing them. Ideally each chunk would be passed through these `delayed` calls and reconstructed on the other end. That way chunking could largely be preserved through `compress`. It's unclear to me that what the cleanest and simplest way to do this is ATM. My best thinking would be slicing the array into pieces after inspecting its chunk sizes and trying to reassemble it afterwards, but that is hardly clean and not really simple AFAICT. Second the tests appear to be failing locally. However this failure doesn't have anything to do with the accuracy of the resulting Dask Array, but instead is due to some property of the graph isn't being maintained. Looking at the error it is not clear to me where this implementation caused it. So the problem may be somewhere deeper in Dask.

ATM I'm not sure that I will be able to solve these problems due to lack of time and/or lack of understanding.

### CODE REVIEW

**Comment by mrocklin** [comment]
Yes, we definitely don't want to send the entire array into a delayed function call.  This will instantiate the full array, then call the function on it, which is likely to fail if the array is larger than memory.

**Comment by jakirkham** [comment]
Of course, can you please elaborate on how that would be fixed? Other than the quite messy and undesirable approach I've already noted above, I'm not seeing a good way to do this.

**Comment by jakirkham** [comment]
Could PR ( https://github.com/dask/dask/pull/2545 ) please be merged in the interim?

**Comment by jakirkham** [comment]
Closing out in favor of PR ( https://github.com/dask/dask/pull/2555 ). Thanks @jcrist.

**Comment by jakirkham** [comment]
This [Travis CI build]( https://travis-ci.org/dask/dask/builds/257413562 ) can be cancelled. Looks like the AppVeyor build already was.

**Comment by jakirkham** [comment]
Should this be on a milestone given it was closed out?

**Pull request closed without merging**
