### PR TITLE
WIP: NEP-18 Tests

### PR DESCRIPTION
**Pull request by pentschev**
DO NOT MERGE. This is a work in progress to track the status of all known bugs related to NEP-18.

- [ ] Tests added / passed
- [ ] Passes `flake8 dask`

### CODE REVIEW

**Comment by mrocklin** [comment]
cc @shoyer @jakirkham

**Comment by jakirkham** [comment]
@pentschev, am curious what is the status of this PR?

**Comment by pentschev** [comment]
@jakirkham I haven't done much here lately, but the purpose of this PR is actually to track the problems we have identified, in hopes to merge it one, when we have no known issues related to NEP-18. Unfortunately, we haven't merged many NEP-18-related fixes or features yet, so I don't expect to have this PR passing and merged anytime soon.

**Comment by jakirkham** [comment]
Is this more viable with meta in? ( https://github.com/dask/dask/pull/4543 )

**Comment by pentschev** [comment]
Not entirely, it certainly helped, but there are still many failing tests. I will try to see how many of those are still useful (many were added during the `_meta` PR, so there may be some redundancy here), and remove the others or move them elsewhere. There are some tests that even include `dask_glm`, which certainly don't belong in here.

**Comment by gforsyth** [comment]
Hey @pentschev, this has been sitting for a long time so I'm going to close it, but please ping if there are extra NEP-18 tasks to be tackled here.  Thanks!

**Comment by pentschev** [comment]
@gforsyth no worries, I haven't really got a chance to look at this for some time. We can definitely reopen it one day if it still makes sense. Thanks for pinging!

**Pull request closed without merging**
