### PR TITLE
CLN: Remove unused funcs

### PR DESCRIPTION
**Pull request by sinhrks**
Some cleanups for dataframe.

Also, can we remove followings (looks never used  internally / non-public)?

- ``categorical.py``
  - ``_categorize``
  - ``strip_categories``
  - ``get_categories``

- ``core.py``
  - ``remove_empties``
  - ``empty_safe``

### CODE REVIEW

**Comment by mrocklin** [comment]
Everything here seems fine to me.  CC @TomAugspurger who may have more recent experience with categorials in dask.dataframe.

**Comment by mrocklin** [comment]
Looks like `is_categorical_dtype` was used after all

**Comment by sinhrks** [comment]
@mrocklin Correct. Now fixed.

**Comment by mrocklin** [comment]
Merged.  Thanks @sinhrks !

**Pull request merged**
