### PR TITLE
Rename dask.dataframe to dask._dataframe

### PR DESCRIPTION
**Pull request by phofl**
- [ ] Closes #xxxx
- [ ] Tests added / passed
- [ ] Passes `pre-commit run --all-files`

For context: We can't currently import dask-expr from a Cluster, because we run into circular imports since dask-expr imports tons of stuff from dask.dataframe. The only feasible solution that I am aware of is renaming dask.dataframe to dask._dataframe and using this as a source for dask.dataframe and dask-expr.

I split this into 2 PRs, this one will hopelessly break ci, but the follow up pr (#10823) should fix it. Doing it in 2 steps preserves git history. In case we don't care, we can just merge the other PR and ignore this one.

### CODE REVIEW

**Comment by mrocklin** [comment]
> The only feasible solution that I am aware of is renaming dask.dataframe to dask._dataframe and using this as a source for dask.dataframe and dask-expr

This would surprise me.  For example, maybe imports at the bottom, or imports within functions?

**Comment by phofl** [comment]
> This would surprise me. For example, maybe imports at the bottom, or imports within functions?

We import stuff from dask.dataframe *everywhere*, we can't move all of them into functions, that would require a huge effort.

Bottom is also not helpful here, I am open to suggestions but it really is a circular import, I don't think we can avoid this trap without relocating stuff

**Comment by crusaderky** [comment]
Didn't do a thorough review; a few random comments after a first look:
- This feels very painful. Maybe we should spend a minute to brainstorm alternatives.
- I wasn't expecting anything to change in the tests (except at most what pokes at internals)
- I'm seeing a bunch of search/replaces that incorrectly affect docstrings, e.g. are visible in rendered sphinx content.
- `dask.dataframe.backends` seems to be an odd exception where the non-underscore module is not just a bunch of imports. Is it intentional?

**Comment by phofl** [comment]
> I wasn't expecting most tests to move to _dataframe either. Most tests should work for both dd and dx.

Tests don't matter, we can move them back if you prefer

> dask.dataframe.backends seems to be an odd exception where the non-underscore module is not just a bunch of imports. Is it intentional?

that was an accident, not sure how this happened. Is fixed

> This feels very painful. Maybe we should spend a minute to brainstorm alternatives.

I am open to suggestions

> I'm seeing a bunch of search/replaces that incorrectly affect docstrings, e.g. are visible in rendered sphinx content.

sorry for those, already fixed now

**Comment by phofl** [comment]
https://github.com/dask-contrib/dask-expr/issues/706

Here is an issue with a reproducer

**Comment by phofl** [comment]
And here is a CI build where tests are timing out because of this issue:

https://github.com/dask/dask/actions/runs/7558876018/job/20581415206


``test_dataframe_broadcast_merge`` is one example

**Comment by mrocklin** [comment]
Just to be clear, I'm not blocking things here.  I agree with Guido's comment that brainstorming alternatives might be good (although I don't plan to participate in that).  But in general, please don't stall on my account (but maybe do stall on each others')

**Comment by phofl** [comment]
I don't mind alternatives, I am just doubtful that there are any reasonable ones (I would be happy if someone can come up with something). I don't intend to spend much time on this before leaving for PTO, this issue makes dask-expr not really usable with the switch, so someone would need to pick this up after I am away if we don't have a resolution until then

**Pull request closed without merging**
