### PR TITLE
Only run the cron CI on dask/dask not forks

### PR DESCRIPTION
**Pull request by jacobtomlinson**
Limits the upstream checks to not run on forks.

### CODE REVIEW

**Comment by jsignell** [comment]
What is the motivation for this?

**Comment by jacobtomlinson** [comment]
Getting this email every day

image

**Comment by jsignell** [comment]
I guess I am just worried about the non-cron implications. Right now this job runs on every push to a fork which I have found useful in https://github.com/dask/dask/pull/6896 for instance.

**Comment by jacobtomlinson** [comment]
> Right now this job runs on every push to a fork

Ah that's a really good point and an oversight on my part.

The functionality of the check ported over from Travis was for it to run on:
- All dask/dask branches
- dask/dask master at night 
- Any PR with `test-upstream` in the first commit message

I've updated the `if` statement to reflect that.

**Comment by jsignell** [comment]
> Although it doesn't look like this was run on #6896?

It ran on the branch on my fork.

Thanks for the update! This is perfect now :)

**Pull request merged**
