### PR TITLE
Update toolz version requirement (>=0.7.2 to >=0.7.3)

### PR DESCRIPTION
**Pull request by brianmartin**
With toolz 0.7.2, `import dask.bag` fails.

```
$ pip freeze | grep toolz
toolz==0.7.2
$ python -c 'from toolz import peek'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'peek'
$ pip install toolz==0.8.2
...
$ pip freeze | grep toolz
toolz==0.8.2
$ python -c 'from toolz import peek'
```

### CODE REVIEW

**Comment by mrocklin** [comment]
Was `peek` first introduced in 0.8.2?  cc @eriknw

**Comment by mrocklin** [comment]
Also thank you very much for identifying the error, and for providing a fix.

**Comment by brianmartin** [comment]
For sure! Was pretty light on the investigation here, so there may be a lower compatible version.

We're ramping up our production usage of Dask here at Opendoor and are looking forward to contributing more going forward.

**Comment by mrocklin** [comment]
Ah, I appreciated the shoutout in the recent article about your stack that made it to Hacker News.  

I hope to see more of you all around here :)

**Comment by mrocklin** [comment]
Thank you @brianmartin .  Merging

**Pull request merged**
