### PR TITLE
Reusing code for assert_eq util method #5495

### LINKED ISSUE #5495: Reusing code in /dask/dask/array/utils.py
I was looking at issue https://github.com/dask/dask/issues/2682 and saw an opportunity to reuse code in this [Array util's assert_eq method](https://github.com/dask/dask/blob/7b4f90f0a708cbb97ebb498c78f7931d82ec99db/dask/array/utils.py#L196-L279).

We can move the logic for computing dt, meta and computed value to a separate method and reuse that for both params `a` and `b`.

### PR DESCRIPTION
**Pull request by VijayantSoni**
- [ ] Tests added / passed
- [ ] Passes `black dask` / `flake8 dask`

closes #5495

### CODE REVIEW

**Comment by quasiben** [comment]
Thanks @VijayantSoni the appveyor is currently failing here:
```
================================== FAILURES ===================================
_____________________ test_zarr_in_memory_distributed_err _____________________
loop = <tornado.platform.asyncio.AsyncIOLoop object at 0x0000008982A599B0>
    def test_zarr_in_memory_distributed_err(loop):
        da = pytest.importorskip("dask.array")
        zarr = pytest.importorskip("zarr")
        with cluster() as (s, [a, b]):
            with Client(
>               s["address"], loop=loop, client_kwargs={"set_as_default": True}
            ) as c:
dask\tests\test_distributed.py:194: 
```

I don't think this is related but could you take a look specifically at that test ?

**Comment by mrocklin** [comment]
Thank you for the cleanup PR @VijayantSoni .  In general this change looks good to me.

> I don't think this is related but could you take a look specifically at that test ?

Indeed, this is unrelated.  I've resolved it (and a couple of other things) in https://github.com/dask/dask/pull/5497

**Comment by VijayantSoni** [comment]
Thanks @quasiben and @mrocklin for reviewing. Should I wait for #5497 to get merged and then merge master into my feature branch or we can merge this independently ?
Also, please let me if there is anything else that I need to take care of.

**Comment by mrocklin** [comment]
I suspect that you can just restart the tests.  I doubt that merging
manually or rebasing is necessary.

**Comment by mrocklin** [comment]
(to be clear, the "you" above is @quasiben, I don't think that there is
anything more that @VijayantSoni <https://github.com/VijayantSoni> likely
needs to do)

**Comment by quasiben** [comment]
All green now.  Thanks @VijayantSoni !

**Comment by VijayantSoni** [comment]
Thank you guys, @mrocklin @quasiben .

**Pull request merged**
