### PR TITLE
Fix skiprows with multiple blocks

### LINKED ISSUE #2065: skiprows makes Dask skip rows in each partition
```python
import dask.dataframe as dd
import dask

print(dask.__version__)
# 0.14.0

d = dd.read_csv('data.txt', skiprows=1000, dtype=str)
print(d.npartitions)
# 6
print(d.compute().shape[0])
# 2644307
```
```sh
$ wc -l data.txt
2650308 data.txt
```

Apparently, Dask passes `skiprows` to each call of `pandas.read_csv`, whereas when reading a single file it should pass it only to the call that reads the first partition.

### PR DESCRIPTION
**Pull request by p-himik**
fixes #2065

### CODE REVIEW

**Comment by mrocklin** [comment]
Generally this looks pretty good to me.  Two comments/questions:

1.  I would be slightly more comfortable with an integrative test that used `dd.read_csv`.  The internal API may shift around a little bit, and I'd be happier testing the full user experience than the behavior of internal functions.  I would look for tests that use `filetexts`
2.  Are there other parameters like skiprows that we should also exclude from `rest_kwargs`?

**Comment by p-himik** [comment]
1. Ahh, right. Will fix.
2. Maybe, but I don't think that they're in the scope of this pull request and corresponding issue.

**Comment by mrocklin** [comment]
This looks good to me.  It looks like there is an unrelated failure from recent work.  

cc @jcrist can you take a look at https://travis-ci.org/dask/dask/jobs/218559738

```
=================================== FAILURES ===================================
________________________________ test_interrupt ________________________________
[gw1] linux -- Python 3.6.1 /home/travis/miniconda/envs/test-environment/bin/python
@pytest.mark.slow
    def test_interrupt():
        try:
            proc = subprocess.Popen([sys.executable, '-c', code],
                                    stdout=subprocess.PIPE,
                                    stderr=subprocess.PIPE)
            # Wait for scheduler to start
            msg = proc.stdout.readline()
            if msg != 'started\n' and proc.poll() is not None:
                assert False, "subprocess failed"
            # Scheduler has started, send an interrupt
            sigint = signal.CTRL_C_EVENT if os.name == 'nt' else signal.SIGINT
            try:
                proc.send_signal(sigint)
                # Wait a bit for it to die
                start = time()
                while time() - start < 0.5:
                    if proc.poll() is not None:
                        break
                    sleep(0.05)
                else:
>                   assert False, "KeyboardInterrupt Failed"
E                   AssertionError: KeyboardInterrupt Failed
E                   assert False
dask/tests/test_threaded.py:155: AssertionError
======= 1 failed, 2412 passed, 11 skipped, 14 xfailed in 307.35 seconds ========
```

**Comment by jcrist** [comment]
Looks like it's just an issue of the wait timeout being too short for travis (which can be slower than a local machine). Just increasing the timeout from `0.5` to `1` should fix it.

**Comment by mrocklin** [comment]
Thanks for the fix @p-himik !  Merging

**Pull request merged**
