### PR TITLE
Temporarily exclude nightly `pyarrow` from `upstream` CI build

### PR DESCRIPTION
**Pull request by jrbourbeau**
This is a temporary workaround for https://github.com/dask/dask/issues/9449 

cc @ncclementi @jorisvandenbossche

### CODE REVIEW

**Comment by ncclementi** [comment]
@jrbourbeau this seems a good patch until we can sort things out. 

I wonder if we know someone besides Joris that we can ping about pyarrow. Would someone like John know about this?

**Comment by jrbourbeau** [comment]
Good question. @jakirkham not sure if you have any thoughts about what might be going on here?

**Comment by jakirkham** [comment]
Sorry I'm not really familiar with these nightlies. Maybe @kkraus14 would know or perhaps know who to ask 🙂

**Comment by kkraus14** [comment]
> Sorry I'm not really familiar with these nightlies. Maybe @kkraus14 would know or perhaps know who to ask 🙂

Right now Arrow is caught up in a bit of a mess related to trying to handle ABI differences between C++ versions with Abseil. Unfortunately, not quite a line of sight on resolving it or an ETA quite yet ☹️.

**Comment by ncclementi** [comment]
@kkraus14 would you mind linking the PR/issues where these discussions are happening so we have them for reference? That way when they are "resolved" we can give the nightlies another try.

**Comment by jorisvandenbossche** [comment]
Testing locally with the environment-3.9.yaml file that is used for setting up this env on CI, I got it working to install pyarrow if pinning libprotobuf to a previous version (which triggers abseil-cpp, glog, grpc, libgoogle-cloud, libthirft, orc and re2 to also use an older version, but so no user facing python dependency is affected. Maybe I could also have pinned another library, but libprotobuf 3.20 was the one that mamba pointed to as the problem when trying to install the nightly arrow-cpp). 
Testing if this also would work on CI in https://github.com/dask/dask/pull/9465

**Comment by jrbourbeau** [comment]
Thanks @jakirkham @kkraus14 @jorisvandenbossche -- closing this PR in favor of https://github.com/dask/dask/pull/9465

**Pull request closed without merging**
