### PR TITLE
Add amin/amax aliases to min/max in dask array

### LINKED ISSUE #5031: dask array failing with numpy 1.17.0rc1 and np.min
Using Python 3.7, dask 2.0, (from conda-forge) and NumPy 1.17.0rc1 (from pip):

```python
import numpy as np
import dask.array as da

image = da.from_array(np.array([[0, 1], [1, 2]]), chunks=(1, 2))
image_min = int(np.min(image))
```

results in:

```pytb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<__array_function__ internals>", line 6, in amin
TypeError: no implementation found for 'numpy.amin' on types that implement __array_function__: [<class 'dask.array.core.Array'>]
```

### PR DESCRIPTION
**Pull request by mrocklin**
Fixes #5031

### CODE REVIEW

**Comment by pentschev** [comment]
Thanks @mrocklin, was going to suggest the same thing.

**Comment by shoyer** [comment]
I would add an alias for `dask.array.round_`, too. It will have the same issue, as noted in https://github.com/numpy/numpy/issues/13877.

**Comment by rgommers** [comment]
This is the easiest fix, but I don't think it's the right one. Using the dict approach as discussed in gh-5031 is much nicer, solves the issue too and does not pollute the `dask.array` namespace with aliases that you don't really want.

**Comment by mrocklin** [comment]
Any interest in submitting an alternative @rgommers ?

**Comment by rgommers** [comment]
Let me give it a try tonight. If anyone else was working on it already, please comment.

**Comment by rgommers** [comment]
> Any interest in submitting an alternative @rgommers ?

Okay first cut in gh-5043.

**Comment by shoyer** [comment]
I would lean towards submitting this first, even if we also go for @rgommers's approach, too (which will be a bit more involved).

**Comment by rgommers** [comment]
> I would lean towards submitting this first, even if we also go for @rgommers's approach, too (which will be a bit more involved).

That's only helpful for skimage in case you stick this in a release right? And at that point you can't remove it easily anymore. Why not just make a decision? - my PR probably takes half a day to finish up.

**Comment by mrocklin** [comment]
I'm happy to defer to folks like @shoyer and @pentschev here on which to choose.  I'll admit a very slight preference for the solution here, just for the sake of simplicity.

**Comment by rgommers** [comment]
@mrocklin note that this doesn't actually fix all the problems, e.g. `np.median(dask_array)` still goes from working fine with numpy 1.16 to raising an uninformative `TypeError` with 1.17. 

I agree it's simpler, and if it was just about extra namespace aliases then that's a taste thing. But `Array.__array_function__` needs a tweak either way.

Also, if you do decide to merge this, the regression tests in gh-5043 would be good to take over here.

**Comment by pentschev** [comment]
I have no major objections either way. The only concern I have is with array creation https://github.com/dask/dask/pull/5043/files#diff-0dc21516366e88095fc3dbf2e9e62f9aR4584. As far as I understand, this would prevent dispatching to libraries like CuPy.

**Comment by rgommers** [comment]
> The only concern I have is with array creation https://github.com/dask/dask/pull/5043/files#diff-0dc21516366e88095fc3dbf2e9e62f9aR4584. As far as I understand, this would prevent dispatching to libraries like CuPy.

I'll move that comment to that actual line. I don't think it's an issue, but let's discuss there.

**Pull request closed without merging**
