### PR TITLE
Allow `array.chunksize` property to handle uneven chunking

### PR DESCRIPTION
**Pull request by d-v-b**
At present, the `chunksize` property of a dask array only displays a single value per axis, even for  arrays with irregular chunking (i.e., multiple chunk sizes). For arrays with irregular chunking, the `chunksize` property can be a source of confusion, as in this example where the existence of single chunks is elided by the `chunksize` property:

```python
import dask.array as da
a = da.zeros((10,10), chunks=((9,1),(9,1)))
print(a)
# prints dask.array<zeros, shape=(10, 10), dtype=float64, chunksize=(9, 9), chunktype=numpy.ndarray>
```

The current behavior of the `chunksize` property is to report the maximum chunksize per axis. In this PR, the `chunksize` property reports the set of all chunksizes per axis: 

```python
import dask.array as da;
a = da.zeros((10,10), chunks=((9,1),(9,1))); print(a)
# prints dask.array<zeros, shape=(10, 10), dtype=float64, chunksize=((1, 9), (1, 9)), chunktype=numpy.ndarray>
```

This has the advantage of giving a more accurate summary of the chunking of the array, but there is a disadvantage: in this PR, `chunksize` becomes a tuple of tuples, many of which will likely be singletons, e.g. `((1 ,) (1,))` , which (to me) is uglier than `(1, 1)`.

So it's not a strict improvement, but in my view the reduced likelihood of confusion about chunking is worth the pain of the ugly nested tuples. 

- [x] Tests added / passed
- [x] Passes `black dask` / `flake8 dask`

### CODE REVIEW

**Comment by TomAugspurger** [comment]
I'm not sure about this change. I'd prefer to properly document `chunksize`, and direct users to `chunks` if they need more details.

**Comment by d-v-b** [comment]
Is the problem that the nested tuples are super ugly, or is there a specific reason why `chunksize` should only report the largest chunksize?

**Comment by TomAugspurger** [comment]
There's backwards compatibility, which I'm hesitant to break without a compelling reason.

Worth hearing from others though.

**Comment by mrocklin** [comment]
I'm also against this change, and in favor of documentation if necessary.
The list of possible sizes in each chunk can grow very large, and isn't
something that I think we should endeavor to communicate in text in a repr.

**Comment by d-v-b** [comment]
Those arguments all make sense to me! I'm happy to close if this PR definitely going nowhere, and if you point me to the relevant documentation I can open a separate PR to update that info. 

That being said, I think people will still find it odd/confusing that the `chunksize` property is an inaccurate representation of the actual chunksizes in an array, even if this is fully documented.

As for arrays with a lot of chunksizes, it would be possible to prettify the repr while preserving the accuracy of the `chunksize` property: 
```python
import dask.array as da;
a = da.zeros((10,10), chunks=((1,2,3,4,5),(9,1)))
print(a)
# prints dask.array<zeros, shape=(10, 10), dtype=float64, chunksize=((1, 2, 3...), (1, 9)), chunktype=numpy.ndarray>
print(a.chunksize)
# prints ((1, 2, 3, 4, 5), (1, 9))
```

**Comment by TomAugspurger** [comment]
For docs, adding an API entry for Array.chunksize at
https://docs.dask.org/en/latest/array-api.html and a bit of
prose text in https://docs.dask.org/en/latest/array-chunks.html makes the
most sense.

**Comment by mrocklin** [comment]
Closing this for now.  Thanks @d-v-b !

**Pull request closed without merging**
