### PR TITLE
Add block_info keyword to map_blocks functions

### PR DESCRIPTION
**Pull request by mrocklin**
Fixes https://github.com/dask/dask/issues/3683

Your block function get information about where it is in the array by
accepting a special ``block_info`` keyword argument.

```python
>>> def func(block, block_info=None):
...     pass
```

This will receive the following information:

```python
>>> block_info
{0: {'shape': (1000,),
     'num-chunks': (10,),
     'chunk-location': (4,),
     'array-location': [(400, 500)]}}
```

For each argument and keyword arguments that are dask arrays (the positions
of which are the first index), you will receive the shape of the full
array, the number of chunks of the full array in each dimension, the chunk
location (for example the fourth chunk over in the first dimension), and
the array location (for example the slice corresponding to ``40:50``).

- [ ] Tests added / passed
- [ ] Passes `flake8 dask`

cc @stuartarchibald

### CODE REVIEW

**Comment by martindurant** [comment]
In connection to this, I think `array.get_chunk` would be useful, taking a tuple like `'chunk-location'` and returning the data (or delayed version thereof) of the one chunk. Intake would like this for chunk-wise streaming array data from server to client.

**Comment by stuartarchibald** [comment]
Thanks for this @mrocklin, really useful. Perhaps it'd also be good to have the shape of the chunk domain? I've been passing that into the block mapping functions, it's just `[len(x) for x in arr.chunks]`. This is so it is possible to branch in the mapped function based on where the blocks exist in the chunk space (as this has a correlation to array space) and allows for detection of whether the chunk is on a "far" edge etc.

**Comment by mrocklin** [comment]
I think that you're looking for block_info['num-chunks']

**Comment by stuartarchibald** [comment]
ah, thanks. I erroneously decided `num-chunks` would be the total number of chunks :) I think that is a good start and as it's a `dict` more things can be trivially added as needed.

Is `'chunk-location'` the same as what arrives in kwarg `block_id` ?

**Comment by mrocklin** [comment]
Yes

**Pull request merged**
