### PR TITLE
Refactor: for loop -> list comprehension

### PR DESCRIPTION
**Pull request by marload**
- [x] Tests added / passed
- [x] Passes `black dask` / `flake8 dask`

I made `for loop` simply using list comprehension.

Thank You!

### CODE REVIEW

**Comment by quasiben** [comment]
@marload did something motivate this change or is this a style update ?

**Comment by marload** [comment]
> @marload did something motivate this change or is this a style update ?

This change is just style change!

**Comment by jakirkham** [comment]
Would you be able to benchmark the change before and after?

**Review by derrix060 — APPROVED** [review]

**Comment by jcrist** [comment]
Closing as stale.

**Pull request closed without merging**
