### PR TITLE
Use repeat to build nearest boundary

### PR DESCRIPTION
**Pull request by j2bbayle**
The current implementation of `map_overlap` with `boundary='nearest'` uses dark.array.overlap.nearest, which copies the first and last elements of the array, concatenate them, and then finally concatenate the array and the repeated first and last elements.

This works well, but produces unreadable visualizations. As an example, here's what one obtain for the following simple example.

```python
import dask.array as da

x = da.arange(50)
y = x.map_overlap(lambda x: x + 1, depth=20, boundary='nearest')

y.visualize(optimize_graph=False)
```

69a8dde3-8f08-401a-a0d7-824f931bd62d

In this pull request, I replace the element copy/concatenate steps by a call to `da.repeat`. It's probably very similar in terms of performance (though I haven't tested that), but produces much cleaner graphs. Here it is for the previous example.

9f55d512-0e9f-4fae-b273-eacbd399af17

- [X] Tests passed
- [X] Passes `pre-commit run --all-files`

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

Admins can comment `ok to test` to allow this one PR to run or `add to allowlist` to allow all future PRs from the same author to run.

**Comment by ncclementi** [comment]
add to allowlist

**Comment by j2bbayle** [comment]
Any news on this?

**Comment by mrocklin** [comment]
Sorry for the lack of review here @j2bbayle .  cc'ing @dask/array this looks like a pretty PR to review.  @jakirkham perhaps you have a few minutes?

**Comment by j2bbayle** [comment]
This is almost a year old, and that's a very small change in the code base (but a nice "free" optimization).

**Comment by j2bbayle** [comment]
Anyone?

**Comment by j2bbayle** [comment]
@fjetter maybe?

**Review by fjetter — APPROVED** [review]
Sincere apologies for letting this sit for so long.

This is indeed a much better version and it may even make a big impact on performance for large scale arrays. 

Enabling optimization shows the impact quite nicely

Before

image


After

image

The new version can properly make use of fusion such that the graph collapses nicely.

We've actually recently been hunting for things like this. Improper expressions that blow up the graph/topologies unnecessarily so this is a big help! Again, sorry for ignoring this for so long.

cc @phofl

**Pull request merged**
