### PR TITLE
Added link to meeting calendar.

### PR DESCRIPTION
**Pull request by TomAugspurger**

### CODE REVIEW

**Comment by mrocklin** [comment]
cc @jakirkham

**Comment by jakirkham** [comment]
Ah ok. So today was a one off adjustment. Good to know.

Also change looks good. Thanks for adding the note.

On a different point, how are we tracking meeting notes? I know I got today's, but where do we keep them for posterity?

**Comment by mrocklin** [comment]
That document has notes for all of time.  I believe that there is a link to the document in this same doc page.

**Comment by jakirkham** [comment]
Yep, the doc is linked and the history is there. Sorry, missed them before. Have subscribed to the calendar too.

**Comment by jakirkham** [comment]
Don't want to overstep, but is this ok to merge?

**Comment by mrocklin** [comment]
Not sure that this is overstepping :)

**Comment by jakirkham** [comment]
Ok, merged. Thanks all. :)

**Pull request merged**
