### PR TITLE
Bump Bokeh min version to 2.1.1

### PR DESCRIPTION
**Pull request by bryevdv**
- [ ] Closes #xxxx
- [x] Tests added / passed
- [x] Passes `pre-commit run --all-files`

xref: https://github.com/dask/distributed/pull/5548

cc @jrbourbeau 

I am not sure if the same update in `distributed` in linked PR is wanted/warranted here, but in case it is, this PR also updates the Bokeh min version to 2.1.1. to match, and deletes old version-check codes.

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by jrbourbeau** [comment]
add to allowlist

**Comment by bryevdv** [comment]
Apologies, I didn't realize the hooks don't run automatically like they do in `distributed`. Will push fixes presently.

**Comment by bryevdv** [comment]
@jrbourbeau not really sure about these `test_ops_blocksize` failures. I guess my local checkouts (here and the other PR) might be a bit out of date. Do you think pulling `main` and rebasing would help?

**Review by jrbourbeau — COMMENTED** [review]
Thanks @bryevdv! This looks great 

> Do you think pulling main and rebasing would help?

Yeah, sorry about those unrelated `test_ops_blocksize` failures. They've already been fixed in `main`, so pulling in those changes should fix those failures. FWIW we also squash and merge all PRs, so no need to rebase unless that's your preference.

**Comment by bryevdv** [comment]
rebased on latest `main`

**Comment by jrbourbeau** [comment]
Hrm I've not seen those sporadic test collection errors before. @jsignell have you run across those before?

The `RuntimeError: There is no current event loop in thread 'Dummy-1'` seems like it may be related to https://github.com/dask/distributed/pull/5531. @jcrist any thoughts on what may be happening?

**Comment by jrbourbeau** [comment]
Just ran into the same test collection errors over in https://github.com/dask/dask/pull/8436 (see [this CI build](https://github.com/dask/dask/runs/4412011497?check_suite_focus=true)). These are clearly unrelated to the changes here, so I'll merge this in an open an ticket to track the collection issue

**Review by jrbourbeau — APPROVED** [review]
Thanks @bryevdv!

**Pull request merged**
