### PR TITLE
Daskarray convolution

### PR DESCRIPTION
**Pull request by anlavandier**
- [X] Tests added / passed
- [X] Passes `black dask` / `flake8 dask` / `isort dask`

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by jsignell** [comment]
ok to test

**Comment by jakirkham** [comment]
Thanks for the PR @anlavandier! 😄

Have a few questions.

Am curious, why this is being added `linalg`? Typically that contains things like matrix multiplication, determinant, eigen decomposition, etc. Convolution doesn't seem to fit there. Is there a reason to include it there as opposed to somewhere else?

Also normally (though not always) we try to follow the API/functionality that NumPy provides. Last I checked NumPy only had 1-D convolution and no N-D. Has that changed? Or is this meant to only be 1-D? Or is there a reason to deviate from NumPy/

Last we do have another implementation of [`convolve` in dask-image]( https://github.com/dask/dask-image/blob/aeff4d1c78d2bf17bf7cc0725c0a1c537c310cd9/dask_image/ndfilters/_conv.py#L16 ). Am curious if you tried using that? Do you have a sense of how this differs from that implementation?

**Comment by jakirkham** [comment]
cc @GenevieveBuckley (in case you have more thoughts here)

**Comment by GenevieveBuckley** [comment]
> Also normally (though not always) we try to follow the API/functionality that NumPy provides. Last I checked NumPy only had 1-D convolution and no N-D. Has that changed? Or is this meant to only be 1-D? Or is there a reason to deviate from NumPy/

Judging from [these imports](https://github.com/dask/dask/pull/8149/files#diff-e2be920ef18483a1045f9dfa4e0f4daa8d6835585566f5d00b7a576fa33a1f58R1626-R1627) and the title of the [earlier version of this PR](https://github.com/dask/dask/pull/8148), it looks like this is an implementation of the scipy.signal N-dimensional convolve. 

I agree, it's probably very confusing if functions in Dask do not mirror the numpy/pandas API. Historically, we've seen these sort of extensions made into separate packages (eg: dask-image extends scipy.ndimage, dask-xgboost extended XGBoost...)

> Last we do have another implementation of [`convolve` in dask-image](https://github.com/dask/dask-image/blob/aeff4d1c78d2bf17bf7cc0725c0a1c537c310cd9/dask_image/ndfilters/_conv.py#L16). Am curious if you tried using that? Do you have a sense of how this differs from that implementation?

Note: the convolve function in dask-image is based on the [scipy.ndimage.convolve](https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.convolve.html) function. I'm not as familiar with scipy's signal processing toolbox, so couldn't comment on the differences to scipy.signal convolve - perhaps @anlavandier can elaborate?

**Comment by anlavandier** [comment]
> Am curious, why this is being added `linalg`? Typically that contains things like matrix multiplication, determinant, eigen decomposition, etc. Convolution doesn't seem to fit there. Is there a reason to include it there as opposed to somewhere else?

There is no reason for why it was added in `linalg`, I didn't know where to put it and I knew convolution could be used in linear algebra so I just put it there. I am completely open to moving the function, and the test somewhere else if asked to. 

> Also normally (though not always) we try to follow the API/functionality that NumPy provides. Last I checked NumPy only had 1-D convolution and no N-D. Has that changed? Or is this meant to only be 1-D? Or is there a reason to deviate from NumPy/

> Last we do have another implementation of [`convolve` in dask-image](https://github.com/dask/dask-image/blob/aeff4d1c78d2bf17bf7cc0725c0a1c537c310cd9/dask_image/ndfilters/_conv.py#L16). Am curious if you tried using that? Do you have a sense of how this differs from that implementation?

The function is meant to be N-D and is indeed deviates from numpy's API, mostly because of personal needs. I was not aware of the existence of the dask-image repository nor the `convolve` function. 
After looking into `scipy.ndimage.convolve` it seems to me that the C file that powers the convolution is independent from `scipy.signal` but I could be mistaken. As far as differences, it looks to me that the the `scipy.ndimage` function does direct convolution with sums and not the FFT like `scipy.signal` does. Tests would have to be made but I expect this function to be slower than both `scipy.signal.fftconvolve` and `scipy.signal.oaconvolve` when the input size augments. 

The arguments also differ: 
* `scipy.signal` function's `mode` is used to determine the size of the output whereas `scipy.ndimage` use `mode` to work out boundary condition.
* There is no way to select axes in `scipy.ndimage`.

**Comment by anlavandier** [comment]
I found this [stackoverflow answer](http://stackoverflow.com/a/16121975/3079302) that explains the differences better than I could. 

> `scipy.signal.fftconvolve` does the convolution in the fft domain (where it's a simple multiplication). This is much faster in many cases, but can lead to very small differences in edge effects than the discrete case, and your data will be coerced into floating point with this particular implementation. Additionally, there's unnecessary memory usage when convolving a small array with a much larger array. All in all, fft-based methods can be dramatically faster, but there are some common use cases where `scipy.signal.fftconvolve` is not an ideal solution.

> \[...\] and `scipy.ndimage.convolve` all use a discrete convolution implemented in C \[...\]

> `scipy.ndimage.convolve` keeps the same data type, and gives you control over the location of the output to minimize memory usage. If you're convolving `uint8`'s (e.g. image data), it's often the best option. The output will always be the same shape as the first input array, which makes sense for images, but perhaps not for more general convolution. `ndimage.convolve` gives you a lot of control over how edge effects are handled through the `mode` kwarg (which functions completely differently than `scipy.signal`'s `mode` kwarg).

Side note: `scipy.signal.oaconvolve` also uses the fft but with the [overlap-add method](https://en.wikipedia.org/wiki/Overlap%E2%80%93add_method) so the same comments apply there.

**Comment by anlavandier** [comment]
Finally, regarding performances, I have found that for 1-D arrays, `scipy.ndimage.convolve` seems to have a linear complexity regarding kernel size which is not the case of the fft based implementations. I ran a small script on a Intel Xeon Gold 6230 20C @ 2.1GHz CPU and got these results:
Comparisons scipy 1-D
Script :
```from scipy.signal import fftconvolve,oaconvolve
from scipy.ndimage import convolve
import numpy as np 
import time


in10 = np.geomspace(10**2,10**5,100).astype(int)

in20 = [5,11,21,51,101,1001]

times = np.zeros((len(in10),len(in20),3))

for i in range(len(in10)):
    for j in range(len(in20)):
        in1 = np.random.rand(in10[i])
        in2 = np.random.rand(in20[j])
        t0 = time.time()
        a = convolve(in1,in2,mode ='constant',cval=0)
        times[i,j,0] = time.time() - t0
        t0 = time.time()
        b = fftconvolve(in1,in2,'same')
        times[i,j,1] = time.time() - t0
        t0 = time.time()
        c = oaconvolve(in1,in2,'same')
        times[i,j,2] = time.time() - t0

import matplotlib.pyplot as plt

fig = plt.figure(figsize = (13,4*(len(in20)+1)//2))
for j in range(len(in20)):
    ax = fig.add_subplot((len(in20)+1)//2,2,j+1)
    ax.plot(in10,times[:,j,0],label = 'ndimage.convolve')
    ax.plot(in10,times[:,j,1],label = 'fftconvolve')
    ax.plot(in10,times[:,j,2],label = 'oaconvolve')
    ax.set_title('kernel size : {}'.format(str(in20[j])))
    ax.set_xscale('log')
    ax.set_xlabel('input size (number of elements)')
    ax.set_ylabel('time (s)')
    ax.legend()
fig.suptitle("Comparison of scipy's convolution on 1D inputs and kernel")
fig.savefig('Comparisons scipy 1-D.png')
```

**Comment by GenevieveBuckley** [comment]
Thank you very much for the detailed responses @anlavandier, that's very helpful.

I expect the next step would be for some of the core team to have a discussion about what the scope of functionality provided by dask/dask-image/etc. should be.

**Comment by anlavandier** [comment]
Speaking of `dask_image.ndfilters.convolve`, I found a bug when the array had more than one chunk in the direction(s) of the convolution (_i.e_ the direction(s) where the shape of the kernel isn't equal to 1) and `mode = wrap`. [Here's the link to the issue](https://github.com/dask/dask-image/issues/242).

**Comment by jsignell** [comment]
Thanks for this work @anlavandier. In order to keep the scope of dask array tightly set to match numpy. We think it would be best to add this functionality to dask-image. This is similar to how the function that you are modeling this on is included in scipy rather than in numpy itself.

**Pull request closed without merging**
