### PR TITLE
update make-meta import in docs

### PR DESCRIPTION
**Pull request by quasiben**
- [ ] Closes #xxxx
- [ ] Tests added / passed
- [ ] Passes `black dask` / `flake8 dask` / `isort dask`

Small doc update to reflect new make_meta import 

cc @jakirkham @galipremsagar

### CODE REVIEW

**Review by jrbourbeau — APPROVED** [review]
Just to be clear, I think this might have been incorrect before https://github.com/dask/dask/pull/7586. For example, I get an `ImportError` with `from dask.dataframe import make_meta` on an older version of `dask` (2021.04.0), but `from dask.dataframe.utils import make_meta` works fine on 2021.04.0 and the current `main` branch

**Comment by jakirkham** [comment]
Sorry is the last version number in that statement meant to be `2021.05.0`?

**Comment by quasiben** [comment]
@jrbourbeau I think that's correct.  It was wrong before

**Comment by jrbourbeau** [comment]
> Sorry is the last version number in that statement meant to be 2021.05.0?

No, I chose `2021.04.0` as a stand-in for some older version of `dask`. I think this import was just wrong before -- thanks for fixing @quasiben

**Comment by jakirkham** [comment]
Ah sorry I didn't follow since `2021.04.0` was used twice. Anyways not important. Assuming I'm just missing something

**Pull request merged**
