### PR TITLE
Docs: Update kubernetes-helm.rst [skip ci]

### PR DESCRIPTION
**Pull request by farrajota**
This PR updates `kubernetes-helm.rst` with some improvements w.r.t. grammar and punctuation. Some additional words had to be inserted here and there, but nothing too drastic.

- [ ] Tests added / passed
- [ ] Passes `flake8 dask`

### CODE REVIEW

**Comment by jkmacc-LANL** [comment]
Should all links into Zero to Jupyterhub point to “latest?”  I found v0.4 to be less helpful than the current version.

**Comment by mrocklin** [comment]
Yes, I can imagine that pointing to latest or stable could have benefits.   I guess the challenge here is if future versions don't have those pages.

**Comment by jkmacc-LANL** [comment]
Is using Heptio (suggested in z2jh v0.4) really the recommendation, instead of what’s in “current”?  I’m happy to make a clarifying change.

**Comment by jkmacc-LANL** [comment]
(Should have mentioned, I’m referring specifically to the AWS instructions.)

**Comment by mrocklin** [comment]
> Is using Heptio (suggested in z2jh v0.4) really the recommendation, instead of what’s in “current”? 

No, we have no specific recommendation and instead prefer to refer to JupyterHub's docs.

I have objection to updating things as long as we have confidence that the link will remain valid for a while.

**Comment by mrocklin** [comment]
Correction: I have *no* objection to updating things as long as we have confidence that the link will remain valid for a while.

**Pull request merged**
