### PR TITLE
Update talks and presentations

### LINKED ISSUE #8344: Update Talks & Presentation page of docs
Currently, the Talks and Tutorials page of the docs is outdated (see https://docs.dask.org/en/stable/presentations.html)
We only have links up to 2019.
 
I'm opening this issue to start tracking some talks and tutorials that we want to include. Comment here with talks or tutorials that should be added to this page.

### PR DESCRIPTION
**Pull request by ncclementi**
- [x] Closes #8344
- [ ] Tests added / passed
- [x] Passes `pre-commit run --all-files`

I updated the content of the Talks and Tutorials page. I'm definitely missing talks and tutorials, but will look for more talks to add. 

EDIT: I took a deeper look at talks, and most of them are included in the links to Dask Summit playlists unless there are specific talks we want to highlight, I think this is ready.

### CODE REVIEW

**Review by jsignell — APPROVED** [review]
This is definitely an improvement over what we have.

**Comment by jsignell** [comment]
Yeah that looks like a sporadic failure, maybe anaconda.org was down for a second or something.

**Comment by jsignell** [comment]
Is this still WIP @ncclementi? I'd be happy to merge it and you can always add more later

**Comment by ncclementi** [comment]
@jsignell my bad I thought I changed the title. I think this is done, although I just merged main into this branch and we are having other failures, they seem to be unrelated though.

**Review by jrbourbeau — APPROVED** [review]

**Pull request merged**
