### PR TITLE
Fix resolve_aliases when multiple aliases are in graph

### PR DESCRIPTION
**Pull request by phofl**
- [ ] Closes #xxxx
- [ ] Tests added / passed
- [ ] Passes `pre-commit run --all-files`

cc @fjetter

### CODE REVIEW

**Review by fjetter — APPROVED** [review]

**Review by fjetter — CHANGES_REQUESTED** [review]
Well, there are a couple of related failures

test_persist_nested
test_futures_in_graph
test_futures_in_subgraphs

**Comment by fjetter** [comment]
Looks like dask.order is now picking up a cyclic dependency

**Comment by phofl** [comment]
Yeah they were all legit, Futures weren't handled properly because of another self-reference case. Should be better now

**Review by hendrikmakait — APPROVED** [review]
Thanks, @phofl! `test_filter_nonpartition_columns` appears to be unrelated (flaky?)

**Comment by phofl** [comment]
I've seen this one pop up before, yes.

**Pull request merged**
