### PR TITLE
ENH: Proposing to allow purity default set by user

### PR DESCRIPTION
**Pull request by ordirules**
This is a proposed API enhancement. I would find inheriting purity very convenient. This amounts to adding a new kwarg for `Delayed` objects, setting the `pure=None` as default and checking `if pure is None: pure=pure_default`.

This is kind of a continuation of the discussion in #2073.

Motivation is that I would like sub functions of classes to inherit purity. This would make life easier for us. I hope the code helps better outline what we want, and maybe you have better suggestions? I am not implying that I think this is good, mainly trying to open a better discussion to better my understanding.  Thanks as usual for the continued support :-)

```python
from dask import delayed

class class1:
    def __init__(self, a):
        self.a = a

    def get(self):
        return self.a

@delayed(pure_default=True)
def get_class_v1(cls, g):
    a = cls(g)
    return a

@delayed(pure=True)
def get_class_v2(cls, g):
    a = cls(g)
    return a

@delayed(pure=False)
def get_class_v3(cls, g):
    a = cls(g)
    return a

def test_class(func, cls,  num, version):

    a = func(cls, num)
    print("class {} instantiation key \t\t{}".format(version, a.key))

    a = func(cls, num)
    print("class {} instantiation key (again) \t{}".format(version, a.key))

    print("class {} member getattr key \t\t{}".format(version, a.get().key))
    print("class {} member getattr key (again) \t{}".format(version, a.get().key))

    print("computed result : {}".format(a.get().compute()))


test_class(get_class_v1, class1, 1, "v1")
test_class(get_class_v2, class1, 2, "v2")
test_class(get_class_v3, class1, 3, "v3")
```
Output:
```
class v1 instantiation key              get_class_v1-9c37603e911bdcb648b7955a2386899f
class v1 instantiation key (again)      get_class_v1-9c37603e911bdcb648b7955a2386899f
class v1 member getattr key             get-57697589615a90ec21c04baf483c6109
class v1 member getattr key (again)     get-57697589615a90ec21c04baf483c6109
computed result : 1
class v2 instantiation key              get_class_v2-9b5bb3fdd1b815d8305980906a4516ab
class v2 instantiation key (again)      get_class_v2-9b5bb3fdd1b815d8305980906a4516ab
class v2 member getattr key             get-d2211284-2daa-450a-99f5-6ac154856152
class v2 member getattr key (again)     get-78647ae3-640e-442c-a1c0-9cb0f27d50b9
computed result : 2
class v3 instantiation key              get_class_v3-60366fbf-3a6a-462d-8f17-f3a93834061a
class v3 instantiation key (again)      get_class_v3-a725e845-df3e-4e19-b24a-85730c637150
class v3 member getattr key             get-13a0ddaa-5a7b-45a1-acf4-60058954aa96
class v3 member getattr key (again)     get-f7721d96-8ed2-4a6f-ab14-272533487d0f
computed result : 3
```

In these three cases, `class1`'s `__init__` is pure, and so are all calls to its attributes.
In the case of `class2`, it's `__init__` is pure, but not subsequent calls to its attributes.
Finally, `class3` is never pure.

### CODE REVIEW

**Comment by mrocklin** [comment]
Thanks for the PR @ordirules .  I take it that https://github.com/dask/dask/pull/2084 wasn't sufficient for your needs?  If so I'm curious why.

We should probably discuss if we want to make this change first, but if we do then this PR will also need testing. 

cc @jcrist you're probably more up-to-date on this topic than I am.  Any thoughts?

**Comment by ordirules** [comment]
Sorry, I should have spent the time to understand why it's not working. The issue is that yes, `getattr` is now pure, but function calls still aren't. It seems this is more deeply embedded and that you'd have to keep track of purity somehow to allow a user to force purity. For example, here is where purity breaks:
```python
from dask import compute, delayed

@delayed(pure=True)
class MyClass:
    def __init__(self):
        pass

    def func(self, a, b):
        return a

# some made up parameters
a = 1
b = 2

# keys should not change
getfunc1 = MyClass().func
getfunc2 = MyClass().func
print("getattr : {}".format(getfunc1._key))
print("getattr again : {}".format(getfunc2._key))

call1 = getfunc1(a,b)
call2 = getfunc2(a,b)
print("getattr + func call : {}".format(call1._key))
print("getattr + func call again : {}".format(call2._key))


print("result 1 : {}".format(call1.compute()))
print("result 2 : {}".format(call2.compute()))
```
output is:
```
getattr : getattr-b52b850bf867517569a2f1cf182879c8
getattr again : getattr-b52b850bf867517569a2f1cf182879c8
getattr + func call : func-f8cd0ac7-0bc5-4d7a-9e55-6da71fc4ca93
getattr + func call again : func-aaae9b2d-84ad-4d06-8528-f6b5e080dbac
result 1 : 1
result 2 : 1
```

You see that the `getattr` call is fine, but not the function call. I would like to find some convenient means to force dask to assume that function calls after a specific function call are always pure. I understand it's potentially a mess (since children functions can receive as inputs dask functions that may not necessarily be pure).

Another solution is that we handle the purity bookkeeping ourselves, but for something like this, it can be messy, resulting in a lot of wrapper code. Perhaps though at this point it should be up to the user writing the pipeline to do this bookkeeping, to keep dask clean.

However, I still ask because I think this may be something not just myself may benefit from. I can see most pipelines being pure by definition (where the randomness is explicitly embedded into the input arguments, and sources and sinks written outside the task graph).

Let me know your thoughts. Thanks again for the input, it's much appreciated.

**Comment by jcrist** [comment]
The `delayed` decorator was written with functions not classes in mind. I'd rather not complicate this model, `delayed` already does a lot of things :).

The big question I have is, what are you trying to do here? In the current version, decorating a class will result in the constructor being lazy. Is this behavior desired? A different method might be to modify `delayed` to work as a method decorator (doesn't currently work). Then your class might look like:

```python
class Foo(object):
    @delayed(pure=True)
    def bar(self, a):
        ...
```

One downside of this approach is that `self` will be tokenized (our internal hashing implementation for generating keys) on every call. If this is expensive, then that can be problematic.

Alternatively, you can currently pass `pure=True` to any delayed call to make it pure/not pure for that call.

```
In [26]: f = MyClass()

In [27]: f.func(1, pure=True)
Out[27]: Delayed('func-60d4c564215b589839bf1a866a91e849')

In [28]: f.func(1, pure=True)
Out[28]: Delayed('func-60d4c564215b589839bf1a866a91e849')
```

---

One potential solution would be to switch the default of `pure` to `None`, and add it as an option in `set_options`. We'd then decide call purity as:

- If explicitly set to either `True` or `False`, always use that
- If not set, fallback to the global setting, if set
- If no global setting, then purity is `False`

Something like:

```python
dask.set_options(delayed_pure=True)   # Set globally
# Set in a context
with dask.set_options(delayed_pure=True):
    m = MyClass()
    r = m.func(1)   # This call is pure, since not explicitly set
    m.func(1, pure=False)   # This call is not pure, since explicitly set
```

One downside of this approach is that people might assume that setting `dask.set_options(pure=True)` at the top of a file makes all functions decorated with `delayed` pure. They're considered pure only as long as the global option is set, the call not the creation is what the global option indicates. To clarify:

```python
dask.set_options(delayed_pure=True)

# Use the default (falls back to global option)
@delayed
def foo(x):
    return x + 1

foo(1)  # This call is pure

dask.set_options(delayed_pure=False)

foo(2)  # This call is not pure
```

I think this could just be solved by documentation though, and think this is the best path forward. This keeps the definition simple:
- Objects don't have pure/deterministic behavior, function calls do.
- Function calls can be locally set to be pure with the `pure` keyword
- If not set, falls back to global setting

Would this be sufficient for your need?

**Comment by ordirules** [comment]
@jcrist thanks for the fairly quick reply. Yes, we'd like to generalize to classes. I think we'll keep testing the use of the class with your disclaimer in mind. The way we instantiate classes are with functions to be inserted into a pipeline in mind (so subsequent calls within class are assumed pure, i.e. all involved class parameters passed as arguments). We use the class approach to facilitate some pieces for the user (it just looks a little nicer that way). Worst case, we can add wrapper methods to satisfy dask's function requirement if need be. For example, we could use `partial` to freeze in some implicit class parameters, etc.
So I'm okay with not discussing classes anymore. Maybe if we have some good examples of how the API is improved with classes, I could present them in the future.

Just one aside question about the class. By coincidence, the hash seems to be deterministic from delaying the constructors (as is seen by the fact the keys are the same in the example above). I haven't had much time to read the code in detail but I thought some pieces were stripping away the `self` from the function call. If it's hashing `self`, is it safe to say that `self` will be deterministic? (i.e. won't have strings referring to memory addresses etc). The objects we create for the pipeline are purposely made light (and no large library dependencies etc, and they can be turned into `partial` functions). They can be easily turned into functions (but again, are more convenient as objects), so we would probably be okay with hashing `self` (on the criterion that it's deterministic).

As to the application, we have a running pipeline at a scientific beamline which is managed by some other API we've been working on (we've thought of using `airflow`, `celeri`, `luigi` but it didn't quite meet our needs). We're trying to use dask to distribute the computing and take care of real time caching. The saving and book keeping is taken into account by the API. (So we rely only on dask from delayed task graph to computation, but that's it. If instance crashes, we just lose the caching dask also provides.)

So although I'm testing delayed, I'm eventually implementing distributed. I should probably mention that. (I hope there aren't too many differences)

About the global setting, this is perfect. I think the possible confusion you raise is an important point but could be documented. Using `with` I think also helps emphasize the point. So I +1 this and think this will resolve our needs to date. However, we're as usual open to other ways (even if we have to do the work on our end, with the benefit of keeping dask cleaner)

This is a little long, so I'll summarize:
1. hashing on functions only is fine with us
2. hashing objects still seems deterministic anyway (hopefully this remains true :-) )
3. We're using this in a scientific pipeline, and the goal is to use distributed to distribute jobs
4. global setting is perfect

Thanks again for the discussion and support :-), and patience in reading my long message!

**Comment by ordirules** [comment]
superseded by #2178

**Pull request closed without merging**
