### PR TITLE
Register sizeof functions for Numba and RMM

### PR DESCRIPTION
**Pull request by jakirkham**
Makes sure that `sizeof` functions are registered for Numba `DeviceNDArray`s and RMM `DeviceBuffer`s.

- [ ] Tests added / passed
- [ ] Passes `black dask` / `flake8 dask`

### CODE REVIEW

**Comment by jakirkham** [comment]
@cjnolet, I don't know if this will fix the issue we saw today, but it's possible it might. Would you be able to test this and let me know? 🙂

**Comment by mrocklin** [comment]
It looks like black is slightly unhappy.  

Do we want to include tests for things like this?  I might defer to @jcrist for an unbiased opinion.

**Comment by jcrist** [comment]
Would testing this require GPU access? I don't have access to a GPU, and we don't on CI either, so I'm inclined to leave tests out unless it's likely they'll be run somewhere.

**Comment by jakirkham** [comment]
Yes both would require a GPU to test.

Leaving tests out would be my inclination as well. Though I don’t have strong feelings about this if they are desired.

**Comment by jakirkham** [comment]
I've pushed a fix for `black`. Please let me know if there is anything else 🙂

**Comment by jcrist** [comment]
This looks good to me, but I have no way to test it. @jakirkham if you've verified it fixes your issue feel free to merge.

**Comment by jakirkham** [comment]
Thanks all! Was able to run the following on a machine with a GPU using this change.

```python
In [1]: import dask                                                             

In [2]: import dask.sizeof                                                      

In [3]: import rmm                                                              

In [4]: import numba                                                            

In [5]: import numba.cuda                                                       

In [6]: rb = rmm.DeviceBuffer(size=10)                                          

In [7]: na = numba.cuda.device_array(shape=(10,), dtype="u1")                   

In [8]: dask.sizeof.sizeof(rb)                                                  
Out[8]: 10

In [9]: dask.sizeof.sizeof(na)                                                  
Out[9]: 10
```

**Pull request merged**
