### PR TITLE
Include compression in write_table call

### LINKED ISSUE #6496: `to_parquet` compression parameter seems to have no effect
```python
from dask.distributed import Client
import dask.dataframe as dd
client = Client(n_workers=1)

df = dd.read_parquet('path-to-file.parquet')
df.to_parquet('output.parquet', engine='pyarrow', compression='brotli', parition_on=[col])
```

**What happened**:

Choosing `gzip`, `snappy`, `brotli` or `lz4` compression options had no effect on the size of the created parquet file. In fact, the file created with the `to_parquet` method actually _inflated_ the size by a factor of 3 (from ~7GB to ~20GB). This leads me to suspect that, possibly, no compression is being used somehow? No errors or warnings get raised -- **even if `compression` is set to a nonsensical string**. 

I've tried using both `fastparquet` and `pyarrow` as the engine during writing.

Is there something obvious I'm missing?

**What you expected to happen**:
Expected the various compression settings to have an effect on the size of the output parquet file.

**Anything else we need to know?**:
The various compression settings _do_ appear to have an effect when using `pandas.DataFrame.to_parquet`, as well as when used with the `pyarrow.parquet` library. 

**Environment**:

- Dask version: 2.22.0
- Python version: 3.7.3
- Arrow version: 1.0.0
- Operating System: Manjaro Linux
- Install method (conda, pip, source): pip

### PR DESCRIPTION
**Pull request by jsignell**
- [ ] Tests added / passed
- [x] Passes `black dask` / `flake8 dask`
- [x] Fixes #6496 

@rjzamora - I am not sure if this is working properly - the file size doesn't appear to change when I use different compression mechanisms.

### CODE REVIEW

**Comment by jsignell** [comment]
or maybe @martindurant can help figure out what's going on...

**Comment by martindurant** [comment]
A good test would be to open one of the resultant files using pyarrow and check the compression in the metadata. File size will not necessarily change, it depends on the algorithm and the data.

**Comment by jsignell** [comment]
Thanks @martindurant! I ended up with:

```python
from dask.datasets import timeseries
import pyarrow.parquet as pq


ddf = timeseries(freq="1T")
ddf.to_parquet("output.parquet", engine="pyarrow", partition_on=["name"], compression="snappy")

dataset = pq.ParquetDataset('output.parquet')
rg = dataset.metadata.row_group(2)
rg.column(1).compression
```

```python
'SNAPPY'
```

So I think this PR is good to go! Unless you think it needs a test?

**Comment by martindurant** [comment]
Since you have the code right there, may as well make it a test (using a compression that is bound to be there, like GZIP)

**Comment by jsignell** [comment]
> Since you have the code right there, may as well make it a test (using a compression that is bound to be there, like GZIP)

yep added.

**Comment by martindurant** [comment]
OK :). I can't tell from the log if it actually ran, but should be good.

+1

**Pull request merged**
