### PR TITLE
Make sure that the divisions of the single partition merge is left

### LINKED ISSUE #8113: Incorrect divisions when doing an inner join between 2 1-partition dataframes
**What happened**:

When doing an inner join between 2 Dask DataFrames that both have 1 partition, the joined Dask Dataframe inherits the divisions from the right DF. This appears to be incorrect behavior when `on` is specified.

This problem was discovered when calling repartition() later on yielded an empty dataframe.

**What you expected to happen**:

The divisions field should be inherited from the left dataframe instead.

**Minimal Complete Verifiable Example**:

```python
import dask
import dask.dataframe as dd
import pandas as pd


df = pd.DataFrame({'a': ['a','b','c']}, index=[0,1,2])
ddf = dd.from_pandas(df, npartitions=1)

right_df = pd.DataFrame({'a': ['a','b','c'], 'b':[1.0, 2.0, 3.0]}).set_index('a')

print("Divisions before join", ddf.divisions)
ddf = ddf.join(right_df, how='inner', on='a')
print("Divisions after join", ddf.divisions)

print("Without repartition", dask.compute(ddf)[0])
print("With no-op repartition", dask.compute(ddf.repartition(divisions=ddf.divisions))[0])
```

The first & second print statements should print the same thing, and so should the third and fourth.

**Anything else we need to know?**:

Some initial investigation notes:
https://github.com/dask/dask/blob/main/dask/dataframe/multi.py#L391 is definitely the problematic area.
The most trivial fix for my particular case would be to swap the left and right if blocks, but that doesn't seem like the full solution.

Perhaps a better solution would be factoring in the `on` parameter(s) in the if statements

**Environment**:

- Dask version: 2021.8.1 (discovered on 2021.4.1)
- Python version: 3.8.8
- Operating System: Ubuntu Bionic
- Install method (conda, pip, source): pip

### PR DESCRIPTION
**Pull request by jsignell**
- [x] Closes #8113
- [x] Tests added / passed
- [x] Passes `black dask` / `flake8 dask` / `isort dask`

### CODE REVIEW

**Comment by jsignell** [comment]
Yikes pandas merge is way trickier than I had thought. Consider this:

```python
In [1]: import dask
   ...: import dask.dataframe as dd
   ...: import pandas as pd
   ...: 
   ...: 
   ...: df = pd.DataFrame({'a': ['a','b','c']}, ind
   ...: ex=[0, 4, 3])
   ...: 
   ...: right_df = pd.DataFrame({'a': ['a','b','c']
   ...: , 'b':[1.0, 2.0, 3.0]}).set_index('a')
   ...: 
   ...: df.join(right_df, on="a", how="inner")
Out[1]: 
   a    b
0  a  1.0
4  b  2.0
3  c  3.0

In [2]: df.merge(right_df, on="a", how="inner")
Out[2]: 
   a    b
0  a  1.0
1  b  2.0
2  c  3.0

In [3]: df.merge(right_df, left_on="a", right_index
   ...: =True, how="inner")
Out[3]: 
   a    b
0  a  1.0
4  b  2.0
3  c  3.0
```

I don't think the current tests do a good job of ensuring that the divisions are actually contained in the index. I am going to open a separate PR to try to make the tests more rigorous.

**Comment by jcrist** [comment]
What's the status of this Julia? Is this good, or is there additional work you needed to do here given your above comment?

**Comment by jsignell** [comment]
> What's the status of this Julia? Is this good, or is there additional work you needed to do here given your above comment?

I don't have a ton of confidence, but it is definitely wrong on main. So I guess we should merge and see if any bugs come up?

**Comment by jsignell** [comment]
I did not open a separate PR fwiw. I think it'll be easier once this is in.

**Comment by jcrist** [comment]
I confess I don't have a good enough understanding of this code to evaluate further. The new test looks good, all existing tests pass, and nothing looks glaringly bad in the PR. I'm happy to merge if you are.

**Pull request merged**
