### PR TITLE
 fixed typo in tsqr documentation and improved clarity

### PR DESCRIPTION
**Pull request by convexset**
=)

### CODE REVIEW

**Comment by mrocklin** [comment]
Thanks!  One thing, it looks like you have commits in this branch from earlier work.  You might want to rebase off of master.

**Comment by convexset** [comment]
Hmmmm could I get you to just paste this docstring in?
```
    """ Direct Tall-and-Skinny QR algorithm

    As presented in:

        A. Benson, D. Gleich, and J. Demmel.
        Direct QR factorizations for tall-and-skinny matrices in
        MapReduce architectures.
        IEEE International Conference on Big Data, 2013.
        http://arxiv.org/abs/1301.1071

    This algorithm is used to compute both the QR decomposition and the
    Singular Value Decomposition.  It requires that the input array have a
    single column of blocks, each of which fit in memory.

    Parameters
    ----------
    data: Array
    compute_svd: bool
        Whether to compute the SVD rather than the QR decomposition
    _max_vchunk_size: Integer
        Used internally in recursion to set the maximum row dimension
        of chunks in subsequent recursive calls.

    Notes
    -----
    With ``k`` blocks of size ``(m, n)``, this algorithm has memory use that
    scales as ``k * m * n``.

    The implementation here is the recursive variant due to the ultimate
    need for one "single core" QR decomposition. In the non-recursive version
    of the algorithm, given ``k`` blocks, after ``k`` ``m * n`` QR
    decompositions, there will be a "single core" QR decomposition that will
    have to work with a ``(k * n, n)`` matrix.

    Here, recursion is applied as necessary to ensure that ``k * n`` is not
    larger than ``m`` (if ``m / n >= 2``). In particular, this is done
    to ensure that single core computations do not have to work on blocks
    larger than ``(m, n)``.

    Where blocks are irregular, the above logic is applied with the "height" of
    the "tallest" block used in place of ``m``.

    Consider use of the ``rechunk`` method to control this behavior. Blocks
    that are as tall as possible are recommended.

    See Also
    --------
    dask.array.linalg.qr - Powered by this algorithm
    dask.array.linalg.svd - Powered by this algorithm
    dask.array.linalg.sfqr - Variant for short-and-fat arrays
    """
```

**Comment by mrocklin** [comment]
Mind if I force push to your branch?

**Comment by convexset** [comment]
Sure. (Sorry for the trouble. But on my end it's quite funny. Goes to show how clueless I am about how GitHub works.)

**Comment by mrocklin** [comment]
Force-pushed.

I recommend adjusting your master branch to track the dask fork exactly

```
git remote add dask git@github.com/dask/dask
git remote update dask
git checkout master
git reset --hard dask/master
```

Then whenever you start new work, base it off of master

```
git checkout master
git pull dask master
git checkout -b new-branch-name
... do work as normal
```

Ideally after a branch gets merged in you should never work off of that same branch in the future, but should always return to master.

**Comment by convexset** [comment]
I have an upstream remote pointing to dask/dask. Just got careless.

Regards,
Jeremy Chen

*To send private or confidential information, please do so via Telegram or
Signal.*

**Pull request merged**
