### PR TITLE
Support for Python 3.12

### PR DESCRIPTION
**Pull request by graingert**
- Blocked by https://github.com/dask/distributed/pull/8223

### CODE REVIEW

**Comment by graingert** [comment]
requires https://github.com/dask/distributed/pull/8223/files#diff-3b1a0d09b95e5e870b6962e81a2682ba3805afb0a134c642259b8162dd94e2acR220 to pass

**Comment by crusaderky** [comment]
@graingert there seems to be a genuine failure

**Comment by crusaderky** [comment]
@graingert also missing changes to pyproject.toml

**Comment by graingert** [comment]
`FAILED dask/array/tests/test_array_core.py::test_setitem_hardmask - AssertionError: {('array-ca2bfc119ac07031ee36eb791623951f',): 2}
assert not {('array-ca2bfc119ac07031ee36eb791623951f',): 2}` seems to fail every time on windows

**Review by jrbourbeau — APPROVED** [review]
Thanks @graingert

**Pull request merged**
