### PR TITLE
[DO NOT MERGE] Test pyarrow nightly in anticipation of pyarrow 4.0 release

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
Similarly as https://github.com/dask/dask/pull/7061, but for the upcoming pyarrow 4.0.0 release

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Hmm, in the windows build, it doesn't seem to update the pyarrow version (just no output: https://github.com/dask/dask/pull/7531/checks?check_run_id=2286836449#step:6:10). While I was specifically interested in testing windows here.

**Review by jrbourbeau — COMMENTED** [review]
Thanks for your efforts here @jorisvandenbossche. Just checking in, is there anything I can help with? It looks like the Windows builds are now installing the nightly version of `pyarrow` https://github.com/dask/dask/pull/7531/checks?check_run_id=2380736480#step:6:216. 

Also the `FutureWarning` from pandas being raised in the `upstream` build should be resolved in the `main` branch if you want to merge that into this PR

**Comment by jorisvandenbossche** [comment]
Ah, indeed, windows is now properly tested. 

> Also the FutureWarning from pandas being raised in the upstream build should be resolved in the main branch if you want to merge that into this PR

Yep, that's indeed not related to pyarrow. 

Nothing further needed here, I might just do another update tomorrow in case there is a new RC, otherwise all looking good here and will close this once the release is done.

**Comment by jorisvandenbossche** [comment]
(pyarrow 4.0 is now used in the main CI)

**Comment by jrbourbeau** [comment]
Thanks for tracking @jorisvandenbossche and congrats on the 4.0 release

**Pull request closed without merging**
