### PR TITLE
Use separate files for each DataFrame function and method

### LINKED ISSUE #7123: Request: Split up the Dataframe API documentation
The documentation page at https://docs.dask.org/en/latest/dataframe-api.html is difficult to use at this point. It takes my browser ~10 seconds to load the entire page and become responsive (or to scroll to the linked to content after loading). Finding anything on the page produces hundreds of entries for most search terms. 

I've tried just downloading the pdf instead from (https://docs.dask.org/_/downloads/en/latest/pdf/) but the TOC there only has three sections and is a bit hard to navigate. 

I love all the docs (seriously, thank you) they're just a bit hard to browse at the moment when I can't quite remember what the supported methods are on a dask object.

### PR DESCRIPTION
**Pull request by jsignell**
- [x] Closes #7123
- [x] Passes `black dask` / `flake8 dask` / `isort dask`

This copies the pattern that numpy and xarray use. You should be able to see the difference in load time https://dask--7890.org.readthedocs.build/en/7890/dataframe-api.html

### CODE REVIEW

**Review by jrbourbeau — COMMENTED** [review]
Thanks @jsignell, this looks great! A couple of questions that come to mind:

- Should we also update the [`clean` command in `docs/Makefile`](https://github.com/dask/dask/blob/7e231a17c04345f6f6cd66660db4a0df0f11b2ec/docs/Makefile#L42-L43) to also the `generated` directory? I'm not sure what sort of caching sphinx does here
- Does this change impact other projects which are using `intersphinx` to link to Dask API docs? I'm wondering if we need to add redirects for this, or if things will continue to work as is

**Comment by jsignell** [comment]
- Should we also update the [`clean` command in `docs/Makefile`](https://github.com/dask/dask/blob/7e231a17c04345f6f6cd66660db4a0df0f11b2ec/docs/Makefile#L42-L43) to also the `generated` directory? I'm not sure what sort of caching sphinx does here

Yes! 

- Does this change impact other projects which are using `intersphinx` to link to Dask API docs? I'm wondering if we need to add redirects for this, or if things will continue to work as is.

I'm not sure about that one, but I am tempted to take a merge and see approach.

**Comment by jsignell** [comment]
I'll look into make.bat tomorrow :(

**Comment by jsignell** [comment]
I tried to copy from xarray or numpy and neither of them have a make.bat. Now I'm wondering if we need it

**Comment by mrocklin** [comment]
This is great.  Two comments, neither of which are likely relevant:

1.  I tried building this locally with `make html` and found that links from the api index page didn't exist.  Probably an issue on my end, but I thought I'd bring it up
2. Probably we'll have a lot of broken links out there.  I'm totally fine just accepting this and moving on, unless there is a very easy solution
3. After this works, any interest in doing this for arrays and bags and futures as well?

**Comment by jrbourbeau** [comment]
> I'm not sure about that one, but I am tempted to take a merge and see approach

+1

> I tried building this locally with make html and found that links from the api index page didn't exist

Hmm, I'm not able to reproduce locally. You might try `make clean html`

**Comment by jsignell** [comment]
> 1. I tried building this locally with `make html` and found that links from the api index page didn't exist.  Probably an issue on my end, but I thought I'd bring it up

I'm wondering if you have an old sphinx version. According to the docs, this setting changed to true by default in 4.0 https://www.sphinx-doc.org/en/master/usage/extensions/autosummary.html#confval-autosummary_generate

> 3\. After this works, any interest in doing this for arrays and bags and futures as well?

Yep that's the plan!

**Comment by jrbourbeau** [comment]
Merged `main` to resolve the unrelated CI issues

**Comment by jsignell** [comment]
Merging!

**Comment by gerrymanoim** [comment]
This is amazing - tyvm!

**Comment by jsignell** [comment]
I took a look at cudf docs to see if external links are working( for instance dask.dataframe.reduction on [cudf docs](https://docs.rapids.ai/api/cudf/stable/dask-cudf.html?highlight=dask%20dataframe)). It looks like no - but I'm not sure if they will just start working once the docs page over there is rebuilt. @quasiben is it easy to trigger a build?

**Comment by jsignell** [comment]
nvmd Ben, I see that it's hardcoded over there. I'll open a PR.

**Comment by jrbourbeau** [comment]
This is great, thanks @jsignell! 

> Probably we'll have a lot of broken links out there. I'm totally fine just accepting this and moving on, unless there is a very easy solution

Looking at pandas' docs, it seems they were able to handle API redirect in a somewhat straightforward way using [sphinx `html_additional_pages`](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_additional_pages)

https://github.com/pandas-dev/pandas/blob/059c8bac51e47d6eaaa3e36d6a293a22312925e6/doc/source/conf.py#L332-L335

https://github.com/pandas-dev/pandas/blob/059c8bac51e47d6eaaa3e36d6a293a22312925e6/doc/_templates/api_redirect.html

**Comment by jsignell** [comment]
Yeah our case is slightly different because in our case we would want to redirect a link where all the information is stored in the anchor. So it'd be going from https://docs.dask.org/en/latest/array-api.html#dask.array.add to https://docs.dask.org/en/latest/generated/dask.array.add.html for instance. I am leaning towards not worrying too much about this.

**Pull request merged**
