### PR TITLE
Optimize cat

### PR DESCRIPTION
**Pull request by laliberte**
This provides a simple optimization where concatenate3 tasks can be merged if they are concatenating different slices of the same array.

### CODE REVIEW

**Comment by mrocklin** [comment]
Cool work @laliberte .  Because this PR is performance-conscious it would be good to see a couple of benchmarks for the kinds of computations with which it helps and also benchmarks on unrelated computations, to make sure that it doesn't negatively impact performance (array optimzations are sometimes bottlenecks)

**Comment by laliberte** [comment]
I've written this PR as part of a slightly larger project. I don't know if this is something that fits with your vision for dask but I think I've figured out a way to allow targets of array.core.store to be sliced dask arrays.
The use case is simple:
```
import h5py
import dask.array as da
source = da.from_array(h5py.File('source_file.h5', 'r')['x'], chunks=(1, 100, 100))
#e.g. source.shape = (1000, 10000, 10000)
dest = da.from_array(h5py.File('large_dest_file.h5', 'a')['x'], chunks=(1, 100, 100))
#e.g. dest.shape = (10000, 10000, 10000)
da.store(source, dest[:1000, ...])
```
This idea is to allow array.core.store to store to a subset of the destination array. At the moment it works well but it requires the `optimize_cat` PR.

Where should we go from here?

**Comment by mrocklin** [comment]
The problem with optimizations is that they get applied to all computations and can slow things down or introduce odd bugs.

If your goal is to support that particular use case then there might be more narrow changes that we can make to solve that need without having to affect all computations.

For example, perhaps `da.store` should take an extra argument that allows you to specify a certain sliced region within the target.

**Comment by laliberte** [comment]
My idea was to minimize options as much as possible and leverage dask internals.

What if I submit my `da.store` PR with the concatenation optimization but only apply the optimization in that narrow case? Then, in the future, the optimization could be benchmarked and added? Is this something that could make sense?

**Comment by mrocklin** [comment]
Adding a `region=` keyword to `da.store` seems simpler me.

**Comment by jcrist** [comment]
I agree with Matt on this one - optimization passes can interact in unexpected ways, increase overhead, and are much harder to maintain than an special purpose functions. In most cases it works out better to create the graph you want originally (in this case by adding an option to `da.store`) instead of trying to change it with optimizations later.

**Comment by laliberte** [comment]
That makes sense. I'll close the PR and resubmit a more targeted version.

Would any of you see any inconvenience if I was to keep the `optimize_concantenate` for my implementation but remove it from `optimize`?

**Pull request closed without merging**
