### PR TITLE
CI: Skip s3fs for 3.5

### PR DESCRIPTION
**Pull request by TomAugspurger**
cc @martindurant

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Taking a look at the pyyaml failures too.

**Comment by TomAugspurger** [comment]
Now we're failing on `pip install moto` trying to downgrade a previous install of pyyaml.

I'm going to take a bit of time right now to overhaul our environment creation.

**Comment by TomAugspurger** [comment]
>I'm going to take a bit of time right now to overhaul our environment creation.

This is going to take a bit of time. So for now I'm just removing s3fs / moto to get our CI going again. I'll follow up later today with the env cleanup.

**Comment by mrocklin** [comment]
It also looks like @martindurant might be able to resolve this short term
by supporting Python 3.5 in s3fs.  I think that he's also doing this at the
same time, so it might be ok to wait.

However, it's also not a bad idea to have one of our CI runs use s3fs
latest release rather than master in order to test continuity.

**Comment by TomAugspurger** [comment]
Just FYI, there are two issues right now. Martin's handling the s3fs one.

All our builds are failing because moto released 1.3.9 yesterday, which has
an exact pin of pyyaml to an older version. This triggers pip to do a
downgrade, which pip errors on.

**Comment by TomAugspurger** [comment]
@mrocklin Have you seen the distributed failure in https://ci.appveyor.com/project/daskdev/dask/builds/25664143#L1264?

```
Windows fatal exception: access violation
1265
```

in `test_distributed.py`. I think unrelated to this PR.

I may merge this, just to at least get travis passing again.

**Comment by TomAugspurger** [comment]
Merging. We should be able to trust travis's output until I get https://github.com/dask/dask/issues/5037 sorted out later today.

**Comment by mrocklin** [comment]
I have not seen that before, no

**Pull request merged**
