### PR TITLE
fix #4278

### LINKED ISSUE #4278: Support pytest 4 in test suite
If you run our test suite today with pytest four you'll notice that things fail.  They've been warning for a while because we've been using pytest markers in old ways.  If anyone wants to make a code contribution that doesn't involve much direct knowledge of Dask, switching our our tests to use markers correctly would be welcome.  

You can easily recreate these errors by installing `pytest==4` and then running our test suite.  See http://docs.dask.org/en/latest/develop.html#install and http://docs.dask.org/en/latest/develop.html#run-tests just below.

### PR DESCRIPTION
**Pull request by 515hikaru**
I made it possible to run a test with pytest==4.0.1(this version is latest now.)

related issue: #4278 

- [x] Tests added / passed
- [x] Passes `flake8 dask`

### CODE REVIEW

**Comment by mrocklin** [comment]
Thank you for starting this @515hikaru .  Are you interested in doing this same work for the other tests?  

You can get a list of all failing tests with by looking at the "Warnings Summary" in one of the [Travis CI logs](https://api.travis-ci.org/v3/job/465304656/log.txt).  You could also change the pytest version here:

https://github.com/dask/dask/blob/master/continuous_integration/travis/install.sh#L54

**Comment by 515hikaru** [comment]
@mrocklin: Thank you for your information. I want to fix other tests.

I will change pytest version when all tests fixed.

**Comment by 515hikaru** [comment]
I fixed all tests, and changed pytest version in travis job.

Although travis 3rd job fails, I have no idea about what is problem.It seems this issue is another one, is not it?

**Comment by mrocklin** [comment]
Yes, it's unrelated and being handled in #4276 .  Merging this now.  Thank you @515hikaru !

If you want to continue with this work the other Dask repositories like `dask/distributed` and `dask/dask-ml` probably also have this same problem.

I also notice that this is your first code contribution to this repository.  Welcome!

**Pull request merged**
