### PR TITLE
Remove AUTHORS.md [ci skip]

### PR DESCRIPTION
**Pull request by jcrist**
This hasn't been updated in years, and is a poor record of all the
contributors who have spent time submitting and reviewing PRs. Better to
just remove it and rely on git instead.

### CODE REVIEW

**Comment by jcrist** [comment]
Github contributors only list the top 100, and provide a minimal view of all the ways people may contribute. I'd rather be vague here and leave it as "dask is developed by the dask development team".

**Comment by mrocklin** [comment]
> I'd rather be vague here and leave it as "dask is developed by the dask development team".

Would this then replace the proposed text?  "The full author list is available using git" 

Sounds fine to me

**Comment by mrocklin** [comment]
I think that if we do point people towards git then we should probably point them to `git shortlog -ns` or something similar.

**Comment by mrocklin** [comment]
Or not, also happy with things as they are.  It's an improvement regardless.

**Comment by jcrist** [comment]
Done.

**Pull request merged**
