### PR TITLE
Un-``xfail`` ``test_categories`` with ``pyarrow`` strings and ``pyarrow>=12``

### PR DESCRIPTION
**Pull request by j-bennet**
https://github.com/apache/arrow/issues/33727 has been fixed in pyarrow via https://github.com/apache/arrow/pull/34289.

Already available in nightly, so this fixes a failure in pyarrow build.

- [x] Passes `pre-commit run --all-files`

### CODE REVIEW

**Review by jrbourbeau — APPROVED** [review]
Thanks @j-bennet!

**Comment by jrbourbeau** [comment]
Can we remove the `xfail` marker from `test_categories_unnamed_index` too? I see it's pointing to the same `arrow` issue

**Comment by j-bennet** [comment]
> Can we remove the `xfail` marker from `test_categories_unnamed_index` too? I see it's pointing to the same `arrow` issue

Checking.

**Comment by j-bennet** [comment]
> Can we remove the `xfail` marker from `test_categories_unnamed_index` too? I see it's pointing to the same `arrow` issue

Hmm, this one is actually failing in CI. It does not fail locally, but something is different in that `CategoricalDtype`, something that's not showing up in `repr`.

**Pull request merged**
