### PR TITLE
Add python 3.11 build to GPU CI

### PR DESCRIPTION
**Pull request by charlesbluca**
Contributes to https://github.com/rapidsai/dask-build-environment/issues/93

- [ ] Tests added / passed
- [ ] Passes `pre-commit run --all-files`

### CODE REVIEW

**Review by jrbourbeau — COMMENTED** [review]
Thanks @charlesbluca. Generally this sounds good to me. There are these errors showing up in CI though 

```
15:42:24 _________________ test_sort_values_tasks_backend[False-x-cudf] _________________
15:42:24 [gw2] linux -- Python 3.11.9 /opt/conda/envs/dask/bin/python3.11
15:42:24 
15:42:24 backend = 'cudf', by = 'x', ascending = False
15:42:24 
15:42:24     @pytest.mark.parametrize(
15:42:24         "backend", ["pandas", pytest.param("cudf", marks=pytest.mark.gpu)]
15:42:24     )
15:42:24     @pytest.mark.parametrize("by", ["x", "z", ["x", "z"], ["z", "x"]])
15:42:24     @pytest.mark.parametrize("ascending", [True, False])
15:42:24     def test_sort_values_tasks_backend(backend, by, ascending):
15:42:24         if backend == "cudf":
15:42:24 >           pytest.importorskip("dask_cudf")
15:42:24 E           pytest.PytestDeprecationWarning: 
15:42:24 E           Module 'dask_cudf' was found, but when imported by pytest it raised:
15:42:24 E               ImportError('libarrow.so.1600: cannot open shared object file: No such file or directory')
15:42:24 E           In pytest 9.1 this warning will become an error by default.
15:42:24 E           You can fix the underlying problem, or alternatively overwrite this behavior and silence this warning by passing exc_type=ImportError explicitly.
15:42:24 E           See [https://docs.pytest.org/en/stable/deprecations.html#pytest-importorskip-default-behavior-regarding-importerror](https://docs.pytest.org/en/stable/deprecations.html#pytest-importorskip-default-behavior-regarding-importerror%1B[0m)
15:42:24 
15:42:24 dask/dataframe/tests/test_shuffle.py:1602: PytestDeprecationWarning
```

**Comment by charlesbluca** [comment]
Hoping that with #11140 resolved this should be green

**Comment by jrbourbeau** [comment]
@charlesbluca it looks like maybe there's an issue with the Python 3.11 build -- could you take a look when you get a chance?

**Comment by charlesbluca** [comment]
rerun tests

**Comment by charlesbluca** [comment]
(mild suspicions that this is some intermittent issues with Jenkins so retrying to see if this is persistent)

**Comment by charlesbluca** [comment]
@jrbourbeau looks like the stalled test runs have completed 🙂 everything look good here to you?

**Review by jrbourbeau — APPROVED** [review]
Thanks for handling that @charlesbluca

**Pull request merged**
