### PR TITLE
Faster array tokenize()

### PR DESCRIPTION
**Pull request by pitrou**
Optionally uses fast hashing functions if available (the packages 'mmh3' or 'cityhash' need to be installed), falls back on SHA1.

The downside is that tokenize values can get different depending on the packages installed on the client.

### CODE REVIEW

**Comment by pitrou** [comment]
Some benchmarks:
* by default:
```
$ python -m timeit -s "from dask.base import tokenize; import numpy as np; a =np.ones((1000,1000))" "tokenize(a)"
100 loops, best of 3: 11.3 msec per loop
```
* after `pip install mmh3`:
```
$ python -m timeit -s "from dask.base import tokenize; import numpy as np; a =np.ones((1000,1000))" "tokenize(a)"
1000 loops, best of 3: 1.75 msec per loop
```
* after `pip install cityhash`:
```
$ python -m timeit -s "from dask.base import tokenize; import numpy as np; a =np.ones((1000,1000))" "tokenize(a)"
1000 loops, best of 3: 934 usec per loop
```

**Comment by pitrou** [comment]
I discovered a reference leak in cityhash, so in its current state it shouldn't be used:
https://github.com/escherba/python-cityhash/pull/16

**Comment by pitrou** [comment]
@mraspaud, you may want to try this PR.

**Comment by pitrou** [comment]
Also mmh3 shouldn't be used on data larger than 2**31 bytes currently: https://github.com/hajimes/mmh3/issues/10

**Comment by pitrou** [comment]
This PR makes the fancy indexing benchmark ~10% faster:
* before:
```
$ asv run --python=same -b Indexing
· Discovering benchmarks
· Running 1 total benchmarks (1 commits * 1 environments * 1 benchmarks)
[  0.00%] ·· Building for existing-py_home_antoine_miniconda3_envs_dask36_bin_python
[  0.00%] ·· Benchmarking existing-py_home_antoine_miniconda3_envs_dask36_bin_python
[100.00%] ··· Running array.FancyIndexing.time_fancy                                                                                                23.22ms
```
* after:
```
$ asv run --python=same -b Indexing
· Discovering benchmarks
· Running 1 total benchmarks (1 commits * 1 environments * 1 benchmarks)
[  0.00%] ·· Building for existing-py_home_antoine_miniconda3_envs_dask36_bin_python
[  0.00%] ·· Benchmarking existing-py_home_antoine_miniconda3_envs_dask36_bin_python
[100.00%] ··· Running array.FancyIndexing.time_fancy                                                                                                20.31ms
```

**Comment by mrocklin** [comment]
Merging this soon if there are no further comments

**Comment by jcrist** [comment]
Should we provide a way to specify what hash to use, perhaps in `set_options`?

```python
dask.set_options(tokenize_hash='mm3')  # use mm3, error if not available
dask.set_options(tokenize_hash=None)   # Use best available hash, default behavior
```

**Comment by pitrou** [comment]
I don't know. I'm viewing this more as an invisible optimization.

**Comment by mrocklin** [comment]
I'm inclined to just make this choice for the user until someone shows up who needs this.

**Comment by jcrist** [comment]
Fine be me.

**Comment by jakirkham** [comment]
> I'm inclined to just make this choice for the user until someone shows up who needs this.

Guess I'm the user showing up. 😄

Am interested in having reproducibility with the hashes. So would like to have some way to set which hash is used regardless of what options may be available now or in the future. @jcrist's proposal above seems reasonable. Any thoughts?

**Comment by mrocklin** [comment]
Seems fine to me

**Comment by jakirkham** [comment]
Raised as issue ( https://github.com/dask/dask/issues/2933 ).

**Pull request merged**
