### PR TITLE
Activate OS X builder on Travis-CI

### PR DESCRIPTION
**Pull request by pitrou**

### CODE REVIEW

**Comment by pitrou** [comment]
And for some reason, the build failed: https://travis-ci.org/dask/dask/builds/218509271

**Comment by pitrou** [comment]
Two blockers here:
* we need to find a way to install graphviz on the OS X builder (shouldn't be too hard, hopefully)
* OS X builds are *still* slow: the monthly backlog graph at https://www.traviscistatus.com looked encouraging, but that was really because the backlog was horrible at peak hours in the past, while it's simply large nowadays...

**Comment by mrocklin** [comment]
I think that the conda recipe for graphviz in defaults has improved.  It
might be worth trying.

If it slows down our ability to merge PRs I'm still comfortable waiting on
this.

**Comment by pitrou** [comment]
I've changed the OS X build to be marked "allow_failures". If I understand correctly, this should allow the whole build to be marked successful before the OS X build finishes.

**Comment by mrocklin** [comment]
This looks good to me.  Semi-relatedly, thoughts on removing some of the existing linux builds?  Perhaps the following:

```
    - PYTHON=3.6 NUMPY=1.11.2 PANDAS=0.19.2 COVERAGE='false' PARALLEL='true' TEST_IMPORTS='true' XTRATESTARGS=
    - PYTHON=2.7 NUMPY=1.11.0 PANDAS=0.19.2 COVERAGE='false' PARALLEL='true' TEST_IMPORTS='false' PYTHONOPTIMIZE=2 XTRATESTARGS=--ignore=dask/diagnostics 
```

**Comment by mrocklin** [comment]
Though obviously that doesn't have to happen here.  I'm +1 on this.  Thanks for going through the trouble.

**Comment by pitrou** [comment]
Yes, we have a lot of builds. Perhaps we don't need to test all those combinations...

**Pull request merged**
