### PR TITLE
Add note about `keep=False` in `drop_duplicates` docstring

### LINKED ISSUE #9334: Documentation for 'keep' argument to 'drop_duplicates' on dask dataframe and series
The documentation for `drop_duplicates` [for dask dataframes](https://docs.dask.org/en/stable/generated/dask.dataframe.DataFrame.drop_duplicates.html) and [for dask series](https://docs.dask.org/en/latest/generated/dask.dataframe.Series.drop_duplicates.html) says "(Not supported in Dask)" for the `keep` argument, but actually it seems to be implemented and seems to work fine when I've used it. It looks like it is just `keep=False` that is not impemented; `keep='first'` and `keep='last'` are working.

It would be good if either the docs reflected this or, if you're still not supposed to use `keep` because it might be buggy, then a warning/error when you do would be good.

### PR DESCRIPTION
**Pull request by jayeshmanani**
- [x] Closes #9334 
- [ ] Tests added / passed
- [x] Passes `pre-commit run --all-files`

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

Admins can comment `ok to test` to allow this one PR to run or `add to allowlist` to allow all future PRs from the same author to run.

**Review by jsignell — COMMENTED** [review]
Thanks for opening this PR! I think you should only put the information in one place though to avoid duplication.

image

https://dask--9887.org.readthedocs.build/en/9887/generated/dask.dataframe.DataFrame.drop_duplicates.html

**Comment by ncclementi** [comment]
@jayeshmanani Thanks you for the PR, I see @jsignell is already reviewing it. I'm answering the question you posted in the issue here since it is related to the PR.

>  As well as I think I also have to add something similar for the Series right?

`drop_duplicates` is defined on the `_Frame` supre-class and both `DataFrame` and `Series` inherit from it. This means that the implementation you are modifying is used for both dataframes and series.

 You can actually check, this in the docs generated from your PR. (at the bottom of the CI there is a docs/readthedocs that contains the docs built for your PR) but you can see that your changes have been applied to both DF and Series. 
 
 Dataframe: 
 https://dask--9887.org.readthedocs.build/en/9887/generated/dask.dataframe.DataFrame.drop_duplicates.html
 
 Series:
https://dask--9887.org.readthedocs.build/en/9887/generated/dask.dataframe.Series.drop_duplicates.html

**Comment by jayeshmanani** [comment]
> s defined on the `_Frame` supre-class and both `DataFrame` and `Series` inherit from it. This means that the implementation you are modifying is used for both dataframes and series.
> 
> You can actually check, this in the docs generated from your PR. (at the bottom of the CI there is a docs/readthedocs that contains the docs built for your PR) but you can see that your changes have been applied to both DF and Serie

Ah Okay, I see. thanks for the clarification. So no additional changes are needed other than those already suggested.

**Comment by jayeshmanani** [comment]
@jsignell I have committed the changes as you suggested, I think it is now good to go.

**Comment by jayeshmanani** [comment]
Any update on this? @jsignell can you check once if there is more improvement needed or not.

**Comment by jsignell** [comment]
Looks good! Sorry for the delay in merge.

**Pull request merged**
