### PR TITLE
Add `dask.base.optimize`

### PR DESCRIPTION
**Pull request by jcrist**
Adds a function for optimizing (but not computing) multiple collections simultaneously.

### CODE REVIEW

**Comment by jcrist** [comment]
Note that this function currently can't be added to the top-level namespace, because `distributed` is using a few functions in the `dask.optimize` namespace without explicitly importing them, which results in errors. This could be fixed in `distributed`, but the same issue may also exist in user code (although an argument could be made that users should have explicitly imported this namespace instead of relying on attribute access on `dask`). I also have an idea for a hack that would allow both, but it's gross and I'd rather not (unless it also came with a deprecation warning for users to fix their code).

I also didn't make this a class method like `compute`, since `optimize` may be a more common method name in numeric python, and adding a new method to `Delayed` objects seemed like it might shadow user methods. I may be overly cautious here though.

**Comment by jcrist** [comment]
This partially solves #3061. Still need to add keywords to not optimize in `to_delayed`, but then optimizing and getting delayed values would look like:

```python
a = da.arange(10, chunks=2).sum()
b = da.arange(10, chunks=2).mean()
delayed_a, delayed_b = (i.to_delayed(optimize_graph=False)
                        for i in dask.optimize(a, b))
```

cc @mrocklin ^^.

I believe this also solves #2472 (cc @jakirkham), as it makes the optimizations easier to call without computing.

**Comment by mrocklin** [comment]
In general this looks fine to me.  I apologize about the import issues with distributed.

I agree that @jakirkham might like to see this.

**Comment by jakirkham** [comment]
> I believe this also solves #2472 (cc @jakirkham), as it makes the optimizations easier to call without computing.

Indeed. This does look like it solves that issue. Thanks @jcrist. :)

**Comment by jcrist** [comment]
>  I also have an idea for a hack that would allow both, but it's gross and I'd rather not (unless it also came with a deprecation warning for users to fix their code).

I renamed `dask/optimize.py` to `dask/optimization.py`, and added deprecated versions in the old namespace. I also added attributes to the `dask.base.optimize` function that point towards the deprecated versions, which allowed adding the `optimize` function to the top-level namespace. This should be fully backwards compatible now.

**Comment by jcrist** [comment]
This could use a review on the deprecation strategy, but other than that I think this should be good to go. Planning on merging tomorrow evening if no comment.

**Comment by jakirkham** [comment]
This seems great to me.

I don't have strong feelings about the deprecation strategy (seems fine to me). Might be worth verifying the old names can still be imported (with a deprecation warning issued).

Otherwise will let others comment on the deprecation strategy if desired.

**Comment by jcrist** [comment]
Thanks for the review. 

> Might be worth verifying the old names can still be imported (with a deprecation warning issued).

The deprecation test already tests that the deprecated optimize methods are found both the `optimize` function and the deprecated `optimize` module, that they're the same, and that calling them raises a warning. See https://github.com/dask/dask/pull/3071/files#diff-9e6eab760e079b96110787ff076acfa5R630.

**Comment by jakirkham** [comment]
Ah sorry. Must have missed that before. LGTM.

**Pull request merged**
