### PR TITLE
Handle `return_stored` in `store` method correctly

### PR DESCRIPTION
**Pull request by jakirkham**
If `store` is returning the stored array loaded, then strip the length 1 tuple from the result to make it easier to work with. IOW return the Dask Array representing the stored result of the computation.

xref: https://github.com/dask/dask/pull/2980

### CODE REVIEW

**Comment by mrocklin** [comment]
Are there other cases where this should happen?  This could use a test.

**Comment by jakirkham** [comment]
Yep, just caught this when working on something else yesterday. So figured I'd add the PR real quick (even if incomplete).

Added a test. This covers all relevant cases with the method. Hope that answers your question. If not, please let me know.

**Comment by mrocklin** [comment]
Fine by me then

**Comment by jakirkham** [comment]
Thanks for taking a look. Should be ready to go if there is nothing else.

**Pull request merged**
